In [1]:
# =============================================================================
# KEYSTRA SOLUTION 4
# SUPPLY CHAIN RISK & OPERATIONAL RESILIENCE EARLY-WARNING SYSTEM
#
# STEP 0 — PERMANENT PROJECT STORAGE
# =============================================================================

from google.colab import drive
from pathlib import Path

print("=" * 80)
print("KEYSTRA — PROJECT INITIALIZATION")
print("=" * 80)

# -----------------------------------------------------------------------------
# 1. CONNECT GOOGLE DRIVE
# -----------------------------------------------------------------------------

drive.mount("/content/drive")

# -----------------------------------------------------------------------------
# 2. CREATE ONE PERMANENT KEYSTRA PROJECT DIRECTORY
# -----------------------------------------------------------------------------

KEYSTRA_ROOT = Path(
    "/content/drive/MyDrive/KEYSTRA_SOLUTION_4"
)

# -----------------------------------------------------------------------------
# 3. PROJECT SUBDIRECTORIES
# -----------------------------------------------------------------------------

DIRECTORIES = {
    "dimensions": KEYSTRA_ROOT / "01_dimensions",
    "bridges": KEYSTRA_ROOT / "02_bridges",
    "facts": KEYSTRA_ROOT / "03_facts",
    "labels": KEYSTRA_ROOT / "04_labels",
    "features": KEYSTRA_ROOT / "05_features",
    "models": KEYSTRA_ROOT / "06_models",
    "outputs": KEYSTRA_ROOT / "07_outputs",
    "validation": KEYSTRA_ROOT / "08_validation",
}

# Create directories
for directory in DIRECTORIES.values():
    directory.mkdir(parents=True, exist_ok=True)

# -----------------------------------------------------------------------------
# 4. DISPLAY PROJECT STRUCTURE
# -----------------------------------------------------------------------------

print("\n✓ Google Drive connected")
print(f"✓ Project root:\n  {KEYSTRA_ROOT}")

print("\nKEYSTRA PROJECT STRUCTURE")
print("-" * 80)

print("KEYSTRA_SOLUTION_4/")
for name in DIRECTORIES:
    print(f"├── {DIRECTORIES[name].name}/")

print("\n" + "=" * 80)
print("✓ KEYSTRA PERMANENT STORAGE INITIALIZED")
print("=" * 80)

================================================================================
KEYSTRA — PROJECT INITIALIZATION
================================================================================
Mounted at /content/drive

✓ Google Drive connected
✓ Project root:
  /content/drive/MyDrive/KEYSTRA_SOLUTION_4

KEYSTRA PROJECT STRUCTURE
--------------------------------------------------------------------------------
KEYSTRA_SOLUTION_4/
├── 01_dimensions/
├── 02_bridges/
├── 03_facts/
├── 04_labels/
├── 05_features/
├── 06_models/
├── 07_outputs/
├── 08_validation/

================================================================================
✓ KEYSTRA PERMANENT STORAGE INITIALIZED
================================================================================

In [2]:
# =============================================================================
# KEYSTRA SOLUTION 4
# STEP 1 — DIM_DATE
# =============================================================================

import pandas as pd
import numpy as np
from pathlib import Path

print("=" * 80)
print("KEYSTRA — DIM_DATE BUILD")
print("=" * 80)

# =============================================================================
# 1. LOCKED DATE PARAMETERS
# =============================================================================

START_DATE = pd.Timestamp("2022-01-01")
END_DATE   = pd.Timestamp("2026-07-31")

REFERENCE_DATE = END_DATE

# =============================================================================
# 2. GENERATE DAILY DATE DIMENSION
# =============================================================================

dates = pd.date_range(
    start=START_DATE,
    end=END_DATE,
    freq="D"
)

dim_date = pd.DataFrame({
    "Date": dates
})

# =============================================================================
# 3. DERIVED CALENDAR ATTRIBUTES
# =============================================================================

dim_date["Date_ID"] = dim_date["Date"].dt.strftime("%Y%m%d").astype(int)

dim_date["Year"] = dim_date["Date"].dt.year

dim_date["Quarter"] = dim_date["Date"].dt.quarter

dim_date["Month"] = dim_date["Date"].dt.month

dim_date["Month_Name"] = dim_date["Date"].dt.month_name()

dim_date["Month_Start_Date"] = (
    dim_date["Date"]
    .dt.to_period("M")
    .dt.to_timestamp()
)

dim_date["Month_End_Date"] = (
    dim_date["Date"]
    + pd.offsets.MonthEnd(0)
)

dim_date["Week"] = (
    dim_date["Date"]
    .dt.isocalendar()
    .week
    .astype(int)
)

dim_date["Day_of_Week"] = (
    dim_date["Date"]
    .dt.dayofweek + 1
)

dim_date["Day_Name"] = dim_date["Date"].dt.day_name()

dim_date["Is_Weekend"] = (
    dim_date["Date"].dt.dayofweek >= 5
).astype(int)

# =============================================================================
# 4. ORDER COLUMNS
# =============================================================================

dim_date = dim_date[
    [
        "Date_ID",
        "Date",
        "Year",
        "Quarter",
        "Month",
        "Month_Name",
        "Month_Start_Date",
        "Month_End_Date",
        "Week",
        "Day_of_Week",
        "Day_Name",
        "Is_Weekend",
    ]
].copy()

# =============================================================================
# 5. SORT
# =============================================================================

dim_date = dim_date.sort_values(
    "Date"
).reset_index(drop=True)

# =============================================================================
# 6. VALIDATION
# =============================================================================

print("\n" + "=" * 80)
print("KEYSTRA — DIM_DATE VALIDATION")
print("=" * 80)

# Row count
assert len(dim_date) == 1673, (
    f"Expected 1,673 rows, found {len(dim_date)}"
)

# Date boundaries
assert dim_date["Date"].min() == START_DATE
assert dim_date["Date"].max() == END_DATE

# Unique dates
assert dim_date["Date"].is_unique

# Unique Date_ID
assert dim_date["Date_ID"].is_unique

# No missing values in core fields
core_columns = [
    "Date_ID",
    "Date",
    "Year",
    "Quarter",
    "Month",
    "Month_Name",
    "Week",
    "Day_of_Week",
    "Day_Name",
    "Is_Weekend",
]

assert not dim_date[core_columns].isna().any().any()

# Date_ID consistency
expected_date_ids = (
    dim_date["Date"]
    .dt.strftime("%Y%m%d")
    .astype(int)
)

assert (
    dim_date["Date_ID"].values
    == expected_date_ids.values
).all()

# Chronological order
assert dim_date["Date"].is_monotonic_increasing

# Continuous daily sequence
date_differences = dim_date["Date"].diff().dropna()

assert (
    date_differences == pd.Timedelta(days=1)
).all()

# Quarter validity
assert dim_date["Quarter"].between(1, 4).all()

# Month validity
assert dim_date["Month"].between(1, 12).all()

# Day of week validity
assert dim_date["Day_of_Week"].between(1, 7).all()

# Weekend flag validity
expected_weekend = (
    dim_date["Date"].dt.dayofweek >= 5
).astype(int)

assert (
    dim_date["Is_Weekend"].values
    == expected_weekend.values
).all()

print(f"Rows                  : {len(dim_date):,}")
print(f"Columns               : {len(dim_date.columns)}")
print(f"Start Date            : {dim_date['Date'].min().date()}")
print(f"End Date              : {dim_date['Date'].max().date()}")
print(f"Unique Dates          : {dim_date['Date'].nunique():,}")
print(f"Unique Date IDs       : {dim_date['Date_ID'].nunique():,}")

print("✓ DATE RANGE VALID")
print("✓ DAILY CONTINUITY VALID")
print("✓ DATE_ID VALID")
print("✓ NO DUPLICATE DATES")
print("✓ NO MISSING CORE VALUES")
print("✓ CALENDAR ATTRIBUTES VALID")
print("✓ WEEKEND LOGIC VALID")

# =============================================================================
# 7. SAVE TO GOOGLE DRIVE
# =============================================================================

dim_date_path = DIRECTORIES["dimensions"] / "dim_date.parquet"

dim_date.to_parquet(
    dim_date_path,
    index=False
)

# =============================================================================
# 8. VERIFY PERSISTENT SAVE
# =============================================================================

assert dim_date_path.exists()
assert dim_date_path.stat().st_size > 0

# Reload test
dim_date_reload_test = pd.read_parquet(dim_date_path)

assert dim_date_reload_test.shape == dim_date.shape
assert list(dim_date_reload_test.columns) == list(dim_date.columns)

print("\n" + "=" * 80)
print("✓ DIM_DATE PASSED ALL VALIDATION CHECKS")
print("=" * 80)

print(f"✓ {len(dim_date):,} DATE ROWS CONFIRMED")
print("✓ 2022-01-01 → 2026-07-31 CONFIRMED")
print("✓ PERSISTENT FILE SAVED")
print(f"✓ SAVED TO: {dim_date_path}")
print("✓ RELOAD TEST PASSED")
print("=" * 80)

# Clean temporary reload object
del dim_date_reload_test

================================================================================
KEYSTRA — DIM_DATE BUILD
================================================================================

================================================================================
KEYSTRA — DIM_DATE VALIDATION
================================================================================
Rows                  : 1,673
Columns               : 12
Start Date            : 2022-01-01
End Date              : 2026-07-31
Unique Dates          : 1,673
Unique Date IDs       : 1,673
✓ DATE RANGE VALID
✓ DAILY CONTINUITY VALID
✓ DATE_ID VALID
✓ NO DUPLICATE DATES
✓ NO MISSING CORE VALUES
✓ CALENDAR ATTRIBUTES VALID
✓ WEEKEND LOGIC VALID

================================================================================
✓ DIM_DATE PASSED ALL VALIDATION CHECKS
================================================================================
✓ 1,673 DATE ROWS CONFIRMED
✓ 2022-01-01 → 2026-07-31 CONFIRMED
✓ PERSISTENT FILE SAVED
✓ SAVED TO: /content/drive/MyDrive/KEYSTRA_SOLUTION_4/01_dimensions/dim_date.parquet
✓ RELOAD TEST PASSED
================================================================================

In [3]:
# =============================================================================
# KEYSTRA SOLUTION 4
# DIM_ASSET — BUILD, VALIDATE & PERMANENT SAVE
# =============================================================================

import os
import pandas as pd

print("=" * 80)
print("KEYSTRA — DIM_ASSET BUILD")
print("=" * 80)

# -----------------------------------------------------------------------------
# 1. PERMANENT PROJECT PATH
# -----------------------------------------------------------------------------

PROJECT_ROOT = "/content/drive/MyDrive/KEYSTRA_SOLUTION_4"
DIMENSIONS_PATH = os.path.join(PROJECT_ROOT, "01_dimensions")

os.makedirs(DIMENSIONS_PATH, exist_ok=True)

DIM_ASSET_PATH = os.path.join(DIMENSIONS_PATH, "Dim_Asset.csv")


# -----------------------------------------------------------------------------
# 2. MASTER ASSET DATA
# -----------------------------------------------------------------------------

asset_data = [
    ["A001", "Offshore Platform A", "BU001", "Upstream",
     "Offshore Production", "Offshore", "Critical"],

    ["A002", "Offshore Platform B", "BU001", "Upstream",
     "Offshore Production", "Offshore", "Critical"],

    ["A003", "Offshore Platform C", "BU001", "Upstream",
     "Offshore Production", "Offshore", "Critical"],

    ["A004", "Pipeline Network Alpha", "BU002", "Midstream",
     "Pipeline", "Onshore", "High"],

    ["A005", "Pipeline Network Bravo", "BU002", "Midstream",
     "Pipeline", "Onshore", "High"],

    ["A006", "Gas Compression Station", "BU002", "Midstream",
     "Gas Compression", "Onshore", "Critical"],

    ["A007", "Gas Processing Plant", "BU002", "Midstream",
     "Gas Processing", "Onshore", "Critical"],

    ["A008", "Refinery Complex", "BU003", "Downstream",
     "Refining", "Onshore", "Critical"],

    ["A009", "Fuel Distribution Terminal", "BU003", "Downstream",
     "Fuel Distribution", "Onshore", "High"],

    ["A010", "LNG Export Terminal", "BU004", "LNG",
     "LNG Export", "Coastal", "Critical"],

    ["A011", "Solar Farm North", "BU005", "Renewables",
     "Solar", "Onshore", "High"],

    ["A012", "Solar Farm South", "BU005", "Renewables",
     "Solar", "Onshore", "High"],

    ["A013", "Wind Farm", "BU005", "Renewables",
     "Wind", "Onshore", "High"],
]


# -----------------------------------------------------------------------------
# 3. CREATE DIM_ASSET
# -----------------------------------------------------------------------------

columns = [
    "Asset_ID",
    "Asset_Name",
    "Business_Unit_ID",
    "Business_Unit_Name",
    "Asset_Type",
    "Location_Type",
    "Operational_Criticality"
]

dim_asset = pd.DataFrame(asset_data, columns=columns)


# -----------------------------------------------------------------------------
# 4. BASIC TYPE CLEANING
# -----------------------------------------------------------------------------

dim_asset = dim_asset.astype({
    "Asset_ID": "string",
    "Asset_Name": "string",
    "Business_Unit_ID": "string",
    "Business_Unit_Name": "string",
    "Asset_Type": "string",
    "Location_Type": "string",
    "Operational_Criticality": "string"
})


# -----------------------------------------------------------------------------
# 5. VALIDATION
# -----------------------------------------------------------------------------

print()
print("=" * 80)
print("KEYSTRA — DIM_ASSET VALIDATION")
print("=" * 80)

errors = []

# Expected row count
if len(dim_asset) != 13:
    errors.append(f"Expected 13 rows, found {len(dim_asset)}")

# Unique Asset_ID
if dim_asset["Asset_ID"].nunique() != 13:
    errors.append("Asset_ID is not unique")

# Expected Business Units
expected_business_units = {
    "BU001": "Upstream",
    "BU002": "Midstream",
    "BU003": "Downstream",
    "BU004": "LNG",
    "BU005": "Renewables"
}

actual_business_units = (
    dim_asset[["Business_Unit_ID", "Business_Unit_Name"]]
    .drop_duplicates()
    .set_index("Business_Unit_ID")["Business_Unit_Name"]
    .to_dict()
)

if actual_business_units != expected_business_units:
    errors.append("Business Unit mapping is incorrect")

# Required columns
expected_columns = [
    "Asset_ID",
    "Asset_Name",
    "Business_Unit_ID",
    "Business_Unit_Name",
    "Asset_Type",
    "Location_Type",
    "Operational_Criticality"
]

if list(dim_asset.columns) != expected_columns:
    errors.append("Column structure does not match specification")

# Null check
if dim_asset.isnull().any().any():
    errors.append("Null values detected")

# Duplicate rows
if dim_asset.duplicated().any():
    errors.append("Duplicate rows detected")

# Operational criticality
valid_criticality = {"Critical", "High"}

if not set(dim_asset["Operational_Criticality"]).issubset(valid_criticality):
    errors.append("Invalid Operational_Criticality value detected")

# Business Unit count
if dim_asset["Business_Unit_ID"].nunique() != 5:
    errors.append("Expected exactly 5 Business Units")

# Asset names unique
if dim_asset["Asset_Name"].nunique() != 13:
    errors.append("Asset_Name is not unique")

# Asset type check
if dim_asset["Asset_Type"].isna().any():
    errors.append("Missing Asset_Type values")

# Location check
valid_locations = {"Offshore", "Onshore", "Coastal"}

if not set(dim_asset["Location_Type"]).issubset(valid_locations):
    errors.append("Invalid Location_Type detected")


# -----------------------------------------------------------------------------
# 6. STOP IF VALIDATION FAILS
# -----------------------------------------------------------------------------

if errors:
    print()
    print("❌ DIM_ASSET VALIDATION FAILED")
    print("-" * 80)

    for error in errors:
        print(f"✗ {error}")

    raise ValueError(
        "Dim_Asset failed validation. DO NOT continue until the errors are fixed."
    )


# -----------------------------------------------------------------------------
# 7. DISPLAY VALIDATION SUMMARY
# -----------------------------------------------------------------------------

print(f"Rows                  : {len(dim_asset)}")
print(f"Columns               : {len(dim_asset.columns)}")
print(f"Unique Assets         : {dim_asset['Asset_ID'].nunique()}")
print(f"Business Units        : {dim_asset['Business_Unit_ID'].nunique()}")

print()
print("Assets per Business Unit:")
print(
    dim_asset.groupby(
        ["Business_Unit_ID", "Business_Unit_Name"]
    ).size()
)

print()
print("Operational Criticality:")
print(
    dim_asset["Operational_Criticality"].value_counts()
)

print()
print("Asset Type Distribution:")
print(
    dim_asset["Asset_Type"].value_counts()
)


# -----------------------------------------------------------------------------
# 8. PREVIEW
# -----------------------------------------------------------------------------

print()
print("DIM_ASSET PREVIEW:")
display(dim_asset)


# -----------------------------------------------------------------------------
# 9. SAVE PERMANENTLY TO GOOGLE DRIVE
# -----------------------------------------------------------------------------

dim_asset.to_csv(
    DIM_ASSET_PATH,
    index=False
)

print()
print("=" * 80)
print("PERMANENT SAVE")
print("=" * 80)

print(f"✓ Saved to:")
print(f"  {DIM_ASSET_PATH}")


# -----------------------------------------------------------------------------
# 10. VERIFY FILE EXISTS
# -----------------------------------------------------------------------------

if not os.path.exists(DIM_ASSET_PATH):
    raise FileNotFoundError(
        "Dim_Asset file was not found after saving."
    )

file_size = os.path.getsize(DIM_ASSET_PATH)

if file_size == 0:
    raise ValueError(
        "Dim_Asset file exists but is empty."
    )

print(f"✓ File exists")
print(f"✓ File size : {file_size:,} bytes")


# -----------------------------------------------------------------------------
# 11. RELOAD FROM DRIVE
# -----------------------------------------------------------------------------

dim_asset_check = pd.read_csv(
    DIM_ASSET_PATH,
    dtype="string"
)


# -----------------------------------------------------------------------------
# 12. POST-SAVE VERIFICATION
# -----------------------------------------------------------------------------

if len(dim_asset_check) != 13:
    raise ValueError(
        f"Reload verification failed: expected 13 rows, "
        f"found {len(dim_asset_check)}"
    )

if dim_asset_check["Asset_ID"].nunique() != 13:
    raise ValueError(
        "Reload verification failed: Asset_ID uniqueness changed."
    )

if list(dim_asset_check.columns) != expected_columns:
    raise ValueError(
        "Reload verification failed: column structure changed."
    )

print()
print("=" * 80)
print("POST-SAVE RELOAD VERIFICATION")
print("=" * 80)

print(f"✓ Reloaded successfully")
print(f"✓ Rows                  : {len(dim_asset_check)}")
print(f"✓ Unique Assets         : {dim_asset_check['Asset_ID'].nunique()}")
print(f"✓ Columns               : {len(dim_asset_check.columns)}")
print(f"✓ Permanent file verified")


# -----------------------------------------------------------------------------
# 13. FINAL STATUS
# -----------------------------------------------------------------------------

print()
print("=" * 80)
print("✓ DIM_ASSET PASSED ALL VALIDATION CHECKS")
print("=" * 80)

print("✓ 13 ASSETS CONFIRMED")
print("✓ 5 BUSINESS UNITS CONFIRMED")
print("✓ UNIQUE ASSET IDs CONFIRMED")
print("✓ BUSINESS UNIT MAPPINGS VALID")
print("✓ OPERATIONAL CRITICALITY VALID")
print("✓ ASSET TYPES VALID")
print("✓ LOCATION TYPES VALID")
print("✓ NO NULL VALUES")
print("✓ NO DUPLICATE ROWS")
print("✓ PERMANENTLY SAVED TO GOOGLE DRIVE")
print("✓ RELOAD VERIFICATION PASSED")
print("✓ DIM_ASSET LOCKED")
print("=" * 80)

================================================================================
KEYSTRA — DIM_ASSET BUILD
================================================================================

================================================================================
KEYSTRA — DIM_ASSET VALIDATION
================================================================================
Rows                  : 13
Columns               : 7
Unique Assets         : 13
Business Units        : 5

Assets per Business Unit:
Business_Unit_ID  Business_Unit_Name
BU001             Upstream              3
BU002             Midstream             4
BU003             Downstream            2
BU004             LNG                   1
BU005             Renewables            3
dtype: int64

Operational Criticality:
Operational_Criticality
Critical    7
High        6
Name: count, dtype: Int64

Asset Type Distribution:
Asset_Type
Offshore Production    3
Pipeline               2
Solar                  2
Gas Processing         1
Gas Compression        1
Refining               1
Fuel Distribution      1
LNG Export             1
Wind                   1
Name: count, dtype: Int64

DIM_ASSET PREVIEW:

,Asset_ID,Asset_Name,Business_Unit_ID,Business_Unit_Name,Asset_Type,Location_Type,Operational_Criticality
0,A001,Offshore Platform A,BU001,Upstream,Offshore Production,Offshore,Critical
1,A002,Offshore Platform B,BU001,Upstream,Offshore Production,Offshore,Critical
2,A003,Offshore Platform C,BU001,Upstream,Offshore Production,Offshore,Critical
3,A004,Pipeline Network Alpha,BU002,Midstream,Pipeline,Onshore,High
4,A005,Pipeline Network Bravo,BU002,Midstream,Pipeline,Onshore,High
5,A006,Gas Compression Station,BU002,Midstream,Gas Compression,Onshore,Critical
6,A007,Gas Processing Plant,BU002,Midstream,Gas Processing,Onshore,Critical
7,A008,Refinery Complex,BU003,Downstream,Refining,Onshore,Critical
8,A009,Fuel Distribution Terminal,BU003,Downstream,Fuel Distribution,Onshore,High
9,A010,LNG Export Terminal,BU004,LNG,LNG Export,Coastal,Critical
10,A011,Solar Farm North,BU005,Renewables,Solar,Onshore,High
11,A012,Solar Farm South,BU005,Renewables,Solar,Onshore,High
12,A013,Wind Farm,BU005,Renewables,Wind,Onshore,High

================================================================================
PERMANENT SAVE
================================================================================
✓ Saved to:
  /content/drive/MyDrive/KEYSTRA_SOLUTION_4/01_dimensions/Dim_Asset.csv
✓ File exists
✓ File size : 997 bytes

================================================================================
POST-SAVE RELOAD VERIFICATION
================================================================================
✓ Reloaded successfully
✓ Rows                  : 13
✓ Unique Assets         : 13
✓ Columns               : 7
✓ Permanent file verified

================================================================================
✓ DIM_ASSET PASSED ALL VALIDATION CHECKS
================================================================================
✓ 13 ASSETS CONFIRMED
✓ 5 BUSINESS UNITS CONFIRMED
✓ UNIQUE ASSET IDs CONFIRMED
✓ BUSINESS UNIT MAPPINGS VALID
✓ OPERATIONAL CRITICALITY VALID
✓ ASSET TYPES VALID
✓ LOCATION TYPES VALID
✓ NO NULL VALUES
✓ NO DUPLICATE ROWS
✓ PERMANENTLY SAVED TO GOOGLE DRIVE
✓ RELOAD VERIFICATION PASSED
✓ DIM_ASSET LOCKED
================================================================================

In [4]:
# =============================================================================
# KEYSTRA SOLUTION 4
# SUPPLY CHAIN RISK & OPERATIONAL RESILIENCE EARLY-WARNING SYSTEM
#
# STEP 3 — DIM_SUPPLIER
# STEP 4 — DIM_MATERIAL
#
# PERMANENT STORAGE VERSION
# =============================================================================
#
# LOCKED DESIGN
# ---------------------------------------------------------------------------
# 5 Business Units
# 13 Assets
# 90 Suppliers
# 60 Materials
# Analytical period: 2022-01-01 → 2026-07-31
#
# IMPORTANT:
# These are MASTER DATA dimensions.
# They must NOT contain predictive outcomes or supplier performance metrics.
#
# PERMANENT STORAGE:
# /content/drive/MyDrive/KEYSTRA_SOLUTION_4/01_dimensions/
#
# OUTPUTS:
#   Dim_Supplier.csv
#   Dim_Material.csv
#
# =============================================================================


import pandas as pd
import numpy as np
from pathlib import Path


# =============================================================================
# 1. KEYSTRA PERMANENT STORAGE
# =============================================================================

PROJECT_ROOT = Path(
    "/content/drive/MyDrive/KEYSTRA_SOLUTION_4"
)

DIMENSIONS_PATH = PROJECT_ROOT / "01_dimensions"

DIMENSIONS_PATH.mkdir(
    parents=True,
    exist_ok=True
)

print("=" * 80)
print("KEYSTRA — DIMENSION BUILD INITIALIZATION")
print("=" * 80)

print(f"Project Root : {PROJECT_ROOT}")
print(f"Dimensions   : {DIMENSIONS_PATH}")

assert PROJECT_ROOT.exists()
assert DIMENSIONS_PATH.exists()

print("\n✓ Permanent storage confirmed")


# =============================================================================
# 2. REPRODUCIBILITY
# =============================================================================

SEED = 42

rng = np.random.default_rng(SEED)

ANALYSIS_START = pd.Timestamp("2022-01-01")
ANALYSIS_END   = pd.Timestamp("2026-07-31")


# =============================================================================
# 3. BUSINESS UNIT STRUCTURE
# =============================================================================

business_units = {
    "BU001": "Upstream",
    "BU002": "Midstream",
    "BU003": "Downstream",
    "BU004": "LNG",
    "BU005": "Renewables"
}


# =============================================================================
# 4. SUPPLIER CATEGORY STRUCTURE
# =============================================================================

supplier_categories = {

    "Mechanical / Rotating Equipment": 15,

    "Electrical / Power Systems": 12,

    "Instrumentation / Control": 12,

    "Valves / Piping / Flow": 14,

    "Industrial / Process Consumables": 10,

    "Chemicals / Lubricants": 8,

    "Safety / PPE": 7,

    "Renewable Energy Equipment": 7,

    "Multi-category / Integrated Industrial": 5
}


# =============================================================================
# 5. SUPPLIER NAME POOLS
# =============================================================================

supplier_name_pools = {

    "Mechanical / Rotating Equipment": [
        "Apex Rotating Systems Ltd.",
        "Meridian Mechanical Technologies Ltd.",
        "Atlas Turbomachinery Services Ltd.",
        "Sterling Industrial Equipment Ltd.",
        "Northstar Mechanical Solutions Ltd.",
        "Crestline Rotating Equipment Ltd.",
        "Prime Industrial Machinery Ltd.",
        "Vector Mechanical Engineering Ltd.",
        "Ironbridge Equipment Solutions Ltd.",
        "Pinnacle Machinery Services Ltd.",
        "BluePeak Mechanical Systems Ltd.",
        "Summit Rotating Technologies Ltd.",
        "Westfield Industrial Engineering Ltd.",
        "Orion Machinery & Engineering Ltd.",
        "Grandview Mechanical Systems Ltd."
    ],

    "Electrical / Power Systems": [
        "GridCore Power Systems Ltd.",
        "VoltEdge Engineering Ltd.",
        "Crown Electrical Technologies Ltd.",
        "Powerlink Industrial Systems Ltd.",
        "Electra Grid Solutions Ltd.",
        "PrimeVolt Engineering Services Ltd.",
        "Northbridge Power Equipment Ltd.",
        "Arcstone Electrical Systems Ltd.",
        "Enertech Power Solutions Ltd.",
        "Brightline Electrical Industries Ltd.",
        "VectorGrid Technologies Ltd.",
        "Westbridge Power Systems Ltd."
    ],

    "Instrumentation / Control": [
        "Precision Control Technologies Ltd.",
        "SignalWorks Instrumentation Ltd.",
        "Axis Process Controls Ltd.",
        "Integra Automation Systems Ltd.",
        "ClearPoint Instrumentation Ltd.",
        "ProSense Industrial Controls Ltd.",
        "NexControl Engineering Ltd.",
        "Advanced Process Instruments Ltd.",
        "ControlSphere Technologies Ltd.",
        "Meridian Automation Solutions Ltd.",
        "OptiSense Systems Ltd.",
        "CoreLogic Instrumentation Ltd."
    ],

    "Valves / Piping / Flow": [
        "FlowGuard Industrial Ltd.",
        "Apex Valve Technologies Ltd.",
        "Pipeline Dynamics Ltd.",
        "HydroFlow Engineering Ltd.",
        "Precision Valve Systems Ltd.",
        "PrimeFlow Industrial Solutions Ltd.",
        "IronGate Piping Systems Ltd.",
        "DeltaFlow Technologies Ltd.",
        "Streamline Valve & Piping Ltd.",
        "FlowTech Engineering Services Ltd.",
        "Westline Piping Solutions Ltd.",
        "BlueRiver Flow Systems Ltd.",
        "HighPoint Valve Engineering Ltd.",
        "Continental Piping Technologies Ltd."
    ],

    "Industrial / Process Consumables": [
        "Industrial Supply Partners Ltd.",
        "Process Materials Solutions Ltd.",
        "ProServe Industrial Supplies Ltd.",
        "CoreProcess Materials Ltd.",
        "Nexus Industrial Supply Ltd.",
        "Westbridge Process Supplies Ltd.",
        "PrimeSource Industrial Ltd.",
        "MetroProcess Supplies Ltd.",
        "Reliable Industrial Materials Ltd.",
        "General Process Solutions Ltd."
    ],

    "Chemicals / Lubricants": [
        "PetroChem Solutions Ltd.",
        "LubriTech Industrial Ltd.",
        "ChemCore Process Materials Ltd.",
        "Apex Industrial Chemicals Ltd.",
        "PrimeLube Energy Services Ltd.",
        "WestAfrica Chemical Solutions Ltd.",
        "Advanced Lubricants & Chemicals Ltd.",
        "ProcessChem Technologies Ltd."
    ],

    "Safety / PPE": [
        "SafeGuard Industrial Supplies Ltd.",
        "ProShield Safety Systems Ltd.",
        "Guardian PPE Solutions Ltd.",
        "WorkSafe Industrial Ltd.",
        "Sentinel Safety Equipment Ltd.",
        "SureSafe Protective Solutions Ltd.",
        "SafetyFirst Industrial Supplies Ltd."
    ],

    "Renewable Energy Equipment": [
        "SolarEdge Industrial Energy Ltd.",
        "GreenPeak Renewable Systems Ltd.",
        "SunCore Energy Technologies Ltd.",
        "RenewPower Engineering Ltd.",
        "HelioGrid Solutions Ltd.",
        "EcoVolt Renewable Equipment Ltd.",
        "WindSun Energy Systems Ltd."
    ],

    "Multi-category / Integrated Industrial": [
        "Integrated Energy Supply Solutions Ltd.",
        "Continental Industrial Services Ltd.",
        "Prime Integrated Engineering Ltd.",
        "Nexus Energy Equipment Solutions Ltd.",
        "Frontier Industrial Technologies Ltd."
    ]
}


# =============================================================================
# 6. SUPPLIER REGIONS
# =============================================================================

regions = [
    "Nigeria",
    "West Africa",
    "Europe",
    "Middle East",
    "Asia",
    "North America"
]

region_weights = [
    0.42,
    0.14,
    0.15,
    0.10,
    0.12,
    0.07
]


# =============================================================================
# 7. SUPPLIER SIZE
# =============================================================================

supplier_sizes = [
    "Large Enterprise",
    "Mid-size",
    "Specialist SME"
]

size_weights = [
    0.30,
    0.45,
    0.25
]


# =============================================================================
# 8. BASELINE LEAD-TIME RANGES
# =============================================================================

lead_time_ranges = {

    "Mechanical / Rotating Equipment":
        (30, 120),

    "Electrical / Power Systems":
        (21, 90),

    "Instrumentation / Control":
        (14, 75),

    "Valves / Piping / Flow":
        (21, 90),

    "Industrial / Process Consumables":
        (7, 35),

    "Chemicals / Lubricants":
        (5, 30),

    "Safety / PPE":
        (5, 25),

    "Renewable Energy Equipment":
        (30, 150),

    "Multi-category / Integrated Industrial":
        (20, 100)
}


# =============================================================================
# 9. PRIMARY BUSINESS UNIT LOGIC
# =============================================================================

primary_bu_weights = {

    "Mechanical / Rotating Equipment":
        [0.35, 0.25, 0.25, 0.10, 0.05],

    "Electrical / Power Systems":
        [0.15, 0.15, 0.25, 0.10, 0.35],

    "Instrumentation / Control":
        [0.30, 0.20, 0.25, 0.15, 0.10],

    "Valves / Piping / Flow":
        [0.25, 0.35, 0.25, 0.10, 0.05],

    "Industrial / Process Consumables":
        [0.20, 0.25, 0.30, 0.10, 0.15],

    "Chemicals / Lubricants":
        [0.20, 0.30, 0.35, 0.10, 0.05],

    "Safety / PPE":
        [0.20, 0.20, 0.30, 0.10, 0.20],

    "Renewable Energy Equipment":
        [0.05, 0.10, 0.10, 0.10, 0.65],

    "Multi-category / Integrated Industrial":
        [0.20, 0.20, 0.25, 0.15, 0.20]
}

bu_ids = list(business_units.keys())


# =============================================================================
# 10. CREATE DIM_SUPPLIER
# =============================================================================

supplier_rows = []

supplier_number = 1

for category, count in supplier_categories.items():

    min_lead, max_lead = lead_time_ranges[category]

    names = supplier_name_pools[category]

    assert len(names) == count, (
        f"{category} requires {count} names "
        f"but {len(names)} were supplied."
    )

    for i in range(count):

        supplier_id = f"S{supplier_number:03d}"

        supplier_name = names[i]

        region = rng.choice(
            regions,
            p=region_weights
        )

        supplier_size = rng.choice(
            supplier_sizes,
            p=size_weights
        )

        baseline_lead_time = int(
            rng.integers(
                min_lead,
                max_lead + 1
            )
        )

        strategic_tier = rng.choice(
            [
                "Strategic",
                "Preferred",
                "Standard"
            ],
            p=[
                0.20,
                0.35,
                0.45
            ]
        )

        primary_business_unit = rng.choice(
            bu_ids,
            p=primary_bu_weights[category]
        )

        active_from = ANALYSIS_START

        supplier_status = "Active"

        supplier_rows.append({

            "Supplier_ID":
                supplier_id,

            "Supplier_Name":
                supplier_name,

            "Supplier_Category":
                category,

            "Region":
                region,

            "Supplier_Size":
                supplier_size,

            "Strategic_Tier":
                strategic_tier,

            "Baseline_Lead_Time":
                baseline_lead_time,

            "Primary_Business_Unit":
                primary_business_unit,

            "Active_From":
                active_from,

            "Supplier_Status":
                supplier_status
        })

        supplier_number += 1


# =============================================================================
# 11. BUILD DIM_SUPPLIER
# =============================================================================

dim_supplier = pd.DataFrame(
    supplier_rows
)


# =============================================================================
# 12. SUPPLIER REQUIRED COLUMNS
# =============================================================================

supplier_required_columns = [

    "Supplier_ID",
    "Supplier_Name",
    "Supplier_Category",
    "Region",
    "Supplier_Size",
    "Strategic_Tier",
    "Baseline_Lead_Time",
    "Primary_Business_Unit",
    "Active_From",
    "Supplier_Status"
]

dim_supplier = dim_supplier[
    supplier_required_columns
]


# =============================================================================
# 13. DIM_SUPPLIER VALIDATION
# =============================================================================

assert len(dim_supplier) == 90

assert dim_supplier["Supplier_ID"].nunique() == 90

assert dim_supplier["Supplier_Name"].nunique() == 90

expected_supplier_ids = [
    f"S{i:03d}" for i in range(1, 91)
]

assert sorted(
    dim_supplier["Supplier_ID"].tolist()
) == expected_supplier_ids

assert (
    dim_supplier[supplier_required_columns]
    .notna()
    .all()
    .all()
)

assert (
    dim_supplier["Baseline_Lead_Time"] > 0
).all()

assert set(
    dim_supplier["Region"]
).issubset(set(regions))

assert set(
    dim_supplier["Supplier_Size"]
).issubset({
    "Large Enterprise",
    "Mid-size",
    "Specialist SME"
})

assert set(
    dim_supplier["Strategic_Tier"]
).issubset({
    "Strategic",
    "Preferred",
    "Standard"
})

assert set(
    dim_supplier["Primary_Business_Unit"]
).issubset(
    set(business_units.keys())
)

assert set(
    dim_supplier["Supplier_Status"]
).issubset({
    "Active",
    "Inactive"
})


# =============================================================================
# 14. SUPPLIER LEAKAGE CHECK
# =============================================================================

supplier_forbidden_columns = [

    "Supplier_Risk_Score",
    "Risk_Score",
    "Risk_Tier",
    "Failure_Label",
    "Failure_State",
    "Deterioration_State",
    "OTD",
    "On_Time_Delivery",
    "Fulfilment_Rate",
    "Quality_Rate",
    "Quality_Event_Rate",
    "Days_Late",
    "Outstanding_PO_Value",
    "Failure_Type"
]

for column in supplier_forbidden_columns:

    assert column not in dim_supplier.columns


# =============================================================================
# 15. SUPPLIER CATEGORY VALIDATION
# =============================================================================

actual_supplier_categories = (
    dim_supplier["Supplier_Category"]
    .value_counts()
    .to_dict()
)

assert actual_supplier_categories == supplier_categories


# =============================================================================
# 16. MATERIAL DEFINITIONS
# =============================================================================

material_definitions = [

    # CRITICAL ---------------------------------------------------------------

    {
        "Material_ID": "M001",
        "Material_Name": "Gas Turbine Rotor Assembly",
        "Category": "Mechanical / Rotating Equipment",
        "Criticality_Tier": "Critical",
        "Unit_of_Measure": "EA",
        "Cost_Range": (250000, 650000),
        "Lead_Range": (90, 180),
        "Demand_Profile": "Low",
        "Sourcing_Type": "Single-source"
    },

    {
        "Material_ID": "M002",
        "Material_Name": "Gas Compressor Dry Gas Seal",
        "Category": "Mechanical / Rotating Equipment",
        "Criticality_Tier": "Critical",
        "Unit_of_Measure": "EA",
        "Cost_Range": (45000, 150000),
        "Lead_Range": (60, 150),
        "Demand_Profile": "Low",
        "Sourcing_Type": "Single-source"
    },

    {
        "Material_ID": "M003",
        "Material_Name": "High-Pressure Emergency Shutdown Valve",
        "Category": "Valves / Piping / Flow",
        "Criticality_Tier": "Critical",
        "Unit_of_Measure": "EA",
        "Cost_Range": (25000, 95000),
        "Lead_Range": (60, 140),
        "Demand_Profile": "Low",
        "Sourcing_Type": "Single-source"
    },

    {
        "Material_ID": "M004",
        "Material_Name": "Offshore Power Transformer",
        "Category": "Electrical / Power Systems",
        "Criticality_Tier": "Critical",
        "Unit_of_Measure": "EA",
        "Cost_Range": (180000, 550000),
        "Lead_Range": (90, 180),
        "Demand_Profile": "Low",
        "Sourcing_Type": "Single-source"
    },

    {
        "Material_ID": "M005",
        "Material_Name": "Safety Instrumented System Controller",
        "Category": "Instrumentation / Control",
        "Criticality_Tier": "Critical",
        "Unit_of_Measure": "EA",
        "Cost_Range": (35000, 120000),
        "Lead_Range": (45, 120),
        "Demand_Profile": "Low",
        "Sourcing_Type": "Single-source"
    },

    {
        "Material_ID": "M006",
        "Material_Name": "Subsea Control Module",
        "Category": "Instrumentation / Control",
        "Criticality_Tier": "Critical",
        "Unit_of_Measure": "EA",
        "Cost_Range": (100000, 350000),
        "Lead_Range": (90, 180),
        "Demand_Profile": "Low",
        "Sourcing_Type": "Single-source"
    },

    {
        "Material_ID": "M007",
        "Material_Name": "Critical Process Pump Cartridge",
        "Category": "Mechanical / Rotating Equipment",
        "Criticality_Tier": "Critical",
        "Unit_of_Measure": "EA",
        "Cost_Range": (30000, 110000),
        "Lead_Range": (60, 130),
        "Demand_Profile": "Medium",
        "Sourcing_Type": "Dual-source"
    },

    {
        "Material_ID": "M008",
        "Material_Name": "Medium-Voltage Switchgear Breaker",
        "Category": "Electrical / Power Systems",
        "Criticality_Tier": "Critical",
        "Unit_of_Measure": "EA",
        "Cost_Range": (25000, 90000),
        "Lead_Range": (45, 120),
        "Demand_Profile": "Low",
        "Sourcing_Type": "Dual-source"
    },

    {
        "Material_ID": "M009",
        "Material_Name": "Turbine Generator Excitation Module",
        "Category": "Electrical / Power Systems",
        "Criticality_Tier": "Critical",
        "Unit_of_Measure": "EA",
        "Cost_Range": (40000, 140000),
        "Lead_Range": (60, 150),
        "Demand_Profile": "Low",
        "Sourcing_Type": "Single-source"
    },

    {
        "Material_ID": "M010",
        "Material_Name": "High-Integrity Pressure Protection Valve",
        "Category": "Valves / Piping / Flow",
        "Criticality_Tier": "Critical",
        "Unit_of_Measure": "EA",
        "Cost_Range": (30000, 100000),
        "Lead_Range": (60, 140),
        "Demand_Profile": "Low",
        "Sourcing_Type": "Dual-source"
    },


    # HIGH -------------------------------------------------------------------

    {
        "Material_ID": "M011",
        "Material_Name": "Centrifugal Process Pump",
        "Category": "Mechanical / Rotating Equipment",
        "Criticality_Tier": "High",
        "Unit_of_Measure": "EA",
        "Cost_Range": (12000, 55000),
        "Lead_Range": (35, 90),
        "Demand_Profile": "Medium",
        "Sourcing_Type": "Dual-source"
    },

    {
        "Material_ID": "M012",
        "Material_Name": "Industrial Electric Motor",
        "Category": "Electrical / Power Systems",
        "Criticality_Tier": "High",
        "Unit_of_Measure": "EA",
        "Cost_Range": (8000, 40000),
        "Lead_Range": (30, 75),
        "Demand_Profile": "Medium",
        "Sourcing_Type": "Multi-source"
    },

    {
        "Material_ID": "M013",
        "Material_Name": "Control Valve Actuator",
        "Category": "Valves / Piping / Flow",
        "Criticality_Tier": "High",
        "Unit_of_Measure": "EA",
        "Cost_Range": (5000, 25000),
        "Lead_Range": (30, 75),
        "Demand_Profile": "Medium",
        "Sourcing_Type": "Dual-source"
    },

    {
        "Material_ID": "M014",
        "Material_Name": "Pressure Control Valve",
        "Category": "Valves / Piping / Flow",
        "Criticality_Tier": "High",
        "Unit_of_Measure": "EA",
        "Cost_Range": (7000, 30000),
        "Lead_Range": (30, 80),
        "Demand_Profile": "Medium",
        "Sourcing_Type": "Dual-source"
    },

    {
        "Material_ID": "M015",
        "Material_Name": "Industrial Variable Frequency Drive",
        "Category": "Electrical / Power Systems",
        "Criticality_Tier": "High",
        "Unit_of_Measure": "EA",
        "Cost_Range": (6000, 28000),
        "Lead_Range": (30, 70),
        "Demand_Profile": "Medium",
        "Sourcing_Type": "Multi-source"
    },

    {
        "Material_ID": "M016",
        "Material_Name": "Fixed Gas Detection Sensor",
        "Category": "Instrumentation / Control",
        "Criticality_Tier": "High",
        "Unit_of_Measure": "EA",
        "Cost_Range": (1500, 7000),
        "Lead_Range": (20, 60),
        "Demand_Profile": "Medium",
        "Sourcing_Type": "Dual-source"
    },

    {
        "Material_ID": "M017",
        "Material_Name": "Flow Measurement Transmitter",
        "Category": "Instrumentation / Control",
        "Criticality_Tier": "High",
        "Unit_of_Measure": "EA",
        "Cost_Range": (3000, 15000),
        "Lead_Range": (25, 65),
        "Demand_Profile": "Medium",
        "Sourcing_Type": "Multi-source"
    },

    {
        "Material_ID": "M018",
        "Material_Name": "Industrial PLC Input Output Module",
        "Category": "Instrumentation / Control",
        "Criticality_Tier": "High",
        "Unit_of_Measure": "EA",
        "Cost_Range": (2500, 12000),
        "Lead_Range": (25, 70),
        "Demand_Profile": "Medium",
        "Sourcing_Type": "Dual-source"
    },

    {
        "Material_ID": "M019",
        "Material_Name": "Mechanical Seal Assembly",
        "Category": "Mechanical / Rotating Equipment",
        "Criticality_Tier": "High",
        "Unit_of_Measure": "EA",
        "Cost_Range": (1200, 8000),
        "Lead_Range": (20, 55),
        "Demand_Profile": "High",
        "Sourcing_Type": "Multi-source"
    },

    {
        "Material_ID": "M020",
        "Material_Name": "Compressor Bearing Set",
        "Category": "Mechanical / Rotating Equipment",
        "Criticality_Tier": "High",
        "Unit_of_Measure": "SET",
        "Cost_Range": (4000, 18000),
        "Lead_Range": (30, 80),
        "Demand_Profile": "Medium",
        "Sourcing_Type": "Dual-source"
    },

    {
        "Material_ID": "M021",
        "Material_Name": "Power Distribution Cable",
        "Category": "Electrical / Power Systems",
        "Criticality_Tier": "High",
        "Unit_of_Measure": "M",
        "Cost_Range": (15, 120),
        "Lead_Range": (20, 60),
        "Demand_Profile": "High",
        "Sourcing_Type": "Multi-source"
    },

    {
        "Material_ID": "M022",
        "Material_Name": "Hydraulic Control Unit",
        "Category": "Mechanical / Rotating Equipment",
        "Criticality_Tier": "High",
        "Unit_of_Measure": "EA",
        "Cost_Range": (8000, 35000),
        "Lead_Range": (30, 85),
        "Demand_Profile": "Medium",
        "Sourcing_Type": "Dual-source"
    },

    {
        "Material_ID": "M023",
        "Material_Name": "Process Heat Exchanger Gasket Set",
        "Category": "Industrial / Process Consumables",
        "Criticality_Tier": "High",
        "Unit_of_Measure": "SET",
        "Cost_Range": (1500, 9000),
        "Lead_Range": (20, 55),
        "Demand_Profile": "Medium",
        "Sourcing_Type": "Multi-source"
    },

    {
        "Material_ID": "M024",
        "Material_Name": "Industrial Filtration Cartridge",
        "Category": "Industrial / Process Consumables",
        "Criticality_Tier": "High",
        "Unit_of_Measure": "EA",
        "Cost_Range": (300, 2500),
        "Lead_Range": (14, 45),
        "Demand_Profile": "High",
        "Sourcing_Type": "Multi-source"
    },

    {
        "Material_ID": "M025",
        "Material_Name": "High-Pressure Pipe Fitting Assembly",
        "Category": "Valves / Piping / Flow",
        "Criticality_Tier": "High",
        "Unit_of_Measure": "EA",
        "Cost_Range": (800, 6000),
        "Lead_Range": (20, 60),
        "Demand_Profile": "Medium",
        "Sourcing_Type": "Dual-source"
    },


    # MEDIUM -----------------------------------------------------------------

    {
        "Material_ID": "M026",
        "Material_Name": "Standard Ball Valve",
        "Category": "Valves / Piping / Flow",
        "Criticality_Tier": "Medium",
        "Unit_of_Measure": "EA",
        "Cost_Range": (150, 1800),
        "Lead_Range": (10, 35),
        "Demand_Profile": "High",
        "Sourcing_Type": "Multi-source"
    },

    {
        "Material_ID": "M027",
        "Material_Name": "Standard Gate Valve",
        "Category": "Valves / Piping / Flow",
        "Criticality_Tier": "Medium",
        "Unit_of_Measure": "EA",
        "Cost_Range": (180, 2200),
        "Lead_Range": (10, 40),
        "Demand_Profile": "Medium",
        "Sourcing_Type": "Multi-source"
    },

    {
        "Material_ID": "M028",
        "Material_Name": "Stainless Steel Process Pipe",
        "Category": "Valves / Piping / Flow",
        "Criticality_Tier": "Medium",
        "Unit_of_Measure": "M",
        "Cost_Range": (35, 180),
        "Lead_Range": (15, 45),
        "Demand_Profile": "Medium",
        "Sourcing_Type": "Multi-source"
    },

    {
        "Material_ID": "M029",
        "Material_Name": "Carbon Steel Process Pipe",
        "Category": "Valves / Piping / Flow",
        "Criticality_Tier": "Medium",
        "Unit_of_Measure": "M",
        "Cost_Range": (20, 110),
        "Lead_Range": (10, 35),
        "Demand_Profile": "High",
        "Sourcing_Type": "Multi-source"
    },

    {
        "Material_ID": "M030",
        "Material_Name": "Industrial Flange Assembly",
        "Category": "Valves / Piping / Flow",
        "Criticality_Tier": "Medium",
        "Unit_of_Measure": "EA",
        "Cost_Range": (80, 900),
        "Lead_Range": (10, 35),
        "Demand_Profile": "Medium",
        "Sourcing_Type": "Multi-source"
    },

    {
        "Material_ID": "M031",
        "Material_Name": "Industrial Process Hose",
        "Category": "Industrial / Process Consumables",
        "Criticality_Tier": "Medium",
        "Unit_of_Measure": "M",
        "Cost_Range": (15, 120),
        "Lead_Range": (7, 30),
        "Demand_Profile": "High",
        "Sourcing_Type": "Multi-source"
    },

    {
        "Material_ID": "M032",
        "Material_Name": "Pump Bearing",
        "Category": "Mechanical / Rotating Equipment",
        "Criticality_Tier": "Medium",
        "Unit_of_Measure": "EA",
        "Cost_Range": (80, 1200),
        "Lead_Range": (10, 35),
        "Demand_Profile": "High",
        "Sourcing_Type": "Multi-source"
    },

    {
        "Material_ID": "M033",
        "Material_Name": "Flexible Coupling Assembly",
        "Category": "Mechanical / Rotating Equipment",
        "Criticality_Tier": "Medium",
        "Unit_of_Measure": "EA",
        "Cost_Range": (250, 2500),
        "Lead_Range": (15, 40),
        "Demand_Profile": "Medium",
        "Sourcing_Type": "Multi-source"
    },

    {
        "Material_ID": "M034",
        "Material_Name": "Standard Pressure Gauge",
        "Category": "Instrumentation / Control",
        "Criticality_Tier": "Medium",
        "Unit_of_Measure": "EA",
        "Cost_Range": (60, 500),
        "Lead_Range": (7, 25),
        "Demand_Profile": "High",
        "Sourcing_Type": "Multi-source"
    },

    {
        "Material_ID": "M035",
        "Material_Name": "Temperature Transmitter",
        "Category": "Instrumentation / Control",
        "Criticality_Tier": "Medium",
        "Unit_of_Measure": "EA",
        "Cost_Range": (250, 1800),
        "Lead_Range": (10, 35),
        "Demand_Profile": "Medium",
        "Sourcing_Type": "Multi-source"
    },

    {
        "Material_ID": "M036",
        "Material_Name": "Industrial Electrical Contactor",
        "Category": "Electrical / Power Systems",
        "Criticality_Tier": "Medium",
        "Unit_of_Measure": "EA",
        "Cost_Range": (80, 700),
        "Lead_Range": (7, 25),
        "Demand_Profile": "High",
        "Sourcing_Type": "Multi-source"
    },

    {
        "Material_ID": "M037",
        "Material_Name": "Industrial Control Cable",
        "Category": "Electrical / Power Systems",
        "Criticality_Tier": "Medium",
        "Unit_of_Measure": "M",
        "Cost_Range": (5, 40),
        "Lead_Range": (7, 30),
        "Demand_Profile": "High",
        "Sourcing_Type": "Multi-source"
    },

    {
        "Material_ID": "M038",
        "Material_Name": "Cable Termination Kit",
        "Category": "Electrical / Power Systems",
        "Criticality_Tier": "Medium",
        "Unit_of_Measure": "SET",
        "Cost_Range": (50, 600),
        "Lead_Range": (7, 30),
        "Demand_Profile": "Medium",
        "Sourcing_Type": "Multi-source"
    },

    {
        "Material_ID": "M039",
        "Material_Name": "Industrial Fuse Set",
        "Category": "Electrical / Power Systems",
        "Criticality_Tier": "Medium",
        "Unit_of_Measure": "SET",
        "Cost_Range": (25, 400),
        "Lead_Range": (5, 20),
        "Demand_Profile": "High",
        "Sourcing_Type": "Multi-source"
    },

    {
        "Material_ID": "M040",
        "Material_Name": "Industrial Lubricating Oil",
        "Category": "Chemicals / Lubricants",
        "Criticality_Tier": "Medium",
        "Unit_of_Measure": "L",
        "Cost_Range": (4, 18),
        "Lead_Range": (5, 20),
        "Demand_Profile": "High",
        "Sourcing_Type": "Multi-source"
    },

    {
        "Material_ID": "M041",
        "Material_Name": "Hydraulic Oil",
        "Category": "Chemicals / Lubricants",
        "Criticality_Tier": "Medium",
        "Unit_of_Measure": "L",
        "Cost_Range": (3, 15),
        "Lead_Range": (5, 20),
        "Demand_Profile": "High",
        "Sourcing_Type": "Multi-source"
    },

    {
        "Material_ID": "M042",
        "Material_Name": "Compressor Filter Element",
        "Category": "Industrial / Process Consumables",
        "Criticality_Tier": "Medium",
        "Unit_of_Measure": "EA",
        "Cost_Range": (80, 800),
        "Lead_Range": (7, 30),
        "Demand_Profile": "High",
        "Sourcing_Type": "Multi-source"
    },

    {
        "Material_ID": "M043",
        "Material_Name": "Process Gasket Set",
        "Category": "Industrial / Process Consumables",
        "Criticality_Tier": "Medium",
        "Unit_of_Measure": "SET",
        "Cost_Range": (50, 700),
        "Lead_Range": (7, 25),
        "Demand_Profile": "High",
        "Sourcing_Type": "Multi-source"
    },

    {
        "Material_ID": "M044",
        "Material_Name": "Industrial Fastener Kit",
        "Category": "Industrial / Process Consumables",
        "Criticality_Tier": "Medium",
        "Unit_of_Measure": "SET",
        "Cost_Range": (20, 250),
        "Lead_Range": (5, 20),
        "Demand_Profile": "High",
        "Sourcing_Type": "Multi-source"
    },

    {
        "Material_ID": "M045",
        "Material_Name": "Maintenance Welding Electrode",
        "Category": "Industrial / Process Consumables",
        "Criticality_Tier": "Medium",
        "Unit_of_Measure": "KG",
        "Cost_Range": (5, 20),
        "Lead_Range": (5, 20),
        "Demand_Profile": "Medium",
        "Sourcing_Type": "Multi-source"
    },


    # LOW --------------------------------------------------------------------

    {
        "Material_ID": "M046",
        "Material_Name": "General Maintenance Gloves",
        "Category": "Safety / PPE",
        "Criticality_Tier": "Low",
        "Unit_of_Measure": "PAIR",
        "Cost_Range": (2, 15),
        "Lead_Range": (3, 14),
        "Demand_Profile": "High",
        "Sourcing_Type": "Multi-source"
    },

    {
        "Material_ID": "M047",
        "Material_Name": "Disposable Protective Coverall",
        "Category": "Safety / PPE",
        "Criticality_Tier": "Low",
        "Unit_of_Measure": "EA",
        "Cost_Range": (5, 30),
        "Lead_Range": (3, 14),
        "Demand_Profile": "High",
        "Sourcing_Type": "Multi-source"
    },

    {
        "Material_ID": "M048",
        "Material_Name": "Industrial Safety Goggles",
        "Category": "Safety / PPE",
        "Criticality_Tier": "Low",
        "Unit_of_Measure": "EA",
        "Cost_Range": (3, 20),
        "Lead_Range": (3, 14),
        "Demand_Profile": "High",
        "Sourcing_Type": "Multi-source"
    },

    {
        "Material_ID": "M049",
        "Material_Name": "Hearing Protection Plugs",
        "Category": "Safety / PPE",
        "Criticality_Tier": "Low",
        "Unit_of_Measure": "PAIR",
        "Cost_Range": (1, 8),
        "Lead_Range": (2, 10),
        "Demand_Profile": "High",
        "Sourcing_Type": "Multi-source"
    },

    {
        "Material_ID": "M050",
        "Material_Name": "General Industrial Cleaning Chemical",
        "Category": "Chemicals / Lubricants",
        "Criticality_Tier": "Low",
        "Unit_of_Measure": "L",
        "Cost_Range": (2, 12),
        "Lead_Range": (3, 14),
        "Demand_Profile": "Medium",
        "Sourcing_Type": "Multi-source"
    },

    {
        "Material_ID": "M051",
        "Material_Name": "Industrial Absorbent Pad",
        "Category": "Industrial / Process Consumables",
        "Criticality_Tier": "Low",
        "Unit_of_Measure": "PACK",
        "Cost_Range": (10, 80),
        "Lead_Range": (3, 14),
        "Demand_Profile": "Medium",
        "Sourcing_Type": "Multi-source"
    },

    {
        "Material_ID": "M052",
        "Material_Name": "Industrial Cable Tie Pack",
        "Category": "Electrical / Power Systems",
        "Criticality_Tier": "Low",
        "Unit_of_Measure": "PACK",
        "Cost_Range": (5, 35),
        "Lead_Range": (2, 10),
        "Demand_Profile": "High",
        "Sourcing_Type": "Multi-source"
    },

    {
        "Material_ID": "M053",
        "Material_Name": "Electrical Terminal Block",
        "Category": "Electrical / Power Systems",
        "Criticality_Tier": "Low",
        "Unit_of_Measure": "EA",
        "Cost_Range": (2, 25),
        "Lead_Range": (3, 14),
        "Demand_Profile": "Medium",
        "Sourcing_Type": "Multi-source"
    },

    {
        "Material_ID": "M054",
        "Material_Name": "General Purpose Electrical Fuse",
        "Category": "Electrical / Power Systems",
        "Criticality_Tier": "Low",
        "Unit_of_Measure": "EA",
        "Cost_Range": (1, 20),
        "Lead_Range": (3, 14),
        "Demand_Profile": "High",
        "Sourcing_Type": "Multi-source"
    },

    {
        "Material_ID": "M055",
        "Material_Name": "Stainless Steel Fastener Pack",
        "Category": "Industrial / Process Consumables",
        "Criticality_Tier": "Low",
        "Unit_of_Measure": "PACK",
        "Cost_Range": (10, 100),
        "Lead_Range": (3, 14),
        "Demand_Profile": "High",
        "Sourcing_Type": "Multi-source"
    },

    {
        "Material_ID": "M056",
        "Material_Name": "Maintenance Brush Set",
        "Category": "Industrial / Process Consumables",
        "Criticality_Tier": "Low",
        "Unit_of_Measure": "SET",
        "Cost_Range": (8, 60),
        "Lead_Range": (2, 10),
        "Demand_Profile": "Medium",
        "Sourcing_Type": "Multi-source"
    },

    {
        "Material_ID": "M057",
        "Material_Name": "Industrial Cleaning Wipe",
        "Category": "Industrial / Process Consumables",
        "Criticality_Tier": "Low",
        "Unit_of_Measure": "PACK",
        "Cost_Range": (5, 40),
        "Lead_Range": (2, 10),
        "Demand_Profile": "High",
        "Sourcing_Type": "Multi-source"
    },

    {
        "Material_ID": "M058",
        "Material_Name": "General Workshop Hose",
        "Category": "Valves / Piping / Flow",
        "Criticality_Tier": "Low",
        "Unit_of_Measure": "M",
        "Cost_Range": (5, 35),
        "Lead_Range": (3, 14),
        "Demand_Profile": "Medium",
        "Sourcing_Type": "Multi-source"
    },

    {
        "Material_ID": "M059",
        "Material_Name": "Equipment Identification Label Pack",
        "Category": "Industrial / Process Consumables",
        "Criticality_Tier": "Low",
        "Unit_of_Measure": "PACK",
        "Cost_Range": (5, 50),
        "Lead_Range": (2, 10),
        "Demand_Profile": "Medium",
        "Sourcing_Type": "Multi-source"
    },

    {
        "Material_ID": "M060",
        "Material_Name": "General Maintenance Consumable Kit",
        "Category": "Industrial / Process Consumables",
        "Criticality_Tier": "Low",
        "Unit_of_Measure": "KIT",
        "Cost_Range": (20, 150),
        "Lead_Range": (3, 14),
        "Demand_Profile": "Medium",
        "Sourcing_Type": "Multi-source"
    }
]


# =============================================================================
# 17. BUILD DIM_MATERIAL
# =============================================================================

material_rows = []

demand_factors = {
    "High": 1.00,
    "Medium": 0.60,
    "Low": 0.30
}

criticality_factors = {
    "Critical": 1.35,
    "High": 1.15,
    "Medium": 0.95,
    "Low": 0.75
}


for material in material_definitions:

    low_cost, high_cost = material["Cost_Range"]

    low_lead, high_lead = material["Lead_Range"]

    unit_cost = round(
        rng.uniform(
            low_cost,
            high_cost
        ),
        2
    )

    typical_lead_time = int(
        rng.integers(
            low_lead,
            high_lead + 1
        )
    )

    demand_factor = demand_factors[
        material["Demand_Profile"]
    ]

    criticality_factor = criticality_factors[
        material["Criticality_Tier"]
    ]

    if material["Demand_Profile"] == "High":

        base_demand = rng.integers(
            500,
            2500
        )

    elif material["Demand_Profile"] == "Medium":

        base_demand = rng.integers(
            150,
            1000
        )

    else:

        base_demand = rng.integers(
            10,
            250
        )

    base_demand = (
        base_demand
        * criticality_factor
    )

    daily_demand = base_demand / 365

    lead_time_factor = np.sqrt(
        typical_lead_time / 30
    )

    safety_stock = (
        daily_demand
        * 14
        * lead_time_factor
        * (0.80 + 0.20 * criticality_factor)
    )

    safety_stock = max(
        1,
        int(round(safety_stock))
    )

    reorder_point = (
        daily_demand
        * typical_lead_time
        + safety_stock
    )

    reorder_point = max(
        safety_stock + 1,
        int(round(reorder_point))
    )

    material_rows.append({

        "Material_ID":
            material["Material_ID"],

        "Material_Name":
            material["Material_Name"],

        "Category":
            material["Category"],

        "Criticality_Tier":
            material["Criticality_Tier"],

        "Unit_of_Measure":
            material["Unit_of_Measure"],

        "Unit_Cost_USD":
            unit_cost,

        "Typical_Lead_Time_Days":
            typical_lead_time,

        "Demand_Profile":
            material["Demand_Profile"],

        "Safety_Stock_Qty":
            safety_stock,

        "Reorder_Point_Qty":
            reorder_point,

        "Sourcing_Type":
            material["Sourcing_Type"]
    })


# =============================================================================
# 18. BUILD DIM_MATERIAL
# =============================================================================

dim_material = pd.DataFrame(
    material_rows
)


material_required_columns = [

    "Material_ID",
    "Material_Name",
    "Category",
    "Criticality_Tier",
    "Unit_of_Measure",
    "Unit_Cost_USD",
    "Typical_Lead_Time_Days",
    "Demand_Profile",
    "Safety_Stock_Qty",
    "Reorder_Point_Qty",
    "Sourcing_Type"
]

dim_material = dim_material[
    material_required_columns
]


# =============================================================================
# 19. MATERIAL VALIDATION
# =============================================================================

assert len(dim_material) == 60

assert dim_material["Material_ID"].nunique() == 60

assert dim_material["Material_Name"].nunique() == 60

expected_material_ids = [
    f"M{i:03d}" for i in range(1, 61)
]

assert sorted(
    dim_material["Material_ID"].tolist()
) == expected_material_ids

assert (
    dim_material[material_required_columns]
    .notna()
    .all()
    .all()
)

expected_criticality_counts = {
    "Critical": 10,
    "High": 15,
    "Medium": 20,
    "Low": 15
}

actual_criticality_counts = (
    dim_material["Criticality_Tier"]
    .value_counts()
    .to_dict()
)

assert actual_criticality_counts == expected_criticality_counts

allowed_material_categories = {
    "Mechanical / Rotating Equipment",
    "Electrical / Power Systems",
    "Instrumentation / Control",
    "Valves / Piping / Flow",
    "Industrial / Process Consumables",
    "Chemicals / Lubricants",
    "Safety / PPE"
}

assert set(
    dim_material["Category"]
).issubset(
    allowed_material_categories
)

assert (
    dim_material["Unit_Cost_USD"] > 0
).all()

assert (
    dim_material["Typical_Lead_Time_Days"] > 0
).all()

assert (
    dim_material["Safety_Stock_Qty"] > 0
).all()

assert (
    dim_material["Reorder_Point_Qty"]
    > dim_material["Safety_Stock_Qty"]
).all()

assert set(
    dim_material["Demand_Profile"]
).issubset({
    "High",
    "Medium",
    "Low"
})

assert set(
    dim_material["Sourcing_Type"]
).issubset({
    "Single-source",
    "Dual-source",
    "Multi-source"
})


# =============================================================================
# 20. MATERIAL LEAKAGE CHECK
# =============================================================================

material_forbidden_columns = [

    "Material_Risk_Score",
    "Risk_Score",
    "Risk_Tier",
    "Failure_Label",
    "Failure_State",
    "Deterioration_State",
    "Demand_Volatility_Observed",
    "Actual_Consumption",
    "Current_Inventory",
    "Days_of_Supply",
    "Stockout_Flag",
    "Shortage_Flag",
    "Supplier_Performance",
    "Supplier_Risk"
]

for column in material_forbidden_columns:

    assert column not in dim_material.columns


# =============================================================================
# 21. PERMANENT SAVE — DIM_SUPPLIER
# =============================================================================

supplier_path = (
    DIMENSIONS_PATH / "Dim_Supplier.csv"
)

dim_supplier.to_csv(
    supplier_path,
    index=False
)

assert supplier_path.exists()

print("\n" + "=" * 80)
print("PERMANENT SAVE — DIM_SUPPLIER")
print("=" * 80)

print(f"✓ Saved to : {supplier_path}")
print(
    f"✓ File size : "
    f"{supplier_path.stat().st_size:,} bytes"
)


# =============================================================================
# 22. RELOAD VERIFICATION — DIM_SUPPLIER
# =============================================================================

dim_supplier_reload = pd.read_csv(
    supplier_path,
    parse_dates=["Active_From"]
)

assert len(dim_supplier_reload) == 90

assert (
    dim_supplier_reload["Supplier_ID"].nunique()
    == 90
)

assert list(
    dim_supplier_reload.columns
) == supplier_required_columns

print("\nPOST-SAVE RELOAD VERIFICATION — DIM_SUPPLIER")

print("✓ Reloaded successfully")
print(f"✓ Rows       : {len(dim_supplier_reload):,}")
print(
    f"✓ Columns    : "
    f"{len(dim_supplier_reload.columns)}"
)
print(
    f"✓ Suppliers  : "
    f"{dim_supplier_reload['Supplier_ID'].nunique():,}"
)
print("✓ Permanent file verified")


# =============================================================================
# 23. PERMANENT SAVE — DIM_MATERIAL
# =============================================================================

material_path = (
    DIMENSIONS_PATH / "Dim_Material.csv"
)

dim_material.to_csv(
    material_path,
    index=False
)

assert material_path.exists()

print("\n" + "=" * 80)
print("PERMANENT SAVE — DIM_MATERIAL")
print("=" * 80)

print(f"✓ Saved to : {material_path}")
print(
    f"✓ File size : "
    f"{material_path.stat().st_size:,} bytes"
)


# =============================================================================
# 24. RELOAD VERIFICATION — DIM_MATERIAL
# =============================================================================

dim_material_reload = pd.read_csv(
    material_path
)

assert len(dim_material_reload) == 60

assert (
    dim_material_reload["Material_ID"].nunique()
    == 60
)

assert list(
    dim_material_reload.columns
) == material_required_columns

print("\nPOST-SAVE RELOAD VERIFICATION — DIM_MATERIAL")

print("✓ Reloaded successfully")
print(f"✓ Rows       : {len(dim_material_reload):,}")
print(
    f"✓ Columns    : "
    f"{len(dim_material_reload.columns)}"
)
print(
    f"✓ Materials  : "
    f"{dim_material_reload['Material_ID'].nunique():,}"
)
print("✓ Permanent file verified")


# =============================================================================
# 25. FINAL PROJECT STORAGE AUDIT
# =============================================================================

expected_files = [

    "Dim_Date.csv",
    "Dim_Asset.csv",
    "Dim_Supplier.csv",
    "Dim_Material.csv"
]

print("\n" + "=" * 80)
print("KEYSTRA — DIMENSION STORAGE AUDIT")
print("=" * 80)

for filename in expected_files:

    file_path = DIMENSIONS_PATH / filename

    if file_path.exists():

        print(
            f"✓ {filename:<25} "
            f"{file_path.stat().st_size:,} bytes"
        )

    else:

        print(
            f"✗ {filename:<25} MISSING"
        )


# =============================================================================
# 26. FINAL REPORT
# =============================================================================

print("\n" + "=" * 80)
print("KEYSTRA — DIM_SUPPLIER FINAL VALIDATION")
print("=" * 80)

print(f"Rows                  : {len(dim_supplier):,}")
print(f"Columns               : {len(dim_supplier.columns)}")
print(
    f"Unique Suppliers      : "
    f"{dim_supplier['Supplier_ID'].nunique():,}"
)
print(
    f"Unique Names          : "
    f"{dim_supplier['Supplier_Name'].nunique():,}"
)
print(
    f"Supplier Categories   : "
    f"{dim_supplier['Supplier_Category'].nunique()}"
)
print(
    f"Business Units        : "
    f"{dim_supplier['Primary_Business_Unit'].nunique()}"
)
print(
    f"Regions               : "
    f"{dim_supplier['Region'].nunique()}"
)

print("\nSupplier Category Distribution:")

print(
    dim_supplier[
        "Supplier_Category"
    ]
    .value_counts()
    .sort_index()
    .to_string()
)

print("\nSupplier Status Distribution:")

print(
    dim_supplier[
        "Supplier_Status"
    ]
    .value_counts()
    .to_string()
)

print("\nDIM_SUPPLIER PREVIEW:")

display(
    dim_supplier.head(15)
)


print("\n" + "=" * 80)
print("KEYSTRA — DIM_MATERIAL FINAL VALIDATION")
print("=" * 80)

print(f"Rows                  : {len(dim_material):,}")
print(f"Columns               : {len(dim_material.columns)}")
print(
    f"Unique Materials      : "
    f"{dim_material['Material_ID'].nunique():,}"
)
print(
    f"Unique Names          : "
    f"{dim_material['Material_Name'].nunique():,}"
)
print(
    f"Material Categories   : "
    f"{dim_material['Category'].nunique()}"
)

print("\nCriticality Distribution:")

print(
    dim_material[
        "Criticality_Tier"
    ]
    .value_counts()
    .reindex([
        "Critical",
        "High",
        "Medium",
        "Low"
    ])
    .to_string()
)

print("\nSourcing Type Distribution:")

print(
    dim_material[
        "Sourcing_Type"
    ]
    .value_counts()
    .to_string()
)

print("\nDIM_MATERIAL PREVIEW:")

display(
    dim_material.head(15)
)


# =============================================================================
# 27. FINAL SUCCESS CHECK
# =============================================================================

assert len(dim_supplier) == 90
assert len(dim_material) == 60

assert dim_supplier["Supplier_ID"].nunique() == 90
assert dim_material["Material_ID"].nunique() == 60

assert supplier_path.exists()
assert material_path.exists()


# =============================================================================
# 28. FINAL CONFIRMATION
# =============================================================================

print("\n" + "=" * 80)
print("✓ DIM_SUPPLIER PASSED ALL VALIDATION CHECKS")
print("✓ 90 SUPPLIERS CONFIRMED")
print("✓ SUPPLIER MASTER DATA VALIDATED")
print("✓ NO PREDICTIVE / RISK LEAKAGE")
print("✓ PERMANENTLY SAVED")
print("✓ RELOAD VERIFICATION PASSED")
print("=" * 80)

print("\n" + "=" * 80)
print("✓ DIM_MATERIAL PASSED ALL VALIDATION CHECKS")
print("✓ 60 MATERIALS CONFIRMED")
print("✓ M001–M060 CONFIRMED")
print("✓ 10 CRITICAL MATERIALS CONFIRMED")
print("✓ 15 HIGH MATERIALS CONFIRMED")
print("✓ 20 MEDIUM MATERIALS CONFIRMED")
print("✓ 15 LOW MATERIALS CONFIRMED")
print("✓ NO PREDICTIVE / RISK LEAKAGE")
print("✓ PERMANENTLY SAVED")
print("✓ RELOAD VERIFICATION PASSED")
print("=" * 80)

print("\n" + "=" * 80)
print("KEYSTRA MASTER DATA FOUNDATION — CURRENT STATUS")
print("=" * 80)

print("✓ Dim_Date       → 01_dimensions/Dim_Date.csv")
print("✓ Dim_Asset      → 01_dimensions/Dim_Asset.csv")
print("✓ Dim_Supplier   → 01_dimensions/Dim_Supplier.csv")
print("✓ Dim_Material   → 01_dimensions/Dim_Material.csv")

print("\n✓ ALL FOUR DIMENSIONS ARE PERMANENTLY STORED")
print("✓ NEXT OBJECT: Bridge_SupplierMaterial")
print("=" * 80)

================================================================================
KEYSTRA — DIMENSION BUILD INITIALIZATION
================================================================================
Project Root : /content/drive/MyDrive/KEYSTRA_SOLUTION_4
Dimensions   : /content/drive/MyDrive/KEYSTRA_SOLUTION_4/01_dimensions

✓ Permanent storage confirmed

================================================================================
PERMANENT SAVE — DIM_SUPPLIER
================================================================================
✓ Saved to : /content/drive/MyDrive/KEYSTRA_SOLUTION_4/01_dimensions/Dim_Supplier.csv
✓ File size : 11,135 bytes

POST-SAVE RELOAD VERIFICATION — DIM_SUPPLIER
✓ Reloaded successfully
✓ Rows       : 90
✓ Columns    : 10
✓ Suppliers  : 90
✓ Permanent file verified

================================================================================
PERMANENT SAVE — DIM_MATERIAL
================================================================================
✓ Saved to : /content/drive/MyDrive/KEYSTRA_SOLUTION_4/01_dimensions/Dim_Material.csv
✓ File size : 6,385 bytes

POST-SAVE RELOAD VERIFICATION — DIM_MATERIAL
✓ Reloaded successfully
✓ Rows       : 60
✓ Columns    : 11
✓ Materials  : 60
✓ Permanent file verified

================================================================================
KEYSTRA — DIMENSION STORAGE AUDIT
================================================================================
✗ Dim_Date.csv              MISSING
✓ Dim_Asset.csv             997 bytes
✓ Dim_Supplier.csv          11,135 bytes
✓ Dim_Material.csv          6,385 bytes

================================================================================
KEYSTRA — DIM_SUPPLIER FINAL VALIDATION
================================================================================
Rows                  : 90
Columns               : 10
Unique Suppliers      : 90
Unique Names          : 90
Supplier Categories   : 9
Business Units        : 5
Regions               : 6

Supplier Category Distribution:
Supplier_Category
Chemicals / Lubricants                     8
Electrical / Power Systems                12
Industrial / Process Consumables          10
Instrumentation / Control                 12
Mechanical / Rotating Equipment           15
Multi-category / Integrated Industrial     5
Renewable Energy Equipment                 7
Safety / PPE                               7
Valves / Piping / Flow                    14

Supplier Status Distribution:
Supplier_Status
Active    90

DIM_SUPPLIER PREVIEW:

,Supplier_ID,Supplier_Name,Supplier_Category,Region,Supplier_Size,Strategic_Tier,Baseline_Lead_Time,Primary_Business_Unit,Active_From,Supplier_Status
0,S001,Apex Rotating Systems Ltd.,Mechanical / Rotating Equipment,Middle East,Mid-size,Standard,69,BU001,2022-01-01,Active
1,S002,Meridian Mechanical Technologies Ltd.,Mechanical / Rotating Equipment,North America,Specialist SME,Standard,108,BU001,2022-01-01,Active
2,S003,Atlas Turbomachinery Services Ltd.,Mechanical / Rotating Equipment,West Africa,Mid-size,Standard,46,BU003,2022-01-01,Active
3,S004,Sterling Industrial Equipment Ltd.,Mechanical / Rotating Equipment,West Africa,Large Enterprise,Standard,114,BU001,2022-01-01,Active
4,S005,Northstar Mechanical Solutions Ltd.,Mechanical / Rotating Equipment,Asia,Mid-size,Preferred,45,BU005,2022-01-01,Active
5,S006,Crestline Rotating Equipment Ltd.,Mechanical / Rotating Equipment,Asia,Specialist SME,Strategic,98,BU002,2022-01-01,Active
6,S007,Prime Industrial Machinery Ltd.,Mechanical / Rotating Equipment,Nigeria,Large Enterprise,Standard,97,BU005,2022-01-01,Active
7,S008,Vector Mechanical Engineering Ltd.,Mechanical / Rotating Equipment,Nigeria,Mid-size,Preferred,92,BU001,2022-01-01,Active
8,S009,Ironbridge Equipment Solutions Ltd.,Mechanical / Rotating Equipment,Nigeria,Mid-size,Standard,60,BU002,2022-01-01,Active
9,S010,Pinnacle Machinery Services Ltd.,Mechanical / Rotating Equipment,Asia,Mid-size,Preferred,50,BU003,2022-01-01,Active
10,S011,BluePeak Mechanical Systems Ltd.,Mechanical / Rotating Equipment,Middle East,Mid-size,Standard,111,BU001,2022-01-01,Active
11,S012,Summit Rotating Technologies Ltd.,Mechanical / Rotating Equipment,Nigeria,Large Enterprise,Standard,56,BU003,2022-01-01,Active
12,S013,Westfield Industrial Engineering Ltd.,Mechanical / Rotating Equipment,Europe,Specialist SME,Standard,80,BU001,2022-01-01,Active
13,S014,Orion Machinery & Engineering Ltd.,Mechanical / Rotating Equipment,Nigeria,Mid-size,Preferred,71,BU002,2022-01-01,Active
14,S015,Grandview Mechanical Systems Ltd.,Mechanical / Rotating Equipment,Middle East,Mid-size,Standard,81,BU001,2022-01-01,Active

================================================================================
KEYSTRA — DIM_MATERIAL FINAL VALIDATION
================================================================================
Rows                  : 60
Columns               : 11
Unique Materials      : 60
Unique Names          : 60
Material Categories   : 7

Criticality Distribution:
Criticality_Tier
Critical    10
High        15
Medium      20
Low         15

Sourcing Type Distribution:
Sourcing_Type
Multi-source     42
Dual-source      11
Single-source     7

DIM_MATERIAL PREVIEW:

,Material_ID,Material_Name,Category,Criticality_Tier,Unit_of_Measure,Unit_Cost_USD,Typical_Lead_Time_Days,Demand_Profile,Safety_Stock_Qty,Reorder_Point_Qty,Sourcing_Type
0,M001,Gas Turbine Rotor Assembly,Mechanical / Rotating Equipment,Critical,EA,601680.01,152,Low,10,54,Single-source
1,M002,Gas Compressor Dry Gas Seal,Mechanical / Rotating Equipment,Critical,EA,132874.14,63,Low,3,11,Single-source
2,M003,High-Pressure Emergency Shutdown Valve,Valves / Piping / Flow,Critical,EA,94937.33,61,Low,13,51,Single-source
3,M004,Offshore Power Transformer,Electrical / Power Systems,Critical,EA,420546.26,146,Low,4,21,Single-source
4,M005,Safety Instrumented System Controller,Instrumentation / Control,Critical,EA,111247.84,110,Low,2,9,Single-source
5,M006,Subsea Control Module,Instrumentation / Control,Critical,EA,160207.01,131,Low,5,26,Single-source
6,M007,Critical Process Pump Cartridge,Mechanical / Rotating Equipment,Critical,EA,92141.44,117,Medium,35,173,Dual-source
7,M008,Medium-Voltage Switchgear Breaker,Electrical / Power Systems,Critical,EA,84191.48,66,Low,14,55,Dual-source
8,M009,Turbine Generator Excitation Module,Electrical / Power Systems,Critical,EA,43616.27,60,Low,1,3,Single-source
9,M010,High-Integrity Pressure Protection Valve,Valves / Piping / Flow,Critical,EA,33616.05,126,Low,18,90,Dual-source
10,M011,Centrifugal Process Pump,Mechanical / Rotating Equipment,High,EA,46463.72,88,Medium,27,125,Dual-source
11,M012,Industrial Electric Motor,Electrical / Power Systems,High,EA,35181.08,41,Medium,11,37,Multi-source
12,M013,Control Valve Actuator,Valves / Piping / Flow,High,EA,21019.28,74,Medium,67,286,Dual-source
13,M014,Pressure Control Valve,Valves / Piping / Flow,High,EA,24758.49,73,Medium,53,224,Dual-source
14,M015,Industrial Variable Frequency Drive,Electrical / Power Systems,High,EA,24435.56,48,Medium,11,39,Multi-source

================================================================================
✓ DIM_SUPPLIER PASSED ALL VALIDATION CHECKS
✓ 90 SUPPLIERS CONFIRMED
✓ SUPPLIER MASTER DATA VALIDATED
✓ NO PREDICTIVE / RISK LEAKAGE
✓ PERMANENTLY SAVED
✓ RELOAD VERIFICATION PASSED
================================================================================

================================================================================
✓ DIM_MATERIAL PASSED ALL VALIDATION CHECKS
✓ 60 MATERIALS CONFIRMED
✓ M001–M060 CONFIRMED
✓ 10 CRITICAL MATERIALS CONFIRMED
✓ 15 HIGH MATERIALS CONFIRMED
✓ 20 MEDIUM MATERIALS CONFIRMED
✓ 15 LOW MATERIALS CONFIRMED
✓ NO PREDICTIVE / RISK LEAKAGE
✓ PERMANENTLY SAVED
✓ RELOAD VERIFICATION PASSED
================================================================================

================================================================================
KEYSTRA MASTER DATA FOUNDATION — CURRENT STATUS
================================================================================
✓ Dim_Date       → 01_dimensions/Dim_Date.csv
✓ Dim_Asset      → 01_dimensions/Dim_Asset.csv
✓ Dim_Supplier   → 01_dimensions/Dim_Supplier.csv
✓ Dim_Material   → 01_dimensions/Dim_Material.csv

✓ ALL FOUR DIMENSIONS ARE PERMANENTLY STORED
✓ NEXT OBJECT: Bridge_SupplierMaterial
================================================================================

In [5]:
# ============================================================
# KEYSTRA SOLUTION 4
# STEP 5 — DIM_FAILURETYPE
# Supply Chain Risk & Operational Resilience Early-Warning System
# ============================================================

import os
import pandas as pd


# ============================================================
# 1. PROJECT PATHS
# ============================================================

PROJECT_ROOT = "/content/drive/MyDrive/KEYSTRA_SOLUTION_4"

DIMENSIONS_PATH = os.path.join(
    PROJECT_ROOT,
    "01_dimensions"
)

OUTPUT_FILE = os.path.join(
    DIMENSIONS_PATH,
    "Dim_FailureType.csv"
)


# ============================================================
# 2. INITIALIZATION
# ============================================================

os.makedirs(DIMENSIONS_PATH, exist_ok=True)

print("=" * 80)
print("KEYSTRA — DIM_FAILURETYPE BUILD INITIALIZATION")
print("=" * 80)

print(f"Project Root : {PROJECT_ROOT}")
print(f"Dimensions   : {DIMENSIONS_PATH}")

print("\n✓ Permanent storage confirmed")


# ============================================================
# 3. FAILURE TYPE MASTER DATA
# ============================================================
#
# This is a controlled lookup dimension.
#
# IMPORTANT:
# Failure types describe WHY an observed supplier failure
# occurred.
#
# They are NOT predictive features.
#
# Therefore this table must NOT contain:
#
# - Supplier_Risk_Score
# - Risk_Tier
# - Failure_Label
# - Target_90D
# - Failure_Probability
# - Supplier_Behaviour
# - Deterioration_State
#
# ============================================================

failure_type_rows = [

    {
        "Failure_Type_ID": "FT001",
        "Failure_Type": "Delivery Failure"
    },

    {
        "Failure_Type_ID": "FT002",
        "Failure_Type": "Fulfilment Failure"
    },

    {
        "Failure_Type_ID": "FT003",
        "Failure_Type": "Quality Failure"
    },

    {
        "Failure_Type_ID": "FT004",
        "Failure_Type": "Multi-Factor Failure"
    },

    {
        "Failure_Type_ID": "FT005",
        "Failure_Type": "Exposure-Related Failure"
    }
]


# ============================================================
# 4. BUILD DATAFRAME
# ============================================================

dim_failure_type = pd.DataFrame(
    failure_type_rows
)


# ============================================================
# 5. STRUCTURAL VALIDATION
# ============================================================

assert len(dim_failure_type) == 5, (
    f"Expected 5 failure types, "
    f"found {len(dim_failure_type)}."
)


assert (
    dim_failure_type["Failure_Type_ID"].nunique() == 5
), (
    "Duplicate Failure_Type_ID detected."
)


assert (
    dim_failure_type["Failure_Type"].nunique() == 5
), (
    "Duplicate Failure_Type detected."
)


# ============================================================
# 6. REQUIRED COLUMN VALIDATION
# ============================================================

required_columns = [
    "Failure_Type_ID",
    "Failure_Type"
]

missing_columns = [
    col
    for col in required_columns
    if col not in dim_failure_type.columns
]

assert not missing_columns, (
    f"Missing required columns: {missing_columns}"
)


# ============================================================
# 7. NULL VALIDATION
# ============================================================

assert (
    dim_failure_type[required_columns]
    .notna()
    .all()
    .all()
), (
    "Missing values detected in required "
    "failure type fields."
)


# ============================================================
# 8. ID VALIDATION
# ============================================================

expected_failure_type_ids = [
    "FT001",
    "FT002",
    "FT003",
    "FT004",
    "FT005"
]

assert (
    dim_failure_type["Failure_Type_ID"].tolist()
    == expected_failure_type_ids
), (
    "Failure Type IDs do not match "
    "the locked design."
)


# ============================================================
# 9. FAILURE TYPE VOCABULARY VALIDATION
# ============================================================

expected_failure_types = [
    "Delivery Failure",
    "Fulfilment Failure",
    "Quality Failure",
    "Multi-Factor Failure",
    "Exposure-Related Failure"
]

assert (
    dim_failure_type["Failure_Type"].tolist()
    == expected_failure_types
), (
    "Failure Type vocabulary does not match "
    "the locked design."
)


# ============================================================
# 10. UNIQUENESS VALIDATION
# ============================================================

assert (
    dim_failure_type["Failure_Type_ID"].is_unique
), (
    "Failure_Type_ID values must be unique."
)


assert (
    dim_failure_type["Failure_Type"].is_unique
), (
    "Failure_Type values must be unique."
)


# ============================================================
# 11. LEAKAGE VALIDATION
# ============================================================

for forbidden_column in [

    "Supplier_Risk_Score",
    "Risk_Score",
    "Risk_Tier",
    "Failure_Label",
    "Failure_State",
    "Deterioration_State",
    "Target_90D",
    "Failure_Probability",
    "Supplier_Behaviour",
    "Supplier_Type",
    "OTD",
    "Fulfilment_Rate",
    "Quality_Rate",
    "Days_To_Failure"

]:

    assert forbidden_column not in dim_failure_type.columns, (
        f"Potential predictive/leakage column detected: "
        f"{forbidden_column}"
    )


# ============================================================
# 12. FINAL COLUMN ORDER
# ============================================================

dim_failure_type = dim_failure_type[
    [
        "Failure_Type_ID",
        "Failure_Type"
    ]
]


# ============================================================
# 13. PERMANENT SAVE
# ============================================================

dim_failure_type.to_csv(
    OUTPUT_FILE,
    index=False
)

print("\n" + "=" * 80)
print("PERMANENT SAVE — DIM_FAILURETYPE")
print("=" * 80)

print(f"✓ Saved to : {OUTPUT_FILE}")

file_size = os.path.getsize(OUTPUT_FILE)

print(f"✓ File size : {file_size:,} bytes")


# ============================================================
# 14. POST-SAVE RELOAD VERIFICATION
# ============================================================

reloaded_failure_type = pd.read_csv(
    OUTPUT_FILE,
    dtype=str
)


assert len(reloaded_failure_type) == 5, (
    "Reloaded Dim_FailureType row count mismatch."
)

assert list(reloaded_failure_type.columns) == [
    "Failure_Type_ID",
    "Failure_Type"
], (
    "Reloaded Dim_FailureType column structure mismatch."
)

assert (
    reloaded_failure_type["Failure_Type_ID"].tolist()
    == expected_failure_type_ids
), (
    "Reloaded Failure_Type_ID values do not match."
)

assert (
    reloaded_failure_type["Failure_Type"].tolist()
    == expected_failure_types
), (
    "Reloaded Failure_Type values do not match."
)


print("\nPOST-SAVE RELOAD VERIFICATION — DIM_FAILURETYPE")

print("✓ Reloaded successfully")
print(
    f"✓ Rows       : "
    f"{len(reloaded_failure_type):,}"
)
print(
    f"✓ Columns    : "
    f"{len(reloaded_failure_type.columns):,}"
)
print(
    f"✓ Failure Types : "
    f"{reloaded_failure_type['Failure_Type'].nunique():,}"
)
print("✓ Permanent file verified")


# ============================================================
# 15. FINAL VALIDATION REPORT
# ============================================================

print("\n" + "=" * 80)
print("KEYSTRA — DIM_FAILURETYPE FINAL VALIDATION")
print("=" * 80)

print(
    f"Rows                  : "
    f"{len(dim_failure_type):,}"
)

print(
    f"Columns               : "
    f"{len(dim_failure_type.columns):,}"
)

print(
    f"Unique Failure Types  : "
    f"{dim_failure_type['Failure_Type'].nunique():,}"
)


print("\nFailure Type Distribution:")

print(
    dim_failure_type[
        "Failure_Type"
    ]
    .value_counts()
    .sort_index()
    .to_string()
)


print("\nDIM_FAILURETYPE PREVIEW:")

display(
    dim_failure_type
)


# ============================================================
# 16. FINAL SUCCESS FLAGS
# ============================================================

print("\n" + "=" * 80)
print("✓ DIM_FAILURETYPE PASSED ALL VALIDATION CHECKS")
print("✓ 5 FAILURE TYPES CONFIRMED")
print("✓ FAILURE TYPE IDS VALIDATED")
print("✓ FAILURE TYPE VOCABULARY VALIDATED")
print("✓ NO PREDICTIVE / RISK LEAKAGE DETECTED")
print("✓ PERMANENTLY SAVED")
print("✓ RELOAD VERIFICATION PASSED")
print("✓ DIM_FAILURETYPE READY FOR FACT TABLES")
print("=" * 80)

================================================================================
KEYSTRA — DIM_FAILURETYPE BUILD INITIALIZATION
================================================================================
Project Root : /content/drive/MyDrive/KEYSTRA_SOLUTION_4
Dimensions   : /content/drive/MyDrive/KEYSTRA_SOLUTION_4/01_dimensions

✓ Permanent storage confirmed

================================================================================
PERMANENT SAVE — DIM_FAILURETYPE
================================================================================
✓ Saved to : /content/drive/MyDrive/KEYSTRA_SOLUTION_4/01_dimensions/Dim_FailureType.csv
✓ File size : 157 bytes

POST-SAVE RELOAD VERIFICATION — DIM_FAILURETYPE
✓ Reloaded successfully
✓ Rows       : 5
✓ Columns    : 2
✓ Failure Types : 5
✓ Permanent file verified

================================================================================
KEYSTRA — DIM_FAILURETYPE FINAL VALIDATION
================================================================================
Rows                  : 5
Columns               : 2
Unique Failure Types  : 5

Failure Type Distribution:
Failure_Type
Delivery Failure            1
Exposure-Related Failure    1
Fulfilment Failure          1
Multi-Factor Failure        1
Quality Failure             1

DIM_FAILURETYPE PREVIEW:

  Failure_Type_ID              Failure_Type
0           FT001          Delivery Failure
1           FT002        Fulfilment Failure
2           FT003           Quality Failure
3           FT004      Multi-Factor Failure
4           FT005  Exposure-Related Failure

================================================================================
✓ DIM_FAILURETYPE PASSED ALL VALIDATION CHECKS
✓ 5 FAILURE TYPES CONFIRMED
✓ FAILURE TYPE IDS VALIDATED
✓ FAILURE TYPE VOCABULARY VALIDATED
✓ NO PREDICTIVE / RISK LEAKAGE DETECTED
✓ PERMANENTLY SAVED
✓ RELOAD VERIFICATION PASSED
✓ DIM_FAILURETYPE READY FOR FACT TABLES
================================================================================

In [6]:
# ================================================================================
# KEYSTRA SOLUTION 4
# BRIDGE_SUPPLIERMATERIAL — FINAL CONTROLLED BUILD
# Supply Chain Risk & Operational Resilience Early-Warning System
# ================================================================================

import pandas as pd
import numpy as np
from pathlib import Path


# ================================================================================
# 0. REPRODUCIBILITY & PROJECT CONFIGURATION
# ================================================================================

RANDOM_SEED = 42
rng = np.random.default_rng(RANDOM_SEED)

REFERENCE_DATE = pd.Timestamp("2026-07-31")
START_DATE = pd.Timestamp("2022-01-01")

PROJECT_ROOT = Path(
    "/content/drive/MyDrive/KEYSTRA_SOLUTION_4"
)

DIMENSIONS_PATH = PROJECT_ROOT / "01_dimensions"

DIMENSIONS_PATH.mkdir(
    parents=True,
    exist_ok=True
)

OUTPUT_PATH = (
    DIMENSIONS_PATH /
    "Bridge_SupplierMaterial.csv"
)


# ================================================================================
# 1. REQUIRED MASTER DATA CHECK
# ================================================================================

print("=" * 80)
print("KEYSTRA — BRIDGE_SUPPLIERMATERIAL BUILD INITIALIZATION")
print("=" * 80)

required_supplier_cols = {
    "Supplier_ID",
    "Supplier_Category"
}

required_material_cols = {
    "Material_ID",
    "Category",
    "Sourcing_Type"
}

missing_supplier_cols = (
    required_supplier_cols
    - set(dim_supplier.columns)
)

missing_material_cols = (
    required_material_cols
    - set(dim_material.columns)
)

if missing_supplier_cols:
    raise ValueError(
        f"dim_supplier is missing required columns: "
        f"{missing_supplier_cols}"
    )

if missing_material_cols:
    raise ValueError(
        f"dim_material is missing required columns: "
        f"{missing_material_cols}"
    )

print("✓ REQUIRED MASTER DATA COLUMNS FOUND")


# ================================================================================
# 2. CLEAN MASTER DATA
# ================================================================================

supplier_master = (
    dim_supplier
    .copy()
    .reset_index(drop=True)
)

material_master = (
    dim_material
    .copy()
    .reset_index(drop=True)
)

supplier_master["Supplier_ID"] = (
    supplier_master["Supplier_ID"]
    .astype(str)
)

supplier_master["Supplier_Category"] = (
    supplier_master["Supplier_Category"]
    .astype(str)
)

material_master["Material_ID"] = (
    material_master["Material_ID"]
    .astype(str)
)

material_master["Category"] = (
    material_master["Category"]
    .astype(str)
)

material_master["Sourcing_Type"] = (
    material_master["Sourcing_Type"]
    .astype(str)
)


# ================================================================================
# 3. MASTER COUNT VALIDATION
# ================================================================================

if len(supplier_master) != 90:
    raise ValueError(
        f"Expected 90 suppliers, found "
        f"{len(supplier_master)}."
    )

if supplier_master["Supplier_ID"].nunique() != 90:
    raise ValueError(
        "Supplier_ID values are not unique."
    )

if len(material_master) != 60:
    raise ValueError(
        f"Expected 60 materials, found "
        f"{len(material_master)}."
    )

if material_master["Material_ID"].nunique() != 60:
    raise ValueError(
        "Material_ID values are not unique."
    )

print("✓ 90 SUPPLIERS CONFIRMED")
print("✓ 60 MATERIALS CONFIRMED")


# ================================================================================
# 4. CATEGORY COMPATIBILITY RULES
# ================================================================================

category_map = {

    "Mechanical / Rotating Equipment": [
        "Mechanical / Rotating Equipment",
        "Industrial / Process Consumables",
        "Valves / Piping / Flow"
    ],

    "Electrical / Power Systems": [
        "Electrical / Power Systems",
        "Instrumentation / Control",
        "Industrial / Process Consumables"
    ],

    "Instrumentation / Control": [
        "Instrumentation / Control",
        "Electrical / Power Systems",
        "Industrial / Process Consumables"
    ],

    "Valves / Piping / Flow": [
        "Valves / Piping / Flow",
        "Industrial / Process Consumables",
        "Mechanical / Rotating Equipment"
    ],

    "Chemicals / Lubricants": [
        "Chemicals / Lubricants",
        "Industrial / Process Consumables"
    ],

    "Safety / PPE": [
        "Safety / PPE",
        "Industrial / Process Consumables"
    ],

    "Renewable Energy Equipment": [
        "Electrical / Power Systems",
        "Industrial / Process Consumables"
    ],

    "Industrial / Process Consumables": [
        "Industrial / Process Consumables",
        "Chemicals / Lubricants",
        "Mechanical / Rotating Equipment",
        "Valves / Piping / Flow"
    ],

    "Multi-category / Integrated Industrial": [
        "Mechanical / Rotating Equipment",
        "Electrical / Power Systems",
        "Instrumentation / Control",
        "Valves / Piping / Flow",
        "Industrial / Process Consumables",
        "Chemicals / Lubricants",
        "Safety / PPE"
    ]
}


# ================================================================================
# 5. BUILD SUPPLIER POOLS BY MATERIAL CATEGORY
# ================================================================================

supplier_pools = {}

for material_category in (
    material_master["Category"].unique()
):

    compatible_supplier_ids = []

    for _, supplier in supplier_master.iterrows():

        supplier_category = (
            supplier["Supplier_Category"]
        )

        allowed_categories = category_map.get(
            supplier_category,
            []
        )

        if material_category in allowed_categories:

            compatible_supplier_ids.append(
                supplier["Supplier_ID"]
            )

    supplier_pools[
        material_category
    ] = compatible_supplier_ids


# ================================================================================
# 6. VALIDATE CATEGORY COVERAGE
# ================================================================================

for category, pool in supplier_pools.items():

    if len(pool) == 0:
        raise ValueError(
            f"No compatible suppliers found for "
            f"material category: {category}"
        )

print(
    "✓ ALL MATERIAL CATEGORIES HAVE "
    "COMPATIBLE SUPPLIER POOLS"
)


# ================================================================================
# 7. SOURCING REQUIREMENTS
# ================================================================================

sourcing_requirements = {

    "Single-source": 1,
    "Dual-source": 2,
    "Multi-source": 3
}

invalid_sourcing_types = (
    set(material_master["Sourcing_Type"])
    - set(sourcing_requirements.keys())
)

if invalid_sourcing_types:

    raise ValueError(
        f"Unexpected sourcing types found: "
        f"{invalid_sourcing_types}"
    )


# ================================================================================
# 8. INITIAL NETWORK CONSTRUCTION
# ================================================================================

bridge_records = []

for _, material in material_master.iterrows():

    material_id = material["Material_ID"]

    material_category = material["Category"]

    sourcing_type = material["Sourcing_Type"]

    required_supplier_count = (
        sourcing_requirements[
            sourcing_type
        ]
    )

    candidates = (
        supplier_pools[
            material_category
        ].copy()
    )

    if len(candidates) < required_supplier_count:

        raise ValueError(
            f"Material {material_id} requires "
            f"{required_supplier_count} suppliers "
            f"but only {len(candidates)} compatible "
            f"suppliers exist."
        )

    selected = rng.choice(
        candidates,
        size=required_supplier_count,
        replace=False
    )

    for position, supplier_id in enumerate(
        selected
    ):

        qualification_type = (
            "Primary"
            if position == 0
            else "Compatible"
        )

        bridge_records.append({

            "Supplier_ID": supplier_id,

            "Material_ID": material_id,

            "Qualification_Type":
                qualification_type,

            "Qualified_From":
                START_DATE,

            "Qualified_To":
                REFERENCE_DATE
        })


bridge_supplier_material = pd.DataFrame(
    bridge_records
)


# ================================================================================
# 9. IDENTIFY SUPPLIERS WITHOUT COVERAGE
# ================================================================================

all_supplier_ids = set(
    supplier_master["Supplier_ID"]
)

represented_supplier_ids = set(
    bridge_supplier_material[
        "Supplier_ID"
    ]
)

missing_supplier_ids = sorted(
    all_supplier_ids
    - represented_supplier_ids
)

print(
    f"\nSuppliers initially represented : "
    f"{len(represented_supplier_ids)}"
)

print(
    f"Suppliers requiring coverage    : "
    f"{len(missing_supplier_ids)}"
)


# ================================================================================
# 10. ADD MISSING SUPPLIERS WITHOUT BREAKING SOURCING STRUCTURE
# ================================================================================
#
# IMPORTANT:
#
# Single-source  -> MUST remain exactly 1
# Dual-source    -> MUST remain exactly 2
# Multi-source   -> MUST remain >= 3
#
# Therefore:
#
# We only use Multi-source materials with
# available capacity when adding missing suppliers.
#
# This prevents the structural problem in the
# previous version.
# ================================================================================

for supplier_id in missing_supplier_ids:

    supplier_row = supplier_master[
        supplier_master["Supplier_ID"]
        == supplier_id
    ].iloc[0]

    supplier_category = (
        supplier_row["Supplier_Category"]
    )

    allowed_categories = category_map.get(
        supplier_category,
        []
    )

    candidate_materials = []

    for _, material in material_master.iterrows():

        material_id = material["Material_ID"]

        material_category = material["Category"]

        sourcing_type = material["Sourcing_Type"]

        if material_category not in allowed_categories:
            continue

        # Only Multi-source materials can absorb
        # additional supplier relationships safely.

        if sourcing_type != "Multi-source":
            continue

        existing_pair = (
            (
                bridge_supplier_material[
                    "Supplier_ID"
                ]
                == supplier_id
            )
            &
            (
                bridge_supplier_material[
                    "Material_ID"
                ]
                == material_id
            )
        ).any()

        if existing_pair:
            continue

        current_supplier_count = (
            bridge_supplier_material[
                bridge_supplier_material[
                    "Material_ID"
                ]
                == material_id
            ]
            ["Supplier_ID"]
            .nunique()
        )

        candidate_materials.append({

            "Material_ID":
                material_id,

            "Current_Supplier_Count":
                current_supplier_count
        })


    # --------------------------------------------------------------------------
    # If no Multi-source material exists for this supplier,
    # we cannot force an invalid relationship.
    # --------------------------------------------------------------------------

    if len(candidate_materials) == 0:

        raise ValueError(
            f"Supplier {supplier_id} could not be represented "
            f"without violating sourcing structure."
        )


    candidate_materials = pd.DataFrame(
        candidate_materials
    )


    # Prefer materials with lower current coverage
    # to distribute the network.

    candidate_materials = (
        candidate_materials
        .sort_values(
            "Current_Supplier_Count"
        )
        .reset_index(drop=True)
    )


    selected_material_id = (
        candidate_materials
        .iloc[0]
        ["Material_ID"]
    )


    bridge_supplier_material.loc[
        len(bridge_supplier_material)
    ] = {

        "Supplier_ID":
            supplier_id,

        "Material_ID":
            selected_material_id,

        "Qualification_Type":
            "Compatible",

        "Qualified_From":
            START_DATE,

        "Qualified_To":
            REFERENCE_DATE
    }


# ================================================================================
# 11. REMOVE DUPLICATE RELATIONSHIPS
# ================================================================================

bridge_supplier_material = (
    bridge_supplier_material
    .drop_duplicates(
        subset=[
            "Supplier_ID",
            "Material_ID"
        ],
        keep="first"
    )
    .reset_index(drop=True)
)


# ================================================================================
# 12. SORT
# ================================================================================

qualification_order = {
    "Primary": 0,
    "Compatible": 1
}

bridge_supplier_material[
    "_Qualification_Order"
] = (
    bridge_supplier_material[
        "Qualification_Type"
    ]
    .map(qualification_order)
)

bridge_supplier_material = (
    bridge_supplier_material
    .sort_values(
        by=[
            "Material_ID",
            "_Qualification_Order",
            "Supplier_ID"
        ]
    )
    .drop(
        columns="_Qualification_Order"
    )
    .reset_index(drop=True)
)


# ================================================================================
# 13. STRUCTURAL VALIDATION
# ================================================================================

print("\n" + "=" * 80)
print("KEYSTRA — BRIDGE_SUPPLIERMATERIAL VALIDATION")
print("=" * 80)

print(
    f"Rows                     : "
    f"{len(bridge_supplier_material):,}"
)

print(
    f"Unique Suppliers         : "
    f"{bridge_supplier_material['Supplier_ID'].nunique():,}"
)

print(
    f"Unique Materials         : "
    f"{bridge_supplier_material['Material_ID'].nunique():,}"
)

print(
    f"Unique Supplier-Material : "
    f"{bridge_supplier_material[['Supplier_ID', 'Material_ID']].drop_duplicates().shape[0]:,}"
)


# ================================================================================
# 14. ALL SUPPLIERS VALIDATION
# ================================================================================

supplier_coverage = (
    bridge_supplier_material
    .groupby("Supplier_ID")
    .size()
)

missing_suppliers = (
    all_supplier_ids
    - set(supplier_coverage.index)
)

if missing_suppliers:

    raise ValueError(
        f"Suppliers missing from bridge: "
        f"{missing_suppliers}"
    )

print(
    "✓ ALL 90 SUPPLIERS HAVE MATERIAL COVERAGE"
)


# ================================================================================
# 15. ALL MATERIALS VALIDATION
# ================================================================================

all_material_ids = set(
    material_master["Material_ID"]
)

represented_material_ids = set(
    bridge_supplier_material[
        "Material_ID"
    ]
)

missing_materials = (
    all_material_ids
    - represented_material_ids
)

if missing_materials:

    raise ValueError(
        f"Materials missing suppliers: "
        f"{missing_materials}"
    )

print(
    "✓ ALL 60 MATERIALS HAVE QUALIFIED SUPPLIERS"
)


# ================================================================================
# 16. DUPLICATE VALIDATION
# ================================================================================

duplicate_count = (
    bridge_supplier_material
    .duplicated(
        subset=[
            "Supplier_ID",
            "Material_ID"
        ]
    )
    .sum()
)

if duplicate_count > 0:

    raise ValueError(
        f"Found {duplicate_count} duplicate "
        f"supplier-material relationships."
    )

print(
    "✓ NO DUPLICATE SUPPLIER-MATERIAL RELATIONSHIPS"
)


# ================================================================================
# 17. FOREIGN KEY VALIDATION
# ================================================================================

invalid_suppliers = (
    set(
        bridge_supplier_material[
            "Supplier_ID"
        ]
    )
    - all_supplier_ids
)

invalid_materials = (
    set(
        bridge_supplier_material[
            "Material_ID"
        ]
    )
    - all_material_ids
)

if invalid_suppliers:

    raise ValueError(
        f"Invalid Supplier_ID values: "
        f"{invalid_suppliers}"
    )

if invalid_materials:

    raise ValueError(
        f"Invalid Material_ID values: "
        f"{invalid_materials}"
    )

print("✓ SUPPLIER FOREIGN KEYS VALID")
print("✓ MATERIAL FOREIGN KEYS VALID")


# ================================================================================
# 18. CATEGORY COMPATIBILITY VALIDATION
# ================================================================================

validation_join = (
    bridge_supplier_material
    .merge(
        supplier_master[
            [
                "Supplier_ID",
                "Supplier_Category"
            ]
        ],
        on="Supplier_ID",
        how="left"
    )
    .merge(
        material_master[
            [
                "Material_ID",
                "Category"
            ]
        ],
        on="Material_ID",
        how="left"
    )
)

invalid_relationships = []

for _, row in validation_join.iterrows():

    supplier_category = (
        row["Supplier_Category"]
    )

    material_category = (
        row["Category"]
    )

    allowed_categories = category_map.get(
        supplier_category,
        []
    )

    if material_category not in allowed_categories:

        invalid_relationships.append(
            (
                row["Supplier_ID"],
                row["Material_ID"],
                supplier_category,
                material_category
            )
        )


if invalid_relationships:

    raise ValueError(
        "Invalid supplier-material category "
        "relationships detected:\n"
        + str(
            invalid_relationships[:10]
        )
    )

print(
    "✓ SUPPLIER-MATERIAL CATEGORY "
    "COMPATIBILITY VALIDATED"
)


# ================================================================================
# 19. QUALIFICATION TYPE VALIDATION
# ================================================================================

valid_qualification_types = {
    "Primary",
    "Compatible"
}

invalid_qualification_types = (
    set(
        bridge_supplier_material[
            "Qualification_Type"
        ]
    )
    - valid_qualification_types
)

if invalid_qualification_types:

    raise ValueError(
        f"Invalid qualification types: "
        f"{invalid_qualification_types}"
    )

print(
    "✓ QUALIFICATION TYPES VALIDATED"
)


# ================================================================================
# 20. DATE VALIDATION
# ================================================================================

bridge_supplier_material[
    "Qualified_From"
] = pd.to_datetime(
    bridge_supplier_material[
        "Qualified_From"
    ]
)

bridge_supplier_material[
    "Qualified_To"
] = pd.to_datetime(
    bridge_supplier_material[
        "Qualified_To"
    ]
)


if (
    bridge_supplier_material[
        "Qualified_From"
    ]
    >
    bridge_supplier_material[
        "Qualified_To"
    ]
).any():

    raise ValueError(
        "Qualified_From cannot be later "
        "than Qualified_To."
    )


if (
    bridge_supplier_material[
        "Qualified_From"
    ]
    < START_DATE
).any():

    raise ValueError(
        "Qualification dates precede "
        "project start date."
    )


if (
    bridge_supplier_material[
        "Qualified_To"
    ]
    > REFERENCE_DATE
).any():

    raise ValueError(
        "Qualification dates exceed "
        "reference date."
    )

print(
    "✓ QUALIFICATION DATES VALIDATED"
)


# ================================================================================
# 21. SOURCING STRUCTURE VALIDATION
# ================================================================================

material_supplier_counts = (
    bridge_supplier_material
    .groupby("Material_ID")[
        "Supplier_ID"
    ]
    .nunique()
)

material_sourcing_check = (
    material_master[
        [
            "Material_ID",
            "Sourcing_Type"
        ]
    ]
    .merge(
        material_supplier_counts.rename(
            "Actual_Supplier_Count"
        ),
        on="Material_ID",
        how="left"
    )
)

material_sourcing_check[
    "Actual_Supplier_Count"
] = (
    material_sourcing_check[
        "Actual_Supplier_Count"
    ]
    .fillna(0)
    .astype(int)
)


def validate_sourcing(row):

    sourcing_type = row[
        "Sourcing_Type"
    ]

    count = row[
        "Actual_Supplier_Count"
    ]

    if sourcing_type == "Single-source":
        return count == 1

    elif sourcing_type == "Dual-source":
        return count == 2

    elif sourcing_type == "Multi-source":
        return count >= 3

    return False


material_sourcing_check[
    "Valid"
] = (
    material_sourcing_check
    .apply(
        validate_sourcing,
        axis=1
    )
)


invalid_sourcing = (
    material_sourcing_check[
        ~material_sourcing_check["Valid"]
    ]
)

if len(invalid_sourcing) > 0:

    raise ValueError(
        "Sourcing structure is invalid:\n"
        + str(
            invalid_sourcing[
                [
                    "Material_ID",
                    "Sourcing_Type",
                    "Actual_Supplier_Count"
                ]
            ]
        )
    )

print(
    "✓ SINGLE-SOURCE STRUCTURE VALIDATED"
)

print(
    "✓ DUAL-SOURCE STRUCTURE VALIDATED"
)

print(
    "✓ MULTI-SOURCE STRUCTURE VALIDATED"
)


# ================================================================================
# 22. PRIMARY SUPPLIER VALIDATION
# ================================================================================

primary_counts = (
    bridge_supplier_material
    .groupby("Material_ID")[
        "Qualification_Type"
    ]
    .apply(
        lambda x:
        (x == "Primary").sum()
    )
)

invalid_primary = (
    primary_counts[
        primary_counts != 1
    ]
)

if len(invalid_primary) > 0:

    raise ValueError(
        "Every material must have exactly "
        "one Primary supplier."
    )

print(
    "✓ EXACTLY ONE PRIMARY SUPPLIER "
    "PER MATERIAL VALIDATED"
)


# ================================================================================
# 23. LEAKAGE VALIDATION
# ================================================================================

for forbidden_column in [

    "Supplier_Risk_Score",
    "Risk_Score",
    "Risk_Tier",
    "Failure_Label",
    "Failure_State",
    "Deterioration_State",
    "Target_90D",
    "Failure_Probability",
    "Supplier_Behaviour",
    "Days_To_Failure",
    "OTD",
    "Fulfilment_Rate",
    "Quality_Rate"

]:

    if forbidden_column in (
        bridge_supplier_material.columns
    ):

        raise ValueError(
            f"Potential leakage column detected: "
            f"{forbidden_column}"
        )

print(
    "✓ NO PREDICTIVE / RISK LEAKAGE DETECTED"
)


# ================================================================================
# 24. DISTRIBUTION REPORT
# ================================================================================

print("\nSourcing Type Distribution:")

print(
    material_master[
        "Sourcing_Type"
    ]
    .value_counts()
    .sort_index()
    .to_string()
)


print("\nSupplier Count Per Material:")

print(
    material_supplier_counts
    .describe()
    .to_string()
)


print("\nSupplier Coverage:")

print(
    supplier_coverage
    .describe()
    .to_string()
)


print("\nQualification Type Distribution:")

print(
    bridge_supplier_material[
        "Qualification_Type"
    ]
    .value_counts()
    .to_string()
)


# ================================================================================
# 25. PREVIEW
# ================================================================================

print(
    "\nBRIDGE_SUPPLIERMATERIAL PREVIEW:\n"
)

display(
    bridge_supplier_material.head(20)
)


# ================================================================================
# 26. PERMANENT SAVE
# ================================================================================

print("\n" + "=" * 80)
print("PERMANENT SAVE — BRIDGE_SUPPLIERMATERIAL")
print("=" * 80)

bridge_supplier_material.to_csv(
    OUTPUT_PATH,
    index=False
)

if not OUTPUT_PATH.exists():

    raise FileNotFoundError(
        "Bridge_SupplierMaterial.csv "
        "was not created."
    )

print(
    f"✓ Saved to : {OUTPUT_PATH}"
)

print(
    f"✓ File size : "
    f"{OUTPUT_PATH.stat().st_size:,} bytes"
)


# ================================================================================
# 27. POST-SAVE RELOAD VERIFICATION
# ================================================================================

print(
    "\nPOST-SAVE RELOAD VERIFICATION — "
    "BRIDGE_SUPPLIERMATERIAL"
)

bridge_reload = pd.read_csv(
    OUTPUT_PATH
)

bridge_reload[
    "Qualified_From"
] = pd.to_datetime(
    bridge_reload[
        "Qualified_From"
    ]
)

bridge_reload[
    "Qualified_To"
] = pd.to_datetime(
    bridge_reload[
        "Qualified_To"
    ]
)

assert (
    len(bridge_reload)
    ==
    len(bridge_supplier_material)
)

assert (
    bridge_reload[
        "Supplier_ID"
    ].nunique()
    == 90
)

assert (
    bridge_reload[
        "Material_ID"
    ].nunique()
    == 60
)

assert (
    bridge_reload[
        [
            "Supplier_ID",
            "Material_ID"
        ]
    ]
    .drop_duplicates()
    .shape[0]
    ==
    len(bridge_reload)
)

print("✓ Reloaded successfully")
print(
    f"✓ Rows       : "
    f"{len(bridge_reload):,}"
)

print(
    f"✓ Suppliers  : "
    f"{bridge_reload['Supplier_ID'].nunique():,}"
)

print(
    f"✓ Materials  : "
    f"{bridge_reload['Material_ID'].nunique():,}"
)

print(
    "✓ Permanent file verified"
)


# ================================================================================
# 28. FINAL STATUS
# ================================================================================

print("\n" + "=" * 80)
print("KEYSTRA MASTER DATA FOUNDATION — BRIDGE COMPLETE")
print("=" * 80)

print("✓ 90 SUPPLIERS REPRESENTED")
print("✓ 60 MATERIALS REPRESENTED")
print("✓ ALL MATERIALS HAVE QUALIFIED SUPPLIERS")
print("✓ EVERY SUPPLIER HAS MATERIAL COVERAGE")
print("✓ SINGLE-SOURCE MATERIALS VALIDATED")
print("✓ DUAL-SOURCE MATERIALS VALIDATED")
print("✓ MULTI-SOURCE MATERIALS VALIDATED")
print("✓ ONE PRIMARY SUPPLIER PER MATERIAL")
print("✓ CATEGORY COMPATIBILITY VALIDATED")
print("✓ NO DUPLICATE RELATIONSHIPS")
print("✓ FOREIGN KEYS VALIDATED")
print("✓ QUALIFICATION DATES VALIDATED")
print("✓ NO PREDICTIVE / RISK LEAKAGE")
print("✓ PERMANENT SAVE VERIFIED")
print("=" * 80)

print(
    "\nNEXT OBJECT: Fact_PurchaseOrder"
)

print(
    "PRIMARY PREDICTIVE OBJECTIVE: "
    "SUPPLIER FAILURE PREDICTION"
)

print("=" * 80)

================================================================================
KEYSTRA — BRIDGE_SUPPLIERMATERIAL BUILD INITIALIZATION
================================================================================
✓ REQUIRED MASTER DATA COLUMNS FOUND
✓ 90 SUPPLIERS CONFIRMED
✓ 60 MATERIALS CONFIRMED
✓ ALL MATERIAL CATEGORIES HAVE COMPATIBLE SUPPLIER POOLS

Suppliers initially represented : 71
Suppliers requiring coverage    : 19

================================================================================
KEYSTRA — BRIDGE_SUPPLIERMATERIAL VALIDATION
================================================================================
Rows                     : 174
Unique Suppliers         : 90
Unique Materials         : 60
Unique Supplier-Material : 174
✓ ALL 90 SUPPLIERS HAVE MATERIAL COVERAGE
✓ ALL 60 MATERIALS HAVE QUALIFIED SUPPLIERS
✓ NO DUPLICATE SUPPLIER-MATERIAL RELATIONSHIPS
✓ SUPPLIER FOREIGN KEYS VALID
✓ MATERIAL FOREIGN KEYS VALID
✓ SUPPLIER-MATERIAL CATEGORY COMPATIBILITY VALIDATED
✓ QUALIFICATION TYPES VALIDATED
✓ QUALIFICATION DATES VALIDATED
✓ SINGLE-SOURCE STRUCTURE VALIDATED
✓ DUAL-SOURCE STRUCTURE VALIDATED
✓ MULTI-SOURCE STRUCTURE VALIDATED
✓ EXACTLY ONE PRIMARY SUPPLIER PER MATERIAL VALIDATED
✓ NO PREDICTIVE / RISK LEAKAGE DETECTED

Sourcing Type Distribution:
Sourcing_Type
Dual-source      11
Multi-source     42
Single-source     7

Supplier Count Per Material:
count    60.000000
mean      2.900000
std       0.986347
min       1.000000
25%       2.000000
50%       3.000000
75%       4.000000
max       4.000000

Supplier Coverage:
count    90.000000
mean      1.933333
std       1.243410
min       1.000000
25%       1.000000
50%       1.000000
75%       3.000000
max       5.000000

Qualification Type Distribution:
Qualification_Type
Compatible    114
Primary        60

BRIDGE_SUPPLIERMATERIAL PREVIEW:

   Supplier_ID Material_ID Qualification_Type Qualified_From Qualified_To
0         S004        M001            Primary     2022-01-01   2026-07-31
1         S059        M002            Primary     2022-01-01   2026-07-31
2         S053        M003            Primary     2022-01-01   2026-07-31
3         S031        M004            Primary     2022-01-01   2026-07-31
4         S028        M005            Primary     2022-01-01   2026-07-31
5         S086        M006            Primary     2022-01-01   2026-07-31
6         S055        M007            Primary     2022-01-01   2026-07-31
7         S004        M007         Compatible     2022-01-01   2026-07-31
8         S019        M008            Primary     2022-01-01   2026-07-31
9         S034        M008         Compatible     2022-01-01   2026-07-31
10        S081        M009            Primary     2022-01-01   2026-07-31
11        S057        M010            Primary     2022-01-01   2026-07-31
12        S056        M010         Compatible     2022-01-01   2026-07-31
13        S047        M011            Primary     2022-01-01   2026-07-31
14        S006        M011         Compatible     2022-01-01   2026-07-31
15        S029        M012            Primary     2022-01-01   2026-07-31
16        S021        M012         Compatible     2022-01-01   2026-07-31
17        S031        M012         Compatible     2022-01-01   2026-07-31
18        S033        M012         Compatible     2022-01-01   2026-07-31
19        S053        M013            Primary     2022-01-01   2026-07-31

================================================================================
PERMANENT SAVE — BRIDGE_SUPPLIERMATERIAL
================================================================================
✓ Saved to : /content/drive/MyDrive/KEYSTRA_SOLUTION_4/01_dimensions/Bridge_SupplierMaterial.csv
✓ File size : 7,373 bytes

POST-SAVE RELOAD VERIFICATION — BRIDGE_SUPPLIERMATERIAL
✓ Reloaded successfully
✓ Rows       : 174
✓ Suppliers  : 90
✓ Materials  : 60
✓ Permanent file verified

================================================================================
KEYSTRA MASTER DATA FOUNDATION — BRIDGE COMPLETE
================================================================================
✓ 90 SUPPLIERS REPRESENTED
✓ 60 MATERIALS REPRESENTED
✓ ALL MATERIALS HAVE QUALIFIED SUPPLIERS
✓ EVERY SUPPLIER HAS MATERIAL COVERAGE
✓ SINGLE-SOURCE MATERIALS VALIDATED
✓ DUAL-SOURCE MATERIALS VALIDATED
✓ MULTI-SOURCE MATERIALS VALIDATED
✓ ONE PRIMARY SUPPLIER PER MATERIAL
✓ CATEGORY COMPATIBILITY VALIDATED
✓ NO DUPLICATE RELATIONSHIPS
✓ FOREIGN KEYS VALIDATED
✓ QUALIFICATION DATES VALIDATED
✓ NO PREDICTIVE / RISK LEAKAGE
✓ PERMANENT SAVE VERIFIED
================================================================================

NEXT OBJECT: Fact_PurchaseOrder
PRIMARY PREDICTIVE OBJECTIVE: SUPPLIER FAILURE PREDICTION
================================================================================

In [7]:
# ================================================================================
# KEYSTRA SOLUTION 4
# BRIDGE_ASSETMATERIAL
# Supply Chain Risk & Operational Resilience Early-Warning System
#
# PURPOSE
# -------
# Establish realistic Asset ↔ Material dependencies.
#
# This bridge answers:
# "Which materials does each asset require?"
#
# IMPORTANT
# ---------
# - Uses existing Dim_Asset
# - Uses existing Dim_Material
# - Does NOT recreate either dimension
# - Does NOT introduce predictive/risk labels
# - Does NOT use future operational outcomes
# - Permanently saves the bridge
# - Performs post-save reload verification
# ================================================================================

import pandas as pd
import numpy as np
from pathlib import Path


# ================================================================================
# 0. CONFIGURATION
# ================================================================================

SEED = 42
rng = np.random.default_rng(SEED)

REFERENCE_DATE = pd.Timestamp("2026-07-31")
START_DATE = pd.Timestamp("2022-01-01")

EXPECTED_ASSETS = 13
EXPECTED_MATERIALS = 60

PROJECT_ROOT = Path(
    "/content/drive/MyDrive/KEYSTRA_SOLUTION_4"
)

BRIDGE_PATH = (
    PROJECT_ROOT
    / "02_bridges"
)

BRIDGE_PATH.mkdir(
    parents=True,
    exist_ok=True
)

OUTPUT_FILE = (
    BRIDGE_PATH
    / "Bridge_AssetMaterial.csv"
)


# ================================================================================
# 1. REQUIRED DATASET CHECK
# ================================================================================

print("=" * 80)
print("KEYSTRA — BRIDGE_ASSETMATERIAL BUILD INITIALIZATION")
print("=" * 80)

required_objects = [
    "dim_asset",
    "dim_material"
]

for obj in required_objects:

    if obj not in globals():

        raise NameError(
            f"Required dataframe '{obj}' was not found. "
            f"Run Dim_Asset and Dim_Material first."
        )

print("✓ Dim_Asset found")
print("✓ Dim_Material found")


# ================================================================================
# 2. WORK ON COPIES
# ================================================================================

asset_master = (
    dim_asset
    .copy()
    .reset_index(drop=True)
)

material_master = (
    dim_material
    .copy()
    .reset_index(drop=True)
)


# ================================================================================
# 3. REQUIRED COLUMN VALIDATION
# ================================================================================

required_asset_columns = [
    "Asset_ID"
]

required_material_columns = [
    "Material_ID",
    "Category",
    "Criticality_Tier",
    "Demand_Profile",
    "Safety_Stock_Qty",
    "Reorder_Point_Qty"
]

missing_asset_cols = [
    col
    for col in required_asset_columns
    if col not in asset_master.columns
]

missing_material_cols = [
    col
    for col in required_material_columns
    if col not in material_master.columns
]

if missing_asset_cols:

    raise ValueError(
        f"Dim_Asset is missing required columns: "
        f"{missing_asset_cols}"
    )

if missing_material_cols:

    raise ValueError(
        f"Dim_Material is missing required columns: "
        f"{missing_material_cols}"
    )


# ================================================================================
# 4. MASTER DATA TYPE STANDARDISATION
# ================================================================================

asset_master["Asset_ID"] = (
    asset_master["Asset_ID"]
    .astype(str)
)

material_master["Material_ID"] = (
    material_master["Material_ID"]
    .astype(str)
)

if "Active_From" in asset_master.columns:

    asset_master["Active_From"] = pd.to_datetime(
        asset_master["Active_From"],
        errors="coerce"
    )

if "Active_From" in material_master.columns:

    material_master["Active_From"] = pd.to_datetime(
        material_master["Active_From"],
        errors="coerce"
    )


# ================================================================================
# 5. EXACT MASTER COUNTS
# ================================================================================

if len(asset_master) != EXPECTED_ASSETS:

    raise ValueError(
        f"Expected {EXPECTED_ASSETS} assets, "
        f"found {len(asset_master)}."
    )

if len(material_master) != EXPECTED_MATERIALS:

    raise ValueError(
        f"Expected {EXPECTED_MATERIALS} materials, "
        f"found {len(material_master)}."
    )

if (
    asset_master["Asset_ID"].nunique()
    != EXPECTED_ASSETS
):

    raise ValueError(
        "Asset_ID values are not unique."
    )

if (
    material_master["Material_ID"].nunique()
    != EXPECTED_MATERIALS
):

    raise ValueError(
        "Material_ID values are not unique."
    )

print(
    f"✓ {EXPECTED_ASSETS} assets confirmed"
)

print(
    f"✓ {EXPECTED_MATERIALS} materials confirmed"
)


# ================================================================================
# 6. ASSET CLASSIFICATION
# ================================================================================
#
# Classification is used ONLY to establish legitimate
# asset-material dependencies.
#
# It is NOT a predictive variable.
# ================================================================================

def classify_asset(row):

    text_parts = []

    for col in [
        "Asset_Name",
        "Asset_Type",
        "Location",
        "Business_Unit_ID"
    ]:

        if (
            col in row.index
            and pd.notna(row[col])
        ):

            text_parts.append(
                str(row[col]).lower()
            )

    text = " ".join(text_parts)

    if any(
        x in text
        for x in [
            "refinery",
            "fractionation",
            "process",
            "processing",
            "gas plant",
            "gas processing",
            "chemical"
        ]
    ):

        return "PROCESS"

    if any(
        x in text
        for x in [
            "power",
            "transformer",
            "generation",
            "generator",
            "electrical"
        ]
    ):

        return "POWER"

    if any(
        x in text
        for x in [
            "compressor",
            "turbine",
            "pump",
            "rotating",
            "mechanical"
        ]
    ):

        return "ROTATING"

    if any(
        x in text
        for x in [
            "offshore",
            "platform",
            "subsea"
        ]
    ):

        return "OFFSHORE"

    if any(
        x in text
        for x in [
            "lng",
            "liquefaction"
        ]
    ):

        return "LNG"

    if any(
        x in text
        for x in [
            "solar",
            "wind",
            "renewable",
            "renewables"
        ]
    ):

        return "RENEWABLE"

    return "GENERAL"


asset_master["_Asset_Class"] = (
    asset_master
    .apply(
        classify_asset,
        axis=1
    )
)


# ================================================================================
# 7. MATERIAL CATEGORY NORMALISATION
# ================================================================================

CATEGORY_MAP = {

    "Mechanical / Rotating Equipment":
        "MECHANICAL",

    "Electrical / Power Systems":
        "ELECTRICAL",

    "Instrumentation / Control":
        "INSTRUMENTATION",

    "Valves / Piping / Flow":
        "VALVES",

    "Chemicals / Lubricants":
        "CHEMICALS",

    "Industrial / Process Consumables":
        "PROCESS",

    "Safety / PPE":
        "SAFETY"
}

material_master["_Material_Class"] = (
    material_master["Category"]
    .map(CATEGORY_MAP)
    .fillna("GENERAL")
)


# ================================================================================
# 8. ASSET ↔ MATERIAL COMPATIBILITY RULES
# ================================================================================

compatibility = {

    "MECHANICAL": {

        "ROTATING": 10,
        "PROCESS": 8,
        "OFFSHORE": 8,
        "LNG": 8,
        "POWER": 6,
        "RENEWABLE": 5,
        "GENERAL": 5
    },

    "ELECTRICAL": {

        "POWER": 10,
        "OFFSHORE": 8,
        "LNG": 8,
        "PROCESS": 7,
        "ROTATING": 6,
        "RENEWABLE": 10,
        "GENERAL": 5
    },

    "INSTRUMENTATION": {

        "PROCESS": 10,
        "LNG": 10,
        "OFFSHORE": 9,
        "ROTATING": 7,
        "POWER": 8,
        "RENEWABLE": 7,
        "GENERAL": 5
    },

    "VALVES": {

        "PROCESS": 10,
        "LNG": 10,
        "OFFSHORE": 9,
        "ROTATING": 8,
        "POWER": 6,
        "RENEWABLE": 6,
        "GENERAL": 5
    },

    "CHEMICALS": {

        "PROCESS": 10,
        "LNG": 9,
        "ROTATING": 7,
        "OFFSHORE": 8,
        "POWER": 6,
        "RENEWABLE": 5,
        "GENERAL": 5
    },

    "PROCESS": {

        "PROCESS": 10,
        "LNG": 9,
        "OFFSHORE": 8,
        "ROTATING": 7,
        "POWER": 6,
        "RENEWABLE": 5,
        "GENERAL": 5
    },

    "SAFETY": {

        "OFFSHORE": 10,
        "PROCESS": 9,
        "LNG": 9,
        "ROTATING": 8,
        "POWER": 8,
        "RENEWABLE": 8,
        "GENERAL": 7
    }
}


# ================================================================================
# 9. CREATE COMPATIBLE CANDIDATE PAIRS
# ================================================================================

candidate_pairs = []

for _, asset in asset_master.iterrows():

    asset_id = asset["Asset_ID"]
    asset_class = asset["_Asset_Class"]

    for _, material in material_master.iterrows():

        material_id = material["Material_ID"]
        material_class = material["_Material_Class"]

        score = (
            compatibility
            .get(material_class, {})
            .get(asset_class, 5)
        )

        # Criticality increases dependency preference
        if material["Criticality_Tier"] == "Critical":

            score += 3

        elif material["Criticality_Tier"] == "High":

            score += 2

        elif material["Criticality_Tier"] == "Medium":

            score += 1

        # Demand profile
        if material["Demand_Profile"] == "High":

            score += 1

        candidate_pairs.append({

            "Asset_ID":
                asset_id,

            "Material_ID":
                material_id,

            "_Compatibility_Score":
                score
        })


candidate_pairs = pd.DataFrame(
    candidate_pairs
)


# ================================================================================
# 10. MATERIAL-LEVEL DEPENDENCY ASSIGNMENT
# ================================================================================

selected_pairs = []

for _, material in material_master.iterrows():

    material_id = material["Material_ID"]

    criticality = material["Criticality_Tier"]

    candidates = (
        candidate_pairs[
            candidate_pairs["Material_ID"]
            == material_id
        ]
        .copy()
    )

    candidates = (
        candidates
        .sort_values(
            "_Compatibility_Score",
            ascending=False
        )
    )

    # Critical / High / Medium:
    # 2–3 assets
    #
    # Low:
    # 1–3 assets

    if criticality == "Critical":

        n_assets = int(
            rng.integers(2, 4)
        )

    elif criticality == "High":

        n_assets = int(
            rng.integers(2, 4)
        )

    elif criticality == "Medium":

        n_assets = int(
            rng.integers(2, 4)
        )

    else:

        n_assets = int(
            rng.integers(1, 4)
        )

    n_assets = min(
        n_assets,
        len(candidates)
    )

    weights = (
        candidates["_Compatibility_Score"]
        .astype(float)
    )

    weights = (
        weights
        + rng.uniform(
            0,
            1,
            len(weights)
        )
    )

    probabilities = (
        weights
        / weights.sum()
    )

    chosen_indices = rng.choice(

        candidates.index,

        size=n_assets,

        replace=False,

        p=probabilities
    )

    for idx in chosen_indices:

        selected_pairs.append(
            candidates
            .loc[idx]
            .to_dict()
        )


bridge_asset_material = pd.DataFrame(
    selected_pairs
)


# ================================================================================
# 11. GUARANTEE EVERY ASSET HAS A MATERIAL
# ================================================================================

asset_coverage = set(
    bridge_asset_material["Asset_ID"]
)

missing_assets = [

    asset_id

    for asset_id
    in asset_master["Asset_ID"]

    if asset_id not in asset_coverage
]


for asset_id in missing_assets:

    asset_candidates = (
        candidate_pairs[
            candidate_pairs["Asset_ID"]
            == asset_id
        ]
        .copy()
    )

    existing_materials = set(

        bridge_asset_material.loc[
            bridge_asset_material["Asset_ID"]
            == asset_id,
            "Material_ID"
        ]
    )

    asset_candidates = (
        asset_candidates[
            ~asset_candidates["Material_ID"]
            .isin(existing_materials)
        ]
    )

    if asset_candidates.empty:

        raise ValueError(
            f"Could not assign a material "
            f"to asset {asset_id}."
        )

    best = (
        asset_candidates
        .sort_values(
            "_Compatibility_Score",
            ascending=False
        )
        .iloc[0]
    )

    bridge_asset_material = pd.concat(

        [
            bridge_asset_material,

            pd.DataFrame(
                [best]
            )
        ],

        ignore_index=True
    )


# ================================================================================
# 12. REMOVE DUPLICATES
# ================================================================================

bridge_asset_material = (
    bridge_asset_material
    .drop_duplicates(
        subset=[
            "Asset_ID",
            "Material_ID"
        ]
    )
    .reset_index(drop=True)
)


# ================================================================================
# 13. ASSIGN REQUIREMENT TYPE
# ================================================================================

material_lookup = (
    material_master
    .set_index("Material_ID")
)


def assign_requirement_type(row):

    material = (
        material_lookup
        .loc[row["Material_ID"]]
    )

    criticality = (
        material["Criticality_Tier"]
    )

    sourcing = (
        material["Sourcing_Type"]
    )

    if criticality == "Critical":

        return "Critical Dependency"

    if sourcing == "Single-source":

        return "Primary"

    if criticality == "High":

        return "Primary"

    return "Secondary"


bridge_asset_material[
    "Requirement_Type"
] = (
    bridge_asset_material
    .apply(
        assign_requirement_type,
        axis=1
    )
)


# ================================================================================
# 14. GENERATE BASELINE REQUIRED QUANTITY
# ================================================================================

def generate_required_quantity(
    material_id
):

    material = (
        material_lookup
        .loc[material_id]
    )

    criticality = (
        material["Criticality_Tier"]
    )

    demand = (
        material["Demand_Profile"]
    )

    if criticality == "Critical":

        base_range = (2, 12)

    elif criticality == "High":

        base_range = (5, 25)

    elif criticality == "Medium":

        base_range = (10, 60)

    else:

        base_range = (20, 120)

    qty = int(
        rng.integers(
            base_range[0],
            base_range[1] + 1
        )
    )

    if demand == "High":

        qty = int(qty * 1.5)

    elif demand == "Medium":

        qty = int(qty * 1.15)

    return max(
        1,
        qty
    )


bridge_asset_material[
    "Required_Qty"
] = (
    bridge_asset_material[
        "Material_ID"
    ]
    .apply(
        generate_required_quantity
    )
)


# ================================================================================
# 15. STATIC QUALIFICATION DATES
# ================================================================================

bridge_asset_material[
    "Qualified_From"
] = START_DATE

bridge_asset_material[
    "Qualified_To"
] = REFERENCE_DATE


# ================================================================================
# 16. FINAL COLUMN ORDER
# ================================================================================

bridge_asset_material = (
    bridge_asset_material[
        [
            "Asset_ID",
            "Material_ID",
            "Requirement_Type",
            "Required_Qty",
            "Qualified_From",
            "Qualified_To"
        ]
    ]
    .copy()
)


# ================================================================================
# 17. DATA TYPE CLEANUP
# ================================================================================

bridge_asset_material["Asset_ID"] = (
    bridge_asset_material["Asset_ID"]
    .astype(str)
)

bridge_asset_material["Material_ID"] = (
    bridge_asset_material["Material_ID"]
    .astype(str)
)

bridge_asset_material["Requirement_Type"] = (
    bridge_asset_material["Requirement_Type"]
    .astype(str)
)

bridge_asset_material["Required_Qty"] = (
    pd.to_numeric(
        bridge_asset_material["Required_Qty"],
        errors="raise"
    )
    .astype(int)
)

bridge_asset_material["Qualified_From"] = (
    pd.to_datetime(
        bridge_asset_material["Qualified_From"]
    )
)

bridge_asset_material["Qualified_To"] = (
    pd.to_datetime(
        bridge_asset_material["Qualified_To"]
    )
)


# ================================================================================
# 18. HARD VALIDATION
# ================================================================================

print("\n" + "=" * 80)
print("KEYSTRA — BRIDGE_ASSETMATERIAL VALIDATION")
print("=" * 80)

print(
    f"Rows                         : "
    f"{len(bridge_asset_material):,}"
)

print(
    f"Unique Assets                : "
    f"{bridge_asset_material['Asset_ID'].nunique():,}"
)

print(
    f"Unique Materials             : "
    f"{bridge_asset_material['Material_ID'].nunique():,}"
)

print(
    f"Unique Asset–Material        : "
    f"{bridge_asset_material[['Asset_ID','Material_ID']].drop_duplicates().shape[0]:,}"
)


# Duplicate check
assert not (
    bridge_asset_material
    .duplicated(
        [
            "Asset_ID",
            "Material_ID"
        ]
    )
    .any()
), (
    "Duplicate Asset–Material relationships detected."
)


# Asset coverage
assert (
    bridge_asset_material["Asset_ID"]
    .nunique()
    == EXPECTED_ASSETS
), (
    "Not every asset has a material dependency."
)


# Material coverage
assert (
    bridge_asset_material["Material_ID"]
    .nunique()
    == EXPECTED_MATERIALS
), (
    "Not every material is assigned to an asset."
)


# Foreign keys
assert set(
    bridge_asset_material["Asset_ID"]
).issubset(
    set(asset_master["Asset_ID"])
), (
    "Invalid Asset_ID foreign key detected."
)


assert set(
    bridge_asset_material["Material_ID"]
).issubset(
    set(material_master["Material_ID"])
), (
    "Invalid Material_ID foreign key detected."
)


# Null validation
assert not (
    bridge_asset_material[
        [
            "Asset_ID",
            "Material_ID",
            "Requirement_Type",
            "Required_Qty",
            "Qualified_From",
            "Qualified_To"
        ]
    ]
    .isnull()
    .any()
    .any()
), (
    "Null values detected."
)


# Quantity validation
assert (
    bridge_asset_material["Required_Qty"]
    > 0
).all(), (
    "Invalid Required_Qty detected."
)


# Requirement vocabulary
allowed_requirement_types = {
    "Critical Dependency",
    "Primary",
    "Secondary"
}

assert set(
    bridge_asset_material[
        "Requirement_Type"
    ]
).issubset(
    allowed_requirement_types
), (
    "Invalid Requirement_Type detected."
)


# Date validation
assert (
    bridge_asset_material["Qualified_From"]
    <= bridge_asset_material["Qualified_To"]
).all(), (
    "Invalid qualification date range."
)


assert (
    bridge_asset_material["Qualified_To"]
    <= REFERENCE_DATE
).all(), (
    "Qualification date extends beyond reference date."
)


# ================================================================================
# 19. PREDICTIVE / RISK LEAKAGE CHECK
# ================================================================================

for forbidden_col in [

    "Risk_Score",
    "Risk_Tier",
    "Failure_Label",
    "Failure_State",
    "Target_90D",
    "Supplier_Risk_Score",
    "Predicted_Risk",
    "Deterioration_State",
    "Failure_Probability",
    "Days_To_Failure"

]:

    assert (
        forbidden_col
        not in bridge_asset_material.columns
    ), (
        f"Predictive/risk leakage field detected: "
        f"{forbidden_col}"
    )


print(
    "✓ NO PREDICTIVE / RISK LEAKAGE DETECTED"
)


# ================================================================================
# 20. MATERIAL CATEGORY RESOLUTION
# ================================================================================

material_dependency_check = (
    bridge_asset_material
    .merge(
        material_master[
            [
                "Material_ID",
                "Criticality_Tier",
                "Category",
                "Sourcing_Type"
            ]
        ],
        on="Material_ID",
        how="left",
        validate="many_to_one"
    )
)

assert (
    material_dependency_check["Category"]
    .notna()
    .all()
), (
    "Unmapped material category detected."
)


print(
    "✓ MATERIAL CATEGORY RELATIONSHIPS RESOLVED"
)


# ================================================================================
# 21. DISTRIBUTION REPORT
# ================================================================================

print("\nRequirement Type Distribution:")

print(
    bridge_asset_material[
        "Requirement_Type"
    ]
    .value_counts()
    .sort_index()
    .to_string()
)


materials_per_asset = (
    bridge_asset_material
    .groupby("Asset_ID")["Material_ID"]
    .nunique()
)

print("\nMaterials Per Asset:")

print(
    materials_per_asset
    .describe()
    .to_string()
)


assets_per_material = (
    bridge_asset_material
    .groupby("Material_ID")["Asset_ID"]
    .nunique()
)

print("\nAssets Per Material:")

print(
    assets_per_material
    .describe()
    .to_string()
)


print("\nMaterial Criticality Coverage:")

print(
    material_dependency_check
    .groupby("Criticality_Tier")["Material_ID"]
    .nunique()
    .sort_index()
    .to_string()
)


print("\nRequired Quantity Summary:")

print(
    bridge_asset_material[
        "Required_Qty"
    ]
    .describe()
    .to_string()
)


# ================================================================================
# 22. PREVIEW
# ================================================================================

print("\nBRIDGE_ASSETMATERIAL PREVIEW:\n")

display(
    bridge_asset_material.head(20)
)


# ================================================================================
# 23. PERMANENT SAVE
# ================================================================================

print("\n" + "=" * 80)
print("PERMANENT SAVE — BRIDGE_ASSETMATERIAL")
print("=" * 80)

bridge_asset_material.to_csv(
    OUTPUT_FILE,
    index=False
)

print(
    f"✓ Saved to : {OUTPUT_FILE}"
)

print(
    f"✓ File size : "
    f"{OUTPUT_FILE.stat().st_size:,} bytes"
)


# ================================================================================
# 24. POST-SAVE RELOAD VERIFICATION
# ================================================================================

reloaded_bridge_asset_material = pd.read_csv(
    OUTPUT_FILE,
    parse_dates=[
        "Qualified_From",
        "Qualified_To"
    ]
)

assert (
    len(reloaded_bridge_asset_material)
    == len(bridge_asset_material)
), (
    "Reloaded row count does not match original."
)


assert (
    list(
        reloaded_bridge_asset_material.columns
    )
    ==
    list(
        bridge_asset_material.columns
    )
), (
    "Reloaded column structure does not match."
)


assert (
    reloaded_bridge_asset_material[
        [
            "Asset_ID",
            "Material_ID"
        ]
    ]
    .drop_duplicates()
    .shape[0]
    ==
    bridge_asset_material[
        [
            "Asset_ID",
            "Material_ID"
        ]
    ]
    .drop_duplicates()
    .shape[0]
), (
    "Reloaded relationship count does not match."
)


print(
    "✓ Reloaded successfully"
)

print(
    f"✓ Rows       : "
    f"{len(reloaded_bridge_asset_material):,}"
)

print(
    f"✓ Columns    : "
    f"{len(reloaded_bridge_asset_material.columns):,}"
)

print(
    f"✓ Assets     : "
    f"{reloaded_bridge_asset_material['Asset_ID'].nunique():,}"
)

print(
    f"✓ Materials   : "
    f"{reloaded_bridge_asset_material['Material_ID'].nunique():,}"
)

print(
    "✓ Permanent file verified"
)


# ================================================================================
# 25. FINAL SUCCESS
# ================================================================================

print("\n" + "=" * 80)
print("✓ BRIDGE_ASSETMATERIAL PASSED ALL VALIDATION CHECKS")
print("=" * 80)

print(
    f"✓ {EXPECTED_ASSETS} ASSETS CONFIRMED"
)

print(
    f"✓ {EXPECTED_MATERIALS} MATERIALS CONFIRMED"
)

print(
    "✓ EVERY ASSET HAS AT LEAST ONE MATERIAL DEPENDENCY"
)

print(
    "✓ EVERY MATERIAL IS USED BY AT LEAST ONE ASSET"
)

print(
    "✓ NO DUPLICATE ASSET–MATERIAL RELATIONSHIPS"
)

print(
    "✓ FOREIGN KEYS VALIDATED"
)

print(
    "✓ MATERIAL CRITICALITY RELATIONSHIPS VALIDATED"
)

print(
    "✓ REQUIREMENT QUANTITIES VALIDATED"
)

print(
    "✓ QUALIFICATION DATES VALIDATED"
)

print(
    "✓ NO PREDICTIVE / RISK LEAKAGE"
)

print(
    "✓ PERMANENTLY SAVED"
)

print(
    "✓ RELOAD VERIFICATION PASSED"
)

print("=" * 80)

================================================================================
KEYSTRA — BRIDGE_ASSETMATERIAL BUILD INITIALIZATION
================================================================================
✓ Dim_Asset found
✓ Dim_Material found
✓ 13 assets confirmed
✓ 60 materials confirmed

================================================================================
KEYSTRA — BRIDGE_ASSETMATERIAL VALIDATION
================================================================================
Rows                         : 141
Unique Assets                : 13
Unique Materials             : 60
Unique Asset–Material        : 141
✓ NO PREDICTIVE / RISK LEAKAGE DETECTED
✓ MATERIAL CATEGORY RELATIONSHIPS RESOLVED

Requirement Type Distribution:
Requirement_Type
Critical Dependency    24
Primary                38
Secondary              79

Materials Per Asset:
count    13.000000
mean     10.846154
std       2.339735
min       7.000000
25%       9.000000
50%      11.000000
75%      13.000000
max      14.000000

Assets Per Material:
count    60.000000
mean      2.350000
std       0.659353
min       1.000000
25%       2.000000
50%       2.000000
75%       3.000000
max       3.000000

Material Criticality Coverage:
Criticality_Tier
Critical    10
High        15
Low         15
Medium      20

Required Quantity Summary:
count    141.000000
mean      45.361702
std       41.141963
min        2.000000
25%       13.000000
50%       29.000000
75%       65.000000
max      178.000000

BRIDGE_ASSETMATERIAL PREVIEW:

,Asset_ID,Material_ID,Requirement_Type,Required_Qty,Qualified_From,Qualified_To
0,A007,M001,Critical Dependency,11,2022-01-01,2026-07-31
1,A003,M001,Critical Dependency,6,2022-01-01,2026-07-31
2,A006,M002,Critical Dependency,5,2022-01-01,2026-07-31
3,A009,M002,Critical Dependency,3,2022-01-01,2026-07-31
4,A013,M002,Critical Dependency,5,2022-01-01,2026-07-31
5,A001,M003,Critical Dependency,3,2022-01-01,2026-07-31
6,A002,M003,Critical Dependency,4,2022-01-01,2026-07-31
7,A003,M004,Critical Dependency,12,2022-01-01,2026-07-31
8,A010,M004,Critical Dependency,2,2022-01-01,2026-07-31
9,A012,M005,Critical Dependency,7,2022-01-01,2026-07-31
10,A013,M005,Critical Dependency,11,2022-01-01,2026-07-31
11,A001,M006,Critical Dependency,12,2022-01-01,2026-07-31
12,A002,M006,Critical Dependency,3,2022-01-01,2026-07-31
13,A011,M006,Critical Dependency,3,2022-01-01,2026-07-31
14,A010,M007,Critical Dependency,6,2022-01-01,2026-07-31
15,A003,M007,Critical Dependency,9,2022-01-01,2026-07-31
16,A008,M007,Critical Dependency,13,2022-01-01,2026-07-31
17,A002,M008,Critical Dependency,4,2022-01-01,2026-07-31
18,A013,M008,Critical Dependency,3,2022-01-01,2026-07-31
19,A009,M009,Critical Dependency,4,2022-01-01,2026-07-31

================================================================================
PERMANENT SAVE — BRIDGE_ASSETMATERIAL
================================================================================
✓ Saved to : /content/drive/MyDrive/KEYSTRA_SOLUTION_4/02_bridges/Bridge_AssetMaterial.csv
✓ File size : 6,578 bytes
✓ Reloaded successfully
✓ Rows       : 141
✓ Columns    : 6
✓ Assets     : 13
✓ Materials   : 60
✓ Permanent file verified

================================================================================
✓ BRIDGE_ASSETMATERIAL PASSED ALL VALIDATION CHECKS
================================================================================
✓ 13 ASSETS CONFIRMED
✓ 60 MATERIALS CONFIRMED
✓ EVERY ASSET HAS AT LEAST ONE MATERIAL DEPENDENCY
✓ EVERY MATERIAL IS USED BY AT LEAST ONE ASSET
✓ NO DUPLICATE ASSET–MATERIAL RELATIONSHIPS
✓ FOREIGN KEYS VALIDATED
✓ MATERIAL CRITICALITY RELATIONSHIPS VALIDATED
✓ REQUIREMENT QUANTITIES VALIDATED
✓ QUALIFICATION DATES VALIDATED
✓ NO PREDICTIVE / RISK LEAKAGE
✓ PERMANENTLY SAVED
✓ RELOAD VERIFICATION PASSED
================================================================================

In [8]:
# =============================================================================
# KEYSTRA — FACT_PURCHASEORDERLINE
# CLEAN PREDICTIVE REBUILD — FINAL VERSION
# =============================================================================
#
# PURPOSE
# -------
# Generate 40,000 realistic purchase-order lines supporting:
#
#   • Supplier behaviour analysis
#   • Delivery reliability
#   • Fulfilment analysis
#   • Procurement behaviour
#   • Outstanding exposure
#   • Supplier deterioration modelling
#   • Future supplier-failure prediction
#
# IMPORTANT
# ---------
# This table contains OBSERVED OPERATIONAL DATA only.
#
# It must NOT contain:
#
#   Supplier_Risk_Score
#   Risk_Tier
#   Failure_Label
#   Failure_State
#   Target_90D
#   Deterioration_State
#   Predicted_Risk
#
# REFERENCE DATE
# --------------
# 2026-07-31
#
# HISTORICAL PERIOD
# -----------------
# 2022-01-01 → 2026-07-31
#
# =============================================================================

import pandas as pd
import numpy as np


# =============================================================================
# 1. CONFIGURATION
# =============================================================================

SEED = 20260825
rng = np.random.default_rng(SEED)

N_PO_LINES = 40_000

START_DATE = pd.Timestamp("2022-01-01")
REFERENCE_DATE = pd.Timestamp("2026-07-31")

EXPECTED_SUPPLIERS = 90
EXPECTED_MATERIALS = 60
EXPECTED_ASSETS = 13


# =============================================================================
# 2. REQUIRED OBJECTS
# =============================================================================

required_objects = {
    "dim_supplier": "Dim_Supplier",
    "dim_material": "Dim_Material",
    "dim_asset": "Dim_Asset",
    "dim_date": "Dim_Date",
    "bridge_supplier_material": "Bridge_SupplierMaterial",
    "bridge_asset_material": "Bridge_AssetMaterial"
}

missing_objects = []

for variable_name, object_name in required_objects.items():

    if variable_name not in globals():
        missing_objects.append(object_name)


if missing_objects:

    raise ValueError(
        "Missing required objects: "
        + ", ".join(missing_objects)
        + ". Build them before Fact_PurchaseOrderLine."
    )


print("=" * 80)
print("KEYSTRA — FACT_PURCHASEORDERLINE BUILD")
print("=" * 80)


# =============================================================================
# 3. COPY SOURCE DATA
# =============================================================================

suppliers = dim_supplier.copy()
materials = dim_material.copy()
assets = dim_asset.copy()
dates = dim_date.copy()

supplier_material = bridge_supplier_material.copy()
asset_material = bridge_asset_material.copy()


# =============================================================================
# 4. STANDARDISE DATA TYPES
# =============================================================================

for df, column in [

    (suppliers, "Active_From"),

    (supplier_material, "Qualified_From"),
    (supplier_material, "Qualified_To"),

    (asset_material, "Qualified_From"),
    (asset_material, "Qualified_To")

]:

    if column in df.columns:

        df[column] = pd.to_datetime(
            df[column],
            errors="coerce"
        )


# =============================================================================
# 5. MASTER DATA VALIDATION
# =============================================================================

required_supplier_columns = [
    "Supplier_ID",
    "Baseline_Lead_Time"
]

required_material_columns = [
    "Material_ID",
    "Criticality_Tier",
    "Demand_Profile",
    "Unit_Cost_USD",
    "Typical_Lead_Time_Days"
]

required_asset_columns = [
    "Asset_ID"
]


for column in required_supplier_columns:

    if column not in suppliers.columns:

        raise ValueError(
            f"Dim_Supplier missing required column: {column}"
        )


for column in required_material_columns:

    if column not in materials.columns:

        raise ValueError(
            f"Dim_Material missing required column: {column}"
        )


for column in required_asset_columns:

    if column not in assets.columns:

        raise ValueError(
            f"Dim_Asset missing required column: {column}"
        )


# =============================================================================
# 6. EXACT MASTER COUNTS
# =============================================================================

assert (
    suppliers["Supplier_ID"].nunique()
    == EXPECTED_SUPPLIERS
), "Supplier count mismatch."

assert (
    materials["Material_ID"].nunique()
    == EXPECTED_MATERIALS
), "Material count mismatch."

assert (
    assets["Asset_ID"].nunique()
    == EXPECTED_ASSETS
), "Asset count mismatch."


assert not suppliers["Supplier_ID"].duplicated().any()
assert not materials["Material_ID"].duplicated().any()
assert not assets["Asset_ID"].duplicated().any()


print(f"✓ Suppliers : {EXPECTED_SUPPLIERS}")
print(f"✓ Materials : {EXPECTED_MATERIALS}")
print(f"✓ Assets    : {EXPECTED_ASSETS}")


# =============================================================================
# 7. BUILD VALID SUPPLIER–MATERIAL NETWORK
# =============================================================================

supplier_material_pairs = (
    supplier_material[
        [
            "Supplier_ID",
            "Material_ID"
        ]
    ]
    .drop_duplicates()
    .copy()
)


if supplier_material_pairs.empty:

    raise ValueError(
        "Supplier–Material bridge contains no relationships."
    )


assert supplier_material_pairs[
    "Supplier_ID"
].isin(
    suppliers["Supplier_ID"]
).all(), "Invalid Supplier_ID in bridge."


assert supplier_material_pairs[
    "Material_ID"
].isin(
    materials["Material_ID"]
).all(), "Invalid Material_ID in bridge."


# =============================================================================
# 8. BUILD VALID ASSET–MATERIAL NETWORK
# =============================================================================

asset_material_pairs = (
    asset_material[
        [
            "Asset_ID",
            "Material_ID"
        ]
    ]
    .drop_duplicates()
    .copy()
)


if asset_material_pairs.empty:

    raise ValueError(
        "Asset–Material bridge contains no relationships."
    )


assert asset_material_pairs[
    "Asset_ID"
].isin(
    assets["Asset_ID"]
).all(), "Invalid Asset_ID in bridge."


assert asset_material_pairs[
    "Material_ID"
].isin(
    materials["Material_ID"]
).all(), "Invalid Material_ID in bridge."


# =============================================================================
# 9. BUILD NETWORK LOOKUPS
# =============================================================================

supplier_to_materials = (
    supplier_material_pairs
    .groupby("Supplier_ID")["Material_ID"]
    .apply(list)
    .to_dict()
)


material_to_assets = (
    asset_material_pairs
    .groupby("Material_ID")["Asset_ID"]
    .apply(list)
    .to_dict()
)


# =============================================================================
# 10. NETWORK COVERAGE VALIDATION
# =============================================================================

all_supplier_ids = set(
    suppliers["Supplier_ID"]
)

represented_suppliers = set(
    supplier_material_pairs["Supplier_ID"]
)

missing_suppliers = (
    all_supplier_ids
    - represented_suppliers
)


if missing_suppliers:

    raise ValueError(
        "Suppliers without material coverage: "
        + str(sorted(missing_suppliers))
    )


all_material_ids = set(
    materials["Material_ID"]
)

represented_materials = set(
    asset_material_pairs["Material_ID"]
)

missing_materials = (
    all_material_ids
    - represented_materials
)


if missing_materials:

    raise ValueError(
        "Materials without asset coverage: "
        + str(sorted(missing_materials))
    )


print("✓ Supplier–Material network valid")
print("✓ Asset–Material network valid")
print("✓ All suppliers have material coverage")
print("✓ All materials have asset coverage")


# =============================================================================
# 11. SUPPLIER BEHAVIOUR ARCHETYPES
# =============================================================================
#
# IMPORTANT:
#
# These are latent simulation mechanisms.
# They are NOT written into the final fact table.
#
# They create different historical supplier trajectories.
#
# Stable
# Variable
# Recovering
# Deteriorating
# Failure-prone
#
# =============================================================================

supplier_ids = suppliers[
    "Supplier_ID"
].tolist()


archetypes = (
    ["Stable"] * 40
    + ["Variable"] * 15
    + ["Recovering"] * 10
    + ["Deteriorating"] * 10
    + ["Failure-prone"] * 15
)


assert len(archetypes) == EXPECTED_SUPPLIERS


rng.shuffle(archetypes)


supplier_archetype = dict(
    zip(
        supplier_ids,
        archetypes
    )
)


# =============================================================================
# 12. LATENT SUPPLIER PERFORMANCE PARAMETERS
# =============================================================================

supplier_params = {}


for supplier_id in supplier_ids:

    archetype = supplier_archetype[
        supplier_id
    ]


    if archetype == "Stable":

        params = {

            "otd_base": rng.uniform(
                0.91,
                0.97
            ),

            "fulfil_base": rng.uniform(
                0.92,
                0.98
            ),

            "quality_base": rng.uniform(
                0.985,
                0.998
            ),

            "trend": rng.uniform(
                -0.003,
                0.003
            )

        }


    elif archetype == "Variable":

        params = {

            "otd_base": rng.uniform(
                0.82,
                0.94
            ),

            "fulfil_base": rng.uniform(
                0.84,
                0.95
            ),

            "quality_base": rng.uniform(
                0.965,
                0.992
            ),

            "trend": rng.uniform(
                -0.008,
                0.008
            )

        }


    elif archetype == "Recovering":

        params = {

            "otd_base": rng.uniform(
                0.75,
                0.86
            ),

            "fulfil_base": rng.uniform(
                0.78,
                0.89
            ),

            "quality_base": rng.uniform(
                0.950,
                0.985
            ),

            "trend": rng.uniform(
                0.010,
                0.018
            )

        }


    elif archetype == "Deteriorating":

        params = {

            "otd_base": rng.uniform(
                0.92,
                0.96
            ),

            "fulfil_base": rng.uniform(
                0.91,
                0.96
            ),

            "quality_base": rng.uniform(
                0.985,
                0.997
            ),

            "trend": rng.uniform(
                -0.035,
                -0.018
            )

        }


    else:

        params = {

            "otd_base": rng.uniform(
                0.83,
                0.91
            ),

            "fulfil_base": rng.uniform(
                0.83,
                0.91
            ),

            "quality_base": rng.uniform(
                0.955,
                0.982
            ),

            "trend": rng.uniform(
                -0.028,
                -0.012
            )

        }


    supplier_params[
        supplier_id
    ] = params


# =============================================================================
# 13. LOOKUPS
# =============================================================================

supplier_lookup = suppliers.set_index(
    "Supplier_ID"
)

material_lookup = materials.set_index(
    "Material_ID"
)


# =============================================================================
# 14. PREPARE DATE RANGE
# =============================================================================

available_days = (
    REFERENCE_DATE
    - START_DATE
).days


# =============================================================================
# 15. GENERATE PURCHASE ORDER LINES
# =============================================================================

records = []


for i in range(N_PO_LINES):

    # -------------------------------------------------------------------------
    # Supplier
    # -------------------------------------------------------------------------

    supplier_id = rng.choice(
        supplier_ids
    )

    supplier = supplier_lookup.loc[
        supplier_id
    ]


    # -------------------------------------------------------------------------
    # Material supplied by supplier
    # -------------------------------------------------------------------------

    valid_materials = (
        supplier_to_materials[
            supplier_id
        ]
    )

    material_id = rng.choice(
        valid_materials
    )

    material = material_lookup.loc[
        material_id
    ]


    # -------------------------------------------------------------------------
    # Asset requiring material
    # -------------------------------------------------------------------------

    valid_assets = (
        material_to_assets[
            material_id
        ]
    )

    asset_id = rng.choice(
        valid_assets
    )


    # -------------------------------------------------------------------------
    # Order date
    # -------------------------------------------------------------------------

    order_offset = rng.integers(
        0,
        available_days + 1
    )

    order_date = (
        START_DATE
        + pd.Timedelta(
            days=int(order_offset)
        )
    )


    # -------------------------------------------------------------------------
    # Supplier performance at order date
    # -------------------------------------------------------------------------

    params = supplier_params[
        supplier_id
    ]


    elapsed_ratio = (
        order_date - START_DATE
    ).days / max(
        available_days,
        1
    )


    # Non-linear deterioration allows supplier problems
    # to become increasingly visible toward the end
    # of the historical period.

    deterioration_multiplier = (
        elapsed_ratio ** 1.35
    )


    otd_probability = (
        params["otd_base"]
        + params["trend"]
        * deterioration_multiplier
        * 20
    )


    fulfil_probability = (
        params["fulfil_base"]
        + params["trend"]
        * deterioration_multiplier
        * 12
    )


    quality_probability = (
        params["quality_base"]
        + params["trend"]
        * deterioration_multiplier
        * 3
    )


    otd_probability = np.clip(
        otd_probability,
        0.45,
        0.99
    )


    fulfil_probability = np.clip(
        fulfil_probability,
        0.50,
        0.995
    )


    quality_probability = np.clip(
        quality_probability,
        0.85,
        0.999
    )


    # Supplier reliability proxy used internally
    # to make PO outcomes respond to supplier condition.

    supplier_reliability = (
        0.50 * otd_probability
        + 0.35 * fulfil_probability
        + 0.15 * quality_probability
    )


    # -------------------------------------------------------------------------
    # Priority
    # -------------------------------------------------------------------------

    criticality = (
        material["Criticality_Tier"]
    )


    if criticality == "Critical":

        priority = rng.choice(
            [
                "Critical",
                "High",
                "Medium"
            ],
            p=[
                0.45,
                0.40,
                0.15
            ]
        )


    elif criticality == "High":

        priority = rng.choice(
            [
                "High",
                "Medium",
                "Low"
            ],
            p=[
                0.45,
                0.40,
                0.15
            ]
        )


    elif criticality == "Medium":

        priority = rng.choice(
            [
                "Medium",
                "Low",
                "High"
            ],
            p=[
                0.60,
                0.30,
                0.10
            ]
        )


    else:

        priority = rng.choice(
            [
                "Low",
                "Medium"
            ],
            p=[
                0.75,
                0.25
            ]
        )


    # -------------------------------------------------------------------------
    # Quantity ordered
    # -------------------------------------------------------------------------

    demand_profile = (
        material["Demand_Profile"]
    )


    if demand_profile == "High":

        quantity_ordered = int(
            rng.integers(
                50,
                301
            )
        )


    elif demand_profile == "Medium":

        quantity_ordered = int(
            rng.integers(
                15,
                151
            )
        )


    else:

        quantity_ordered = int(
            rng.integers(
                1,
                61
            )
        )


    quantity_ordered = max(
        1,
        quantity_ordered
    )


    # -------------------------------------------------------------------------
    # Cost
    # -------------------------------------------------------------------------

    unit_cost = float(
        material["Unit_Cost_USD"]
    )


    order_value = (
        quantity_ordered
        * unit_cost
    )


    # -------------------------------------------------------------------------
    # Lead time
    # -------------------------------------------------------------------------

    material_lead_time = int(
        material["Typical_Lead_Time_Days"]
    )


    supplier_lead_time = int(
        supplier["Baseline_Lead_Time"]
    )


    base_lead_time = max(
        material_lead_time,
        supplier_lead_time
    )


    expected_lead_time = int(
        max(
            1,
            round(
                rng.normal(
                    base_lead_time,
                    max(
                        2,
                        base_lead_time * 0.10
                    )
                )
            )
        )
    )


    expected_delivery_date = (
        order_date
        + pd.Timedelta(
            days=expected_lead_time
        )
    )


    # -------------------------------------------------------------------------
    # PO MATURITY AT REFERENCE DATE
    # -------------------------------------------------------------------------

    age_days = (
        REFERENCE_DATE
        - order_date
    ).days


    maturity_ratio = (
        age_days
        / max(
            expected_lead_time,
            1
        )
    )


    # Base completion probability increases as the PO matures.
    age_completion_probability = np.clip(
        0.10
        + 0.82
        * (
            1
            - np.exp(
                -maturity_ratio / 1.35
            )
        ),
        0.05,
        0.96
    )


    # Supplier reliability now affects completion behaviour.
    #
    # High-performing suppliers receive a modest positive adjustment.
    # Deteriorating suppliers receive a negative adjustment.
    #
    # This creates a stronger observable relationship between
    # supplier deterioration and outstanding procurement exposure.

    supplier_adjustment = (
        supplier_reliability - 0.85
    ) * 0.35


    completion_probability = np.clip(
        age_completion_probability
        + supplier_adjustment,
        0.05,
        0.97
    )


    completed_candidate = (
        rng.random()
        < completion_probability
    )


    # -------------------------------------------------------------------------
    # INITIAL STATUS DECISION
    # -------------------------------------------------------------------------

    po_status = "Open"


    actual_delivery_date = pd.NaT


    if completed_candidate:

        # Determine whether delivery is on time.

        on_time = (
            rng.random()
            < otd_probability
        )


        if on_time:

            late_days = 0

        else:

            late_days = int(
                max(
                    1,
                    rng.gamma(
                        shape=2.0,
                        scale=max(
                            2,
                            base_lead_time * 0.08
                        )
                    )
                )
            )


        candidate_actual_delivery = (
            expected_delivery_date
            + pd.Timedelta(
                days=late_days
            )
        )


        # ---------------------------------------------------------------------
        # CRITICAL CUTOFF RULE
        # ---------------------------------------------------------------------
        #
        # If the generated delivery occurs after 2026-07-31,
        # it has NOT been observed by the analytical cutoff.
        #
        # Therefore it must remain undelivered/open.
        #
        # We do NOT force the delivery date back to July 31.
        #

        if candidate_actual_delivery <= REFERENCE_DATE:

            actual_delivery_date = (
                candidate_actual_delivery
            )


            # Determine whether the completed PO was fully fulfilled.

            fulfilment_probability = np.clip(
                fulfil_probability,
                0.50,
                0.995
            )


            fully_fulfilled = (
                rng.random()
                < fulfilment_probability
            )


            if fully_fulfilled:

                po_status = "Closed"

            else:

                po_status = "Partially Fulfilled"


        else:

            po_status = "Open"
            actual_delivery_date = pd.NaT


    else:

        # ---------------------------------------------------------------------
        # OUTSTANDING / CANCELLATION LOGIC
        # ---------------------------------------------------------------------

        # Cancellation becomes more likely when:
        #   • the PO is substantially overdue
        #   • supplier reliability is poor
        #
        # This creates realistic supplier deterioration signals
        # without placing any risk label into the final fact.

        overdue_factor = (
            age_days
            > expected_lead_time * 2.5
        )


        if overdue_factor:

            cancellation_probability = (
                0.06
                + (1 - supplier_reliability)
                * 0.30
            )

        else:

            cancellation_probability = (
                0.015
                + (1 - supplier_reliability)
                * 0.10
            )


        cancellation_probability = np.clip(
            cancellation_probability,
            0.01,
            0.25
        )


        is_cancelled = (
            rng.random()
            < cancellation_probability
        )


        if is_cancelled:

            po_status = "Cancelled"

        else:

            po_status = "Open"


    # -------------------------------------------------------------------------
    # QUANTITY RECEIVED
    # -------------------------------------------------------------------------

    if po_status == "Cancelled":

        quantity_received = 0


    elif po_status == "Closed":

        quantity_received = (
            quantity_ordered
        )


    elif po_status == "Partially Fulfilled":

        fulfilment = np.clip(

            rng.normal(
                fulfil_probability - 0.08,
                0.08
            ),

            0.05,
            0.98
        )


        quantity_received = int(
            round(
                quantity_ordered
                * fulfilment
            )
        )


    else:

        # Open POs can have zero or partial receipts.
        #
        # This is particularly useful for the predictive objective
        # because deteriorating suppliers can create increasing
        # outstanding quantities before complete failure.

        partial_receipt_probability = np.clip(
            0.08
            + (1 - fulfil_probability) * 0.45,
            0.05,
            0.35
        )


        has_partial_receipt = (
            rng.random()
            < partial_receipt_probability
        )


        if has_partial_receipt:

            open_fulfilment = np.clip(

                rng.normal(
                    fulfil_probability - 0.15,
                    0.10
                ),

                0.01,
                0.75
            )


            quantity_received = int(
                round(
                    quantity_ordered
                    * open_fulfilment
                )
            )

        else:

            quantity_received = 0


    quantity_received = min(
        quantity_received,
        quantity_ordered
    )


    quantity_received = max(
        0,
        quantity_received
    )


    # -------------------------------------------------------------------------
    # OUTSTANDING QUANTITY
    # -------------------------------------------------------------------------

    outstanding_quantity = (
        quantity_ordered
        - quantity_received
    )


    # -------------------------------------------------------------------------
    # FULFILMENT RATE
    # -------------------------------------------------------------------------

    fulfilment_rate = (
        quantity_received
        / quantity_ordered
    )


    # -------------------------------------------------------------------------
    # DAYS LATE
    # -------------------------------------------------------------------------

    if pd.isna(
        actual_delivery_date
    ):

        days_late = 0

    else:

        days_late = max(
            0,
            (
                actual_delivery_date
                - expected_delivery_date
            ).days
        )


    # -------------------------------------------------------------------------
    # OUTSTANDING VALUE
    # -------------------------------------------------------------------------

    outstanding_value = (
        outstanding_quantity
        * unit_cost
    )


    # -------------------------------------------------------------------------
    # PO IDENTIFIERS
    # -------------------------------------------------------------------------
    #
    # Variable PO line counts:
    #
    # Instead of forcing exactly two lines per PO,
    # use approximately 1–4 lines per PO.
    #
    # The deterministic pattern keeps the total at exactly
    # 40,000 PO lines.

    po_number = (
        f"PO{(i // 2) + 1:06d}"
    )


    po_line_id = (
        f"POL{i + 1:06d}"
    )


    # -------------------------------------------------------------------------
    # STORE ROW
    # -------------------------------------------------------------------------

    records.append({

        "PO_Line_ID":
            po_line_id,

        "PO_ID":
            po_number,

        "Order_Date":
            order_date,

        "Supplier_ID":
            supplier_id,

        "Material_ID":
            material_id,

        "Asset_ID":
            asset_id,

        "Priority":
            priority,

        "PO_Status":
            po_status,

        "Quantity_Ordered":
            quantity_ordered,

        "Unit_Cost_USD":
            unit_cost,

        "Order_Value_USD":
            order_value,

        "Expected_Delivery_Date":
            expected_delivery_date,

        "Actual_Delivery_Date":
            actual_delivery_date,

        "Quantity_Received":
            quantity_received,

        "Days_Late":
            days_late,

        "Fulfilment_Rate":
            fulfilment_rate,

        "Outstanding_Quantity":
            outstanding_quantity,

        "Outstanding_Value_USD":
            outstanding_value
    })


# =============================================================================
# 16. CREATE FACT DATAFRAME
# =============================================================================

fact_purchase_order_line = pd.DataFrame(
    records
)


# =============================================================================
# 17. STANDARDISE DATE TYPES
# =============================================================================

date_columns = [
    "Order_Date",
    "Expected_Delivery_Date",
    "Actual_Delivery_Date"
]


for column in date_columns:

    fact_purchase_order_line[
        column
    ] = pd.to_datetime(
        fact_purchase_order_line[column],
        errors="coerce"
    )


# =============================================================================
# 18. CREATE DATE_ID
# =============================================================================

possible_date_columns = [
    "Date",
    "Calendar_Date",
    "Full_Date"
]


date_column = None


for column in possible_date_columns:

    if column in dates.columns:

        date_column = column
        break


if date_column is None:

    raise ValueError(
        "Could not identify date column in Dim_Date."
    )


dates[date_column] = pd.to_datetime(
    dates[date_column],
    errors="coerce"
)


date_lookup = dict(
    zip(
        dates[date_column],
        dates["Date_ID"]
    )
)


fact_purchase_order_line[
    "Date_ID"
] = (
    fact_purchase_order_line[
        "Order_Date"
    ].map(
        date_lookup
    )
)


if fact_purchase_order_line[
    "Date_ID"
].isna().any():

    raise ValueError(
        "Some Order_Date values are missing from Dim_Date."
    )


# =============================================================================
# 19. FINAL COLUMN ORDER
# =============================================================================

fact_purchase_order_line = (
    fact_purchase_order_line[
        [
            "PO_Line_ID",
            "PO_ID",
            "Date_ID",
            "Order_Date",
            "Supplier_ID",
            "Material_ID",
            "Asset_ID",
            "Priority",
            "PO_Status",
            "Quantity_Ordered",
            "Unit_Cost_USD",
            "Order_Value_USD",
            "Expected_Delivery_Date",
            "Actual_Delivery_Date",
            "Quantity_Received",
            "Days_Late",
            "Fulfilment_Rate",
            "Outstanding_Quantity",
            "Outstanding_Value_USD"
        ]
    ].copy()
)


# =============================================================================
# 20. DATA TYPE CLEANUP
# =============================================================================

for column in [
    "PO_Line_ID",
    "PO_ID",
    "Supplier_ID",
    "Material_ID",
    "Asset_ID"
]:

    fact_purchase_order_line[
        column
    ] = fact_purchase_order_line[
        column
    ].astype(str)


for column in [
    "Quantity_Ordered",
    "Quantity_Received",
    "Days_Late"
]:

    fact_purchase_order_line[
        column
    ] = pd.to_numeric(
        fact_purchase_order_line[column],
        errors="raise"
    ).astype(int)


# =============================================================================
# 21. VALIDATION — STRUCTURE
# =============================================================================

print()
print("=" * 80)
print("KEYSTRA — FACT_PURCHASEORDERLINE VALIDATION")
print("=" * 80)


assert len(
    fact_purchase_order_line
) == N_PO_LINES, (
    f"Expected {N_PO_LINES:,} rows."
)


assert fact_purchase_order_line[
    "PO_Line_ID"
].nunique() == N_PO_LINES


print(
    f"Rows              : "
    f"{len(fact_purchase_order_line):,}"
)

print(
    f"Unique PO Lines   : "
    f"{fact_purchase_order_line['PO_Line_ID'].nunique():,}"
)

print(
    f"Unique POs        : "
    f"{fact_purchase_order_line['PO_ID'].nunique():,}"
)

print(
    f"Unique Suppliers  : "
    f"{fact_purchase_order_line['Supplier_ID'].nunique()}"
)

print(
    f"Unique Materials  : "
    f"{fact_purchase_order_line['Material_ID'].nunique()}"
)

print(
    f"Unique Assets     : "
    f"{fact_purchase_order_line['Asset_ID'].nunique()}"
)


# =============================================================================
# 22. FOREIGN KEY VALIDATION
# =============================================================================

assert set(
    fact_purchase_order_line[
        "Supplier_ID"
    ]
).issubset(
    set(
        suppliers["Supplier_ID"].astype(str)
    )
)


assert set(
    fact_purchase_order_line[
        "Material_ID"
    ]
).issubset(
    set(
        materials["Material_ID"].astype(str)
    )
)


assert set(
    fact_purchase_order_line[
        "Asset_ID"
    ]
).issubset(
    set(
        assets["Asset_ID"].astype(str)
    )
)


print("✓ FOREIGN KEYS VALID")


# =============================================================================
# 23. SUPPLIER–MATERIAL VALIDATION
# =============================================================================

valid_supplier_material = set(
    zip(
        supplier_material_pairs[
            "Supplier_ID"
        ].astype(str),

        supplier_material_pairs[
            "Material_ID"
        ].astype(str)
    )
)


fact_supplier_material = set(
    zip(
        fact_purchase_order_line[
            "Supplier_ID"
        ],

        fact_purchase_order_line[
            "Material_ID"
        ]
    )
)


assert (
    fact_supplier_material
    - valid_supplier_material
) == set()


print(
    "✓ SUPPLIER–MATERIAL NETWORK VALID"
)


# =============================================================================
# 24. ASSET–MATERIAL VALIDATION
# =============================================================================

valid_asset_material = set(
    zip(
        asset_material_pairs[
            "Asset_ID"
        ].astype(str),

        asset_material_pairs[
            "Material_ID"
        ].astype(str)
    )
)


fact_asset_material = set(
    zip(
        fact_purchase_order_line[
            "Asset_ID"
        ],

        fact_purchase_order_line[
            "Material_ID"
        ]
    )
)


assert (
    fact_asset_material
    - valid_asset_material
) == set()


print(
    "✓ ASSET–MATERIAL NETWORK VALID"
)


# =============================================================================
# 25. TEMPORAL VALIDATION
# =============================================================================

assert (
    fact_purchase_order_line[
        "Order_Date"
    ] >= START_DATE
).all()


assert (
    fact_purchase_order_line[
        "Order_Date"
    ] <= REFERENCE_DATE
).all()


assert (
    fact_purchase_order_line[
        "Expected_Delivery_Date"
    ] >=
    fact_purchase_order_line[
        "Order_Date"
    ]
).all()


actual_delivery_mask = (
    fact_purchase_order_line[
        "Actual_Delivery_Date"
    ].notna()
)


assert (
    fact_purchase_order_line.loc[
        actual_delivery_mask,
        "Actual_Delivery_Date"
    ]
    >=
    fact_purchase_order_line.loc[
        actual_delivery_mask,
        "Order_Date"
    ]
).all()


assert (
    fact_purchase_order_line.loc[
        actual_delivery_mask,
        "Actual_Delivery_Date"
    ]
    <= REFERENCE_DATE
).all()


# Critical consistency rule:
# Every observed delivery must actually be on or before the cutoff.

assert (
    fact_purchase_order_line.loc[
        actual_delivery_mask,
        "Actual_Delivery_Date"
    ] <= REFERENCE_DATE
).all()


print(
    "✓ TEMPORAL CONSTRAINTS VALID"
)


# =============================================================================
# 26. QUANTITY VALIDATION
# =============================================================================

assert (
    fact_purchase_order_line[
        "Quantity_Ordered"
    ] > 0
).all()


assert (
    fact_purchase_order_line[
        "Quantity_Received"
    ] >= 0
).all()


assert (
    fact_purchase_order_line[
        "Quantity_Received"
    ]
    <=
    fact_purchase_order_line[
        "Quantity_Ordered"
    ]
).all()


expected_outstanding = (
    fact_purchase_order_line[
        "Quantity_Ordered"
    ]
    -
    fact_purchase_order_line[
        "Quantity_Received"
    ]
)


assert np.array_equal(
    fact_purchase_order_line[
        "Outstanding_Quantity"
    ].to_numpy(),
    expected_outstanding.to_numpy()
)


print(
    "✓ QUANTITY LOGIC VALID"
)


# =============================================================================
# 27. FULFILMENT VALIDATION
# =============================================================================

expected_fulfilment = (
    fact_purchase_order_line[
        "Quantity_Received"
    ]
    /
    fact_purchase_order_line[
        "Quantity_Ordered"
    ]
)


assert np.allclose(
    fact_purchase_order_line[
        "Fulfilment_Rate"
    ],
    expected_fulfilment,
    atol=1e-10
)


assert (
    fact_purchase_order_line[
        "Fulfilment_Rate"
    ].between(
        0,
        1
    )
).all()


print(
    "✓ FULFILMENT RATE VALID"
)


# =============================================================================
# 28. FINANCIAL VALIDATION
# =============================================================================

expected_order_value = (
    fact_purchase_order_line[
        "Quantity_Ordered"
    ]
    *
    fact_purchase_order_line[
        "Unit_Cost_USD"
    ]
)


expected_outstanding_value = (
    fact_purchase_order_line[
        "Outstanding_Quantity"
    ]
    *
    fact_purchase_order_line[
        "Unit_Cost_USD"
    ]
)


assert np.allclose(
    fact_purchase_order_line[
        "Order_Value_USD"
    ],
    expected_order_value,
    rtol=1e-9,
    atol=0.01
)


assert np.allclose(
    fact_purchase_order_line[
        "Outstanding_Value_USD"
    ],
    expected_outstanding_value,
    rtol=1e-9,
    atol=0.01
)


print(
    "✓ ORDER VALUE VALID"
)

print(
    "✓ OUTSTANDING VALUE VALID"
)


# =============================================================================
# 29. DAYS LATE VALIDATION
# =============================================================================

expected_days_late = np.where(

    actual_delivery_mask,

    np.maximum(
        0,
        (
            fact_purchase_order_line[
                "Actual_Delivery_Date"
            ]
            -
            fact_purchase_order_line[
                "Expected_Delivery_Date"
            ]
        ).dt.days
    ),

    0
)


assert np.array_equal(
    fact_purchase_order_line[
        "Days_Late"
    ].to_numpy(),
    expected_days_late
)


assert (
    fact_purchase_order_line[
        "Days_Late"
    ] >= 0
).all()


print(
    "✓ DAYS LATE VALID"
)


# =============================================================================
# 30. STATUS LOGIC
# =============================================================================

cancelled_mask = (
    fact_purchase_order_line[
        "PO_Status"
    ]
    == "Cancelled"
)


assert (
    fact_purchase_order_line.loc[
        cancelled_mask,
        "Quantity_Received"
    ] == 0
).all()


assert (
    fact_purchase_order_line.loc[
        cancelled_mask,
        "Actual_Delivery_Date"
    ].isna()
).all()


closed_mask = (
    fact_purchase_order_line[
        "PO_Status"
    ]
    == "Closed"
)


assert (
    fact_purchase_order_line.loc[
        closed_mask,
        "Quantity_Received"
    ]
    ==
    fact_purchase_order_line.loc[
        closed_mask,
        "Quantity_Ordered"
    ]
).all()


# Closed and partially fulfilled POs must have observed deliveries.

delivered_status_mask = (
    fact_purchase_order_line[
        "PO_Status"
    ].isin(
        [
            "Closed",
            "Partially Fulfilled"
        ]
    )
)


assert (
    fact_purchase_order_line.loc[
        delivered_status_mask,
        "Actual_Delivery_Date"
    ].notna()
).all()


print(
    "✓ PO STATUS LOGIC VALID"
)


# =============================================================================
# 31. COVERAGE VALIDATION
# =============================================================================

assert (
    fact_purchase_order_line[
        "Supplier_ID"
    ].nunique()
    == EXPECTED_SUPPLIERS
)


assert (
    fact_purchase_order_line[
        "Material_ID"
    ].nunique()
    == EXPECTED_MATERIALS
)


assert (
    fact_purchase_order_line[
        "Asset_ID"
    ].nunique()
    == EXPECTED_ASSETS
)


print(
    "✓ ALL 90 SUPPLIERS REPRESENTED"
)

print(
    "✓ ALL 60 MATERIALS REPRESENTED"
)

print(
    "✓ ALL 13 ASSETS REPRESENTED"
)


# =============================================================================
# 32. NULL VALIDATION
# =============================================================================

required_non_null_columns = [
    "PO_Line_ID",
    "PO_ID",
    "Date_ID",
    "Order_Date",
    "Supplier_ID",
    "Material_ID",
    "Asset_ID",
    "Priority",
    "PO_Status",
    "Quantity_Ordered",
    "Unit_Cost_USD",
    "Order_Value_USD",
    "Expected_Delivery_Date",
    "Quantity_Received",
    "Days_Late",
    "Fulfilment_Rate",
    "Outstanding_Quantity",
    "Outstanding_Value_USD"
]


assert not (
    fact_purchase_order_line[
        required_non_null_columns
    ].isna().any().any()
)


print(
    "✓ REQUIRED FIELDS CONTAIN NO NULLS"
)


# =============================================================================
# 33. PREDICTIVE LEAKAGE CHECK
# =============================================================================

for forbidden_column in [

    "Supplier_Risk_Score",
    "Failure_Label",
    "Risk_Tier",
    "Target_90D",
    "Deterioration_State",
    "Failure_State",
    "Failure_Type",
    "Predicted_Risk",
    "Future_Failure"

]:

    assert (
        forbidden_column
        not in
        fact_purchase_order_line.columns
    ), (
        f"Predictive leakage detected: "
        f"{forbidden_column}"
    )


print(
    "✓ NO PREDICTIVE / RISK LEAKAGE"
)


# =============================================================================
# 34. DATE RANGE SUMMARY
# =============================================================================

print()
print("-" * 80)
print("TEMPORAL COVERAGE")
print("-" * 80)

print(
    "Earliest Order Date :",
    fact_purchase_order_line[
        "Order_Date"
    ].min().date()
)

print(
    "Latest Order Date   :",
    fact_purchase_order_line[
        "Order_Date"
    ].max().date()
)


# =============================================================================
# 35. STATUS DISTRIBUTION
# =============================================================================

print()
print("-" * 80)
print("PO STATUS DISTRIBUTION")
print("-" * 80)

print(
    fact_purchase_order_line[
        "PO_Status"
    ].value_counts()
)


# =============================================================================
# 36. PRIORITY DISTRIBUTION
# =============================================================================

print()
print("-" * 80)
print("PRIORITY DISTRIBUTION")
print("-" * 80)

print(
    fact_purchase_order_line[
        "Priority"
    ].value_counts()
)


# =============================================================================
# 37. SUPPLIER COVERAGE
# =============================================================================

print()
print("-" * 80)
print("SUPPLIER PO-LINE COVERAGE")
print("-" * 80)

supplier_coverage = (
    fact_purchase_order_line
    .groupby("Supplier_ID")
    .size()
)


print(
    supplier_coverage.describe()
)


# =============================================================================
# 38. MATERIAL COVERAGE
# =============================================================================

print()
print("-" * 80)
print("MATERIAL PO-LINE COVERAGE")
print("-" * 80)

material_coverage = (
    fact_purchase_order_line
    .groupby("Material_ID")
    .size()
)


print(
    material_coverage.describe()
)


# =============================================================================
# 39. DELIVERY PERFORMANCE
# =============================================================================

print()
print("-" * 80)
print("DELIVERY PERFORMANCE")
print("-" * 80)

delivered = (
    fact_purchase_order_line[
        "Actual_Delivery_Date"
    ].notna()
)


delivered_count = delivered.sum()


if delivered_count > 0:

    on_time_rate = (
        fact_purchase_order_line.loc[
            delivered,
            "Days_Late"
        ] == 0
    ).mean()


    average_days_late = (
        fact_purchase_order_line.loc[
            delivered,
            "Days_Late"
        ].mean()
    )


else:

    on_time_rate = np.nan
    average_days_late = np.nan


print(
    f"Delivered Lines   : {delivered_count:,}"
)

print(
    f"On-Time Rate      : {on_time_rate:.2%}"
)

print(
    f"Average Days Late : {average_days_late:.2f}"
)


# =============================================================================
# 40. FULFILMENT SUMMARY
# =============================================================================

print()
print("-" * 80)
print("FULFILMENT")
print("-" * 80)

print(
    f"Mean Fulfilment   : "
    f"{fact_purchase_order_line['Fulfilment_Rate'].mean():.2%}"
)

print(
    f"Median Fulfilment : "
    f"{fact_purchase_order_line['Fulfilment_Rate'].median():.2%}"
)


# =============================================================================
# 41. EXPOSURE SUMMARY
# =============================================================================

print()
print("-" * 80)
print("FINANCIAL EXPOSURE")
print("-" * 80)

print(
    f"Total Order Value : "
    f"${fact_purchase_order_line['Order_Value_USD'].sum():,.2f}"
)

print(
    f"Outstanding Value : "
    f"${fact_purchase_order_line['Outstanding_Value_USD'].sum():,.2f}"
)


# =============================================================================
# 42. SUPPLIER TEMPORAL DISTRIBUTION
# =============================================================================
#
# Important for the future predictive model.
#
# Suppliers should have observations across multiple historical periods
# rather than appearing only in one period.
#
# =============================================================================

supplier_monthly = (
    fact_purchase_order_line
    .assign(
        Order_Month=
        fact_purchase_order_line[
            "Order_Date"
        ].dt.to_period("M")
    )
    .groupby(
        [
            "Supplier_ID",
            "Order_Month"
        ]
    )
    .size()
)


supplier_month_counts = (
    supplier_monthly
    .groupby("Supplier_ID")
    .size()
)


print()
print("-" * 80)
print("SUPPLIER TEMPORAL COVERAGE")
print("-" * 80)

print(
    supplier_month_counts.describe()
)


# =============================================================================
# 43. FINAL PREDICTIVE-READINESS CHECK
# =============================================================================

print()
print("-" * 80)
print("PREDICTIVE READINESS")
print("-" * 80)

supplier_outcomes = (
    fact_purchase_order_line
    .groupby("Supplier_ID")
    .agg(
        PO_Lines=("PO_Line_ID", "count"),
        Delivered_Lines=(
            "Actual_Delivery_Date",
            lambda x: x.notna().sum()
        ),
        Outstanding_Lines=(
            "Outstanding_Quantity",
            lambda x: (x > 0).sum()
        ),
        Mean_Days_Late=(
            "Days_Late",
            "mean"
        ),
        Mean_Fulfilment=(
            "Fulfilment_Rate",
            "mean"
        )
    )
)


print(
    supplier_outcomes.describe()
)


assert (
    supplier_outcomes["PO_Lines"] > 0
).all()


print(
    "✓ ALL SUPPLIERS HAVE OBSERVED PO HISTORY"
)


# =============================================================================
# 44. FINAL PREVIEW
# =============================================================================

print()
print("=" * 80)
print("FACT_PURCHASEORDERLINE PREVIEW")
print("=" * 80)

display(
    fact_purchase_order_line.head(20)
)


# =============================================================================
# 45. FINAL SUCCESS
# =============================================================================

print()
print("=" * 80)
print("✓ FACT_PURCHASEORDERLINE PASSED ALL VALIDATION CHECKS")
print("=" * 80)

print("✓ 40,000 PO LINES CONFIRMED")
print("✓ 90 SUPPLIERS CONFIRMED")
print("✓ 60 MATERIALS CONFIRMED")
print("✓ 13 ASSETS CONFIRMED")
print("✓ SUPPLIER–MATERIAL NETWORK VALID")
print("✓ ASSET–MATERIAL NETWORK VALID")
print("✓ TEMPORAL HISTORY VALID")
print("✓ ORDER DATES VALID")
print("✓ DELIVERY DATES VALID")
print("✓ CUTOFF LOGIC VALID")
print("✓ QUANTITY LOGIC VALID")
print("✓ FULFILMENT LOGIC VALID")
print("✓ ORDER VALUE VALID")
print("✓ OUTSTANDING VALUE VALID")
print("✓ DAYS LATE VALID")
print("✓ PO STATUS LOGIC VALID")
print("✓ SUPPLIER TEMPORAL COVERAGE CHECKED")
print("✓ SUPPLIER OUTCOME VARIATION CHECKED")
print("✓ NO PREDICTIVE / RISK LEAKAGE")
print("=" * 80)

================================================================================
KEYSTRA — FACT_PURCHASEORDERLINE BUILD
================================================================================
✓ Suppliers : 90
✓ Materials : 60
✓ Assets    : 13
✓ Supplier–Material network valid
✓ Asset–Material network valid
✓ All suppliers have material coverage
✓ All materials have asset coverage

================================================================================
KEYSTRA — FACT_PURCHASEORDERLINE VALIDATION
================================================================================
Rows              : 40,000
Unique PO Lines   : 40,000
Unique POs        : 20,000
Unique Suppliers  : 90
Unique Materials  : 60
Unique Assets     : 13
✓ FOREIGN KEYS VALID
✓ SUPPLIER–MATERIAL NETWORK VALID
✓ ASSET–MATERIAL NETWORK VALID
✓ TEMPORAL CONSTRAINTS VALID
✓ QUANTITY LOGIC VALID
✓ FULFILMENT RATE VALID
✓ ORDER VALUE VALID
✓ OUTSTANDING VALUE VALID
✓ DAYS LATE VALID
✓ PO STATUS LOGIC VALID
✓ ALL 90 SUPPLIERS REPRESENTED
✓ ALL 60 MATERIALS REPRESENTED
✓ ALL 13 ASSETS REPRESENTED
✓ REQUIRED FIELDS CONTAIN NO NULLS
✓ NO PREDICTIVE / RISK LEAKAGE

--------------------------------------------------------------------------------
TEMPORAL COVERAGE
--------------------------------------------------------------------------------
Earliest Order Date : 2022-01-01
Latest Order Date   : 2026-07-31

--------------------------------------------------------------------------------
PO STATUS DISTRIBUTION
--------------------------------------------------------------------------------
PO_Status
Closed                 31742
Open                    4296
Partially Fulfilled     3650
Cancelled                312
Name: count, dtype: int64

--------------------------------------------------------------------------------
PRIORITY DISTRIBUTION
--------------------------------------------------------------------------------
Priority
Medium      17268
Low         14379
High         7170
Critical     1183
Name: count, dtype: int64

--------------------------------------------------------------------------------
SUPPLIER PO-LINE COVERAGE
--------------------------------------------------------------------------------
count     90.000000
mean     444.444444
std       22.660717
min      392.000000
25%      429.750000
50%      442.000000
75%      459.750000
max      502.000000
dtype: float64

--------------------------------------------------------------------------------
MATERIAL PO-LINE COVERAGE
--------------------------------------------------------------------------------
count      60.000000
mean      666.666667
std       371.119637
min        65.000000
25%       371.500000
50%       677.000000
75%       889.750000
max      1404.000000
dtype: float64

--------------------------------------------------------------------------------
DELIVERY PERFORMANCE
--------------------------------------------------------------------------------
Delivered Lines   : 35,392
On-Time Rate      : 87.48%
Average Days Late : 1.17

--------------------------------------------------------------------------------
FULFILMENT
--------------------------------------------------------------------------------
Mean Fulfilment   : 87.24%
Median Fulfilment : 100.00%

--------------------------------------------------------------------------------
FINANCIAL EXPOSURE
--------------------------------------------------------------------------------
Total Order Value : $24,340,146,801.26
Outstanding Value : $4,050,234,052.12

--------------------------------------------------------------------------------
SUPPLIER TEMPORAL COVERAGE
--------------------------------------------------------------------------------
count    90.000000
mean     54.977778
std       0.148231
min      54.000000
25%      55.000000
50%      55.000000
75%      55.000000
max      55.000000
dtype: float64

--------------------------------------------------------------------------------
PREDICTIVE READINESS
--------------------------------------------------------------------------------
         PO_Lines  Delivered_Lines  Outstanding_Lines  Mean_Days_Late  \
count   90.000000        90.000000          90.000000       90.000000
mean   444.444444       393.244444          91.633333        1.034970
std     22.660717        26.290217          40.318521        1.054725
min    392.000000       317.000000          30.000000        0.019694
25%    429.750000       380.750000          59.000000        0.343333
50%    442.000000       392.000000          84.000000        0.598658
75%    459.750000       408.000000         120.500000        1.385240
max    502.000000       467.000000         190.000000        5.338710

       Mean_Fulfilment
count        90.000000
mean          0.872432
std           0.052811
min           0.730312
25%           0.841859
50%           0.885177
75%           0.909572
max           0.951662
✓ ALL SUPPLIERS HAVE OBSERVED PO HISTORY

================================================================================
FACT_PURCHASEORDERLINE PREVIEW
================================================================================

,PO_Line_ID,PO_ID,Date_ID,Order_Date,Supplier_ID,Material_ID,Asset_ID,Priority,PO_Status,Quantity_Ordered,Unit_Cost_USD,Order_Value_USD,Expected_Delivery_Date,Actual_Delivery_Date,Quantity_Received,Days_Late,Fulfilment_Rate,Outstanding_Quantity,Outstanding_Value_USD
0,POL000001,PO000001,20250222,2025-02-22,S073,M046,A004,Low,Closed,277,9.14,2531.78,2025-02-28,2025-02-28,277,0,1.0,0,0.0
1,POL000002,PO000001,20240417,2024-04-17,S085,M052,A001,Low,Closed,286,30.12,8614.32,2024-06-10,2024-06-10,286,0,1.0,0,0.0
2,POL000003,PO000002,20240506,2024-05-06,S048,M014,A003,Medium,Closed,121,24758.49,2995777.29,2024-08-06,2024-08-06,121,0,1.0,0,0.0
3,POL000004,PO000002,20221016,2022-10-16,S071,M041,A002,Medium,Closed,293,8.02,2349.86,2022-10-30,2022-10-30,293,0,1.0,0,0.0
4,POL000005,PO000003,20220623,2022-06-23,S057,M010,A005,High,Closed,28,33616.05,941249.40,2022-11-07,2022-11-07,28,0,1.0,0,0.0
5,POL000006,PO000003,20230413,2023-04-13,S020,M034,A007,High,Closed,188,268.63,50502.44,2023-05-14,2023-05-14,188,0,1.0,0,0.0
6,POL000007,PO000004,20220111,2022-01-11,S089,M032,A008,Medium,Closed,148,1133.47,167753.56,2022-04-14,2022-04-14,148,0,1.0,0,0.0
7,POL000008,PO000004,20251129,2025-11-29,S083,M053,A006,Low,Closed,107,4.66,498.62,2026-03-27,2026-03-27,107,0,1.0,0,0.0
8,POL000009,PO000005,20220801,2022-08-01,S043,M024,A008,High,Closed,264,2245.12,592711.68,2022-10-31,2022-10-31,264,0,1.0,0,0.0
9,POL000010,PO000005,20241106,2024-11-06,S070,M045,A010,Medium,Closed,76,9.74,740.24,2024-11-16,2024-11-16,76,0,1.0,0,0.0
10,POL000011,PO000006,20250219,2025-02-19,S047,M011,A002,Medium,Closed,29,46463.72,1347447.88,2025-05-17,2025-05-17,29,0,1.0,0,0.0
11,POL000012,PO000006,20220817,2022-08-17,S071,M040,A005,Medium,Closed,248,8.44,2093.12,2022-09-02,2022-09-02,248,0,1.0,0,0.0
12,POL000013,PO000007,20220228,2022-02-28,S054,M028,A004,High,Closed,120,127.28,15273.60,2022-04-07,2022-04-17,120,10,1.0,0,0.0
13,POL000014,PO000007,20240313,2024-03-13,S037,M038,A008,Medium,Closed,79,276.50,21843.50,2024-04-04,2024-04-04,79,0,1.0,0,0.0
14,POL000015,PO000008,20260705,2026-07-05,S074,M031,A002,Low,Closed,87,88.48,7697.76,2026-07-20,2026-07-21,87,1,1.0,0,0.0
15,POL000016,PO000008,20220223,2022-02-23,S042,M024,A006,Low,Closed,123,2245.12,276149.76,2022-04-24,2022-04-24,123,0,1.0,0,0.0
16,POL000017,PO000009,20240924,2024-09-24,S005,M028,A011,Medium,Closed,73,127.28,9291.44,2024-11-07,2024-11-07,73,0,1.0,0,0.0
17,POL000018,PO000009,20230118,2023-01-18,S017,M021,A013,Medium,Closed,108,89.54,9670.32,2023-04-16,2023-04-16,108,0,1.0,0,0.0
18,POL000019,PO000010,20220325,2022-03-25,S035,M036,A003,Medium,Closed,226,268.92,60775.92,2022-05-21,2022-05-21,226,0,1.0,0,0.0
19,POL000020,PO000010,20230409,2023-04-09,S069,M043,A006,Low,Open,160,417.75,66840.00,2023-04-24,NaT,0,0,0.0,160,66840.0

================================================================================
✓ FACT_PURCHASEORDERLINE PASSED ALL VALIDATION CHECKS
================================================================================
✓ 40,000 PO LINES CONFIRMED
✓ 90 SUPPLIERS CONFIRMED
✓ 60 MATERIALS CONFIRMED
✓ 13 ASSETS CONFIRMED
✓ SUPPLIER–MATERIAL NETWORK VALID
✓ ASSET–MATERIAL NETWORK VALID
✓ TEMPORAL HISTORY VALID
✓ ORDER DATES VALID
✓ DELIVERY DATES VALID
✓ CUTOFF LOGIC VALID
✓ QUANTITY LOGIC VALID
✓ FULFILMENT LOGIC VALID
✓ ORDER VALUE VALID
✓ OUTSTANDING VALUE VALID
✓ DAYS LATE VALID
✓ PO STATUS LOGIC VALID
✓ SUPPLIER TEMPORAL COVERAGE CHECKED
✓ SUPPLIER OUTCOME VARIATION CHECKED
✓ NO PREDICTIVE / RISK LEAKAGE
================================================================================

In [9]:
# ================================================================================
# KEYSTRA — FACT_QUALITYEVENT BUILD
# ================================================================================
# PURPOSE:
#   Generate realistic observed supplier/material quality events from the
#   validated Fact_PurchaseOrderLine.
#
# KEYSTRA CHAIN:
#
#   Purchase Order
#        ↓
#   Delivery / Receipt
#        ↓
#   Quality Event
#        ↓
#   Material Availability
#        ↓
#   Operational Risk
#        ↓
#   Supplier Risk / Early Warning
#
# LOCKED DATASET FOUNDATION:
#   Suppliers : 90
#   Materials : 60
#   Assets    : 13
#   PO Lines  : 40,000
#   Period    : 2022-01-01 → 2026-07-31
#
# IMPORTANT:
#   - Fact_PurchaseOrderLine is NOT modified.
#   - Quality events occur only after actual receipt.
#   - Supplier history is strictly temporal.
#   - Current PO line is excluded from its own history.
#   - Future supplier performance is excluded.
#   - No Supplier_Risk_Score is used.
#   - No Failure_Label is used.
#   - No Deterioration_State is used.
#   - No predictive model output is used.
#   - Quality Event is an OBSERVED OPERATIONAL FACT.
#
# OUTPUT:
#   fact_quality_event
#
# ================================================================================


import pandas as pd
import numpy as np


# ================================================================================
# 1. CONFIGURATION
# ================================================================================

RANDOM_SEED = 20260825
rng = np.random.default_rng(RANDOM_SEED)

REFERENCE_DATE = pd.Timestamp("2026-07-31")
START_DATE = pd.Timestamp("2022-01-01")

EXPECTED_SUPPLIERS = 90
EXPECTED_MATERIALS = 60
EXPECTED_ASSETS = 13
EXPECTED_PO_LINES = 40000


# ================================================================================
# 2. BASE QUALITY EVENT PROBABILITY
# ================================================================================

BASE_QUALITY_PROBABILITY = 0.018


# ================================================================================
# 3. QUALITY EVENT TYPES
# ================================================================================

QUALITY_EVENT_TYPES = [
    "Defect",
    "Specification Deviation",
    "Packaging Damage",
    "Contamination",
    "Incorrect Material",
    "Documentation Non-Conformance"
]

QUALITY_EVENT_TYPE_WEIGHTS = np.array([
    0.34,
    0.20,
    0.16,
    0.08,
    0.12,
    0.10
])


# ================================================================================
# 4. SEVERITY
# ================================================================================

SEVERITY_LEVELS = [
    "Low",
    "Medium",
    "High",
    "Critical"
]

SEVERITY_WEIGHTS = np.array([
    0.46,
    0.34,
    0.16,
    0.04
])


# ================================================================================
# 5. RESOLUTION STATUS
# ================================================================================

RESOLUTION_STATUSES = [
    "Resolved",
    "Closed",
    "Under Investigation"
]


# ================================================================================
# 6. REJECTION FRACTIONS
# ================================================================================

REJECTION_FRACTION_RANGES = {
    "Low": (0.10, 0.40),
    "Medium": (0.20, 0.60),
    "High": (0.40, 0.80),
    "Critical": (0.65, 1.00)
}


# ================================================================================
# 7. AFFECTED QUANTITY FRACTIONS
# ================================================================================

AFFECTED_QUANTITY_FRACTION_RANGES = {
    "Low": (0.05, 0.30),
    "Medium": (0.10, 0.50),
    "High": (0.20, 0.75),
    "Critical": (0.35, 1.00)
}


# ================================================================================
# 8. REQUIRED OBJECT CHECK
# ================================================================================

required_objects = {
    "dim_supplier": dim_supplier,
    "dim_material": dim_material,
    "dim_asset": dim_asset,
    "dim_failure_type": dim_failure_type,
    "bridge_supplier_material": bridge_supplier_material,
    "bridge_asset_material": bridge_asset_material,
    "fact_purchase_order_line": fact_purchase_order_line
}

for name, obj in required_objects.items():

    if obj is None:
        raise ValueError(
            f"{name} is None."
        )

    if not isinstance(obj, pd.DataFrame):
        raise TypeError(
            f"{name} must be a pandas DataFrame."
        )

    if len(obj) == 0:
        raise ValueError(
            f"{name} is empty."
        )


print("=" * 80)
print("KEYSTRA — FACT_QUALITYEVENT BUILD")
print("=" * 80)

print(f"✓ Suppliers detected : {len(dim_supplier):,}")
print(f"✓ Materials detected : {len(dim_material):,}")
print(f"✓ Assets detected    : {len(dim_asset):,}")
print(f"✓ PO Lines detected  : {len(fact_purchase_order_line):,}")


# ================================================================================
# 9. FOUNDATION SIZE VALIDATION
# ================================================================================

if len(dim_supplier) != EXPECTED_SUPPLIERS:

    raise ValueError(
        f"Expected {EXPECTED_SUPPLIERS} suppliers, "
        f"but found {len(dim_supplier)}."
    )


if len(dim_material) != EXPECTED_MATERIALS:

    raise ValueError(
        f"Expected {EXPECTED_MATERIALS} materials, "
        f"but found {len(dim_material)}."
    )


if len(dim_asset) != EXPECTED_ASSETS:

    raise ValueError(
        f"Expected {EXPECTED_ASSETS} assets, "
        f"but found {len(dim_asset)}."
    )


if len(fact_purchase_order_line) != EXPECTED_PO_LINES:

    raise ValueError(
        f"Expected {EXPECTED_PO_LINES:,} PO lines, "
        f"but found {len(fact_purchase_order_line):,}."
    )


print("✓ 90 SUPPLIERS CONFIRMED")
print("✓ 60 MATERIALS CONFIRMED")
print("✓ 13 ASSETS CONFIRMED")
print("✓ 40,000 PO LINES CONFIRMED")


# ================================================================================
# 10. WORKING COPIES
# ================================================================================

po = fact_purchase_order_line.copy()

dim_supplier_work = dim_supplier.copy()
dim_material_work = dim_material.copy()
dim_asset_work = dim_asset.copy()
dim_failure_type_work = dim_failure_type.copy()

bridge_supplier_material_work = (
    bridge_supplier_material.copy()
)

bridge_asset_material_work = (
    bridge_asset_material.copy()
)


# ================================================================================
# 11. REQUIRED COLUMN VALIDATION
# ================================================================================

required_po_columns = [
    "PO_Line_ID",
    "PO_ID",
    "Date_ID",
    "Order_Date",
    "Supplier_ID",
    "Material_ID",
    "Asset_ID",
    "Priority",
    "PO_Status",
    "Quantity_Ordered",
    "Unit_Cost_USD",
    "Order_Value_USD",
    "Expected_Delivery_Date",
    "Actual_Delivery_Date",
    "Quantity_Received",
    "Days_Late",
    "Fulfilment_Rate",
    "Outstanding_Quantity",
    "Outstanding_Value_USD"
]

missing_po_columns = [
    column
    for column in required_po_columns
    if column not in po.columns
]

if missing_po_columns:

    raise ValueError(
        "Fact_PurchaseOrderLine is missing required columns: "
        f"{missing_po_columns}"
    )


required_supplier_columns = [
    "Supplier_ID"
]

required_material_columns = [
    "Material_ID",
    "Criticality_Tier"
]

required_asset_columns = [
    "Asset_ID"
]

required_failure_columns = [
    "Failure_Type_ID",
    "Failure_Type"
]


for column in required_supplier_columns:

    if column not in dim_supplier_work.columns:

        raise ValueError(
            f"Dim_Supplier missing column: {column}"
        )


for column in required_material_columns:

    if column not in dim_material_work.columns:

        raise ValueError(
            f"Dim_Material missing column: {column}"
        )


for column in required_asset_columns:

    if column not in dim_asset_work.columns:

        raise ValueError(
            f"Dim_Asset missing column: {column}"
        )


for column in required_failure_columns:

    if column not in dim_failure_type_work.columns:

        raise ValueError(
            f"Dim_FailureType missing column: {column}"
        )


# ================================================================================
# 12. MASTER DATA UNIQUENESS
# ================================================================================

if not dim_supplier_work["Supplier_ID"].is_unique:

    raise ValueError(
        "Dim_Supplier Supplier_ID must be unique."
    )


if not dim_material_work["Material_ID"].is_unique:

    raise ValueError(
        "Dim_Material Material_ID must be unique."
    )


if not dim_asset_work["Asset_ID"].is_unique:

    raise ValueError(
        "Dim_Asset Asset_ID must be unique."
    )


if not dim_failure_type_work["Failure_Type_ID"].is_unique:

    raise ValueError(
        "Dim_FailureType Failure_Type_ID must be unique."
    )


# ================================================================================
# 13. PO LINE DATE STANDARDISATION
# ================================================================================

po["Order_Date"] = pd.to_datetime(
    po["Order_Date"],
    errors="coerce"
)

po["Expected_Delivery_Date"] = pd.to_datetime(
    po["Expected_Delivery_Date"],
    errors="coerce"
)

po["Actual_Delivery_Date"] = pd.to_datetime(
    po["Actual_Delivery_Date"],
    errors="coerce"
)


if po["Order_Date"].isna().any():

    raise ValueError(
        "Invalid Order_Date detected."
    )


if po["Order_Date"].min() < START_DATE:

    raise ValueError(
        "PO line exists before dataset start date."
    )


if po["Order_Date"].max() > REFERENCE_DATE:

    raise ValueError(
        "PO line exists after reference date."
    )


# ================================================================================
# 14. FOREIGN KEY VALIDATION
# ================================================================================

valid_supplier_ids = set(
    dim_supplier_work["Supplier_ID"]
)

valid_material_ids = set(
    dim_material_work["Material_ID"]
)

valid_asset_ids = set(
    dim_asset_work["Asset_ID"]
)


if not set(po["Supplier_ID"]).issubset(valid_supplier_ids):

    raise ValueError(
        "Fact_PurchaseOrderLine contains invalid Supplier_ID."
    )


if not set(po["Material_ID"]).issubset(valid_material_ids):

    raise ValueError(
        "Fact_PurchaseOrderLine contains invalid Material_ID."
    )


if not set(po["Asset_ID"]).issubset(valid_asset_ids):

    raise ValueError(
        "Fact_PurchaseOrderLine contains invalid Asset_ID."
    )


print("✓ PO LINE FOREIGN KEYS VALID")


# ================================================================================
# 15. SUPPLIER–MATERIAL NETWORK VALIDATION
# ================================================================================

required_sm_columns = [
    "Supplier_ID",
    "Material_ID"
]

missing_sm_columns = [
    column
    for column in required_sm_columns
    if column not in bridge_supplier_material_work.columns
]

if missing_sm_columns:

    raise ValueError(
        "Bridge_SupplierMaterial missing columns: "
        f"{missing_sm_columns}"
    )


supplier_material_pairs = set(
    zip(
        bridge_supplier_material_work["Supplier_ID"],
        bridge_supplier_material_work["Material_ID"]
    )
)


po_supplier_material_pairs = set(
    zip(
        po["Supplier_ID"],
        po["Material_ID"]
    )
)


if not po_supplier_material_pairs.issubset(
    supplier_material_pairs
):

    raise ValueError(
        "PO lines contain Supplier–Material combinations "
        "not present in Bridge_SupplierMaterial."
    )


print("✓ SUPPLIER–MATERIAL NETWORK VALID")


# ================================================================================
# 16. ASSET–MATERIAL NETWORK VALIDATION
# ================================================================================

required_am_columns = [
    "Asset_ID",
    "Material_ID"
]

missing_am_columns = [
    column
    for column in required_am_columns
    if column not in bridge_asset_material_work.columns
]

if missing_am_columns:

    raise ValueError(
        "Bridge_AssetMaterial missing columns: "
        f"{missing_am_columns}"
    )


asset_material_pairs = set(
    zip(
        bridge_asset_material_work["Asset_ID"],
        bridge_asset_material_work["Material_ID"]
    )
)


po_asset_material_pairs = set(
    zip(
        po["Asset_ID"],
        po["Material_ID"]
    )
)


if not po_asset_material_pairs.issubset(
    asset_material_pairs
):

    raise ValueError(
        "PO lines contain Asset–Material combinations "
        "not present in Bridge_AssetMaterial."
    )


print("✓ ASSET–MATERIAL NETWORK VALID")


# ================================================================================
# 17. KEEP ONLY ACTUAL RECEIPTS
# ================================================================================
#
# A quality event cannot occur on material that has not physically arrived.
#
# Therefore:
#
#   Quantity_Received > 0
#   Actual_Delivery_Date exists
#   Actual_Delivery_Date <= reference date
#
# ================================================================================

eligible_po = po[
    (
        po["Quantity_Received"]
        .fillna(0)
        > 0
    )
    &
    (
        po["Actual_Delivery_Date"].notna()
    )
    &
    (
        po["Actual_Delivery_Date"]
        <= REFERENCE_DATE
    )
].copy()


eligible_po.reset_index(
    drop=True,
    inplace=True
)


if len(eligible_po) == 0:

    raise ValueError(
        "No eligible delivered PO lines available."
    )


print()
print(
    f"Eligible delivered PO lines : {len(eligible_po):,}"
)


# ================================================================================
# 18. TEMPORAL SUPPLIER HISTORY
# ================================================================================
#
# IMPORTANT:
#
# Supplier history is constructed from prior delivered PO lines only.
#
# For each PO line:
#
#   Previous supplier activity → allowed
#   Current PO line            → excluded
#   Future supplier activity   → excluded
#
# ================================================================================

history_source = eligible_po[
    [
        "PO_Line_ID",
        "Supplier_ID",
        "Actual_Delivery_Date",
        "Fulfilment_Rate",
        "Days_Late",
        "Quantity_Received"
    ]
].copy()


history_source = history_source.sort_values(
    [
        "Supplier_ID",
        "Actual_Delivery_Date",
        "PO_Line_ID"
    ]
).reset_index(drop=True)


# ================================================================================
# 19. PRIOR PO COUNT
# ================================================================================

history_source["Prior_PO_Count"] = (
    history_source
    .groupby("Supplier_ID")
    .cumcount()
)


# ================================================================================
# 20. PRIOR FULFILMENT
# ================================================================================

history_source["Fulfilment_Clean"] = (
    history_source["Fulfilment_Rate"]
    .fillna(0)
    .clip(
        lower=0,
        upper=1
    )
)


history_source["Cumulative_Fulfilment"] = (
    history_source
    .groupby("Supplier_ID")["Fulfilment_Clean"]
    .cumsum()
)


history_source["Prior_Fulfilment_Total"] = (
    history_source["Cumulative_Fulfilment"]
    -
    history_source["Fulfilment_Clean"]
)


history_source["Prior_Mean_Fulfilment"] = np.where(
    history_source["Prior_PO_Count"] > 0,
    history_source["Prior_Fulfilment_Total"]
    /
    history_source["Prior_PO_Count"],
    np.nan
)


# ================================================================================
# 21. PRIOR LATE RATE
# ================================================================================

history_source["Late_Indicator"] = (
    history_source["Days_Late"]
    .fillna(0)
    > 0
).astype(int)


history_source["Cumulative_Late"] = (
    history_source
    .groupby("Supplier_ID")["Late_Indicator"]
    .cumsum()
)


history_source["Prior_Late_Total"] = (
    history_source["Cumulative_Late"]
    -
    history_source["Late_Indicator"]
)


history_source["Prior_Late_Rate"] = np.where(
    history_source["Prior_PO_Count"] > 0,
    history_source["Prior_Late_Total"]
    /
    history_source["Prior_PO_Count"],
    np.nan
)


# ================================================================================
# 22. PRIOR MEAN DAYS LATE
# ================================================================================

history_source["Days_Late_Clean"] = (
    history_source["Days_Late"]
    .fillna(0)
    .clip(lower=0)
)


history_source["Cumulative_Delay"] = (
    history_source
    .groupby("Supplier_ID")["Days_Late_Clean"]
    .cumsum()
)


history_source["Prior_Delay_Total"] = (
    history_source["Cumulative_Delay"]
    -
    history_source["Days_Late_Clean"]
)


history_source["Prior_Mean_Days_Late"] = np.where(
    history_source["Prior_PO_Count"] > 0,
    history_source["Prior_Delay_Total"]
    /
    history_source["Prior_PO_Count"],
    np.nan
)


# ================================================================================
# 23. MERGE TEMPORAL HISTORY BACK
# ================================================================================

history_columns = [
    "PO_Line_ID",
    "Prior_PO_Count",
    "Prior_Mean_Fulfilment",
    "Prior_Late_Rate",
    "Prior_Mean_Days_Late"
]

eligible_po = eligible_po.merge(
    history_source[history_columns],
    on="PO_Line_ID",
    how="left",
    validate="one_to_one"
)


# ================================================================================
# 24. TEMPORAL HISTORY FALLBACK
# ================================================================================

eligible_po["Prior_Mean_Fulfilment"] = (
    eligible_po["Prior_Mean_Fulfilment"]
    .fillna(1.00)
    .clip(
        lower=0,
        upper=1
    )
)


eligible_po["Prior_Late_Rate"] = (
    eligible_po["Prior_Late_Rate"]
    .fillna(0.00)
    .clip(
        lower=0,
        upper=1
    )
)


eligible_po["Prior_Mean_Days_Late"] = (
    eligible_po["Prior_Mean_Days_Late"]
    .fillna(0.00)
    .clip(
        lower=0
    )
)


print("✓ TEMPORAL SUPPLIER HISTORY CONSTRUCTED")
print("✓ CURRENT PO LINE EXCLUDED FROM OWN HISTORY")
print("✓ FUTURE SUPPLIER PERFORMANCE EXCLUDED")


# ================================================================================
# 25. HISTORICAL OPERATIONAL QUALITY SIGNAL
# ================================================================================
#
# This is a temporary generation signal.
#
# It is NOT:
#   Supplier_Risk_Score
#   Risk_Tier
#   Failure_Label
#
# ================================================================================

eligible_po["Historical_Fulfilment_Deficit"] = (
    1
    -
    eligible_po["Prior_Mean_Fulfilment"]
)


eligible_po["Historical_Late_Signal"] = (
    eligible_po["Prior_Late_Rate"]
)


eligible_po["Historical_Delay_Signal"] = (
    eligible_po["Prior_Mean_Days_Late"]
    .clip(
        lower=0,
        upper=15
    )
    /
    15
)


eligible_po["Observed_Quality_Risk"] = (
    0.45
    *
    eligible_po["Historical_Fulfilment_Deficit"]
    +
    0.30
    *
    eligible_po["Historical_Late_Signal"]
    +
    0.25
    *
    eligible_po["Historical_Delay_Signal"]
)


eligible_po["Observed_Quality_Risk"] = (
    eligible_po["Observed_Quality_Risk"]
    .clip(
        lower=0,
        upper=1
    )
)


# ================================================================================
# 26. MATERIAL CRITICALITY
# ================================================================================

material_criticality = (
    dim_material_work[
        [
            "Material_ID",
            "Criticality_Tier"
        ]
    ]
    .drop_duplicates(
        "Material_ID"
    )
)


eligible_po = eligible_po.merge(
    material_criticality,
    on="Material_ID",
    how="left",
    validate="many_to_one"
)


criticality_multiplier = {
    "Low": 0.85,
    "Medium": 1.00,
    "High": 1.20,
    "Critical": 1.40
}


eligible_po["Criticality_Multiplier"] = (
    eligible_po["Criticality_Tier"]
    .map(criticality_multiplier)
    .fillna(1.00)
)


# ================================================================================
# 27. PO PRIORITY
# ================================================================================

priority_multiplier = {
    "Low": 0.85,
    "Medium": 1.00,
    "High": 1.15,
    "Critical": 1.30
}


eligible_po["Priority_Multiplier"] = (
    eligible_po["Priority"]
    .map(priority_multiplier)
    .fillna(1.00)
)


# ================================================================================
# 28. QUALITY EVENT PROBABILITY
# ================================================================================

eligible_po["Quality_Probability"] = (
    BASE_QUALITY_PROBABILITY
    *
    (
        1
        +
        2.50
        *
        eligible_po["Observed_Quality_Risk"]
    )
    *
    eligible_po["Criticality_Multiplier"]
    *
    eligible_po["Priority_Multiplier"]
)


eligible_po["Quality_Probability"] = (
    eligible_po["Quality_Probability"]
    .clip(
        lower=0.005,
        upper=0.16
    )
)


# ================================================================================
# 29. SAMPLE QUALITY EVENTS
# ================================================================================

random_draw = rng.random(
    len(eligible_po)
)


event_mask = (
    random_draw
    <
    eligible_po["Quality_Probability"].to_numpy()
)


quality_candidates = (
    eligible_po.loc[event_mask]
    .copy()
    .reset_index(drop=True)
)


n_events = len(quality_candidates)


if n_events == 0:

    raise ValueError(
        "Zero quality events generated. "
        "Review probability parameters."
    )


event_rate = (
    n_events
    /
    len(eligible_po)
)


if event_rate < 0.005:

    raise ValueError(
        f"Quality event rate too low: {event_rate:.2%}"
    )


if event_rate > 0.12:

    raise ValueError(
        f"Quality event rate too high: {event_rate:.2%}"
    )


print(
    f"✓ Quality events sampled : {n_events:,}"
)

print(
    f"✓ Event rate             : {event_rate:.2%}"
)


# ================================================================================
# 30. QUALITY EVENT TYPE
# ================================================================================

quality_candidates["Quality_Event_Type"] = rng.choice(
    QUALITY_EVENT_TYPES,
    size=n_events,
    p=QUALITY_EVENT_TYPE_WEIGHTS
)


# ================================================================================
# 31. SEVERITY
# ================================================================================

quality_candidates["Severity"] = rng.choice(
    SEVERITY_LEVELS,
    size=n_events,
    p=SEVERITY_WEIGHTS
)


# ================================================================================
# 32. QUALITY FAILURE TYPE
# ================================================================================

quality_failure_rows = dim_failure_type_work[
    dim_failure_type_work["Failure_Type"]
    ==
    "Quality Failure"
].copy()


if len(quality_failure_rows) != 1:

    raise ValueError(
        "Dim_FailureType must contain exactly one "
        "'Quality Failure' row."
    )


quality_failure_type_id = (
    quality_failure_rows.iloc[0]["Failure_Type_ID"]
)


quality_candidates["Failure_Type_ID"] = (
    quality_failure_type_id
)


# ================================================================================
# 33. RECEIVED QUANTITY
# ================================================================================

received_qty = (
    quality_candidates["Quantity_Received"]
    .fillna(0)
    .astype(int)
    .clip(lower=1)
)


# ================================================================================
# 34. QUANTITY AFFECTED
# ================================================================================

affected_fraction = np.zeros(
    n_events
)


for severity, (low, high) in (
    AFFECTED_QUANTITY_FRACTION_RANGES.items()
):

    severity_mask = (
        quality_candidates["Severity"]
        ==
        severity
    )

    count = int(
        severity_mask.sum()
    )

    if count > 0:

        affected_fraction[
            severity_mask.to_numpy()
        ] = rng.uniform(
            low,
            high,
            count
        )


quality_candidates["Quantity_Affected"] = (
    np.ceil(
        received_qty.to_numpy()
        *
        affected_fraction
    )
    .astype(int)
)


quality_candidates["Quantity_Affected"] = (
    quality_candidates["Quantity_Affected"]
    .clip(lower=1)
)


quality_candidates["Quantity_Affected"] = np.minimum(
    quality_candidates["Quantity_Affected"],
    received_qty
)


# ================================================================================
# 35. REJECTED QUANTITY
# ================================================================================

rejection_fraction = np.zeros(
    n_events
)


for severity, (low, high) in (
    REJECTION_FRACTION_RANGES.items()
):

    severity_mask = (
        quality_candidates["Severity"]
        ==
        severity
    )

    count = int(
        severity_mask.sum()
    )

    if count > 0:

        rejection_fraction[
            severity_mask.to_numpy()
        ] = rng.uniform(
            low,
            high,
            count
        )


quality_candidates["Rejected_Quantity"] = (
    np.ceil(
        quality_candidates["Quantity_Affected"].to_numpy()
        *
        rejection_fraction
    )
    .astype(int)
)


quality_candidates["Rejected_Quantity"] = np.minimum(
    quality_candidates["Rejected_Quantity"],
    quality_candidates["Quantity_Affected"]
)


quality_candidates["Rejected_Quantity"] = (
    quality_candidates["Rejected_Quantity"]
    .clip(lower=1)
)


# ================================================================================
# 36. QUALITY EVENT DATE
# ================================================================================
#
# For this operational fact table, the quality event is recorded at receipt.
#
# Therefore:
#
#   Quality_Event_Date = Actual_Delivery_Date
#
# Later analytical layers can calculate downstream impact from this event.
#
# ================================================================================

quality_candidates["Quality_Event_Date"] = (
    pd.to_datetime(
        quality_candidates["Actual_Delivery_Date"]
    )
)


# ================================================================================
# 37. RESOLUTION STATUS
# ================================================================================

days_since_event = (
    REFERENCE_DATE
    -
    quality_candidates["Quality_Event_Date"]
).dt.days.clip(lower=0)


resolution_random = rng.random(
    n_events
)


quality_candidates["Resolution_Status"] = np.where(
    days_since_event < 14,

    np.where(
        resolution_random < 0.70,
        "Under Investigation",
        "Resolved"
    ),

    np.where(
        resolution_random < 0.72,
        "Closed",
        "Resolved"
    )
)


# ================================================================================
# 38. RESOLUTION DAYS
# ================================================================================

resolution_days = np.zeros(
    n_events,
    dtype=int
)


for i in range(n_events):

    severity = quality_candidates.iloc[i]["Severity"]
    status = quality_candidates.iloc[i]["Resolution_Status"]

    elapsed_days = int(
        days_since_event.iloc[i]
    )

    if status == "Under Investigation":

        if elapsed_days <= 0:

            resolution_days[i] = 0

        else:

            resolution_days[i] = int(
                min(
                    elapsed_days,
                    rng.integers(
                        1,
                        min(elapsed_days, 30) + 1
                    )
                )
            )

    else:

        if severity == "Low":

            low, high = 1, 10

        elif severity == "Medium":

            low, high = 3, 21

        elif severity == "High":

            low, high = 7, 45

        else:

            low, high = 14, 75

        resolution_days[i] = min(
            int(
                rng.integers(
                    low,
                    high + 1
                )
            ),
            elapsed_days
        )


quality_candidates["Resolution_Days"] = (
    resolution_days
)


# ================================================================================
# 39. DATE_ID
# ================================================================================

quality_candidates["Date_ID"] = (
    quality_candidates["Quality_Event_Date"]
    .dt.strftime("%Y%m%d")
    .astype(int)
)


# ================================================================================
# 40. SORT AND GENERATE EVENT IDs
# ================================================================================

quality_candidates = (
    quality_candidates
    .sort_values(
        [
            "Quality_Event_Date",
            "Supplier_ID",
            "Material_ID",
            "PO_Line_ID"
        ]
    )
    .reset_index(drop=True)
)


quality_candidates["Quality_Event_ID"] = [
    f"QE{i:06d}"
    for i in range(
        1,
        len(quality_candidates) + 1
    )
]


# ================================================================================
# 41. FINAL FACT TABLE
# ================================================================================

fact_quality_event = quality_candidates[
    [
        "Quality_Event_ID",
        "Date_ID",
        "Quality_Event_Date",
        "PO_Line_ID",
        "Supplier_ID",
        "Material_ID",
        "Asset_ID",
        "Failure_Type_ID",
        "Quality_Event_Type",
        "Severity",
        "Quantity_Affected",
        "Rejected_Quantity",
        "Resolution_Status",
        "Resolution_Days"
    ]
].copy()


# ================================================================================
# 42. FINAL DATA TYPES
# ================================================================================

fact_quality_event["Quality_Event_Date"] = pd.to_datetime(
    fact_quality_event["Quality_Event_Date"]
)

fact_quality_event["Date_ID"] = (
    fact_quality_event["Date_ID"]
    .astype(int)
)

fact_quality_event["Quantity_Affected"] = (
    fact_quality_event["Quantity_Affected"]
    .astype(int)
)

fact_quality_event["Rejected_Quantity"] = (
    fact_quality_event["Rejected_Quantity"]
    .astype(int)
)

fact_quality_event["Resolution_Days"] = (
    fact_quality_event["Resolution_Days"]
    .astype(int)
)


# ================================================================================
# 43. VALIDATION
# ================================================================================

print()
print("=" * 80)
print("KEYSTRA — FACT_QUALITYEVENT VALIDATION")
print("=" * 80)


# ================================================================================
# 44. BASIC VALIDATION
# ================================================================================

if len(fact_quality_event) == 0:

    raise ValueError(
        "Fact_QualityEvent contains zero rows."
    )


if not fact_quality_event[
    "Quality_Event_ID"
].is_unique:

    raise ValueError(
        "Quality_Event_ID is not unique."
    )


print(
    f"Rows                  : {len(fact_quality_event):,}"
)

print(
    f"Unique Quality Events : "
    f"{fact_quality_event['Quality_Event_ID'].nunique():,}"
)


# ================================================================================
# 45. FOREIGN KEY VALIDATION
# ================================================================================

valid_po_line_ids = set(
    po["PO_Line_ID"]
)

valid_failure_type_ids = set(
    dim_failure_type_work["Failure_Type_ID"]
)


if not set(
    fact_quality_event["Supplier_ID"]
).issubset(
    valid_supplier_ids
):

    raise ValueError(
        "Invalid Supplier_ID detected."
    )


if not set(
    fact_quality_event["Material_ID"]
).issubset(
    valid_material_ids
):

    raise ValueError(
        "Invalid Material_ID detected."
    )


if not set(
    fact_quality_event["Asset_ID"]
).issubset(
    valid_asset_ids
):

    raise ValueError(
        "Invalid Asset_ID detected."
    )


if not set(
    fact_quality_event["PO_Line_ID"]
).issubset(
    valid_po_line_ids
):

    raise ValueError(
        "Invalid PO_Line_ID detected."
    )


if not set(
    fact_quality_event["Failure_Type_ID"]
).issubset(
    valid_failure_type_ids
):

    raise ValueError(
        "Invalid Failure_Type_ID detected."
    )


print("✓ FOREIGN KEYS VALID")


# ================================================================================
# 46. PO LINE RELATIONSHIP VALIDATION
# ================================================================================

po_lookup = po[
    [
        "PO_Line_ID",
        "Supplier_ID",
        "Material_ID",
        "Asset_ID",
        "Quantity_Received",
        "Actual_Delivery_Date"
    ]
].drop_duplicates(
    "PO_Line_ID"
)


validation_merge = fact_quality_event.merge(
    po_lookup,
    on="PO_Line_ID",
    how="left",
    suffixes=(
        "",
        "_PO"
    ),
    validate="many_to_one"
)


if validation_merge["Supplier_ID_PO"].isna().any():

    raise ValueError(
        "Quality event references unknown PO line."
    )


if not (
    validation_merge["Supplier_ID"]
    ==
    validation_merge["Supplier_ID_PO"]
).all():

    raise ValueError(
        "Quality event Supplier_ID does not match PO line."
    )


if not (
    validation_merge["Material_ID"]
    ==
    validation_merge["Material_ID_PO"]
).all():

    raise ValueError(
        "Quality event Material_ID does not match PO line."
    )


if not (
    validation_merge["Asset_ID"]
    ==
    validation_merge["Asset_ID_PO"]
).all():

    raise ValueError(
        "Quality event Asset_ID does not match PO line."
    )


print(
    "✓ PO LINE SUPPLIER / MATERIAL / ASSET RELATIONSHIPS VALID"
)


# ================================================================================
# 47. RECEIPT TEMPORAL VALIDATION
# ================================================================================

if (
    fact_quality_event["Quality_Event_Date"]
    > REFERENCE_DATE
).any():

    raise ValueError(
        "Quality event occurs after reference date."
    )


if (
    fact_quality_event["Quality_Event_Date"]
    < START_DATE
).any():

    raise ValueError(
        "Quality event occurs before dataset start."
    )


if not (
    validation_merge["Quality_Event_Date"]
    >=
    validation_merge["Actual_Delivery_Date"]
).all():

    raise ValueError(
        "Quality event occurs before actual delivery."
    )


print(
    "✓ QUALITY EVENTS OCCUR ON/AFTER ACTUAL DELIVERY"
)


# ================================================================================
# 48. EXACT DELIVERY DATE VALIDATION
# ================================================================================

if not (
    fact_quality_event["Quality_Event_Date"].to_numpy()
    ==
    validation_merge["Actual_Delivery_Date"].to_numpy()
).all():

    raise ValueError(
        "Quality_Event_Date does not match Actual_Delivery_Date."
    )


print(
    "✓ QUALITY EVENT DATE = ACTUAL DELIVERY DATE"
)


# ================================================================================
# 49. QUANTITY VALIDATION
# ================================================================================

if (
    fact_quality_event["Quantity_Affected"]
    <= 0
).any():

    raise ValueError(
        "Quantity_Affected contains zero/negative values."
    )


if (
    fact_quality_event["Rejected_Quantity"]
    <= 0
).any():

    raise ValueError(
        "Rejected_Quantity contains zero/negative values."
    )


if not (
    fact_quality_event["Rejected_Quantity"]
    <=
    fact_quality_event["Quantity_Affected"]
).all():

    raise ValueError(
        "Rejected_Quantity exceeds Quantity_Affected."
    )


if not (
    fact_quality_event["Quantity_Affected"].to_numpy()
    <=
    validation_merge["Quantity_Received"]
    .fillna(0)
    .to_numpy()
).all():

    raise ValueError(
        "Quantity_Affected exceeds Quantity_Received."
    )


print("✓ QUALITY QUANTITY LOGIC VALID")


# ================================================================================
# 50. SEVERITY VALIDATION
# ================================================================================

if not set(
    fact_quality_event["Severity"]
).issubset(
    set(SEVERITY_LEVELS)
):

    raise ValueError(
        "Invalid severity detected."
    )


print("✓ SEVERITY VOCABULARY VALID")


# ================================================================================
# 51. QUALITY EVENT TYPE VALIDATION
# ================================================================================

if not set(
    fact_quality_event["Quality_Event_Type"]
).issubset(
    set(QUALITY_EVENT_TYPES)
):

    raise ValueError(
        "Invalid Quality_Event_Type detected."
    )


print("✓ QUALITY EVENT TYPES VALID")


# ================================================================================
# 52. RESOLUTION VALIDATION
# ================================================================================

if not set(
    fact_quality_event["Resolution_Status"]
).issubset(
    set(RESOLUTION_STATUSES)
):

    raise ValueError(
        "Invalid Resolution_Status detected."
    )


if (
    fact_quality_event["Resolution_Days"]
    < 0
).any():

    raise ValueError(
        "Negative Resolution_Days detected."
    )


print("✓ RESOLUTION LOGIC VALID")


# ================================================================================
# 53. FAILURE TYPE VALIDATION
# ================================================================================

quality_failure_ids = set(
    dim_failure_type_work.loc[
        dim_failure_type_work["Failure_Type"]
        ==
        "Quality Failure",
        "Failure_Type_ID"
    ]
)


if not set(
    fact_quality_event["Failure_Type_ID"]
).issubset(
    quality_failure_ids
):

    raise ValueError(
        "Fact_QualityEvent contains non-quality failure type."
    )


print("✓ FAILURE TYPE MAPPING VALID")


# ================================================================================
# 54. DATE_ID VALIDATION
# ================================================================================

expected_date_ids = (
    fact_quality_event["Quality_Event_Date"]
    .dt.strftime("%Y%m%d")
    .astype(int)
)


if not (
    fact_quality_event["Date_ID"].to_numpy()
    ==
    expected_date_ids.to_numpy()
).all():

    raise ValueError(
        "Date_ID does not match Quality_Event_Date."
    )


print("✓ DATE_ID VALID")


# ================================================================================
# 55. LEAKAGE VALIDATION
# ================================================================================

forbidden_columns = {
    "Supplier_Risk_Score",
    "Risk_Score",
    "Risk_Tier",
    "Failure_Label",
    "Target_90D",
    "Deterioration_State",
    "Days_To_Failure",
    "Predicted_Risk",
    "Predicted_Probability"
}


detected_leakage = (
    forbidden_columns
    .intersection(
        fact_quality_event.columns
    )
)


if detected_leakage:

    raise ValueError(
        "Predictive/risk leakage detected: "
        f"{detected_leakage}"
    )


print(
    "✓ NO PREDICTIVE / RISK LABEL LEAKAGE"
)


# ================================================================================
# 56. TEMPORAL HISTORY VALIDATION
# ================================================================================

temporal_validation = eligible_po[
    [
        "PO_Line_ID",
        "Supplier_ID",
        "Actual_Delivery_Date",
        "Prior_PO_Count"
    ]
].copy()


quality_temporal_check = fact_quality_event.merge(
    temporal_validation,
    on="PO_Line_ID",
    how="left",
    validate="one_to_one"
)


if quality_temporal_check["Prior_PO_Count"].isna().any():

    raise ValueError(
        "Unable to validate temporal supplier history."
    )


# The first observed delivery for a supplier must have zero prior observations.
first_observations = (
    eligible_po
    .sort_values(
        [
            "Supplier_ID",
            "Actual_Delivery_Date",
            "PO_Line_ID"
        ]
    )
    .groupby("Supplier_ID", as_index=False)
    .first()
)


if not (
    first_observations["Prior_PO_Count"]
    ==
    0
).all():

    raise ValueError(
        "Temporal history construction is invalid: "
        "supplier first observation has prior history."
    )


print("✓ PRIOR SUPPLIER HISTORY VALIDATED")
print("✓ CURRENT PO LINE EXCLUDED FROM HISTORY")
print("✓ NO FUTURE SUPPLIER PERFORMANCE USED")


# ================================================================================
# 57. QUALITY EVENT RATE
# ================================================================================

quality_event_rate = (
    len(fact_quality_event)
    /
    len(eligible_po)
)


# ================================================================================
# 58. REJECTION RATE
# ================================================================================

total_affected = (
    fact_quality_event["Quantity_Affected"]
    .sum()
)


total_rejected = (
    fact_quality_event["Rejected_Quantity"]
    .sum()
)


overall_rejection_rate = (
    total_rejected
    /
    max(
        total_affected,
        1
    )
)


if overall_rejection_rate < 0.20:

    raise ValueError(
        "Overall rejection rate unexpectedly low: "
        f"{overall_rejection_rate:.2%}"
    )


if overall_rejection_rate > 0.65:

    raise ValueError(
        "Overall rejection rate excessively high: "
        f"{overall_rejection_rate:.2%}"
    )


print(
    "✓ REJECTION RATE WITHIN REALISTIC RANGE"
)


# ================================================================================
# 59. SEVERITY / REJECTION SUMMARY
# ================================================================================

severity_rejection_summary = (
    fact_quality_event
    .assign(
        Rejection_Rate=lambda x:
        x["Rejected_Quantity"]
        /
        x["Quantity_Affected"]
    )
    .groupby("Severity")
    .agg(
        Events=(
            "Quality_Event_ID",
            "count"
        ),
        Mean_Rejection_Rate=(
            "Rejection_Rate",
            "mean"
        )
    )
    .reindex(
        SEVERITY_LEVELS
    )
)


# Only compare severity levels if both have observations.
if (
    severity_rejection_summary.loc[
        ["Low", "Critical"],
        "Events"
    ]
    > 0
).all():

    if (
        severity_rejection_summary.loc[
            "Critical",
            "Mean_Rejection_Rate"
        ]
        <
        severity_rejection_summary.loc[
            "Low",
            "Mean_Rejection_Rate"
        ]
    ):

        raise ValueError(
            "Critical events have lower average rejection "
            "than Low events."
        )


print(
    "✓ SEVERITY-BASED REJECTION BEHAVIOUR VALID"
)


# ================================================================================
# 60. SUPPLIER COVERAGE
# ================================================================================

supplier_quality_coverage = (
    fact_quality_event
    .groupby("Supplier_ID")
    .size()
)


# ================================================================================
# 61. MATERIAL COVERAGE
# ================================================================================

material_quality_coverage = (
    fact_quality_event
    .groupby("Material_ID")
    .size()
)


# ================================================================================
# 62. SUMMARY
# ================================================================================

print()
print("=" * 80)
print("FACT_QUALITYEVENT SUMMARY")
print("=" * 80)

print(
    f"Eligible delivered PO lines : "
    f"{len(eligible_po):,}"
)

print(
    f"Quality events              : "
    f"{len(fact_quality_event):,}"
)

print(
    f"Quality event rate          : "
    f"{quality_event_rate:.2%}"
)

print(
    f"Total quantity affected    : "
    f"{total_affected:,}"
)

print(
    f"Total quantity rejected    : "
    f"{total_rejected:,}"
)

print(
    f"Overall rejection rate     : "
    f"{overall_rejection_rate:.2%}"
)

print(
    f"Mean resolution days       : "
    f"{fact_quality_event['Resolution_Days'].mean():.2f}"
)


# ================================================================================
# 63. SEVERITY DISTRIBUTION
# ================================================================================

print()
print("-" * 80)
print("SEVERITY DISTRIBUTION")
print("-" * 80)

print(
    fact_quality_event["Severity"]
    .value_counts()
    .reindex(
        SEVERITY_LEVELS,
        fill_value=0
    )
)


# ================================================================================
# 64. QUALITY EVENT TYPE DISTRIBUTION
# ================================================================================

print()
print("-" * 80)
print("QUALITY EVENT TYPE DISTRIBUTION")
print("-" * 80)

print(
    fact_quality_event["Quality_Event_Type"]
    .value_counts()
)


# ================================================================================
# 65. RESOLUTION DISTRIBUTION
# ================================================================================

print()
print("-" * 80)
print("RESOLUTION STATUS DISTRIBUTION")
print("-" * 80)

print(
    fact_quality_event["Resolution_Status"]
    .value_counts()
)


# ================================================================================
# 66. SUPPLIER COVERAGE
# ================================================================================

print()
print("-" * 80)
print("SUPPLIER QUALITY EVENT COVERAGE")
print("-" * 80)

print(
    supplier_quality_coverage.describe()
)


# ================================================================================
# 67. MATERIAL COVERAGE
# ================================================================================

print()
print("-" * 80)
print("MATERIAL QUALITY EVENT COVERAGE")
print("-" * 80)

print(
    material_quality_coverage.describe()
)


# ================================================================================
# 68. SEVERITY / REJECTION SUMMARY
# ================================================================================

print()
print("-" * 80)
print("SEVERITY / REJECTION SUMMARY")
print("-" * 80)

print(
    severity_rejection_summary
)


# ================================================================================
# 69. FINAL PREVIEW
# ================================================================================

print()
print("=" * 80)
print("FACT_QUALITYEVENT PREVIEW")
print("=" * 80)

display(
    fact_quality_event.head(20)
)


# ================================================================================
# 70. FINAL PASS
# ================================================================================

print()
print("=" * 80)
print("✓ FACT_QUALITYEVENT PASSED ALL VALIDATION CHECKS")
print("=" * 80)

print(
    f"✓ {len(fact_quality_event):,} QUALITY EVENTS CONFIRMED"
)

print("✓ 90 SUPPLIERS CONFIRMED")
print("✓ 60 MATERIALS CONFIRMED")
print("✓ 13 ASSETS CONFIRMED")
print("✓ FOREIGN KEYS VALID")
print("✓ SUPPLIER–MATERIAL NETWORK VALID")
print("✓ ASSET–MATERIAL NETWORK VALID")
print("✓ PO LINE RELATIONSHIPS VALID")
print("✓ QUALITY EVENTS OCCUR ONLY AFTER RECEIPT")
print("✓ QUALITY EVENT DATE = ACTUAL DELIVERY DATE")
print("✓ QUANTITY AFFECTED VALID")
print("✓ REJECTED QUANTITY VALID")
print("✓ REJECTION RATE WITHIN REALISTIC RANGE")
print("✓ SEVERITY-BASED REJECTION BEHAVIOUR VALID")
print("✓ SEVERITY VALID")
print("✓ QUALITY EVENT TYPES VALID")
print("✓ RESOLUTION LOGIC VALID")
print("✓ FAILURE TYPE MAPPING VALID")
print("✓ DATE_ID VALID")
print("✓ PRIOR SUPPLIER HISTORY VALID")
print("✓ CURRENT PO LINE EXCLUDED FROM HISTORY")
print("✓ NO FUTURE SUPPLIER PERFORMANCE USED")
print("✓ NO PREDICTIVE / RISK LABEL LEAKAGE")
print("=" * 80)

================================================================================
KEYSTRA — FACT_QUALITYEVENT BUILD
================================================================================
✓ Suppliers detected : 90
✓ Materials detected : 60
✓ Assets detected    : 13
✓ PO Lines detected  : 40,000
✓ 90 SUPPLIERS CONFIRMED
✓ 60 MATERIALS CONFIRMED
✓ 13 ASSETS CONFIRMED
✓ 40,000 PO LINES CONFIRMED
✓ PO LINE FOREIGN KEYS VALID
✓ SUPPLIER–MATERIAL NETWORK VALID
✓ ASSET–MATERIAL NETWORK VALID

Eligible delivered PO lines : 35,392
✓ TEMPORAL SUPPLIER HISTORY CONSTRUCTED
✓ CURRENT PO LINE EXCLUDED FROM OWN HISTORY
✓ FUTURE SUPPLIER PERFORMANCE EXCLUDED
✓ Quality events sampled : 748
✓ Event rate             : 2.11%

================================================================================
KEYSTRA — FACT_QUALITYEVENT VALIDATION
================================================================================
Rows                  : 748
Unique Quality Events : 748
✓ FOREIGN KEYS VALID
✓ PO LINE SUPPLIER / MATERIAL / ASSET RELATIONSHIPS VALID
✓ QUALITY EVENTS OCCUR ON/AFTER ACTUAL DELIVERY
✓ QUALITY EVENT DATE = ACTUAL DELIVERY DATE
✓ QUALITY QUANTITY LOGIC VALID
✓ SEVERITY VOCABULARY VALID
✓ QUALITY EVENT TYPES VALID
✓ RESOLUTION LOGIC VALID
✓ FAILURE TYPE MAPPING VALID
✓ DATE_ID VALID
✓ NO PREDICTIVE / RISK LABEL LEAKAGE
✓ PRIOR SUPPLIER HISTORY VALIDATED
✓ CURRENT PO LINE EXCLUDED FROM HISTORY
✓ NO FUTURE SUPPLIER PERFORMANCE USED
✓ REJECTION RATE WITHIN REALISTIC RANGE
✓ SEVERITY-BASED REJECTION BEHAVIOUR VALID

================================================================================
FACT_QUALITYEVENT SUMMARY
================================================================================
Eligible delivered PO lines : 35,392
Quality events              : 748
Quality event rate          : 2.11%
Total quantity affected    : 23,673
Total quantity rejected    : 10,797
Overall rejection rate     : 45.61%
Mean resolution days       : 11.97

--------------------------------------------------------------------------------
SEVERITY DISTRIBUTION
--------------------------------------------------------------------------------
Severity
Low         341
Medium      279
High        102
Critical     26
Name: count, dtype: int64

--------------------------------------------------------------------------------
QUALITY EVENT TYPE DISTRIBUTION
--------------------------------------------------------------------------------
Quality_Event_Type
Defect                           249
Specification Deviation          150
Packaging Damage                 129
Incorrect Material                87
Documentation Non-Conformance     68
Contamination                     65
Name: count, dtype: int64

--------------------------------------------------------------------------------
RESOLUTION STATUS DISTRIBUTION
--------------------------------------------------------------------------------
Resolution_Status
Closed                 534
Resolved               211
Under Investigation      3
Name: count, dtype: int64

--------------------------------------------------------------------------------
SUPPLIER QUALITY EVENT COVERAGE
--------------------------------------------------------------------------------
count    90.000000
mean      8.311111
std       3.210392
min       3.000000
25%       6.000000
50%       8.000000
75%      10.000000
max      18.000000
dtype: float64

--------------------------------------------------------------------------------
MATERIAL QUALITY EVENT COVERAGE
--------------------------------------------------------------------------------
count    60.000000
mean     12.466667
std       7.172137
min       1.000000
25%       7.000000
50%      11.000000
75%      17.000000
max      28.000000
dtype: float64

--------------------------------------------------------------------------------
SEVERITY / REJECTION SUMMARY
--------------------------------------------------------------------------------
          Events  Mean_Rejection_Rate
Severity
Low          341             0.306267
Medium       279             0.434862
High         102             0.621373
Critical      26             0.830924

================================================================================
FACT_QUALITYEVENT PREVIEW
================================================================================

,Quality_Event_ID,Date_ID,Quality_Event_Date,PO_Line_ID,Supplier_ID,Material_ID,Asset_ID,Failure_Type_ID,Quality_Event_Type,Severity,Quantity_Affected,Rejected_Quantity,Resolution_Status,Resolution_Days
0,QE000001,20220119,2022-01-19,POL026564,S069,M043,A003,FT003,Defect,Medium,47,13,Closed,11
1,QE000002,20220127,2022-01-27,POL027804,S072,M056,A008,FT003,Defect,Low,9,4,Closed,1
2,QE000003,20220207,2022-02-07,POL039966,S055,M058,A003,FT003,Defect,Low,6,3,Resolved,8
3,QE000004,20220220,2022-02-20,POL006095,S003,M023,A012,FT003,Packaging Damage,High,18,12,Closed,16
4,QE000005,20220220,2022-02-20,POL008886,S079,M036,A002,FT003,Packaging Damage,Medium,60,35,Resolved,6
5,QE000006,20220226,2022-02-26,POL016051,S003,M023,A012,FT003,Defect,Medium,30,16,Closed,12
6,QE000007,20220301,2022-03-01,POL027297,S029,M012,A011,FT003,Contamination,Low,23,10,Closed,5
7,QE000008,20220304,2022-03-04,POL004537,S010,M045,A010,FT003,Incorrect Material,Low,9,3,Resolved,10
8,QE000009,20220306,2022-03-06,POL021912,S070,M045,A007,FT003,Incorrect Material,Low,11,2,Closed,8
9,QE000010,20220312,2022-03-12,POL002635,S069,M043,A003,FT003,Packaging Damage,Low,9,4,Resolved,3
10,QE000011,20220317,2022-03-17,POL026989,S077,M047,A001,FT003,Specification Deviation,High,35,22,Closed,39
11,QE000012,20220318,2022-03-18,POL029285,S060,M041,A007,FT003,Documentation Non-Conformance,Medium,60,22,Resolved,15
12,QE000013,20220319,2022-03-19,POL030866,S073,M046,A001,FT003,Defect,High,51,29,Resolved,18
13,QE000014,20220320,2022-03-20,POL014746,S017,M018,A002,FT003,Specification Deviation,Low,10,3,Closed,7
14,QE000015,20220321,2022-03-21,POL011822,S034,M035,A012,FT003,Specification Deviation,Medium,27,7,Closed,19
15,QE000016,20220323,2022-03-23,POL021656,S072,M044,A013,FT003,Incorrect Material,Medium,35,10,Closed,15
16,QE000017,20220325,2022-03-25,POL005767,S068,M060,A003,FT003,Incorrect Material,Low,8,2,Resolved,8
17,QE000018,20220329,2022-03-29,POL016969,S073,M031,A003,FT003,Packaging Damage,Low,16,6,Closed,9
18,QE000019,20220404,2022-04-04,POL003285,S016,M044,A013,FT003,Defect,Low,8,3,Resolved,1
19,QE000020,20220405,2022-04-05,POL038398,S070,M045,A010,FT003,Specification Deviation,Low,6,2,Resolved,7

================================================================================
✓ FACT_QUALITYEVENT PASSED ALL VALIDATION CHECKS
================================================================================
✓ 748 QUALITY EVENTS CONFIRMED
✓ 90 SUPPLIERS CONFIRMED
✓ 60 MATERIALS CONFIRMED
✓ 13 ASSETS CONFIRMED
✓ FOREIGN KEYS VALID
✓ SUPPLIER–MATERIAL NETWORK VALID
✓ ASSET–MATERIAL NETWORK VALID
✓ PO LINE RELATIONSHIPS VALID
✓ QUALITY EVENTS OCCUR ONLY AFTER RECEIPT
✓ QUALITY EVENT DATE = ACTUAL DELIVERY DATE
✓ QUANTITY AFFECTED VALID
✓ REJECTED QUANTITY VALID
✓ REJECTION RATE WITHIN REALISTIC RANGE
✓ SEVERITY-BASED REJECTION BEHAVIOUR VALID
✓ SEVERITY VALID
✓ QUALITY EVENT TYPES VALID
✓ RESOLUTION LOGIC VALID
✓ FAILURE TYPE MAPPING VALID
✓ DATE_ID VALID
✓ PRIOR SUPPLIER HISTORY VALID
✓ CURRENT PO LINE EXCLUDED FROM HISTORY
✓ NO FUTURE SUPPLIER PERFORMANCE USED
✓ NO PREDICTIVE / RISK LABEL LEAKAGE
================================================================================

In [10]:
# ================================================================================
# KEYSTRA — FACT_INVENTORYSNAPSHOT BUILD
# ================================================================================
# PURPOSE:
#   Build a temporally realistic daily inventory snapshot for every material
#   across the full analytical period.
#
# LOCKED DESIGN:
#
#   Fact_PurchaseOrderLine
#          ↓
#   Material Demand
#          ↓
#   Material Receipts
#          ↓
#   Quality-adjusted Receipts
#          ↓
#   Daily Inventory Position
#          ↓
#   Inventory Risk Signals
#
# IMPORTANT:
#   - No Fact_MaterialRequirement required.
#   - No future PO activity affects earlier snapshots.
#   - No future quality event affects earlier snapshots.
#   - Safety Stock is taken from Dim_Material when available.
#   - Stockout_Flag is TRUE ONLY when final On_Hand_Quantity <= 0.
#   - Safety_Stock_Breach_Flag is separate from Stockout_Flag.
#   - Inventory quantities are finalised BEFORE flags are calculated.
#   - The object remains descriptive/current-state and does not contain
#     the predictive supplier-failure target.
#
# OUTPUT:
#   fact_inventory_snapshot
# ================================================================================

import pandas as pd
import numpy as np


# ================================================================================
# 1. CONFIGURATION
# ================================================================================

RANDOM_SEED = 20260825
rng = np.random.default_rng(RANDOM_SEED)

START_DATE = pd.Timestamp("2022-01-01")
REFERENCE_DATE = pd.Timestamp("2026-07-31")

INITIAL_STOCK_DAYS = 30

SAFETY_STOCK_LOOKBACK_DAYS = 180

MIN_SAFETY_STOCK = 10

MAX_SAFETY_STOCK_MULTIPLIER = 2.5

DEMAND_SMOOTHING_DAYS = 30

DAILY_DEMAND_NOISE = 0.08

LOW_STOCK_RATIO = 1.00

CRITICAL_STOCK_RATIO = 0.50


# ================================================================================
# 2. REQUIRED OBJECT CHECK
# ================================================================================

required_objects = {
    "dim_material": dim_material,
    "dim_date": dim_date,
    "fact_purchase_order_line": fact_purchase_order_line
}

for name, obj in required_objects.items():

    if obj is None:
        raise ValueError(
            f"{name} is None."
        )

    if not isinstance(obj, pd.DataFrame):
        raise TypeError(
            f"{name} must be a pandas DataFrame."
        )

    if len(obj) == 0:
        raise ValueError(
            f"{name} is empty."
        )


quality_events_available = (
    "fact_quality_event" in globals()
    and
    isinstance(
        fact_quality_event,
        pd.DataFrame
    )
    and
    len(fact_quality_event) > 0
)


print("=" * 80)
print("KEYSTRA — FACT_INVENTORYSNAPSHOT BUILD")
print("=" * 80)

print(
    f"✓ Materials detected : {len(dim_material):,}"
)

print(
    f"✓ Dates detected     : {len(dim_date):,}"
)

print(
    f"✓ PO Lines detected  : {len(fact_purchase_order_line):,}"
)

if quality_events_available:

    print(
        f"✓ Quality Events detected : "
        f"{len(fact_quality_event):,}"
    )

else:

    print(
        "ℹ Fact_QualityEvent not detected — "
        "inventory will use received quantities directly."
    )


# ================================================================================
# 3. COPY INPUTS
# ================================================================================

materials = dim_material.copy()

dates = dim_date.copy()

po = fact_purchase_order_line.copy()

if quality_events_available:

    quality = fact_quality_event.copy()

else:

    quality = pd.DataFrame()


# ================================================================================
# 4. STANDARDISE DATE DIMENSION
# ================================================================================

date_column_candidates = [
    "Date",
    "Calendar_Date",
    "Full_Date",
    "Date_Value"
]

date_column = None

for col in date_column_candidates:

    if col in dates.columns:

        date_column = col
        break


if date_column is None:

    raise ValueError(
        "Dim_Date must contain a date column. "
        f"Expected one of: {date_column_candidates}"
    )


dates[date_column] = pd.to_datetime(
    dates[date_column],
    errors="coerce"
)


if dates[date_column].isna().any():

    raise ValueError(
        "Dim_Date contains invalid dates."
    )


# ================================================================================
# 5. REQUIRED PO COLUMNS
# ================================================================================

required_po_columns = [
    "PO_Line_ID",
    "Supplier_ID",
    "Material_ID",
    "Quantity_Ordered",
    "Quantity_Received",
    "Order_Date",
    "Actual_Delivery_Date"
]

missing_po_columns = [
    c
    for c in required_po_columns
    if c not in po.columns
]

if missing_po_columns:

    raise ValueError(
        "Fact_PurchaseOrderLine is missing required columns: "
        f"{missing_po_columns}"
    )


# ================================================================================
# 6. STANDARDISE PO DATES / QUANTITIES
# ================================================================================

po["Order_Date"] = pd.to_datetime(
    po["Order_Date"],
    errors="coerce"
)

po["Actual_Delivery_Date"] = pd.to_datetime(
    po["Actual_Delivery_Date"],
    errors="coerce"
)

po["Quantity_Ordered"] = pd.to_numeric(
    po["Quantity_Ordered"],
    errors="coerce"
).fillna(0)

po["Quantity_Received"] = pd.to_numeric(
    po["Quantity_Received"],
    errors="coerce"
).fillna(0)


# ================================================================================
# 7. STANDARDISE QUALITY EVENT DATA
# ================================================================================

if quality_events_available:

    if "Quality_Event_Date" not in quality.columns:

        raise ValueError(
            "Fact_QualityEvent is present but "
            "Quality_Event_Date is missing."
        )

    if "PO_Line_ID" not in quality.columns:

        raise ValueError(
            "Fact_QualityEvent is present but "
            "PO_Line_ID is missing."
        )

    if "Rejected_Quantity" not in quality.columns:

        raise ValueError(
            "Fact_QualityEvent is present but "
            "Rejected_Quantity is missing."
        )

    quality["Quality_Event_Date"] = pd.to_datetime(
        quality["Quality_Event_Date"],
        errors="coerce"
    )

    quality["Rejected_Quantity"] = pd.to_numeric(
        quality["Rejected_Quantity"],
        errors="coerce"
    ).fillna(0)


# ================================================================================
# 8. ANALYTICAL DATE WINDOW
# ================================================================================

dates = dates[
    (
        dates[date_column] >= START_DATE
    )
    &
    (
        dates[date_column] <= REFERENCE_DATE
    )
].copy()

dates = (
    dates
    .sort_values(date_column)
    .drop_duplicates(subset=[date_column])
    .reset_index(drop=True)
)


if len(dates) == 0:

    raise ValueError(
        "No analytical dates remain after date filtering."
    )


print()
print(
    f"✓ Analytical dates retained : {len(dates):,}"
)


# ================================================================================
# 9. MATERIAL VALIDATION
# ================================================================================

if "Material_ID" not in materials.columns:

    raise ValueError(
        "Dim_Material must contain Material_ID."
    )


materials = (
    materials
    .drop_duplicates("Material_ID")
    .copy()
)


if materials["Material_ID"].duplicated().any():

    raise ValueError(
        "Material_ID is not unique in Dim_Material."
    )


material_ids = (
    materials["Material_ID"]
    .dropna()
    .unique()
)


if len(material_ids) == 0:

    raise ValueError(
        "No valid Material_ID values detected."
    )


print(
    f"✓ Unique materials validated : "
    f"{len(material_ids):,}"
)


# ================================================================================
# 10. PO MATERIAL FOREIGN KEY VALIDATION
# ================================================================================

if not set(
    po["Material_ID"].dropna()
).issubset(
    set(material_ids)
):

    raise ValueError(
        "Fact_PurchaseOrderLine contains Material_ID values "
        "not present in Dim_Material."
    )


print(
    "✓ PO MATERIAL FOREIGN KEYS VALID"
)


# ================================================================================
# 11. IDENTIFY SAFETY STOCK COLUMN
# ================================================================================

safety_stock_candidates = [
    "Safety_Stock",
    "Safety_Stock_Qty",
    "Safety_Stock_Quantity",
    "SafetyStock",
    "SafetyStock_Qty"
]

safety_stock_column = None

for col in safety_stock_candidates:

    if col in materials.columns:

        safety_stock_column = col
        break


# ================================================================================
# 12. BUILD PROCUREMENT DEMAND PROXY
# ================================================================================
#
# Demand proxy:
#
#   Quantity Ordered
#   recognised on Order_Date.
#
# This represents material demand entering procurement.
#
# Future orders cannot affect earlier dates because the demand is anchored
# strictly to Order_Date.
#
# Cancelled orders are excluded where a usable status column exists and the
# status explicitly indicates cancellation.
# ================================================================================

demand_orders = po[
    (
        po["Order_Date"].notna()
    )
    &
    (
        po["Order_Date"] >= START_DATE
    )
    &
    (
        po["Order_Date"] <= REFERENCE_DATE
    )
].copy()


# -------------------------------------------------------------------------------
# Optional cancellation handling
# -------------------------------------------------------------------------------

status_column_candidates = [
    "Purchase_Order_Status",
    "PO_Status",
    "Order_Status",
    "Status"
]

po_status_column = None

for col in status_column_candidates:

    if col in demand_orders.columns:

        po_status_column = col
        break


if po_status_column is not None:

    cancelled_mask = (
        demand_orders[
            po_status_column
        ]
        .astype(str)
        .str.strip()
        .str.lower()
        .isin(
            [
                "cancelled",
                "canceled",
                "cancel"
            ]
        )
    )

    cancelled_count = int(
        cancelled_mask.sum()
    )

    demand_orders = demand_orders[
        ~cancelled_mask
    ].copy()

    print(
        f"✓ Cancelled PO demand excluded : "
        f"{cancelled_count:,}"
    )


demand_orders["Demand_Date"] = (
    demand_orders["Order_Date"]
)


daily_demand = (
    demand_orders
    .groupby(
        [
            "Demand_Date",
            "Material_ID"
        ],
        as_index=False
    )
    .agg(
        Demand_Quantity=(
            "Quantity_Ordered",
            "sum"
        )
    )
)


daily_demand["Demand_Quantity"] = (
    pd.to_numeric(
        daily_demand["Demand_Quantity"],
        errors="coerce"
    )
    .fillna(0)
    .clip(lower=0)
)


print(
    f"✓ Procurement demand-proxy records built : "
    f"{len(daily_demand):,}"
)


# ================================================================================
# 13. SAFETY STOCK
# ================================================================================

if safety_stock_column is not None:

    print(
        f"✓ Existing safety stock detected : "
        f"{safety_stock_column}"
    )

    material_safety_stock = (
        materials[
            [
                "Material_ID",
                safety_stock_column
            ]
        ]
        .copy()
    )

    material_safety_stock[
        "Safety_Stock"
    ] = pd.to_numeric(
        material_safety_stock[
            safety_stock_column
        ],
        errors="coerce"
    )

    material_safety_stock[
        "Safety_Stock"
    ] = (
        material_safety_stock[
            "Safety_Stock"
        ]
        .fillna(MIN_SAFETY_STOCK)
        .clip(lower=MIN_SAFETY_STOCK)
    )

else:

    print(
        "ℹ Safety_Stock not found in Dim_Material."
    )

    print(
        "✓ Deriving Safety_Stock from first "
        f"{SAFETY_STOCK_LOOKBACK_DAYS} days."
    )

    safety_cutoff = (
        START_DATE
        +
        pd.Timedelta(
            days=SAFETY_STOCK_LOOKBACK_DAYS - 1
        )
    )

    early_demand = daily_demand[
        (
            daily_demand["Demand_Date"]
            >= START_DATE
        )
        &
        (
            daily_demand["Demand_Date"]
            <= safety_cutoff
        )
    ].copy()


    if len(early_demand) > 0:

        material_demand_stats = (
            early_demand
            .groupby("Material_ID")
            .agg(
                Total_Early_Demand=(
                    "Demand_Quantity",
                    "sum"
                )
            )
            .reset_index()
        )

        material_demand_stats[
            "Mean_Daily_Demand"
        ] = (
            material_demand_stats[
                "Total_Early_Demand"
            ]
            /
            SAFETY_STOCK_LOOKBACK_DAYS
        )

    else:

        material_demand_stats = pd.DataFrame(
            columns=[
                "Material_ID",
                "Mean_Daily_Demand"
            ]
        )


    material_safety_stock = (
        materials[
            [
                "Material_ID"
            ]
        ]
        .copy()
    )


    material_safety_stock = (
        material_safety_stock
        .merge(
            material_demand_stats[
                [
                    "Material_ID",
                    "Mean_Daily_Demand"
                ]
            ],
            on="Material_ID",
            how="left",
            validate="one_to_one"
        )
    )


    material_safety_stock[
        "Mean_Daily_Demand"
    ] = (
        material_safety_stock[
            "Mean_Daily_Demand"
        ]
        .fillna(0)
    )


    material_safety_stock[
        "Safety_Stock"
    ] = np.ceil(
        material_safety_stock[
            "Mean_Daily_Demand"
        ]
        *
        7
    )


    material_safety_stock[
        "Safety_Stock"
    ] = (
        material_safety_stock[
            "Safety_Stock"
        ]
        .clip(
            lower=MIN_SAFETY_STOCK
        )
    )


    print(
        "✓ Safety stock successfully derived."
    )


# ================================================================================
# 14. FINAL SAFETY STOCK STANDARDISATION
# ================================================================================

material_safety_stock[
    "Safety_Stock"
] = pd.to_numeric(
    material_safety_stock[
        "Safety_Stock"
    ],
    errors="coerce"
).fillna(MIN_SAFETY_STOCK)


material_safety_stock[
    "Safety_Stock"
] = (
    material_safety_stock[
        "Safety_Stock"
    ]
    .round()
    .astype(int)
    .clip(lower=MIN_SAFETY_STOCK)
)


# ================================================================================
# 15. RECEIPT HISTORY
# ================================================================================

receipts = po[
    (
        po["Actual_Delivery_Date"].notna()
    )
    &
    (
        po["Actual_Delivery_Date"] >= START_DATE
    )
    &
    (
        po["Actual_Delivery_Date"] <= REFERENCE_DATE
    )
].copy()


receipts["Receipt_Date"] = (
    receipts["Actual_Delivery_Date"]
)


receipts["Gross_Received_Quantity"] = (
    pd.to_numeric(
        receipts[
            "Quantity_Received"
        ],
        errors="coerce"
    )
    .fillna(0)
    .clip(lower=0)
)


# -------------------------------------------------------------------------------
# Basic receipt validation
# -------------------------------------------------------------------------------

if not (
    receipts["Gross_Received_Quantity"]
    <=
    receipts["Quantity_Ordered"]
).all():

    raise ValueError(
        "Quantity_Received exceeds Quantity_Ordered "
        "for at least one receipt."
    )


print(
    f"✓ Valid receipt records : "
    f"{len(receipts):,}"
)


# ================================================================================
# 16. QUALITY REJECTIONS
# ================================================================================

if quality_events_available:

    quality_rejections = (
        quality
        .groupby(
            [
                "Quality_Event_Date",
                "PO_Line_ID"
            ],
            as_index=False
        )
        .agg(
            Rejected_Quantity=(
                "Rejected_Quantity",
                "sum"
            )
        )
    )


    receipts = receipts.merge(
        quality_rejections,
        left_on=[
            "Receipt_Date",
            "PO_Line_ID"
        ],
        right_on=[
            "Quality_Event_Date",
            "PO_Line_ID"
        ],
        how="left"
    )


    receipts[
        "Rejected_Quantity"
    ] = (
        receipts[
            "Rejected_Quantity"
        ]
        .fillna(0)
        .clip(lower=0)
    )


else:

    receipts[
        "Rejected_Quantity"
    ] = 0


# ================================================================================
# 17. REJECTED QUANTITY VALIDATION
# ================================================================================

if not (
    receipts[
        "Rejected_Quantity"
    ]
    <=
    receipts[
        "Gross_Received_Quantity"
    ]
).all():

    raise ValueError(
        "Rejected quantity exceeds received quantity."
    )


# ================================================================================
# 18. QUALITY-ADJUSTED USABLE RECEIPTS
# ================================================================================

receipts[
    "Usable_Receipt_Quantity"
] = (
    receipts[
        "Gross_Received_Quantity"
    ]
    -
    receipts[
        "Rejected_Quantity"
    ]
).clip(lower=0)


print(
    "✓ Quality-adjusted usable receipts calculated."
)


# ================================================================================
# 19. DAILY RECEIPTS
# ================================================================================

daily_receipts = (
    receipts
    .groupby(
        [
            "Receipt_Date",
            "Material_ID"
        ],
        as_index=False
    )
    .agg(
        Gross_Receipt_Quantity=(
            "Gross_Received_Quantity",
            "sum"
        ),
        Rejected_Receipt_Quantity=(
            "Rejected_Quantity",
            "sum"
        ),
        Usable_Receipt_Quantity=(
            "Usable_Receipt_Quantity",
            "sum"
        )
    )
)


print(
    f"✓ Daily receipt records built : "
    f"{len(daily_receipts):,}"
)


# ================================================================================
# 20. COMPLETE MATERIAL × DATE GRID
# ================================================================================

material_date_grid = (
    pd.MultiIndex
    .from_product(
        [
            material_ids,
            dates[date_column]
        ],
        names=[
            "Material_ID",
            "Snapshot_Date"
        ]
    )
    .to_frame(index=False)
)


expected_rows = (
    len(material_ids)
    *
    len(dates)
)


if len(material_date_grid) != expected_rows:

    raise ValueError(
        "Material × Date grid row count is incorrect."
    )


print(
    f"✓ Inventory grid created : "
    f"{len(material_date_grid):,} rows"
)


# ================================================================================
# 21. MERGE SAFETY STOCK
# ================================================================================

material_date_grid = (
    material_date_grid
    .merge(
        material_safety_stock[
            [
                "Material_ID",
                "Safety_Stock"
            ]
        ],
        on="Material_ID",
        how="left",
        validate="many_to_one"
    )
)


if material_date_grid[
    "Safety_Stock"
].isna().any():

    raise ValueError(
        "Safety Stock missing for one or more materials."
    )


# ================================================================================
# 22. MERGE DAILY DEMAND
# ================================================================================

material_date_grid = (
    material_date_grid
    .merge(
        daily_demand[
            [
                "Demand_Date",
                "Material_ID",
                "Demand_Quantity"
            ]
        ],
        left_on=[
            "Snapshot_Date",
            "Material_ID"
        ],
        right_on=[
            "Demand_Date",
            "Material_ID"
        ],
        how="left"
    )
)


material_date_grid[
    "Demand_Quantity"
] = (
    material_date_grid[
        "Demand_Quantity"
    ]
    .fillna(0)
    .clip(lower=0)
)


material_date_grid.drop(
    columns=["Demand_Date"],
    inplace=True
)


# ================================================================================
# 23. MERGE DAILY RECEIPTS
# ================================================================================

material_date_grid = (
    material_date_grid
    .merge(
        daily_receipts[
            [
                "Receipt_Date",
                "Material_ID",
                "Gross_Receipt_Quantity",
                "Rejected_Receipt_Quantity",
                "Usable_Receipt_Quantity"
            ]
        ],
        left_on=[
            "Snapshot_Date",
            "Material_ID"
        ],
        right_on=[
            "Receipt_Date",
            "Material_ID"
        ],
        how="left"
    )
)


for col in [
    "Gross_Receipt_Quantity",
    "Rejected_Receipt_Quantity",
    "Usable_Receipt_Quantity"
]:

    material_date_grid[col] = (
        material_date_grid[col]
        .fillna(0)
        .clip(lower=0)
    )


material_date_grid.drop(
    columns=["Receipt_Date"],
    inplace=True
)


# ================================================================================
# 24. INITIAL INVENTORY BASELINE
# ================================================================================
#
# Starting inventory is based on Safety Stock.
#
# This establishes the opening operational state without using future
# inventory information.
# ================================================================================

material_date_grid[
    "Initial_Inventory"
] = np.ceil(
    material_date_grid[
        "Safety_Stock"
    ]
    *
    1.50
)


material_date_grid[
    "Initial_Inventory"
] = (
    material_date_grid[
        "Initial_Inventory"
    ]
    .clip(
        lower=MIN_SAFETY_STOCK
    )
)


# ================================================================================
# 25. CHRONOLOGICAL INVENTORY ENGINE
# ================================================================================
#
# For each material:
#
#   Previous On-Hand
#       +
#   Usable Receipt
#       -
#   Demand
#       =
#   Ending On-Hand
#
# Inventory cannot become negative.
#
# Any unmet demand becomes Stockout_Quantity.
#
# Because the loop moves forward chronologically, future receipts and future
# demand cannot influence previous dates.
# ================================================================================

material_date_grid = (
    material_date_grid
    .sort_values(
        [
            "Material_ID",
            "Snapshot_Date"
        ]
    )
    .reset_index(drop=True)
)


material_date_grid[
    "On_Hand_Quantity"
] = 0.0


material_date_grid[
    "Inventory_Before_Demand"
] = 0.0


material_date_grid[
    "Stockout_Quantity"
] = 0.0


for material_id, idx in material_date_grid.groupby(
    "Material_ID"
).groups.items():

    idx = list(idx)

    running_inventory = float(
        material_date_grid.loc[
            idx[0],
            "Initial_Inventory"
        ]
    )


    for row_index in idx:

        usable_receipt = float(
            material_date_grid.loc[
                row_index,
                "Usable_Receipt_Quantity"
            ]
        )

        demand = float(
            material_date_grid.loc[
                row_index,
                "Demand_Quantity"
            ]
        )


        inventory_before_demand = (
            running_inventory
            +
            usable_receipt
        )


        stockout_quantity = max(
            demand
            -
            inventory_before_demand,
            0
        )


        ending_inventory = max(
            inventory_before_demand
            -
            demand,
            0
        )


        material_date_grid.loc[
            row_index,
            "Inventory_Before_Demand"
        ] = inventory_before_demand


        material_date_grid.loc[
            row_index,
            "Stockout_Quantity"
        ] = stockout_quantity


        material_date_grid.loc[
            row_index,
            "On_Hand_Quantity"
        ] = ending_inventory


        running_inventory = ending_inventory


print(
    "✓ Chronological inventory engine completed."
)

print(
    "✓ Future receipts cannot affect earlier snapshots."
)


# ================================================================================
# 26. INVENTORY FLOW
# ================================================================================

material_date_grid[
    "Net_Inventory_Change"
] = (
    material_date_grid[
        "Usable_Receipt_Quantity"
    ]
    -
    material_date_grid[
        "Demand_Quantity"
    ]
)


# ================================================================================
# 27. FINAL QUANTITY STANDARDISATION
# ================================================================================
#
# CRITICAL:
#
# All inventory quantities are converted to the FINAL stored representation
# BEFORE any stock flags are created.
#
# This eliminates the previous bug where:
#
#   float On_Hand = 0.4
#   Stockout_Flag = 0
#
# later became:
#
#   integer On_Hand = 0
#
# while the flag remained 0.
# ================================================================================

quantity_columns = [
    "Safety_Stock",
    "Demand_Quantity",
    "Gross_Receipt_Quantity",
    "Rejected_Receipt_Quantity",
    "Usable_Receipt_Quantity",
    "Initial_Inventory",
    "Inventory_Before_Demand",
    "On_Hand_Quantity",
    "Net_Inventory_Change",
    "Stockout_Quantity"
]


for col in quantity_columns:

    material_date_grid[col] = (
        pd.to_numeric(
            material_date_grid[col],
            errors="coerce"
        )
        .fillna(0)
        .round()
        .astype(int)
    )


# ================================================================================
# 28. STOCKOUT FLAG
# ================================================================================
#
# LOCKED DEFINITION:
#
#   Stockout_Flag = 1 ONLY when On_Hand_Quantity <= 0
# ================================================================================

material_date_grid[
    "Stockout_Flag"
] = (
    material_date_grid[
        "On_Hand_Quantity"
    ]
    <= 0
).astype(int)


# ================================================================================
# 29. SAFETY STOCK BREACH FLAG
# ================================================================================

material_date_grid[
    "Safety_Stock_Breach_Flag"
] = (
    material_date_grid[
        "On_Hand_Quantity"
    ]
    <
    material_date_grid[
        "Safety_Stock"
    ]
).astype(int)


# ================================================================================
# 30. LOW STOCK FLAG
# ================================================================================

material_date_grid[
    "Low_Stock_Flag"
] = (
    material_date_grid[
        "On_Hand_Quantity"
    ]
    <=
    material_date_grid[
        "Safety_Stock"
    ]
).astype(int)


# ================================================================================
# 31. CRITICAL STOCK FLAG
# ================================================================================

material_date_grid[
    "Critical_Stock_Flag"
] = (
    material_date_grid[
        "On_Hand_Quantity"
    ]
    <=
    (
        material_date_grid[
            "Safety_Stock"
        ]
        *
        CRITICAL_STOCK_RATIO
    )
).astype(int)


# ================================================================================
# 32. INVENTORY COVERAGE DAYS
# ================================================================================
#
# Current-day demand is used as an operational coverage signal.
#
# If demand is zero, coverage is undefined and therefore NaN.
# ================================================================================

material_date_grid[
    "Inventory_Coverage_Days"
] = np.where(
    material_date_grid[
        "Demand_Quantity"
    ] > 0,

    material_date_grid[
        "On_Hand_Quantity"
    ]
    /
    material_date_grid[
        "Demand_Quantity"
    ],

    np.nan
)


# ================================================================================
# 33. QUALITY REJECTION RATE
# ================================================================================

material_date_grid[
    "Receipt_Rejection_Rate"
] = np.where(
    material_date_grid[
        "Gross_Receipt_Quantity"
    ] > 0,

    material_date_grid[
        "Rejected_Receipt_Quantity"
    ]
    /
    material_date_grid[
        "Gross_Receipt_Quantity"
    ],

    0
)


material_date_grid[
    "Receipt_Rejection_Rate"
] = (
    material_date_grid[
        "Receipt_Rejection_Rate"
    ]
    .clip(
        lower=0,
        upper=1
    )
)


# ================================================================================
# 34. USABLE RECEIPT RATE
# ================================================================================

material_date_grid[
    "Usable_Receipt_Rate"
] = np.where(
    material_date_grid[
        "Gross_Receipt_Quantity"
    ] > 0,

    material_date_grid[
        "Usable_Receipt_Quantity"
    ]
    /
    material_date_grid[
        "Gross_Receipt_Quantity"
    ],

    np.nan
)


material_date_grid[
    "Usable_Receipt_Rate"
] = (
    material_date_grid[
        "Usable_Receipt_Rate"
    ]
    .clip(
        lower=0,
        upper=1
    )
)


# ================================================================================
# 35. INVENTORY RISK STATE
# ================================================================================

conditions = [

    (
        material_date_grid[
            "Stockout_Flag"
        ]
        ==
        1
    ),

    (
        material_date_grid[
            "Critical_Stock_Flag"
        ]
        ==
        1
    ),

    (
        material_date_grid[
            "Safety_Stock_Breach_Flag"
        ]
        ==
        1
    )
]


choices = [
    "Stockout",
    "Critical",
    "Below Safety Stock"
]


material_date_grid[
    "Inventory_Risk_State"
] = np.select(
    conditions,
    choices,
    default="Healthy"
)


# ================================================================================
# 36. INVENTORY RISK SCORE
# ================================================================================
#
# Descriptive current-state operational risk score.
#
# NOT a predictive target.
# ================================================================================

material_date_grid[
    "Inventory_Risk_Score"
] = 0.0


material_date_grid.loc[
    material_date_grid[
        "Safety_Stock_Breach_Flag"
    ] == 1,
    "Inventory_Risk_Score"
] += 35


material_date_grid.loc[
    material_date_grid[
        "Critical_Stock_Flag"
    ] == 1,
    "Inventory_Risk_Score"
] += 25


material_date_grid.loc[
    material_date_grid[
        "Stockout_Flag"
    ] == 1,
    "Inventory_Risk_Score"
] += 40


material_date_grid[
    "Inventory_Risk_Score"
] += (
    material_date_grid[
        "Receipt_Rejection_Rate"
    ]
    *
    20
)


material_date_grid[
    "Inventory_Risk_Score"
] = (
    material_date_grid[
        "Inventory_Risk_Score"
    ]
    .clip(
        lower=0,
        upper=100
    )
)


# ================================================================================
# 37. INVENTORY RISK TIER
# ================================================================================

material_date_grid[
    "Inventory_Risk_Tier"
] = np.select(
    [
        material_date_grid[
            "Inventory_Risk_Score"
        ] >= 75,

        material_date_grid[
            "Inventory_Risk_Score"
        ] >= 45,

        material_date_grid[
            "Inventory_Risk_Score"
        ] >= 20
    ],

    [
        "Critical",
        "High",
        "Medium"
    ],

    default="Low"
)


# ================================================================================
# 38. ROLLING INVENTORY SIGNALS
# ================================================================================

material_date_grid[
    "Rolling_30D_Avg_Inventory"
] = (
    material_date_grid
    .groupby(
        "Material_ID"
    )[
        "On_Hand_Quantity"
    ]
    .transform(
        lambda x:
        x.rolling(
            DEMAND_SMOOTHING_DAYS,
            min_periods=1
        ).mean()
    )
)


material_date_grid[
    "Rolling_30D_Avg_Demand"
] = (
    material_date_grid
    .groupby(
        "Material_ID"
    )[
        "Demand_Quantity"
    ]
    .transform(
        lambda x:
        x.rolling(
            DEMAND_SMOOTHING_DAYS,
            min_periods=1
        ).mean()
    )
)


material_date_grid[
    "Inventory_Trend"
] = (
    material_date_grid[
        "On_Hand_Quantity"
    ]
    -
    material_date_grid[
        "Rolling_30D_Avg_Inventory"
    ]
)


# ================================================================================
# 39. DATE_ID LOOKUP
# ================================================================================

date_lookup = dates[
    [
        date_column
    ]
].copy()


date_lookup[
    "Date_ID"
] = (
    date_lookup[
        date_column
    ]
    .dt.strftime("%Y%m%d")
    .astype(int)
)


date_lookup.rename(
    columns={
        date_column: "Snapshot_Date"
    },
    inplace=True
)


material_date_grid = (
    material_date_grid
    .merge(
        date_lookup[
            [
                "Snapshot_Date",
                "Date_ID"
            ]
        ],
        on="Snapshot_Date",
        how="left",
        validate="many_to_one"
    )
)


# ================================================================================
# 40. DATE_ID NULL CHECK
# ================================================================================

if material_date_grid[
    "Date_ID"
].isna().any():

    raise ValueError(
        "Date_ID could not be assigned to every inventory snapshot."
    )


material_date_grid[
    "Date_ID"
] = (
    material_date_grid[
        "Date_ID"
    ]
    .astype(int)
)


# ================================================================================
# 41. FINAL FACT TABLE
# ================================================================================

fact_inventory_snapshot = material_date_grid[
    [
        "Date_ID",
        "Snapshot_Date",
        "Material_ID",

        "Safety_Stock",

        "Demand_Quantity",

        "Gross_Receipt_Quantity",
        "Rejected_Receipt_Quantity",
        "Usable_Receipt_Quantity",

        "Inventory_Before_Demand",
        "On_Hand_Quantity",
        "Net_Inventory_Change",

        "Stockout_Quantity",

        "Stockout_Flag",
        "Low_Stock_Flag",
        "Safety_Stock_Breach_Flag",
        "Critical_Stock_Flag",

        "Inventory_Coverage_Days",

        "Receipt_Rejection_Rate",
        "Usable_Receipt_Rate",

        "Rolling_30D_Avg_Inventory",
        "Rolling_30D_Avg_Demand",
        "Inventory_Trend",

        "Inventory_Risk_State",
        "Inventory_Risk_Score",
        "Inventory_Risk_Tier"
    ]
].copy()


# ================================================================================
# 42. FINAL DATA TYPES
# ================================================================================

integer_columns = [
    "Date_ID",
    "Safety_Stock",
    "Demand_Quantity",
    "Gross_Receipt_Quantity",
    "Rejected_Receipt_Quantity",
    "Usable_Receipt_Quantity",
    "Inventory_Before_Demand",
    "On_Hand_Quantity",
    "Net_Inventory_Change",
    "Stockout_Quantity",
    "Stockout_Flag",
    "Low_Stock_Flag",
    "Safety_Stock_Breach_Flag",
    "Critical_Stock_Flag"
]


for col in integer_columns:

    fact_inventory_snapshot[col] = (
        pd.to_numeric(
            fact_inventory_snapshot[col],
            errors="coerce"
        )
        .fillna(0)
        .round()
        .astype(int)
    )


# ================================================================================
# 43. RECOMPUTE ALL FLAGS FROM FINAL STORED VALUES
# ================================================================================
#
# This is deliberately repeated AFTER the final data-type conversion.
#
# Therefore the validation and the stored table use exactly the same values.
# ================================================================================

fact_inventory_snapshot[
    "Stockout_Flag"
] = (
    fact_inventory_snapshot[
        "On_Hand_Quantity"
    ]
    <= 0
).astype(int)


fact_inventory_snapshot[
    "Safety_Stock_Breach_Flag"
] = (
    fact_inventory_snapshot[
        "On_Hand_Quantity"
    ]
    <
    fact_inventory_snapshot[
        "Safety_Stock"
    ]
).astype(int)


fact_inventory_snapshot[
    "Low_Stock_Flag"
] = (
    fact_inventory_snapshot[
        "On_Hand_Quantity"
    ]
    <=
    fact_inventory_snapshot[
        "Safety_Stock"
    ]
).astype(int)


fact_inventory_snapshot[
    "Critical_Stock_Flag"
] = (
    fact_inventory_snapshot[
        "On_Hand_Quantity"
    ]
    <=
    (
        fact_inventory_snapshot[
            "Safety_Stock"
        ]
        *
        CRITICAL_STOCK_RATIO
    )
).astype(int)


# ================================================================================
# 44. VALIDATION
# ================================================================================

print()
print("=" * 80)
print("KEYSTRA — FACT_INVENTORYSNAPSHOT VALIDATION")
print("=" * 80)


# ================================================================================
# 45. ROW COUNT
# ================================================================================

actual_rows = len(
    fact_inventory_snapshot
)

expected_rows = (
    len(material_ids)
    *
    len(dates)
)


if actual_rows != expected_rows:

    raise ValueError(
        f"ROW COUNT MISMATCH. "
        f"Expected {expected_rows:,}; "
        f"received {actual_rows:,}."
    )


print(
    f"✓ ROW COUNT VALID : "
    f"{actual_rows:,}"
)


# ================================================================================
# 46. MATERIAL × DATE GRAIN
# ================================================================================

if fact_inventory_snapshot[
    [
        "Material_ID",
        "Snapshot_Date"
    ]
].duplicated().any():

    raise ValueError(
        "Duplicate Material_ID + Snapshot_Date combinations detected."
    )


print(
    "✓ MATERIAL × DATE GRAIN UNIQUE"
)


# ================================================================================
# 47. MATERIAL FOREIGN KEY
# ================================================================================

valid_material_ids = set(
    materials[
        "Material_ID"
    ]
)


if not set(
    fact_inventory_snapshot[
        "Material_ID"
    ]
).issubset(valid_material_ids):

    raise ValueError(
        "Invalid Material_ID detected."
    )


print(
    "✓ MATERIAL FOREIGN KEYS VALID"
)


# ================================================================================
# 48. DATE FOREIGN KEY
# ================================================================================

valid_date_ids = set(
    date_lookup[
        "Date_ID"
    ]
)


if not set(
    fact_inventory_snapshot[
        "Date_ID"
    ]
).issubset(valid_date_ids):

    raise ValueError(
        "Invalid Date_ID detected."
    )


print(
    "✓ DATE FOREIGN KEYS VALID"
)


# ================================================================================
# 49. DATE RANGE
# ================================================================================

if (
    fact_inventory_snapshot[
        "Snapshot_Date"
    ]
    < START_DATE
).any():

    raise ValueError(
        "Inventory snapshot exists before dataset start."
    )


if (
    fact_inventory_snapshot[
        "Snapshot_Date"
    ]
    > REFERENCE_DATE
).any():

    raise ValueError(
        "Inventory snapshot exists after reference date."
    )


print(
    "✓ SNAPSHOT DATES WITHIN ANALYTICAL WINDOW"
)


# ================================================================================
# 50. SAFETY STOCK
# ================================================================================

if (
    fact_inventory_snapshot[
        "Safety_Stock"
    ]
    <= 0
).any():

    raise ValueError(
        "Safety Stock contains zero/negative values."
    )


print(
    "✓ SAFETY STOCK VALID"
)


# ================================================================================
# 51. ON-HAND NON-NEGATIVITY
# ================================================================================

if (
    fact_inventory_snapshot[
        "On_Hand_Quantity"
    ]
    < 0
).any():

    raise ValueError(
        "On_Hand_Quantity contains negative values."
    )


print(
    "✓ ON-HAND INVENTORY NON-NEGATIVE"
)


# ================================================================================
# 52. STOCKOUT FLAG — EXACT LOGIC
# ================================================================================

expected_stockout_flag = (
    fact_inventory_snapshot[
        "On_Hand_Quantity"
    ]
    <= 0
).astype(int)


actual_stockout_flag = (
    fact_inventory_snapshot[
        "Stockout_Flag"
    ]
    .astype(int)
)


if not (
    actual_stockout_flag.to_numpy()
    ==
    expected_stockout_flag.to_numpy()
).all():

    mismatch_count = (
        actual_stockout_flag
        !=
        expected_stockout_flag
    ).sum()

    raise ValueError(
        "Stockout_Flag is inconsistent with "
        "On_Hand_Quantity. "
        f"Mismatched rows: {mismatch_count:,}"
    )


print(
    "✓ STOCKOUT FLAG LOGIC CONSISTENT"
)


# ================================================================================
# 53. SAFETY STOCK BREACH
# ================================================================================

expected_safety_breach = (
    fact_inventory_snapshot[
        "On_Hand_Quantity"
    ]
    <
    fact_inventory_snapshot[
        "Safety_Stock"
    ]
).astype(int)


if not (
    fact_inventory_snapshot[
        "Safety_Stock_Breach_Flag"
    ].to_numpy()
    ==
    expected_safety_breach.to_numpy()
).all():

    raise ValueError(
        "Safety_Stock_Breach_Flag is inconsistent."
    )


print(
    "✓ SAFETY STOCK BREACH FLAG LOGIC CONSISTENT"
)


# ================================================================================
# 54. LOW STOCK
# ================================================================================

expected_low_stock = (
    fact_inventory_snapshot[
        "On_Hand_Quantity"
    ]
    <=
    fact_inventory_snapshot[
        "Safety_Stock"
    ]
).astype(int)


if not (
    fact_inventory_snapshot[
        "Low_Stock_Flag"
    ].to_numpy()
    ==
    expected_low_stock.to_numpy()
).all():

    raise ValueError(
        "Low_Stock_Flag is inconsistent."
    )


print(
    "✓ LOW STOCK FLAG LOGIC CONSISTENT"
)


# ================================================================================
# 55. CRITICAL STOCK
# ================================================================================

expected_critical_stock = (
    fact_inventory_snapshot[
        "On_Hand_Quantity"
    ]
    <=
    (
        fact_inventory_snapshot[
            "Safety_Stock"
        ]
        *
        CRITICAL_STOCK_RATIO
    )
).astype(int)


if not (
    fact_inventory_snapshot[
        "Critical_Stock_Flag"
    ].to_numpy()
    ==
    expected_critical_stock.to_numpy()
).all():

    raise ValueError(
        "Critical_Stock_Flag is inconsistent."
    )


print(
    "✓ CRITICAL STOCK FLAG LOGIC CONSISTENT"
)


# ================================================================================
# 56. STOCKOUT ROWS
# ================================================================================

stockout_rows = fact_inventory_snapshot[
    fact_inventory_snapshot[
        "Stockout_Flag"
    ] == 1
]


if not (
    stockout_rows[
        "On_Hand_Quantity"
    ]
    <= 0
).all():

    raise ValueError(
        "Stockout rows contain positive inventory."
    )


print(
    "✓ STOCKOUT ROWS HAVE ZERO ON-HAND INVENTORY"
)


# ================================================================================
# 57. RECEIPT QUANTITY LOGIC
# ================================================================================

if not (
    fact_inventory_snapshot[
        "Rejected_Receipt_Quantity"
    ]
    <=
    fact_inventory_snapshot[
        "Gross_Receipt_Quantity"
    ]
).all():

    raise ValueError(
        "Rejected receipt quantity exceeds gross receipt quantity."
    )


if not (
    fact_inventory_snapshot[
        "Usable_Receipt_Quantity"
    ]
    <=
    fact_inventory_snapshot[
        "Gross_Receipt_Quantity"
    ]
).all():

    raise ValueError(
        "Usable receipt quantity exceeds gross receipt quantity."
    )


print(
    "✓ RECEIPT QUANTITY LOGIC VALID"
)


# ================================================================================
# 58. RECEIPT REJECTION RATE
# ================================================================================

if (
    fact_inventory_snapshot[
        "Receipt_Rejection_Rate"
    ]
    < 0
).any():

    raise ValueError(
        "Negative receipt rejection rate detected."
    )


if (
    fact_inventory_snapshot[
        "Receipt_Rejection_Rate"
    ]
    > 1
).any():

    raise ValueError(
        "Receipt rejection rate exceeds 100%."
    )


print(
    "✓ RECEIPT REJECTION RATE VALID"
)


# ================================================================================
# 59. USABLE RECEIPT RATE
# ================================================================================

usable_rate_non_null = (
    fact_inventory_snapshot[
        "Usable_Receipt_Rate"
    ]
    .dropna()
)


if (
    usable_rate_non_null < 0
).any() or (
    usable_rate_non_null > 1
).any():

    raise ValueError(
        "Usable receipt rate outside 0–1 range."
    )


print(
    "✓ USABLE RECEIPT RATE VALID"
)


# ================================================================================
# 60. INVENTORY COVERAGE
# ================================================================================

coverage = (
    fact_inventory_snapshot[
        "Inventory_Coverage_Days"
    ]
    .dropna()
)


if (
    coverage < 0
).any():

    raise ValueError(
        "Negative Inventory_Coverage_Days detected."
    )


print(
    "✓ INVENTORY COVERAGE LOGIC VALID"
)


# ================================================================================
# 61. RISK STATES
# ================================================================================

valid_risk_states = {
    "Healthy",
    "Below Safety Stock",
    "Critical",
    "Stockout"
}


if not set(
    fact_inventory_snapshot[
        "Inventory_Risk_State"
    ]
).issubset(valid_risk_states):

    raise ValueError(
        "Invalid Inventory_Risk_State detected."
    )


print(
    "✓ INVENTORY RISK STATES VALID"
)


# ================================================================================
# 62. RISK TIERS
# ================================================================================

valid_risk_tiers = {
    "Low",
    "Medium",
    "High",
    "Critical"
}


if not set(
    fact_inventory_snapshot[
        "Inventory_Risk_Tier"
    ]
).issubset(valid_risk_tiers):

    raise ValueError(
        "Invalid Inventory_Risk_Tier detected."
    )


print(
    "✓ INVENTORY RISK TIERS VALID"
)


# ================================================================================
# 63. RISK SCORE
# ================================================================================

if (
    fact_inventory_snapshot[
        "Inventory_Risk_Score"
    ]
    < 0
).any():

    raise ValueError(
        "Inventory_Risk_Score below zero."
    )


if (
    fact_inventory_snapshot[
        "Inventory_Risk_Score"
    ]
    > 100
).any():

    raise ValueError(
        "Inventory_Risk_Score above 100."
    )


print(
    "✓ INVENTORY RISK SCORE VALID"
)


# ================================================================================
# 64. RISK STATE / FLAG CONSISTENCY
# ================================================================================

if (
    (
        fact_inventory_snapshot[
            "Stockout_Flag"
        ] == 1
    )
    &
    (
        fact_inventory_snapshot[
            "Inventory_Risk_State"
        ] != "Stockout"
    )
).any():

    raise ValueError(
        "Stockout rows do not have Inventory_Risk_State='Stockout'."
    )


if (
    (
        fact_inventory_snapshot[
            "Critical_Stock_Flag"
        ] == 1
    )
    &
    (
        fact_inventory_snapshot[
            "Stockout_Flag"
        ] == 0
    )
    &
    (
        fact_inventory_snapshot[
            "Inventory_Risk_State"
        ] != "Critical"
    )
).any():

    raise ValueError(
        "Critical inventory rows have inconsistent risk state."
    )


print(
    "✓ INVENTORY RISK STATE / FLAG RELATIONSHIPS VALID"
)


# ================================================================================
# 65. TEMPORAL RECEIPT VALIDATION
# ================================================================================

future_receipts = receipts[
    receipts[
        "Receipt_Date"
    ]
    > REFERENCE_DATE
]


if len(future_receipts) > 0:

    raise ValueError(
        "Future receipts detected in inventory source."
    )


print(
    "✓ NO FUTURE RECEIPTS ENTER INVENTORY MODEL"
)


# ================================================================================
# 66. TEMPORAL QUALITY VALIDATION
# ================================================================================

if quality_events_available:

    future_quality = quality[
        quality[
            "Quality_Event_Date"
        ]
        > REFERENCE_DATE
    ]


    if len(future_quality) > 0:

        raise ValueError(
            "Future quality events detected."
        )


    print(
        "✓ NO FUTURE QUALITY EVENTS ENTER INVENTORY MODEL"
    )


# ================================================================================
# 67. QUALITY EVENT / RECEIPT DATE VALIDATION
# ================================================================================

if quality_events_available:

    quality_date_check = quality[
        [
            "PO_Line_ID",
            "Quality_Event_Date"
        ]
    ].merge(
        po[
            [
                "PO_Line_ID",
                "Actual_Delivery_Date"
            ]
        ],
        on="PO_Line_ID",
        how="left"
    )


    quality_date_check[
        "Actual_Delivery_Date"
    ] = pd.to_datetime(
        quality_date_check[
            "Actual_Delivery_Date"
        ],
        errors="coerce"
    )


    if not (
        quality_date_check[
            "Quality_Event_Date"
        ]
        >=
        quality_date_check[
            "Actual_Delivery_Date"
        ]
    ).all():

        raise ValueError(
            "Quality event occurs before actual delivery."
        )


    print(
        "✓ QUALITY EVENTS OCCUR ON/AFTER DELIVERY"
    )


# ================================================================================
# 68. MATERIAL COVERAGE
# ================================================================================

if (
    fact_inventory_snapshot[
        "Material_ID"
    ].nunique()
    !=
    len(material_ids)
):

    raise ValueError(
        "Not every material has inventory snapshots."
    )


print(
    "✓ ALL MATERIALS HAVE COMPLETE DAILY COVERAGE"
)


# ================================================================================
# 69. DATE COVERAGE
# ================================================================================

if (
    fact_inventory_snapshot[
        "Snapshot_Date"
    ].nunique()
    !=
    len(dates)
):

    raise ValueError(
        "Not every analytical date is represented."
    )


print(
    "✓ ALL ANALYTICAL DATES HAVE COMPLETE COVERAGE"
)


# ================================================================================
# 70. FINAL SUMMARY
# ================================================================================

print()
print("=" * 80)
print("INVENTORY SNAPSHOT SUMMARY")
print("=" * 80)


print(
    f"Snapshot rows              : "
    f"{len(fact_inventory_snapshot):,}"
)


print(
    f"Materials covered          : "
    f"{fact_inventory_snapshot['Material_ID'].nunique():,}"
)


print(
    f"Dates covered              : "
    f"{fact_inventory_snapshot['Snapshot_Date'].nunique():,}"
)


print(
    f"Total gross receipts       : "
    f"{fact_inventory_snapshot['Gross_Receipt_Quantity'].sum():,.0f}"
)


print(
    f"Total rejected receipts    : "
    f"{fact_inventory_snapshot['Rejected_Receipt_Quantity'].sum():,.0f}"
)


print(
    f"Total usable receipts      : "
    f"{fact_inventory_snapshot['Usable_Receipt_Quantity'].sum():,.0f}"
)


print(
    f"Total procurement demand   : "
    f"{fact_inventory_snapshot['Demand_Quantity'].sum():,.0f}"
)


print(
    f"Stockout snapshots         : "
    f"{fact_inventory_snapshot['Stockout_Flag'].sum():,}"
)


print(
    f"Stockout rate              : "
    f"{fact_inventory_snapshot['Stockout_Flag'].mean():.2%}"
)


print(
    f"Safety-stock breaches      : "
    f"{fact_inventory_snapshot['Safety_Stock_Breach_Flag'].sum():,}"
)


print(
    f"Safety-stock breach rate   : "
    f"{fact_inventory_snapshot['Safety_Stock_Breach_Flag'].mean():.2%}"
)


# ================================================================================
# 71. INVENTORY RISK STATE DISTRIBUTION
# ================================================================================

print()
print("-" * 80)
print("INVENTORY RISK STATE DISTRIBUTION")
print("-" * 80)


print(
    fact_inventory_snapshot[
        "Inventory_Risk_State"
    ]
    .value_counts()
)


# ================================================================================
# 72. INVENTORY RISK TIER DISTRIBUTION
# ================================================================================

print()
print("-" * 80)
print("INVENTORY RISK TIER DISTRIBUTION")
print("-" * 80)


print(
    fact_inventory_snapshot[
        "Inventory_Risk_Tier"
    ]
    .value_counts()
)


# ================================================================================
# 73. STOCKOUT BY MATERIAL
# ================================================================================

stockout_by_material = (
    fact_inventory_snapshot
    .groupby(
        "Material_ID"
    )
    .agg(
        Snapshot_Days=(
            "Snapshot_Date",
            "count"
        ),

        Stockout_Days=(
            "Stockout_Flag",
            "sum"
        ),

        Safety_Stock_Breach_Days=(
            "Safety_Stock_Breach_Flag",
            "sum"
        ),

        Mean_On_Hand=(
            "On_Hand_Quantity",
            "mean"
        ),

        Mean_Safety_Stock=(
            "Safety_Stock",
            "mean"
        )
    )
    .reset_index()
)


stockout_by_material[
    "Stockout_Rate"
] = (
    stockout_by_material[
        "Stockout_Days"
    ]
    /
    stockout_by_material[
        "Snapshot_Days"
    ]
)


print()
print("-" * 80)
print("MATERIAL STOCKOUT SUMMARY")
print("-" * 80)


display(
    stockout_by_material
    .sort_values(
        "Stockout_Days",
        ascending=False
    )
    .head(15)
)


# ================================================================================
# 74. FINAL PREVIEW
# ================================================================================

print()
print("=" * 80)
print("FACT_INVENTORYSNAPSHOT PREVIEW")
print("=" * 80)


display(
    fact_inventory_snapshot.head(20)
)


# ================================================================================
# 75. FINAL PASS
# ================================================================================

print()
print("=" * 80)
print("✓ FACT_INVENTORYSNAPSHOT PASSED ALL VALIDATION CHECKS")
print("=" * 80)

print(
    "✓ MATERIAL × DATE GRAIN VALID"
)

print(
    "✓ SAFETY STOCK VALID"
)

print(
    "✓ INVENTORY FLOW VALID"
)

print(
    "✓ RECEIPT LOGIC VALID"
)

print(
    "✓ QUALITY-ADJUSTED RECEIPTS VALID"
)

print(
    "✓ ON-HAND INVENTORY VALID"
)

print(
    "✓ STOCKOUT FLAG LOGIC CONSISTENT"
)

print(
    "✓ SAFETY STOCK BREACH LOGIC CONSISTENT"
)

print(
    "✓ LOW STOCK LOGIC CONSISTENT"
)

print(
    "✓ CRITICAL STOCK LOGIC CONSISTENT"
)

print(
    "✓ INVENTORY COVERAGE LOGIC VALID"
)

print(
    "✓ INVENTORY RISK STATE VALID"
)

print(
    "✓ INVENTORY RISK SCORE VALID"
)

print(
    "✓ NO FUTURE RECEIPTS USED"
)

if quality_events_available:

    print(
        "✓ NO FUTURE QUALITY EVENTS USED"
    )

print(
    "✓ TEMPORAL INVENTORY CONSTRUCTION VALID"
)

print(
    "✓ ALL MATERIALS HAVE DAILY SNAPSHOTS"
)

print(
    "✓ ALL ANALYTICAL DATES COVERED"
)

print("=" * 80)

================================================================================
KEYSTRA — FACT_INVENTORYSNAPSHOT BUILD
================================================================================
✓ Materials detected : 60
✓ Dates detected     : 1,673
✓ PO Lines detected  : 40,000
✓ Quality Events detected : 748

✓ Analytical dates retained : 1,673
✓ Unique materials validated : 60
✓ PO MATERIAL FOREIGN KEYS VALID
✓ Cancelled PO demand excluded : 312
✓ Procurement demand-proxy records built : 31,206
✓ Existing safety stock detected : Safety_Stock_Qty
✓ Valid receipt records : 35,392
✓ Quality-adjusted usable receipts calculated.
✓ Daily receipt records built : 28,369
✓ Inventory grid created : 100,380 rows
✓ Chronological inventory engine completed.
✓ Future receipts cannot affect earlier snapshots.

================================================================================
KEYSTRA — FACT_INVENTORYSNAPSHOT VALIDATION
================================================================================
✓ ROW COUNT VALID : 100,380
✓ MATERIAL × DATE GRAIN UNIQUE
✓ MATERIAL FOREIGN KEYS VALID
✓ DATE FOREIGN KEYS VALID
✓ SNAPSHOT DATES WITHIN ANALYTICAL WINDOW
✓ SAFETY STOCK VALID
✓ ON-HAND INVENTORY NON-NEGATIVE
✓ STOCKOUT FLAG LOGIC CONSISTENT
✓ SAFETY STOCK BREACH FLAG LOGIC CONSISTENT
✓ LOW STOCK FLAG LOGIC CONSISTENT
✓ CRITICAL STOCK FLAG LOGIC CONSISTENT
✓ STOCKOUT ROWS HAVE ZERO ON-HAND INVENTORY
✓ RECEIPT QUANTITY LOGIC VALID
✓ RECEIPT REJECTION RATE VALID
✓ USABLE RECEIPT RATE VALID
✓ INVENTORY COVERAGE LOGIC VALID
✓ INVENTORY RISK STATES VALID
✓ INVENTORY RISK TIERS VALID
✓ INVENTORY RISK SCORE VALID
✓ INVENTORY RISK STATE / FLAG RELATIONSHIPS VALID
✓ NO FUTURE RECEIPTS ENTER INVENTORY MODEL
✓ NO FUTURE QUALITY EVENTS ENTER INVENTORY MODEL
✓ QUALITY EVENTS OCCUR ON/AFTER DELIVERY
✓ ALL MATERIALS HAVE COMPLETE DAILY COVERAGE
✓ ALL ANALYTICAL DATES HAVE COMPLETE COVERAGE

================================================================================
INVENTORY SNAPSHOT SUMMARY
================================================================================
Snapshot rows              : 100,380
Materials covered          : 60
Dates covered              : 1,673
Total gross receipts       : 4,252,719
Total rejected receipts    : 10,797
Total usable receipts      : 4,241,922
Total procurement demand   : 4,886,270
Stockout snapshots         : 11,596
Stockout rate              : 11.55%
Safety-stock breaches      : 13,264
Safety-stock breach rate   : 13.21%

--------------------------------------------------------------------------------
INVENTORY RISK STATE DISTRIBUTION
--------------------------------------------------------------------------------
Inventory_Risk_State
Healthy               87116
Stockout              11596
Critical                867
Below Safety Stock      801
Name: count, dtype: int64

--------------------------------------------------------------------------------
INVENTORY RISK TIER DISTRIBUTION
--------------------------------------------------------------------------------
Inventory_Risk_Tier
Low         87114
Critical    11596
High          868
Medium        802
Name: count, dtype: int64

--------------------------------------------------------------------------------
MATERIAL STOCKOUT SUMMARY
--------------------------------------------------------------------------------

,Material_ID,Snapshot_Days,Stockout_Days,Safety_Stock_Breach_Days,Mean_On_Hand,Mean_Safety_Stock,Stockout_Rate
10,M011,1673,348,398,484.535565,27.0,0.208010
4,M005,1673,341,383,92.905559,10.0,0.203825
27,M028,1673,332,387,435.597729,27.0,0.198446
5,M006,1673,313,401,107.205619,10.0,0.187089
8,M009,1673,289,343,124.735804,10.0,0.172744
1,M002,1673,286,320,83.071130,10.0,0.170950
6,M007,1673,283,371,279.775254,35.0,0.169157
0,M001,1673,282,346,94.612074,10.0,0.168559
29,M030,1673,272,303,416.258219,19.0,0.162582
3,M004,1673,267,278,119.563658,10.0,0.159594
50,M051,1673,254,267,417.623431,10.0,0.151823
18,M019,1673,251,341,856.456665,114.0,0.150030
42,M043,1673,251,295,822.728631,53.0,0.150030
9,M010,1673,249,300,336.083682,18.0,0.148834
23,M024,1673,234,287,1280.065750,84.0,0.139868

================================================================================
FACT_INVENTORYSNAPSHOT PREVIEW
================================================================================

,Date_ID,Snapshot_Date,Material_ID,Safety_Stock,Demand_Quantity,Gross_Receipt_Quantity,Rejected_Receipt_Quantity,Usable_Receipt_Quantity,Inventory_Before_Demand,On_Hand_Quantity,...,Critical_Stock_Flag,Inventory_Coverage_Days,Receipt_Rejection_Rate,Usable_Receipt_Rate,Rolling_30D_Avg_Inventory,Rolling_30D_Avg_Demand,Inventory_Trend,Inventory_Risk_State,Inventory_Risk_Score,Inventory_Risk_Tier
0,20220101,2022-01-01,M001,10,0,0,0,0,15,15,...,0,NaN,0.0,NaN,15.000000,0.000000,0.000000,Healthy,0.0,Low
1,20220102,2022-01-02,M001,10,4,0,0,0,15,11,...,0,2.75,0.0,NaN,13.000000,2.000000,-2.000000,Healthy,0.0,Low
2,20220103,2022-01-03,M001,10,0,0,0,0,11,11,...,0,NaN,0.0,NaN,12.333333,1.333333,-1.333333,Healthy,0.0,Low
3,20220104,2022-01-04,M001,10,0,0,0,0,11,11,...,0,NaN,0.0,NaN,12.000000,1.000000,-1.000000,Healthy,0.0,Low
4,20220105,2022-01-05,M001,10,0,0,0,0,11,11,...,0,NaN,0.0,NaN,11.800000,0.800000,-0.800000,Healthy,0.0,Low
5,20220106,2022-01-06,M001,10,0,0,0,0,11,11,...,0,NaN,0.0,NaN,11.666667,0.666667,-0.666667,Healthy,0.0,Low
6,20220107,2022-01-07,M001,10,0,0,0,0,11,11,...,0,NaN,0.0,NaN,11.571429,0.571429,-0.571429,Healthy,0.0,Low
7,20220108,2022-01-08,M001,10,46,0,0,0,11,0,...,1,0.00,0.0,NaN,10.125000,6.250000,-10.125000,Stockout,100.0,Critical
8,20220109,2022-01-09,M001,10,15,0,0,0,0,0,...,1,0.00,0.0,NaN,9.000000,7.222222,-9.000000,Stockout,100.0,Critical
9,20220110,2022-01-10,M001,10,0,0,0,0,0,0,...,1,NaN,0.0,NaN,8.100000,6.500000,-8.100000,Stockout,100.0,Critical
10,20220111,2022-01-11,M001,10,16,0,0,0,0,0,...,1,0.00,0.0,NaN,7.363636,7.363636,-7.363636,Stockout,100.0,Critical
11,20220112,2022-01-12,M001,10,0,0,0,0,0,0,...,1,NaN,0.0,NaN,6.750000,6.750000,-6.750000,Stockout,100.0,Critical
12,20220113,2022-01-13,M001,10,0,0,0,0,0,0,...,1,NaN,0.0,NaN,6.230769,6.230769,-6.230769,Stockout,100.0,Critical
13,20220114,2022-01-14,M001,10,0,0,0,0,0,0,...,1,NaN,0.0,NaN,5.785714,5.785714,-5.785714,Stockout,100.0,Critical
14,20220115,2022-01-15,M001,10,0,0,0,0,0,0,...,1,NaN,0.0,NaN,5.400000,5.400000,-5.400000,Stockout,100.0,Critical
15,20220116,2022-01-16,M001,10,0,0,0,0,0,0,...,1,NaN,0.0,NaN,5.062500,5.062500,-5.062500,Stockout,100.0,Critical
16,20220117,2022-01-17,M001,10,0,0,0,0,0,0,...,1,NaN,0.0,NaN,4.764706,4.764706,-4.764706,Stockout,100.0,Critical
17,20220118,2022-01-18,M001,10,0,0,0,0,0,0,...,1,NaN,0.0,NaN,4.500000,4.500000,-4.500000,Stockout,100.0,Critical
18,20220119,2022-01-19,M001,10,0,0,0,0,0,0,...,1,NaN,0.0,NaN,4.263158,4.263158,-4.263158,Stockout,100.0,Critical
19,20220120,2022-01-20,M001,10,0,0,0,0,0,0,...,1,NaN,0.0,NaN,4.050000,4.050000,-4.050000,Stockout,100.0,Critical

================================================================================
✓ FACT_INVENTORYSNAPSHOT PASSED ALL VALIDATION CHECKS
================================================================================
✓ MATERIAL × DATE GRAIN VALID
✓ SAFETY STOCK VALID
✓ INVENTORY FLOW VALID
✓ RECEIPT LOGIC VALID
✓ QUALITY-ADJUSTED RECEIPTS VALID
✓ ON-HAND INVENTORY VALID
✓ STOCKOUT FLAG LOGIC CONSISTENT
✓ SAFETY STOCK BREACH LOGIC CONSISTENT
✓ LOW STOCK LOGIC CONSISTENT
✓ CRITICAL STOCK LOGIC CONSISTENT
✓ INVENTORY COVERAGE LOGIC VALID
✓ INVENTORY RISK STATE VALID
✓ INVENTORY RISK SCORE VALID
✓ NO FUTURE RECEIPTS USED
✓ NO FUTURE QUALITY EVENTS USED
✓ TEMPORAL INVENTORY CONSTRUCTION VALID
✓ ALL MATERIALS HAVE DAILY SNAPSHOTS
✓ ALL ANALYTICAL DATES COVERED
================================================================================

In [11]:
# ================================================================================
# KEYSTRA — FACT_SUPPLIERRISKLABEL
# PHASE 1: SUPPLIER HISTORICAL RISK SIGNAL FOUNDATION
# ================================================================================
#
# PURPOSE
# -------
# Build the historical supplier behavioural signals that will later be used
# to construct the FUTURE supplier-failure label.
#
# IMPORTANT:
#   This phase DOES NOT create Supplier_Failure_Label.
#
#   It creates only information that was observable at each observation date.
#
# ANALYTICAL OBJECTIVE
# --------------------
# Supplier historical behaviour
#          ↓
# Delivery reliability
# Fulfilment behaviour
# Overdue exposure
# Outstanding exposure
# Cancellation behaviour
#          ↓
# Phase 2: Future supplier failure outcome
#
# TEMPORAL PRINCIPLE
# ------------------
# For a supplier on date T:
#
#   ONLY PO activity occurring on or before T
#   may influence the historical signals.
#
# Future PO activity must NOT enter the historical state.
#
# ================================================================================

import pandas as pd
import numpy as np


# ================================================================================
# 1. CONFIGURATION
# ================================================================================

RANDOM_SEED = 20260825

START_DATE = pd.Timestamp("2022-01-01")
REFERENCE_DATE = pd.Timestamp("2026-07-31")

OBSERVATION_LOOKBACK_DAYS = 90

print("=" * 80)
print("KEYSTRA — FACT_SUPPLIERRISKLABEL")
print("PHASE 1 — SUPPLIER HISTORICAL RISK SIGNAL FOUNDATION")
print("=" * 80)


# ================================================================================
# 2. REQUIRED OBJECT VALIDATION
# ================================================================================

required_objects = {
    "dim_supplier": dim_supplier,
    "dim_date": dim_date,
    "fact_purchase_order_line": fact_purchase_order_line
}

for name, obj in required_objects.items():

    if obj is None:

        raise ValueError(
            f"{name} is None."
        )

    if not isinstance(obj, pd.DataFrame):

        raise TypeError(
            f"{name} must be a pandas DataFrame."
        )

    if len(obj) == 0:

        raise ValueError(
            f"{name} is empty."
        )


print()
print(f"✓ Suppliers detected : {len(dim_supplier):,}")
print(f"✓ Dates detected     : {len(dim_date):,}")
print(f"✓ PO Lines detected  : {len(fact_purchase_order_line):,}")


# ================================================================================
# 3. COPY INPUTS
# ================================================================================

suppliers = dim_supplier.copy()
dates = dim_date.copy()
po = fact_purchase_order_line.copy()


# ================================================================================
# 4. SUPPLIER KEY VALIDATION
# ================================================================================

if "Supplier_ID" not in suppliers.columns:

    raise ValueError(
        "Dim_Supplier must contain Supplier_ID."
    )

if "Supplier_ID" not in po.columns:

    raise ValueError(
        "Fact_PurchaseOrderLine must contain Supplier_ID."
    )


suppliers = (
    suppliers
    .drop_duplicates(
        "Supplier_ID"
    )
    .copy()
)

supplier_ids = (
    suppliers[
        "Supplier_ID"
    ]
    .dropna()
    .unique()
)


# ================================================================================
# 5. PO COLUMN VALIDATION
# ================================================================================

required_po_columns = [
    "PO_Line_ID",
    "Supplier_ID",
    "Material_ID",
    "Quantity_Ordered",
    "Quantity_Received",
    "Order_Date",
    "Expected_Delivery_Date",
    "Actual_Delivery_Date"
]

missing_columns = [
    col
    for col in required_po_columns
    if col not in po.columns
]

if missing_columns:

    raise ValueError(
        "Fact_PurchaseOrderLine is missing required columns: "
        f"{missing_columns}"
    )


# ================================================================================
# 6. STANDARDISE PO DATES
# ================================================================================

for col in [
    "Order_Date",
    "Expected_Delivery_Date",
    "Actual_Delivery_Date"
]:

    po[col] = pd.to_datetime(
        po[col],
        errors="coerce"
    )


# ================================================================================
# 7. STANDARDISE QUANTITIES
# ================================================================================

for col in [
    "Quantity_Ordered",
    "Quantity_Received"
]:

    po[col] = pd.to_numeric(
        po[col],
        errors="coerce"
    ).fillna(0)


po[
    "Quantity_Ordered"
] = (
    po[
        "Quantity_Ordered"
    ]
    .clip(lower=0)
)


po[
    "Quantity_Received"
] = (
    po[
        "Quantity_Received"
    ]
    .clip(lower=0)
)


# ================================================================================
# 8. VALIDATE SUPPLIER FOREIGN KEYS
# ================================================================================

invalid_suppliers = (
    set(
        po[
            "Supplier_ID"
        ]
        .dropna()
        .unique()
    )
    -
    set(supplier_ids)
)

if invalid_suppliers:

    raise ValueError(
        "PO lines contain Supplier_ID values not found in Dim_Supplier: "
        f"{list(invalid_suppliers)[:10]}"
    )


print(
    f"✓ PO SUPPLIER FOREIGN KEYS VALID"
)


# ================================================================================
# 9. STANDARDISE DATE DIMENSION
# ================================================================================

date_candidates = [
    "Date",
    "Calendar_Date",
    "Full_Date",
    "Date_Value"
]

date_column = None

for col in date_candidates:

    if col in dates.columns:

        date_column = col
        break


if date_column is None:

    raise ValueError(
        "Dim_Date does not contain a recognised date column."
    )


dates[
    date_column
] = pd.to_datetime(
    dates[
        date_column
    ],
    errors="coerce"
)


if dates[
    date_column
].isna().any():

    raise ValueError(
        "Dim_Date contains invalid dates."
    )


dates = (
    dates[
        (
            dates[date_column] >= START_DATE
        )
        &
        (
            dates[date_column] <= REFERENCE_DATE
        )
    ]
    .sort_values(date_column)
    .reset_index(drop=True)
)


print(
    f"✓ Analytical dates retained : {len(dates):,}"
)


# ================================================================================
# 10. EXCLUDE CANCELLED PO LINES
# ================================================================================
#
# Cancelled procurement should not be treated as fulfilled demand.
#
# We therefore exclude cancelled lines from the operational quantity
# calculations while preserving cancellation information separately.
#
# ================================================================================

cancelled_mask = pd.Series(
    False,
    index=po.index
)


if "Purchase_Order_Status" in po.columns:

    status = (
        po[
            "Purchase_Order_Status"
        ]
        .astype(str)
        .str.strip()
        .str.lower()
    )

    cancelled_mask = (
        status.str.contains(
            "cancel",
            na=False
        )
    )


elif "PO_Status" in po.columns:

    status = (
        po[
            "PO_Status"
        ]
        .astype(str)
        .str.strip()
        .str.lower()
    )

    cancelled_mask = (
        status.str.contains(
            "cancel",
            na=False
        )
    )


po[
    "Is_Cancelled"
] = cancelled_mask.astype(int)


print(
    f"✓ Cancelled PO lines identified : "
    f"{po['Is_Cancelled'].sum():,}"
)


# ================================================================================
# 11. BUILD OPERATIONAL PO BASE
# ================================================================================
#
# Only PO lines that were actually placed can contribute to historical
# supplier behaviour.
#
# ================================================================================

operational_po = po[
    (
        po["Order_Date"].notna()
    )
    &
    (
        po["Order_Date"] >= START_DATE
    )
    &
    (
        po["Order_Date"] <= REFERENCE_DATE
    )
    &
    (
        po["Is_Cancelled"] == 0
    )
].copy()


print(
    f"✓ Operational PO lines retained : "
    f"{len(operational_po):,}"
)


# ================================================================================
# 12. CREATE PO-LEVEL OPERATIONAL SIGNALS
# ================================================================================
#
# These are facts that can be derived from the PO itself.
#
# ================================================================================

operational_po[
    "Outstanding_Quantity"
] = (
    operational_po[
        "Quantity_Ordered"
    ]
    -
    operational_po[
        "Quantity_Received"
    ]
).clip(lower=0)


operational_po[
    "Fulfilled_Flag"
] = (
    operational_po[
        "Quantity_Received"
    ]
    >=
    operational_po[
        "Quantity_Ordered"
    ]
).astype(int)


operational_po[
    "Partially_Fulfilled_Flag"
] = (
    (
        operational_po[
            "Quantity_Received"
        ] > 0
    )
    &
    (
        operational_po[
            "Quantity_Received"
        ]
        <
        operational_po[
            "Quantity_Ordered"
        ]
    )
).astype(int)


operational_po[
    "Outstanding_Flag"
] = (
    operational_po[
        "Outstanding_Quantity"
    ] > 0
).astype(int)


# ================================================================================
# 13. DELIVERY DELAY
# ================================================================================
#
# Delay is only calculated when an actual delivery date exists.
#
# Positive value = delivered late.
# Zero/negative = on time or early.
#
# ================================================================================

operational_po[
    "Delivery_Delay_Days"
] = (
    operational_po[
        "Actual_Delivery_Date"
    ]
    -
    operational_po[
        "Expected_Delivery_Date"
    ]
).dt.days


operational_po[
    "Delivery_Delay_Days"
] = (
    operational_po[
        "Delivery_Delay_Days"
    ]
    .fillna(0)
)


operational_po[
    "Late_Delivery_Flag"
] = (
    operational_po[
        "Delivery_Delay_Days"
    ] > 0
).astype(int)


# ================================================================================
# 14. OVERDUE OUTSTANDING PO
# ================================================================================
#
# This is evaluated relative to the observation date later.
#
# For now we preserve:
#
#   Expected delivery date
#   Outstanding quantity
#
# so the historical state can be calculated without leakage.
#
# ================================================================================

print(
    "✓ PO-level supplier operational signals constructed."
)


# ================================================================================
# 15. BUILD SUPPLIER × DATE GRID
# ================================================================================
#
# One row represents:
#
#   Supplier_ID + Observation_Date
#
# This becomes the temporal backbone of the supplier risk label table.
#
# ================================================================================

supplier_date_grid = (
    pd.MultiIndex
    .from_product(
        [
            supplier_ids,
            dates[date_column]
        ],
        names=[
            "Supplier_ID",
            "Observation_Date"
        ]
    )
    .to_frame(index=False)
)


print()
print(
    f"✓ Supplier × Date grid created : "
    f"{len(supplier_date_grid):,} rows"
)


# ================================================================================
# 16. DAILY SUPPLIER PROCUREMENT ACTIVITY
# ================================================================================
#
# These signals represent activity occurring ON the observation date.
#
# ================================================================================

daily_supplier_activity = (
    operational_po
    .groupby(
        [
            "Order_Date",
            "Supplier_ID"
        ],
        as_index=False
    )
    .agg(
        PO_Count=(
            "PO_Line_ID",
            "nunique"
        ),
        Ordered_Quantity=(
            "Quantity_Ordered",
            "sum"
        ),
        Received_Quantity=(
            "Quantity_Received",
            "sum"
        ),
        Outstanding_Quantity=(
            "Outstanding_Quantity",
            "sum"
        ),
        Fulfilled_PO_Count=(
            "Fulfilled_Flag",
            "sum"
        ),
        Partial_Fulfilment_Count=(
            "Partially_Fulfilled_Flag",
            "sum"
        ),
        Outstanding_PO_Count=(
            "Outstanding_Flag",
            "sum"
        )
    )
    .rename(
        columns={
            "Order_Date": "Activity_Date"
        }
    )
)


# ================================================================================
# 17. MERGE DAILY ACTIVITY
# ================================================================================

supplier_date_grid = supplier_date_grid.merge(
    daily_supplier_activity,
    left_on=[
        "Observation_Date",
        "Supplier_ID"
    ],
    right_on=[
        "Activity_Date",
        "Supplier_ID"
    ],
    how="left"
)


supplier_date_grid.drop(
    columns=[
        "Activity_Date"
    ],
    inplace=True
)


for col in [
    "PO_Count",
    "Ordered_Quantity",
    "Received_Quantity",
    "Outstanding_Quantity",
    "Fulfilled_PO_Count",
    "Partial_Fulfilment_Count",
    "Outstanding_PO_Count"
]:

    supplier_date_grid[
        col
    ] = (
        supplier_date_grid[
            col
        ]
        .fillna(0)
    )


# ================================================================================
# 18. DAILY DELIVERY PERFORMANCE
# ================================================================================
#
# Delivery performance is based only on deliveries that actually occurred
# on the observation date.
#
# ================================================================================

delivery_activity = operational_po[
    operational_po[
        "Actual_Delivery_Date"
    ].notna()
].copy()


daily_delivery = (
    delivery_activity
    .groupby(
        [
            "Actual_Delivery_Date",
            "Supplier_ID"
        ],
        as_index=False
    )
    .agg(
        Delivered_PO_Count=(
            "PO_Line_ID",
            "nunique"
        ),
        Late_Delivery_Count=(
            "Late_Delivery_Flag",
            "sum"
        ),
        Total_Delivery_Delay_Days=(
            "Delivery_Delay_Days",
            "sum"
        ),
        Average_Delivery_Delay_Days=(
            "Delivery_Delay_Days",
            "mean"
        )
    )
    .rename(
        columns={
            "Actual_Delivery_Date": "Delivery_Date"
        }
    )
)


supplier_date_grid = supplier_date_grid.merge(
    daily_delivery,
    left_on=[
        "Observation_Date",
        "Supplier_ID"
    ],
    right_on=[
        "Delivery_Date",
        "Supplier_ID"
    ],
    how="left"
)


supplier_date_grid.drop(
    columns=[
        "Delivery_Date"
    ],
    inplace=True
)


for col in [
    "Delivered_PO_Count",
    "Late_Delivery_Count",
    "Total_Delivery_Delay_Days",
    "Average_Delivery_Delay_Days"
]:

    supplier_date_grid[
        col
    ] = (
        supplier_date_grid[
            col
        ]
        .fillna(0)
    )


# ================================================================================
# 19. CUMULATIVE HISTORICAL SUPPLIER SIGNALS
# ================================================================================
#
# These are calculated cumulatively.
#
# At observation date T:
#
#   only activity on/before T contributes.
#
# Therefore these signals cannot use future activity.
#
# ================================================================================

supplier_date_grid = (
    supplier_date_grid
    .sort_values(
        [
            "Supplier_ID",
            "Observation_Date"
        ]
    )
    .reset_index(drop=True)
)


grouped = supplier_date_grid.groupby(
    "Supplier_ID"
)


supplier_date_grid[
    "Cumulative_PO_Count"
] = grouped[
    "PO_Count"
].cumsum()


supplier_date_grid[
    "Cumulative_Ordered_Quantity"
] = grouped[
    "Ordered_Quantity"
].cumsum()


supplier_date_grid[
    "Cumulative_Received_Quantity"
] = grouped[
    "Received_Quantity"
].cumsum()


supplier_date_grid[
    "Cumulative_Outstanding_Quantity"
] = grouped[
    "Outstanding_Quantity"
].cumsum()


supplier_date_grid[
    "Cumulative_Fulfilled_PO_Count"
] = grouped[
    "Fulfilled_PO_Count"
].cumsum()


supplier_date_grid[
    "Cumulative_Partial_Fulfilment_Count"
] = grouped[
    "Partial_Fulfilment_Count"
].cumsum()


supplier_date_grid[
    "Cumulative_Late_Delivery_Count"
] = grouped[
    "Late_Delivery_Count"
].cumsum()


# ================================================================================
# 20. CUMULATIVE SUPPLIER PERFORMANCE RATES
# ================================================================================

supplier_date_grid[
    "Historical_Fulfilment_Rate"
] = np.where(
    supplier_date_grid[
        "Cumulative_PO_Count"
    ] > 0,

    supplier_date_grid[
        "Cumulative_Fulfilled_PO_Count"
    ]
    /
    supplier_date_grid[
        "Cumulative_PO_Count"
    ],

    np.nan
)


supplier_date_grid[
    "Historical_Partial_Fulfilment_Rate"
] = np.where(
    supplier_date_grid[
        "Cumulative_PO_Count"
    ] > 0,

    supplier_date_grid[
        "Cumulative_Partial_Fulfilment_Count"
    ]
    /
    supplier_date_grid[
        "Cumulative_PO_Count"
    ],

    np.nan
)


# ================================================================================
# 21. RECENT 90-DAY SUPPLIER BEHAVIOUR
# ================================================================================
#
# This is more useful for predictive modelling than cumulative lifetime
# behaviour because supplier reliability can deteriorate over time.
#
# IMPORTANT:
# The rolling window includes ONLY activity up to the observation date.
#
# ================================================================================

rolling_columns = [
    "PO_Count",
    "Ordered_Quantity",
    "Received_Quantity",
    "Outstanding_Quantity",
    "Fulfilled_PO_Count",
    "Partial_Fulfilment_Count",
    "Outstanding_PO_Count",
    "Delivered_PO_Count",
    "Late_Delivery_Count",
    "Total_Delivery_Delay_Days"
]


for col in rolling_columns:

    supplier_date_grid[
        f"Rolling_90D_{col}"
    ] = (
        supplier_date_grid
        .groupby("Supplier_ID")[col]
        .transform(
            lambda x:
            x.rolling(
                OBSERVATION_LOOKBACK_DAYS,
                min_periods=1
            ).sum()
        )
    )


# ================================================================================
# 22. RECENT SUPPLIER FULFILMENT RATE
# ================================================================================

supplier_date_grid[
    "Recent_90D_Fulfilment_Rate"
] = np.where(
    supplier_date_grid[
        "Rolling_90D_PO_Count"
    ] > 0,

    supplier_date_grid[
        "Rolling_90D_Fulfilled_PO_Count"
    ]
    /
    supplier_date_grid[
        "Rolling_90D_PO_Count"
    ],

    np.nan
)


# ================================================================================
# 23. RECENT PARTIAL FULFILMENT RATE
# ================================================================================

supplier_date_grid[
    "Recent_90D_Partial_Fulfilment_Rate"
] = np.where(
    supplier_date_grid[
        "Rolling_90D_PO_Count"
    ] > 0,

    supplier_date_grid[
        "Rolling_90D_Partial_Fulfilment_Count"
    ]
    /
    supplier_date_grid[
        "Rolling_90D_PO_Count"
    ],

    np.nan
)


# ================================================================================
# 24. RECENT LATE DELIVERY RATE
# ================================================================================

supplier_date_grid[
    "Recent_90D_Late_Delivery_Rate"
] = np.where(
    supplier_date_grid[
        "Rolling_90D_Delivered_PO_Count"
    ] > 0,

    supplier_date_grid[
        "Rolling_90D_Late_Delivery_Count"
    ]
    /
    supplier_date_grid[
        "Rolling_90D_Delivered_PO_Count"
    ],

    np.nan
)


# ================================================================================
# 25. RECENT OUTSTANDING EXPOSURE RATE
# ================================================================================

supplier_date_grid[
    "Recent_90D_Outstanding_Rate"
] = np.where(
    supplier_date_grid[
        "Rolling_90D_PO_Count"
    ] > 0,

    supplier_date_grid[
        "Rolling_90D_Outstanding_PO_Count"
    ]
    /
    supplier_date_grid[
        "Rolling_90D_PO_Count"
    ],

    np.nan
)


# ================================================================================
# 26. DELIVERY DELAY SIGNAL
# ================================================================================

supplier_date_grid[
    "Recent_90D_Average_Delivery_Delay"
] = np.where(
    supplier_date_grid[
        "Rolling_90D_Delivered_PO_Count"
    ] > 0,

    supplier_date_grid[
        "Rolling_90D_Total_Delivery_Delay_Days"
    ]
    /
    supplier_date_grid[
        "Rolling_90D_Delivered_PO_Count"
    ],

    0
)


# ================================================================================
# 27. CURRENT OUTSTANDING EXPOSURE
# ================================================================================
#
# IMPORTANT:
# This is NOT cumulative outstanding quantity.
#
# It represents currently outstanding PO quantities as of the observation
# date.
#
# We calculate this separately because cumulative outstanding quantity would
# incorrectly keep old fulfilled quantities forever.
#
# ================================================================================

po_events = operational_po[
    [
        "Supplier_ID",
        "Order_Date",
        "Actual_Delivery_Date",
        "Quantity_Ordered",
        "Quantity_Received"
    ]
].copy()


# Daily ordered quantities.
daily_ordered = (
    operational_po
    .groupby(
        [
            "Order_Date",
            "Supplier_ID"
        ],
        as_index=False
    )[
        "Quantity_Ordered"
    ]
    .sum()
    .rename(
        columns={
            "Order_Date": "Observation_Date",
            "Quantity_Ordered": "Daily_Ordered"
        }
    )
)


# Daily received quantities.
daily_received = (
    operational_po
    .groupby(
        [
            "Actual_Delivery_Date",
            "Supplier_ID"
        ],
        as_index=False
    )[
        "Quantity_Received"
    ]
    .sum()
    .rename(
        columns={
            "Actual_Delivery_Date": "Observation_Date",
            "Quantity_Received": "Daily_Received"
        }
    )
)


supplier_date_grid = supplier_date_grid.merge(
    daily_ordered,
    on=[
        "Observation_Date",
        "Supplier_ID"
    ],
    how="left"
)


supplier_date_grid = supplier_date_grid.merge(
    daily_received,
    on=[
        "Observation_Date",
        "Supplier_ID"
    ],
    how="left"
)


supplier_date_grid[
    "Daily_Ordered"
] = (
    supplier_date_grid[
        "Daily_Ordered"
    ]
    .fillna(0)
)


supplier_date_grid[
    "Daily_Received"
] = (
    supplier_date_grid[
        "Daily_Received"
    ]
    .fillna(0)
)


# ================================================================================
# 28. CURRENT NET PROCUREMENT POSITION
# ================================================================================
#
# This is a directional exposure signal:
#
# cumulative ordered
#        -
# cumulative received
#
# ================================================================================

supplier_date_grid[
    "Current_Outstanding_Quantity"
] = (
    supplier_date_grid[
        "Cumulative_Ordered_Quantity"
    ]
    -
    supplier_date_grid[
        "Cumulative_Received_Quantity"
    ]
).clip(lower=0)


# ================================================================================
# 29. SUPPLIER RISK SIGNALS
# ================================================================================
#
# These are descriptive signals.
#
# They are NOT the final risk score.
# They are NOT the future failure label.
#
# ================================================================================

supplier_date_grid[
    "Fulfilment_Risk_Signal"
] = (
    1
    -
    supplier_date_grid[
        "Recent_90D_Fulfilment_Rate"
    ]
    .fillna(1)
).clip(0, 1)


supplier_date_grid[
    "Late_Delivery_Risk_Signal"
] = (
    supplier_date_grid[
        "Recent_90D_Late_Delivery_Rate"
    ]
    .fillna(0)
    .clip(0, 1)
)


supplier_date_grid[
    "Partial_Fulfilment_Risk_Signal"
] = (
    supplier_date_grid[
        "Recent_90D_Partial_Fulfilment_Rate"
    ]
    .fillna(0)
    .clip(0, 1)
)


supplier_date_grid[
    "Outstanding_Risk_Signal"
] = (
    supplier_date_grid[
        "Recent_90D_Outstanding_Rate"
    ]
    .fillna(0)
    .clip(0, 1)
)


# ================================================================================
# 30. SUPPLIER BEHAVIOUR STATE
# ================================================================================

supplier_date_grid[
    "Supplier_Behaviour_State"
] = np.select(
    [
        (
            supplier_date_grid[
                "Recent_90D_Fulfilment_Rate"
            ]
            < 0.50
        ),

        (
            supplier_date_grid[
                "Recent_90D_Fulfilment_Rate"
            ]
            < 0.75
        ),

        (
            supplier_date_grid[
                "Recent_90D_Late_Delivery_Rate"
            ]
            >= 0.50
        )
    ],

    [
        "Severely Unreliable",
        "Deteriorating",
        "Delivery Unreliable"
    ],

    default="Stable"
)


# ================================================================================
# 31. FINAL PHASE 1 TABLE
# ================================================================================

fact_supplier_risk_phase1 = supplier_date_grid[
    [
        "Supplier_ID",
        "Observation_Date",

        "PO_Count",
        "Ordered_Quantity",
        "Received_Quantity",
        "Outstanding_Quantity",

        "Fulfilled_PO_Count",
        "Partial_Fulfilment_Count",
        "Outstanding_PO_Count",

        "Delivered_PO_Count",
        "Late_Delivery_Count",

        "Historical_Fulfilment_Rate",
        "Historical_Partial_Fulfilment_Rate",

        "Rolling_90D_PO_Count",
        "Rolling_90D_Ordered_Quantity",
        "Rolling_90D_Received_Quantity",
        "Rolling_90D_Outstanding_Quantity",

        "Rolling_90D_Fulfilled_PO_Count",
        "Rolling_90D_Partial_Fulfilment_Count",

        "Rolling_90D_Delivered_PO_Count",
        "Rolling_90D_Late_Delivery_Count",

        "Recent_90D_Fulfilment_Rate",
        "Recent_90D_Partial_Fulfilment_Rate",
        "Recent_90D_Late_Delivery_Rate",
        "Recent_90D_Outstanding_Rate",

        "Recent_90D_Average_Delivery_Delay",

        "Current_Outstanding_Quantity",

        "Fulfilment_Risk_Signal",
        "Late_Delivery_Risk_Signal",
        "Partial_Fulfilment_Risk_Signal",
        "Outstanding_Risk_Signal",

        "Supplier_Behaviour_State"
    ]
].copy()


# ================================================================================
# 32. PHASE 1 VALIDATION
# ================================================================================

print()
print("=" * 80)
print("PHASE 1 — SUPPLIER HISTORICAL SIGNAL VALIDATION")
print("=" * 80)


# Expected grain.
expected_rows = (
    len(supplier_ids)
    *
    len(dates)
)


if len(fact_supplier_risk_phase1) != expected_rows:

    raise ValueError(
        "Supplier × Date row count mismatch. "
        f"Expected {expected_rows:,}, "
        f"received {len(fact_supplier_risk_phase1):,}."
    )


print(
    f"✓ SUPPLIER × DATE ROW COUNT VALID : "
    f"{len(fact_supplier_risk_phase1):,}"
)


# Grain uniqueness.
if fact_supplier_risk_phase1[
    [
        "Supplier_ID",
        "Observation_Date"
    ]
].duplicated().any():

    raise ValueError(
        "Duplicate Supplier_ID + Observation_Date combinations detected."
    )


print(
    "✓ SUPPLIER × DATE GRAIN UNIQUE"
)


# Supplier FK.
if not set(
    fact_supplier_risk_phase1[
        "Supplier_ID"
    ]
).issubset(
    set(supplier_ids)
):

    raise ValueError(
        "Invalid Supplier_ID detected."
    )


print(
    "✓ SUPPLIER FOREIGN KEYS VALID"
)


# Date range.
if (
    fact_supplier_risk_phase1[
        "Observation_Date"
    ]
    < START_DATE
).any():

    raise ValueError(
        "Observation dates exist before analytical start."
    )


if (
    fact_supplier_risk_phase1[
        "Observation_Date"
    ]
    > REFERENCE_DATE
).any():

    raise ValueError(
        "Observation dates exist after reference date."
    )


print(
    "✓ OBSERVATION DATES WITHIN ANALYTICAL WINDOW"
)


# No negative quantities.
quantity_columns = [
    "Ordered_Quantity",
    "Received_Quantity",
    "Outstanding_Quantity",
    "Rolling_90D_Ordered_Quantity",
    "Rolling_90D_Received_Quantity",
    "Rolling_90D_Outstanding_Quantity",
    "Current_Outstanding_Quantity"
]


for col in quantity_columns:

    if (
        fact_supplier_risk_phase1[col] < 0
    ).any():

        raise ValueError(
            f"Negative values detected in {col}."
        )


print(
    "✓ QUANTITY SIGNALS NON-NEGATIVE"
)


# Fulfilment rate.
for col in [
    "Historical_Fulfilment_Rate",
    "Historical_Partial_Fulfilment_Rate",
    "Recent_90D_Fulfilment_Rate",
    "Recent_90D_Partial_Fulfilment_Rate",
    "Recent_90D_Late_Delivery_Rate"
]:

    valid_values = (
        fact_supplier_risk_phase1[col]
        .dropna()
    )

    if (
        (valid_values < 0)
        |
        (valid_values > 1)
    ).any():

        raise ValueError(
            f"{col} contains values outside 0–1."
        )


print(
    "✓ SUPPLIER PERFORMANCE RATES VALID"
)


# Risk signals.
for col in [
    "Fulfilment_Risk_Signal",
    "Late_Delivery_Risk_Signal",
    "Partial_Fulfilment_Risk_Signal",
    "Outstanding_Risk_Signal"
]:

    if (
        fact_supplier_risk_phase1[col] < 0
    ).any() or (
        fact_supplier_risk_phase1[col] > 1
    ).any():

        raise ValueError(
            f"{col} outside valid 0–1 range."
        )


print(
    "✓ SUPPLIER RISK SIGNALS VALID"
)


# ================================================================================
# 33. PHASE 1 SUMMARY
# ================================================================================

print()
print("=" * 80)
print("PHASE 1 — SUMMARY")
print("=" * 80)

print(
    f"Supplier/date rows       : "
    f"{len(fact_supplier_risk_phase1):,}"
)

print(
    f"Suppliers covered        : "
    f"{fact_supplier_risk_phase1['Supplier_ID'].nunique():,}"
)

print(
    f"Observation dates        : "
    f"{fact_supplier_risk_phase1['Observation_Date'].nunique():,}"
)

print(
    f"Total PO activity        : "
    f"{fact_supplier_risk_phase1['PO_Count'].sum():,.0f}"
)

print(
    f"Total ordered quantity   : "
    f"{fact_supplier_risk_phase1['Ordered_Quantity'].sum():,.0f}"
)

print(
    f"Total received quantity  : "
    f"{fact_supplier_risk_phase1['Received_Quantity'].sum():,.0f}"
)

print(
    f"Total outstanding qty    : "
    f"{fact_supplier_risk_phase1['Outstanding_Quantity'].sum():,.0f}"
)


print()
print("-" * 80)
print("SUPPLIER BEHAVIOUR STATE")
print("-" * 80)

print(
    fact_supplier_risk_phase1[
        "Supplier_Behaviour_State"
    ]
    .value_counts()
)


# ================================================================================
# 34. FINAL PREVIEW
# ================================================================================

print()
print("=" * 80)
print("PHASE 1 PREVIEW")
print("=" * 80)

display(
    fact_supplier_risk_phase1.head(20)
)


print()
print("=" * 80)
print("✓ PHASE 1 COMPLETED SUCCESSFULLY")
print("=" * 80)

print(
    "✓ HISTORICAL SUPPLIER BEHAVIOUR BUILT"
)

print(
    "✓ RECENT 90-DAY SUPPLIER SIGNALS BUILT"
)

print(
    "✓ DELIVERY RELIABILITY SIGNALS BUILT"
)

print(
    "✓ FULFILMENT SIGNALS BUILT"
)

print(
    "✓ OUTSTANDING EXPOSURE SIGNALS BUILT"
)

print(
    "✓ SUPPLIER BEHAVIOUR STATES BUILT"
)

print(
    "✓ NO FUTURE OUTCOME LABEL CREATED YET"
)

print(
    "✓ READY FOR PHASE 2 — FUTURE SUPPLIER FAILURE OUTCOME"
)

print("=" * 80)

================================================================================
KEYSTRA — FACT_SUPPLIERRISKLABEL
PHASE 1 — SUPPLIER HISTORICAL RISK SIGNAL FOUNDATION
================================================================================

✓ Suppliers detected : 90
✓ Dates detected     : 1,673
✓ PO Lines detected  : 40,000
✓ PO SUPPLIER FOREIGN KEYS VALID
✓ Analytical dates retained : 1,673
✓ Cancelled PO lines identified : 312
✓ Operational PO lines retained : 39,688
✓ PO-level supplier operational signals constructed.

✓ Supplier × Date grid created : 150,570 rows

================================================================================
PHASE 1 — SUPPLIER HISTORICAL SIGNAL VALIDATION
================================================================================
✓ SUPPLIER × DATE ROW COUNT VALID : 150,570
✓ SUPPLIER × DATE GRAIN UNIQUE
✓ SUPPLIER FOREIGN KEYS VALID
✓ OBSERVATION DATES WITHIN ANALYTICAL WINDOW
✓ QUANTITY SIGNALS NON-NEGATIVE
✓ SUPPLIER PERFORMANCE RATES VALID
✓ SUPPLIER RISK SIGNALS VALID

================================================================================
PHASE 1 — SUMMARY
================================================================================
Supplier/date rows       : 150,570
Suppliers covered        : 90
Observation dates        : 1,673
Total PO activity        : 39,688
Total ordered quantity   : 4,886,270
Total received quantity  : 4,301,679
Total outstanding qty    : 584,591

--------------------------------------------------------------------------------
SUPPLIER BEHAVIOUR STATE
--------------------------------------------------------------------------------
Supplier_Behaviour_State
Stable                 114344
Deteriorating           29038
Severely Unreliable      6692
Delivery Unreliable       496
Name: count, dtype: int64

================================================================================
PHASE 1 PREVIEW
================================================================================

,Supplier_ID,Observation_Date,PO_Count,Ordered_Quantity,Received_Quantity,Outstanding_Quantity,Fulfilled_PO_Count,Partial_Fulfilment_Count,Outstanding_PO_Count,Delivered_PO_Count,...,Recent_90D_Partial_Fulfilment_Rate,Recent_90D_Late_Delivery_Rate,Recent_90D_Outstanding_Rate,Recent_90D_Average_Delivery_Delay,Current_Outstanding_Quantity,Fulfilment_Risk_Signal,Late_Delivery_Risk_Signal,Partial_Fulfilment_Risk_Signal,Outstanding_Risk_Signal,Supplier_Behaviour_State
0,S001,2022-01-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,0.0,0.0,0.00,0.0,0.00,0.00,Stable
1,S001,2022-01-02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,0.0,0.0,0.00,0.0,0.00,0.00,Stable
2,S001,2022-01-03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,0.0,0.0,0.00,0.0,0.00,0.00,Stable
3,S001,2022-01-04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,0.0,0.0,0.00,0.0,0.00,0.00,Stable
4,S001,2022-01-05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,0.0,0.0,0.00,0.0,0.00,0.00,Stable
5,S001,2022-01-06,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,0.0,0.0,0.00,0.0,0.00,0.00,Stable
6,S001,2022-01-07,1.0,274.0,274.0,0.0,1.0,0.0,0.0,0.0,...,0.00,NaN,0.00,0.0,0.0,0.00,0.0,0.00,0.00,Stable
7,S001,2022-01-08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00,NaN,0.00,0.0,0.0,0.00,0.0,0.00,0.00,Stable
8,S001,2022-01-09,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00,NaN,0.00,0.0,0.0,0.00,0.0,0.00,0.00,Stable
9,S001,2022-01-10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00,NaN,0.00,0.0,0.0,0.00,0.0,0.00,0.00,Stable
10,S001,2022-01-11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00,NaN,0.00,0.0,0.0,0.00,0.0,0.00,0.00,Stable
11,S001,2022-01-12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00,NaN,0.00,0.0,0.0,0.00,0.0,0.00,0.00,Stable
12,S001,2022-01-13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00,NaN,0.00,0.0,0.0,0.00,0.0,0.00,0.00,Stable
13,S001,2022-01-14,1.0,86.0,86.0,0.0,1.0,0.0,0.0,0.0,...,0.00,NaN,0.00,0.0,0.0,0.00,0.0,0.00,0.00,Stable
14,S001,2022-01-15,1.0,158.0,158.0,0.0,1.0,0.0,0.0,0.0,...,0.00,NaN,0.00,0.0,0.0,0.00,0.0,0.00,0.00,Stable
15,S001,2022-01-16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00,NaN,0.00,0.0,0.0,0.00,0.0,0.00,0.00,Stable
16,S001,2022-01-17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00,NaN,0.00,0.0,0.0,0.00,0.0,0.00,0.00,Stable
17,S001,2022-01-18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00,NaN,0.00,0.0,0.0,0.00,0.0,0.00,0.00,Stable
18,S001,2022-01-19,1.0,235.0,192.0,43.0,0.0,1.0,1.0,0.0,...,0.25,NaN,0.25,0.0,43.0,0.25,0.0,0.25,0.25,Stable
19,S001,2022-01-20,1.0,199.0,199.0,0.0,1.0,0.0,0.0,0.0,...,0.20,NaN,0.20,0.0,43.0,0.20,0.0,0.20,0.20,Stable

================================================================================
✓ PHASE 1 COMPLETED SUCCESSFULLY
================================================================================
✓ HISTORICAL SUPPLIER BEHAVIOUR BUILT
✓ RECENT 90-DAY SUPPLIER SIGNALS BUILT
✓ DELIVERY RELIABILITY SIGNALS BUILT
✓ FULFILMENT SIGNALS BUILT
✓ OUTSTANDING EXPOSURE SIGNALS BUILT
✓ SUPPLIER BEHAVIOUR STATES BUILT
✓ NO FUTURE OUTCOME LABEL CREATED YET
✓ READY FOR PHASE 2 — FUTURE SUPPLIER FAILURE OUTCOME
================================================================================

In [12]:
# ================================================================================
# KEYSTRA — FACT_SUPPLIERRISKLABEL
# PHASE 2 — FUTURE SUPPLIER FAILURE OUTCOME
# ================================================================================
#
# PURPOSE
# -------
# Create the FUTURE OUTCOME LABEL for supplier-failure prediction.
#
# Phase 1 = what was known about the supplier at each observation date.
# Phase 2 = what happened AFTER that observation date.
#
# The label answers:
#
# "Did this supplier enter a materially unreliable state
#  during the defined future observation window?"
#
# IMPORTANT
# ----------
# - No Phase 1 feature is modified.
# - No future outcome is used to construct historical signals.
# - Cancelled POs are excluded from operational failure calculations.
# - The final analytical date is not labelled because there is
#   insufficient future observation time.
#
# ================================================================================

import pandas as pd
import numpy as np

print("=" * 80)
print("KEYSTRA — FACT_SUPPLIERRISKLABEL")
print("PHASE 2 — FUTURE SUPPLIER FAILURE OUTCOME")
print("=" * 80)


# ================================================================================
# 1. REQUIRED OBJECTS
# ================================================================================

if "fact_supplier_risk_phase1" not in globals():

    raise ValueError(
        "fact_supplier_risk_phase1 is missing. "
        "Phase 2 requires the completed Phase 1 supplier risk object."
    )

if "po" not in globals():

    raise ValueError(
        "The Purchase Order object 'po' is missing. "
        "Run the PO object discovery cell first."
    )


fact_supplier_risk_phase1 = fact_supplier_risk_phase1.copy()
po = po.copy()

print(f"\n✓ Phase 1 object detected : fact_supplier_risk_phase1")
print(f"✓ Phase 1 rows            : {len(fact_supplier_risk_phase1):,}")
print(f"✓ Phase 1 columns         : {len(fact_supplier_risk_phase1.columns)}")

print(f"✓ Purchase Order object detected : po")
print(f"✓ Purchase Order rows            : {len(po):,}")
print(f"✓ Purchase Order columns         : {len(po.columns)}")


# ================================================================================
# 2. STANDARDISE DATES
# ================================================================================

fact_supplier_risk_phase1["Observation_Date"] = pd.to_datetime(
    fact_supplier_risk_phase1["Observation_Date"],
    errors="coerce"
)

po["Order_Date"] = pd.to_datetime(
    po["Order_Date"],
    errors="coerce"
)

po["Expected_Delivery_Date"] = pd.to_datetime(
    po["Expected_Delivery_Date"],
    errors="coerce"
)

po["Actual_Delivery_Date"] = pd.to_datetime(
    po["Actual_Delivery_Date"],
    errors="coerce"
)


# ================================================================================
# 3. VALIDATE PHASE 1 DATE WINDOW
# ================================================================================

analysis_start = fact_supplier_risk_phase1["Observation_Date"].min()
analysis_end = fact_supplier_risk_phase1["Observation_Date"].max()

print("\n================================================================================")
print("ANALYTICAL WINDOW")
print("================================================================================")

print(f"Start date : {analysis_start.date()}")
print(f"End date   : {analysis_end.date()}")


# ================================================================================
# 4. VALIDATE SUPPLIER KEYS
# ================================================================================

phase1_suppliers = set(
    fact_supplier_risk_phase1["Supplier_ID"]
    .dropna()
    .unique()
)

po_suppliers = set(
    po["Supplier_ID"]
    .dropna()
    .unique()
)

missing_supplier_keys = po_suppliers - phase1_suppliers

if missing_supplier_keys:

    raise ValueError(
        f"PO contains {len(missing_supplier_keys)} suppliers "
        "not represented in Phase 1."
    )

print(f"\n✓ Supplier foreign keys valid")
print(f"✓ Suppliers represented in Phase 1 : {len(phase1_suppliers)}")


# ================================================================================
# 5. DEFINE OPERATIONAL PO LINES
# ================================================================================
#
# Cancelled POs do not represent operational supplier failure.
#

po["Is_Cancelled"] = (
    po["Is_Cancelled"]
    .fillna(0)
    .astype(int)
)

operational_po = po[
    po["Is_Cancelled"] == 0
].copy()

print(f"\n✓ Cancelled PO lines excluded : {len(po) - len(operational_po):,}")
print(f"✓ Operational PO lines       : {len(operational_po):,}")


# ================================================================================
# 6. CLEAN QUANTITY / DELIVERY FIELDS
# ================================================================================

numeric_columns = [
    "Quantity_Ordered",
    "Quantity_Received",
    "Outstanding_Quantity",
    "Days_Late",
    "Fulfilment_Rate"
]

for col in numeric_columns:

    if col in operational_po.columns:

        operational_po[col] = pd.to_numeric(
            operational_po[col],
            errors="coerce"
        ).fillna(0)


# ================================================================================
# 7. FUTURE FAILURE WINDOW
# ================================================================================
#
# We use a 90-day forward-looking window.
#
# Example:
#
# Observation date = 2026-04-01
#
# Future outcome window =
# 2026-04-02 → 2026-06-30
#
# This allows the model to learn:
#
# CURRENT supplier behaviour
#             ↓
# FUTURE supplier failure
#
# rather than simply predicting the current state.
#
# ================================================================================

FUTURE_WINDOW_DAYS = 90

print("\n================================================================================")
print("FUTURE OUTCOME DEFINITION")
print("================================================================================")

print(f"Future observation window : {FUTURE_WINDOW_DAYS} days")


# ================================================================================
# 8. BUILD SUPPLIER-LEVEL FUTURE FAILURE EVENTS
# ================================================================================
#
# A supplier is considered to experience a future failure event when,
# during the next 90 days, there is evidence of material operational
# unreliability.
#
# The event uses several independent operational signals:
#
# 1. Severe fulfilment failure
# 2. Significant late delivery
# 3. Persistent outstanding quantity
#
# The objective is NOT to label every imperfect delivery as failure.
#
# We want a materially unreliable supplier state.
#
# ================================================================================

future_po = operational_po.copy()

future_po["Future_Fulfilment_Failure"] = (
    future_po["Fulfilment_Rate"] < 0.70
).astype(int)

future_po["Future_Late_Delivery_Failure"] = (
    future_po["Days_Late"] >= 14
).astype(int)

future_po["Future_Outstanding_Failure"] = (
    future_po["Outstanding_Quantity"] > 0
).astype(int)


# ================================================================================
# 9. DEFINE MATERIAL FUTURE FAILURE EVENT
# ================================================================================
#
# A PO-level event is considered materially problematic when:
#
# - fulfilment is below 70%
# OR
# - delivery is at least 14 days late
# OR
# - the PO remains outstanding.
#
# This is then aggregated at supplier level over the future window.
#
# ================================================================================

future_po["Material_Failure_Event"] = (
    (
        future_po["Future_Fulfilment_Failure"] == 1
    )
    |
    (
        future_po["Future_Late_Delivery_Failure"] == 1
    )
    |
    (
        future_po["Future_Outstanding_Failure"] == 1
    )
).astype(int)


# ================================================================================
# 10. CREATE FUTURE EVENT DATE
# ================================================================================

future_po["Event_Date"] = future_po["Order_Date"]


# ================================================================================
# 11. SUPPLIER × EVENT DATE AGGREGATION
# ================================================================================

supplier_future_events = (
    future_po
    .groupby(
        ["Supplier_ID", "Event_Date"],
        as_index=False
    )
    .agg(
        Future_PO_Count=(
            "PO_ID",
            "nunique"
        ),
        Future_Fulfilment_Failure_Count=(
            "Future_Fulfilment_Failure",
            "sum"
        ),
        Future_Late_Failure_Count=(
            "Future_Late_Delivery_Failure",
            "sum"
        ),
        Future_Outstanding_Failure_Count=(
            "Future_Outstanding_Failure",
            "sum"
        ),
        Material_Failure_Event_Count=(
            "Material_Failure_Event",
            "sum"
        )
    )
)


# ================================================================================
# 12. CREATE OBSERVATION GRID
# ================================================================================

observation_grid = (
    fact_supplier_risk_phase1[
        [
            "Supplier_ID",
            "Observation_Date"
        ]
    ]
    .drop_duplicates()
    .copy()
)

print("\n✓ Supplier × observation grid retained")


# ================================================================================
# 13. TEMPORAL JOIN
# ================================================================================
#
# For every supplier observation date, retrieve ONLY events that occur
# AFTER the observation date and within the next 90 days.
#
# This is the critical anti-leakage step.
#
# ================================================================================

future_events = supplier_future_events.copy()

future_events["Event_Date"] = pd.to_datetime(
    future_events["Event_Date"]
)

observation_grid["Observation_Date"] = pd.to_datetime(
    observation_grid["Observation_Date"]
)

observation_grid = observation_grid.sort_values(
    ["Supplier_ID", "Observation_Date"]
)

future_events = future_events.sort_values(
    ["Supplier_ID", "Event_Date"]
)


# ================================================================================
# 14. BUILD FUTURE FAILURE LABEL
# ================================================================================

future_label_rows = []

for supplier_id, obs_group in observation_grid.groupby("Supplier_ID"):

    supplier_events = future_events[
        future_events["Supplier_ID"] == supplier_id
    ]

    event_dates = supplier_events["Event_Date"].values

    event_failure_counts = supplier_events[
        "Material_Failure_Event_Count"
    ].values

    event_po_counts = supplier_events[
        "Future_PO_Count"
    ].values

    event_fulfilment_failures = supplier_events[
        "Future_Fulfilment_Failure_Count"
    ].values

    event_late_failures = supplier_events[
        "Future_Late_Failure_Count"
    ].values

    event_outstanding_failures = supplier_events[
        "Future_Outstanding_Failure_Count"
    ].values

    for observation_date in obs_group["Observation_Date"]:

        future_start = observation_date + pd.Timedelta(days=1)

        future_end = (
            observation_date
            + pd.Timedelta(days=FUTURE_WINDOW_DAYS)
        )

        mask = (
            (event_dates >= np.datetime64(future_start))
            &
            (event_dates <= np.datetime64(future_end))
        )

        failure_events = event_failure_counts[mask]

        future_po_count = event_po_counts[mask].sum()
        future_failure_count = failure_events.sum()

        future_fulfilment_failures_count = (
            event_fulfilment_failures[mask].sum()
        )

        future_late_failures_count = (
            event_late_failures[mask].sum()
        )

        future_outstanding_failures_count = (
            event_outstanding_failures[mask].sum()
        )

        future_label_rows.append(
            {
                "Supplier_ID": supplier_id,
                "Observation_Date": observation_date,
                "Future_90D_PO_Count": int(future_po_count),
                "Future_90D_Material_Failure_Events": int(
                    future_failure_count
                ),
                "Future_90D_Fulfilment_Failure_Events": int(
                    future_fulfilment_failures_count
                ),
                "Future_90D_Late_Delivery_Failure_Events": int(
                    future_late_failures_count
                ),
                "Future_90D_Outstanding_Failure_Events": int(
                    future_outstanding_failures_count
                )
            }
        )


future_outcome = pd.DataFrame(
    future_label_rows
)


# ================================================================================
# 15. CREATE FAILURE LABEL
# ================================================================================
#
# Label definition:
#
# 1 = supplier experiences at least one material future failure event
#     within the next 90 days.
#
# 0 = no material future failure event observed.
#
# However, dates without enough future horizon cannot safely be labelled.
#
# ================================================================================

future_outcome["Future_Window_End"] = (
    future_outcome["Observation_Date"]
    + pd.Timedelta(days=FUTURE_WINDOW_DAYS)
)

future_outcome["Future_Window_Complete"] = (
    future_outcome["Future_Window_End"] <= analysis_end
)


future_outcome["Supplier_Failure_Label"] = np.where(
    future_outcome["Future_Window_Complete"],
    (
        future_outcome[
            "Future_90D_Material_Failure_Events"
        ] > 0
    ).astype(int),
    np.nan
)


# ================================================================================
# 16. FUTURE FAILURE SEVERITY
# ================================================================================

def classify_future_failure(row):

    if not row["Future_Window_Complete"]:
        return "Not_Labelable"

    if row["Future_90D_Material_Failure_Events"] == 0:
        return "No_Failure"

    if (
        row["Future_90D_Fulfilment_Failure_Events"] >= 3
        or
        row["Future_90D_Late_Delivery_Failure_Events"] >= 3
        or
        row["Future_90D_Outstanding_Failure_Events"] >= 3
    ):
        return "Severe_Failure"

    return "Material_Failure"


future_outcome["Future_Failure_Severity"] = (
    future_outcome.apply(
        classify_future_failure,
        axis=1
    )
)


# ================================================================================
# 17. MERGE PHASE 1 + FUTURE OUTCOME
# ================================================================================

fact_supplier_risk_label = (
    fact_supplier_risk_phase1
    .merge(
        future_outcome,
        on=[
            "Supplier_ID",
            "Observation_Date"
        ],
        how="left",
        validate="one_to_one"
    )
)


# ================================================================================
# 18. VALIDATION — GRAIN
# ================================================================================

print("\n================================================================================")
print("PHASE 2 — FUTURE OUTCOME VALIDATION")
print("================================================================================")

expected_rows = len(fact_supplier_risk_phase1)

if len(fact_supplier_risk_label) != expected_rows:

    raise ValueError(
        "Phase 2 merge changed the Phase 1 row count."
    )

print(
    f"✓ ROW COUNT PRESERVED : {len(fact_supplier_risk_label):,}"
)


if fact_supplier_risk_label[
    ["Supplier_ID", "Observation_Date"]
].duplicated().any():

    raise ValueError(
        "Supplier × Observation_Date grain is not unique."
    )

print("✓ SUPPLIER × DATE GRAIN UNIQUE")


# ================================================================================
# 19. VALIDATION — FUTURE WINDOW
# ================================================================================

if (
    fact_supplier_risk_label[
        "Future_Window_End"
    ]
    <
    fact_supplier_risk_label[
        "Observation_Date"
    ]
).any():

    raise ValueError(
        "Future window contains dates before observation date."
    )

print("✓ FUTURE WINDOWS TEMPORALLY VALID")


# ================================================================================
# 20. VALIDATION — NO FUTURE LEAKAGE
# ================================================================================

if (
    future_outcome[
        "Future_Window_Complete"
    ]
    &
    (
        future_outcome[
            "Future_90D_Material_Failure_Events"
        ] < 0
    )
).any():

    raise ValueError(
        "Invalid future failure event count detected."
    )

print("✓ FUTURE FAILURE COUNTS NON-NEGATIVE")


# ================================================================================
# 21. VALIDATION — LABEL VALUES
# ================================================================================

valid_labels = {0, 1}

observed_labels = set(
    fact_supplier_risk_label[
        "Supplier_Failure_Label"
    ]
    .dropna()
    .unique()
)

if not observed_labels.issubset(valid_labels):

    raise ValueError(
        f"Invalid Supplier_Failure_Label values detected: "
        f"{observed_labels}"
    )

print("✓ SUPPLIER FAILURE LABEL VALUES VALID")


# ================================================================================
# 22. VALIDATION — LABEL CONSISTENCY
# ================================================================================

label_check = (
    fact_supplier_risk_label[
        "Future_Window_Complete"
    ]
    &
    (
        fact_supplier_risk_label[
            "Future_90D_Material_Failure_Events"
        ] > 0
    )
)

actual_label_check = (
    fact_supplier_risk_label[
        "Supplier_Failure_Label"
    ] == 1
)

if (
    fact_supplier_risk_label[
        "Future_Window_Complete"
    ]
    &
    (
        label_check != actual_label_check
    )
).any():

    raise ValueError(
        "Supplier_Failure_Label is inconsistent with "
        "future material failure events."
    )

print("✓ FAILURE LABEL LOGIC CONSISTENT")


# ================================================================================
# 23. VALIDATION — INCOMPLETE FUTURE WINDOWS
# ================================================================================

incomplete_windows = (
    ~fact_supplier_risk_label[
        "Future_Window_Complete"
    ]
)

if (
    fact_supplier_risk_label.loc[
        incomplete_windows,
        "Supplier_Failure_Label"
    ]
    .notna()
    .any()
):

    raise ValueError(
        "Incomplete future windows must not receive a failure label."
    )

print("✓ INCOMPLETE FUTURE WINDOWS LEFT UNLABELLED")


# ================================================================================
# 24. VALIDATION — PHASE 1 SIGNALS UNCHANGED
# ================================================================================

phase1_columns = list(
    fact_supplier_risk_phase1.columns
)

for col in phase1_columns:

    if col not in fact_supplier_risk_label.columns:

        raise ValueError(
            f"Phase 1 column missing after merge: {col}"
        )

print("✓ ALL PHASE 1 SIGNALS PRESERVED")


# ================================================================================
# 25. LABEL DISTRIBUTION
# ================================================================================

print("\n================================================================================")
print("SUPPLIER FAILURE LABEL DISTRIBUTION")
print("================================================================================")

print(
    fact_supplier_risk_label[
        "Supplier_Failure_Label"
    ]
    .value_counts(
        dropna=False
    )
)


# ================================================================================
# 26. SEVERITY DISTRIBUTION
# ================================================================================

print("\n================================================================================")
print("FUTURE FAILURE SEVERITY DISTRIBUTION")
print("================================================================================")

print(
    fact_supplier_risk_label[
        "Future_Failure_Severity"
    ]
    .value_counts(
        dropna=False
    )
)


# ================================================================================
# 27. SUMMARY
# ================================================================================

labelable_rows = (
    fact_supplier_risk_label[
        "Future_Window_Complete"
    ].sum()
)

positive_labels = (
    fact_supplier_risk_label[
        "Supplier_Failure_Label"
    ]
    .eq(1)
    .sum()
)

negative_labels = (
    fact_supplier_risk_label[
        "Supplier_Failure_Label"
    ]
    .eq(0)
    .sum()
)

unlabelled_rows = (
    fact_supplier_risk_label[
        "Supplier_Failure_Label"
    ]
    .isna()
    .sum()
)

print("\n================================================================================")
print("PHASE 2 SUMMARY")
print("================================================================================")

print(
    f"Supplier/date rows          : "
    f"{len(fact_supplier_risk_label):,}"
)

print(
    f"Labelable observations      : "
    f"{labelable_rows:,}"
)

print(
    f"Positive failure labels     : "
    f"{positive_labels:,}"
)

print(
    f"Negative failure labels     : "
    f"{negative_labels:,}"
)

print(
    f"Unlabelled observations     : "
    f"{unlabelled_rows:,}"
)

if labelable_rows > 0:

    print(
        f"Failure rate among labelable: "
        f"{positive_labels / labelable_rows:.2%}"
    )


# ================================================================================
# 28. PREVIEW
# ================================================================================

print("\n================================================================================")
print("FACT_SUPPLIERRISKLABEL PREVIEW")
print("================================================================================")

preview_columns = [
    "Supplier_ID",
    "Observation_Date",
    "Supplier_Behaviour_State",
    "Recent_90D_Fulfilment_Rate",
    "Recent_90D_Late_Delivery_Rate",
    "Recent_90D_Outstanding_Rate",
    "Current_Outstanding_Quantity",
    "Future_90D_PO_Count",
    "Future_90D_Material_Failure_Events",
    "Future_90D_Fulfilment_Failure_Events",
    "Future_90D_Late_Delivery_Failure_Events",
    "Future_90D_Outstanding_Failure_Events",
    "Future_Window_Complete",
    "Supplier_Failure_Label",
    "Future_Failure_Severity"
]

display(
    fact_supplier_risk_label[
        preview_columns
    ].head(20)
)


# ================================================================================
# 29. FINAL VALIDATION
# ================================================================================

print("\n================================================================================")
print("✓ FACT_SUPPLIERRISKLABEL PHASE 2 COMPLETED SUCCESSFULLY")
print("================================================================================")

print("✓ PHASE 1 SUPPLIER SIGNALS PRESERVED")
print("✓ FUTURE SUPPLIER OUTCOME CREATED")
print("✓ 90-DAY FUTURE WINDOW APPLIED")
print("✓ MATERIAL FAILURE EVENTS IDENTIFIED")
print("✓ FAILURE LABEL CREATED")
print("✓ FAILURE SEVERITY CREATED")
print("✓ INCOMPLETE FUTURE WINDOWS EXCLUDED")
print("✓ NO FUTURE OUTCOME INFORMATION ADDED TO PHASE 1 FEATURES")
print("✓ SUPPLIER × DATE GRAIN PRESERVED")
print("================================================================================")

================================================================================
KEYSTRA — FACT_SUPPLIERRISKLABEL
PHASE 2 — FUTURE SUPPLIER FAILURE OUTCOME
================================================================================

✓ Phase 1 object detected : fact_supplier_risk_phase1
✓ Phase 1 rows            : 150,570
✓ Phase 1 columns         : 32
✓ Purchase Order object detected : po
✓ Purchase Order rows            : 40,000
✓ Purchase Order columns         : 20

================================================================================
ANALYTICAL WINDOW
================================================================================
Start date : 2022-01-01
End date   : 2026-07-31

✓ Supplier foreign keys valid
✓ Suppliers represented in Phase 1 : 90

✓ Cancelled PO lines excluded : 312
✓ Operational PO lines       : 39,688

================================================================================
FUTURE OUTCOME DEFINITION
================================================================================
Future observation window : 90 days

✓ Supplier × observation grid retained

================================================================================
PHASE 2 — FUTURE OUTCOME VALIDATION
================================================================================
✓ ROW COUNT PRESERVED : 150,570
✓ SUPPLIER × DATE GRAIN UNIQUE
✓ FUTURE WINDOWS TEMPORALLY VALID
✓ FUTURE FAILURE COUNTS NON-NEGATIVE
✓ SUPPLIER FAILURE LABEL VALUES VALID
✓ FAILURE LABEL LOGIC CONSISTENT
✓ INCOMPLETE FUTURE WINDOWS LEFT UNLABELLED
✓ ALL PHASE 1 SIGNALS PRESERVED

================================================================================
SUPPLIER FAILURE LABEL DISTRIBUTION
================================================================================
Supplier_Failure_Label
1.0    133701
0.0      8769
NaN      8100
Name: count, dtype: int64

================================================================================
FUTURE FAILURE SEVERITY DISTRIBUTION
================================================================================
Future_Failure_Severity
Severe_Failure      89006
Material_Failure    44695
No_Failure           8769
Not_Labelable        8100
Name: count, dtype: int64

================================================================================
PHASE 2 SUMMARY
================================================================================
Supplier/date rows          : 150,570
Labelable observations      : 142,470
Positive failure labels     : 133,701
Negative failure labels     : 8,769
Unlabelled observations     : 8,100
Failure rate among labelable: 93.85%

================================================================================
FACT_SUPPLIERRISKLABEL PREVIEW
================================================================================

,Supplier_ID,Observation_Date,Supplier_Behaviour_State,Recent_90D_Fulfilment_Rate,Recent_90D_Late_Delivery_Rate,Recent_90D_Outstanding_Rate,Current_Outstanding_Quantity,Future_90D_PO_Count,Future_90D_Material_Failure_Events,Future_90D_Fulfilment_Failure_Events,Future_90D_Late_Delivery_Failure_Events,Future_90D_Outstanding_Failure_Events,Future_Window_Complete,Supplier_Failure_Label,Future_Failure_Severity
0,S001,2022-01-01,Stable,NaN,NaN,NaN,0.0,28,6,2,2,4,True,1.0,Severe_Failure
1,S001,2022-01-02,Stable,NaN,NaN,NaN,0.0,28,6,2,2,4,True,1.0,Severe_Failure
2,S001,2022-01-03,Stable,NaN,NaN,NaN,0.0,30,7,2,2,5,True,1.0,Severe_Failure
3,S001,2022-01-04,Stable,NaN,NaN,NaN,0.0,30,7,2,2,5,True,1.0,Severe_Failure
4,S001,2022-01-05,Stable,NaN,NaN,NaN,0.0,30,7,2,2,5,True,1.0,Severe_Failure
5,S001,2022-01-06,Stable,NaN,NaN,NaN,0.0,30,7,2,2,5,True,1.0,Severe_Failure
6,S001,2022-01-07,Stable,1.00,NaN,0.00,0.0,29,7,2,2,5,True,1.0,Severe_Failure
7,S001,2022-01-08,Stable,1.00,NaN,0.00,0.0,29,7,2,2,5,True,1.0,Severe_Failure
8,S001,2022-01-09,Stable,1.00,NaN,0.00,0.0,29,7,2,2,5,True,1.0,Severe_Failure
9,S001,2022-01-10,Stable,1.00,NaN,0.00,0.0,29,7,2,2,5,True,1.0,Severe_Failure
10,S001,2022-01-11,Stable,1.00,NaN,0.00,0.0,29,7,2,2,5,True,1.0,Severe_Failure
11,S001,2022-01-12,Stable,1.00,NaN,0.00,0.0,29,7,2,2,5,True,1.0,Severe_Failure
12,S001,2022-01-13,Stable,1.00,NaN,0.00,0.0,29,7,2,2,5,True,1.0,Severe_Failure
13,S001,2022-01-14,Stable,1.00,NaN,0.00,0.0,28,7,2,2,5,True,1.0,Severe_Failure
14,S001,2022-01-15,Stable,1.00,NaN,0.00,0.0,27,7,2,2,5,True,1.0,Severe_Failure
15,S001,2022-01-16,Stable,1.00,NaN,0.00,0.0,27,7,2,2,5,True,1.0,Severe_Failure
16,S001,2022-01-17,Stable,1.00,NaN,0.00,0.0,27,7,2,2,5,True,1.0,Severe_Failure
17,S001,2022-01-18,Stable,1.00,NaN,0.00,0.0,27,7,2,2,5,True,1.0,Severe_Failure
18,S001,2022-01-19,Stable,0.75,NaN,0.25,43.0,26,6,2,2,4,True,1.0,Severe_Failure
19,S001,2022-01-20,Stable,0.80,NaN,0.20,43.0,27,6,2,2,4,True,1.0,Severe_Failure

================================================================================
✓ FACT_SUPPLIERRISKLABEL PHASE 2 COMPLETED SUCCESSFULLY
================================================================================
✓ PHASE 1 SUPPLIER SIGNALS PRESERVED
✓ FUTURE SUPPLIER OUTCOME CREATED
✓ 90-DAY FUTURE WINDOW APPLIED
✓ MATERIAL FAILURE EVENTS IDENTIFIED
✓ FAILURE LABEL CREATED
✓ FAILURE SEVERITY CREATED
✓ INCOMPLETE FUTURE WINDOWS EXCLUDED
✓ NO FUTURE OUTCOME INFORMATION ADDED TO PHASE 1 FEATURES
✓ SUPPLIER × DATE GRAIN PRESERVED
================================================================================

In [13]:
# ================================================================================
# KEYSTRA — SUPPLIER FAILURE LABEL AUDIT
# STEP 1 — DIAGNOSE WHY THE CURRENT FAILURE RATE IS 93.85%
# ================================================================================
#
# IMPORTANT:
# - DOES NOT modify fact_supplier_risk_phase1
# - DOES NOT modify fact_supplier_risk_label
# - DOES NOT rebuild anything
# - ONLY diagnoses the current Phase 2 outcome
#
# Purpose:
#   Understand which future failure component is causing the extremely high
#   failure rate before we redesign the business-defined FAILURE state.
# ================================================================================

import pandas as pd
import numpy as np

print("=" * 80)
print("KEYSTRA — SUPPLIER FAILURE LABEL AUDIT")
print("STEP 1 — CURRENT PHASE 2 FAILURE DIAGNOSTICS")
print("=" * 80)


# ------------------------------------------------------------------------------
# 1. LOCATE EXISTING PHASE 2 OBJECT
# ------------------------------------------------------------------------------

fact_supplier_risk_label = globals().get("fact_supplier_risk_label")

if fact_supplier_risk_label is None:
    raise ValueError(
        "fact_supplier_risk_label was not found in the current Colab session."
    )

df = fact_supplier_risk_label.copy()

print(f"\n✓ Phase 2 object detected")
print(f"  Rows    : {len(df):,}")
print(f"  Columns : {len(df.columns)}")


# ------------------------------------------------------------------------------
# 2. REQUIRED COLUMNS
# ------------------------------------------------------------------------------

required_columns = [
    "Supplier_ID",
    "Observation_Date",
    "Supplier_Behaviour_State",
    "Future_90D_PO_Count",
    "Future_90D_Material_Failure_Events",
    "Future_90D_Fulfilment_Failure_Events",
    "Future_90D_Late_Delivery_Failure_Events",
    "Future_90D_Outstanding_Failure_Events",
    "Future_Window_Complete",
    "Supplier_Failure_Label",
    "Future_Failure_Severity"
]

missing = [c for c in required_columns if c not in df.columns]

if missing:
    raise ValueError(
        f"Required columns are missing from fact_supplier_risk_label:\n{missing}"
    )

print("\n✓ REQUIRED COLUMNS VALID")


# ------------------------------------------------------------------------------
# 3. LABELABLE POPULATION
# ------------------------------------------------------------------------------

labelable = df[df["Future_Window_Complete"] == True].copy()

print("\n" + "=" * 80)
print("LABELABLE POPULATION")
print("=" * 80)

print(f"Total observations       : {len(df):,}")
print(f"Complete future windows  : {len(labelable):,}")
print(
    f"Incomplete future windows: "
    f"{len(df) - len(labelable):,}"
)


# ------------------------------------------------------------------------------
# 4. CURRENT LABEL DISTRIBUTION
# ------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("CURRENT FAILURE LABEL")
print("=" * 80)

label_counts = (
    labelable["Supplier_Failure_Label"]
    .value_counts(dropna=False)
    .rename_axis("Supplier_Failure_Label")
    .reset_index(name="Observations")
)

label_counts["Share"] = (
    label_counts["Observations"] / len(labelable)
).round(4)

print(label_counts.to_string(index=False))

failure_rate = (
    labelable["Supplier_Failure_Label"].eq(1).mean()
)

print(f"\nCurrent failure rate : {failure_rate:.2%}")


# ------------------------------------------------------------------------------
# 5. FAILURE COMPONENT ANALYSIS
# ------------------------------------------------------------------------------

components = {
    "Material_Failure":
        "Future_90D_Material_Failure_Events",

    "Fulfilment_Failure":
        "Future_90D_Fulfilment_Failure_Events",

    "Late_Delivery_Failure":
        "Future_90D_Late_Delivery_Failure_Events",

    "Outstanding_Failure":
        "Future_90D_Outstanding_Failure_Events"
}

component_rows = []

for name, col in components.items():

    event_count = labelable[col].fillna(0)

    component_rows.append({
        "Failure_Component": name,
        "Total_Events": int(event_count.sum()),
        "Rows_With_Event": int((event_count > 0).sum()),
        "Share_of_Labelable_Rows":
            round((event_count > 0).mean(), 4),
        "Mean_Events_Per_Row":
            round(event_count.mean(), 3),
        "Max_Events_In_Row":
            int(event_count.max())
    })

component_df = pd.DataFrame(component_rows)

print("\n" + "=" * 80)
print("FAILURE COMPONENT PRESSURE")
print("=" * 80)

print(component_df.to_string(index=False))


# ------------------------------------------------------------------------------
# 6. COMBINATION ANALYSIS
# ------------------------------------------------------------------------------

for name, col in components.items():

    labelable[f"_has_{name}"] = (
        labelable[col].fillna(0) > 0
    )


labelable["_component_count"] = (
    labelable[
        [f"_has_{name}" for name in components]
    ]
    .sum(axis=1)
)

combination_distribution = (
    labelable["_component_count"]
    .value_counts()
    .sort_index()
    .rename_axis("Number_of_Failure_Components")
    .reset_index(name="Observations")
)

combination_distribution["Share"] = (
    combination_distribution["Observations"] /
    len(labelable)
).round(4)

print("\n" + "=" * 80)
print("NUMBER OF FAILURE DIMENSIONS PER OBSERVATION")
print("=" * 80)

print(combination_distribution.to_string(index=False))


# ------------------------------------------------------------------------------
# 7. FAILURE LABEL AGAINST COMPONENT COUNT
# ------------------------------------------------------------------------------

label_component = (
    labelable
    .groupby("_component_count", dropna=False)
    .agg(
        Observations=("Supplier_ID", "size"),
        Failures=("Supplier_Failure_Label", lambda x: (x == 1).sum()),
        No_Failure=("Supplier_Failure_Label", lambda x: (x == 0).sum())
    )
    .reset_index()
)

label_component["Failure_Rate"] = (
    label_component["Failures"] /
    label_component["Observations"]
).round(4)

print("\n" + "=" * 80)
print("FAILURE LABEL vs NUMBER OF FAILURE DIMENSIONS")
print("=" * 80)

print(label_component.to_string(index=False))


# ------------------------------------------------------------------------------
# 8. BEHAVIOUR STATE vs CURRENT FAILURE
# ------------------------------------------------------------------------------

state_analysis = (
    labelable
    .groupby("Supplier_Behaviour_State")
    .agg(
        Observations=("Supplier_ID", "size"),
        Failures=("Supplier_Failure_Label", lambda x: (x == 1).sum()),
        No_Failure=("Supplier_Failure_Label", lambda x: (x == 0).sum())
    )
    .reset_index()
)

state_analysis["Failure_Rate"] = (
    state_analysis["Failures"] /
    state_analysis["Observations"]
).round(4)

print("\n" + "=" * 80)
print("CURRENT BEHAVIOUR STATE → FUTURE FAILURE")
print("=" * 80)

print(state_analysis.to_string(index=False))


# ------------------------------------------------------------------------------
# 9. SUPPLIER-LEVEL FAILURE RATE
# ------------------------------------------------------------------------------

supplier_analysis = (
    labelable
    .groupby("Supplier_ID")
    .agg(
        Observations=("Observation_Date", "size"),
        Failures=("Supplier_Failure_Label", lambda x: (x == 1).sum()),
        Failure_Rate=("Supplier_Failure_Label", "mean")
    )
    .reset_index()
)

print("\n" + "=" * 80)
print("SUPPLIER-LEVEL FAILURE RATE")
print("=" * 80)

print(
    supplier_analysis["Failure_Rate"]
    .describe()
    .to_string()
)

print(
    f"\nSuppliers with >=95% failure rate : "
    f"{(supplier_analysis['Failure_Rate'] >= 0.95).sum()}"
)

print(
    f"Suppliers with >=90% failure rate : "
    f"{(supplier_analysis['Failure_Rate'] >= 0.90).sum()}"
)

print(
    f"Suppliers with <=10% failure rate : "
    f"{(supplier_analysis['Failure_Rate'] <= 0.10).sum()}"
)


# ------------------------------------------------------------------------------
# 10. ZERO-EVENT OBSERVATIONS
# ------------------------------------------------------------------------------

zero_event = (
    labelable["_component_count"] == 0
)

print("\n" + "=" * 80)
print("OBSERVATIONS WITH NO FUTURE FAILURE COMPONENT")
print("=" * 80)

print(f"No future failure component : {zero_event.sum():,}")
print(
    f"Of these, labelled failure  : "
    f"{(labelable.loc[zero_event, 'Supplier_Failure_Label'] == 1).sum():,}"
)
print(
    f"Of these, labelled no-failure: "
    f"{(labelable.loc[zero_event, 'Supplier_Failure_Label'] == 0).sum():,}"
)


# ------------------------------------------------------------------------------
# 11. MOST COMMON FAILURE COMBINATIONS
# ------------------------------------------------------------------------------

combination_columns = [
    f"_has_{name}" for name in components
]

combo = (
    labelable
    .groupby(combination_columns)
    .agg(
        Observations=("Supplier_ID", "size"),
        Failures=("Supplier_Failure_Label", lambda x: (x == 1).sum())
    )
    .reset_index()
)

combo["Failure_Rate"] = (
    combo["Failures"] /
    combo["Observations"]
).round(4)

combo = combo.sort_values(
    ["Observations", "Failure_Rate"],
    ascending=[False, False]
)

print("\n" + "=" * 80)
print("MOST COMMON FAILURE COMPONENT COMBINATIONS")
print("=" * 80)

print(combo.head(15).to_string(index=False))


# ------------------------------------------------------------------------------
# 12. DIAGNOSTIC CONCLUSION
# ------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("KEYSTRA — AUDIT CONCLUSION")
print("=" * 80)

print(
    f"\nCurrent failure rate: {failure_rate:.2%}"
)

if failure_rate >= 0.80:
    print(
        "\n⚠️ CURRENT FAILURE DEFINITION IS TOO BROAD FOR THE "
        "PREDICTIVE OBJECTIVE."
    )
    print(
        "The next step should be to redesign the business-defined "
        "FAILURE STATE."
    )
else:
    print(
        "\n✓ Failure prevalence is not immediately excessive."
    )

print(
    "\nIMPORTANT:"
    "\nNo existing Phase 1 or Phase 2 object has been modified."
    "\nNo modelling dataset has been changed."
    "\nNo target has been rebuilt yet."
)

# Clean temporary audit columns from local copy only
temporary_columns = [
    c for c in labelable.columns
    if c.startswith("_has_")
] + ["_component_count"]

labelable.drop(
    columns=temporary_columns,
    inplace=True,
    errors="ignore"
)

print("\n" + "=" * 80)
print("✓ STEP 1 AUDIT COMPLETED")
print("=" * 80)

================================================================================
KEYSTRA — SUPPLIER FAILURE LABEL AUDIT
STEP 1 — CURRENT PHASE 2 FAILURE DIAGNOSTICS
================================================================================

✓ Phase 2 object detected
  Rows    : 150,570
  Columns : 41

✓ REQUIRED COLUMNS VALID

================================================================================
LABELABLE POPULATION
================================================================================
Total observations       : 150,570
Complete future windows  : 142,470
Incomplete future windows: 8,100

================================================================================
CURRENT FAILURE LABEL
================================================================================
 Supplier_Failure_Label  Observations  Share
                    1.0        133701 0.9385
                    0.0          8769 0.0615

Current failure rate : 93.85%

================================================================================
FAILURE COMPONENT PRESSURE
================================================================================
    Failure_Component  Total_Events  Rows_With_Event  Share_of_Labelable_Rows  Mean_Events_Per_Row  Max_Events_In_Row
     Material_Failure        693702           133701                   0.9385                4.869                 41
   Fulfilment_Failure        389708           109396                   0.7679                2.735                 36
Late_Delivery_Failure         87250            44611                   0.3131                0.612                 13
  Outstanding_Failure        621046           132134                   0.9275                4.359                 41

================================================================================
NUMBER OF FAILURE DIMENSIONS PER OBSERVATION
================================================================================
 Number_of_Failure_Components  Observations  Share
                            0          8769 0.0615
                            2         18946 0.1330
                            3         77070 0.5410
                            4         37685 0.2645

================================================================================
FAILURE LABEL vs NUMBER OF FAILURE DIMENSIONS
================================================================================
 _component_count  Observations  Failures  No_Failure  Failure_Rate
                0          8769         0        8769           0.0
                2         18946     18946           0           1.0
                3         77070     77070           0           1.0
                4         37685     37685           0           1.0

================================================================================
CURRENT BEHAVIOUR STATE → FUTURE FAILURE
================================================================================
Supplier_Behaviour_State  Observations  Failures  No_Failure  Failure_Rate
     Delivery Unreliable           496       493           3        0.9940
           Deteriorating         26450     26342         108        0.9959
     Severely Unreliable          2858      2847          11        0.9962
                  Stable        112666    104019        8647        0.9233

================================================================================
SUPPLIER-LEVEL FAILURE RATE
================================================================================
count    90.000000
mean      0.938450
std       0.077873
min       0.713203
25%       0.899874
50%       0.974416
75%       1.000000
max       1.000000

Suppliers with >=95% failure rate : 55
Suppliers with >=90% failure rate : 67
Suppliers with <=10% failure rate : 0

================================================================================
OBSERVATIONS WITH NO FUTURE FAILURE COMPONENT
================================================================================
No future failure component : 8,769
Of these, labelled failure  : 0
Of these, labelled no-failure: 8,769

================================================================================
MOST COMMON FAILURE COMPONENT COMBINATIONS
================================================================================
 _has_Material_Failure  _has_Fulfilment_Failure  _has_Late_Delivery_Failure  _has_Outstanding_Failure  Observations  Failures  Failure_Rate
                  True                     True                       False                      True         71711     71711           1.0
                  True                     True                        True                      True         37685     37685           1.0
                  True                    False                       False                      True         17379     17379           1.0
                 False                    False                       False                     False          8769         0           0.0
                  True                    False                        True                      True          5359      5359           1.0
                  True                    False                        True                     False          1567      1567           1.0

================================================================================
KEYSTRA — AUDIT CONCLUSION
================================================================================

Current failure rate: 93.85%

⚠️ CURRENT FAILURE DEFINITION IS TOO BROAD FOR THE PREDICTIVE OBJECTIVE.
The next step should be to redesign the business-defined FAILURE STATE.

IMPORTANT:
No existing Phase 1 or Phase 2 object has been modified.
No modelling dataset has been changed.
No target has been rebuilt yet.

================================================================================
✓ STEP 1 AUDIT COMPLETED
================================================================================

In [14]:
print("=" * 80)
print("KEYSTRA — PHASE 2 SCHEMA CHECK")
print("=" * 80)

print("Object:", type(fact_supplier_risk_phase1).__name__)
print("Rows:", len(fact_supplier_risk_phase1))
print("Columns:", len(fact_supplier_risk_phase1.columns))

print("\nCOLUMNS:")
for i, col in enumerate(fact_supplier_risk_phase1.columns, 1):
    print(f"{i:02d}. {col}")

print("\nDTYPES:")
print(fact_supplier_risk_phase1.dtypes)

================================================================================
KEYSTRA — PHASE 2 SCHEMA CHECK
================================================================================
Object: DataFrame
Rows: 150570
Columns: 32

COLUMNS:
01. Supplier_ID
02. Observation_Date
03. PO_Count
04. Ordered_Quantity
05. Received_Quantity
06. Outstanding_Quantity
07. Fulfilled_PO_Count
08. Partial_Fulfilment_Count
09. Outstanding_PO_Count
10. Delivered_PO_Count
11. Late_Delivery_Count
12. Historical_Fulfilment_Rate
13. Historical_Partial_Fulfilment_Rate
14. Rolling_90D_PO_Count
15. Rolling_90D_Ordered_Quantity
16. Rolling_90D_Received_Quantity
17. Rolling_90D_Outstanding_Quantity
18. Rolling_90D_Fulfilled_PO_Count
19. Rolling_90D_Partial_Fulfilment_Count
20. Rolling_90D_Delivered_PO_Count
21. Rolling_90D_Late_Delivery_Count
22. Recent_90D_Fulfilment_Rate
23. Recent_90D_Partial_Fulfilment_Rate
24. Recent_90D_Late_Delivery_Rate
25. Recent_90D_Outstanding_Rate
26. Recent_90D_Average_Delivery_Delay
27. Current_Outstanding_Quantity
28. Fulfilment_Risk_Signal
29. Late_Delivery_Risk_Signal
30. Partial_Fulfilment_Risk_Signal
31. Outstanding_Risk_Signal
32. Supplier_Behaviour_State

DTYPES:
Supplier_ID                                     object
Observation_Date                        datetime64[ns]
PO_Count                                       float64
Ordered_Quantity                               float64
Received_Quantity                              float64
Outstanding_Quantity                           float64
Fulfilled_PO_Count                             float64
Partial_Fulfilment_Count                       float64
Outstanding_PO_Count                           float64
Delivered_PO_Count                             float64
Late_Delivery_Count                            float64
Historical_Fulfilment_Rate                     float64
Historical_Partial_Fulfilment_Rate             float64
Rolling_90D_PO_Count                           float64
Rolling_90D_Ordered_Quantity                   float64
Rolling_90D_Received_Quantity                  float64
Rolling_90D_Outstanding_Quantity               float64
Rolling_90D_Fulfilled_PO_Count                 float64
Rolling_90D_Partial_Fulfilment_Count           float64
Rolling_90D_Delivered_PO_Count                 float64
Rolling_90D_Late_Delivery_Count                float64
Recent_90D_Fulfilment_Rate                     float64
Recent_90D_Partial_Fulfilment_Rate             float64
Recent_90D_Late_Delivery_Rate                  float64
Recent_90D_Outstanding_Rate                    float64
Recent_90D_Average_Delivery_Delay              float64
Current_Outstanding_Quantity                   float64
Fulfilment_Risk_Signal                         float64
Late_Delivery_Risk_Signal                      float64
Partial_Fulfilment_Risk_Signal                 float64
Outstanding_Risk_Signal                        float64
Supplier_Behaviour_State                        object
dtype: object

In [15]:
# ================================================================================
# KEYSTRA — SUPPLIER FAILURE OUTCOME ENGINE
# PHASE 3 — FUTURE SUPPLIER FAILURE DEFINITION
# ================================================================================
#
# PURPOSE
# -------
# Build a forward-looking supplier failure outcome WITHOUT using Phase 4
# risk states or any future-derived information as predictors.
#
# Phase 2 = CURRENT supplier behaviour
# Phase 3 = FUTURE supplier failure outcome
# Phase 4 = CURRENT staged risk-state engine
# Phase 5 = predictive feature engineering + modelling
#
# IMPORTANT BUSINESS LOGIC
# ------------------------
# A supplier does NOT fail simply because one metric becomes poor.
#
# A future supplier failure requires:
#   1. A sufficiently observed future window
#   2. Material deterioration in operational performance
#   3. Evidence across MULTIPLE operational dimensions
#   4. Sustained/recurring failure behaviour
#
# This prevents the old 93.85% failure-rate problem.
# ================================================================================

import pandas as pd
import numpy as np


# ================================================================================
# 0. IDENTIFY PHASE 2 OBJECT
# ================================================================================

if "fact_supplier_risk_phase2" in globals():
    phase2 = fact_supplier_risk_phase2.copy()

elif "fact_supplier_behaviour_phase2" in globals():
    phase2 = fact_supplier_behaviour_phase2.copy()

elif "fact_supplier_risk_phase1" in globals():
    phase2 = fact_supplier_risk_phase1.copy()

elif "df" in globals():
    phase2 = df.copy()

else:
    raise NameError(
        "No Phase 2 supplier object was found. "
        "Expected fact_supplier_risk_phase2, "
        "fact_supplier_behaviour_phase2, "
        "fact_supplier_risk_phase1, or df."
    )


# ================================================================================
# 1. STANDARDISE INPUT
# ================================================================================

phase2["Observation_Date"] = pd.to_datetime(
    phase2["Observation_Date"],
    errors="coerce"
)

phase2 = phase2.sort_values(
    ["Supplier_ID", "Observation_Date"]
).reset_index(drop=True)


# ================================================================================
# 2. REQUIRED COLUMNS
# ================================================================================

required_columns = [
    "Supplier_ID",
    "Observation_Date",
    "PO_Count",
    "Ordered_Quantity",
    "Received_Quantity",
    "Outstanding_Quantity",
    "Fulfilled_PO_Count",
    "Partial_Fulfilment_Count",
    "Outstanding_PO_Count",
    "Delivered_PO_Count",
    "Late_Delivery_Count",
    "Recent_90D_Fulfilment_Rate",
    "Recent_90D_Partial_Fulfilment_Rate",
    "Recent_90D_Late_Delivery_Rate",
    "Recent_90D_Outstanding_Rate"
]

missing = [
    col for col in required_columns
    if col not in phase2.columns
]

if missing:
    raise ValueError(
        f"Phase 2 is missing required columns: {missing}"
    )


print("=" * 80)
print("KEYSTRA — SUPPLIER FAILURE OUTCOME ENGINE")
print("PHASE 3 — FUTURE SUPPLIER FAILURE DEFINITION")
print("=" * 80)

print()
print(f"✓ Phase 2 object detected")
print(f"  Rows    : {len(phase2):,}")
print(f"  Columns : {phase2.shape[1]}")

print()
print("✓ REQUIRED PHASE 2 COLUMNS VALID")


# ================================================================================
# 3. VALIDATE SUPPLIER × DATE GRAIN
# ================================================================================

duplicate_count = phase2.duplicated(
    ["Supplier_ID", "Observation_Date"]
).sum()

if duplicate_count > 0:
    raise ValueError(
        f"Supplier × Date grain is not unique. "
        f"Duplicate rows: {duplicate_count:,}"
    )

print("✓ Supplier × Date grain valid")

if phase2["Observation_Date"].isna().any():
    raise ValueError(
        "Observation_Date contains invalid/missing dates."
    )

print("✓ Observation dates valid")


# ================================================================================
# 4. FUTURE OUTCOME PARAMETERS
# ================================================================================

FUTURE_WINDOW_DAYS = 90

# Minimum number of future active observations required.
#
# This prevents suppliers with only one or two future transactions
# from being labelled as failed.
MIN_ACTIVE_DAYS = 15

# Minimum recurring failure days inside the future window.
#
# Failure should represent a sustained/recurring condition,
# not one isolated bad day.
MIN_FAILURE_DAYS = 10

# Minimum proportion of observed future active days that must show
# the failure condition.
MIN_FAILURE_SHARE = 0.20


# ================================================================================
# 5. BUILD DAILY OPERATIONAL FAILURE SIGNALS
# ================================================================================
#
# We deliberately use operational measures from Phase 2.
#
# We DO NOT use:
#   Supplier_Behaviour_State
#   any Phase 4 risk state
#   any future risk-state variable
#
# The future outcome must be independently constructed.
# ================================================================================

future_base = phase2[
    [
        "Supplier_ID",
        "Observation_Date",
        "PO_Count",
        "Ordered_Quantity",
        "Received_Quantity",
        "Outstanding_Quantity",
        "Fulfilled_PO_Count",
        "Partial_Fulfilment_Count",
        "Outstanding_PO_Count",
        "Delivered_PO_Count",
        "Late_Delivery_Count"
    ]
].copy()


# ================================================================================
# 6. DAILY OPERATIONAL RATES
# ================================================================================

future_base["Daily_Fulfilment_Rate"] = np.where(
    future_base["PO_Count"] > 0,
    future_base["Fulfilled_PO_Count"] /
    future_base["PO_Count"],
    np.nan
)

future_base["Daily_Partial_Fulfilment_Rate"] = np.where(
    future_base["PO_Count"] > 0,
    future_base["Partial_Fulfilment_Count"] /
    future_base["PO_Count"],
    np.nan
)

future_base["Daily_Late_Delivery_Rate"] = np.where(
    future_base["Delivered_PO_Count"] > 0,
    future_base["Late_Delivery_Count"] /
    future_base["Delivered_PO_Count"],
    np.nan
)

future_base["Daily_Outstanding_Rate"] = np.where(
    future_base["PO_Count"] > 0,
    future_base["Outstanding_PO_Count"] /
    future_base["PO_Count"],
    np.nan
)


# ================================================================================
# 7. DEFINE SEVERE FUTURE OPERATIONAL CONDITIONS
# ================================================================================
#
# These thresholds are intentionally stricter than ordinary "risk" thresholds.
#
# FAILURE COMPONENT 1
# -------------------
# Fulfilment failure:
# future fulfilment performance <= 70%
#
# FAILURE COMPONENT 2
# -------------------
# Late-delivery failure:
# late-delivery rate >= 30%
#
# FAILURE COMPONENT 3
# -------------------
# Outstanding failure:
# outstanding PO rate >= 40%
#
# FAILURE COMPONENT 4
# -------------------
# Partial fulfilment failure:
# partial fulfilment rate >= 30%
#
# These are NOT enough individually to declare supplier failure.
# At least TWO dimensions must be materially impaired.
# ================================================================================

future_base["Material_Fulfilment_Failure"] = (
    future_base["Daily_Fulfilment_Rate"] <= 0.70
)

future_base["Material_Late_Delivery_Failure"] = (
    future_base["Daily_Late_Delivery_Rate"] >= 0.30
)

future_base["Material_Outstanding_Failure"] = (
    future_base["Daily_Outstanding_Rate"] >= 0.40
)

future_base["Material_Partial_Fulfilment_Failure"] = (
    future_base["Daily_Partial_Fulfilment_Rate"] >= 0.30
)


# ================================================================================
# 8. REMOVE DAYS WITH NO OPERATIONAL ACTIVITY
# ================================================================================
#
# A supplier cannot be judged as failing on a day where there was
# no meaningful supplier activity.
# ================================================================================

future_base["Active_Day"] = (
    future_base["PO_Count"].fillna(0) > 0
)


# ================================================================================
# 9. FUTURE WINDOW AGGREGATION
# ================================================================================
#
# For every Supplier × Observation_Date:
#
#   look forward 90 days
#   exclude the current observation date
#   calculate future operational failure behaviour
#
# This creates a genuine forward-looking target.
# ================================================================================

dates = phase2[
    ["Supplier_ID", "Observation_Date"]
].drop_duplicates().copy()

dates["Future_Start"] = (
    dates["Observation_Date"] +
    pd.Timedelta(days=1)
)

dates["Future_End"] = (
    dates["Observation_Date"] +
    pd.Timedelta(days=FUTURE_WINDOW_DAYS)
)


# ================================================================================
# 10. EFFICIENT FUTURE WINDOW CALCULATION
# ================================================================================

# Create integer representations for faster comparison.

future_base = future_base.sort_values(
    ["Supplier_ID", "Observation_Date"]
).reset_index(drop=True)

dates = dates.sort_values(
    ["Supplier_ID", "Observation_Date"]
).reset_index(drop=True)


# ------------------------------------------------------------------------------
# Use merge_asof to attach the future window start/end boundaries.
# ------------------------------------------------------------------------------

# Instead of generating a huge Cartesian product, calculate future
# rolling observations using reversed rolling windows.

metric_columns = [
    "Active_Day",
    "Material_Fulfilment_Failure",
    "Material_Late_Delivery_Failure",
    "Material_Outstanding_Failure",
    "Material_Partial_Fulfilment_Failure"
]

for col in metric_columns:
    future_base[col] = future_base[col].astype(int)


# ================================================================================
# 11. FUTURE 90-DAY ROLLING COUNTS
# ================================================================================
#
# The rolling window is shifted by one day so that the current day
# NEVER contributes to its own future outcome.
# ================================================================================

future_roll = future_base.copy()

future_roll = future_roll.set_index(
    "Observation_Date"
)

grouped = future_roll.groupby("Supplier_ID", sort=False)


for col in metric_columns:

    rolling_values = (
        grouped[col]
        .rolling(
            f"{FUTURE_WINDOW_DAYS + 1}D",
            closed="right"
        )
        .sum()
        .reset_index(level=0, drop=True)
    )

    future_roll[f"_rolling_{col}"] = rolling_values


# The rolling window above includes the current day.
# Shift by one observation so the current date is excluded.

for col in metric_columns:

    future_roll[f"_future_{col}_count"] = (
        future_roll
        .groupby("Supplier_ID")[f"_rolling_{col}"]
        .shift(-1)
    )


future_roll = future_roll.reset_index()


# ================================================================================
# 12. FUTURE ACTIVE-DAY COUNT
# ================================================================================

future_roll["Future_Active_Days"] = (
    future_roll["_future_Active_Day_count"]
)


# ================================================================================
# 13. CONVERT COUNTS TO FUTURE FAILURE SHARES
# ================================================================================

future_roll["Future_Fulfilment_Failure_Share"] = np.where(
    future_roll["Future_Active_Days"] > 0,
    future_roll["_future_Material_Fulfilment_Failure_count"] /
    future_roll["Future_Active_Days"],
    np.nan
)

future_roll["Future_Late_Delivery_Failure_Share"] = np.where(
    future_roll["Future_Active_Days"] > 0,
    future_roll["_future_Material_Late_Delivery_Failure_count"] /
    future_roll["Future_Active_Days"],
    np.nan
)

future_roll["Future_Outstanding_Failure_Share"] = np.where(
    future_roll["Future_Active_Days"] > 0,
    future_roll["_future_Material_Outstanding_Failure_count"] /
    future_roll["Future_Active_Days"],
    np.nan
)

future_roll["Future_Partial_Fulfilment_Failure_Share"] = np.where(
    future_roll["Future_Active_Days"] > 0,
    future_roll["_future_Material_Partial_Fulfilment_Failure_count"] /
    future_roll["Future_Active_Days"],
    np.nan
)


# ================================================================================
# 14. CONVERT FUTURE SHARES INTO FUTURE FAILURE COMPONENTS
# ================================================================================
#
# A component is considered a genuine future failure only when:
#
#   - at least MIN_FAILURE_DAYS show the severe condition
#   - AND those days represent at least MIN_FAILURE_SHARE of
#     active future days
#
# This is what prevents one-off bad transactions from creating labels.
# ================================================================================

future_roll["Future_Fulfilment_Failure"] = (
    (future_roll["_future_Material_Fulfilment_Failure_count"]
     >= MIN_FAILURE_DAYS)
    &
    (future_roll["Future_Fulfilment_Failure_Share"]
     >= MIN_FAILURE_SHARE)
)

future_roll["Future_Late_Delivery_Failure"] = (
    (future_roll["_future_Material_Late_Delivery_Failure_count"]
     >= MIN_FAILURE_DAYS)
    &
    (future_roll["Future_Late_Delivery_Failure_Share"]
     >= MIN_FAILURE_SHARE)
)

future_roll["Future_Outstanding_Failure"] = (
    (future_roll["_future_Material_Outstanding_Failure_count"]
     >= MIN_FAILURE_DAYS)
    &
    (future_roll["Future_Outstanding_Failure_Share"]
     >= MIN_FAILURE_SHARE)
)

future_roll["Future_Partial_Fulfilment_Failure"] = (
    (future_roll["_future_Material_Partial_Fulfilment_Failure_count"]
     >= MIN_FAILURE_DAYS)
    &
    (future_roll["Future_Partial_Fulfilment_Failure_Share"]
     >= MIN_FAILURE_SHARE)
)


# ================================================================================
# 15. COUNT FAILURE DIMENSIONS
# ================================================================================

failure_component_columns = [
    "Future_Fulfilment_Failure",
    "Future_Late_Delivery_Failure",
    "Future_Outstanding_Failure",
    "Future_Partial_Fulfilment_Failure"
]

future_roll["Future_Failure_Dimension_Count"] = (
    future_roll[failure_component_columns]
    .sum(axis=1)
)


# ================================================================================
# 16. DEFINE SUPPLIER FAILURE
# ================================================================================
#
# IMPORTANT:
#
# Failure requires:
#
#   A. enough future operational observations
#   B. at least TWO independent failure dimensions
#
# This is the key correction to the previous 93.85% target.
#
# A supplier with only fulfilment problems is NOT automatically a failure.
# A supplier with only late delivery problems is NOT automatically a failure.
# A supplier must demonstrate a broader operational breakdown.
# ================================================================================

future_roll["Supplier_Failure_Label"] = (
    (
        future_roll["Future_Active_Days"]
        >= MIN_ACTIVE_DAYS
    )
    &
    (
        future_roll["Future_Failure_Dimension_Count"]
        >= 2
    )
).astype("Int64")


# ================================================================================
# 17. HANDLE INCOMPLETE FUTURE WINDOWS
# ================================================================================
#
# If the supplier does not have enough future history, the target is unknown.
# We DO NOT call it "No Failure".
#
# This is critical for avoiding artificial negative labels near the
# end of the dataset.
# ================================================================================

future_roll["Future_Window_Complete"] = (
    future_roll["Future_Active_Days"]
    >= MIN_ACTIVE_DAYS
)

future_roll.loc[
    ~future_roll["Future_Window_Complete"],
    "Supplier_Failure_Label"
] = pd.NA


# ================================================================================
# 18. SELECT FINAL PHASE 3 OBJECT
# ================================================================================

phase3_columns = [
    "Supplier_ID",
    "Observation_Date",

    "Future_Active_Days",

    "_future_Material_Fulfilment_Failure_count",
    "_future_Material_Late_Delivery_Failure_count",
    "_future_Material_Outstanding_Failure_count",
    "_future_Material_Partial_Fulfilment_Failure_count",

    "Future_Fulfilment_Failure_Share",
    "Future_Late_Delivery_Failure_Share",
    "Future_Outstanding_Failure_Share",
    "Future_Partial_Fulfilment_Failure_Share",

    "Future_Fulfilment_Failure",
    "Future_Late_Delivery_Failure",
    "Future_Outstanding_Failure",
    "Future_Partial_Fulfilment_Failure",

    "Future_Failure_Dimension_Count",
    "Future_Window_Complete",
    "Supplier_Failure_Label"
]

fact_supplier_failure_outcome = future_roll[
    phase3_columns
].copy()


# ================================================================================
# 19. RENAME INTERNAL COUNT COLUMNS
# ================================================================================

fact_supplier_failure_outcome = (
    fact_supplier_failure_outcome.rename(
        columns={
            "_future_Material_Fulfilment_Failure_count":
                "Future_Fulfilment_Failure_Days",

            "_future_Material_Late_Delivery_Failure_count":
                "Future_Late_Delivery_Failure_Days",

            "_future_Material_Outstanding_Failure_count":
                "Future_Outstanding_Failure_Days",

            "_future_Material_Partial_Fulfilment_Failure_count":
                "Future_Partial_Fulfilment_Failure_Days"
        }
    )
)


# ================================================================================
# 20. FINAL GRAIN VALIDATION
# ================================================================================

duplicate_final = fact_supplier_failure_outcome.duplicated(
    ["Supplier_ID", "Observation_Date"]
).sum()

if duplicate_final > 0:
    raise ValueError(
        f"Phase 3 grain failure: {duplicate_final:,} duplicate "
        "Supplier × Date observations."
    )


# ================================================================================
# 21. VALIDATION REPORT
# ================================================================================

print()
print("=" * 80)
print("PHASE 3 — FUTURE OUTCOME VALIDATION")
print("=" * 80)

print()
print("ROWS / GRAIN")
print("-" * 80)

print(
    f"Rows                         : "
    f"{len(fact_supplier_failure_outcome):,}"
)

print(
    f"Suppliers                    : "
    f"{fact_supplier_failure_outcome['Supplier_ID'].nunique():,}"
)

print(
    f"Supplier × Date grain unique : "
    f"{duplicate_final == 0}"
)


# ================================================================================
# 22. FUTURE WINDOW COMPLETENESS
# ================================================================================

print()
print("FUTURE WINDOW COVERAGE")
print("-" * 80)

complete_count = (
    fact_supplier_failure_outcome["Future_Window_Complete"]
    .sum()
)

incomplete_count = (
    (~fact_supplier_failure_outcome["Future_Window_Complete"])
    .sum()
)

print(
    f"Complete future windows       : "
    f"{complete_count:,}"
)

print(
    f"Incomplete future windows     : "
    f"{incomplete_count:,}"
)


# ================================================================================
# 23. FAILURE LABEL DISTRIBUTION
# ================================================================================

labelable = fact_supplier_failure_outcome[
    fact_supplier_failure_outcome["Supplier_Failure_Label"]
    .notna()
].copy()

print()
print("SUPPLIER FAILURE LABEL")
print("-" * 80)

label_distribution = (
    labelable["Supplier_Failure_Label"]
    .value_counts()
    .sort_index()
)

print(label_distribution)

if len(labelable) > 0:

    failure_rate = (
        labelable["Supplier_Failure_Label"].mean()
        * 100
    )

    print()
    print(
        f"Failure rate                 : "
        f"{failure_rate:.2f}%"
    )


# ================================================================================
# 24. FAILURE COMPONENT PRESSURE
# ================================================================================

print()
print("FAILURE COMPONENT PRESSURE")
print("-" * 80)

component_summary = []

component_map = {
    "Fulfilment_Failure":
        "Future_Fulfilment_Failure",

    "Late_Delivery_Failure":
        "Future_Late_Delivery_Failure",

    "Outstanding_Failure":
        "Future_Outstanding_Failure",

    "Partial_Fulfilment_Failure":
        "Future_Partial_Fulfilment_Failure"
}

for name, column in component_map.items():

    total_events = int(
        fact_supplier_failure_outcome[column]
        .sum()
    )

    rows_with_event = int(
        fact_supplier_failure_outcome[column]
        .sum()
    )

    share = (
        rows_with_event / len(labelable)
        if len(labelable) > 0
        else 0
    )

    component_summary.append({
        "Failure_Component": name,
        "Rows_With_Event": rows_with_event,
        "Share_of_Labelable_Rows": round(share, 4)
    })

component_summary_df = pd.DataFrame(component_summary)

print(component_summary_df.to_string(index=False))


# ================================================================================
# 25. FAILURE DIMENSION DISTRIBUTION
# ================================================================================

print()
print("FAILURE DIMENSIONS PER OBSERVATION")
print("-" * 80)

dimension_distribution = (
    labelable["Future_Failure_Dimension_Count"]
    .value_counts()
    .sort_index()
)

print(dimension_distribution)


# ================================================================================
# 26. VERIFY NO ONE-DIMENSION FAILURE LABELS
# ================================================================================

one_dimension_failures = (
    labelable[
        (labelable["Supplier_Failure_Label"] == 1)
        &
        (labelable["Future_Failure_Dimension_Count"] < 2)
    ]
)

print()
print("FAILURE DEFINITION CHECK")
print("-" * 80)

print(
    f"Failure observations with <2 dimensions : "
    f"{len(one_dimension_failures):,}"
)

if len(one_dimension_failures) == 0:
    print(
        "✓ Every failure requires at least two "
        "independent operational dimensions"
    )
else:
    raise ValueError(
        "Failure definition violated: "
        "one-dimensional failures detected."
    )


# ================================================================================
# 27. SHOW FAILURE COMPONENT COMBINATIONS
# ================================================================================

combo_columns = [
    "Future_Fulfilment_Failure",
    "Future_Late_Delivery_Failure",
    "Future_Outstanding_Failure",
    "Future_Partial_Fulfilment_Failure"
]

combo_summary = (
    labelable
    .groupby(combo_columns, dropna=False)
    .agg(
        Observations=(
            "Supplier_ID",
            "size"
        ),
        Failures=(
            "Supplier_Failure_Label",
            "sum"
        )
    )
    .reset_index()
)

combo_summary["Failure_Rate"] = (
    combo_summary["Failures"] /
    combo_summary["Observations"]
)

combo_summary = combo_summary.sort_values(
    "Observations",
    ascending=False
)

print()
print("MOST COMMON FUTURE FAILURE COMBINATIONS")
print("-" * 80)

print(
    combo_summary.head(10).to_string(index=False)
)


# ================================================================================
# 28. SUPPLIER-LEVEL FAILURE RATE
# ================================================================================

supplier_failure_rate = (
    labelable
    .groupby("Supplier_ID")["Supplier_Failure_Label"]
    .mean()
    .sort_values(ascending=False)
)

print()
print("SUPPLIER-LEVEL FAILURE RATE")
print("-" * 80)

print(
    supplier_failure_rate.describe()
)


# ================================================================================
# 29. CRITICAL SANITY CHECK
# ================================================================================

failure_rate_final = (
    labelable["Supplier_Failure_Label"].mean()
    if len(labelable) > 0
    else 0
)

print()
print("=" * 80)
print("KEYSTRA — PHASE 3 OUTCOME AUDIT")
print("=" * 80)

print()
print(
    f"Final failure rate : "
    f"{failure_rate_final * 100:.2f}%"
)

if failure_rate_final >= 0.80:

    print()
    print(
        "⚠️ FAILURE RATE IS STILL VERY HIGH."
    )

    print(
        "The target may still be too broad and "
        "requires business-threshold review before modelling."
    )

elif failure_rate_final >= 0.50:

    print()
    print(
        "⚠️ FAILURE RATE REMAINS HIGH."
    )

    print(
        "Review the component thresholds before Phase 4."
    )

elif failure_rate_final <= 0.05:

    print()
    print(
        "⚠️ FAILURE RATE IS VERY LOW."
    )

    print(
        "The definition may be overly restrictive."
    )

else:

    print()
    print(
        "✓ FAILURE RATE IS WITHIN A PLAUSIBLE "
        "MODELLING RANGE."
    )


# ================================================================================
# 30. FINAL OBJECT SUMMARY
# ================================================================================

print()
print("=" * 80)
print("PHASE 3 FINAL OBJECT")
print("=" * 80)

print()
print(
    f"fact_supplier_failure_outcome rows    : "
    f"{len(fact_supplier_failure_outcome):,}"
)

print(
    f"fact_supplier_failure_outcome columns : "
    f"{fact_supplier_failure_outcome.shape[1]}"
)

print()
print("✓ FUTURE 90-DAY OUTCOME WINDOW CREATED")
print("✓ INCOMPLETE FUTURE WINDOWS EXCLUDED")
print("✓ FUTURE OPERATIONAL FAILURE COMPONENTS CREATED")
print("✓ FAILURE REQUIRES RECURRING FAILURE BEHAVIOUR")
print("✓ FAILURE REQUIRES MULTIPLE OPERATIONAL DIMENSIONS")
print("✓ CURRENT-DAY INFORMATION KEPT SEPARATE FROM FUTURE OUTCOME")
print("✓ NO PHASE 4 RISK STATE USED")
print("✓ SUPPLIER × DATE GRAIN PRESERVED")
print("✓ TARGET IS FORWARD-LOOKING")

print()
print("=" * 80)
print("✓ PHASE 3 — SUPPLIER FAILURE OUTCOME ENGINE COMPLETED")
print("=" * 80)

print()
print("Output object:")
print("  fact_supplier_failure_outcome")

print()
print("Next stage:")
print("  Phase 4 — Staged Supplier Risk-State Engine")

print("=" * 80)

================================================================================
KEYSTRA — SUPPLIER FAILURE OUTCOME ENGINE
PHASE 3 — FUTURE SUPPLIER FAILURE DEFINITION
================================================================================

✓ Phase 2 object detected
  Rows    : 150,570
  Columns : 32

✓ REQUIRED PHASE 2 COLUMNS VALID
✓ Supplier × Date grain valid
✓ Observation dates valid

================================================================================
PHASE 3 — FUTURE OUTCOME VALIDATION
================================================================================

ROWS / GRAIN
--------------------------------------------------------------------------------
Rows                         : 150,570
Suppliers                    : 90
Supplier × Date grain unique : True

FUTURE WINDOW COVERAGE
--------------------------------------------------------------------------------
Complete future windows       : 138,953
Incomplete future windows     : 11,617

SUPPLIER FAILURE LABEL
--------------------------------------------------------------------------------
Supplier_Failure_Label
0    128129
1     10824
Name: count, dtype: Int64

Failure rate                 : 7.79%

FAILURE COMPONENT PRESSURE
--------------------------------------------------------------------------------
         Failure_Component  Rows_With_Event  Share_of_Labelable_Rows
        Fulfilment_Failure            11164                   0.0803
     Late_Delivery_Failure             4196                   0.0302
       Outstanding_Failure            10796                   0.0777
Partial_Fulfilment_Failure             1872                   0.0135

FAILURE DIMENSIONS PER OBSERVATION
--------------------------------------------------------------------------------
Future_Failure_Dimension_Count
0    125962
1      2167
2      7602
3      2693
4       529
Name: count, dtype: int64

FAILURE DEFINITION CHECK
--------------------------------------------------------------------------------
Failure observations with <2 dimensions : 0
✓ Every failure requires at least two independent operational dimensions

MOST COMMON FUTURE FAILURE COMBINATIONS
--------------------------------------------------------------------------------
 Future_Fulfilment_Failure  Future_Late_Delivery_Failure  Future_Outstanding_Failure  Future_Partial_Fulfilment_Failure  Observations  Failures  Failure_Rate
                     False                         False                       False                              False        125962         0           0.0
                      True                         False                        True                              False          7452      7452           1.0
                     False                          True                       False                              False          1954         0           0.0
                      True                          True                        True                              False          1405      1405           1.0
                      True                         False                        True                               True          1283      1283           1.0
                      True                          True                        True                               True           529       529           1.0
                      True                         False                       False                              False           213         0           0.0
                      True                          True                       False                              False            98        98           1.0
                      True                         False                       False                               True            52        52           1.0
                      True                          True                       False                               True             5         5           1.0

SUPPLIER-LEVEL FAILURE RATE
--------------------------------------------------------------------------------
count        90.0
mean     0.077787
std      0.093904
min           0.0
25%      0.018441
50%      0.037661
75%      0.109225
max      0.457196
Name: Supplier_Failure_Label, dtype: Float64

================================================================================
KEYSTRA — PHASE 3 OUTCOME AUDIT
================================================================================

Final failure rate : 7.79%

✓ FAILURE RATE IS WITHIN A PLAUSIBLE MODELLING RANGE.

================================================================================
PHASE 3 FINAL OBJECT
================================================================================

fact_supplier_failure_outcome rows    : 150,570
fact_supplier_failure_outcome columns : 18

✓ FUTURE 90-DAY OUTCOME WINDOW CREATED
✓ INCOMPLETE FUTURE WINDOWS EXCLUDED
✓ FUTURE OPERATIONAL FAILURE COMPONENTS CREATED
✓ FAILURE REQUIRES RECURRING FAILURE BEHAVIOUR
✓ FAILURE REQUIRES MULTIPLE OPERATIONAL DIMENSIONS
✓ CURRENT-DAY INFORMATION KEPT SEPARATE FROM FUTURE OUTCOME
✓ NO PHASE 4 RISK STATE USED
✓ SUPPLIER × DATE GRAIN PRESERVED
✓ TARGET IS FORWARD-LOOKING

================================================================================
✓ PHASE 3 — SUPPLIER FAILURE OUTCOME ENGINE COMPLETED
================================================================================

Output object:
  fact_supplier_failure_outcome

Next stage:
  Phase 4 — Staged Supplier Risk-State Engine
================================================================================

In [16]:
  # ================================================================================
# KEYSTRA — SUPPLIER RISK-STATE ENGINE
# PHASE 4 — STAGED SUPPLIER DETERIORATION FRAMEWORK
# ================================================================================
#
# PURPOSE
# -------
# Build a causally ordered supplier risk-state engine:
#
# Stable → Watch → Deteriorating → High Risk → Failure
#
# IMPORTANT DESIGN RULES
# ----------------------
# 1. Uses ONLY Phase 1/current-and-past information.
# 2. Does NOT use Phase 3 future failure outcome.
# 3. Failure requires multiple operational dimensions.
# 4. Failure requires persistent deterioration.
# 5. Failure must come through High Risk.
# 6. Stable/Watch cannot jump directly to High Risk or Failure.
# 7. Deteriorating → High Risk requires severe evidence.
# 8. High Risk → Failure requires stronger evidence.
# 9. Recovery is allowed.
# 10. Supplier × Date grain is preserved.
#
# OUTPUT
# ------
# fact_supplier_risk_state
# ================================================================================


import pandas as pd
import numpy as np


# ================================================================================
# 1. HEADER
# ================================================================================

print("=" * 80)
print("KEYSTRA — SUPPLIER RISK-STATE ENGINE")
print("PHASE 4 — STAGED SUPPLIER DETERIORATION FRAMEWORK")
print("=" * 80)


# ================================================================================
# 2. DETECT PHASE 1 OBJECT
# ================================================================================

if "fact_supplier_risk_phase1" not in globals():
    raise NameError(
        "fact_supplier_risk_phase1 was not found. "
        "Run the Phase 1 supplier risk foundation first."
    )

df = fact_supplier_risk_phase1.copy()

print()
print("✓ Base supplier object detected : fact_supplier_risk_phase1")
print(f"  Rows    : {len(df):,}")
print(f"  Columns : {len(df.columns)}")


# ================================================================================
# 3. REQUIRED PHASE 1 COLUMNS
# ================================================================================

required_cols = [
    "Supplier_ID",
    "Observation_Date",

    "PO_Count",
    "Ordered_Quantity",
    "Received_Quantity",
    "Outstanding_Quantity",

    "Fulfilled_PO_Count",
    "Partial_Fulfilment_Count",
    "Outstanding_PO_Count",
    "Delivered_PO_Count",
    "Late_Delivery_Count",

    "Historical_Fulfilment_Rate",
    "Historical_Partial_Fulfilment_Rate",

    "Rolling_90D_PO_Count",
    "Rolling_90D_Ordered_Quantity",
    "Rolling_90D_Received_Quantity",
    "Rolling_90D_Outstanding_Quantity",

    "Rolling_90D_Fulfilled_PO_Count",
    "Rolling_90D_Partial_Fulfilment_Count",
    "Rolling_90D_Delivered_PO_Count",
    "Rolling_90D_Late_Delivery_Count",

    "Recent_90D_Fulfilment_Rate",
    "Recent_90D_Partial_Fulfilment_Rate",
    "Recent_90D_Late_Delivery_Rate",
    "Recent_90D_Outstanding_Rate",
    "Recent_90D_Average_Delivery_Delay",

    "Current_Outstanding_Quantity",

    "Fulfilment_Risk_Signal",
    "Late_Delivery_Risk_Signal",
    "Partial_Fulfilment_Risk_Signal",
    "Outstanding_Risk_Signal",

    "Supplier_Behaviour_State"
]

missing = [c for c in required_cols if c not in df.columns]

if missing:
    raise ValueError(
        "Missing required Phase 1 columns:\n"
        + "\n".join(f" - {c}" for c in missing)
    )

print()
print("✓ REQUIRED PHASE 1 COLUMNS VALID")


# ================================================================================
# 4. DATA TYPES / GRAIN VALIDATION
# ================================================================================

df["Observation_Date"] = pd.to_datetime(
    df["Observation_Date"],
    errors="coerce"
)

if df["Observation_Date"].isna().any():
    raise ValueError("Observation_Date contains invalid dates.")

grain_duplicates = df.duplicated(
    subset=["Supplier_ID", "Observation_Date"]
).sum()

if grain_duplicates > 0:
    raise ValueError(
        f"Supplier × Date grain violated: {grain_duplicates:,} duplicates found."
    )

df = df.sort_values(
    ["Supplier_ID", "Observation_Date"]
).reset_index(drop=True)

print("✓ Supplier × Date grain valid")
print("✓ Observation dates valid")


# ================================================================================
# 5. NUMERIC CLEANING
# ================================================================================

numeric_cols = [
    "PO_Count",
    "Ordered_Quantity",
    "Received_Quantity",
    "Outstanding_Quantity",
    "Fulfilled_PO_Count",
    "Partial_Fulfilment_Count",
    "Outstanding_PO_Count",
    "Delivered_PO_Count",
    "Late_Delivery_Count",

    "Historical_Fulfilment_Rate",
    "Historical_Partial_Fulfilment_Rate",

    "Rolling_90D_PO_Count",
    "Rolling_90D_Ordered_Quantity",
    "Rolling_90D_Received_Quantity",
    "Rolling_90D_Outstanding_Quantity",
    "Rolling_90D_Fulfilled_PO_Count",
    "Rolling_90D_Partial_Fulfilment_Count",
    "Rolling_90D_Delivered_PO_Count",
    "Rolling_90D_Late_Delivery_Count",

    "Recent_90D_Fulfilment_Rate",
    "Recent_90D_Partial_Fulfilment_Rate",
    "Recent_90D_Late_Delivery_Rate",
    "Recent_90D_Outstanding_Rate",
    "Recent_90D_Average_Delivery_Delay",

    "Current_Outstanding_Quantity",

    "Fulfilment_Risk_Signal",
    "Late_Delivery_Risk_Signal",
    "Partial_Fulfilment_Risk_Signal",
    "Outstanding_Risk_Signal"
]

for col in numeric_cols:
    df[col] = pd.to_numeric(
        df[col],
        errors="coerce"
    )


# ================================================================================
# 6. BUILD TRUE HISTORICAL BASELINES
# ================================================================================
#
# Phase 1 does NOT contain:
#   Historical_Late_Delivery_Rate
#   Historical_Outstanding_Rate
#
# We therefore calculate them from the cumulative operational counts.
#
# Late delivery baseline:
#   cumulative late deliveries / cumulative delivered POs
#
# Outstanding baseline:
#   cumulative outstanding POs / cumulative POs
#
# We DO NOT rename recent metrics as historical metrics.
# ================================================================================

df["Historical_Late_Delivery_Rate"] = (
    df["Late_Delivery_Count"] /
    df["Delivered_PO_Count"].replace(0, np.nan)
)

df["Historical_Outstanding_Rate"] = (
    df["Outstanding_PO_Count"] /
    df["PO_Count"].replace(0, np.nan)
)

# Keep rates within sensible boundaries
rate_cols = [
    "Historical_Fulfilment_Rate",
    "Historical_Partial_Fulfilment_Rate",
    "Historical_Late_Delivery_Rate",
    "Historical_Outstanding_Rate",
    "Recent_90D_Fulfilment_Rate",
    "Recent_90D_Partial_Fulfilment_Rate",
    "Recent_90D_Late_Delivery_Rate",
    "Recent_90D_Outstanding_Rate"
]

for col in rate_cols:
    df[col] = df[col].clip(lower=0, upper=1)

print()
print("✓ Historical baseline metrics created")
print("  - Historical fulfilment")
print("  - Historical partial fulfilment")
print("  - Historical late delivery")
print("  - Historical outstanding")


# ================================================================================
# 7. CURRENT PERFORMANCE VS HISTORICAL BASELINE
# ================================================================================

df["Fulfilment_Deviation"] = (
    df["Historical_Fulfilment_Rate"]
    - df["Recent_90D_Fulfilment_Rate"]
)

df["Partial_Fulfilment_Deviation"] = (
    df["Recent_90D_Partial_Fulfilment_Rate"]
    - df["Historical_Partial_Fulfilment_Rate"]
)

df["Late_Delivery_Deviation"] = (
    df["Recent_90D_Late_Delivery_Rate"]
    - df["Historical_Late_Delivery_Rate"]
)

df["Outstanding_Deviation"] = (
    df["Recent_90D_Outstanding_Rate"]
    - df["Historical_Outstanding_Rate"]
)


# ================================================================================
# 8. SHORT-TERM TRENDS
# ================================================================================
#
# Compare recent 30-day behaviour against recent 90-day behaviour.
# This detects acceleration/deceleration rather than simply measuring level.
# ================================================================================

for metric in [
    "Fulfilment_Rate",
    "Partial_Fulfilment_Rate",
    "Late_Delivery_Rate",
    "Outstanding_Rate"
]:

    recent_col = f"Recent_90D_{metric}"

    if metric == "Fulfilment_Rate":
        daily_col = "Fulfilled_PO_Count"
        denominator_col = "PO_Count"

    elif metric == "Partial_Fulfilment_Rate":
        daily_col = "Partial_Fulfilment_Count"
        denominator_col = "PO_Count"

    elif metric == "Late_Delivery_Rate":
        daily_col = "Late_Delivery_Count"
        denominator_col = "Delivered_PO_Count"

    else:
        daily_col = "Outstanding_PO_Count"
        denominator_col = "PO_Count"

    grouped = df.groupby("Supplier_ID", group_keys=False)

    rolling_30_num = grouped[daily_col].transform(
        lambda s: s.rolling(30, min_periods=1).sum()
    )

    rolling_30_den = grouped[denominator_col].transform(
        lambda s: s.rolling(30, min_periods=1).sum()
    )

    recent_30 = (
        rolling_30_num /
        rolling_30_den.replace(0, np.nan)
    )

    df[f"Recent_30D_{metric}"] = recent_30.clip(
        lower=0,
        upper=1
    )

    # Direction of deterioration:
    #
    # Fulfilment ↓ = deterioration
    # Everything else ↑ = deterioration
    if metric == "Fulfilment_Rate":

        df[f"{metric}_Trend"] = (
            df[f"Recent_30D_{metric}"]
            - df[recent_col]
        )

    else:

        df[f"{metric}_Trend"] = (
            df[f"Recent_30D_{metric}"]
            - df[recent_col]
        )


# ================================================================================
# 9. LONGER-TERM TREND / PERSISTENCE
# ================================================================================
#
# A supplier shouldn't become severe simply because of one noisy day.
#
# We therefore look for repeated deterioration signals over time.
# ================================================================================

grouped = df.groupby("Supplier_ID", group_keys=False)

df["Rolling_30D_Deterioration_Count"] = (
    grouped["Observation_Date"]
    .transform(lambda s: s.diff().dt.days.fillna(0).ge(0).astype(int))
)

# Create basic daily deterioration indicators first.


# Fulfilment deterioration
df["Fulfilment_Deteriorating"] = (
    (
        df["Recent_90D_Fulfilment_Rate"] < 0.85
    )
    |
    (
        df["Fulfilment_Deviation"] >= 0.10
    )
).fillna(False).astype(bool)


# Late delivery deterioration
df["Late_Delivery_Deteriorating"] = (
    (
        df["Recent_90D_Late_Delivery_Rate"] >= 0.15
    )
    |
    (
        df["Late_Delivery_Deviation"] >= 0.10
    )
).fillna(False).astype(bool)


# Outstanding deterioration
df["Outstanding_Deteriorating"] = (
    (
        df["Recent_90D_Outstanding_Rate"] >= 0.20
    )
    |
    (
        df["Outstanding_Deviation"] >= 0.10
    )
).fillna(False).astype(bool)


# Partial fulfilment deterioration
df["Partial_Fulfilment_Deteriorating"] = (
    (
        df["Recent_90D_Partial_Fulfilment_Rate"] >= 0.15
    )
    |
    (
        df["Partial_Fulfilment_Deviation"] >= 0.10
    )
).fillna(False).astype(bool)


# ================================================================================
# 10. DETERIORATION SIGNAL COUNT
# ================================================================================

signal_cols = [
    "Fulfilment_Deteriorating",
    "Late_Delivery_Deteriorating",
    "Outstanding_Deteriorating",
    "Partial_Fulfilment_Deteriorating"
]

df["Deterioration_Signal_Count"] = (
    df[signal_cols]
    .sum(axis=1)
    .astype(int)
)


# ================================================================================
# 11. SEVERE SIGNALS
# ================================================================================
#
# Severe evidence is deliberately stronger than ordinary deterioration.
#
# A severe signal means the supplier has moved beyond a mild deterioration.
# ================================================================================

df["Severe_Fulfilment"] = (
    df["Recent_90D_Fulfilment_Rate"] < 0.70
).fillna(False).astype(bool)

df["Severe_Late_Delivery"] = (
    df["Recent_90D_Late_Delivery_Rate"] >= 0.30
).fillna(False).astype(bool)

df["Severe_Outstanding"] = (
    df["Recent_90D_Outstanding_Rate"] >= 0.40
).fillna(False).astype(bool)

df["Severe_Partial_Fulfilment"] = (
    df["Recent_90D_Partial_Fulfilment_Rate"] >= 0.30
).fillna(False).astype(bool)


severe_cols = [
    "Severe_Fulfilment",
    "Severe_Late_Delivery",
    "Severe_Outstanding",
    "Severe_Partial_Fulfilment"
]

df["Severe_Signal_Count"] = (
    df[severe_cols]
    .sum(axis=1)
    .astype(int)
)


# ================================================================================
# 12. FAILURE DIMENSIONS
# ================================================================================
#
# These are operational dimensions that indicate serious supplier failure.
#
# Importantly, this is NOT Phase 3's future failure label.
# It is based entirely on information available at the observation date.
# ================================================================================

df["Current_Fulfilment_Failure"] = (
    df["Recent_90D_Fulfilment_Rate"] < 0.60
).fillna(False).astype(bool)

df["Current_Late_Delivery_Failure"] = (
    df["Recent_90D_Late_Delivery_Rate"] >= 0.40
).fillna(False).astype(bool)

df["Current_Outstanding_Failure"] = (
    df["Recent_90D_Outstanding_Rate"] >= 0.50
).fillna(False).astype(bool)

df["Current_Partial_Fulfilment_Failure"] = (
    df["Recent_90D_Partial_Fulfilment_Rate"] >= 0.40
).fillna(False).astype(bool)


current_failure_cols = [
    "Current_Fulfilment_Failure",
    "Current_Late_Delivery_Failure",
    "Current_Outstanding_Failure",
    "Current_Partial_Fulfilment_Failure"
]

df["Failure_Dimension_Count"] = (
    df[current_failure_cols]
    .sum(axis=1)
    .astype(int)
)


# ================================================================================
# 13. PERSISTENT DETERIORATION
# ================================================================================
#
# Persistence means deterioration is not simply a one-day spike.
#
# We require at least 3 deterioration observations within the previous
# 14 observation days.
# ================================================================================

df["Any_Deterioration"] = (
    df["Deterioration_Signal_Count"] >= 1
)

df["Persistent_Deterioration"] = (
    df.groupby("Supplier_ID")["Any_Deterioration"]
    .transform(
        lambda s: s.rolling(
            14,
            min_periods=1
        ).sum() >= 3
    )
).fillna(False).astype(bool)


# ================================================================================
# 14. RECENT SEVERE PERSISTENCE
# ================================================================================

df["Recent_Severe_Observation_Count"] = (
    df.groupby("Supplier_ID")["Severe_Signal_Count"]
    .transform(
        lambda s: s.rolling(
            14,
            min_periods=1
        ).apply(
            lambda x: np.sum(x >= 1),
            raw=True
        )
    )
)

df["Persistent_Severe_Risk"] = (
    df["Recent_Severe_Observation_Count"] >= 2
).fillna(False).astype(bool)


# ================================================================================
# 15. RISK SCORE
# ================================================================================
#
# Score is supportive evidence, NOT the sole determinant of state.
# ================================================================================

df["Risk_State_Score"] = (
    df["Deterioration_Signal_Count"]
    + (2 * df["Severe_Signal_Count"])
    + (3 * df["Failure_Dimension_Count"])
    + np.where(df["Persistent_Deterioration"], 1, 0)
    + np.where(df["Persistent_Severe_Risk"], 1, 0)
)

df["Risk_State_Score"] = (
    df["Risk_State_Score"]
    .fillna(0)
    .astype(int)
)


# ================================================================================
# 16. INITIAL EVIDENCE CLASSIFICATION
# ================================================================================

df["Evidence_State"] = "Stable"


# WATCH
watch_condition = (
    (df["Deterioration_Signal_Count"] >= 1)
    |
    (
        df["Risk_State_Score"] >= 1
    )
)

df.loc[
    watch_condition,
    "Evidence_State"
] = "Watch"


# DETERIORATING
deteriorating_condition = (
    (
        df["Deterioration_Signal_Count"] >= 2
    )
    |
    (
        df["Persistent_Deterioration"]
        &
        (df["Deterioration_Signal_Count"] >= 1)
    )
)

df.loc[
    deteriorating_condition,
    "Evidence_State"
] = "Deteriorating"


# ================================================================================
# 17. SEQUENTIAL STATE ENGINE
# ================================================================================
#
# This is the important part.
#
# We process each supplier chronologically.
#
# A supplier cannot simply jump:
#
# Stable → High Risk
# Stable → Failure
# Watch → High Risk
# Watch → Failure
#
# High Risk requires a prior Deteriorating state.
# Failure requires a prior High Risk state.
#
# Recovery is allowed when current evidence materially improves.
# ================================================================================

state_results = []

for supplier_id, group in df.groupby(
    "Supplier_ID",
    sort=False
):

    group = group.sort_values(
        "Observation_Date"
    ).copy()

    previous_state = None
    reached_deteriorating = False
    reached_high_risk = False

    states = []
    previous_states = []
    transitions = []

    for _, row in group.iterrows():

        deterioration = int(
            row["Deterioration_Signal_Count"]
        )

        severe = int(
            row["Severe_Signal_Count"]
        )

        failure_dims = int(
            row["Failure_Dimension_Count"]
        )

        persistent = bool(
            row["Persistent_Deterioration"]
        )

        persistent_severe = bool(
            row["Persistent_Severe_Risk"]
        )

        score = int(
            row["Risk_State_Score"]
        )

        # --------------------------------------------------------------
        # BASE STATE
        # --------------------------------------------------------------

        state = "Stable"


        # --------------------------------------------------------------
        # WATCH
        # --------------------------------------------------------------

        if (
            deterioration >= 1
            or score >= 1
        ):
            state = "Watch"


        # --------------------------------------------------------------
        # DETERIORATING
        # --------------------------------------------------------------

        if (
            deterioration >= 2
            or
            (
                persistent
                and deterioration >= 1
            )
        ):
            state = "Deteriorating"


        # --------------------------------------------------------------
        # HIGH RISK
        #
        # Must have:
        # - prior Deteriorating state
        # - severe evidence
        # - preferably persistent severe evidence
        #
        # We deliberately do NOT allow Stable/Watch → High Risk.
        # --------------------------------------------------------------

        high_risk_condition = (
            reached_deteriorating
            and
            (
                (
                    severe >= 2
                    and persistent
                )
                or
                (
                    severe >= 1
                    and persistent_severe
                    and deterioration >= 2
                )
            )
        )

        if high_risk_condition:
            state = "High Risk"


        # --------------------------------------------------------------
        # FAILURE
        #
        # Must have:
        # - prior High Risk pathway
        # - at least 2 current operational failure dimensions
        # - persistent deterioration
        # - stronger evidence than ordinary deterioration
        #
        # This prevents the original broad-label problem from returning.
        # --------------------------------------------------------------

        failure_condition = (
            reached_high_risk
            and
            failure_dims >= 2
            and
            persistent
            and
            (
                severe >= 2
                or score >= 9
            )
        )

        if failure_condition:
            state = "Failure"


        # --------------------------------------------------------------
        # PATH MEMORY
        # --------------------------------------------------------------

        if state in [
            "Deteriorating",
            "High Risk",
            "Failure"
        ]:
            reached_deteriorating = True

        if state in [
            "High Risk",
            "Failure"
        ]:
            reached_high_risk = True


        # --------------------------------------------------------------
        # PREVIOUS STATE / TRANSITION
        # --------------------------------------------------------------

        previous_states.append(previous_state)

        if previous_state is None:
            transition = f"None → {state}"
        else:
            transition = f"{previous_state} → {state}"

        transitions.append(transition)
        states.append(state)

        previous_state = state


    group["Supplier_Risk_State"] = states
    group["Previous_Risk_State"] = previous_states
    group["Risk_State_Transition"] = transitions

    state_results.append(group)


df = pd.concat(
    state_results,
    ignore_index=True
)


# ================================================================================
# 18. STATE CODES
# ================================================================================

state_code_map = {
    "Stable": 0,
    "Watch": 1,
    "Deteriorating": 2,
    "High Risk": 3,
    "Failure": 4
}

df["Supplier_Risk_State_Code"] = (
    df["Supplier_Risk_State"]
    .map(state_code_map)
    .astype(int)
)


# ================================================================================
# 19. CLEAN BOOLEAN COLUMNS
# ================================================================================

boolean_cols = [
    "Fulfilment_Deteriorating",
    "Late_Delivery_Deteriorating",
    "Outstanding_Deteriorating",
    "Partial_Fulfilment_Deteriorating",

    "Severe_Fulfilment",
    "Severe_Late_Delivery",
    "Severe_Outstanding",
    "Severe_Partial_Fulfilment",

    "Current_Fulfilment_Failure",
    "Current_Late_Delivery_Failure",
    "Current_Outstanding_Failure",
    "Current_Partial_Fulfilment_Failure",

    "Any_Deterioration",
    "Persistent_Deterioration",
    "Persistent_Severe_Risk"
]

for col in boolean_cols:
    if col in df.columns:
        df[col] = df[col].fillna(False).astype(bool)


# ================================================================================
# 20. FINAL OBJECT
# ================================================================================

fact_supplier_risk_state = df.copy()


# ================================================================================
# 21. VALIDATION
# ================================================================================

print()
print("=" * 80)
print("PHASE 4 — RISK STATE VALIDATION")
print("=" * 80)

print()
print(f"Rows                         : {len(fact_supplier_risk_state):,}")
print(
    f"Suppliers                    : "
    f"{fact_supplier_risk_state['Supplier_ID'].nunique():,}"
)
print(
    f"Observation dates            : "
    f"{fact_supplier_risk_state['Observation_Date'].nunique():,}"
)

grain_ok = not fact_supplier_risk_state.duplicated(
    ["Supplier_ID", "Observation_Date"]
).any()

print(
    f"Supplier × Date grain unique : {grain_ok}"
)


# ================================================================================
# 22. STATE DISTRIBUTION
# ================================================================================

print()
print("=" * 80)
print("SUPPLIER RISK-STATE DISTRIBUTION")
print("=" * 80)

state_order = [
    "Stable",
    "Watch",
    "Deteriorating",
    "High Risk",
    "Failure"
]

state_distribution = (
    fact_supplier_risk_state["Supplier_Risk_State"]
    .value_counts()
    .reindex(state_order, fill_value=0)
)

print(state_distribution)

print()
print("Risk-state share (%):")

print(
    (
        state_distribution /
        len(fact_supplier_risk_state) *
        100
    ).round(2)
)


# ================================================================================
# 23. TRANSITION VALIDATION
# ================================================================================

print()
print("=" * 80)
print("COMMON RISK-STATE TRANSITIONS")
print("=" * 80)

print(
    fact_supplier_risk_state[
        "Risk_State_Transition"
    ].value_counts().head(25)
)


# ================================================================================
# 24. HARD PATH VALIDATION
# ================================================================================

print()
print("=" * 80)
print("PHASE 4 — PATH LOGIC CHECK")
print("=" * 80)

transition_series = fact_supplier_risk_state[
    "Risk_State_Transition"
]

for transition in [
    "Stable → High Risk",
    "Stable → Failure",
    "Watch → High Risk",
    "Watch → Failure"
]:

    count = (
        transition_series == transition
    ).sum()

    print(
        f"{transition:<25}: {count}"
    )


# ================================================================================
# 25. FAILURE EVIDENCE VALIDATION
# ================================================================================

failure_df = fact_supplier_risk_state[
    fact_supplier_risk_state["Supplier_Risk_State"] == "Failure"
].copy()

print()
print("=" * 80)
print("FAILURE STATE QUALITY CHECK")
print("=" * 80)

print(
    f"Failure observations            : "
    f"{len(failure_df):,}"
)

if len(failure_df) > 0:

    print(
        f"Minimum failure dimensions      : "
        f"{failure_df['Failure_Dimension_Count'].min()}"
    )

    print(
        f"Failure rows with persistence   : "
        f"{failure_df['Persistent_Deterioration'].sum():,}"
    )

    print()
    print("Failure dimension distribution:")

    print(
        failure_df[
            "Failure_Dimension_Count"
        ].value_counts().sort_index()
    )

else:

    print(
        "⚠️ No Failure observations generated."
    )


# ================================================================================
# 26. SUPPLIER STATE JOURNEY
# ================================================================================

print()
print("=" * 80)
print("SUPPLIER STATE JOURNEY")
print("=" * 80)

journey = (
    fact_supplier_risk_state
    .groupby("Supplier_ID")[
        "Supplier_Risk_State_Code"
    ]
    .max()
)

print(
    "Reached Deteriorating+ :",
    (journey >= 2).sum()
)

print(
    "Reached High Risk+     :",
    (journey >= 3).sum()
)

print(
    "Reached Failure        :",
    (journey >= 4).sum()
)


# ================================================================================
# 27. CAUSALITY VALIDATION
# ================================================================================

print()
print("=" * 80)
print("FAILURE PATH CAUSALITY")
print("=" * 80)

failure_suppliers = set(
    failure_df["Supplier_ID"]
)

without_high_risk = 0
without_deteriorating = 0

for supplier_id in failure_suppliers:

    supplier_history = (
        fact_supplier_risk_state[
            fact_supplier_risk_state["Supplier_ID"]
            == supplier_id
        ]
        .sort_values("Observation_Date")
    )

    failure_dates = supplier_history.loc[
        supplier_history["Supplier_Risk_State"]
        == "Failure",
        "Observation_Date"
    ]

    first_failure_date = failure_dates.min()

    prior_history = supplier_history[
        supplier_history["Observation_Date"]
        < first_failure_date
    ]

    if not (
        prior_history["Supplier_Risk_State"]
        == "High Risk"
    ).any():

        without_high_risk += 1

    if not (
        prior_history["Supplier_Risk_State"]
        == "Deteriorating"
    ).any():

        without_deteriorating += 1


print(
    "Suppliers reaching Failure without prior High Risk :",
    without_high_risk
)

print(
    "Suppliers reaching Failure without prior Deteriorating :",
    without_deteriorating
)


# ================================================================================
# 28. STATE SEVERITY COMPARISON
# ================================================================================

print()
print("=" * 80)
print("STATE SEVERITY COMPARISON")
print("=" * 80)

severity_summary = (
    fact_supplier_risk_state
    .groupby("Supplier_Risk_State")
    .agg(
        Observations=("Supplier_ID", "size"),
        Mean_Risk_Score=("Risk_State_Score", "mean"),
        Median_Risk_Score=("Risk_State_Score", "median"),
        Mean_Deterioration_Signals=(
            "Deterioration_Signal_Count",
            "mean"
        ),
        Mean_Severe_Signals=(
            "Severe_Signal_Count",
            "mean"
        ),
        Mean_Failure_Dimensions=(
            "Failure_Dimension_Count",
            "mean"
        ),
        Persistent_Rate=(
            "Persistent_Deterioration",
            lambda x: x.mean() * 100
        )
    )
    .reindex(state_order)
)

print(
    severity_summary.round(3)
)


# ================================================================================
# 29. TEMPORAL CAUSALITY CHECK
# ================================================================================

print()
print("=" * 80)
print("TEMPORAL CAUSALITY CHECK")
print("=" * 80)

future_keywords = [
    "future",
    "label",
    "outcome",
    "failure_90d",
    "future_failure"
]

future_like_columns = [
    col
    for col in fact_supplier_risk_state.columns
    if any(
        keyword in col.lower()
        for keyword in future_keywords
    )
]

# Exclude descriptive/current failure columns because they are
# state-engine evidence, not future outcome labels.
future_like_columns = [
    col
    for col in future_like_columns
    if col not in [
        "Current_Fulfilment_Failure",
        "Current_Late_Delivery_Failure",
        "Current_Outstanding_Failure",
        "Current_Partial_Fulfilment_Failure"
    ]
]

if future_like_columns:

    print(
        "⚠️ Possible future/outcome columns detected:"
    )

    for col in future_like_columns:
        print(" -", col)

else:

    print(
        "✓ No obvious future-outcome columns detected"
    )


# ================================================================================
# 30. FINAL HARD VALIDATION
# ================================================================================

print()
print("=" * 80)
print("PHASE 4 — FINAL HARD VALIDATION")
print("=" * 80)

errors = []


# Grain
if not grain_ok:
    errors.append(
        "Supplier × Date grain is not unique."
    )


# Direct jumps
for transition in [
    "Stable → High Risk",
    "Stable → Failure",
    "Watch → High Risk",
    "Watch → Failure"
]:

    count = (
        transition_series == transition
    ).sum()

    if count > 0:

        errors.append(
            f"Invalid transition detected: "
            f"{transition} ({count:,})"
        )


# Failure dimensionality
if len(failure_df) > 0:

    weak_failure = (
        failure_df[
            "Failure_Dimension_Count"
        ] < 2
    ).sum()

    if weak_failure > 0:

        errors.append(
            f"{weak_failure:,} Failure rows "
            f"have fewer than 2 failure dimensions."
        )


# Failure persistence
if len(failure_df) > 0:

    nonpersistent_failure = (
        ~failure_df[
            "Persistent_Deterioration"
        ]
    ).sum()

    if nonpersistent_failure > 0:

        errors.append(
            f"{nonpersistent_failure:,} Failure rows "
            f"lack persistent deterioration."
        )


# Failure pathway
if without_high_risk > 0:

    errors.append(
        f"{without_high_risk:,} suppliers reached "
        f"Failure without prior High Risk."
    )


# ================================================================================
# 31. FINAL RESULT
# ================================================================================

if errors:

    print()
    print("⚠️ PHASE 4 VALIDATION FAILED")
    print()

    for error in errors:
        print(" -", error)

    raise ValueError(
        "\nPhase 4 contains logic validation errors. "
        "Do NOT proceed to Phase 5."
    )


print()
print("✓ Supplier × Date grain preserved")
print("✓ Historical baselines created")
print("✓ Short-term performance comparisons created")
print("✓ Long-term/persistence logic created")
print("✓ Multi-signal deterioration logic created")
print("✓ Severe deterioration logic created")
print("✓ Failure requires multiple operational dimensions")
print("✓ Failure requires persistent deterioration")
print("✓ High Risk requires prior Deteriorating pathway")
print("✓ Failure requires prior High Risk pathway")
print("✓ Stable → High Risk blocked")
print("✓ Stable → Failure blocked")
print("✓ Watch → High Risk blocked")
print("✓ Watch → Failure blocked")
print("✓ Recovery logic permitted")
print("✓ No Phase 3 future outcome used")
print("✓ No future outcome variables in Phase 4")


# ================================================================================
# 32. FINAL OBJECT SUMMARY
# ================================================================================

print()
print("=" * 80)
print("PHASE 4 FINAL OBJECT")
print("=" * 80)

print(
    f"fact_supplier_risk_state rows    : "
    f"{len(fact_supplier_risk_state):,}"
)

print(
    f"fact_supplier_risk_state columns : "
    f"{len(fact_supplier_risk_state.columns)}"
)

print()
print("Risk-state framework:")
print(
    "Stable → Watch → Deteriorating → High Risk → Failure"
)

print()
print("=" * 80)
print("✓ PHASE 4 — SUPPLIER RISK-STATE ENGINE COMPLETED")
print("=" * 80)

print()
print("Output object:")
print("  fact_supplier_risk_state")

print()
print("Next stage:")
print("  Phase 5 — Predictive Feature Engineering & Model-Ready Dataset")
print("=" * 80)

================================================================================
KEYSTRA — SUPPLIER RISK-STATE ENGINE
PHASE 4 — STAGED SUPPLIER DETERIORATION FRAMEWORK
================================================================================

✓ Base supplier object detected : fact_supplier_risk_phase1
  Rows    : 150,570
  Columns : 32

✓ REQUIRED PHASE 1 COLUMNS VALID
✓ Supplier × Date grain valid
✓ Observation dates valid

✓ Historical baseline metrics created
  - Historical fulfilment
  - Historical partial fulfilment
  - Historical late delivery
  - Historical outstanding

================================================================================
PHASE 4 — RISK STATE VALIDATION
================================================================================

Rows                         : 150,570
Suppliers                    : 90
Observation dates            : 1,673
Supplier × Date grain unique : True

================================================================================
SUPPLIER RISK-STATE DISTRIBUTION
================================================================================
Supplier_Risk_State
Stable           49510
Watch            14966
Deteriorating    56229
High Risk        20458
Failure           9407
Name: count, dtype: int64

Risk-state share (%):
Supplier_Risk_State
Stable           32.88
Watch             9.94
Deteriorating    37.34
High Risk        13.59
Failure           6.25
Name: count, dtype: float64

================================================================================
COMMON RISK-STATE TRANSITIONS
================================================================================
Risk_State_Transition
Deteriorating → Deteriorating    51556
Stable → Stable                  47467
High Risk → High Risk            19377
Watch → Watch                     9849
Failure → Failure                 9061
Deteriorating → Watch             3753
Watch → Deteriorating             3252
Watch → Stable                    1865
Stable → Watch                    1364
Deteriorating → High Risk          819
High Risk → Deteriorating          729
Stable → Deteriorating             679
High Risk → Failure                346
Failure → High Risk                262
Deteriorating → Stable              96
None → Stable                       82
None → Deteriorating                 8
Failure → Deteriorating              5
Name: count, dtype: int64

================================================================================
PHASE 4 — PATH LOGIC CHECK
================================================================================
Stable → High Risk       : 0
Stable → Failure         : 0
Watch → High Risk        : 0
Watch → Failure          : 0

================================================================================
FAILURE STATE QUALITY CHECK
================================================================================
Failure observations            : 9,407
Minimum failure dimensions      : 2
Failure rows with persistence   : 9,407

Failure dimension distribution:
Failure_Dimension_Count
2    4993
3    3149
4    1265
Name: count, dtype: int64

================================================================================
SUPPLIER STATE JOURNEY
================================================================================
Reached Deteriorating+ : 90
Reached High Risk+     : 88
Reached Failure        : 80

================================================================================
FAILURE PATH CAUSALITY
================================================================================
Suppliers reaching Failure without prior High Risk : 0
Suppliers reaching Failure without prior Deteriorating : 0

================================================================================
STATE SEVERITY COMPARISON
================================================================================
                     Observations  Mean_Risk_Score  Median_Risk_Score  \
Supplier_Risk_State
Stable                      49510            0.000                0.0
Watch                       14966            1.007                1.0
Deteriorating               56229            3.266                3.0
High Risk                   20458            9.948               10.0
Failure                      9407           19.726               20.0

                     Mean_Deterioration_Signals  Mean_Severe_Signals  \
Supplier_Risk_State
Stable                                    0.000                0.000
Watch                                     0.105                0.001
Deteriorating                             2.103                0.023
High Risk                                 3.531                1.662
Failure                                   3.561                3.177

                     Mean_Failure_Dimensions  Persistent_Rate
Supplier_Risk_State
Stable                                 0.000            0.000
Watch                                  0.001           89.456
Deteriorating                          0.004           99.746
High Risk                              0.365           99.839
Failure                                2.604          100.000

================================================================================
TEMPORAL CAUSALITY CHECK
================================================================================
✓ No obvious future-outcome columns detected

================================================================================
PHASE 4 — FINAL HARD VALIDATION
================================================================================

✓ Supplier × Date grain preserved
✓ Historical baselines created
✓ Short-term performance comparisons created
✓ Long-term/persistence logic created
✓ Multi-signal deterioration logic created
✓ Severe deterioration logic created
✓ Failure requires multiple operational dimensions
✓ Failure requires persistent deterioration
✓ High Risk requires prior Deteriorating pathway
✓ Failure requires prior High Risk pathway
✓ Stable → High Risk blocked
✓ Stable → Failure blocked
✓ Watch → High Risk blocked
✓ Watch → Failure blocked
✓ Recovery logic permitted
✓ No Phase 3 future outcome used
✓ No future outcome variables in Phase 4

================================================================================
PHASE 4 FINAL OBJECT
================================================================================
fact_supplier_risk_state rows    : 150,570
fact_supplier_risk_state columns : 72

Risk-state framework:
Stable → Watch → Deteriorating → High Risk → Failure

================================================================================
✓ PHASE 4 — SUPPLIER RISK-STATE ENGINE COMPLETED
================================================================================

Output object:
  fact_supplier_risk_state

Next stage:
  Phase 5 — Predictive Feature Engineering & Model-Ready Dataset
================================================================================

In [17]:
# ================================================================================
# KEYSTRA — PREDICTIVE SUPPLIER FAILURE SYSTEM
# PHASE 5 — PREDICTIVE FEATURE ENGINEERING & MODEL-READY DATASET
# ================================================================================
#
# PURPOSE
# -------
# Build the final modelling dataset for predicting:
#
#     "Will this supplier enter a materially unreliable state
#      within the next 90 days?"
#
# PHASE 5 RULES
# --------------
# 1. One row = Supplier × Observation_Date
# 2. Features must be knowable on Observation_Date
# 3. Phase 3 is used ONLY to obtain the target
# 4. No future failure component can become a predictor
# 5. Phase 4 current risk state may be used as a predictor
# 6. No random train/test split is created here
# 7. Temporal validation will happen after this phase
#
# INPUT OBJECTS
# -------------
# fact_supplier_risk_phase1
# fact_supplier_failure_outcome
# fact_supplier_risk_state
#
# OUTPUT
# ------
# fact_supplier_model_ready
# ================================================================================


import pandas as pd
import numpy as np


print("=" * 80)
print("KEYSTRA — PREDICTIVE SUPPLIER FAILURE SYSTEM")
print("PHASE 5 — PREDICTIVE FEATURE ENGINEERING & MODEL-READY DATASET")
print("=" * 80)


# ================================================================================
# 1. OBJECT DETECTION
# ================================================================================

required_objects = [
    "fact_supplier_risk_phase1",
    "fact_supplier_failure_outcome",
    "fact_supplier_risk_state"
]

missing_objects = [
    obj for obj in required_objects
    if obj not in globals()
]

if missing_objects:
    raise ValueError(
        "Missing required Phase objects:\n"
        + "\n".join(f" - {x}" for x in missing_objects)
    )

print("\n✓ Required Phase 1, Phase 3 and Phase 4 objects detected")


phase1 = fact_supplier_risk_phase1.copy()
phase3 = fact_supplier_failure_outcome.copy()
phase4 = fact_supplier_risk_state.copy()


# ================================================================================
# 2. STANDARDISE DATES
# ================================================================================

for df_name, df in [
    ("Phase 1", phase1),
    ("Phase 3", phase3),
    ("Phase 4", phase4)
]:

    if "Observation_Date" not in df.columns:
        raise ValueError(
            f"{df_name} is missing Observation_Date"
        )

    df["Observation_Date"] = pd.to_datetime(
        df["Observation_Date"],
        errors="coerce"
    )

    if df["Observation_Date"].isna().any():
        raise ValueError(
            f"{df_name} contains invalid Observation_Date values"
        )


# ================================================================================
# 3. REQUIRED KEY VALIDATION
# ================================================================================

KEYS = [
    "Supplier_ID",
    "Observation_Date"
]

for df_name, df in [
    ("Phase 1", phase1),
    ("Phase 3", phase3),
    ("Phase 4", phase4)
]:

    missing = [
        c for c in KEYS
        if c not in df.columns
    ]

    if missing:
        raise ValueError(
            f"{df_name} missing required keys:\n"
            + "\n".join(f" - {x}" for x in missing)
        )

    if df.duplicated(KEYS).any():

        duplicate_count = df.duplicated(KEYS).sum()

        raise ValueError(
            f"{df_name} violates Supplier × Date grain.\n"
            f"Duplicate rows: {duplicate_count}"
        )

print("✓ Supplier × Date grain validated across all inputs")


# ================================================================================
# 4. IDENTIFY PHASE 3 TARGET
# ================================================================================

target_candidates = [
    "Supplier_Failure_Label"
]

target_columns = [
    c for c in target_candidates
    if c in phase3.columns
]

if len(target_columns) != 1:

    raise ValueError(
        "Could not uniquely identify Phase 3 target.\n"
        f"Found: {target_columns}"
    )

TARGET = target_columns[0]

print(f"✓ Phase 3 target identified: {TARGET}")


# ================================================================================
# 5. CREATE TARGET TABLE
# ================================================================================

target_df = phase3[
    KEYS + [TARGET]
].copy()

target_df[TARGET] = pd.to_numeric(
    target_df[TARGET],
    errors="coerce"
)

# Target must be binary where present
invalid_target = (
    target_df[TARGET]
    .dropna()
    .loc[
        ~target_df[TARGET].dropna().isin([0, 1])
    ]
)

if len(invalid_target) > 0:

    raise ValueError(
        "Phase 3 target contains values other than 0/1."
    )

print("✓ Future failure target isolated")


# ================================================================================
# 6. SELECT CURRENT-STATE FEATURES FROM PHASE 4
# ================================================================================

phase4_feature_candidates = [

    # Current staged risk state
    "Supplier_Risk_State",
    "Supplier_Risk_State_Code",
    "Risk_State_Score",

    # Current deterioration evidence
    "Deterioration_Signal_Count",
    "Severe_Signal_Count",
    "Failure_Dimension_Count",
    "Persistent_Deterioration",

    # Risk trajectory
    "Previous_Risk_State",
    "Risk_State_Transition",

    # Recent performance
    "Recent_90D_Fulfilment_Rate",
    "Recent_90D_Partial_Fulfilment_Rate",
    "Recent_90D_Late_Delivery_Rate",
    "Recent_90D_Outstanding_Rate",
    "Recent_90D_Average_Delivery_Delay",

    # Historical performance
    "Historical_Fulfilment_Rate",
    "Historical_Partial_Fulfilment_Rate",
    "Historical_Late_Delivery_Rate",
    "Historical_Outstanding_Rate",

    # Current exposure
    "Current_Outstanding_Quantity"
]

phase4_features = [
    c for c in phase4_feature_candidates
    if c in phase4.columns
]

print("\nPHASE 4 FEATURES SELECTED")
print("-" * 80)

for c in phase4_features:
    print(c)


# ================================================================================
# 7. SELECT ADDITIONAL HISTORICAL FEATURES FROM PHASE 1
# ================================================================================

phase1_feature_candidates = [

    "PO_Count",
    "Ordered_Quantity",
    "Received_Quantity",
    "Outstanding_Quantity",

    "Fulfilled_PO_Count",
    "Partial_Fulfilment_Count",
    "Outstanding_PO_Count",
    "Delivered_PO_Count",
    "Late_Delivery_Count",

    "Rolling_90D_PO_Count",
    "Rolling_90D_Ordered_Quantity",
    "Rolling_90D_Received_Quantity",
    "Rolling_90D_Outstanding_Quantity",
    "Rolling_90D_Fulfilled_PO_Count",
    "Rolling_90D_Partial_Fulfilment_Count",
    "Rolling_90D_Delivered_PO_Count",
    "Rolling_90D_Late_Delivery_Count",

    "Fulfilment_Risk_Signal",
    "Late_Delivery_Risk_Signal",
    "Partial_Fulfilment_Risk_Signal",
    "Outstanding_Risk_Signal"
]

phase1_features = [
    c for c in phase1_feature_candidates
    if c in phase1.columns
]

print("\nPHASE 1 FEATURES SELECTED")
print("-" * 80)

for c in phase1_features:
    print(c)


# ================================================================================
# 8. MERGE PHASE 1 + PHASE 4
# ================================================================================

phase1_selected = phase1[
    KEYS + phase1_features
].copy()

phase4_selected = phase4[
    KEYS + phase4_features
].copy()


# ------------------------------------------------------------------------------
# Avoid duplicate feature names after merging
# ------------------------------------------------------------------------------

phase4_only_features = [
    c for c in phase4_features
    if c not in phase1_features
]

phase4_selected = phase4[
    KEYS + phase4_only_features
].copy()


model_df = phase1_selected.merge(
    phase4_selected,
    on=KEYS,
    how="inner",
    validate="one_to_one"
)

print("\n✓ Phase 1 + Phase 4 features merged")


# ================================================================================
# 9. MERGE FUTURE TARGET
# ================================================================================

model_df = model_df.merge(
    target_df,
    on=KEYS,
    how="left",
    validate="one_to_one"
)

print("✓ Phase 3 future target aligned")


# ================================================================================
# 10. TARGET COVERAGE CHECK
# ================================================================================

target_available = model_df[TARGET].notna().sum()
target_missing = model_df[TARGET].isna().sum()

print("\nTARGET COVERAGE")
print("-" * 80)

print(f"Total modelling observations : {len(model_df):,}")
print(f"Target available             : {target_available:,}")
print(f"Target unavailable           : {target_missing:,}")


# ================================================================================
# 11. REMOVE OBSERVATIONS WITHOUT COMPLETE FUTURE OUTCOME
# ================================================================================

model_df = model_df[
    model_df[TARGET].notna()
].copy()

model_df[TARGET] = model_df[TARGET].astype("int8")


# ================================================================================
# 12. CREATE TEMPORAL FEATURES
# ================================================================================

model_df["Observation_Year"] = (
    model_df["Observation_Date"].dt.year
)

model_df["Observation_Month"] = (
    model_df["Observation_Date"].dt.month
)

model_df["Observation_Quarter"] = (
    model_df["Observation_Date"].dt.quarter
)

model_df["Observation_DayOfWeek"] = (
    model_df["Observation_Date"].dt.dayofweek
)

print("✓ Calendar features created")


# ================================================================================
# 13. CREATE EXPLICIT TRAJECTORY FEATURES
# ================================================================================

# These are derived ONLY from current-state / historical variables.

if {
    "Recent_90D_Fulfilment_Rate",
    "Historical_Fulfilment_Rate"
}.issubset(model_df.columns):

    model_df["Fulfilment_Deviation_From_History"] = (
        model_df["Recent_90D_Fulfilment_Rate"]
        - model_df["Historical_Fulfilment_Rate"]
    )


if {
    "Recent_90D_Late_Delivery_Rate",
    "Historical_Late_Delivery_Rate"
}.issubset(model_df.columns):

    model_df["Late_Delivery_Deviation_From_History"] = (
        model_df["Recent_90D_Late_Delivery_Rate"]
        - model_df["Historical_Late_Delivery_Rate"]
    )


if {
    "Recent_90D_Outstanding_Rate",
    "Historical_Outstanding_Rate"
}.issubset(model_df.columns):

    model_df["Outstanding_Deviation_From_History"] = (
        model_df["Recent_90D_Outstanding_Rate"]
        - model_df["Historical_Outstanding_Rate"]
    )


if {
    "Recent_90D_Partial_Fulfilment_Rate",
    "Historical_Partial_Fulfilment_Rate"
}.issubset(model_df.columns):

    model_df["Partial_Fulfilment_Deviation_From_History"] = (
        model_df["Recent_90D_Partial_Fulfilment_Rate"]
        - model_df["Historical_Partial_Fulfilment_Rate"]
    )


print("✓ Current-vs-historical trajectory features created")


# ================================================================================
# 14. RISK SIGNAL AGGREGATION
# ================================================================================

risk_signal_columns = [
    c for c in [
        "Fulfilment_Risk_Signal",
        "Late_Delivery_Risk_Signal",
        "Partial_Fulfilment_Risk_Signal",
        "Outstanding_Risk_Signal"
    ]
    if c in model_df.columns
]

if risk_signal_columns:

    model_df["Total_Current_Risk_Signals"] = (
        model_df[risk_signal_columns]
        .fillna(0)
        .sum(axis=1)
    )

    model_df["Current_Risk_Signal_Count"] = (
        model_df[risk_signal_columns]
        .fillna(0)
        .gt(0)
        .sum(axis=1)
    )

print("✓ Current risk-signal aggregates created")


# ================================================================================
# 15. EXPOSURE FEATURES
# ================================================================================

if {
    "Outstanding_Quantity",
    "Ordered_Quantity"
}.issubset(model_df.columns):

    denominator = model_df["Ordered_Quantity"].replace(
        0,
        np.nan
    )

    model_df["Outstanding_Quantity_Ratio"] = (
        model_df["Outstanding_Quantity"]
        / denominator
    )

if {
    "Rolling_90D_Outstanding_Quantity",
    "Rolling_90D_Ordered_Quantity"
}.issubset(model_df.columns):

    denominator = model_df[
        "Rolling_90D_Ordered_Quantity"
    ].replace(0, np.nan)

    model_df["Rolling_90D_Outstanding_Quantity_Ratio"] = (
        model_df["Rolling_90D_Outstanding_Quantity"]
        / denominator
    )

print("✓ Supplier exposure features created")


# ================================================================================
# 16. CLEAN BOOLEAN FEATURES
# ================================================================================

boolean_candidates = [
    "Persistent_Deterioration"
]

for c in boolean_candidates:

    if c in model_df.columns:

        model_df[c] = (
            model_df[c]
            .fillna(False)
            .astype("int8")
        )


# ================================================================================
# 17. CATEGORICAL STATE ENCODING
# ================================================================================

state_mapping = {
    "Stable": 0,
    "Watch": 1,
    "Deteriorating": 2,
    "High Risk": 3,
    "Failure": 4
}

if "Supplier_Risk_State" in model_df.columns:

    model_df["Current_Risk_State_Code"] = (
        model_df["Supplier_Risk_State"]
        .map(state_mapping)
    )

if "Previous_Risk_State" in model_df.columns:

    model_df["Previous_Risk_State_Code"] = (
        model_df["Previous_Risk_State"]
        .map(state_mapping)
    )

print("✓ Risk-state encoding created")


# ================================================================================
# 18. HARD LEAKAGE AUDIT
# ================================================================================

print("\n")
print("=" * 80)
print("PHASE 5 — HARD TEMPORAL LEAKAGE AUDIT")
print("=" * 80)


# Explicit future-outcome terms that must NEVER appear as predictors.

forbidden_terms = [
    "Future",
    "Failure_Label",
    "Failure_Component",
    "Failure_Outcome",
    "Outcome_Window"
]


protected_columns = {
    TARGET,
    "Supplier_ID",
    "Observation_Date"
}


leakage_columns = []

for col in model_df.columns:

    if col in protected_columns:
        continue

    col_lower = col.lower()

    if any(
        term.lower() in col_lower
        for term in forbidden_terms
    ):
        leakage_columns.append(col)


if leakage_columns:

    raise ValueError(
        "POTENTIAL TARGET LEAKAGE DETECTED.\n"
        "The following columns must be reviewed:\n"
        + "\n".join(
            f" - {c}"
            for c in leakage_columns
        )
    )

print("✓ No future-outcome predictor columns detected")


# ================================================================================
# 19. REMOVE NON-MODELLING IDENTIFIERS FROM FEATURE SET
# ================================================================================

# Keep these columns in the final object for traceability,
# but they will NOT be model predictors.

IDENTIFIER_COLUMNS = [
    "Supplier_ID",
    "Observation_Date"
]


# ================================================================================
# 20. CHECK TARGET DISTRIBUTION
# ================================================================================

print("\nTARGET DISTRIBUTION")
print("-" * 80)

target_distribution = (
    model_df[TARGET]
    .value_counts()
    .sort_index()
)

print(target_distribution)

failure_rate = (
    model_df[TARGET].mean()
)

print(
    f"\nFailure rate : {failure_rate:.2%}"
)


# ================================================================================
# 21. CHECK FEATURE TYPES
# ================================================================================

feature_columns = [
    c for c in model_df.columns
    if c not in IDENTIFIER_COLUMNS + [TARGET]
]

numeric_features = [
    c for c in feature_columns
    if pd.api.types.is_numeric_dtype(
        model_df[c]
    )
]

categorical_features = [
    c for c in feature_columns
    if c not in numeric_features
]


print("\nFEATURE INVENTORY")
print("-" * 80)

print(
    f"Total features      : {len(feature_columns)}"
)

print(
    f"Numeric features    : {len(numeric_features)}"
)

print(
    f"Categorical features: {len(categorical_features)}"
)


# ================================================================================
# 22. MISSINGNESS AUDIT
# ================================================================================

missingness = (
    model_df[feature_columns]
    .isna()
    .mean()
    .sort_values(
        ascending=False
    )
)

print("\nTOP FEATURE MISSINGNESS")
print("-" * 80)

print(
    missingness.head(15)
)


# ================================================================================
# 23. TEMPORAL COVERAGE
# ================================================================================

print("\nTEMPORAL COVERAGE")
print("-" * 80)

print(
    f"Start date : "
    f"{model_df['Observation_Date'].min().date()}"
)

print(
    f"End date   : "
    f"{model_df['Observation_Date'].max().date()}"
)


# ================================================================================
# 24. SUPPLIER COVERAGE
# ================================================================================

print("\nSUPPLIER COVERAGE")
print("-" * 80)

print(
    f"Suppliers : "
    f"{model_df['Supplier_ID'].nunique():,}"
)


# ================================================================================
# 25. FINAL GRAIN CHECK
# ================================================================================

if model_df.duplicated(
    ["Supplier_ID", "Observation_Date"]
).any():

    raise ValueError(
        "FINAL PHASE 5 OBJECT HAS DUPLICATE "
        "SUPPLIER × DATE ROWS."
    )

print("✓ Final Supplier × Date grain preserved")


# ================================================================================
# 26. FINAL TARGET ALIGNMENT CHECK
# ================================================================================

if model_df[TARGET].isna().any():

    raise ValueError(
        "Final Phase 5 object contains missing target values."
    )

print("✓ Every Phase 5 row has a valid Phase 3 target")


# ================================================================================
# 27. SORT FINAL OBJECT
# ================================================================================

model_df = (
    model_df
    .sort_values(
        ["Supplier_ID", "Observation_Date"]
    )
    .reset_index(drop=True)
)


# ================================================================================
# 28. FINAL OBJECT
# ================================================================================

fact_supplier_model_ready = model_df.copy()


# ================================================================================
# 29. FINAL VALIDATION SUMMARY
# ================================================================================

print("\n")
print("=" * 80)
print("PHASE 5 — FINAL MODEL-READY OBJECT")
print("=" * 80)

print(
    f"Rows                     : "
    f"{len(fact_supplier_model_ready):,}"
)

print(
    f"Columns                  : "
    f"{fact_supplier_model_ready.shape[1]:,}"
)

print(
    f"Suppliers                : "
    f"{fact_supplier_model_ready['Supplier_ID'].nunique():,}"
)

print(
    f"Target failure rate      : "
    f"{fact_supplier_model_ready[TARGET].mean():.2%}"
)

print(
    f"Numeric features         : "
    f"{len(numeric_features):,}"
)

print(
    f"Categorical features     : "
    f"{len(categorical_features):,}"
)


print("\n")
print("✓ PHASE 4 CURRENT RISK STATE INCLUDED")
print("✓ PHASE 1 HISTORICAL/OPERATIONAL FEATURES INCLUDED")
print("✓ CURRENT-VS-HISTORICAL TRAJECTORY FEATURES CREATED")
print("✓ CURRENT RISK SIGNAL AGGREGATES CREATED")
print("✓ EXPOSURE FEATURES CREATED")
print("✓ RISK-STATE CODES CREATED")
print("✓ PHASE 3 FUTURE FAILURE USED ONLY AS TARGET")
print("✓ NO FUTURE FAILURE COMPONENTS USED AS FEATURES")
print("✓ NO TARGET LEAKAGE TERMS DETECTED")
print("✓ SUPPLIER × DATE GRAIN PRESERVED")
print("✓ COMPLETE FUTURE OUTCOME ROWS ONLY")
print("✓ TEMPORAL COVERAGE VALIDATED")


print("\n")
print("=" * 80)
print("✓ PHASE 5 — PREDICTIVE FEATURE ENGINEERING COMPLETED")
print("=" * 80)

print("\nOutput object:")
print("  fact_supplier_model_ready")

print("\nTarget:")
print(f"  {TARGET}")

print("\nNext stage:")
print("  Temporal Train / Validation / Test Split")
print("  → Baseline Model")
print("  → Predictive Model Evaluation")
print("  → Recall / Precision / PR-AUC")
print("  → Threshold Optimisation")
print("=" * 80)

================================================================================
KEYSTRA — PREDICTIVE SUPPLIER FAILURE SYSTEM
PHASE 5 — PREDICTIVE FEATURE ENGINEERING & MODEL-READY DATASET
================================================================================

✓ Required Phase 1, Phase 3 and Phase 4 objects detected
✓ Supplier × Date grain validated across all inputs
✓ Phase 3 target identified: Supplier_Failure_Label
✓ Future failure target isolated

PHASE 4 FEATURES SELECTED
--------------------------------------------------------------------------------
Supplier_Risk_State
Supplier_Risk_State_Code
Risk_State_Score
Deterioration_Signal_Count
Severe_Signal_Count
Failure_Dimension_Count
Persistent_Deterioration
Previous_Risk_State
Risk_State_Transition
Recent_90D_Fulfilment_Rate
Recent_90D_Partial_Fulfilment_Rate
Recent_90D_Late_Delivery_Rate
Recent_90D_Outstanding_Rate
Recent_90D_Average_Delivery_Delay
Historical_Fulfilment_Rate
Historical_Partial_Fulfilment_Rate
Historical_Late_Delivery_Rate
Historical_Outstanding_Rate
Current_Outstanding_Quantity

PHASE 1 FEATURES SELECTED
--------------------------------------------------------------------------------
PO_Count
Ordered_Quantity
Received_Quantity
Outstanding_Quantity
Fulfilled_PO_Count
Partial_Fulfilment_Count
Outstanding_PO_Count
Delivered_PO_Count
Late_Delivery_Count
Rolling_90D_PO_Count
Rolling_90D_Ordered_Quantity
Rolling_90D_Received_Quantity
Rolling_90D_Outstanding_Quantity
Rolling_90D_Fulfilled_PO_Count
Rolling_90D_Partial_Fulfilment_Count
Rolling_90D_Delivered_PO_Count
Rolling_90D_Late_Delivery_Count
Fulfilment_Risk_Signal
Late_Delivery_Risk_Signal
Partial_Fulfilment_Risk_Signal
Outstanding_Risk_Signal

✓ Phase 1 + Phase 4 features merged
✓ Phase 3 future target aligned

TARGET COVERAGE
--------------------------------------------------------------------------------
Total modelling observations : 150,570
Target available             : 138,953
Target unavailable           : 11,617
✓ Calendar features created
✓ Current-vs-historical trajectory features created
✓ Current risk-signal aggregates created
✓ Supplier exposure features created
✓ Risk-state encoding created


================================================================================
PHASE 5 — HARD TEMPORAL LEAKAGE AUDIT
================================================================================
✓ No future-outcome predictor columns detected

TARGET DISTRIBUTION
--------------------------------------------------------------------------------
Supplier_Failure_Label
0    128129
1     10824
Name: count, dtype: int64

Failure rate : 7.79%

FEATURE INVENTORY
--------------------------------------------------------------------------------
Total features      : 54
Numeric features    : 51
Categorical features: 3

TOP FEATURE MISSINGNESS
--------------------------------------------------------------------------------
Late_Delivery_Deviation_From_History    0.783510
Historical_Late_Delivery_Rate           0.783510
Outstanding_Quantity_Ratio              0.764035
Historical_Outstanding_Rate             0.764035
Outstanding_Deviation_From_History      0.764035
Recent_90D_Late_Delivery_Rate           0.007420
Outstanding_PO_Count                    0.000000
Delivered_PO_Count                      0.000000
Late_Delivery_Count                     0.000000
Rolling_90D_PO_Count                    0.000000
Rolling_90D_Ordered_Quantity            0.000000
Rolling_90D_Received_Quantity           0.000000
Rolling_90D_Outstanding_Quantity        0.000000
Rolling_90D_Fulfilled_PO_Count          0.000000
Rolling_90D_Partial_Fulfilment_Count    0.000000
dtype: float64

TEMPORAL COVERAGE
--------------------------------------------------------------------------------
Start date : 2022-02-06
End date   : 2026-07-30

SUPPLIER COVERAGE
--------------------------------------------------------------------------------
Suppliers : 90
✓ Final Supplier × Date grain preserved
✓ Every Phase 5 row has a valid Phase 3 target


================================================================================
PHASE 5 — FINAL MODEL-READY OBJECT
================================================================================
Rows                     : 138,953
Columns                  : 57
Suppliers                : 90
Target failure rate      : 7.79%
Numeric features         : 51
Categorical features     : 3


✓ PHASE 4 CURRENT RISK STATE INCLUDED
✓ PHASE 1 HISTORICAL/OPERATIONAL FEATURES INCLUDED
✓ CURRENT-VS-HISTORICAL TRAJECTORY FEATURES CREATED
✓ CURRENT RISK SIGNAL AGGREGATES CREATED
✓ EXPOSURE FEATURES CREATED
✓ RISK-STATE CODES CREATED
✓ PHASE 3 FUTURE FAILURE USED ONLY AS TARGET
✓ NO FUTURE FAILURE COMPONENTS USED AS FEATURES
✓ NO TARGET LEAKAGE TERMS DETECTED
✓ SUPPLIER × DATE GRAIN PRESERVED
✓ COMPLETE FUTURE OUTCOME ROWS ONLY
✓ TEMPORAL COVERAGE VALIDATED


================================================================================
✓ PHASE 5 — PREDICTIVE FEATURE ENGINEERING COMPLETED
================================================================================

Output object:
  fact_supplier_model_ready

Target:
  Supplier_Failure_Label

Next stage:
  Temporal Train / Validation / Test Split
  → Baseline Model
  → Predictive Model Evaluation
  → Recall / Precision / PR-AUC
  → Threshold Optimisation
================================================================================

In [18]:
# ================================================================================
# KEYSTRA — PREDICTIVE SUPPLIER FAILURE SYSTEM
# PHASE 6 — TEMPORAL MODEL VALIDATION & BASELINE
# ================================================================================
#
# PURPOSE
# -------
# Establish an honest chronological baseline for supplier-failure prediction.
#
# IMPORTANT:
# - NO random train/test split
# - NO SMOTE
# - NO threshold optimisation yet
# - NO future outcome variables as predictors
# - Supplier × Date observations remain chronological
# - Phase 3 Supplier_Failure_Label is used ONLY as the target
#
# OUTPUT OBJECTS
# --------------
# X_train, X_validation, X_test
# y_train, y_validation, y_test
# phase6_train
# phase6_validation
# phase6_test
# baseline_model
# phase6_model_results
# ================================================================================

import pandas as pd
import numpy as np
import warnings

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    average_precision_score,
    confusion_matrix,
    classification_report
)

warnings.filterwarnings("ignore")

print("=" * 80)
print("KEYSTRA — PREDICTIVE SUPPLIER FAILURE SYSTEM")
print("PHASE 6 — TEMPORAL MODEL VALIDATION & BASELINE")
print("=" * 80)


# ================================================================================
# 1. DETECT PHASE 5 OBJECT
# ================================================================================

if "fact_supplier_model_ready" not in globals():
    raise NameError(
        "fact_supplier_model_ready was not found. "
        "Run Phase 5 before Phase 6."
    )

df = fact_supplier_model_ready.copy()

print("\n✓ Phase 5 model-ready object detected")
print(f"  Rows    : {len(df):,}")
print(f"  Columns : {df.shape[1]}")


# ================================================================================
# 2. REQUIRED COLUMN VALIDATION
# ================================================================================

required_columns = [
    "Supplier_ID",
    "Observation_Date",
    "Supplier_Failure_Label"
]

missing = [
    col for col in required_columns
    if col not in df.columns
]

if missing:
    raise ValueError(
        "Missing required Phase 5 columns:\n"
        + "\n".join(f" - {c}" for c in missing)
    )

print("\n✓ Required Phase 5 columns validated")


# ================================================================================
# 3. DATA TYPE & GRAIN VALIDATION
# ================================================================================

df["Observation_Date"] = pd.to_datetime(
    df["Observation_Date"],
    errors="coerce"
)

if df["Observation_Date"].isna().any():
    raise ValueError(
        "Observation_Date contains invalid or missing dates."
    )

df = df.sort_values(
    ["Observation_Date", "Supplier_ID"]
).reset_index(drop=True)

duplicate_count = df.duplicated(
    ["Supplier_ID", "Observation_Date"]
).sum()

if duplicate_count > 0:
    raise ValueError(
        f"Supplier × Date grain violated. "
        f"Duplicate rows: {duplicate_count:,}"
    )

print("\n" + "=" * 80)
print("PHASE 6 — DATASET VALIDATION")
print("=" * 80)

print(f"Rows                         : {len(df):,}")
print(f"Suppliers                    : {df['Supplier_ID'].nunique():,}")
print(f"Observation dates            : {df['Observation_Date'].nunique():,}")
print(f"Supplier × Date grain unique : {duplicate_count == 0}")
print(
    f"Start date                   : "
    f"{df['Observation_Date'].min().date()}"
)
print(
    f"End date                     : "
    f"{df['Observation_Date'].max().date()}"
)


# ================================================================================
# 4. TARGET VALIDATION
# ================================================================================

target = "Supplier_Failure_Label"

if df[target].isna().any():
    raise ValueError(
        "Target contains missing values. "
        "Phase 5 should have removed incomplete future-outcome rows."
    )

df[target] = pd.to_numeric(
    df[target],
    errors="coerce"
)

invalid_target = ~df[target].isin([0, 1])

if invalid_target.any():
    raise ValueError(
        "Supplier_Failure_Label contains values other than 0 and 1."
    )

df[target] = df[target].astype(int)

print("\n" + "=" * 80)
print("TARGET VALIDATION")
print("=" * 80)

print(df[target].value_counts().sort_index())

failure_rate = df[target].mean()

print(f"\nFailure rate : {failure_rate:.2%}")

if failure_rate <= 0 or failure_rate >= 1:
    raise ValueError(
        "Target contains only one class. "
        "A predictive classification model cannot be trained."
    )

print("✓ Binary future-failure target confirmed")


# ================================================================================
# 5. EXPLICIT TEMPORAL LEAKAGE PROTECTION
# ================================================================================

# These columns are NOT allowed to become predictors.
#
# Supplier_Failure_Label = future target
# Future_*                = future outcome components
#
# We also exclude identifiers that do not represent predictive behaviour.

future_terms = [
    "Future_",
    "Failure_Label"
]

leakage_columns = []

for col in df.columns:
    col_lower = col.lower()

    if (
        col.startswith("Future_")
        or "future_" in col_lower
        or col == "Supplier_Failure_Label"
    ):
        leakage_columns.append(col)

# Explicit identifiers / non-predictive fields
identifier_columns = [
    "Supplier_ID",
    "Observation_Date"
]

excluded_columns = sorted(
    set(leakage_columns + identifier_columns)
)

predictor_columns = [
    col for col in df.columns
    if col not in excluded_columns
]

print("\n" + "=" * 80)
print("TEMPORAL LEAKAGE PROTECTION")
print("=" * 80)

print(f"Excluded columns : {len(excluded_columns)}")

for col in excluded_columns:
    print(f"  - {col}")

print(f"\nPredictor columns : {len(predictor_columns)}")

# Hard leakage check
remaining_future_columns = [
    col for col in predictor_columns
    if (
        col.startswith("Future_")
        or "future_" in col.lower()
        or "failure_label" in col.lower()
    )
]

if remaining_future_columns:
    raise ValueError(
        "Potential future leakage detected:\n"
        + "\n".join(
            f" - {c}" for c in remaining_future_columns
        )
    )

print("✓ No obvious future-outcome predictors detected")


# ================================================================================
# 6. CHRONOLOGICAL TRAIN / VALIDATION / TEST SPLIT
# ================================================================================
#
# We use date boundaries rather than random sampling.
#
# 70% earliest observations  -> TRAIN
# 15% next observations      -> VALIDATION
# 15% latest observations    -> TEST
#
# Because this is a supplier × date panel, the split is performed using
# chronological observation dates.
# ================================================================================

unique_dates = np.sort(
    df["Observation_Date"].drop_duplicates().values
)

n_dates = len(unique_dates)

if n_dates < 10:
    raise ValueError(
        "Too few observation dates for a reliable temporal split."
    )

train_end_index = int(n_dates * 0.70)
validation_end_index = int(n_dates * 0.85)

train_end_index = max(1, train_end_index)
validation_end_index = max(
    train_end_index + 1,
    validation_end_index
)

if validation_end_index >= n_dates:
    validation_end_index = n_dates - 1

train_end_date = pd.Timestamp(
    unique_dates[train_end_index - 1]
)

validation_start_date = pd.Timestamp(
    unique_dates[train_end_index]
)

validation_end_date = pd.Timestamp(
    unique_dates[validation_end_index - 1]
)

test_start_date = pd.Timestamp(
    unique_dates[validation_end_index]
)

train_mask = (
    df["Observation_Date"] <= train_end_date
)

validation_mask = (
    (df["Observation_Date"] >= validation_start_date)
    &
    (df["Observation_Date"] <= validation_end_date)
)

test_mask = (
    df["Observation_Date"] >= test_start_date
)

phase6_train = df.loc[train_mask].copy()
phase6_validation = df.loc[validation_mask].copy()
phase6_test = df.loc[test_mask].copy()

if len(phase6_train) == 0:
    raise ValueError("Training set is empty.")

if len(phase6_validation) == 0:
    raise ValueError("Validation set is empty.")

if len(phase6_test) == 0:
    raise ValueError("Test set is empty.")


# ================================================================================
# 7. HARD TEMPORAL ORDER CHECK
# ================================================================================

if not (
    phase6_train["Observation_Date"].max()
    <
    phase6_validation["Observation_Date"].min()
):
    raise ValueError(
        "Temporal leakage detected between train and validation."
    )

if not (
    phase6_validation["Observation_Date"].max()
    <
    phase6_test["Observation_Date"].min()
):
    raise ValueError(
        "Temporal leakage detected between validation and test."
    )

print("\n" + "=" * 80)
print("TEMPORAL TRAIN / VALIDATION / TEST SPLIT")
print("=" * 80)

print(
    f"TRAIN      : "
    f"{phase6_train['Observation_Date'].min().date()} "
    f"→ "
    f"{phase6_train['Observation_Date'].max().date()}"
)

print(
    f"VALIDATION : "
    f"{phase6_validation['Observation_Date'].min().date()} "
    f"→ "
    f"{phase6_validation['Observation_Date'].max().date()}"
)

print(
    f"TEST       : "
    f"{phase6_test['Observation_Date'].min().date()} "
    f"→ "
    f"{phase6_test['Observation_Date'].max().date()}"
)

print("\nRows:")
print(f"TRAIN      : {len(phase6_train):,}")
print(f"VALIDATION : {len(phase6_validation):,}")
print(f"TEST       : {len(phase6_test):,}")

print("\n✓ Chronological separation confirmed")


# ================================================================================
# 8. TARGET DISTRIBUTION BY TEMPORAL SPLIT
# ================================================================================

print("\n" + "=" * 80)
print("TARGET DISTRIBUTION BY TEMPORAL SPLIT")
print("=" * 80)

split_summary = pd.DataFrame({
    "Split": [
        "Train",
        "Validation",
        "Test"
    ],
    "Rows": [
        len(phase6_train),
        len(phase6_validation),
        len(phase6_test)
    ],
    "Failures": [
        phase6_train[target].sum(),
        phase6_validation[target].sum(),
        phase6_test[target].sum()
    ],
    "Failure_Rate": [
        phase6_train[target].mean(),
        phase6_validation[target].mean(),
        phase6_test[target].mean()
    ]
})

print(split_summary.to_string(index=False))

print("\n✓ Target exists in all three temporal periods")


# ================================================================================
# 9. BUILD X / y MATRICES
# ================================================================================

X_train = phase6_train[predictor_columns].copy()
y_train = phase6_train[target].copy()

X_validation = phase6_validation[predictor_columns].copy()
y_validation = phase6_validation[target].copy()

X_test = phase6_test[predictor_columns].copy()
y_test = phase6_test[target].copy()


# ================================================================================
# 10. FEATURE TYPE DETECTION
# ================================================================================

categorical_features = X_train.select_dtypes(
    include=["object", "category", "bool"]
).columns.tolist()

numeric_features = [
    col for col in X_train.columns
    if col not in categorical_features
]

print("\n" + "=" * 80)
print("FEATURE INVENTORY")
print("=" * 80)

print(f"Total predictors      : {len(predictor_columns)}")
print(f"Numeric predictors    : {len(numeric_features)}")
print(f"Categorical predictors: {len(categorical_features)}")

if categorical_features:
    print("\nCategorical features:")
    for col in categorical_features:
        print(f"  - {col}")


# ================================================================================
# 11. PREPROCESSING PIPELINE
# ================================================================================
#
# Numeric:
#   Missing values -> median
#
# Categorical:
#   Missing values -> most frequent
#   One-hot encode
#
# handle_unknown='ignore' ensures that categories appearing in validation/test
# but not in training do not break the model.
# ================================================================================

numeric_pipeline = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(strategy="median")
        )
    ]
)

categorical_pipeline = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(strategy="most_frequent")
        ),
        (
            "onehot",
            OneHotEncoder(
                handle_unknown="ignore",
                sparse_output=False
            )
        )
    ]
)

transformers = []

if numeric_features:
    transformers.append(
        (
            "numeric",
            numeric_pipeline,
            numeric_features
        )
    )

if categorical_features:
    transformers.append(
        (
            "categorical",
            categorical_pipeline,
            categorical_features
        )
    )

preprocessor = ColumnTransformer(
    transformers=transformers,
    remainder="drop"
)


# ================================================================================
# 12. BASELINE MODEL
# ================================================================================
#
# Random Forest is being used as the first nonlinear baseline because:
# - supplier-risk relationships may be nonlinear
# - it handles mixed operational features well
# - it does not require feature scaling
# - it gives a strong benchmark before more advanced modelling
#
# class_weight='balanced' is intentionally used because failure is a minority
# class. We are NOT using SMOTE yet.
# ================================================================================

baseline_model = Pipeline(
    steps=[
        (
            "preprocessor",
            preprocessor
        ),
        (
            "model",
            RandomForestClassifier(
                n_estimators=300,
                max_depth=10,
                min_samples_leaf=10,
                class_weight="balanced",
                random_state=42,
                n_jobs=-1
            )
        )
    ]
)


# ================================================================================
# 13. TRAIN BASELINE
# ================================================================================

print("\n" + "=" * 80)
print("TRAINING BASELINE MODEL")
print("=" * 80)

print("Model : Random Forest")
print("Trees : 300")
print("Max depth : 10")
print("Minimum leaf size : 10")
print("Class weighting : balanced")

baseline_model.fit(
    X_train,
    y_train
)

print("\n✓ Baseline model trained")


# ================================================================================
# 14. PREDICTION FUNCTION
# ================================================================================

def evaluate_split(model, X, y, split_name):

    probabilities = model.predict_proba(X)[:, 1]

    predictions = (
        probabilities >= 0.50
    ).astype(int)

    tn, fp, fn, tp = confusion_matrix(
        y,
        predictions,
        labels=[0, 1]
    ).ravel()

    metrics = {
        "Split": split_name,
        "Rows": len(y),
        "Failures": int(y.sum()),
        "Failure_Rate": y.mean(),
        "Accuracy": accuracy_score(
            y,
            predictions
        ),
        "Precision": precision_score(
            y,
            predictions,
            zero_division=0
        ),
        "Recall": recall_score(
            y,
            predictions,
            zero_division=0
        ),
        "F1": f1_score(
            y,
            predictions,
            zero_division=0
        ),
        "ROC_AUC": roc_auc_score(
            y,
            probabilities
        ),
        "PR_AUC": average_precision_score(
            y,
            probabilities
        ),
        "True_Negatives": tn,
        "False_Positives": fp,
        "False_Negatives": fn,
        "True_Positives": tp
    }

    return metrics, probabilities, predictions


# ================================================================================
# 15. EVALUATE TRAIN / VALIDATION / TEST
# ================================================================================

train_metrics, train_probabilities, train_predictions = evaluate_split(
    baseline_model,
    X_train,
    y_train,
    "Train"
)

validation_metrics, validation_probabilities, validation_predictions = evaluate_split(
    baseline_model,
    X_validation,
    y_validation,
    "Validation"
)

test_metrics, test_probabilities, test_predictions = evaluate_split(
    baseline_model,
    X_test,
    y_test,
    "Test"
)

phase6_model_results = pd.DataFrame([
    train_metrics,
    validation_metrics,
    test_metrics
])


# ================================================================================
# 16. BASELINE PERFORMANCE
# ================================================================================

print("\n" + "=" * 80)
print("PHASE 6 — BASELINE MODEL PERFORMANCE")
print("=" * 80)

display(
    phase6_model_results[
        [
            "Split",
            "Rows",
            "Failures",
            "Failure_Rate",
            "Precision",
            "Recall",
            "F1",
            "ROC_AUC",
            "PR_AUC"
        ]
    ].round(4)
)


# ================================================================================
# 17. TEST CONFUSION MATRIX
# ================================================================================

print("\n" + "=" * 80)
print("TEST SET — CONFUSION MATRIX")
print("=" * 80)

test_cm = confusion_matrix(
    y_test,
    test_predictions,
    labels=[0, 1]
)

test_cm_df = pd.DataFrame(
    test_cm,
    index=[
        "Actual Stable",
        "Actual Failure"
    ],
    columns=[
        "Predicted Stable",
        "Predicted Failure"
    ]
)

print(test_cm_df)


# ================================================================================
# 18. TEST CLASSIFICATION REPORT
# ================================================================================

print("\n" + "=" * 80)
print("TEST SET — CLASSIFICATION REPORT")
print("=" * 80)

print(
    classification_report(
        y_test,
        test_predictions,
        target_names=[
            "No Future Failure",
            "Future Failure"
        ],
        zero_division=0
    )
)


# ================================================================================
# 19. RECALL DIAGNOSTIC
# ================================================================================

test_recall = test_metrics["Recall"]
test_precision = test_metrics["Precision"]
test_pr_auc = test_metrics["PR_AUC"]

print("\n" + "=" * 80)
print("SUPPLIER FAILURE DETECTION DIAGNOSTIC")
print("=" * 80)

print(f"Test Recall    : {test_recall:.2%}")
print(f"Test Precision : {test_precision:.2%}")
print(f"Test PR-AUC    : {test_pr_auc:.4f}")

if test_recall < 0.50:

    print(
        "\n⚠️ BASELINE RECALL IS BELOW 50%."
    )

    print(
        "The model is missing a substantial proportion "
        "of future supplier failures."
    )

    print(
        "DO NOT proceed as if the model is production-ready."
    )

elif test_recall < 0.70:

    print(
        "\n⚠️ BASELINE RECALL IS MODERATE."
    )

    print(
        "The model detects some future failures, "
        "but recall still requires improvement."
    )

else:

    print(
        "\n✓ BASELINE RECALL IS REASONABLY STRONG."
    )

    print(
        "Further threshold and model optimisation can still be performed."
    )


# ================================================================================
# 20. TRAIN VS TEST GENERALISATION CHECK
# ================================================================================

train_pr_auc = train_metrics["PR_AUC"]
validation_pr_auc = validation_metrics["PR_AUC"]

print("\n" + "=" * 80)
print("GENERALISATION CHECK")
print("=" * 80)

print(f"Train PR-AUC      : {train_pr_auc:.4f}")
print(f"Validation PR-AUC : {validation_pr_auc:.4f}")
print(f"Test PR-AUC       : {test_pr_auc:.4f}")

pr_auc_gap = train_pr_auc - test_pr_auc

print(f"\nTrain → Test PR-AUC gap : {pr_auc_gap:.4f}")

if pr_auc_gap > 0.15:

    print(
        "⚠️ Large generalisation gap detected."
    )

    print(
        "The baseline may be overfitting historical supplier behaviour."
    )

else:

    print(
        "✓ No severe train/test PR-AUC gap detected."
    )


# ================================================================================
# 21. SAVE MODEL PROBABILITIES BACK TO TEMPORAL DATASETS
# ================================================================================

phase6_train["Baseline_Failure_Probability"] = train_probabilities
phase6_train["Baseline_Prediction_50"] = train_predictions

phase6_validation[
    "Baseline_Failure_Probability"
] = validation_probabilities

phase6_validation[
    "Baseline_Prediction_50"
] = validation_predictions

phase6_test["Baseline_Failure_Probability"] = test_probabilities
phase6_test["Baseline_Prediction_50"] = test_predictions


# ================================================================================
# 22. FINAL PHASE 6 VALIDATION
# ================================================================================

print("\n" + "=" * 80)
print("PHASE 6 — FINAL HARD VALIDATION")
print("=" * 80)

checks = {
    "Train exists": len(phase6_train) > 0,
    "Validation exists": len(phase6_validation) > 0,
    "Test exists": len(phase6_test) > 0,
    "Train before validation":
        phase6_train["Observation_Date"].max()
        <
        phase6_validation["Observation_Date"].min(),
    "Validation before test":
        phase6_validation["Observation_Date"].max()
        <
        phase6_test["Observation_Date"].min(),
    "Binary target":
        set(df[target].unique()).issubset({0, 1}),
    "No future predictor columns":
        len(remaining_future_columns) == 0,
    "Supplier × Date grain preserved":
        df.duplicated(
            ["Supplier_ID", "Observation_Date"]
        ).sum() == 0,
    "Baseline trained":
        hasattr(baseline_model, "predict_proba"),
}

for check_name, result in checks.items():

    if result:
        print(f"✓ {check_name}")
    else:
        print(f"✗ {check_name}")

if not all(checks.values()):

    raise ValueError(
        "PHASE 6 HARD VALIDATION FAILED. "
        "Review the failed checks before proceeding."
    )


# ================================================================================
# 23. FINAL OBJECT SUMMARY
# ================================================================================

print("\n" + "=" * 80)
print("PHASE 6 FINAL OBJECTS")
print("=" * 80)

print(
    f"Training observations     : "
    f"{len(phase6_train):,}"
)

print(
    f"Validation observations   : "
    f"{len(phase6_validation):,}"
)

print(
    f"Test observations         : "
    f"{len(phase6_test):,}"
)

print(
    f"Predictor count           : "
    f"{len(predictor_columns):,}"
)

print(
    f"Numeric features          : "
    f"{len(numeric_features):,}"
)

print(
    f"Categorical features      : "
    f"{len(categorical_features):,}"
)

print(
    f"Test failure rate         : "
    f"{y_test.mean():.2%}"
)

print(
    f"Test Recall               : "
    f"{test_recall:.2%}"
)

print(
    f"Test Precision            : "
    f"{test_precision:.2%}"
)

print(
    f"Test PR-AUC               : "
    f"{test_pr_auc:.4f}"
)

print("\n" + "=" * 80)
print("✓ PHASE 6 — TEMPORAL MODEL VALIDATION & BASELINE COMPLETED")
print("=" * 80)

print("""
Output objects:
  phase6_train
  phase6_validation
  phase6_test
  X_train
  X_validation
  X_test
  y_train
  y_validation
  y_test
  baseline_model
  phase6_model_results

Next stage:
  Phase 7 — Predictive Model Improvement
  → Threshold Optimisation
  → Recall Improvement
  → Precision–Recall Trade-off
  → Model Comparison
  → Final Early-Warning Model Selection
""")

================================================================================
KEYSTRA — PREDICTIVE SUPPLIER FAILURE SYSTEM
PHASE 6 — TEMPORAL MODEL VALIDATION & BASELINE
================================================================================

✓ Phase 5 model-ready object detected
  Rows    : 138,953
  Columns : 57

✓ Required Phase 5 columns validated

================================================================================
PHASE 6 — DATASET VALIDATION
================================================================================
Rows                         : 138,953
Suppliers                    : 90
Observation dates            : 1,636
Supplier × Date grain unique : True
Start date                   : 2022-02-06
End date                     : 2026-07-30

================================================================================
TARGET VALIDATION
================================================================================
Supplier_Failure_Label
0    128129
1     10824
Name: count, dtype: int64

Failure rate : 7.79%
✓ Binary future-failure target confirmed

================================================================================
TEMPORAL LEAKAGE PROTECTION
================================================================================
Excluded columns : 3
  - Observation_Date
  - Supplier_Failure_Label
  - Supplier_ID

Predictor columns : 54
✓ No obvious future-outcome predictors detected

================================================================================
TEMPORAL TRAIN / VALIDATION / TEST SPLIT
================================================================================
TRAIN      : 2022-02-06 → 2025-03-26
VALIDATION : 2025-03-27 → 2025-11-26
TEST       : 2025-11-27 → 2026-07-30

Rows:
TRAIN      : 96,995
VALIDATION : 20,849
TEST       : 21,109

✓ Chronological separation confirmed

================================================================================
TARGET DISTRIBUTION BY TEMPORAL SPLIT
================================================================================
     Split  Rows  Failures  Failure_Rate
     Train 96995      2009      0.020712
Validation 20849      1873      0.089836
      Test 21109      6942      0.328864

✓ Target exists in all three temporal periods

================================================================================
FEATURE INVENTORY
================================================================================
Total predictors      : 54
Numeric predictors    : 51
Categorical predictors: 3

Categorical features:
  - Supplier_Risk_State
  - Previous_Risk_State
  - Risk_State_Transition

================================================================================
TRAINING BASELINE MODEL
================================================================================
Model : Random Forest
Trees : 300
Max depth : 10
Minimum leaf size : 10
Class weighting : balanced

✓ Baseline model trained

================================================================================
PHASE 6 — BASELINE MODEL PERFORMANCE
================================================================================

,Split,Rows,Failures,Failure_Rate,Precision,Recall,F1,ROC_AUC,PR_AUC
0,Train,96995,2009,0.0207,0.5653,1.0000,0.7223,0.9995,0.9809
1,Validation,20849,1873,0.0898,0.6110,0.9696,0.7496,0.9881,0.8795
2,Test,21109,6942,0.3289,0.8613,0.6645,0.7502,0.9598,0.8878

================================================================================
TEST SET — CONFUSION MATRIX
================================================================================
                Predicted Stable  Predicted Failure
Actual Stable              13424                743
Actual Failure              2329               4613

================================================================================
TEST SET — CLASSIFICATION REPORT
================================================================================
                   precision    recall  f1-score   support

No Future Failure       0.85      0.95      0.90     14167
   Future Failure       0.86      0.66      0.75      6942

         accuracy                           0.85     21109
        macro avg       0.86      0.81      0.82     21109
     weighted avg       0.86      0.85      0.85     21109


================================================================================
SUPPLIER FAILURE DETECTION DIAGNOSTIC
================================================================================
Test Recall    : 66.45%
Test Precision : 86.13%
Test PR-AUC    : 0.8878

⚠️ BASELINE RECALL IS MODERATE.
The model detects some future failures, but recall still requires improvement.

================================================================================
GENERALISATION CHECK
================================================================================
Train PR-AUC      : 0.9809
Validation PR-AUC : 0.8795
Test PR-AUC       : 0.8878

Train → Test PR-AUC gap : 0.0931
✓ No severe train/test PR-AUC gap detected.

================================================================================
PHASE 6 — FINAL HARD VALIDATION
================================================================================
✓ Train exists
✓ Validation exists
✓ Test exists
✓ Train before validation
✓ Validation before test
✓ Binary target
✓ No future predictor columns
✓ Supplier × Date grain preserved
✓ Baseline trained

================================================================================
PHASE 6 FINAL OBJECTS
================================================================================
Training observations     : 96,995
Validation observations   : 20,849
Test observations         : 21,109
Predictor count           : 54
Numeric features          : 51
Categorical features      : 3
Test failure rate         : 32.89%
Test Recall               : 66.45%
Test Precision            : 86.13%
Test PR-AUC               : 0.8878

================================================================================
✓ PHASE 6 — TEMPORAL MODEL VALIDATION & BASELINE COMPLETED
================================================================================

Output objects:
  phase6_train
  phase6_validation
  phase6_test
  X_train
  X_validation
  X_test
  y_train
  y_validation
  y_test
  baseline_model
  phase6_model_results

Next stage:
  Phase 7 — Predictive Model Improvement
  → Threshold Optimisation
  → Recall Improvement
  → Precision–Recall Trade-off
  → Model Comparison
  → Final Early-Warning Model Selection

In [19]:
# ================================================================================
# KEYSTRA — PREDICTIVE SUPPLIER FAILURE SYSTEM
# PHASE 7 — PREDICTIVE MODEL IMPROVEMENT & THRESHOLD OPTIMISATION
# ================================================================================
#
# PURPOSE
# -------
# 1. Diagnose temporal target drift
# 2. Evaluate baseline probability calibration/behaviour
# 3. Optimise the operating threshold using VALIDATION ONLY
# 4. Compare alternative models
# 5. Select the strongest early-warning candidate
# 6. Evaluate the selected configuration once on the untouched TEST set
#
# IMPORTANT:
# - TEST SET IS NOT USED FOR THRESHOLD SELECTION
# - TEST SET IS USED ONLY FOR FINAL EVALUATION
# - Phase 6 baseline remains our benchmark
# - No Phase 3 future outcome component is used as a predictor
#
# ================================================================================

import numpy as np
import pandas as pd

from sklearn.base import clone
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer

from sklearn.ensemble import (
    RandomForestClassifier,
    HistGradientBoostingClassifier
)

from sklearn.metrics import (
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    average_precision_score,
    confusion_matrix,
    classification_report
)

from sklearn.inspection import permutation_importance


# ================================================================================
# 1. PHASE 7 HEADER
# ================================================================================

print("=" * 80)
print("KEYSTRA — PREDICTIVE SUPPLIER FAILURE SYSTEM")
print("PHASE 7 — PREDICTIVE MODEL IMPROVEMENT & THRESHOLD OPTIMISATION")
print("=" * 80)


# ================================================================================
# 2. REQUIRED OBJECT VALIDATION
# ================================================================================

required_objects = [
    "phase6_train",
    "phase6_validation",
    "phase6_test",
    "X_train",
    "X_validation",
    "X_test",
    "y_train",
    "y_validation",
    "y_test",
    "baseline_model",
    "phase6_model_results"
]

missing_objects = [
    obj for obj in required_objects
    if obj not in globals()
]

if missing_objects:
    raise ValueError(
        "Missing required Phase 6 objects:\n"
        + "\n".join(f" - {x}" for x in missing_objects)
    )

print("\n✓ Required Phase 6 objects detected")


# ================================================================================
# 3. BASIC DATA VALIDATION
# ================================================================================

print("\n" + "=" * 80)
print("PHASE 7 — INPUT VALIDATION")
print("=" * 80)

print(f"Train rows       : {len(X_train):,}")
print(f"Validation rows  : {len(X_validation):,}")
print(f"Test rows        : {len(X_test):,}")

print(f"Train failures      : {int(y_train.sum()):,}")
print(f"Validation failures : {int(y_validation.sum()):,}")
print(f"Test failures       : {int(y_test.sum()):,}")

train_rate = float(y_train.mean())
validation_rate = float(y_validation.mean())
test_rate = float(y_test.mean())

print(f"\nTrain failure rate      : {train_rate:.2%}")
print(f"Validation failure rate : {validation_rate:.2%}")
print(f"Test failure rate       : {test_rate:.2%}")


# ================================================================================
# 4. TEMPORAL TARGET DRIFT DIAGNOSTIC
# ================================================================================

print("\n" + "=" * 80)
print("TEMPORAL FAILURE-RATE DRIFT DIAGNOSTIC")
print("=" * 80)

def temporal_failure_summary(df, target):
    temp = df.copy()

    if "Observation_Date" not in temp.columns:
        raise ValueError(
            "Observation_Date is required for temporal drift analysis."
        )

    temp["Observation_Date"] = pd.to_datetime(
        temp["Observation_Date"],
        errors="coerce"
    )

    temp = temp.loc[temp["Observation_Date"].notna()].copy()

    temp["Year"] = temp["Observation_Date"].dt.year
    temp["Month"] = temp["Observation_Date"].dt.to_period("M").astype(str)

    yearly = (
        temp.groupby("Year")[target]
        .agg(
            Observations="size",
            Failures="sum",
            Failure_Rate="mean"
        )
        .reset_index()
    )

    monthly = (
        temp.groupby("Month")[target]
        .agg(
            Observations="size",
            Failures="sum",
            Failure_Rate="mean"
        )
        .reset_index()
    )

    return yearly, monthly


train_drift_df = phase6_train.copy()
validation_drift_df = phase6_validation.copy()
test_drift_df = phase6_test.copy()

train_drift_df["Supplier_Failure_Label"] = y_train.values
validation_drift_df["Supplier_Failure_Label"] = y_validation.values
test_drift_df["Supplier_Failure_Label"] = y_test.values

train_yearly, train_monthly = temporal_failure_summary(
    train_drift_df,
    "Supplier_Failure_Label"
)

validation_yearly, validation_monthly = temporal_failure_summary(
    validation_drift_df,
    "Supplier_Failure_Label"
)

test_yearly, test_monthly = temporal_failure_summary(
    test_drift_df,
    "Supplier_Failure_Label"
)

print("\nTRAIN — yearly failure rate")
print(train_yearly.to_string(index=False))

print("\nVALIDATION — yearly failure rate")
print(validation_yearly.to_string(index=False))

print("\nTEST — yearly failure rate")
print(test_yearly.to_string(index=False))


# ================================================================================
# 5. DRIFT SEVERITY
# ================================================================================

print("\n" + "=" * 80)
print("TEMPORAL DRIFT ASSESSMENT")
print("=" * 80)

train_to_validation_change = validation_rate - train_rate
validation_to_test_change = test_rate - validation_rate
train_to_test_change = test_rate - train_rate

print(
    f"Train → Validation absolute change : "
    f"{train_to_validation_change:+.2%}"
)

print(
    f"Validation → Test absolute change : "
    f"{validation_to_test_change:+.2%}"
)

print(
    f"Train → Test absolute change      : "
    f"{train_to_test_change:+.2%}"
)

if test_rate >= train_rate * 3:
    print(
        "\n⚠️ SIGNIFICANT TEMPORAL TARGET DRIFT DETECTED."
    )
    print(
        "Failure prevalence increases substantially over time."
    )
else:
    print(
        "\n✓ No extreme temporal target drift detected."
    )


# ================================================================================
# 6. PHASE 6 BASELINE PROBABILITIES
# ================================================================================

print("\n" + "=" * 80)
print("PHASE 6 BASELINE PROBABILITY GENERATION")
print("=" * 80)

baseline_validation_probability = baseline_model.predict_proba(
    X_validation
)[:, 1]

baseline_test_probability = baseline_model.predict_proba(
    X_test
)[:, 1]

print("✓ Validation probabilities generated")
print("✓ Test probabilities generated")


# ================================================================================
# 7. BASELINE THRESHOLD PERFORMANCE
# ================================================================================

def evaluate_threshold(
    y_true,
    probabilities,
    threshold
):
    predictions = (
        probabilities >= threshold
    ).astype(int)

    precision = precision_score(
        y_true,
        predictions,
        zero_division=0
    )

    recall = recall_score(
        y_true,
        predictions,
        zero_division=0
    )

    f1 = f1_score(
        y_true,
        predictions,
        zero_division=0
    )

    return {
        "Threshold": threshold,
        "Precision": precision,
        "Recall": recall,
        "F1": f1,
        "Predicted_Failure_Rate": predictions.mean()
    }


thresholds = np.round(
    np.arange(0.10, 0.91, 0.05),
    2
)

validation_threshold_results = pd.DataFrame(
    [
        evaluate_threshold(
            y_validation,
            baseline_validation_probability,
            threshold
        )
        for threshold in thresholds
    ]
)

print("\n" + "=" * 80)
print("BASELINE THRESHOLD ANALYSIS — VALIDATION")
print("=" * 80)

print(
    validation_threshold_results.to_string(
        index=False,
        formatters={
            "Precision": "{:.3f}".format,
            "Recall": "{:.3f}".format,
            "F1": "{:.3f}".format,
            "Predicted_Failure_Rate": "{:.3f}".format
        }
    )
)


# ================================================================================
# 8. BUSINESS-ORIENTED THRESHOLD SELECTION
# ================================================================================
#
# For supplier-risk early warning, missing a real future failure is more costly
# than generating an additional warning.
#
# We therefore prioritise recall while maintaining a minimum precision floor.
#
# The precision floor can be adjusted later if required.
# ================================================================================

MINIMUM_PRECISION = 0.50
TARGET_RECALL = 0.80

eligible_thresholds = validation_threshold_results[
    validation_threshold_results["Precision"]
    >= MINIMUM_PRECISION
].copy()

if eligible_thresholds.empty:
    raise ValueError(
        "No threshold satisfies the minimum validation precision requirement."
    )

high_recall_candidates = eligible_thresholds[
    eligible_thresholds["Recall"] >= TARGET_RECALL
].copy()

if not high_recall_candidates.empty:

    # Among thresholds achieving target recall,
    # choose the one with the highest F1.
    selected_threshold_row = (
        high_recall_candidates
        .sort_values(
            ["F1", "Recall", "Precision"],
            ascending=False
        )
        .iloc[0]
    )

    threshold_selection_reason = (
        f"Selected from thresholds achieving at least "
        f"{TARGET_RECALL:.0%} recall."
    )

else:

    # If 80% recall cannot be achieved while maintaining
    # the precision floor, select the strongest F1 threshold.
    selected_threshold_row = (
        eligible_thresholds
        .sort_values(
            ["F1", "Recall", "Precision"],
            ascending=False
        )
        .iloc[0]
    )

    threshold_selection_reason = (
        f"{TARGET_RECALL:.0%} recall target could not be achieved "
        "at the required precision floor; selected strongest F1."
    )


selected_threshold = float(
    selected_threshold_row["Threshold"]
)

print("\n" + "=" * 80)
print("VALIDATION THRESHOLD SELECTION")
print("=" * 80)

print(f"Minimum precision requirement : {MINIMUM_PRECISION:.0%}")
print(f"Target recall                 : {TARGET_RECALL:.0%}")
print(f"Selected threshold            : {selected_threshold:.2f}")
print(
    f"Validation precision          : "
    f"{selected_threshold_row['Precision']:.2%}"
)
print(
    f"Validation recall             : "
    f"{selected_threshold_row['Recall']:.2%}"
)
print(
    f"Validation F1                 : "
    f"{selected_threshold_row['F1']:.2%}"
)
print(
    f"Predicted failure rate        : "
    f"{selected_threshold_row['Predicted_Failure_Rate']:.2%}"
)
print(f"\nReason: {threshold_selection_reason}")


# ================================================================================
# 9. BASELINE TEST PERFORMANCE AT OPTIMISED THRESHOLD
# ================================================================================
#
# IMPORTANT:
# The threshold was chosen using VALIDATION.
# The TEST set is now evaluated using that frozen threshold.
# ================================================================================

baseline_test_predictions_optimised = (
    baseline_test_probability >= selected_threshold
).astype(int)

baseline_test_precision_optimised = precision_score(
    y_test,
    baseline_test_predictions_optimised,
    zero_division=0
)

baseline_test_recall_optimised = recall_score(
    y_test,
    baseline_test_predictions_optimised,
    zero_division=0
)

baseline_test_f1_optimised = f1_score(
    y_test,
    baseline_test_predictions_optimised,
    zero_division=0
)

baseline_test_pr_auc = average_precision_score(
    y_test,
    baseline_test_probability
)

baseline_test_roc_auc = roc_auc_score(
    y_test,
    baseline_test_probability
)

print("\n" + "=" * 80)
print("BASELINE — FINAL TEST EVALUATION AT FROZEN THRESHOLD")
print("=" * 80)

print(f"Threshold : {selected_threshold:.2f}")
print(f"Precision : {baseline_test_precision_optimised:.2%}")
print(f"Recall    : {baseline_test_recall_optimised:.2%}")
print(f"F1        : {baseline_test_f1_optimised:.2%}")
print(f"PR-AUC    : {baseline_test_pr_auc:.4f}")
print(f"ROC-AUC   : {baseline_test_roc_auc:.4f}")


# ================================================================================
# 10. PREPARE MODELING FEATURES
# ================================================================================

print("\n" + "=" * 80)
print("PHASE 7 — MODEL IMPROVEMENT")
print("=" * 80)

categorical_features = [
    c for c in X_train.columns
    if X_train[c].dtype == "object"
]

numeric_features = [
    c for c in X_train.columns
    if c not in categorical_features
]

print(f"Numeric features      : {len(numeric_features)}")
print(f"Categorical features  : {len(categorical_features)}")


# ================================================================================
# 11. BUILD PREPROCESSOR
# ================================================================================

numeric_transformer = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(strategy="median")
        )
    ]
)

categorical_transformer = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(strategy="most_frequent")
        ),
        (
            "onehot",
            OneHotEncoder(
                handle_unknown="ignore",
                sparse_output=False
            )
        )
    ]
)

preprocessor = ColumnTransformer(
    transformers=[
        (
            "num",
            numeric_transformer,
            numeric_features
        ),
        (
            "cat",
            categorical_transformer,
            categorical_features
        )
    ],
    remainder="drop"
)


# ================================================================================
# 12. IMPROVED MODEL — RANDOM FOREST
# ================================================================================
#
# Slightly stronger regularisation than the original baseline.
# ================================================================================

improved_rf = Pipeline(
    steps=[
        (
            "preprocessor",
            preprocessor
        ),
        (
            "model",
            RandomForestClassifier(
                n_estimators=400,
                max_depth=12,
                min_samples_leaf=15,
                max_features="sqrt",
                class_weight="balanced_subsample",
                random_state=42,
                n_jobs=-1
            )
        )
    ]
)


# ================================================================================
# 13. SECOND MODEL — HISTOGRAM GRADIENT BOOSTING
# ================================================================================
#
# We use a separate preprocessor because HGB requires numerical input.
# ================================================================================

hgb_preprocessor = ColumnTransformer(
    transformers=[
        (
            "num",
            SimpleImputer(strategy="median"),
            numeric_features
        ),
        (
            "cat",
            Pipeline(
                steps=[
                    (
                        "imputer",
                        SimpleImputer(
                            strategy="most_frequent"
                        )
                    ),
                    (
                        "onehot",
                        OneHotEncoder(
                            handle_unknown="ignore",
                            sparse_output=False
                        )
                    )
                ]
            ),
            categorical_features
        )
    ],
    remainder="drop"
)

hgb_model = Pipeline(
    steps=[
        (
            "preprocessor",
            hgb_preprocessor
        ),
        (
            "model",
            HistGradientBoostingClassifier(
                max_iter=300,
                learning_rate=0.05,
                max_leaf_nodes=31,
                min_samples_leaf=30,
                l2_regularization=1.0,
                random_state=42
            )
        )
    ]
)


# ================================================================================
# 14. TRAIN IMPROVED RANDOM FOREST
# ================================================================================

print("\nTraining improved Random Forest...")

improved_rf.fit(
    X_train,
    y_train
)

print("✓ Improved Random Forest trained")


# ================================================================================
# 15. TRAIN HISTOGRAM GRADIENT BOOSTING
# ================================================================================

print("\nTraining Gradient Boosting model...")

hgb_model.fit(
    X_train,
    y_train
)

print("✓ Gradient Boosting model trained")


# ================================================================================
# 16. VALIDATION PREDICTIONS
# ================================================================================

print("\nGenerating validation probabilities...")

improved_rf_validation_probability = improved_rf.predict_proba(
    X_validation
)[:, 1]

hgb_validation_probability = hgb_model.predict_proba(
    X_validation
)[:, 1]

print("✓ Validation probabilities generated")


# ================================================================================
# 17. MODEL COMPARISON USING VALIDATION PR-AUC
# ================================================================================

model_validation_results = pd.DataFrame({

    "Model": [
        "Phase 6 Baseline Random Forest",
        "Improved Random Forest",
        "Histogram Gradient Boosting"
    ],

    "PR_AUC": [
        average_precision_score(
            y_validation,
            baseline_validation_probability
        ),

        average_precision_score(
            y_validation,
            improved_rf_validation_probability
        ),

        average_precision_score(
            y_validation,
            hgb_validation_probability
        )
    ],

    "ROC_AUC": [
        roc_auc_score(
            y_validation,
            baseline_validation_probability
        ),

        roc_auc_score(
            y_validation,
            improved_rf_validation_probability
        ),

        roc_auc_score(
            y_validation,
            hgb_validation_probability
        )
    ]
})

model_validation_results = (
    model_validation_results
    .sort_values("PR_AUC", ascending=False)
    .reset_index(drop=True)
)

print("\n" + "=" * 80)
print("MODEL COMPARISON — VALIDATION")
print("=" * 80)

print(
    model_validation_results.to_string(
        index=False,
        formatters={
            "PR_AUC": "{:.4f}".format,
            "ROC_AUC": "{:.4f}".format
        }
    )
)


# ================================================================================
# 18. SELECT BEST MODEL USING VALIDATION PR-AUC
# ================================================================================

best_model_name = model_validation_results.iloc[0]["Model"]

if best_model_name == "Phase 6 Baseline Random Forest":

    best_model = baseline_model
    best_validation_probability = baseline_validation_probability

elif best_model_name == "Improved Random Forest":

    best_model = improved_rf
    best_validation_probability = improved_rf_validation_probability

elif best_model_name == "Histogram Gradient Boosting":

    best_model = hgb_model
    best_validation_probability = hgb_validation_probability

else:
    raise ValueError(
        f"Unknown selected model: {best_model_name}"
    )

print("\n" + "=" * 80)
print("BEST MODEL SELECTION")
print("=" * 80)

print(f"Selected model : {best_model_name}")
print(
    f"Validation PR-AUC : "
    f"{average_precision_score(y_validation, best_validation_probability):.4f}"
)


# ================================================================================
# 19. OPTIMISE THRESHOLD FOR SELECTED MODEL
# ================================================================================

best_model_threshold_results = pd.DataFrame(
    [
        evaluate_threshold(
            y_validation,
            best_validation_probability,
            threshold
        )
        for threshold in thresholds
    ]
)

eligible_best = best_model_threshold_results[
    best_model_threshold_results["Precision"]
    >= MINIMUM_PRECISION
].copy()

if eligible_best.empty:
    raise ValueError(
        "Selected model has no threshold satisfying "
        "the minimum precision requirement."
    )

high_recall_best = eligible_best[
    eligible_best["Recall"] >= TARGET_RECALL
].copy()

if not high_recall_best.empty:

    best_threshold_row = (
        high_recall_best
        .sort_values(
            ["F1", "Recall", "Precision"],
            ascending=False
        )
        .iloc[0]
    )

else:

    best_threshold_row = (
        eligible_best
        .sort_values(
            ["F1", "Recall", "Precision"],
            ascending=False
        )
        .iloc[0]
    )


final_operating_threshold = float(
    best_threshold_row["Threshold"]
)

print("\n" + "=" * 80)
print("FINAL OPERATING THRESHOLD — VALIDATION")
print("=" * 80)

print(
    f"Selected model              : {best_model_name}"
)

print(
    f"Operating threshold         : "
    f"{final_operating_threshold:.2f}"
)

print(
    f"Validation precision        : "
    f"{best_threshold_row['Precision']:.2%}"
)

print(
    f"Validation recall           : "
    f"{best_threshold_row['Recall']:.2%}"
)

print(
    f"Validation F1               : "
    f"{best_threshold_row['F1']:.2%}"
)

print(
    f"Predicted warning rate      : "
    f"{best_threshold_row['Predicted_Failure_Rate']:.2%}"
)


# ================================================================================
# 20. FINAL TEST EVALUATION
# ================================================================================
#
# Only NOW do we touch the test set with the selected model + frozen threshold.
# ================================================================================

print("\n" + "=" * 80)
print("FINAL TEST EVALUATION")
print("=" * 80)

if best_model_name == "Phase 6 Baseline Random Forest":

    final_test_probability = baseline_test_probability

else:

    final_test_probability = best_model.predict_proba(
        X_test
    )[:, 1]


final_test_prediction = (
    final_test_probability
    >= final_operating_threshold
).astype(int)


final_precision = precision_score(
    y_test,
    final_test_prediction,
    zero_division=0
)

final_recall = recall_score(
    y_test,
    final_test_prediction,
    zero_division=0
)

final_f1 = f1_score(
    y_test,
    final_test_prediction,
    zero_division=0
)

final_pr_auc = average_precision_score(
    y_test,
    final_test_probability
)

final_roc_auc = roc_auc_score(
    y_test,
    final_test_probability
)

final_cm = confusion_matrix(
    y_test,
    final_test_prediction
)


print(f"Model              : {best_model_name}")
print(f"Threshold           : {final_operating_threshold:.2f}")
print(f"Precision            : {final_precision:.2%}")
print(f"Recall               : {final_recall:.2%}")
print(f"F1                   : {final_f1:.2%}")
print(f"PR-AUC               : {final_pr_auc:.4f}")
print(f"ROC-AUC              : {final_roc_auc:.4f}")

print("\nConfusion Matrix")
print(
    pd.DataFrame(
        final_cm,
        index=["Actual Stable", "Actual Failure"],
        columns=["Predicted Stable", "Predicted Failure"]
    )
)


# ================================================================================
# 21. FINAL CLASSIFICATION REPORT
# ================================================================================

print("\n" + "=" * 80)
print("FINAL TEST CLASSIFICATION REPORT")
print("=" * 80)

print(
    classification_report(
        y_test,
        final_test_prediction,
        target_names=[
            "No Future Failure",
            "Future Failure"
        ],
        zero_division=0
    )
)


# ================================================================================
# 22. BASELINE VS FINAL MODEL
# ================================================================================

phase6_test_recall = recall_score(
    y_test,
    (
        baseline_test_probability >= 0.50
    ).astype(int),
    zero_division=0
)

phase6_test_precision = precision_score(
    y_test,
    (
        baseline_test_probability >= 0.50
    ).astype(int),
    zero_division=0
)

phase6_test_f1 = f1_score(
    y_test,
    (
        baseline_test_probability >= 0.50
    ).astype(int),
    zero_division=0
)

comparison = pd.DataFrame({

    "Metric": [
        "Precision",
        "Recall",
        "F1",
        "PR-AUC",
        "ROC-AUC"
    ],

    "Phase_6_Baseline": [
        phase6_test_precision,
        phase6_test_recall,
        phase6_test_f1,
        average_precision_score(
            y_test,
            baseline_test_probability
        ),
        roc_auc_score(
            y_test,
            baseline_test_probability
        )
    ],

    "Phase_7_Final": [
        final_precision,
        final_recall,
        final_f1,
        final_pr_auc,
        final_roc_auc
    ]
})

comparison["Change"] = (
    comparison["Phase_7_Final"]
    - comparison["Phase_6_Baseline"]
)

print("\n" + "=" * 80)
print("PHASE 6 BASELINE VS PHASE 7 FINAL")
print("=" * 80)

print(
    comparison.to_string(
        index=False,
        formatters={
            "Phase_6_Baseline": "{:.4f}".format,
            "Phase_7_Final": "{:.4f}".format,
            "Change": "{:+.4f}".format
        }
    )
)


# ================================================================================
# 23. EARLY-WARNING PERFORMANCE DIAGNOSTIC
# ================================================================================

print("\n" + "=" * 80)
print("EARLY-WARNING PERFORMANCE DIAGNOSTIC")
print("=" * 80)

missed_failures = int(
    (
        (y_test == 1)
        & (final_test_prediction == 0)
    ).sum()
)

detected_failures = int(
    (
        (y_test == 1)
        & (final_test_prediction == 1)
    ).sum()
)

false_warnings = int(
    (
        (y_test == 0)
        & (final_test_prediction == 1)
    ).sum()
)

correct_stable = int(
    (
        (y_test == 0)
        & (final_test_prediction == 0)
    ).sum()
)

print(f"Future failures detected : {detected_failures:,}")
print(f"Future failures missed   : {missed_failures:,}")
print(f"False warnings           : {false_warnings:,}")
print(f"Correct stable cases     : {correct_stable:,}")

print(
    f"\nFailure detection rate   : "
    f"{detected_failures / max(int(y_test.sum()), 1):.2%}"
)

print(
    f"False-warning rate       : "
    f"{false_warnings / max(int((y_test == 0).sum()), 1):.2%}"
)


# ================================================================================
# 24. MODEL INTERPRETABILITY — PERMUTATION IMPORTANCE
# ================================================================================
#
# Only run for models that support sklearn permutation importance through
# predict_proba. This is calculated on VALIDATION, not TEST, so that the
# test set remains a final evaluation set.
# ================================================================================

print("\n" + "=" * 80)
print("FEATURE IMPORTANCE DIAGNOSTIC — VALIDATION")
print("=" * 80)

try:

    importance_sample_size = min(
        10000,
        len(X_validation)
    )

    importance_sample = X_validation.iloc[
        :importance_sample_size
    ].copy()

    importance_target = y_validation.iloc[
        :importance_sample_size
    ].copy()

    permutation_result = permutation_importance(
        best_model,
        importance_sample,
        importance_target,
        scoring="average_precision",
        n_repeats=3,
        random_state=42,
        n_jobs=-1
    )

    feature_importance = pd.DataFrame({
        "Feature": X_validation.columns,
        "Importance_Mean": permutation_result.importances_mean,
        "Importance_STD": permutation_result.importances_std
    })

    feature_importance = (
        feature_importance
        .sort_values(
            "Importance_Mean",
            ascending=False
        )
        .reset_index(drop=True)
    )

    print("\nTop 20 predictive features:\n")

    print(
        feature_importance.head(20).to_string(
            index=False,
            formatters={
                "Importance_Mean": "{:.6f}".format,
                "Importance_STD": "{:.6f}".format
            }
        )
    )

except Exception as e:

    feature_importance = pd.DataFrame()

    print(
        f"⚠️ Feature importance diagnostic could not be completed: {e}"
    )


# ================================================================================
# 25. FINAL PHASE 7 OBJECT
# ================================================================================

phase7_model_results = pd.DataFrame({

    "Model": [
        best_model_name
    ],

    "Operating_Threshold": [
        final_operating_threshold
    ],

    "Validation_Precision": [
        best_threshold_row["Precision"]
    ],

    "Validation_Recall": [
        best_threshold_row["Recall"]
    ],

    "Validation_F1": [
        best_threshold_row["F1"]
    ],

    "Test_Precision": [
        final_precision
    ],

    "Test_Recall": [
        final_recall
    ],

    "Test_F1": [
        final_f1
    ],

    "Test_PR_AUC": [
        final_pr_auc
    ],

    "Test_ROC_AUC": [
        final_roc_auc
    ]
})


# ================================================================================
# 26. FINAL VALIDATION CHECKS
# ================================================================================

print("\n" + "=" * 80)
print("PHASE 7 — FINAL HARD VALIDATION")
print("=" * 80)

checks = {

    "Validation probabilities generated":
        len(best_validation_probability) == len(y_validation),

    "Test probabilities generated":
        len(final_test_probability) == len(y_test),

    "Binary predictions generated":
        set(np.unique(final_test_prediction)).issubset({0, 1}),

    "Threshold selected from validation":
        True,

    "Test evaluated after threshold selection":
        True,

    "No future target used as predictor":
        "Supplier_Failure_Label" not in X_train.columns,

    "Temporal split preserved":
        phase6_train["Observation_Date"].max()
        < phase6_validation["Observation_Date"].min(),

    "Validation before test":
        phase6_validation["Observation_Date"].max()
        < phase6_test["Observation_Date"].min(),

    "Final model produces finite probabilities":
        np.isfinite(final_test_probability).all()
}

for check_name, check_result in checks.items():

    if check_result:
        print(f"✓ {check_name}")
    else:
        print(f"✗ FAILED — {check_name}")


if not all(checks.values()):

    raise ValueError(
        "Phase 7 hard validation failed. "
        "Review the failed checks before proceeding."
    )


# ================================================================================
# 27. PHASE 7 SUMMARY
# ================================================================================

print("\n" + "=" * 80)
print("PHASE 7 FINAL SUMMARY")
print("=" * 80)

print(f"Selected model            : {best_model_name}")
print(f"Operating threshold       : {final_operating_threshold:.2f}")

print(
    f"Validation recall         : "
    f"{best_threshold_row['Recall']:.2%}"
)

print(
    f"Validation precision      : "
    f"{best_threshold_row['Precision']:.2%}"
)

print(
    f"Final test recall         : "
    f"{final_recall:.2%}"
)

print(
    f"Final test precision      : "
    f"{final_precision:.2%}"
)

print(
    f"Final test F1             : "
    f"{final_f1:.2%}"
)

print(
    f"Final test PR-AUC         : "
    f"{final_pr_auc:.4f}"
)

print(
    f"Final test ROC-AUC        : "
    f"{final_roc_auc:.4f}"
)

print("\n" + "=" * 80)
print("PHASE 7 FINAL OBJECTS")
print("=" * 80)

print("  phase7_model_results")
print("  best_model")
print("  final_operating_threshold")
print("  final_test_probability")
print("  final_test_prediction")
print("  comparison")
print("  feature_importance")

print("\n" + "=" * 80)
print("✓ PHASE 7 — PREDICTIVE MODEL IMPROVEMENT COMPLETED")
print("=" * 80)

print("""
Next stage:
  Phase 8 — Early-Warning Engine
  → Supplier risk probability
  → Warning severity
  → Alert prioritisation
  → Explainable risk drivers
  → Recommended intervention
""")

================================================================================
KEYSTRA — PREDICTIVE SUPPLIER FAILURE SYSTEM
PHASE 7 — PREDICTIVE MODEL IMPROVEMENT & THRESHOLD OPTIMISATION
================================================================================

✓ Required Phase 6 objects detected

================================================================================
PHASE 7 — INPUT VALIDATION
================================================================================
Train rows       : 96,995
Validation rows  : 20,849
Test rows        : 21,109
Train failures      : 2,009
Validation failures : 1,873
Test failures       : 6,942

Train failure rate      : 2.07%
Validation failure rate : 8.98%
Test failure rate       : 32.89%

================================================================================
TEMPORAL FAILURE-RATE DRIFT DIAGNOSTIC
================================================================================

TRAIN — yearly failure rate
 Year  Observations  Failures  Failure_Rate
 2022         26538        67      0.002525
 2023         31655       295      0.009319
 2024         31573      1192      0.037754
 2025          7229       455      0.062941

VALIDATION — yearly failure rate
 Year  Observations  Failures  Failure_Rate
 2025         20849      1873      0.089836

TEST — yearly failure rate
 Year  Observations  Failures  Failure_Rate
 2025          2869       287      0.100035
 2026         18240      6655      0.364857

================================================================================
TEMPORAL DRIFT ASSESSMENT
================================================================================
Train → Validation absolute change : +6.91%
Validation → Test absolute change : +23.90%
Train → Test absolute change      : +30.82%

⚠️ SIGNIFICANT TEMPORAL TARGET DRIFT DETECTED.
Failure prevalence increases substantially over time.

================================================================================
PHASE 6 BASELINE PROBABILITY GENERATION
================================================================================
✓ Validation probabilities generated
✓ Test probabilities generated

================================================================================
BASELINE THRESHOLD ANALYSIS — VALIDATION
================================================================================
 Threshold Precision Recall    F1 Predicted_Failure_Rate
      0.10     0.474  1.000 0.643                  0.190
      0.15     0.489  0.999 0.657                  0.184
      0.20     0.506  0.999 0.672                  0.177
      0.25     0.521  0.999 0.685                  0.172
      0.30     0.536  0.991 0.696                  0.166
      0.35     0.561  0.990 0.716                  0.159
      0.40     0.576  0.988 0.728                  0.154
      0.45     0.593  0.983 0.740                  0.149
      0.50     0.611  0.970 0.750                  0.143
      0.55     0.623  0.958 0.755                  0.138
      0.60     0.647  0.951 0.770                  0.132
      0.65     0.665  0.939 0.778                  0.127
      0.70     0.684  0.917 0.783                  0.120
      0.75     0.712  0.905 0.797                  0.114
      0.80     0.748  0.872 0.805                  0.105
      0.85     0.786  0.821 0.803                  0.094
      0.90     0.852  0.720 0.780                  0.076

================================================================================
VALIDATION THRESHOLD SELECTION
================================================================================
Minimum precision requirement : 50%
Target recall                 : 80%
Selected threshold            : 0.80
Validation precision          : 74.84%
Validation recall             : 87.19%
Validation F1                 : 80.54%
Predicted failure rate        : 10.47%

Reason: Selected from thresholds achieving at least 80% recall.

================================================================================
BASELINE — FINAL TEST EVALUATION AT FROZEN THRESHOLD
================================================================================
Threshold : 0.80
Precision : 90.10%
Recall    : 36.20%
F1        : 51.65%
PR-AUC    : 0.8878
ROC-AUC   : 0.9598

================================================================================
PHASE 7 — MODEL IMPROVEMENT
================================================================================
Numeric features      : 51
Categorical features  : 3

Training improved Random Forest...
✓ Improved Random Forest trained

Training Gradient Boosting model...
✓ Gradient Boosting model trained

Generating validation probabilities...
✓ Validation probabilities generated

================================================================================
MODEL COMPARISON — VALIDATION
================================================================================
                         Model PR_AUC ROC_AUC
   Histogram Gradient Boosting 0.9482  0.9950
        Improved Random Forest 0.9057  0.9908
Phase 6 Baseline Random Forest 0.8795  0.9881

================================================================================
BEST MODEL SELECTION
================================================================================
Selected model : Histogram Gradient Boosting
Validation PR-AUC : 0.9482

================================================================================
FINAL OPERATING THRESHOLD — VALIDATION
================================================================================
Selected model              : Histogram Gradient Boosting
Operating threshold         : 0.30
Validation precision        : 84.21%
Validation recall           : 93.65%
Validation F1               : 88.68%
Predicted warning rate      : 9.99%

================================================================================
FINAL TEST EVALUATION
================================================================================
Model              : Histogram Gradient Boosting
Threshold           : 0.30
Precision            : 95.27%
Recall               : 87.05%
F1                   : 90.97%
PR-AUC               : 0.9721
ROC-AUC              : 0.9893

Confusion Matrix
                Predicted Stable  Predicted Failure
Actual Stable              13867                300
Actual Failure               899               6043

================================================================================
FINAL TEST CLASSIFICATION REPORT
================================================================================
                   precision    recall  f1-score   support

No Future Failure       0.94      0.98      0.96     14167
   Future Failure       0.95      0.87      0.91      6942

         accuracy                           0.94     21109
        macro avg       0.95      0.92      0.93     21109
     weighted avg       0.94      0.94      0.94     21109


================================================================================
PHASE 6 BASELINE VS PHASE 7 FINAL
================================================================================
   Metric Phase_6_Baseline Phase_7_Final  Change
Precision           0.8613        0.9527 +0.0914
   Recall           0.6645        0.8705 +0.2060
       F1           0.7502        0.9097 +0.1595
   PR-AUC           0.8878        0.9721 +0.0843
  ROC-AUC           0.9598        0.9893 +0.0295

================================================================================
EARLY-WARNING PERFORMANCE DIAGNOSTIC
================================================================================
Future failures detected : 6,043
Future failures missed   : 899
False warnings           : 300
Correct stable cases     : 13,867

Failure detection rate   : 87.05%
False-warning rate       : 2.12%

================================================================================
FEATURE IMPORTANCE DIAGNOSTIC — VALIDATION
================================================================================

Top 20 predictive features:

                                  Feature Importance_Mean Importance_STD
                     Rolling_90D_PO_Count        0.210986       0.011581
                   Fulfilment_Risk_Signal        0.190175       0.008163
               Recent_90D_Fulfilment_Rate        0.129025       0.005742
     Rolling_90D_Partial_Fulfilment_Count        0.027404       0.007537
         Rolling_90D_Outstanding_Quantity        0.017244       0.001885
        Recent_90D_Average_Delivery_Delay        0.013517       0.002614
        Fulfilment_Deviation_From_History        0.010953       0.001615
               Total_Current_Risk_Signals        0.010938       0.002394
Partial_Fulfilment_Deviation_From_History        0.008334       0.001975
             Current_Outstanding_Quantity        0.006580       0.000991
             Rolling_90D_Ordered_Quantity        0.006425       0.000273
               Historical_Fulfilment_Rate        0.003808       0.000323
                         Risk_State_Score        0.003313       0.000635
       Historical_Partial_Fulfilment_Rate        0.002383       0.001120
   Rolling_90D_Outstanding_Quantity_Ratio        0.002236       0.002047
                 Supplier_Risk_State_Code        0.001840       0.000027
                    Risk_State_Transition        0.001236       0.000106
                  Failure_Dimension_Count        0.001229       0.000136
                        Observation_Month        0.001106       0.000496
            Rolling_90D_Received_Quantity        0.000814       0.000165

================================================================================
PHASE 7 — FINAL HARD VALIDATION
================================================================================
✓ Validation probabilities generated
✓ Test probabilities generated
✓ Binary predictions generated
✓ Threshold selected from validation
✓ Test evaluated after threshold selection
✓ No future target used as predictor
✓ Temporal split preserved
✓ Validation before test
✓ Final model produces finite probabilities

================================================================================
PHASE 7 FINAL SUMMARY
================================================================================
Selected model            : Histogram Gradient Boosting
Operating threshold       : 0.30
Validation recall         : 93.65%
Validation precision      : 84.21%
Final test recall         : 87.05%
Final test precision      : 95.27%
Final test F1             : 90.97%
Final test PR-AUC         : 0.9721
Final test ROC-AUC        : 0.9893

================================================================================
PHASE 7 FINAL OBJECTS
================================================================================
  phase7_model_results
  best_model
  final_operating_threshold
  final_test_probability
  final_test_prediction
  comparison
  feature_importance

================================================================================
✓ PHASE 7 — PREDICTIVE MODEL IMPROVEMENT COMPLETED
================================================================================

Next stage:
  Phase 8 — Early-Warning Engine
  → Supplier risk probability
  → Warning severity
  → Alert prioritisation
  → Explainable risk drivers
  → Recommended intervention

In [20]:
# ================================================================================
# KEYSTRA — PREDICTIVE SUPPLIER FAILURE SYSTEM
# PHASE 8 — SUPPLIER EARLY-WARNING & RISK PRIORITISATION ENGINE
# CORRECTED VERSION — MODEL INPUT ALIGNMENT
# ================================================================================
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix
print("=" * 80)
print("KEYSTRA — PREDICTIVE SUPPLIER FAILURE SYSTEM")
print("PHASE 8 — SUPPLIER EARLY-WARNING & RISK PRIORITISATION ENGINE")
print("=" * 80)
# ================================================================================
# 1. REQUIRED OBJECT VALIDATION
# ================================================================================
required_objects = [
    "fact_supplier_model_ready",
    "fact_supplier_risk_state",
    "best_model",
    "final_operating_threshold"
]
missing_objects = [
    obj for obj in required_objects
    if obj not in globals()
]
if missing_objects:
    raise RuntimeError(
        "Missing required Phase 8 objects:\n"
        + "\n".join(f" - {x}" for x in missing_objects)
    )
print("\n✓ Required Phase 5, Phase 4 and Phase 7 objects detected")
# ================================================================================
# 2. COPY INPUTS — NEVER MODIFY ORIGINAL OBJECTS
# ================================================================================
model_ready = fact_supplier_model_ready.copy()
risk_state = fact_supplier_risk_state.copy()
# ================================================================================
# 3. BASIC VALIDATION
# ================================================================================
required_model_columns = [
    "Supplier_ID",
    "Observation_Date"
]
required_state_columns = [
    "Supplier_ID",
    "Observation_Date",
    "Supplier_Risk_State",
    "Previous_Risk_State",
    "Risk_State_Transition",
    "Supplier_Risk_State_Code",
    "Risk_State_Score",
    "Deterioration_Signal_Count",
    "Severe_Signal_Count",
    "Failure_Dimension_Count",
    "Persistent_Deterioration"
]
for col in required_model_columns:
    if col not in model_ready.columns:
        raise ValueError(
            f"Missing required model-ready column: {col}"
        )
for col in required_state_columns:
    if col not in risk_state.columns:
        raise ValueError(
            f"Missing required Phase 4 column: {col}"
        )
# ================================================================================
# 4. NORMALISE DATES
# ================================================================================
model_ready["Observation_Date"] = pd.to_datetime(
    model_ready["Observation_Date"]
)
risk_state["Observation_Date"] = pd.to_datetime(
    risk_state["Observation_Date"]
)
print("\n" + "=" * 80)
print("PHASE 8 — INPUT VALIDATION")
print("=" * 80)
print(f"Model-ready rows : {len(model_ready):,}")
print(f"Risk-state rows  : {len(risk_state):,}")
print("✓ Required columns validated")
# ================================================================================
# 5. IDENTIFY THE ACTUAL MODEL PREDICTOR COLUMNS
# ================================================================================
# best_model is expected to be the Phase 7 fitted pipeline.
# Extract the exact columns the preprocessing stage expects.
model_predictor_columns = None
try:
    # Most likely structure:
    # Pipeline -> ColumnTransformer -> estimator
    preprocessor = best_model.named_steps.get(
        "preprocessor",
        None
    )
    if preprocessor is not None:
        transformer_columns = []
        for _, _, cols in preprocessor.transformers_:
            if isinstance(cols, (list, tuple, np.ndarray, pd.Index)):
                transformer_columns.extend(list(cols))
        model_predictor_columns = list(
            dict.fromkeys(transformer_columns)
        )
except Exception:
    model_predictor_columns = None
# Fallback to the Phase 6/7 predictor list if extraction fails.
if not model_predictor_columns:
    excluded_columns = [
        "Observation_Date",
        "Supplier_Failure_Label",
        "Supplier_ID"
    ]
    model_predictor_columns = [
        col
        for col in model_ready.columns
        if col not in excluded_columns
    ]
print(f"\nPredictor columns expected by model : "
      f"{len(model_predictor_columns)}")
# ================================================================================
# 6. BUILD CURRENT SUPPLIER SNAPSHOT
# ================================================================================
latest_model_date = model_ready["Observation_Date"].max()
current_model = (
    model_ready[
        model_ready["Observation_Date"] == latest_model_date
    ]
    .copy()
)
print("\n" + "=" * 80)
print("CURRENT SUPPLIER SNAPSHOT")
print("=" * 80)
print(f"Latest modelling date : {latest_model_date.date()}")
print(f"Suppliers evaluated   : {current_model['Supplier_ID'].nunique():,}")
# ================================================================================
# 7. ADD PHASE 4 RISK-STATE INFORMATION
#
# THIS IS THE FIX FOR THE ERROR.
#
# The Phase 7 model requires:
#   Supplier_Risk_State
#   Previous_Risk_State
#   Risk_State_Transition
#
# They are stored in fact_supplier_risk_state, so we join them using:
#
#       Supplier_ID + Observation_Date
#
# This preserves temporal alignment.
# ================================================================================
state_features = [
    "Supplier_ID",
    "Observation_Date",
    "Supplier_Risk_State",
    "Previous_Risk_State",
    "Risk_State_Transition",
    "Supplier_Risk_State_Code",
    "Risk_State_Score",
    "Deterioration_Signal_Count",
    "Severe_Signal_Count",
    "Failure_Dimension_Count",
    "Persistent_Deterioration"
]
state_snapshot = (
    risk_state[state_features]
    .copy()
)
state_snapshot = (
    state_snapshot[
        state_snapshot["Observation_Date"] == latest_model_date
    ]
    .copy()
)
# Check grain before merge
if state_snapshot.duplicated(
    ["Supplier_ID", "Observation_Date"]
).any():
    duplicates = state_snapshot[
        state_snapshot.duplicated(
            ["Supplier_ID", "Observation_Date"],
            keep=False
        )
    ]
    raise ValueError(
        "Phase 4 current snapshot contains duplicate "
        "Supplier × Date rows.\n"
        f"Duplicate rows: {len(duplicates)}"
    )
current_snapshot = current_model.merge(
    state_snapshot,
    on=["Supplier_ID", "Observation_Date"],
    how="left",
    suffixes=("", "_phase4")
)
# ================================================================================
# 8. RESOLVE POSSIBLE DUPLICATE PHASE 4 COLUMNS
# ================================================================================
for col in [
    "Supplier_Risk_State",
    "Previous_Risk_State",
    "Risk_State_Transition",
    "Supplier_Risk_State_Code",
    "Risk_State_Score",
    "Deterioration_Signal_Count",
    "Severe_Signal_Count",
    "Failure_Dimension_Count",
    "Persistent_Deterioration"
]:
    phase4_col = f"{col}_phase4"
    if phase4_col in current_snapshot.columns:
        # If original column is missing/blank,
        # use the Phase 4 version.
        if col not in current_snapshot.columns:
            current_snapshot[col] = current_snapshot[phase4_col]
        else:
            current_snapshot[col] = (
                current_snapshot[col]
                .combine_first(current_snapshot[phase4_col])
            )
        current_snapshot.drop(
            columns=[phase4_col],
            inplace=True
        )
# ================================================================================
# 9. CRITICAL MODEL-INPUT CHECK
# ================================================================================
missing_model_inputs = [
    col
    for col in model_predictor_columns
    if col not in current_snapshot.columns
]
if missing_model_inputs:
    raise ValueError(
        "Current supplier snapshot is still missing model inputs:\n"
        + "\n".join(f" - {x}" for x in missing_model_inputs)
    )
# Check categorical fields specifically.
required_categorical = [
    "Supplier_Risk_State",
    "Previous_Risk_State",
    "Risk_State_Transition"
]
missing_categorical = [
    col
    for col in required_categorical
    if col not in current_snapshot.columns
]
if missing_categorical:
    raise ValueError(
        "Required categorical risk-state fields are missing:\n"
        + "\n".join(f" - {x}" for x in missing_categorical)
    )
print("\n✓ Phase 4 categorical risk-state fields successfully attached")
# ================================================================================
# 10. CHECK CATEGORICAL VALUES
# ================================================================================
for col in required_categorical:
    missing_values = current_snapshot[col].isna().sum()
    if missing_values > 0:
        print(
            f"⚠️ {col}: {missing_values:,} missing values"
        )
    else:
        print(
            f"✓ {col}: complete"
        )
# ================================================================================
# 11. CREATE EXACT MODEL INPUT
# ================================================================================
X_current = (
    current_snapshot[
        model_predictor_columns
    ]
    .copy()
)
# ================================================================================
# 12. HANDLE NUMERIC MISSING VALUES
# ================================================================================
numeric_columns = X_current.select_dtypes(
    include=[np.number]
).columns
for col in numeric_columns:
    X_current[col] = (
        pd.to_numeric(
            X_current[col],
            errors="coerce"
        )
    )
    X_current[col] = (
        X_current[col]
        .replace([np.inf, -np.inf], np.nan)
    )
# Do NOT blindly fill categorical fields with arbitrary values.
# The Phase 7 pipeline should handle known categories.
for col in required_categorical:
    if col in X_current.columns:
        X_current[col] = (
            X_current[col]
            .astype(object)
        )
# ================================================================================
# 13. FINAL MODEL INPUT ALIGNMENT CHECK
# ================================================================================
if list(X_current.columns) != model_predictor_columns:
    X_current = X_current.reindex(
        columns=model_predictor_columns
    )
if X_current.shape[1] != len(model_predictor_columns):
    raise RuntimeError(
        "Model input column count mismatch."
    )
print("\n" + "=" * 80)
print("PHASE 8 — MODEL INPUT ALIGNMENT")
print("=" * 80)
print(f"Current suppliers       : {len(X_current):,}")
print(f"Predictor columns       : {X_current.shape[1]:,}")
print(f"Expected predictors     : {len(model_predictor_columns):,}")
print("✓ Current snapshot aligned with Phase 7 model")
# ================================================================================
# 14. SCORE CURRENT SUPPLIERS
# ================================================================================
print("\n" + "=" * 80)
print("PHASE 8 — CURRENT SUPPLIER FAILURE PROBABILITY")
print("=" * 80)
try:
    current_probability = (
        best_model
        .predict_proba(X_current)[:, 1]
    )
except Exception as e:
    raise RuntimeError(
        "Phase 7 model could not score the corrected "
        "Phase 8 supplier snapshot.\n"
        f"Model error: {e}"
    )
current_snapshot[
    "Supplier_Failure_Probability"
] = current_probability
# ================================================================================
# 15. OPERATING THRESHOLD
# ================================================================================
threshold = float(final_operating_threshold)
current_snapshot[
    "Failure_Warning_Flag"
] = (
    current_snapshot[
        "Supplier_Failure_Probability"
    ] >= threshold
)
print(f"Operating threshold : {threshold:.2f}")
print(
    f"Suppliers above threshold : "
    f"{current_snapshot['Failure_Warning_Flag'].sum():,}"
)
# ================================================================================
# 16. WARNING SEVERITY
# ================================================================================
def classify_warning(probability):
    if probability >= 0.80:
        return "Critical"
    elif probability >= threshold:
        return "High"
    elif probability >= 0.20:
        return "Moderate"
    else:
        return "Low"
current_snapshot[
    "Warning_Severity"
] = current_snapshot[
    "Supplier_Failure_Probability"
].apply(classify_warning)
# ================================================================================
# 17. RISK PRIORITY SCORE
#
# Combines:
#   - predicted future failure probability
#   - current risk-state severity
#   - operational risk signals
#
# This is for prioritisation, not model training.
# ================================================================================
risk_state_score = pd.to_numeric(
    current_snapshot.get(
        "Risk_State_Score",
        pd.Series(
            0,
            index=current_snapshot.index
        )
    ),
    errors="coerce"
).fillna(0)
risk_state_component = (
    risk_state_score /
    max(
        risk_state_score.max(),
        1
    )
)
current_snapshot[
    "Risk_Priority_Score"
] = (
    0.70 *
    current_snapshot[
        "Supplier_Failure_Probability"
    ]
    +
    0.30 *
    risk_state_component
)
# ================================================================================
# 18. PRIORITY RANK
# ================================================================================
current_snapshot = (
    current_snapshot
    .sort_values(
        "Risk_Priority_Score",
        ascending=False
    )
    .reset_index(drop=True)
)
current_snapshot[
    "Risk_Priority_Rank"
] = (
    np.arange(
        1,
        len(current_snapshot) + 1
    )
)
# ================================================================================
# 19. EARLY-WARNING DIAGNOSTIC
# ================================================================================
print("\n" + "=" * 80)
print("EARLY-WARNING SUMMARY")
print("=" * 80)
print(
    f"Suppliers evaluated       : "
    f"{len(current_snapshot):,}"
)
print(
    f"Critical warnings         : "
    f"{(
        current_snapshot['Warning_Severity'] == 'Critical'
    ).sum():,}"
)
print(
    f"High warnings             : "
    f"{(
        current_snapshot['Warning_Severity'] == 'High'
    ).sum():,}"
)
print(
    f"Moderate warnings         : "
    f"{(
        current_snapshot['Warning_Severity'] == 'Moderate'
    ).sum():,}"
)
print(
    f"Low warnings              : "
    f"{(
        current_snapshot['Warning_Severity'] == 'Low'
    ).sum():,}"
)
# ================================================================================
# 20. TOP SUPPLIER ALERTS
# ================================================================================
display_columns = [
    "Supplier_ID",
    "Observation_Date",
    "Supplier_Risk_State",
    "Supplier_Failure_Probability",
    "Failure_Warning_Flag",
    "Warning_Severity",
    "Risk_State_Score",
    "Deterioration_Signal_Count",
    "Severe_Signal_Count",
    "Failure_Dimension_Count",
    "Risk_Priority_Score",
    "Risk_Priority_Rank"
]
display_columns = [
    col
    for col in display_columns
    if col in current_snapshot.columns
]
print("\n" + "=" * 80)
print("TOP 20 SUPPLIER EARLY-WARNING ALERTS")
print("=" * 80)
display(
    current_snapshot[
        display_columns
    ].head(20)
)
# ================================================================================
# 21. STATE × WARNING SEVERITY
# ================================================================================
state_severity_summary = (
    current_snapshot
    .groupby(
        [
            "Supplier_Risk_State",
            "Warning_Severity"
        ],
        dropna=False
    )
    .agg(
        Suppliers=(
            "Supplier_ID",
            "nunique"
        ),
        Mean_Failure_Probability=(
            "Supplier_Failure_Probability",
            "mean"
        ),
        Max_Failure_Probability=(
            "Supplier_Failure_Probability",
            "max"
        )
    )
    .reset_index()
)
print("\n" + "=" * 80)
print("RISK STATE × WARNING SEVERITY")
print("=" * 80)
display(
    state_severity_summary
)
# ================================================================================
# 22. PHASE 8 HARD VALIDATION
# ================================================================================
print("\n" + "=" * 80)
print("PHASE 8 — FINAL HARD VALIDATION")
print("=" * 80)
assert (
    current_snapshot["Supplier_ID"]
    .nunique()
    ==
    len(current_snapshot)
), "Duplicate current supplier rows detected."
assert (
    current_snapshot[
        "Supplier_Failure_Probability"
    ]
    .between(0, 1)
    .all()
), "Invalid failure probabilities detected."
assert (
    current_snapshot[
        "Failure_Warning_Flag"
    ].dtype == bool
), "Warning flag is not boolean."
assert (
    current_snapshot[
        "Risk_Priority_Rank"
    ].is_unique
), "Risk priority ranks are not unique."
assert (
    current_snapshot[
        "Supplier_Risk_State"
    ].notna().all()
), "Missing supplier risk states detected."
assert (
    current_snapshot[
        "Previous_Risk_State"
    ].notna().all()
), "Missing previous risk states detected."
assert (
    current_snapshot[
        "Risk_State_Transition"
    ].notna().all()
), "Missing risk-state transitions detected."
print("✓ One current observation per supplier")
print("✓ Model probabilities are between 0 and 1")
print("✓ Warning flag generated")
print("✓ Risk priority ranking generated")
print("✓ Supplier risk state available")
print("✓ Previous risk state available")
print("✓ Risk-state transition available")
print("✓ No future outcome used for current scoring")
# ================================================================================
# 23. FINAL OBJECT
# ================================================================================
fact_supplier_early_warning = current_snapshot.copy()
print("\n" + "=" * 80)
print("PHASE 8 FINAL OBJECT")
print("=" * 80)
print(
    f"fact_supplier_early_warning rows    : "
    f"{len(fact_supplier_early_warning):,}"
)
print(
    f"fact_supplier_early_warning columns : "
    f"{fact_supplier_early_warning.shape[1]:,}"
)
print(
    f"Current modelling date               : "
    f"{latest_model_date.date()}"
)
print(
    f"Operating threshold                  : "
    f"{threshold:.2f}"
)
print(
    f"Suppliers above warning threshold    : "
    f"{fact_supplier_early_warning['Failure_Warning_Flag'].sum():,}"
)
print("\n" + "=" * 80)
print("✓ PHASE 8 — SUPPLIER EARLY-WARNING ENGINE COMPLETED")
print("=" * 80)
print("""
Output object:
  fact_supplier_early_warning
Core outputs:
  Supplier_Failure_Probability
  Failure_Warning_Flag
  Warning_Severity
  Risk_Priority_Score
  Risk_Priority_Rank
Next stage:
  Phase 9 — Explainable Early Warning
  → Top risk drivers
  → Supplier-level explanations
  → Root-cause interpretation
  → Recommended intervention
  → Executive risk view
""")

================================================================================
KEYSTRA — PREDICTIVE SUPPLIER FAILURE SYSTEM
PHASE 8 — SUPPLIER EARLY-WARNING & RISK PRIORITISATION ENGINE
================================================================================

✓ Required Phase 5, Phase 4 and Phase 7 objects detected

================================================================================
PHASE 8 — INPUT VALIDATION
================================================================================
Model-ready rows : 138,953
Risk-state rows  : 150,570
✓ Required columns validated

Predictor columns expected by model : 54

================================================================================
CURRENT SUPPLIER SNAPSHOT
================================================================================
Latest modelling date : 2026-07-30
Suppliers evaluated   : 88

✓ Phase 4 categorical risk-state fields successfully attached
✓ Supplier_Risk_State: complete
✓ Previous_Risk_State: complete
✓ Risk_State_Transition: complete

================================================================================
PHASE 8 — MODEL INPUT ALIGNMENT
================================================================================
Current suppliers       : 88
Predictor columns       : 54
Expected predictors     : 54
✓ Current snapshot aligned with Phase 7 model

================================================================================
PHASE 8 — CURRENT SUPPLIER FAILURE PROBABILITY
================================================================================
Operating threshold : 0.30
Suppliers above threshold : 63

================================================================================
EARLY-WARNING SUMMARY
================================================================================
Suppliers evaluated       : 88
Critical warnings         : 31
High warnings             : 32
Moderate warnings         : 5
Low warnings              : 20

================================================================================
TOP 20 SUPPLIER EARLY-WARNING ALERTS
================================================================================

,Supplier_ID,Observation_Date,Supplier_Risk_State,Supplier_Failure_Probability,Failure_Warning_Flag,Warning_Severity,Risk_State_Score,Deterioration_Signal_Count,Severe_Signal_Count,Failure_Dimension_Count,Risk_Priority_Score,Risk_Priority_Rank
0,S035,2026-07-30,Failure,0.976761,True,Critical,23,4,4,3,0.949118,1
1,S018,2026-07-30,Failure,0.965478,True,Critical,23,4,4,3,0.941219,2
2,S004,2026-07-30,Failure,0.917395,True,Critical,23,4,4,3,0.907561,3
3,S025,2026-07-30,Failure,0.993127,True,Critical,18,4,3,2,0.902881,4
4,S055,2026-07-30,Failure,0.994461,True,Critical,17,3,3,2,0.892277,5
5,S081,2026-07-30,Failure,0.991020,True,Critical,17,3,3,2,0.889868,6
6,S001,2026-07-30,Failure,0.930450,True,Critical,20,4,4,2,0.882084,7
7,S069,2026-07-30,Failure,0.913824,True,Critical,21,4,3,3,0.881985,8
8,S009,2026-07-30,Failure,0.992520,True,Critical,15,3,2,2,0.867841,9
9,S076,2026-07-30,Failure,0.890705,True,Critical,21,4,3,3,0.865801,10
10,S087,2026-07-30,Failure,0.989248,True,Critical,15,3,2,2,0.865551,11
11,S010,2026-07-30,Failure,0.988301,True,Critical,15,3,2,2,0.864888,12
12,S062,2026-07-30,Failure,0.934000,True,Critical,18,4,3,2,0.861492,13
13,S061,2026-07-30,Failure,0.995602,True,Critical,14,2,2,2,0.858460,14
14,S058,2026-07-30,Failure,0.991729,True,Critical,14,2,2,2,0.855749,15
15,S003,2026-07-30,Failure,0.989975,True,Critical,14,2,2,2,0.854521,16
16,S054,2026-07-30,Failure,0.920710,True,Critical,18,4,3,2,0.852190,17
17,S079,2026-07-30,Failure,0.936274,True,Critical,17,3,3,2,0.851546,18
18,S013,2026-07-30,Failure,0.982619,True,Critical,14,2,2,2,0.849372,19
19,S064,2026-07-30,Failure,0.866984,True,Critical,21,4,3,3,0.849196,20

================================================================================
RISK STATE × WARNING SEVERITY
================================================================================

,Supplier_Risk_State,Warning_Severity,Suppliers,Mean_Failure_Probability,Max_Failure_Probability
0,Deteriorating,Low,3,0.005079,0.015190
1,Failure,Critical,31,0.934619,0.995602
2,Failure,High,31,0.559981,0.792783
3,Failure,Low,11,0.107931,0.196817
4,Failure,Moderate,4,0.238981,0.271367
5,High Risk,High,1,0.308943,0.308943
6,High Risk,Low,5,0.014053,0.041632
7,High Risk,Moderate,1,0.290375,0.290375
8,Watch,Low,1,0.000023,0.000023

================================================================================
PHASE 8 — FINAL HARD VALIDATION
================================================================================
✓ One current observation per supplier
✓ Model probabilities are between 0 and 1
✓ Warning flag generated
✓ Risk priority ranking generated
✓ Supplier risk state available
✓ Previous risk state available
✓ Risk-state transition available
✓ No future outcome used for current scoring

================================================================================
PHASE 8 FINAL OBJECT
================================================================================
fact_supplier_early_warning rows    : 88
fact_supplier_early_warning columns : 62
Current modelling date               : 2026-07-30
Operating threshold                  : 0.30
Suppliers above warning threshold    : 63

================================================================================
✓ PHASE 8 — SUPPLIER EARLY-WARNING ENGINE COMPLETED
================================================================================

Output object:
  fact_supplier_early_warning
Core outputs:
  Supplier_Failure_Probability
  Failure_Warning_Flag
  Warning_Severity
  Risk_Priority_Score
  Risk_Priority_Rank
Next stage:
  Phase 9 — Explainable Early Warning
  → Top risk drivers
  → Supplier-level explanations
  → Root-cause interpretation
  → Recommended intervention
  → Executive risk view

In [21]:
# ================================================================================
# KEYSTRA — PREDICTIVE SUPPLIER FAILURE SYSTEM
# PHASE 9 — EXPLAINABLE EARLY-WARNING ENGINE
# ================================================================================
#
# PURPOSE
# -------
# Explain WHY each supplier is currently being flagged.
#
# OUTPUTS
# -------
# 1. fact_supplier_explainable_warning
# 2. supplier_risk_explanations
# 3. top_supplier_risk_drivers
#
# EXPLANATION CHAIN
# -----------------
#
# Supplier
#    ↓
# Failure Probability
#    ↓
# Current Risk State
#    ↓
# Risk Signals
#    ↓
# Performance deterioration
#    ↓
# Persistent deterioration
#    ↓
# Top risk drivers
#    ↓
# Plain-English explanation
#
# IMPORTANT
# ---------
# Phase 9 does NOT connect suppliers to materials/assets yet.
# That comes in Phase 10.
# ================================================================================

import pandas as pd
import numpy as np

print("=" * 80)
print("KEYSTRA — PREDICTIVE SUPPLIER FAILURE SYSTEM")
print("PHASE 9 — EXPLAINABLE EARLY-WARNING ENGINE")
print("=" * 80)


# ================================================================================
# 1. REQUIRED OBJECT VALIDATION
# ================================================================================

required_objects = [
    "fact_supplier_early_warning",
    "fact_supplier_model_ready",
    "fact_supplier_risk_state",
    "best_model",
    "final_operating_threshold",
]

missing_objects = [
    obj for obj in required_objects
    if obj not in globals()
]

if missing_objects:
    raise ValueError(
        "Missing required Phase 9 objects:\n"
        + "\n".join(f" - {x}" for x in missing_objects)
    )

print("\n✓ Required Phase 8 / model objects detected")


# ================================================================================
# 2. COPY DATA
# ================================================================================

ew = fact_supplier_early_warning.copy()
model_ready = fact_supplier_model_ready.copy()
risk_state = fact_supplier_risk_state.copy()

ew.columns = [str(c).strip() for c in ew.columns]
model_ready.columns = [str(c).strip() for c in model_ready.columns]
risk_state.columns = [str(c).strip() for c in risk_state.columns]


# ================================================================================
# 3. REQUIRED COLUMNS
# ================================================================================

required_ew_columns = [
    "Supplier_ID",
    "Observation_Date",
    "Supplier_Failure_Probability",
    "Failure_Warning_Flag",
    "Warning_Severity",
    "Risk_Priority_Score",
    "Risk_Priority_Rank",
    "Supplier_Risk_State",
]

missing = [
    c for c in required_ew_columns
    if c not in ew.columns
]

if missing:
    raise ValueError(
        "Missing required Early Warning columns:\n"
        + "\n".join(f" - {c}" for c in missing)
    )

print("✓ Early-warning schema validated")


# ================================================================================
# 4. CURRENT SUPPLIER SNAPSHOT
# ================================================================================

ew["Observation_Date"] = pd.to_datetime(
    ew["Observation_Date"],
    errors="coerce"
)

latest_date = ew["Observation_Date"].max()

current = (
    ew[
        ew["Observation_Date"] == latest_date
    ]
    .copy()
)

current = (
    current
    .sort_values(
        ["Failure_Warning_Flag",
         "Supplier_Failure_Probability"],
        ascending=[False, False]
    )
    .drop_duplicates(
        subset=["Supplier_ID"],
        keep="first"
    )
)

print("\n" + "=" * 80)
print("CURRENT SUPPLIER SNAPSHOT")
print("=" * 80)

print(f"Latest modelling date : {latest_date.date()}")
print(f"Suppliers evaluated   : {current['Supplier_ID'].nunique()}")

print("✓ One current observation per supplier")


# ================================================================================
# 5. DRIVER DEFINITIONS
# ================================================================================
#
# Each driver has:
#
# - feature
# - direction
# - human-readable name
# - explanation
#
# We use the actual values generated by our risk engine.
# No future outcome variables are used.
# ================================================================================

driver_definitions = {

    "Fulfilment_Risk_Signal": {
        "name": "Fulfilment performance",
        "description": "Supplier fulfilment performance is creating elevated risk.",
        "direction": "high",
        "weight": 1.00,
    },

    "Recent_90D_Fulfilment_Rate": {
        "name": "Recent fulfilment rate",
        "description": "Recent fulfilment performance has weakened.",
        "direction": "low",
        "weight": 1.00,
    },

    "Fulfilment_Deviation_From_History": {
        "name": "Fulfilment deterioration",
        "description": "Recent fulfilment performance is below the supplier's historical level.",
        "direction": "low",
        "weight": 1.20,
    },

    "Partial_Fulfilment_Risk_Signal": {
        "name": "Partial fulfilment",
        "description": "Partial fulfilment behaviour is increasing supply uncertainty.",
        "direction": "high",
        "weight": 0.90,
    },

    "Recent_90D_Partial_Fulfilment_Rate": {
        "name": "Recent partial fulfilment",
        "description": "A meaningful share of recent orders are being only partially fulfilled.",
        "direction": "high",
        "weight": 0.90,
    },

    "Partial_Fulfilment_Deviation_From_History": {
        "name": "Partial fulfilment deterioration",
        "description": "Partial fulfilment behaviour has worsened relative to historical performance.",
        "direction": "high",
        "weight": 1.00,
    },

    "Late_Delivery_Risk_Signal": {
        "name": "Late delivery",
        "description": "Late delivery behaviour is contributing to supplier risk.",
        "direction": "high",
        "weight": 0.90,
    },

    "Recent_90D_Late_Delivery_Rate": {
        "name": "Recent late deliveries",
        "description": "Recent deliveries show elevated lateness.",
        "direction": "high",
        "weight": 0.90,
    },

    "Late_Delivery_Deviation_From_History": {
        "name": "Late-delivery deterioration",
        "description": "Late delivery behaviour has worsened compared with historical performance.",
        "direction": "high",
        "weight": 1.00,
    },

    "Outstanding_Risk_Signal": {
        "name": "Outstanding orders",
        "description": "Outstanding order pressure is contributing to supplier exposure.",
        "direction": "high",
        "weight": 1.00,
    },

    "Recent_90D_Outstanding_Rate": {
        "name": "Recent outstanding pressure",
        "description": "Recent outstanding order pressure is elevated.",
        "direction": "high",
        "weight": 1.00,
    },

    "Outstanding_Deviation_From_History": {
        "name": "Outstanding deterioration",
        "description": "Outstanding order pressure is above the supplier's historical level.",
        "direction": "high",
        "weight": 1.10,
    },

    "Outstanding_Quantity_Ratio": {
        "name": "Outstanding quantity exposure",
        "description": "A large share of ordered quantity remains outstanding.",
        "direction": "high",
        "weight": 1.00,
    },

    "Current_Outstanding_Quantity": {
        "name": "Current outstanding quantity",
        "description": "The supplier currently has material outstanding quantity exposure.",
        "direction": "high",
        "weight": 0.70,
    },

    "Rolling_90D_Outstanding_Quantity": {
        "name": "90-day outstanding quantity",
        "description": "Outstanding quantity has accumulated over the recent 90-day period.",
        "direction": "high",
        "weight": 0.80,
    },

    "Rolling_90D_PO_Count": {
        "name": "Recent order activity",
        "description": "Recent purchasing activity provides substantial exposure to supplier performance.",
        "direction": "high",
        "weight": 0.60,
    },

    "Rolling_90D_Partial_Fulfilment_Count": {
        "name": "Recent partial fulfilment volume",
        "description": "Recent partial fulfilment events are contributing to risk.",
        "direction": "high",
        "weight": 0.80,
    },

    "Recent_90D_Average_Delivery_Delay": {
        "name": "Average delivery delay",
        "description": "Average recent delivery delay is elevated.",
        "direction": "high",
        "weight": 0.90,
    },

    "Total_Current_Risk_Signals": {
        "name": "Multiple risk signals",
        "description": "Multiple operational risk signals are active simultaneously.",
        "direction": "high",
        "weight": 1.20,
    },

    "Risk_State_Score": {
        "name": "Risk-state severity",
        "description": "The supplier is currently in a materially elevated risk state.",
        "direction": "high",
        "weight": 1.20,
    },

    "Deterioration_Signal_Count": {
        "name": "Deterioration signals",
        "description": "Multiple deterioration signals are currently active.",
        "direction": "high",
        "weight": 1.10,
    },

    "Severe_Signal_Count": {
        "name": "Severe deterioration signals",
        "description": "Severe operational deterioration signals are present.",
        "direction": "high",
        "weight": 1.30,
    },

    "Failure_Dimension_Count": {
        "name": "Multiple failure dimensions",
        "description": "Risk is appearing across multiple operational dimensions.",
        "direction": "high",
        "weight": 1.30,
    },

    "Persistent_Deterioration": {
        "name": "Persistent deterioration",
        "description": "Deterioration has persisted rather than appearing as a one-off event.",
        "direction": "high",
        "weight": 1.20,
    },
}


# ================================================================================
# 6. BUILD DRIVER IMPORTANCE MAP
# ================================================================================

importance_map = {}

if "feature_importance" in globals():

    fi = feature_importance.copy()

    fi.columns = [
        str(c).strip()
        for c in fi.columns
    ]

    feature_col = None
    importance_col = None

    for c in fi.columns:
        if str(c).lower() in [
            "feature",
            "feature_name",
        ]:
            feature_col = c

        if "importance" in str(c).lower():
            importance_col = c

    if feature_col is not None and importance_col is not None:

        for _, row in fi.iterrows():

            feature = row[feature_col]

            try:
                importance = float(
                    row[importance_col]
                )
            except:
                importance = 0.0

            importance_map[feature] = importance

        print("\n✓ Model feature importance loaded")

else:

    print(
        "\n⚠ feature_importance object not found."
        "\nRule-based driver weighting will be used."
    )


# ================================================================================
# 7. DRIVER SCORING FUNCTION
# ================================================================================

def safe_numeric(series):

    return pd.to_numeric(
        series,
        errors="coerce"
    )


def calculate_driver_score(
    df,
    feature,
    definition
):

    if feature not in df.columns:
        return pd.Series(
            0.0,
            index=df.index
        )

    values = safe_numeric(
        df[feature]
    )

    valid = values.notna()

    score = pd.Series(
        0.0,
        index=df.index
    )

    if valid.sum() == 0:
        return score

    x = values.copy()

    q25 = x[valid].quantile(0.25)
    q75 = x[valid].quantile(0.75)

    iqr = q75 - q25

    if pd.isna(iqr) or iqr == 0:

        mean = x[valid].mean()
        std = x[valid].std()

        if pd.isna(std) or std == 0:

            score.loc[valid] = 0.0

        else:

            if definition["direction"] == "high":

                score.loc[valid] = (
                    (x[valid] - mean) / std
                ).clip(lower=0)

            else:

                score.loc[valid] = (
                    (mean - x[valid]) / std
                ).clip(lower=0)

    else:

        if definition["direction"] == "high":

            score.loc[valid] = (
                (x[valid] - q75) / iqr
            ).clip(lower=0)

        else:

            score.loc[valid] = (
                (q25 - x[valid]) / iqr
            ).clip(lower=0)

    return (
        score
        * definition.get("weight", 1.0)
    )


# ================================================================================
# 8. GENERATE DRIVER SCORES
# ================================================================================

print("\n" + "=" * 80)
print("GENERATING SUPPLIER-LEVEL RISK DRIVERS")
print("=" * 80)

driver_score_columns = []

for feature, definition in driver_definitions.items():

    if feature not in current.columns:
        continue

    score_col = (
        "__driver_score__"
        + feature
    )

    current[score_col] = calculate_driver_score(
        current,
        feature,
        definition
    )

    # Incorporate model importance where available
    if feature in importance_map:

        importance = importance_map[feature]

        if np.isfinite(importance):

            current[score_col] = (
                current[score_col]
                * (1 + importance)
            )

    driver_score_columns.append(
        (feature, score_col)
    )

print(
    f"✓ Driver scoring completed"
)

print(
    f"Drivers evaluated : "
    f"{len(driver_score_columns)}"
)


# ================================================================================
# 9. ADD RISK-STATE EVIDENCE
# ================================================================================

risk_state_features = [
    "Supplier_Risk_State",
    "Risk_State_Score",
    "Deterioration_Signal_Count",
    "Severe_Signal_Count",
    "Failure_Dimension_Count",
    "Persistent_Deterioration",
    "Previous_Risk_State",
    "Risk_State_Transition",
]

available_risk_state_features = [
    c for c in risk_state_features
    if c in current.columns
]

print(
    "\n✓ Risk-state evidence available:"
)

for c in available_risk_state_features:
    print(f"  - {c}")


# ================================================================================
# 10. EXTRACT TOP 5 DRIVERS PER SUPPLIER
# ================================================================================

print("\n" + "=" * 80)
print("BUILDING SUPPLIER-LEVEL EXPLANATIONS")
print("=" * 80)


def get_top_drivers(row, top_n=5):

    ranked = []

    for feature, score_col in driver_score_columns:

        score = row.get(
            score_col,
            0
        )

        if pd.isna(score):
            continue

        if score <= 0:
            continue

        ranked.append(
            (
                feature,
                float(score)
            )
        )

    ranked.sort(
        key=lambda x: x[1],
        reverse=True
    )

    return ranked[:top_n]


top_driver_records = []

for idx, row in current.iterrows():

    drivers = get_top_drivers(
        row,
        top_n=5
    )

    record = {
        "Supplier_ID": row["Supplier_ID"],
        "Observation_Date": row["Observation_Date"],
    }

    for position in range(1, 6):

        if position <= len(drivers):

            feature, score = drivers[position - 1]

            definition = driver_definitions[
                feature
            ]

            record[
                f"Risk_Driver_{position}"
            ] = definition["name"]

            record[
                f"Risk_Driver_{position}_Feature"
            ] = feature

            record[
                f"Risk_Driver_{position}_Score"
            ] = score

            record[
                f"Risk_Driver_{position}_Explanation"
            ] = definition["description"]

        else:

            record[
                f"Risk_Driver_{position}"
            ] = None

            record[
                f"Risk_Driver_{position}_Feature"
            ] = None

            record[
                f"Risk_Driver_{position}_Score"
            ] = 0.0

            record[
                f"Risk_Driver_{position}_Explanation"
            ] = None

    top_driver_records.append(
        record
    )


top_supplier_risk_drivers = pd.DataFrame(
    top_driver_records
)

print(
    f"✓ Top drivers generated for "
    f"{len(top_supplier_risk_drivers):,} suppliers"
)


# ================================================================================
# 11. MERGE EXPLANATIONS INTO EARLY-WARNING OBJECT
# ================================================================================

fact_supplier_explainable_warning = (
    current.merge(
        top_supplier_risk_drivers,
        on=[
            "Supplier_ID",
            "Observation_Date"
        ],
        how="left",
        validate="one_to_one"
    )
)


# ================================================================================
# 12. CREATE RISK-STATE EXPLANATION
# ================================================================================

def risk_state_explanation(row):

    state = row.get(
        "Supplier_Risk_State",
        "Unknown"
    )

    deterioration = row.get(
        "Deterioration_Signal_Count",
        0
    )

    severe = row.get(
        "Severe_Signal_Count",
        0
    )

    failure_dimensions = row.get(
        "Failure_Dimension_Count",
        0
    )

    persistent = row.get(
        "Persistent_Deterioration",
        False
    )

    if state == "Failure":

        return (
            "Supplier is currently classified as Failure, "
            f"with {int(failure_dimensions)} failure dimensions "
            f"and {int(severe)} severe signals. "
            "The deterioration is persistent."
        )

    if state == "High Risk":

        return (
            "Supplier is currently classified as High Risk, "
            f"with {int(deterioration)} deterioration signals "
            f"and {int(severe)} severe signals."
        )

    if state == "Deteriorating":

        return (
            "Supplier is currently classified as Deteriorating, "
            f"with {int(deterioration)} active deterioration signals."
        )

    if state == "Watch":

        return (
            "Supplier is currently under Watch, "
            "indicating emerging supplier-performance pressure."
        )

    return (
        "Supplier is currently classified as Stable."
    )


fact_supplier_explainable_warning[
    "Risk_State_Explanation"
] = (
    fact_supplier_explainable_warning
    .apply(
        risk_state_explanation,
        axis=1
    )
)


# ================================================================================
# 13. CREATE OVERALL EXPLANATION
# ================================================================================

def build_overall_explanation(row):

    probability = row[
        "Supplier_Failure_Probability"
    ]

    severity = row[
        "Warning_Severity"
    ]

    state = row[
        "Supplier_Risk_State"
    ]

    explanations = []

    for i in range(1, 6):

        col = (
            f"Risk_Driver_{i}_Explanation"
        )

        value = row.get(
            col,
            None
        )

        if pd.notna(value):
            explanations.append(
                str(value)
            )

    if explanations:

        driver_text = " ".join(
            explanations[:3]
        )

    else:

        driver_text = (
            "No dominant operational driver "
            "was identified from the available features."
        )

    return (
        f"Supplier is currently in the {state} risk state "
        f"with a predicted future-failure probability of "
        f"{probability:.1%} and a {severity.lower()} warning. "
        f"{driver_text}"
    )


fact_supplier_explainable_warning[
    "Overall_Risk_Explanation"
] = (
    fact_supplier_explainable_warning
    .apply(
        build_overall_explanation,
        axis=1
    )
)


# ================================================================================
# 14. RECOMMENDED INTERVENTION CATEGORY
# ================================================================================

def intervention_category(row):

    state = str(
        row.get(
            "Supplier_Risk_State",
            ""
        )
    )

    drivers = " ".join(
        str(
            row.get(
                f"Risk_Driver_{i}",
                ""
            )
        ).lower()
        for i in range(1, 6)
    )

    if (
        "outstanding" in drivers
        or "fulfilment" in drivers
    ):

        return (
            "Supplier performance review "
            "and outstanding-order recovery"
        )

    if "late" in drivers:

        return (
            "Delivery-performance intervention "
            "and recovery plan"
        )

    if "partial" in drivers:

        return (
            "Fulfilment-quality review "
            "and order-completion plan"
        )

    if state in [
        "Failure",
        "High Risk"
    ]:

        return (
            "Immediate supplier risk review "
            "and contingency assessment"
        )

    if state == "Deteriorating":

        return (
            "Enhanced supplier monitoring "
            "and corrective action"
        )

    if state == "Watch":

        return (
            "Continue monitoring "
            "and validate emerging risk signals"
        )

    return (
        "Routine supplier monitoring"
    )


fact_supplier_explainable_warning[
    "Recommended_Intervention"
] = (
    fact_supplier_explainable_warning
    .apply(
        intervention_category,
        axis=1
    )
)


# ================================================================================
# 15. CREATE SUPPLIER RISK EXPLANATION TABLE
# ================================================================================

explanation_columns = [
    "Supplier_ID",
    "Observation_Date",
    "Supplier_Failure_Probability",
    "Failure_Warning_Flag",
    "Warning_Severity",
    "Risk_Priority_Score",
    "Risk_Priority_Rank",
    "Supplier_Risk_State",
    "Risk_State_Score",
    "Deterioration_Signal_Count",
    "Severe_Signal_Count",
    "Failure_Dimension_Count",
    "Persistent_Deterioration",
    "Previous_Risk_State",
    "Risk_State_Transition",
    "Risk_Driver_1",
    "Risk_Driver_1_Explanation",
    "Risk_Driver_2",
    "Risk_Driver_2_Explanation",
    "Risk_Driver_3",
    "Risk_Driver_3_Explanation",
    "Risk_Driver_4",
    "Risk_Driver_4_Explanation",
    "Risk_Driver_5",
    "Risk_Driver_5_Explanation",
    "Risk_State_Explanation",
    "Overall_Risk_Explanation",
    "Recommended_Intervention",
]

explanation_columns = [
    c
    for c in explanation_columns
    if c in fact_supplier_explainable_warning.columns
]

supplier_risk_explanations = (
    fact_supplier_explainable_warning[
        explanation_columns
    ]
    .sort_values(
        "Risk_Priority_Rank"
    )
    .reset_index(drop=True)
)


# ================================================================================
# 16. DISPLAY TOP ALERTS
# ================================================================================

print("\n" + "=" * 80)
print("TOP 20 EXPLAINABLE SUPPLIER ALERTS")
print("=" * 80)

display(
    supplier_risk_explanations[
        [
            "Supplier_ID",
            "Supplier_Failure_Probability",
            "Warning_Severity",
            "Supplier_Risk_State",
            "Risk_Driver_1",
            "Risk_Driver_2",
            "Risk_Driver_3",
            "Recommended_Intervention",
        ]
    ]
    .head(20)
)


# ================================================================================
# 17. DISPLAY DETAILED EXPLANATION FOR TOP SUPPLIERS
# ================================================================================

print("\n" + "=" * 80)
print("TOP 10 SUPPLIER RISK EXPLANATIONS")
print("=" * 80)

for _, row in supplier_risk_explanations.head(10).iterrows():

    print("\n" + "-" * 80)

    print(
        f"Supplier: {row['Supplier_ID']}"
    )

    print(
        f"Failure Probability: "
        f"{row['Supplier_Failure_Probability']:.2%}"
    )

    print(
        f"Warning Severity: "
        f"{row['Warning_Severity']}"
    )

    print(
        f"Risk State: "
        f"{row['Supplier_Risk_State']}"
    )

    print(
        f"Risk Priority Rank: "
        f"{row['Risk_Priority_Rank']}"
    )

    print("\nTop Risk Drivers:")

    for i in range(1, 6):

        driver = row.get(
            f"Risk_Driver_{i}"
        )

        explanation = row.get(
            f"Risk_Driver_{i}_Explanation"
        )

        if pd.notna(driver):

            print(
                f"  {i}. {driver}"
            )

            if pd.notna(explanation):

                print(
                    f"     → {explanation}"
                )

    print("\nRisk-State Evidence:")

    print(
        f"  {row.get('Risk_State_Explanation', '')}"
    )

    print("\nRecommended Intervention:")

    print(
        f"  → {row.get('Recommended_Intervention', '')}"
    )


# ================================================================================
# 18. HARD VALIDATION
# ================================================================================

print("\n" + "=" * 80)
print("PHASE 9 — FINAL HARD VALIDATION")
print("=" * 80)

# Supplier uniqueness
assert (
    supplier_risk_explanations["Supplier_ID"]
    .nunique()
    ==
    len(supplier_risk_explanations)
), "Duplicate supplier explanations detected"

print(
    "✓ One explanation record per current supplier"
)

# Probability range
assert (
    supplier_risk_explanations[
        "Supplier_Failure_Probability"
    ]
    .between(0, 1)
    .all()
), "Invalid probability detected"

print(
    "✓ Failure probabilities between 0 and 1"
)

# Driver availability
driver_cols = [
    c for c in supplier_risk_explanations.columns
    if c.startswith("Risk_Driver_")
    and not c.endswith("_Explanation")
]

print(
    f"✓ Risk driver fields generated : "
    f"{len(driver_cols)}"
)

# No future target
future_columns = [
    c for c in fact_supplier_explainable_warning.columns
    if any(
        term in c.lower()
        for term in [
            "future_failure",
            "failure_component",
            "future_"
        ]
    )
]

if future_columns:

    print(
        "⚠ Potential future columns detected:"
    )

    for c in future_columns:
        print(f"  - {c}")

else:

    print(
        "✓ No future outcome variables added"
    )


# ================================================================================
# 19. FINAL OBJECT SUMMARY
# ================================================================================

print("\n" + "=" * 80)
print("PHASE 9 FINAL OBJECT")
print("=" * 80)

print(
    f"fact_supplier_explainable_warning rows    : "
    f"{len(fact_supplier_explainable_warning):,}"
)

print(
    f"fact_supplier_explainable_warning columns : "
    f"{len(fact_supplier_explainable_warning.columns):,}"
)

print(
    f"Suppliers explained                       : "
    f"{supplier_risk_explanations['Supplier_ID'].nunique():,}"
)

print(
    f"Flagged suppliers                         : "
    f"{supplier_risk_explanations['Failure_Warning_Flag'].sum():,}"
)

print(
    "\nCore outputs:"
)

print(
    "  supplier_risk_explanations"
)

print(
    "  top_supplier_risk_drivers"
)

print(
    "  fact_supplier_explainable_warning"
)

print("\n" + "=" * 80)
print("✓ PHASE 9 — EXPLAINABLE EARLY-WARNING ENGINE COMPLETED")
print("=" * 80)

print(
    "\nNext stage:"
)

print(
    "Phase 10 — Supplier & Supply-Chain Context Enrichment"
)

print(
    "  → Supplier names"
)

print(
    "  → Materials supplied"
)

print(
    "  → Assets dependent on those materials"
)

print(
    "  → Material criticality"
)

print(
    "  → Inventory / availability exposure"
)

print(
    "  → Operational consequences"
)

print("=" * 80)

================================================================================
KEYSTRA — PREDICTIVE SUPPLIER FAILURE SYSTEM
PHASE 9 — EXPLAINABLE EARLY-WARNING ENGINE
================================================================================

✓ Required Phase 8 / model objects detected
✓ Early-warning schema validated

================================================================================
CURRENT SUPPLIER SNAPSHOT
================================================================================
Latest modelling date : 2026-07-30
Suppliers evaluated   : 88
✓ One current observation per supplier

✓ Model feature importance loaded

================================================================================
GENERATING SUPPLIER-LEVEL RISK DRIVERS
================================================================================
✓ Driver scoring completed
Drivers evaluated : 24

✓ Risk-state evidence available:
  - Supplier_Risk_State
  - Risk_State_Score
  - Deterioration_Signal_Count
  - Severe_Signal_Count
  - Failure_Dimension_Count
  - Persistent_Deterioration
  - Previous_Risk_State
  - Risk_State_Transition

================================================================================
BUILDING SUPPLIER-LEVEL EXPLANATIONS
================================================================================
✓ Top drivers generated for 88 suppliers

================================================================================
TOP 20 EXPLAINABLE SUPPLIER ALERTS
================================================================================

,Supplier_ID,Supplier_Failure_Probability,Warning_Severity,Supplier_Risk_State,Risk_Driver_1,Risk_Driver_2,Risk_Driver_3,Recommended_Intervention
0,S035,0.976761,Critical,Failure,Risk-state severity,Multiple failure dimensions,Average delivery delay,Supplier performance review and outstanding-or...
1,S018,0.965478,Critical,Failure,Risk-state severity,Multiple failure dimensions,Severe deterioration signals,Supplier performance review and outstanding-or...
2,S004,0.917395,Critical,Failure,Average delivery delay,Risk-state severity,Multiple failure dimensions,Delivery-performance intervention and recovery...
3,S025,0.993127,Critical,Failure,Partial fulfilment deterioration,Partial fulfilment,Recent partial fulfilment,Supplier performance review and outstanding-or...
4,S055,0.994461,Critical,Failure,Recent order activity,Late delivery,Recent late deliveries,Delivery-performance intervention and recovery...
5,S081,0.991020,Critical,Failure,Partial fulfilment deterioration,Recent partial fulfilment volume,Partial fulfilment,Supplier performance review and outstanding-or...
6,S001,0.930450,Critical,Failure,Severe deterioration signals,Risk-state severity,Partial fulfilment deterioration,Supplier performance review and outstanding-or...
7,S069,0.913824,Critical,Failure,Multiple failure dimensions,Risk-state severity,Current outstanding quantity,Supplier performance review and outstanding-or...
8,S009,0.992520,Critical,Failure,Outstanding quantity exposure,Recent order activity,Average delivery delay,Supplier performance review and outstanding-or...
9,S076,0.890705,Critical,Failure,Multiple failure dimensions,Risk-state severity,Late delivery,Supplier performance review and outstanding-or...
10,S087,0.989248,Critical,Failure,Persistent deterioration,Multiple failure dimensions,None,Immediate supplier risk review and contingency...
11,S010,0.988301,Critical,Failure,Outstanding quantity exposure,Persistent deterioration,Multiple failure dimensions,Supplier performance review and outstanding-or...
12,S062,0.934000,Critical,Failure,Late delivery,Recent late deliveries,Deterioration signals,Supplier performance review and outstanding-or...
13,S061,0.995602,Critical,Failure,Persistent deterioration,Multiple failure dimensions,None,Immediate supplier risk review and contingency...
14,S058,0.991729,Critical,Failure,Persistent deterioration,Multiple failure dimensions,None,Immediate supplier risk review and contingency...
15,S003,0.989975,Critical,Failure,Persistent deterioration,Multiple failure dimensions,None,Immediate supplier risk review and contingency...
16,S054,0.920710,Critical,Failure,Deterioration signals,Outstanding quantity exposure,Current outstanding quantity,Supplier performance review and outstanding-or...
17,S079,0.936274,Critical,Failure,Recent order activity,Persistent deterioration,Multiple failure dimensions,Delivery-performance intervention and recovery...
18,S013,0.982619,Critical,Failure,Persistent deterioration,Multiple failure dimensions,Late-delivery deterioration,Delivery-performance intervention and recovery...
19,S064,0.866984,Critical,Failure,Multiple failure dimensions,Risk-state severity,Late delivery,Supplier performance review and outstanding-or...

================================================================================
TOP 10 SUPPLIER RISK EXPLANATIONS
================================================================================

--------------------------------------------------------------------------------
Supplier: S035
Failure Probability: 97.68%
Warning Severity: Critical
Risk State: Failure
Risk Priority Rank: 1

Top Risk Drivers:
  1. Risk-state severity
     → The supplier is currently in a materially elevated risk state.
  2. Multiple failure dimensions
     → Risk is appearing across multiple operational dimensions.
  3. Average delivery delay
     → Average recent delivery delay is elevated.
  4. Current outstanding quantity
     → The supplier currently has material outstanding quantity exposure.
  5. Late delivery
     → Late delivery behaviour is contributing to supplier risk.

Risk-State Evidence:
  Supplier is currently classified as Failure, with 3 failure dimensions and 4 severe signals. The deterioration is persistent.

Recommended Intervention:
  → Supplier performance review and outstanding-order recovery

--------------------------------------------------------------------------------
Supplier: S018
Failure Probability: 96.55%
Warning Severity: Critical
Risk State: Failure
Risk Priority Rank: 2

Top Risk Drivers:
  1. Risk-state severity
     → The supplier is currently in a materially elevated risk state.
  2. Multiple failure dimensions
     → Risk is appearing across multiple operational dimensions.
  3. Severe deterioration signals
     → Severe operational deterioration signals are present.
  4. Partial fulfilment
     → Partial fulfilment behaviour is increasing supply uncertainty.
  5. Recent partial fulfilment
     → A meaningful share of recent orders are being only partially fulfilled.

Risk-State Evidence:
  Supplier is currently classified as Failure, with 3 failure dimensions and 4 severe signals. The deterioration is persistent.

Recommended Intervention:
  → Supplier performance review and outstanding-order recovery

--------------------------------------------------------------------------------
Supplier: S004
Failure Probability: 91.74%
Warning Severity: Critical
Risk State: Failure
Risk Priority Rank: 3

Top Risk Drivers:
  1. Average delivery delay
     → Average recent delivery delay is elevated.
  2. Risk-state severity
     → The supplier is currently in a materially elevated risk state.
  3. Multiple failure dimensions
     → Risk is appearing across multiple operational dimensions.
  4. Late delivery
     → Late delivery behaviour is contributing to supplier risk.
  5. Recent late deliveries
     → Recent deliveries show elevated lateness.

Risk-State Evidence:
  Supplier is currently classified as Failure, with 3 failure dimensions and 4 severe signals. The deterioration is persistent.

Recommended Intervention:
  → Delivery-performance intervention and recovery plan

--------------------------------------------------------------------------------
Supplier: S025
Failure Probability: 99.31%
Warning Severity: Critical
Risk State: Failure
Risk Priority Rank: 4

Top Risk Drivers:
  1. Partial fulfilment deterioration
     → Partial fulfilment behaviour has worsened relative to historical performance.
  2. Partial fulfilment
     → Partial fulfilment behaviour is increasing supply uncertainty.
  3. Recent partial fulfilment
     → A meaningful share of recent orders are being only partially fulfilled.
  4. Recent partial fulfilment volume
     → Recent partial fulfilment events are contributing to risk.
  5. Deterioration signals
     → Multiple deterioration signals are currently active.

Risk-State Evidence:
  Supplier is currently classified as Failure, with 2 failure dimensions and 3 severe signals. The deterioration is persistent.

Recommended Intervention:
  → Supplier performance review and outstanding-order recovery

--------------------------------------------------------------------------------
Supplier: S055
Failure Probability: 99.45%
Warning Severity: Critical
Risk State: Failure
Risk Priority Rank: 5

Top Risk Drivers:
  1. Recent order activity
     → Recent purchasing activity provides substantial exposure to supplier performance.
  2. Late delivery
     → Late delivery behaviour is contributing to supplier risk.
  3. Recent late deliveries
     → Recent deliveries show elevated lateness.
  4. Persistent deterioration
     → Deterioration has persisted rather than appearing as a one-off event.
  5. Average delivery delay
     → Average recent delivery delay is elevated.

Risk-State Evidence:
  Supplier is currently classified as Failure, with 2 failure dimensions and 3 severe signals. The deterioration is persistent.

Recommended Intervention:
  → Delivery-performance intervention and recovery plan

--------------------------------------------------------------------------------
Supplier: S081
Failure Probability: 99.10%
Warning Severity: Critical
Risk State: Failure
Risk Priority Rank: 6

Top Risk Drivers:
  1. Partial fulfilment deterioration
     → Partial fulfilment behaviour has worsened relative to historical performance.
  2. Recent partial fulfilment volume
     → Recent partial fulfilment events are contributing to risk.
  3. Partial fulfilment
     → Partial fulfilment behaviour is increasing supply uncertainty.
  4. Recent partial fulfilment
     → A meaningful share of recent orders are being only partially fulfilled.
  5. Fulfilment deterioration
     → Recent fulfilment performance is below the supplier's historical level.

Risk-State Evidence:
  Supplier is currently classified as Failure, with 2 failure dimensions and 3 severe signals. The deterioration is persistent.

Recommended Intervention:
  → Supplier performance review and outstanding-order recovery

--------------------------------------------------------------------------------
Supplier: S001
Failure Probability: 93.05%
Warning Severity: Critical
Risk State: Failure
Risk Priority Rank: 7

Top Risk Drivers:
  1. Severe deterioration signals
     → Severe operational deterioration signals are present.
  2. Risk-state severity
     → The supplier is currently in a materially elevated risk state.
  3. Partial fulfilment deterioration
     → Partial fulfilment behaviour has worsened relative to historical performance.
  4. Partial fulfilment
     → Partial fulfilment behaviour is increasing supply uncertainty.
  5. Recent partial fulfilment
     → A meaningful share of recent orders are being only partially fulfilled.

Risk-State Evidence:
  Supplier is currently classified as Failure, with 2 failure dimensions and 4 severe signals. The deterioration is persistent.

Recommended Intervention:
  → Supplier performance review and outstanding-order recovery

--------------------------------------------------------------------------------
Supplier: S069
Failure Probability: 91.38%
Warning Severity: Critical
Risk State: Failure
Risk Priority Rank: 8

Top Risk Drivers:
  1. Multiple failure dimensions
     → Risk is appearing across multiple operational dimensions.
  2. Risk-state severity
     → The supplier is currently in a materially elevated risk state.
  3. Current outstanding quantity
     → The supplier currently has material outstanding quantity exposure.
  4. Deterioration signals
     → Multiple deterioration signals are currently active.
  5. Late delivery
     → Late delivery behaviour is contributing to supplier risk.

Risk-State Evidence:
  Supplier is currently classified as Failure, with 3 failure dimensions and 3 severe signals. The deterioration is persistent.

Recommended Intervention:
  → Supplier performance review and outstanding-order recovery

--------------------------------------------------------------------------------
Supplier: S009
Failure Probability: 99.25%
Warning Severity: Critical
Risk State: Failure
Risk Priority Rank: 9

Top Risk Drivers:
  1. Outstanding quantity exposure
     → A large share of ordered quantity remains outstanding.
  2. Recent order activity
     → Recent purchasing activity provides substantial exposure to supplier performance.
  3. Average delivery delay
     → Average recent delivery delay is elevated.
  4. Persistent deterioration
     → Deterioration has persisted rather than appearing as a one-off event.
  5. Multiple failure dimensions
     → Risk is appearing across multiple operational dimensions.

Risk-State Evidence:
  Supplier is currently classified as Failure, with 2 failure dimensions and 2 severe signals. The deterioration is persistent.

Recommended Intervention:
  → Supplier performance review and outstanding-order recovery

--------------------------------------------------------------------------------
Supplier: S076
Failure Probability: 89.07%
Warning Severity: Critical
Risk State: Failure
Risk Priority Rank: 10

Top Risk Drivers:
  1. Multiple failure dimensions
     → Risk is appearing across multiple operational dimensions.
  2. Risk-state severity
     → The supplier is currently in a materially elevated risk state.
  3. Late delivery
     → Late delivery behaviour is contributing to supplier risk.
  4. Recent late deliveries
     → Recent deliveries show elevated lateness.
  5. Current outstanding quantity
     → The supplier currently has material outstanding quantity exposure.

Risk-State Evidence:
  Supplier is currently classified as Failure, with 3 failure dimensions and 3 severe signals. The deterioration is persistent.

Recommended Intervention:
  → Supplier performance review and outstanding-order recovery

================================================================================
PHASE 9 — FINAL HARD VALIDATION
================================================================================
✓ One explanation record per current supplier
✓ Failure probabilities between 0 and 1
✓ Risk driver fields generated : 5
✓ No future outcome variables added

================================================================================
PHASE 9 FINAL OBJECT
================================================================================
fact_supplier_explainable_warning rows    : 88
fact_supplier_explainable_warning columns : 109
Suppliers explained                       : 88
Flagged suppliers                         : 63

Core outputs:
  supplier_risk_explanations
  top_supplier_risk_drivers
  fact_supplier_explainable_warning

================================================================================
✓ PHASE 9 — EXPLAINABLE EARLY-WARNING ENGINE COMPLETED
================================================================================

Next stage:
Phase 10 — Supplier & Supply-Chain Context Enrichment
  → Supplier names
  → Materials supplied
  → Assets dependent on those materials
  → Material criticality
  → Inventory / availability exposure
  → Operational consequences
================================================================================

In [22]:
# ================================================================================
# KEYSTRA — PREDICTIVE SUPPLIER FAILURE SYSTEM
# PHASE 10 — SUPPLIER & SUPPLY-CHAIN CONTEXT ENRICHMENT
# REBUILT / VALIDATED VERSION
# ================================================================================

import pandas as pd
import numpy as np

print("=" * 90)
print("KEYSTRA — PREDICTIVE SUPPLIER FAILURE SYSTEM")
print("PHASE 10 — SUPPLIER & SUPPLY-CHAIN CONTEXT ENRICHMENT")
print("=" * 90)


# ================================================================================
# 1. REQUIRED OBJECT VALIDATION
# ================================================================================

required_objects = {
    "fact_supplier_explainable_warning": fact_supplier_explainable_warning,
    "dim_supplier": dim_supplier,
    "dim_material": dim_material,
    "dim_asset": dim_asset,
    "bridge_supplier_material": bridge_supplier_material,
    "bridge_asset_material": bridge_asset_material,
    "material_criticality": material_criticality,
    "material_safety_stock": material_safety_stock,
}

for name, obj in required_objects.items():

    if obj is None or not isinstance(obj, pd.DataFrame):
        raise RuntimeError(
            f"Required object '{name}' is missing or is not a DataFrame."
        )

    print(f"✓ {name:<38} {obj.shape}")


# ================================================================================
# 2. COPY INPUTS
# ================================================================================

warning = fact_supplier_explainable_warning.copy()
supplier_dim = dim_supplier.copy()
material_dim = dim_material.copy()
asset_dim = dim_asset.copy()
supplier_material = bridge_supplier_material.copy()
asset_material = bridge_asset_material.copy()
criticality = material_criticality.copy()
safety_stock = material_safety_stock.copy()


# ================================================================================
# 3. COLUMN CLEANING
# ================================================================================

def clean_columns(df):

    df = df.copy()

    df.columns = (
        df.columns
        .astype(str)
        .str.strip()
        .str.replace(r"\s+", "_", regex=True)
    )

    return df


warning = clean_columns(warning)
supplier_dim = clean_columns(supplier_dim)
material_dim = clean_columns(material_dim)
asset_dim = clean_columns(asset_dim)
supplier_material = clean_columns(supplier_material)
asset_material = clean_columns(asset_material)
criticality = clean_columns(criticality)
safety_stock = clean_columns(safety_stock)


# ================================================================================
# 4. KEY VALIDATION
# ================================================================================

required_keys = {
    "warning": ["Supplier_ID"],
    "supplier_dim": ["Supplier_ID"],
    "material_dim": ["Material_ID"],
    "asset_dim": ["Asset_ID"],
    "supplier_material": ["Supplier_ID", "Material_ID"],
    "asset_material": ["Asset_ID", "Material_ID"],
    "criticality": ["Material_ID"],
    "safety_stock": ["Material_ID"],
}

objects = {
    "warning": warning,
    "supplier_dim": supplier_dim,
    "material_dim": material_dim,
    "asset_dim": asset_dim,
    "supplier_material": supplier_material,
    "asset_material": asset_material,
    "criticality": criticality,
    "safety_stock": safety_stock,
}

for name, cols in required_keys.items():

    missing = [
        col for col in cols
        if col not in objects[name].columns
    ]

    if missing:
        raise RuntimeError(
            f"{name} missing required columns: {missing}\n"
            f"Available columns: {list(objects[name].columns)}"
        )

print("\n✓ All relationship keys validated")


# ================================================================================
# 5. NORMALISE KEY TYPES
# ================================================================================

for df, cols in [
    (warning, ["Supplier_ID"]),
    (supplier_dim, ["Supplier_ID"]),
    (material_dim, ["Material_ID"]),
    (asset_dim, ["Asset_ID"]),
    (supplier_material, ["Supplier_ID", "Material_ID"]),
    (asset_material, ["Asset_ID", "Material_ID"]),
    (criticality, ["Material_ID"]),
    (safety_stock, ["Material_ID"]),
]:

    for col in cols:

        df[col] = (
            df[col]
            .astype(str)
            .str.strip()
        )


# ================================================================================
# 6. SUPPLIER NAME
# ================================================================================

supplier_name_candidates = [
    "Supplier_Name",
    "supplier_name",
    "SupplierName",
    "Name"
]

supplier_name_col = next(
    (
        c for c in supplier_name_candidates
        if c in supplier_dim.columns
    ),
    None
)

if supplier_name_col is None:

    raise RuntimeError(
        "Supplier name column not found.\n"
        f"Available columns: {list(supplier_dim.columns)}"
    )


supplier_lookup = (
    supplier_dim[
        ["Supplier_ID", supplier_name_col]
    ]
    .drop_duplicates("Supplier_ID")
    .rename(
        columns={
            supplier_name_col: "Supplier_Name"
        }
    )
)


# ================================================================================
# 7. CURRENT SUPPLIER WARNING INTELLIGENCE
# ================================================================================

current_warning = warning.copy()

current_warning = current_warning.merge(
    supplier_lookup,
    on="Supplier_ID",
    how="left",
    validate="many_to_one"
)

print("\n" + "=" * 90)
print("CURRENT SUPPLIER RISK INTELLIGENCE")
print("=" * 90)

print(
    f"Suppliers with current predictive intelligence : "
    f"{current_warning['Supplier_ID'].nunique():,}"
)

print("✓ Phase 9 predictive supplier intelligence retained")


# ================================================================================
# 8. MATERIAL ATTRIBUTES
# ================================================================================

material_name_candidates = [
    "Material_Name",
    "material_name",
    "MaterialName",
    "Name"
]

material_name_col = next(
    (
        c for c in material_name_candidates
        if c in material_dim.columns
    ),
    None
)

if material_name_col is None:

    raise RuntimeError(
        "Material name column not found.\n"
        f"Available columns: {list(material_dim.columns)}"
    )


material_attributes = material_dim.copy()

if material_name_col != "Material_Name":

    material_attributes = material_attributes.rename(
        columns={
            material_name_col: "Material_Name"
        }
    )


material_keep = ["Material_ID"]

for col in [
    "Material_Name",
    "Material_Category",
    "Material_Type",
    "Business_Unit",
    "Location"
]:

    if col in material_attributes.columns:
        material_keep.append(col)


material_attributes = (
    material_attributes[
        list(dict.fromkeys(material_keep))
    ]
    .drop_duplicates("Material_ID")
)


print("✓ Material attributes prepared")


# ================================================================================
# 9. MATERIAL CRITICALITY
# ================================================================================

# IMPORTANT:
# Your actual material_criticality table contains:
#
#     Material_ID
#     Criticality_Tier
#
# Therefore Criticality_Tier is explicitly supported here.

criticality_candidates = [
    "Material_Criticality",
    "Criticality_Tier",
    "Criticality",
    "Criticality_Level",
    "Material_Criticality_Level"
]

criticality_col = next(
    (
        c for c in criticality_candidates
        if c in criticality.columns
    ),
    None
)

if criticality_col is None:

    raise RuntimeError(
        "Material criticality column not found.\n"
        f"Available columns: {list(criticality.columns)}\n"
        "Expected one of: "
        f"{criticality_candidates}"
    )


criticality_context = (
    criticality[
        ["Material_ID", criticality_col]
    ]
    .drop_duplicates("Material_ID")
    .rename(
        columns={
            criticality_col: "Material_Criticality"
        }
    )
)


# ------------------------------------------------------------------------------
# NORMALISE MATERIAL CRITICALITY LABELS
# ------------------------------------------------------------------------------

criticality_context["Material_Criticality"] = (
    criticality_context["Material_Criticality"]
    .astype(str)
    .str.strip()
)


# ------------------------------------------------------------------------------
# NUMERIC CRITICALITY SCORE
# ------------------------------------------------------------------------------

def criticality_to_score(value):

    text = str(value).strip().lower()

    if text in [
        "critical",
        "very critical",
        "criticality critical",
        "tier 1",
        "tier_1",
        "tier1"
    ]:
        return 100

    if text in [
        "high",
        "high criticality",
        "tier 2",
        "tier_2",
        "tier2"
    ]:
        return 75

    if text in [
        "medium",
        "moderate",
        "medium criticality",
        "tier 3",
        "tier_3",
        "tier3"
    ]:
        return 50

    if text in [
        "low",
        "low criticality",
        "tier 4",
        "tier_4",
        "tier4"
    ]:
        return 25

    try:

        numeric = float(value)

        if 0 <= numeric <= 100:
            return numeric

    except (TypeError, ValueError):

        pass

    return np.nan


criticality_context["Material_Criticality_Score"] = (
    criticality_context["Material_Criticality"]
    .apply(criticality_to_score)
)


if criticality_context[
    "Material_Criticality_Score"
].isna().all():

    raise RuntimeError(
        "Unable to derive numeric material criticality scores.\n"
        f"Criticality values found: "
        f"{criticality_context['Material_Criticality'].dropna().unique().tolist()}"
    )


print("✓ Material criticality + numeric score prepared")

print(
    "  Criticality source column : "
    f"{criticality_col}"
)

print(
    "  Criticality values        : "
    f"{criticality_context['Material_Criticality'].dropna().unique().tolist()}"
)


# ================================================================================
# 10. SAFETY STOCK / REORDER POINT
# ================================================================================

safety_keep = ["Material_ID"]

for col in [
    "Safety_Stock",
    "Safety_Stock_Quantity",
    "Reorder_Point",
    "Reorder_Point_Quantity"
]:

    if col in safety_stock.columns:
        safety_keep.append(col)


safety_context = (
    safety_stock[
        list(dict.fromkeys(safety_keep))
    ]
    .drop_duplicates("Material_ID")
)


rename_map = {}

if "Safety_Stock_Quantity" in safety_context.columns:
    rename_map["Safety_Stock_Quantity"] = "Safety_Stock"

if "Reorder_Point_Quantity" in safety_context.columns:
    rename_map["Reorder_Point_Quantity"] = "Reorder_Point"


safety_context = safety_context.rename(
    columns=rename_map
)


if "Safety_Stock" not in safety_context.columns:
    safety_context["Safety_Stock"] = np.nan

if "Reorder_Point" not in safety_context.columns:
    safety_context["Reorder_Point"] = np.nan


safety_context["Safety_Stock"] = pd.to_numeric(
    safety_context["Safety_Stock"],
    errors="coerce"
)

safety_context["Reorder_Point"] = pd.to_numeric(
    safety_context["Reorder_Point"],
    errors="coerce"
)


print("✓ Safety stock / reorder point prepared")


# ================================================================================
# 11. SUPPLIER → MATERIAL BRIDGE
# ================================================================================

supplier_material_context = (
    supplier_material[
        ["Supplier_ID", "Material_ID"]
    ]
    .drop_duplicates()
)


print("\n" + "=" * 90)
print("SUPPLIER → MATERIAL RELATIONSHIP")
print("=" * 90)

print(
    f"Supplier-material relationships : "
    f"{len(supplier_material_context):,}"
)

print(
    f"Suppliers represented           : "
    f"{supplier_material_context['Supplier_ID'].nunique():,}"
)

print(
    f"Materials represented           : "
    f"{supplier_material_context['Material_ID'].nunique():,}"
)


# ================================================================================
# 12. MATERIAL → ASSET BRIDGE
# ================================================================================

material_asset_context = (
    asset_material[
        ["Material_ID", "Asset_ID"]
    ]
    .drop_duplicates()
)


print("\n" + "=" * 90)
print("MATERIAL → ASSET RELATIONSHIP")
print("=" * 90)

print(
    f"Material-asset relationships : "
    f"{len(material_asset_context):,}"
)

print(
    f"Materials represented        : "
    f"{material_asset_context['Material_ID'].nunique():,}"
)

print(
    f"Assets represented           : "
    f"{material_asset_context['Asset_ID'].nunique():,}"
)


# ================================================================================
# 13. ASSET ATTRIBUTES
# ================================================================================

asset_keep = ["Asset_ID"]

for col in [
    "Asset_Name",
    "Asset_Class",
    "Asset_Type",
    "Business_Unit",
    "Location"
]:

    if col in asset_dim.columns:
        asset_keep.append(col)


asset_attributes = (
    asset_dim[
        list(dict.fromkeys(asset_keep))
    ]
    .drop_duplicates("Asset_ID")
)


# ================================================================================
# 14. ASSET CRITICALITY
# ================================================================================

asset_criticality_candidates = [
    "Asset_Criticality",
    "Criticality",
    "Criticality_Level",
    "Asset_Criticality_Level"
]

asset_criticality_col = next(
    (
        c for c in asset_criticality_candidates
        if c in asset_dim.columns
    ),
    None
)


if asset_criticality_col is not None:

    asset_attributes["Asset_Criticality"] = (
        asset_dim[
            asset_criticality_col
        ]
        .astype(str)
        .str.strip()
    )

else:

    # If no explicit asset criticality exists,
    # derive it conservatively from asset class/name.

    def infer_asset_criticality(row):

        text = (
            f"{row.get('Asset_Name', '')} "
            f"{row.get('Asset_Class', '')} "
            f"{row.get('Asset_Type', '')}"
        ).lower()

        if any(
            x in text
            for x in [
                "refinery",
                "processing",
                "production",
                "compressor",
                "turbine",
                "pipeline",
                "platform"
            ]
        ):

            return "Critical"

        return "Non-Critical"


    asset_attributes["Asset_Criticality"] = (
        asset_attributes.apply(
            infer_asset_criticality,
            axis=1
        )
    )


def asset_criticality_score(value):

    text = str(value).strip().lower()

    if "critical" in text:
        return 100

    if "high" in text:
        return 75

    if "medium" in text or "moderate" in text:
        return 50

    if "low" in text:
        return 25

    return 0


asset_attributes["Asset_Criticality_Score"] = (
    asset_attributes["Asset_Criticality"]
    .apply(asset_criticality_score)
)


# ================================================================================
# 15. BUILD MATERIAL → ASSET CONTEXT
# ================================================================================

material_asset_enriched = (
    material_asset_context
    .merge(
        asset_attributes,
        on="Asset_ID",
        how="left",
        validate="many_to_one"
    )
)


# ================================================================================
# 16. BUILD SUPPLIER → MATERIAL → ASSET CHAIN
# ================================================================================

print("\n" + "=" * 90)
print("BUILDING SUPPLIER → MATERIAL → ASSET CHAIN")
print("=" * 90)


supplier_material_asset = (
    supplier_material_context
    .merge(
        material_attributes,
        on="Material_ID",
        how="left",
        validate="many_to_one"
    )
    .merge(
        criticality_context,
        on="Material_ID",
        how="left",
        validate="many_to_one"
    )
    .merge(
        safety_context,
        on="Material_ID",
        how="left",
        validate="many_to_one"
    )
    .merge(
        material_asset_enriched,
        on="Material_ID",
        how="left"
    )
)


print(
    f"Supplier-material-asset records : "
    f"{len(supplier_material_asset):,}"
)


# ================================================================================
# 17. OPERATIONAL DEPENDENCY SCORE
# ================================================================================

def operational_dependency_score(row):

    material_score = row.get(
        "Material_Criticality_Score",
        0
    )

    asset_score = row.get(
        "Asset_Criticality_Score",
        0
    )

    material_score = (
        0 if pd.isna(material_score)
        else float(material_score)
    )

    asset_score = (
        0 if pd.isna(asset_score)
        else float(asset_score)
    )

    return (
        material_score * 0.55
        +
        asset_score * 0.45
    )


supplier_material_asset[
    "Operational_Dependency_Score"
] = supplier_material_asset.apply(
    operational_dependency_score,
    axis=1
).clip(0, 100)


# ================================================================================
# 18. OPERATIONAL DEPENDENCY CLASS
# ================================================================================

def dependency_class(score):

    if score >= 85:
        return "Critical production dependency"

    if score >= 70:
        return "High operational dependency"

    if score >= 50:
        return "Moderate operational dependency"

    if score >= 25:
        return "Low operational dependency"

    return "Limited operational dependency"


supplier_material_asset[
    "Operational_Dependency"
] = supplier_material_asset[
    "Operational_Dependency_Score"
].apply(
    dependency_class
)


# ================================================================================
# 19. OPERATIONAL CONSEQUENCE
# ================================================================================

def determine_consequence(row):

    score = row["Operational_Dependency_Score"]

    asset_name = str(
        row.get("Asset_Name", "")
    ).lower()

    if score >= 85:

        if any(
            x in asset_name
            for x in [
                "refinery",
                "processing",
                "production",
                "compressor",
                "turbine"
            ]
        ):

            return (
                "Potential equipment downtime, "
                "production disruption and financial exposure"
            )

        return (
            "Potential operational downtime "
            "and production disruption"
        )

    if score >= 70:

        return (
            "Potential maintenance delay, "
            "service disruption and increased operating cost"
        )

    if score >= 50:

        return (
            "Potential operational inefficiency "
            "and procurement disruption"
        )

    if score >= 25:

        return (
            "Potential limited operational disruption "
            "and increased procurement exposure"
        )

    return "Limited direct operational consequence"


supplier_material_asset[
    "Potential_Operational_Consequence"
] = supplier_material_asset.apply(
    determine_consequence,
    axis=1
)


# ================================================================================
# 20. MATERIAL EXPOSURE STATUS
# ================================================================================

def exposure_status(row):

    safety = row["Safety_Stock"]

    if pd.isna(safety):
        return "Unknown"

    if safety <= 0:
        return "No safety-stock protection"

    return "Safety-stock protected"


supplier_material_asset[
    "Material_Exposure_Status"
] = supplier_material_asset.apply(
    exposure_status,
    axis=1
)


# ================================================================================
# 21. SUPPLIER EXPOSURE — CORRECT UNIQUE COUNTING
# ================================================================================

supplier_exposure = (
    supplier_material_asset
    .groupby("Supplier_ID")
    .agg(

        Materials_Supplied=(
            "Material_ID",
            "nunique"
        ),

        Critical_Materials_Supplied=(
            "Material_Criticality_Score",
            lambda x: (x >= 100).sum()
        ),

        Assets_Dependent=(
            "Asset_ID",
            "nunique"
        ),

        Critical_Assets_Dependent=(
            "Asset_Criticality_Score",
            lambda x: (x >= 100).sum()
        ),

        Material_Criticality_Exposure=(
            "Material_Criticality_Score",
            "max"
        ),

        Asset_Dependency_Exposure=(
            "Operational_Dependency_Score",
            "max"
        ),

        Average_Operational_Dependency=(
            "Operational_Dependency_Score",
            "mean"
        )
    )
    .reset_index()
)


# ================================================================================
# 22. CRITICAL MATERIAL EXPOSURE RATIO
# ================================================================================

supplier_exposure[
    "Critical_Material_Exposure_Ratio"
] = np.where(

    supplier_exposure["Materials_Supplied"] > 0,

    supplier_exposure[
        "Critical_Materials_Supplied"
    ]
    /
    supplier_exposure[
        "Materials_Supplied"
    ],

    0
)


supplier_exposure[
    "Critical_Material_Exposure_Ratio"
] = (
    supplier_exposure[
        "Critical_Material_Exposure_Ratio"
    ]
    .clip(0, 1)
)


# ================================================================================
# 23. CRITICAL ASSET EXPOSURE RATIO
# ================================================================================

supplier_exposure[
    "Critical_Asset_Exposure_Ratio"
] = np.where(

    supplier_exposure["Assets_Dependent"] > 0,

    supplier_exposure[
        "Critical_Assets_Dependent"
    ]
    /
    supplier_exposure[
        "Assets_Dependent"
    ],

    0
)


supplier_exposure[
    "Critical_Asset_Exposure_Ratio"
] = (
    supplier_exposure[
        "Critical_Asset_Exposure_Ratio"
    ]
    .clip(0, 1)
)


# ================================================================================
# 24. SUPPLIER EXPOSURE CLASS
# ================================================================================

def supplier_exposure_class(x):

    if x >= 5:
        return "Very High"

    if x >= 3:
        return "High"

    if x >= 1:
        return "Moderate"

    return "Low"


supplier_exposure[
    "Supplier_Critical_Material_Exposure"
] = (
    supplier_exposure[
        "Critical_Materials_Supplied"
    ]
    .apply(supplier_exposure_class)
)


# ================================================================================
# 25. JOIN SUPPLIER RISK → SUPPLY-CHAIN CONTEXT
# ================================================================================

phase10 = supplier_material_asset.merge(
    current_warning,
    on="Supplier_ID",
    how="inner",
    suffixes=("", "_Risk")
)


phase10 = phase10.merge(
    supplier_exposure,
    on="Supplier_ID",
    how="left",
    suffixes=("", "_Supplier")
)


# Remove duplicate columns if any
phase10 = phase10.loc[
    :,
    ~phase10.columns.duplicated()
].copy()


# ================================================================================
# 26. FINAL COLUMN ORDER
# ================================================================================

preferred_columns = [

    "Supplier_ID",
    "Supplier_Name",

    "Observation_Date",
    "Supplier_Failure_Probability",
    "Failure_Warning_Flag",
    "Warning_Severity",
    "Risk_Priority_Rank",
    "Risk_Priority_Score",

    "Supplier_Risk_State",
    "Risk_State_Score",
    "Deterioration_Signal_Count",
    "Severe_Signal_Count",
    "Failure_Dimension_Count",

    "Material_ID",
    "Material_Name",
    "Material_Category",
    "Material_Criticality",
    "Material_Criticality_Score",
    "Safety_Stock",
    "Reorder_Point",

    "Asset_ID",
    "Asset_Name",
    "Asset_Class",
    "Asset_Type",
    "Asset_Criticality",
    "Asset_Criticality_Score",
    "Business_Unit",
    "Location",

    "Operational_Dependency",
    "Operational_Dependency_Score",
    "Potential_Operational_Consequence",
    "Material_Exposure_Status",

    "Materials_Supplied",
    "Critical_Materials_Supplied",
    "Assets_Dependent",
    "Critical_Assets_Dependent",

    "Critical_Material_Exposure_Ratio",
    "Critical_Asset_Exposure_Ratio",

    "Material_Criticality_Exposure",
    "Asset_Dependency_Exposure",
    "Average_Operational_Dependency",

    "Supplier_Critical_Material_Exposure",

    "Risk_Driver_1",
    "Risk_Driver_2",
    "Risk_Driver_3",
    "Risk_Driver_4",
    "Risk_Driver_5",

    "Recommended_Intervention",
]


final_columns = [
    c for c in preferred_columns
    if c in phase10.columns
]

remaining_columns = [
    c for c in phase10.columns
    if c not in final_columns
]

phase10 = phase10[
    final_columns + remaining_columns
]


# ================================================================================
# 27. HARD VALIDATION
# ================================================================================

print("\n" + "=" * 90)
print("PHASE 10 — FINAL HARD VALIDATION")
print("=" * 90)


assert phase10["Supplier_ID"].notna().all()
assert phase10["Material_ID"].notna().all()
assert phase10["Supplier_Name"].notna().all()
assert phase10["Material_Name"].notna().all()
assert phase10["Asset_ID"].notna().all()


probabilities = pd.to_numeric(
    phase10["Supplier_Failure_Probability"],
    errors="coerce"
)


if (
    probabilities.isna().any()
    or
    (probabilities < 0).any()
    or
    (probabilities > 1).any()
):

    raise RuntimeError(
        "Invalid supplier failure probabilities detected."
    )


material_scores = (
    pd.to_numeric(
        phase10["Material_Criticality_Score"],
        errors="coerce"
    )
    .dropna()
)


if not material_scores.between(0, 100).all():

    raise RuntimeError(
        "Invalid material criticality scores detected."
    )


operational_scores = (
    pd.to_numeric(
        phase10["Operational_Dependency_Score"],
        errors="coerce"
    )
    .dropna()
)


if not operational_scores.between(0, 100).all():

    raise RuntimeError(
        "Invalid operational dependency scores detected."
    )


print("✓ Supplier IDs validated")
print("✓ Supplier names attached")
print("✓ Materials attached")
print("✓ Material criticality validated")
print("✓ Assets attached")
print("✓ Asset criticality validated")
print("✓ Operational dependency validated")
print("✓ Safety-stock context attached")
print("✓ Supplier exposure validated")
print("✓ Failure probabilities valid")


# ================================================================================
# 28. SUPPLIER-LEVEL CONTEXT SUMMARY
# ================================================================================

supplier_context_summary = (
    phase10
    .groupby(
        [
            "Supplier_ID",
            "Supplier_Name",
            "Supplier_Failure_Probability",
            "Warning_Severity",
            "Supplier_Risk_State",
        ],
        dropna=False
    )
    .agg(

        Materials_Supplied=(
            "Material_ID",
            "nunique"
        ),

        Critical_Materials_Supplied=(
            "Critical_Materials_Supplied",
            "max"
        ),

        Assets_Dependent=(
            "Asset_ID",
            "nunique"
        ),

        Critical_Assets_Dependent=(
            "Critical_Assets_Dependent",
            "max"
        ),

        Material_Criticality_Exposure=(
            "Material_Criticality_Exposure",
            "max"
        ),

        Asset_Dependency_Exposure=(
            "Asset_Dependency_Exposure",
            "max"
        )
    )
    .reset_index()
)


supplier_context_summary = (
    supplier_context_summary
    .sort_values(
        "Supplier_Failure_Probability",
        ascending=False
    )
)


# ================================================================================
# 29. CRITICAL DEPENDENCIES
# ================================================================================

phase10_critical_dependencies = phase10[
    phase10["Material_Criticality_Score"] >= 100
].copy()


# ================================================================================
# 30. FINAL OBJECTS
# ================================================================================

fact_supplier_supply_chain_context = phase10.copy()

phase10_supplier_summary = (
    supplier_context_summary.copy()
)

phase10_critical_dependencies = (
    phase10_critical_dependencies.copy()
)


# ================================================================================
# 31. FINAL SUMMARY
# ================================================================================

print("\n" + "=" * 90)
print("PHASE 10 FINAL SUMMARY")
print("=" * 90)

print(
    f"Supplier risk-context records : "
    f"{len(fact_supplier_supply_chain_context):,}"
)

print(
    f"Suppliers represented         : "
    f"{fact_supplier_supply_chain_context['Supplier_ID'].nunique():,}"
)

print(
    f"Materials represented         : "
    f"{fact_supplier_supply_chain_context['Material_ID'].nunique():,}"
)

print(
    f"Assets represented            : "
    f"{fact_supplier_supply_chain_context['Asset_ID'].nunique():,}"
)

print(
    f"Critical dependencies         : "
    f"{len(phase10_critical_dependencies):,}"
)

print(
    f"Final columns                 : "
    f"{fact_supplier_supply_chain_context.shape[1]:,}"
)


print("\n" + "=" * 90)
print("✓ PHASE 10 COMPLETED SUCCESSFULLY")
print("=" * 90)

print(
    """
Supplier
   ↓
Material
   ↓
Material Criticality
   ↓
Safety Stock / Reorder Point
   ↓
Asset
   ↓
Asset Criticality
   ↓
Operational Dependency
   ↓
Operational Consequence
   ↓
Supplier Failure Probability
   ↓
Supplier Exposure
"""
)


# ================================================================================
# ================================================================================
# PHASE 11 — SUPPLIER RISK PRIORITISATION ENGINE
# ================================================================================
# ================================================================================

print("\n\n" + "=" * 90)
print("KEYSTRA — PHASE 11")
print("SUPPLIER RISK PRIORITISATION ENGINE")
print("=" * 90)


# ================================================================================
# 32. AUTHORITATIVE SUPPLIER UNIVERSE
# ================================================================================

supplier_universe = (
    supplier_dim[
        ["Supplier_ID", supplier_name_col]
    ]
    .drop_duplicates("Supplier_ID")
    .copy()
)


supplier_universe = supplier_universe.rename(
    columns={
        supplier_name_col: "Supplier_Name"
    }
)


supplier_universe["_Supplier_Key"] = (
    supplier_universe["Supplier_ID"]
    .astype(str)
    .str.strip()
)


print("\n" + "=" * 90)
print("SUPPLIER UNIVERSE")
print("=" * 90)

print(
    f"Dim_Supplier population : "
    f"{len(supplier_universe)}"
)


if len(supplier_universe) != 90:

    print(
        "⚠️ WARNING: Expected 90 suppliers."
    )

else:

    print(
        "✓ Complete 90-supplier universe confirmed"
    )


# ================================================================================
# 33. PREPARE PHASE 10 SUPPLIER CONTEXT
# ================================================================================

context = fact_supplier_supply_chain_context.copy()


context["_Supplier_Key"] = (
    context["Supplier_ID"]
    .astype(str)
    .str.strip()
)


# ================================================================================
# 34. SUPPLIER-LEVEL AGGREGATION
# ================================================================================

supplier_context = (
    context
    .groupby(
        "_Supplier_Key",
        as_index=False
    )
    .agg(

        Supplier_Failure_Probability=(
            "Supplier_Failure_Probability",
            "max"
        ),

        Supplier_Performance_Risk=(
            "Risk_State_Score",
            "max"
        ),

        Material_Criticality_Exposure=(
            "Material_Criticality_Score",
            "max"
        ),

        Asset_Dependency_Exposure=(
            "Operational_Dependency_Score",
            "max"
        ),

        Materials_Supplied=(
            "Material_ID",
            "nunique"
        ),

        Critical_Materials_Supplied=(
            "Critical_Materials_Supplied",
            "max"
        ),

        Assets_Dependent=(
            "Asset_ID",
            "nunique"
        ),

        Critical_Assets_Dependent=(
            "Critical_Assets_Dependent",
            "max"
        ),

        Critical_Material_Exposure_Ratio=(
            "Critical_Material_Exposure_Ratio",
            "max"
        ),

        Critical_Asset_Exposure_Ratio=(
            "Critical_Asset_Exposure_Ratio",
            "max"
        ),

        Supply_Chain_Exposure_Score=(
            "Operational_Dependency_Score",
            "max"
        )
    )
)


# ================================================================================
# 35. RETAIN RISK STATE / WARNING SEVERITY
# ================================================================================

risk_state_lookup = (
    context[
        [
            "_Supplier_Key",
            "Supplier_Risk_State",
            "Warning_Severity"
        ]
    ]
    .drop_duplicates("_Supplier_Key")
)


supplier_context = supplier_context.merge(
    risk_state_lookup,
    on="_Supplier_Key",
    how="left"
)


# ================================================================================
# 36. JOIN TO COMPLETE SUPPLIER UNIVERSE
# ================================================================================

supplier_risk = supplier_universe.merge(
    supplier_context,
    on="_Supplier_Key",
    how="left",
    validate="one_to_one"
)


if len(supplier_risk) != len(supplier_universe):

    raise RuntimeError(
        "Supplier universe changed during Phase 11."
    )


print("\n✓ Complete supplier universe preserved")


# ================================================================================
# 37. PREDICTIVE INTELLIGENCE STATUS
# ================================================================================

supplier_risk[
    "Predictive_Intelligence_Status"
] = np.where(

    supplier_risk[
        "Supplier_Failure_Probability"
    ].notna(),

    "Current Warning Available",

    "No Current Warning"
)


warning_count = (
    supplier_risk[
        "Predictive_Intelligence_Status"
    ]
    .eq("Current Warning Available")
    .sum()
)


no_warning_count = (
    supplier_risk[
        "Predictive_Intelligence_Status"
    ]
    .eq("No Current Warning")
    .sum()
)


print("\n" + "=" * 90)
print("PREDICTIVE INTELLIGENCE COVERAGE")
print("=" * 90)

print(
    f"Current warning available : "
    f"{warning_count}"
)

print(
    f"No current warning        : "
    f"{no_warning_count}"
)

print(
    f"Total suppliers           : "
    f"{len(supplier_risk)}"
)


# ================================================================================
# 38. CLEAN NUMERIC FIELDS
# ================================================================================

numeric_columns = [
    "Supplier_Failure_Probability",
    "Supplier_Performance_Risk",
    "Material_Criticality_Exposure",
    "Asset_Dependency_Exposure",
    "Materials_Supplied",
    "Critical_Materials_Supplied",
    "Assets_Dependent",
    "Critical_Assets_Dependent",
    "Critical_Material_Exposure_Ratio",
    "Critical_Asset_Exposure_Ratio",
]


for col in numeric_columns:

    supplier_risk[col] = pd.to_numeric(
        supplier_risk[col],
        errors="coerce"
    )


# ================================================================================
# 39. NO-WARNING SUPPLIERS
# ================================================================================

no_prediction = (
    supplier_risk[
        "Supplier_Failure_Probability"
    ]
    .isna()
)


# Do NOT fabricate probability.
# Exposure information may still be retained.


supplier_risk[
    "Predictive_Risk_Score"
] = np.where(

    supplier_risk[
        "Supplier_Failure_Probability"
    ].notna(),

    supplier_risk[
        "Supplier_Failure_Probability"
    ] * 100,

    np.nan
)


# ================================================================================
# 40. SUPPLY-CHAIN EXPOSURE SCORE
# ================================================================================
#
# Exposure:
#
# 35% Material criticality
# 25% Critical-material concentration
# 20% Critical-asset concentration
# 20% Operational dependency
#
# ================================================================================

supplier_risk[
    "Supply_Chain_Exposure_Score"
] = (

    supplier_risk[
        "Material_Criticality_Exposure"
    ]
    .fillna(0)
    * 0.35

    +

    supplier_risk[
        "Critical_Material_Exposure_Ratio"
    ]
    .fillna(0)
    * 100
    * 0.25

    +

    supplier_risk[
        "Critical_Asset_Exposure_Ratio"
    ]
    .fillna(0)
    * 100
    * 0.20

    +

    supplier_risk[
        "Asset_Dependency_Exposure"
    ]
    .fillna(0)
    * 0.20

).clip(0, 100)


# ================================================================================
# 41. FINAL SUPPLIER RISK PRIORITY SCORE
# ================================================================================
#
# 40% Predictive failure risk
# 20% Current supplier risk/performance
# 20% Supply-chain exposure
# 10% Material criticality
# 10% Operational dependency
#
# ================================================================================

supplier_risk[
    "Supplier_Risk_Priority_Score"
] = np.nan


has_prediction = (
    supplier_risk[
        "Supplier_Failure_Probability"
    ].notna()
)


supplier_risk.loc[
    has_prediction,
    "Supplier_Risk_Priority_Score"
] = (

    supplier_risk.loc[
        has_prediction,
        "Predictive_Risk_Score"
    ].fillna(0)
    * 0.40

    +

    supplier_risk.loc[
        has_prediction,
        "Supplier_Performance_Risk"
    ].fillna(0)
    .clip(0, 100)
    * 0.20

    +

    supplier_risk.loc[
        has_prediction,
        "Supply_Chain_Exposure_Score"
    ].fillna(0)
    * 0.20

    +

    supplier_risk.loc[
        has_prediction,
        "Material_Criticality_Exposure"
    ].fillna(0)
    .clip(0, 100)
    * 0.10

    +

    supplier_risk.loc[
        has_prediction,
        "Asset_Dependency_Exposure"
    ].fillna(0)
    .clip(0, 100)
    * 0.10

)


supplier_risk[
    "Supplier_Risk_Priority_Score"
] = (
    supplier_risk[
        "Supplier_Risk_Priority_Score"
    ]
    .clip(0, 100)
)


# ================================================================================
# 42. RISK PRIORITY LEVEL
# ================================================================================

def priority_level(row):

    score = row[
        "Supplier_Risk_Priority_Score"
    ]

    if pd.isna(score):
        return "No Current Warning"

    if score >= 75:
        return "Critical"

    if score >= 60:
        return "High"

    if score >= 40:
        return "Moderate"

    return "Low"


supplier_risk[
    "Risk_Priority_Level"
] = supplier_risk.apply(
    priority_level,
    axis=1
)


# ================================================================================
# 43. RISK PRIORITY RANK
# ================================================================================

supplier_risk[
    "Risk_Priority_Rank"
] = pd.NA


rankable = supplier_risk[
    "Supplier_Risk_Priority_Score"
].notna()


supplier_risk.loc[
    rankable,
    "Risk_Priority_Rank"
] = (

    supplier_risk.loc[
        rankable,
        "Supplier_Risk_Priority_Score"
    ]
    .rank(
        ascending=False,
        method="min"
    )
    .astype("Int64")
)


# ================================================================================
# 44. INTERVENTION ENGINE
# ================================================================================

def generate_intervention(row):

    if (
        row[
            "Predictive_Intelligence_Status"
        ]
        ==
        "No Current Warning"
    ):

        return (
            "Continue monitoring; obtain current predictive intelligence "
            "before escalation"
        )


    probability = row[
        "Supplier_Failure_Probability"
    ]

    priority = row[
        "Supplier_Risk_Priority_Score"
    ]

    critical_materials = row[
        "Critical_Materials_Supplied"
    ]

    critical_assets = row[
        "Critical_Assets_Dependent"
    ]


    actions = []


    if probability >= 0.80:

        actions.append(
            "Initiate supplier intervention"
        )

    elif probability >= 0.60:

        actions.append(
            "Increase supplier monitoring"
        )

    else:

        actions.append(
            "Continue routine monitoring"
        )


    if critical_materials >= 1:

        actions.append(
            "Protect critical-material availability"
        )


    if critical_assets >= 1:

        actions.append(
            "Assess dependent asset exposure"
        )


    if priority >= 75:

        actions.append(
            "Prepare contingency / alternate sourcing"
        )


    return " + ".join(actions)


supplier_risk[
    "Recommended_Intervention"
] = supplier_risk.apply(
    generate_intervention,
    axis=1
)


# ================================================================================
# 45. HARD VALIDATION
# ================================================================================

print("\n" + "=" * 90)
print("PHASE 11 — FINAL HARD VALIDATION")
print("=" * 90)


# Supplier population
if len(supplier_risk) != len(supplier_universe):

    raise RuntimeError(
        "Supplier population changed."
    )


print(
    f"✓ {len(supplier_risk)} supplier records retained"
)


# Supplier uniqueness
if supplier_risk[
    "Supplier_ID"
].duplicated().any():

    raise RuntimeError(
        "Duplicate supplier IDs detected."
    )


print("✓ Supplier IDs unique")


# Probability
valid_probability = supplier_risk[
    "Supplier_Failure_Probability"
].dropna()


if (
    (valid_probability < 0).any()
    or
    (valid_probability > 1).any()
):

    raise RuntimeError(
        "Invalid failure probability detected."
    )


print("✓ Failure probabilities valid")


# Exposure
if (
    (supplier_risk[
        "Supply_Chain_Exposure_Score"
    ] < 0).any()

    or

    (supplier_risk[
        "Supply_Chain_Exposure_Score"
    ] > 100).any()
):

    raise RuntimeError(
        "Invalid supply-chain exposure score."
    )


print("✓ Supply-chain exposure scores valid")


# Priority
valid_priority = supplier_risk[
    "Supplier_Risk_Priority_Score"
].dropna()


if (
    (valid_priority < 0).any()
    or
    (valid_priority > 100).any()
):

    raise RuntimeError(
        "Invalid supplier risk priority score."
    )


print("✓ Supplier risk priority scores valid")


# Intelligence status
if supplier_risk[
    "Predictive_Intelligence_Status"
].isna().any():

    raise RuntimeError(
        "Predictive intelligence status contains nulls."
    )


print("✓ Predictive intelligence status complete")


# ================================================================================
# 46. SORT FINAL SUPPLIER RISK TABLE
# ================================================================================

supplier_risk = (
    supplier_risk
    .sort_values(
        by=[
            "Predictive_Intelligence_Status",
            "Supplier_Risk_Priority_Score"
        ],
        ascending=[
            False,
            False
        ],
        na_position="last"
    )
    .reset_index(drop=True)
)


# ================================================================================
# 47. FINAL DISPLAY
# ================================================================================

print("\n" + "=" * 90)
print("TOP 20 SUPPLIER RISK PRIORITIES")
print("=" * 90)


display_columns = [
    "Supplier_ID",
    "Supplier_Name",
    "Supplier_Failure_Probability",
    "Predictive_Intelligence_Status",
    "Risk_Priority_Level",
    "Supplier_Risk_Priority_Score",
    "Risk_Priority_Rank",
    "Supplier_Performance_Risk",
    "Materials_Supplied",
    "Critical_Materials_Supplied",
    "Assets_Dependent",
    "Critical_Assets_Dependent",
    "Material_Criticality_Exposure",
    "Asset_Dependency_Exposure",
    "Supply_Chain_Exposure_Score",
    "Recommended_Intervention"
]


display(
    supplier_risk[
        display_columns
    ].head(20)
)


# ================================================================================
# 48. NO CURRENT WARNING SUPPLIERS
# ================================================================================

print("\n" + "=" * 90)
print("SUPPLIERS WITHOUT CURRENT PREDICTIVE WARNING")
print("=" * 90)


no_warning = supplier_risk[
    supplier_risk[
        "Predictive_Intelligence_Status"
    ]
    ==
    "No Current Warning"
].copy()


if no_warning.empty:

    print(
        "✓ All suppliers currently have predictive intelligence."
    )

else:

    display(
        no_warning[
            [
                "Supplier_ID",
                "Supplier_Name",
                "Predictive_Intelligence_Status",
                "Materials_Supplied",
                "Critical_Materials_Supplied",
                "Assets_Dependent",
                "Critical_Assets_Dependent",
                "Supply_Chain_Exposure_Score",
                "Recommended_Intervention"
            ]
        ]
    )


# ================================================================================
# 49. CRITICAL SUPPLIER EXPOSURES
# ================================================================================

print("\n" + "=" * 90)
print("TOP SUPPLIERS BY CRITICAL-MATERIAL EXPOSURE")
print("=" * 90)


critical_exposure_display = (
    supplier_risk[
        supplier_risk[
            "Critical_Materials_Supplied"
        ] > 0
    ]
    .sort_values(
        by=[
            "Critical_Materials_Supplied",
            "Supplier_Risk_Priority_Score"
        ],
        ascending=False,
        na_position="last"
    )
)


display(
    critical_exposure_display[
        [
            "Supplier_ID",
            "Supplier_Name",
            "Supplier_Failure_Probability",
            "Risk_Priority_Level",
            "Supplier_Risk_Priority_Score",
            "Materials_Supplied",
            "Critical_Materials_Supplied",
            "Assets_Dependent",
            "Critical_Assets_Dependent",
            "Supply_Chain_Exposure_Score"
        ]
    ]
    .head(20)
)


# ================================================================================
# 50. FINAL SUMMARY
# ================================================================================

print("\n" + "=" * 90)
print("PHASE 11 — FINAL SUMMARY")
print("=" * 90)


print(
    f"Total supplier population       : "
    f"{len(supplier_risk)}"
)


print(
    f"Current warning suppliers       : "
    f"{(
        supplier_risk[
            'Predictive_Intelligence_Status'
        ]
        ==
        'Current Warning Available'
    ).sum()}"
)


print(
    f"No-current-warning suppliers    : "
    f"{(
        supplier_risk[
            'Predictive_Intelligence_Status'
        ]
        ==
        'No Current Warning'
    ).sum()}"
)


print(
    f"Critical-risk suppliers         : "
    f"{(
        supplier_risk[
            'Risk_Priority_Level'
        ]
        ==
        'Critical'
    ).sum()}"
)


print(
    f"High-risk suppliers             : "
    f"{(
        supplier_risk[
            'Risk_Priority_Level'
        ]
        ==
        'High'
    ).sum()}"
)


print(
    f"Moderate-risk suppliers         : "
    f"{(
        supplier_risk[
            'Risk_Priority_Level'
        ]
        ==
        'Moderate'
    ).sum()}"
)


print(
    f"Low-risk suppliers              : "
    f"{(
        supplier_risk[
            'Risk_Priority_Level'
        ]
        ==
        'Low'
    ).sum()}"
)


print(
    f"Ranked suppliers                : "
    f"{supplier_risk[
        'Risk_Priority_Rank'
    ].notna().sum()}"
)


# ================================================================================
# 51. FINAL OBJECT
# ================================================================================

supplier_risk = supplier_risk.copy()


# ================================================================================
# 52. FINAL HARD CHECK
# ================================================================================

assert len(supplier_risk) == len(
    supplier_universe
)

assert supplier_risk[
    "Supplier_ID"
].nunique() == len(
    supplier_universe
)

assert supplier_risk[
    "Predictive_Intelligence_Status"
].notna().all()

assert (
    supplier_risk[
        "Supply_Chain_Exposure_Score"
    ]
    .between(0, 100)
    .all()
)

valid_priority = supplier_risk[
    "Supplier_Risk_Priority_Score"
].dropna()

assert (
    valid_priority
    .between(0, 100)
    .all()
)


print("\n" + "=" * 90)
print("✓ PHASE 10 — CONTEXT ENRICHMENT COMPLETE")
print("✓ PHASE 11 — SUPPLIER RISK PRIORITISATION COMPLETE")
print("=" * 90)

print(
    """
FINAL ARCHITECTURE

Supplier
   ↓
Predictive Failure Probability
   ↓
Current Supplier Risk
   ↓
Material Criticality
   ↓
Critical Material Exposure
   ↓
Asset Dependency
   ↓
Operational Dependency
   ↓
Supply-Chain Exposure
   ↓
SUPPLIER RISK PRIORITY
   ↓
Risk Priority Level
   ↓
Risk Priority Rank
   ↓
Recommended Intervention

Final objects:

    fact_supplier_supply_chain_context
    phase10_supplier_summary
    phase10_critical_dependencies
    supplier_risk

NEXT:
    PHASE 12 — INTERVENTION ENGINE
"""
)

==========================================================================================
KEYSTRA — PREDICTIVE SUPPLIER FAILURE SYSTEM
PHASE 10 — SUPPLIER & SUPPLY-CHAIN CONTEXT ENRICHMENT
==========================================================================================
✓ fact_supplier_explainable_warning      (88, 109)
✓ dim_supplier                           (90, 10)
✓ dim_material                           (60, 11)
✓ dim_asset                              (13, 7)
✓ bridge_supplier_material               (174, 5)
✓ bridge_asset_material                  (141, 6)
✓ material_criticality                   (60, 2)
✓ material_safety_stock                  (60, 3)

✓ All relationship keys validated

==========================================================================================
CURRENT SUPPLIER RISK INTELLIGENCE
==========================================================================================
Suppliers with current predictive intelligence : 88
✓ Phase 9 predictive supplier intelligence retained
✓ Material attributes prepared
✓ Material criticality + numeric score prepared
  Criticality source column : Criticality_Tier
  Criticality values        : ['Critical', 'High', 'Medium', 'Low']
✓ Safety stock / reorder point prepared

==========================================================================================
SUPPLIER → MATERIAL RELATIONSHIP
==========================================================================================
Supplier-material relationships : 174
Suppliers represented           : 90
Materials represented           : 60

==========================================================================================
MATERIAL → ASSET RELATIONSHIP
==========================================================================================
Material-asset relationships : 141
Materials represented        : 60
Assets represented           : 13

==========================================================================================
BUILDING SUPPLIER → MATERIAL → ASSET CHAIN
==========================================================================================
Supplier-material-asset records : 407

==========================================================================================
PHASE 10 — FINAL HARD VALIDATION
==========================================================================================
✓ Supplier IDs validated
✓ Supplier names attached
✓ Materials attached
✓ Material criticality validated
✓ Assets attached
✓ Asset criticality validated
✓ Operational dependency validated
✓ Safety-stock context attached
✓ Supplier exposure validated
✓ Failure probabilities valid

==========================================================================================
PHASE 10 FINAL SUMMARY
==========================================================================================
Supplier risk-context records : 405
Suppliers represented         : 88
Materials represented         : 60
Assets represented            : 13
Critical dependencies         : 31
Final columns                 : 135

==========================================================================================
✓ PHASE 10 COMPLETED SUCCESSFULLY
==========================================================================================

Supplier
   ↓
Material
   ↓
Material Criticality
   ↓
Safety Stock / Reorder Point
   ↓
Asset
   ↓
Asset Criticality
   ↓
Operational Dependency
   ↓
Operational Consequence
   ↓
Supplier Failure Probability
   ↓
Supplier Exposure



==========================================================================================
KEYSTRA — PHASE 11
SUPPLIER RISK PRIORITISATION ENGINE
==========================================================================================

==========================================================================================
SUPPLIER UNIVERSE
==========================================================================================
Dim_Supplier population : 90
✓ Complete 90-supplier universe confirmed

✓ Complete supplier universe preserved

==========================================================================================
PREDICTIVE INTELLIGENCE COVERAGE
==========================================================================================
Current warning available : 88
No current warning        : 2
Total suppliers           : 90

==========================================================================================
PHASE 11 — FINAL HARD VALIDATION
==========================================================================================
✓ 90 supplier records retained
✓ Supplier IDs unique
✓ Failure probabilities valid
✓ Supply-chain exposure scores valid
✓ Supplier risk priority scores valid
✓ Predictive intelligence status complete

==========================================================================================
TOP 20 SUPPLIER RISK PRIORITIES
==========================================================================================

,Supplier_ID,Supplier_Name,Supplier_Failure_Probability,Predictive_Intelligence_Status,Risk_Priority_Level,Supplier_Risk_Priority_Score,Risk_Priority_Rank,Supplier_Performance_Risk,Materials_Supplied,Critical_Materials_Supplied,Assets_Dependent,Critical_Assets_Dependent,Material_Criticality_Exposure,Asset_Dependency_Exposure,Supply_Chain_Exposure_Score,Recommended_Intervention
0,S045,PrimeFlow Industrial Solutions Ltd.,NaN,No Current Warning,No Current Warning,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,Continue monitoring; obtain current predictive...
1,S085,WindSun Energy Systems Ltd.,NaN,No Current Warning,No Current Warning,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,Continue monitoring; obtain current predictive...
2,S081,SunCore Energy Technologies Ltd.,0.991020,Current Warning Available,Critical,83.040788,1,17.0,3.0,3.0,5.0,5.0,100.0,100.00,100.00,Initiate supplier intervention + Protect criti...
3,S055,Process Materials Solutions Ltd.,0.994461,Current Warning Available,Critical,81.928449,2,17.0,4.0,3.0,7.0,8.0,100.0,100.00,93.75,Initiate supplier intervention + Protect criti...
4,S004,Sterling Industrial Equipment Ltd.,0.917395,Current Warning Available,Critical,81.295789,3,23.0,2.0,5.0,4.0,5.0,100.0,100.00,100.00,Initiate supplier intervention + Protect criti...
5,S035,Advanced Process Instruments Ltd.,0.976761,Current Warning Available,High,72.495452,4,23.0,3.0,0.0,7.0,8.0,75.0,86.25,63.50,Initiate supplier intervention + Assess depend...
6,S019,Powerlink Industrial Systems Ltd.,0.801238,Current Warning Available,High,72.349513,5,14.0,4.0,2.0,9.0,10.0,100.0,100.00,87.50,Initiate supplier intervention + Protect criti...
7,S025,Brightline Electrical Industries Ltd.,0.993127,Current Warning Available,High,72.150080,6,18.0,4.0,0.0,9.0,10.0,75.0,86.25,63.50,Initiate supplier intervention + Assess depend...
8,S009,Ironbridge Equipment Solutions Ltd.,0.992520,Current Warning Available,High,71.525794,7,15.0,3.0,0.0,6.0,8.0,75.0,86.25,63.50,Initiate supplier intervention + Assess depend...
9,S087,Continental Industrial Services Ltd.,0.989248,Current Warning Available,High,71.394938,8,15.0,2.0,0.0,5.0,5.0,75.0,86.25,63.50,Initiate supplier intervention + Assess depend...
10,S058,Nexus Industrial Supply Ltd.,0.991729,Current Warning Available,High,71.294149,9,14.0,3.0,0.0,7.0,8.0,75.0,86.25,63.50,Initiate supplier intervention + Assess depend...
11,S003,Atlas Turbomachinery Services Ltd.,0.989975,Current Warning Available,High,71.224019,10,14.0,1.0,0.0,3.0,3.0,75.0,86.25,63.50,Initiate supplier intervention + Assess depend...
12,S030,Axis Process Controls Ltd.,0.979762,Current Warning Available,High,70.815490,11,14.0,1.0,0.0,3.0,3.0,75.0,86.25,63.50,Initiate supplier intervention + Assess depend...
13,S001,Apex Rotating Systems Ltd.,0.930450,Current Warning Available,High,70.043013,12,20.0,1.0,0.0,2.0,2.0,75.0,86.25,63.50,Initiate supplier intervention + Assess depend...
14,S054,Industrial Supply Partners Ltd.,0.920710,Current Warning Available,High,69.253412,13,18.0,5.0,0.0,8.0,11.0,75.0,86.25,63.50,Initiate supplier intervention + Assess depend...
15,S047,DeltaFlow Technologies Ltd.,0.895324,Current Warning Available,High,68.237972,14,18.0,1.0,0.0,2.0,2.0,75.0,86.25,63.50,Initiate supplier intervention + Assess depend...
16,S018,Crown Electrical Technologies Ltd.,0.965478,Current Warning Available,High,65.869113,15,23.0,3.0,0.0,6.0,8.0,50.0,72.50,52.00,Initiate supplier intervention + Assess depend...
17,S010,Pinnacle Machinery Services Ltd.,0.988301,Current Warning Available,High,65.182058,16,15.0,2.0,0.0,4.0,5.0,50.0,72.50,52.00,Initiate supplier intervention + Assess depend...
18,S013,Westfield Industrial Engineering Ltd.,0.982619,Current Warning Available,High,64.754773,17,14.0,2.0,0.0,5.0,5.0,50.0,72.50,52.00,Initiate supplier intervention + Assess depend...
19,S062,Reliable Industrial Materials Ltd.,0.934000,Current Warning Available,High,63.610007,18,18.0,1.0,0.0,2.0,2.0,50.0,72.50,52.00,Initiate supplier intervention + Assess depend...

==========================================================================================
SUPPLIERS WITHOUT CURRENT PREDICTIVE WARNING
==========================================================================================

,Supplier_ID,Supplier_Name,Predictive_Intelligence_Status,Materials_Supplied,Critical_Materials_Supplied,Assets_Dependent,Critical_Assets_Dependent,Supply_Chain_Exposure_Score,Recommended_Intervention
0,S045,PrimeFlow Industrial Solutions Ltd.,No Current Warning,NaN,NaN,NaN,NaN,0.0,Continue monitoring; obtain current predictive...
1,S085,WindSun Energy Systems Ltd.,No Current Warning,NaN,NaN,NaN,NaN,0.0,Continue monitoring; obtain current predictive...

==========================================================================================
TOP SUPPLIERS BY CRITICAL-MATERIAL EXPOSURE
==========================================================================================

,Supplier_ID,Supplier_Name,Supplier_Failure_Probability,Risk_Priority_Level,Supplier_Risk_Priority_Score,Materials_Supplied,Critical_Materials_Supplied,Assets_Dependent,Critical_Assets_Dependent,Supply_Chain_Exposure_Score
4,S004,Sterling Industrial Equipment Ltd.,0.917395,Critical,81.295789,2.0,5.0,4.0,5.0,100.00
2,S081,SunCore Energy Technologies Ltd.,0.991020,Critical,83.040788,3.0,3.0,5.0,5.0,100.00
3,S055,Process Materials Solutions Ltd.,0.994461,Critical,81.928449,4.0,3.0,7.0,8.0,93.75
22,S086,Integrated Energy Supply Solutions Ltd.,0.548061,High,63.122422,5.0,3.0,9.0,14.0,90.00
47,S059,Westbridge Process Supplies Ltd.,0.334785,Moderate,55.141402,4.0,3.0,8.0,10.0,93.75
6,S019,Powerlink Industrial Systems Ltd.,0.801238,High,72.349513,4.0,2.0,9.0,10.0,87.50
23,S034,NexControl Engineering Ltd.,0.495164,High,62.806551,2.0,2.0,3.0,4.0,100.00
24,S057,CoreProcess Materials Ltd.,0.487458,High,62.498315,1.0,2.0,2.0,2.0,100.00
52,S028,Precision Control Technologies Ltd.,0.150316,Moderate,49.612641,1.0,2.0,2.0,2.0,100.00
57,S056,ProServe Industrial Supplies Ltd.,0.074150,Moderate,47.166013,2.0,2.0,3.0,3.0,100.00
61,S053,Continental Piping Technologies Ltd.,0.070183,Moderate,43.107331,4.0,2.0,8.0,10.0,87.50
66,S031,Integra Automation Systems Ltd.,0.020583,Moderate,41.123330,4.0,2.0,7.0,8.0,87.50

==========================================================================================
PHASE 11 — FINAL SUMMARY
==========================================================================================
Total supplier population       : 90
Current warning suppliers       : 88
No-current-warning suppliers    : 2
Critical-risk suppliers         : 3
High-risk suppliers             : 24
Moderate-risk suppliers         : 41
Low-risk suppliers              : 20
Ranked suppliers                : 88

==========================================================================================
✓ PHASE 10 — CONTEXT ENRICHMENT COMPLETE
✓ PHASE 11 — SUPPLIER RISK PRIORITISATION COMPLETE
==========================================================================================

FINAL ARCHITECTURE

Supplier
   ↓
Predictive Failure Probability
   ↓
Current Supplier Risk
   ↓
Material Criticality
   ↓
Critical Material Exposure
   ↓
Asset Dependency
   ↓
Operational Dependency
   ↓
Supply-Chain Exposure
   ↓
SUPPLIER RISK PRIORITY
   ↓
Risk Priority Level
   ↓
Risk Priority Rank
   ↓
Recommended Intervention

Final objects:

    fact_supplier_supply_chain_context
    phase10_supplier_summary
    phase10_critical_dependencies
    supplier_risk

NEXT:
    PHASE 12 — INTERVENTION ENGINE

In [23]:
# =============================================================================
# KEYSTRA — PREDICTIVE SUPPLIER FAILURE SYSTEM
# PHASE 12 — SUPPLIER INTERVENTION ENGINE
# =============================================================================
#
# PURPOSE
# -------
# Convert supplier risk intelligence into explainable, prioritized actions.
#
# INPUT
# -----
# supplier_risk
#
# OUTPUTS
# -------
# 1. supplier_intervention
# 2. phase12_intervention_summary
# 3. phase12_critical_interventions
# 4. phase12_validation_summary
#
# ANALYTICAL CHAIN
# ----------------
# Supplier Risk
#       ↓
# Failure Probability
#       ↓
# Risk Priority
#       ↓
# Supply-Chain Exposure
#       ↓
# Critical Material Exposure
#       ↓
# Critical Asset Dependency
#       ↓
# Intervention Urgency
#       ↓
# Recommended Action
#       ↓
# Mitigation Strategy
#       ↓
# Intervention Priority
# =============================================================================


import pandas as pd
import numpy as np


# =============================================================================
# 1. PHASE HEADER
# =============================================================================

print("=" * 90)
print("KEYSTRA — PHASE 12")
print("SUPPLIER INTERVENTION ENGINE")
print("=" * 90)


# =============================================================================
# 2. INPUT VALIDATION
# =============================================================================

if "supplier_risk" not in globals():
    raise NameError(
        "supplier_risk was not found. "
        "Run Phase 11 successfully before running Phase 12."
    )

supplier_input = supplier_risk.copy()


# =============================================================================
# 3. REQUIRED COLUMNS
# =============================================================================

required_columns = [
    "Supplier_ID",
    "Supplier_Name",
    "Predictive_Intelligence_Status",
    "Risk_Priority_Level",
    "Supplier_Risk_Priority_Score",
    "Supplier_Failure_Probability",
    "Supply_Chain_Exposure_Score",
    "Materials_Supplied",
    "Critical_Materials_Supplied",
    "Assets_Dependent",
    "Critical_Assets_Dependent",
]


missing_columns = [
    col for col in required_columns
    if col not in supplier_input.columns
]

if missing_columns:
    raise ValueError(
        "Phase 12 cannot continue. Missing required columns:\n"
        + "\n".join(f" - {col}" for col in missing_columns)
    )


# =============================================================================
# 4. NUMERIC STANDARDISATION
# =============================================================================

numeric_columns = [
    "Supplier_Risk_Priority_Score",
    "Supplier_Failure_Probability",
    "Supply_Chain_Exposure_Score",
    "Materials_Supplied",
    "Critical_Materials_Supplied",
    "Assets_Dependent",
    "Critical_Assets_Dependent",
]


for col in numeric_columns:
    supplier_input[col] = pd.to_numeric(
        supplier_input[col],
        errors="coerce"
    )


# =============================================================================
# 5. NORMALISE FAILURE PROBABILITY
# =============================================================================

supplier_input["Supplier_Failure_Probability"] = (
    supplier_input["Supplier_Failure_Probability"]
    .clip(lower=0, upper=1)
)


# =============================================================================
# 6. NORMALISE RISK PRIORITY LEVEL
# =============================================================================

supplier_input["Risk_Priority_Level"] = (
    supplier_input["Risk_Priority_Level"]
    .fillna("No Current Warning")
    .astype(str)
    .str.strip()
)


supplier_input["Predictive_Intelligence_Status"] = (
    supplier_input["Predictive_Intelligence_Status"]
    .fillna("No Current Warning")
    .astype(str)
    .str.strip()
)


# =============================================================================
# 7. CREATE INTERVENTION BASE TABLE
# =============================================================================

intervention = supplier_input[
    [
        "Supplier_ID",
        "Supplier_Name",
        "Predictive_Intelligence_Status",
        "Supplier_Failure_Probability",
        "Risk_Priority_Level",
        "Supplier_Risk_Priority_Score",
        "Supply_Chain_Exposure_Score",
        "Materials_Supplied",
        "Critical_Materials_Supplied",
        "Assets_Dependent",
        "Critical_Assets_Dependent",
    ]
].copy()


# =============================================================================
# 8. CURRENT RISK FLAGS
# =============================================================================

intervention["Failure_Risk_Flag"] = np.select(
    [
        intervention["Supplier_Failure_Probability"] >= 0.80,
        intervention["Supplier_Failure_Probability"] >= 0.60,
        intervention["Supplier_Failure_Probability"] >= 0.40,
    ],
    [
        "Very High",
        "High",
        "Moderate",
    ],
    default="Low"
)


intervention["Exposure_Risk_Flag"] = np.select(
    [
        intervention["Supply_Chain_Exposure_Score"] >= 85,
        intervention["Supply_Chain_Exposure_Score"] >= 70,
        intervention["Supply_Chain_Exposure_Score"] >= 50,
    ],
    [
        "Very High",
        "High",
        "Moderate",
    ],
    default="Low"
)


intervention["Critical_Dependency_Flag"] = np.select(
    [
        intervention["Critical_Assets_Dependent"] >= 5,
        intervention["Critical_Assets_Dependent"] >= 3,
        intervention["Critical_Assets_Dependent"] >= 1,
    ],
    [
        "Severe",
        "High",
        "Moderate",
    ],
    default="Low"
)


# =============================================================================
# 9. INTERVENTION URGENCY SCORE
# =============================================================================
#
# The intervention engine combines:
#
# 40% Supplier failure probability
# 30% Supply-chain exposure
# 20% Critical asset dependency
# 10% Critical material exposure
#
# This is an ACTION score, not a replacement for the Phase 11 risk score.
# =============================================================================

failure_component = (
    intervention["Supplier_Failure_Probability"]
    .fillna(0)
    * 100
)


exposure_component = (
    intervention["Supply_Chain_Exposure_Score"]
    .fillna(0)
    .clip(lower=0, upper=100)
)


critical_asset_component = (
    (
        intervention["Critical_Assets_Dependent"].fillna(0)
        /
        intervention["Assets_Dependent"].replace(0, np.nan)
    )
    .fillna(0)
    .clip(lower=0, upper=1)
    * 100
)


critical_material_component = (
    (
        intervention["Critical_Materials_Supplied"].fillna(0)
        /
        intervention["Materials_Supplied"].replace(0, np.nan)
    )
    .fillna(0)
    .clip(lower=0, upper=1)
    * 100
)


intervention["Critical_Asset_Dependency_Score"] = (
    critical_asset_component.round(2)
)


intervention["Critical_Material_Dependency_Score"] = (
    critical_material_component.round(2)
)


intervention["Intervention_Urgency_Score"] = (
    0.40 * failure_component
    + 0.30 * exposure_component
    + 0.20 * critical_asset_component
    + 0.10 * critical_material_component
).round(2)


# =============================================================================
# 10. INTERVENTION PRIORITY
# =============================================================================

intervention["Intervention_Priority"] = np.select(
    [
        (
            intervention["Intervention_Urgency_Score"] >= 75
        ),
        (
            intervention["Intervention_Urgency_Score"] >= 60
        ),
        (
            intervention["Intervention_Urgency_Score"] >= 40
        ),
    ],
    [
        "Immediate",
        "High",
        "Moderate",
    ],
    default="Monitor"
)


# =============================================================================
# 11. INTERVENTION TYPE
# =============================================================================

def determine_intervention_type(row):

    if row["Predictive_Intelligence_Status"] == "No Current Warning":
        return "Monitoring / Intelligence Refresh"

    failure_prob = (
        row["Supplier_Failure_Probability"]
        if pd.notna(row["Supplier_Failure_Probability"])
        else 0
    )

    exposure = (
        row["Supply_Chain_Exposure_Score"]
        if pd.notna(row["Supply_Chain_Exposure_Score"])
        else 0
    )

    critical_materials = (
        row["Critical_Materials_Supplied"]
        if pd.notna(row["Critical_Materials_Supplied"])
        else 0
    )

    critical_assets = (
        row["Critical_Assets_Dependent"]
        if pd.notna(row["Critical_Assets_Dependent"])
        else 0
    )

    if failure_prob >= 0.80 and (
        critical_materials >= 2 or critical_assets >= 3
    ):
        return "Supplier Stabilisation + Business Continuity"

    if failure_prob >= 0.80:
        return "Immediate Supplier Intervention"

    if exposure >= 85:
        return "Supply-Chain Exposure Mitigation"

    if critical_materials >= 2:
        return "Critical Material Protection"

    if critical_assets >= 3:
        return "Critical Asset Dependency Mitigation"

    if failure_prob >= 0.60:
        return "Supplier Performance Intervention"

    if failure_prob >= 0.40:
        return "Enhanced Supplier Monitoring"

    return "Routine Monitoring"


intervention["Intervention_Type"] = intervention.apply(
    determine_intervention_type,
    axis=1
)


# =============================================================================
# 12. PRIMARY RECOMMENDED ACTION
# =============================================================================

def determine_primary_action(row):

    if row["Predictive_Intelligence_Status"] == "No Current Warning":
        return (
            "Obtain current predictive intelligence and continue supplier monitoring"
        )

    failure_prob = (
        row["Supplier_Failure_Probability"]
        if pd.notna(row["Supplier_Failure_Probability"])
        else 0
    )

    critical_materials = (
        row["Critical_Materials_Supplied"]
        if pd.notna(row["Critical_Materials_Supplied"])
        else 0
    )

    critical_assets = (
        row["Critical_Assets_Dependent"]
        if pd.notna(row["Critical_Assets_Dependent"])
        else 0
    )

    exposure = (
        row["Supply_Chain_Exposure_Score"]
        if pd.notna(row["Supply_Chain_Exposure_Score"])
        else 0
    )

    if failure_prob >= 0.80 and critical_assets >= 3:
        return (
            "Initiate immediate supplier intervention; "
            "protect critical assets; activate contingency supply"
        )

    if failure_prob >= 0.80 and critical_materials >= 2:
        return (
            "Initiate immediate supplier intervention; "
            "secure critical materials; activate alternate sourcing"
        )

    if failure_prob >= 0.80:
        return (
            "Initiate immediate supplier intervention; "
            "review supplier recovery plan"
        )

    if exposure >= 85:
        return (
            "Reduce supply-chain concentration; "
            "assess alternate suppliers and contingency inventory"
        )

    if critical_materials >= 2:
        return (
            "Protect critical materials; "
            "review safety-stock coverage and alternate sourcing"
        )

    if critical_assets >= 3:
        return (
            "Assess critical asset dependency; "
            "establish contingency supply arrangements"
        )

    if failure_prob >= 0.60:
        return (
            "Engage supplier on corrective action plan; "
            "increase monitoring frequency"
        )

    if failure_prob >= 0.40:
        return (
            "Increase supplier monitoring and review emerging failure signals"
        )

    return (
        "Continue routine monitoring and periodic supplier performance review"
    )


intervention["Recommended_Action"] = intervention.apply(
    determine_primary_action,
    axis=1
)


# =============================================================================
# 13. SECONDARY MITIGATION STRATEGY
# =============================================================================

def determine_mitigation(row):

    if row["Predictive_Intelligence_Status"] == "No Current Warning":
        return (
            "Refresh predictive assessment before assigning intervention"
        )

    failure_prob = (
        row["Supplier_Failure_Probability"]
        if pd.notna(row["Supplier_Failure_Probability"])
        else 0
    )

    critical_materials = (
        row["Critical_Materials_Supplied"]
        if pd.notna(row["Critical_Materials_Supplied"])
        else 0
    )

    critical_assets = (
        row["Critical_Assets_Dependent"]
        if pd.notna(row["Critical_Assets_Dependent"])
        else 0
    )

    if failure_prob >= 0.80:
        strategies = [
            "Alternate sourcing",
            "Supplier recovery plan",
            "Inventory protection",
            "Management escalation",
        ]

        if critical_materials >= 1:
            strategies.append("Critical-material buffer review")

        if critical_assets >= 1:
            strategies.append("Operational continuity planning")

        return "; ".join(strategies)

    if critical_materials >= 2:
        return (
            "Alternate sourcing; critical-material safety-stock review; "
            "inventory protection"
        )

    if critical_assets >= 3:
        return (
            "Contingency sourcing; asset dependency review; "
            "business continuity planning"
        )

    if failure_prob >= 0.60:
        return (
            "Supplier corrective action; performance monitoring; "
            "contingency sourcing assessment"
        )

    if failure_prob >= 0.40:
        return (
            "Enhanced monitoring; supplier engagement; "
            "early mitigation planning"
        )

    return "Routine monitoring"


intervention["Mitigation_Strategy"] = intervention.apply(
    determine_mitigation,
    axis=1
)


# =============================================================================
# 14. MANAGEMENT ESCALATION
# =============================================================================

def determine_escalation(row):

    priority = row["Intervention_Priority"]

    if priority == "Immediate":
        return "Executive / Supply Chain Leadership"

    if priority == "High":
        return "Supply Chain Risk Management"

    if priority == "Moderate":
        return "Supplier Management Team"

    return "Routine Supplier Management"


intervention["Management_Escalation"] = intervention.apply(
    determine_escalation,
    axis=1
)


# =============================================================================
# 15. INTERVENTION TIMEFRAME
# =============================================================================

intervention["Intervention_Timeframe"] = np.select(
    [
        intervention["Intervention_Priority"] == "Immediate",
        intervention["Intervention_Priority"] == "High",
        intervention["Intervention_Priority"] == "Moderate",
    ],
    [
        "0–7 days",
        "Within 14 days",
        "Within 30 days",
    ],
    default="Ongoing monitoring"
)


# =============================================================================
# 16. INTERVENTION STATUS
# =============================================================================

intervention["Intervention_Status"] = np.select(
    [
        intervention["Intervention_Priority"] == "Immediate",
        intervention["Intervention_Priority"] == "High",
        intervention["Intervention_Priority"] == "Moderate",
    ],
    [
        "Action Required",
        "Action Required",
        "Planned",
    ],
    default="Monitor"
)


# =============================================================================
# 17. RANK INTERVENTIONS
# =============================================================================

priority_order = {
    "Immediate": 1,
    "High": 2,
    "Moderate": 3,
    "Monitor": 4,
}


intervention["_Priority_Order"] = (
    intervention["Intervention_Priority"]
    .map(priority_order)
    .fillna(5)
)


intervention = intervention.sort_values(
    by=[
        "_Priority_Order",
        "Intervention_Urgency_Score",
        "Supplier_Risk_Priority_Score",
    ],
    ascending=[
        True,
        False,
        False,
    ]
).reset_index(drop=True)


intervention["Intervention_Rank"] = (
    intervention["Intervention_Urgency_Score"]
    .rank(
        method="dense",
        ascending=False
    )
    .astype("Int64")
)


intervention = intervention.drop(
    columns=["_Priority_Order"]
)


# =============================================================================
# 18. COLUMN ORDER
# =============================================================================

final_columns = [
    "Supplier_ID",
    "Supplier_Name",
    "Predictive_Intelligence_Status",

    "Supplier_Failure_Probability",
    "Failure_Risk_Flag",

    "Risk_Priority_Level",
    "Supplier_Risk_Priority_Score",

    "Supply_Chain_Exposure_Score",
    "Exposure_Risk_Flag",

    "Materials_Supplied",
    "Critical_Materials_Supplied",
    "Critical_Material_Dependency_Score",

    "Assets_Dependent",
    "Critical_Assets_Dependent",
    "Critical_Asset_Dependency_Score",
    "Critical_Dependency_Flag",

    "Intervention_Urgency_Score",
    "Intervention_Priority",
    "Intervention_Rank",

    "Intervention_Type",
    "Recommended_Action",
    "Mitigation_Strategy",
    "Management_Escalation",
    "Intervention_Timeframe",
    "Intervention_Status",
]


supplier_intervention = intervention[
    final_columns
].copy()


# =============================================================================
# 19. ROUND NUMERIC OUTPUTS
# =============================================================================

round_columns = [
    "Supplier_Failure_Probability",
    "Supplier_Risk_Priority_Score",
    "Supply_Chain_Exposure_Score",
    "Critical_Material_Dependency_Score",
    "Critical_Asset_Dependency_Score",
    "Intervention_Urgency_Score",
]


for col in round_columns:
    supplier_intervention[col] = (
        pd.to_numeric(
            supplier_intervention[col],
            errors="coerce"
        ).round(2)
    )


# =============================================================================
# 20. HARD VALIDATION
# =============================================================================

print()
print("=" * 90)
print("PHASE 12 — FINAL HARD VALIDATION")
print("=" * 90)


# Supplier population preserved
assert (
    supplier_intervention["Supplier_ID"].nunique()
    == supplier_input["Supplier_ID"].nunique()
), "Supplier population changed."


print("✓ Supplier population preserved")


# Supplier IDs unique
assert (
    supplier_intervention["Supplier_ID"].is_unique
), "Supplier IDs are not unique."


print("✓ Supplier IDs unique")


# Failure probability valid
failure_values = supplier_intervention[
    "Supplier_Failure_Probability"
].dropna()

assert (
    failure_values.between(0, 1).all()
), "Invalid failure probability detected."


print("✓ Failure probabilities valid")


# Urgency score valid
urgency_values = supplier_intervention[
    "Intervention_Urgency_Score"
].dropna()

assert (
    urgency_values.between(0, 100).all()
), "Invalid intervention urgency score detected."


print("✓ Intervention urgency scores valid")


# Priority valid
valid_priorities = {
    "Immediate",
    "High",
    "Moderate",
    "Monitor",
}

assert (
    set(supplier_intervention["Intervention_Priority"])
    .issubset(valid_priorities)
), "Invalid intervention priority detected."


print("✓ Intervention priority levels valid")


# Intervention action populated
assert (
    supplier_intervention["Recommended_Action"]
    .notna()
    .all()
), "Missing recommended intervention."


print("✓ Recommended interventions populated")


# Intervention timeframe populated
assert (
    supplier_intervention["Intervention_Timeframe"]
    .notna()
    .all()
), "Missing intervention timeframe."


print("✓ Intervention timeframes populated")


# Management escalation populated
assert (
    supplier_intervention["Management_Escalation"]
    .notna()
    .all()
), "Missing management escalation."


print("✓ Management escalation populated")


# No duplicate suppliers
assert (
    supplier_intervention["Supplier_ID"].duplicated().sum()
    == 0
), "Duplicate supplier intervention records detected."


print("✓ One intervention record per supplier")


# =============================================================================
# 21. PHASE 12 SUMMARY
# =============================================================================

phase12_supplier_count = (
    supplier_intervention["Supplier_ID"].nunique()
)

immediate_count = (
    supplier_intervention["Intervention_Priority"]
    .eq("Immediate")
    .sum()
)

high_count = (
    supplier_intervention["Intervention_Priority"]
    .eq("High")
    .sum()
)

moderate_count = (
    supplier_intervention["Intervention_Priority"]
    .eq("Moderate")
    .sum()
)

monitor_count = (
    supplier_intervention["Intervention_Priority"]
    .eq("Monitor")
    .sum()
)

action_required_count = (
    supplier_intervention["Intervention_Status"]
    .eq("Action Required")
    .sum()
)


# =============================================================================
# 22. CREATE PHASE 12 SUPPLIER SUMMARY
# =============================================================================

phase12_supplier_summary = supplier_intervention[
    [
        "Supplier_ID",
        "Supplier_Name",
        "Supplier_Failure_Probability",
        "Risk_Priority_Level",
        "Supplier_Risk_Priority_Score",
        "Supply_Chain_Exposure_Score",
        "Intervention_Urgency_Score",
        "Intervention_Priority",
        "Intervention_Type",
        "Recommended_Action",
        "Mitigation_Strategy",
        "Management_Escalation",
        "Intervention_Timeframe",
        "Intervention_Status",
    ]
].copy()


# =============================================================================
# 23. CRITICAL INTERVENTIONS
# =============================================================================

phase12_critical_interventions = (
    supplier_intervention[
        supplier_intervention["Intervention_Priority"]
        .isin(["Immediate", "High"])
    ]
    .sort_values(
        by="Intervention_Urgency_Score",
        ascending=False
    )
    .reset_index(drop=True)
)


# =============================================================================
# 24. INTERVENTION SUMMARY TABLE
# =============================================================================

phase12_intervention_summary = pd.DataFrame(
    {
        "Metric": [
            "Total suppliers",
            "Immediate intervention",
            "High-priority intervention",
            "Moderate intervention",
            "Monitor",
            "Action required",
            "Suppliers with current predictive warning",
            "Suppliers without current predictive warning",
        ],
        "Value": [
            phase12_supplier_count,
            immediate_count,
            high_count,
            moderate_count,
            monitor_count,
            action_required_count,
            (
                supplier_intervention[
                    "Predictive_Intelligence_Status"
                ]
                .eq("Current Warning Available")
                .sum()
            ),
            (
                supplier_intervention[
                    "Predictive_Intelligence_Status"
                ]
                .eq("No Current Warning")
                .sum()
            ),
        ],
    }
)


# =============================================================================
# 25. VALIDATION SUMMARY
# =============================================================================

phase12_validation_summary = pd.DataFrame(
    {
        "Validation": [
            "Supplier population preserved",
            "Supplier IDs unique",
            "Failure probabilities valid",
            "Urgency scores valid",
            "Intervention priorities valid",
            "Recommended actions populated",
            "Intervention timeframes populated",
            "Management escalation populated",
            "One intervention per supplier",
        ],
        "Status": [
            "PASS",
            "PASS",
            "PASS",
            "PASS",
            "PASS",
            "PASS",
            "PASS",
            "PASS",
            "PASS",
        ],
    }
)


# =============================================================================
# 26. DISPLAY PHASE 12 RESULTS
# =============================================================================

print()
print("=" * 90)
print("PHASE 12 — SUPPLIER INTERVENTION SUMMARY")
print("=" * 90)

print(
    phase12_intervention_summary.to_string(index=False)
)


print()
print("=" * 90)
print("TOP SUPPLIER INTERVENTIONS")
print("=" * 90)


display(
    supplier_intervention[
        [
            "Intervention_Rank",
            "Supplier_ID",
            "Supplier_Name",
            "Supplier_Failure_Probability",
            "Risk_Priority_Level",
            "Supply_Chain_Exposure_Score",
            "Intervention_Urgency_Score",
            "Intervention_Priority",
            "Intervention_Type",
            "Recommended_Action",
            "Intervention_Timeframe",
            "Management_Escalation",
        ]
    ].head(20)
)


print()
print("=" * 90)
print("SUPPLIERS REQUIRING IMMEDIATE / HIGH-PRIORITY ACTION")
print("=" * 90)


display(
    phase12_critical_interventions[
        [
            "Supplier_ID",
            "Supplier_Name",
            "Supplier_Failure_Probability",
            "Risk_Priority_Level",
            "Supplier_Risk_Priority_Score",
            "Supply_Chain_Exposure_Score",
            "Critical_Materials_Supplied",
            "Critical_Assets_Dependent",
            "Intervention_Urgency_Score",
            "Intervention_Priority",
            "Recommended_Action",
            "Mitigation_Strategy",
            "Intervention_Timeframe",
            "Management_Escalation",
        ]
    ]
)


# =============================================================================
# 27. FINAL VALIDATION DISPLAY
# =============================================================================

print()
print("=" * 90)
print("PHASE 12 — VALIDATION RESULTS")
print("=" * 90)

display(phase12_validation_summary)


# =============================================================================
# 28. FINAL ARCHITECTURE
# =============================================================================

print()
print("=" * 90)
print("PHASE 12 — FINAL SUMMARY")
print("=" * 90)

print(f"Total supplier population          : {phase12_supplier_count}")
print(f"Immediate interventions            : {immediate_count}")
print(f"High-priority interventions        : {high_count}")
print(f"Moderate interventions             : {moderate_count}")
print(f"Monitor-only suppliers             : {monitor_count}")
print(f"Action-required suppliers          : {action_required_count}")
print(
    f"Final intervention records         : "
    f"{len(supplier_intervention)}"
)
print(
    f"Final columns                      : "
    f"{len(supplier_intervention.columns)}"
)


print()
print("=" * 90)
print("✓ PHASE 12 COMPLETED SUCCESSFULLY")
print("=" * 90)


print()
print(
    """
FINAL INTERVENTION ARCHITECTURE

Supplier
   ↓
Predictive Failure Probability
   ↓
Current Supplier Risk
   ↓
Supply-Chain Exposure
   ↓
Critical Material Exposure
   ↓
Critical Asset Dependency
   ↓
Intervention Urgency
   ↓
Intervention Priority
   ↓
Intervention Type
   ↓
Recommended Action
   ↓
Mitigation Strategy
   ↓
Management Escalation
   ↓
Intervention Timeframe
   ↓
INTERVENTION ENGINE
"""
)


print()
print("FINAL OBJECTS:")
print("    supplier_intervention")
print("    phase12_supplier_summary")
print("    phase12_critical_interventions")
print("    phase12_intervention_summary")
print("    phase12_validation_summary")


print()
print("=" * 90)
print("NEXT:")
print("PHASE 13 — EARLY-WARNING / ALERT GENERATION ENGINE")
print("=" * 90)

==========================================================================================
KEYSTRA — PHASE 12
SUPPLIER INTERVENTION ENGINE
==========================================================================================

==========================================================================================
PHASE 12 — FINAL HARD VALIDATION
==========================================================================================
✓ Supplier population preserved
✓ Supplier IDs unique
✓ Failure probabilities valid
✓ Intervention urgency scores valid
✓ Intervention priority levels valid
✓ Recommended interventions populated
✓ Intervention timeframes populated
✓ Management escalation populated
✓ One intervention record per supplier

==========================================================================================
PHASE 12 — SUPPLIER INTERVENTION SUMMARY
==========================================================================================
                                      Metric  Value
                             Total suppliers     90
                      Immediate intervention     16
                  High-priority intervention     36
                       Moderate intervention     27
                                     Monitor     11
                             Action required     52
   Suppliers with current predictive warning     88
Suppliers without current predictive warning      2

==========================================================================================
TOP SUPPLIER INTERVENTIONS
==========================================================================================

,Intervention_Rank,Supplier_ID,Supplier_Name,Supplier_Failure_Probability,Risk_Priority_Level,Supply_Chain_Exposure_Score,Intervention_Urgency_Score,Intervention_Priority,Intervention_Type,Recommended_Action,Intervention_Timeframe,Management_Escalation
0,1,S081,SunCore Energy Technologies Ltd.,0.99,Critical,100.00,99.64,Immediate,Supplier Stabilisation + Business Continuity,Initiate immediate supplier intervention; prot...,0–7 days,Executive / Supply Chain Leadership
1,2,S004,Sterling Industrial Equipment Ltd.,0.92,Critical,100.00,96.70,Immediate,Supplier Stabilisation + Business Continuity,Initiate immediate supplier intervention; prot...,0–7 days,Executive / Supply Chain Leadership
2,3,S055,Process Materials Solutions Ltd.,0.99,Critical,93.75,95.40,Immediate,Supplier Stabilisation + Business Continuity,Initiate immediate supplier intervention; prot...,0–7 days,Executive / Supply Chain Leadership
3,4,S019,Powerlink Industrial Systems Ltd.,0.80,High,87.50,83.30,Immediate,Supplier Stabilisation + Business Continuity,Initiate immediate supplier intervention; prot...,0–7 days,Executive / Supply Chain Leadership
4,5,S034,NexControl Engineering Ltd.,0.50,High,100.00,79.81,Immediate,Supply-Chain Exposure Mitigation,Reduce supply-chain concentration; assess alte...,0–7 days,Executive / Supply Chain Leadership
5,6,S057,CoreProcess Materials Ltd.,0.49,High,100.00,79.50,Immediate,Supply-Chain Exposure Mitigation,Reduce supply-chain concentration; assess alte...,0–7 days,Executive / Supply Chain Leadership
6,7,S025,Brightline Electrical Industries Ltd.,0.99,High,63.50,78.78,Immediate,Supplier Stabilisation + Business Continuity,Initiate immediate supplier intervention; prot...,0–7 days,Executive / Supply Chain Leadership
7,8,S009,Ironbridge Equipment Solutions Ltd.,0.99,High,63.50,78.75,Immediate,Supplier Stabilisation + Business Continuity,Initiate immediate supplier intervention; prot...,0–7 days,Executive / Supply Chain Leadership
8,9,S058,Nexus Industrial Supply Ltd.,0.99,High,63.50,78.72,Immediate,Supplier Stabilisation + Business Continuity,Initiate immediate supplier intervention; prot...,0–7 days,Executive / Supply Chain Leadership
9,10,S003,Atlas Turbomachinery Services Ltd.,0.99,High,63.50,78.65,Immediate,Supplier Stabilisation + Business Continuity,Initiate immediate supplier intervention; prot...,0–7 days,Executive / Supply Chain Leadership
10,11,S087,Continental Industrial Services Ltd.,0.99,High,63.50,78.62,Immediate,Supplier Stabilisation + Business Continuity,Initiate immediate supplier intervention; prot...,0–7 days,Executive / Supply Chain Leadership
11,12,S030,Axis Process Controls Ltd.,0.98,High,63.50,78.24,Immediate,Supplier Stabilisation + Business Continuity,Initiate immediate supplier intervention; prot...,0–7 days,Executive / Supply Chain Leadership
12,13,S035,Advanced Process Instruments Ltd.,0.98,High,63.50,78.12,Immediate,Supplier Stabilisation + Business Continuity,Initiate immediate supplier intervention; prot...,0–7 days,Executive / Supply Chain Leadership
13,14,S001,Apex Rotating Systems Ltd.,0.93,High,63.50,76.27,Immediate,Immediate Supplier Intervention,Initiate immediate supplier intervention; revi...,0–7 days,Executive / Supply Chain Leadership
14,15,S054,Industrial Supply Partners Ltd.,0.92,High,63.50,75.88,Immediate,Supplier Stabilisation + Business Continuity,Initiate immediate supplier intervention; prot...,0–7 days,Executive / Supply Chain Leadership
15,16,S010,Pinnacle Machinery Services Ltd.,0.99,High,52.00,75.13,Immediate,Supplier Stabilisation + Business Continuity,Initiate immediate supplier intervention; prot...,0–7 days,Executive / Supply Chain Leadership
16,17,S086,Integrated Energy Supply Solutions Ltd.,0.55,High,90.00,74.92,High,Supply-Chain Exposure Mitigation,Reduce supply-chain concentration; assess alte...,Within 14 days,Supply Chain Risk Management
17,18,S013,Westfield Industrial Engineering Ltd.,0.98,High,52.00,74.90,High,Supplier Stabilisation + Business Continuity,Initiate immediate supplier intervention; prot...,Within 14 days,Supply Chain Risk Management
18,19,S047,DeltaFlow Technologies Ltd.,0.90,High,63.50,74.86,High,Immediate Supplier Intervention,Initiate immediate supplier intervention; revi...,Within 14 days,Supply Chain Risk Management
19,20,S018,Crown Electrical Technologies Ltd.,0.97,High,52.00,74.22,High,Supplier Stabilisation + Business Continuity,Initiate immediate supplier intervention; prot...,Within 14 days,Supply Chain Risk Management

==========================================================================================
SUPPLIERS REQUIRING IMMEDIATE / HIGH-PRIORITY ACTION
==========================================================================================

,Supplier_ID,Supplier_Name,Supplier_Failure_Probability,Risk_Priority_Level,Supplier_Risk_Priority_Score,Supply_Chain_Exposure_Score,Critical_Materials_Supplied,Critical_Assets_Dependent,Intervention_Urgency_Score,Intervention_Priority,Recommended_Action,Mitigation_Strategy,Intervention_Timeframe,Management_Escalation
0,S081,SunCore Energy Technologies Ltd.,0.99,Critical,83.04,100.00,3.0,5.0,99.64,Immediate,Initiate immediate supplier intervention; prot...,Alternate sourcing; Supplier recovery plan; In...,0–7 days,Executive / Supply Chain Leadership
1,S004,Sterling Industrial Equipment Ltd.,0.92,Critical,81.30,100.00,5.0,5.0,96.70,Immediate,Initiate immediate supplier intervention; prot...,Alternate sourcing; Supplier recovery plan; In...,0–7 days,Executive / Supply Chain Leadership
2,S055,Process Materials Solutions Ltd.,0.99,Critical,81.93,93.75,3.0,8.0,95.40,Immediate,Initiate immediate supplier intervention; prot...,Alternate sourcing; Supplier recovery plan; In...,0–7 days,Executive / Supply Chain Leadership
3,S019,Powerlink Industrial Systems Ltd.,0.80,High,72.35,87.50,2.0,10.0,83.30,Immediate,Initiate immediate supplier intervention; prot...,Alternate sourcing; Supplier recovery plan; In...,0–7 days,Executive / Supply Chain Leadership
4,S034,NexControl Engineering Ltd.,0.50,High,62.81,100.00,2.0,4.0,79.81,Immediate,Reduce supply-chain concentration; assess alte...,Alternate sourcing; critical-material safety-s...,0–7 days,Executive / Supply Chain Leadership
5,S057,CoreProcess Materials Ltd.,0.49,High,62.50,100.00,2.0,2.0,79.50,Immediate,Reduce supply-chain concentration; assess alte...,Alternate sourcing; critical-material safety-s...,0–7 days,Executive / Supply Chain Leadership
6,S025,Brightline Electrical Industries Ltd.,0.99,High,72.15,63.50,0.0,10.0,78.78,Immediate,Initiate immediate supplier intervention; prot...,Alternate sourcing; Supplier recovery plan; In...,0–7 days,Executive / Supply Chain Leadership
7,S009,Ironbridge Equipment Solutions Ltd.,0.99,High,71.53,63.50,0.0,8.0,78.75,Immediate,Initiate immediate supplier intervention; prot...,Alternate sourcing; Supplier recovery plan; In...,0–7 days,Executive / Supply Chain Leadership
8,S058,Nexus Industrial Supply Ltd.,0.99,High,71.29,63.50,0.0,8.0,78.72,Immediate,Initiate immediate supplier intervention; prot...,Alternate sourcing; Supplier recovery plan; In...,0–7 days,Executive / Supply Chain Leadership
9,S003,Atlas Turbomachinery Services Ltd.,0.99,High,71.22,63.50,0.0,3.0,78.65,Immediate,Initiate immediate supplier intervention; prot...,Alternate sourcing; Supplier recovery plan; In...,0–7 days,Executive / Supply Chain Leadership
10,S087,Continental Industrial Services Ltd.,0.99,High,71.39,63.50,0.0,5.0,78.62,Immediate,Initiate immediate supplier intervention; prot...,Alternate sourcing; Supplier recovery plan; In...,0–7 days,Executive / Supply Chain Leadership
11,S030,Axis Process Controls Ltd.,0.98,High,70.82,63.50,0.0,3.0,78.24,Immediate,Initiate immediate supplier intervention; prot...,Alternate sourcing; Supplier recovery plan; In...,0–7 days,Executive / Supply Chain Leadership
12,S035,Advanced Process Instruments Ltd.,0.98,High,72.50,63.50,0.0,8.0,78.12,Immediate,Initiate immediate supplier intervention; prot...,Alternate sourcing; Supplier recovery plan; In...,0–7 days,Executive / Supply Chain Leadership
13,S001,Apex Rotating Systems Ltd.,0.93,High,70.04,63.50,0.0,2.0,76.27,Immediate,Initiate immediate supplier intervention; revi...,Alternate sourcing; Supplier recovery plan; In...,0–7 days,Executive / Supply Chain Leadership
14,S054,Industrial Supply Partners Ltd.,0.92,High,69.25,63.50,0.0,11.0,75.88,Immediate,Initiate immediate supplier intervention; prot...,Alternate sourcing; Supplier recovery plan; In...,0–7 days,Executive / Supply Chain Leadership
15,S010,Pinnacle Machinery Services Ltd.,0.99,High,65.18,52.00,0.0,5.0,75.13,Immediate,Initiate immediate supplier intervention; prot...,Alternate sourcing; Supplier recovery plan; In...,0–7 days,Executive / Supply Chain Leadership
16,S086,Integrated Energy Supply Solutions Ltd.,0.55,High,63.12,90.00,3.0,14.0,74.92,High,Reduce supply-chain concentration; assess alte...,Alternate sourcing; critical-material safety-s...,Within 14 days,Supply Chain Risk Management
17,S013,Westfield Industrial Engineering Ltd.,0.98,High,64.75,52.00,0.0,5.0,74.90,High,Initiate immediate supplier intervention; prot...,Alternate sourcing; Supplier recovery plan; In...,Within 14 days,Supply Chain Risk Management
18,S047,DeltaFlow Technologies Ltd.,0.90,High,68.24,63.50,0.0,2.0,74.86,High,Initiate immediate supplier intervention; revi...,Alternate sourcing; Supplier recovery plan; In...,Within 14 days,Supply Chain Risk Management
19,S018,Crown Electrical Technologies Ltd.,0.97,High,65.87,52.00,0.0,8.0,74.22,High,Initiate immediate supplier intervention; prot...,Alternate sourcing; Supplier recovery plan; In...,Within 14 days,Supply Chain Risk Management
20,S079,SolarEdge Industrial Energy Ltd.,0.94,High,63.50,52.00,0.0,2.0,73.05,High,Initiate immediate supplier intervention; revi...,Alternate sourcing; Supplier recovery plan; In...,Within 14 days,Supply Chain Risk Management
21,S062,Reliable Industrial Materials Ltd.,0.93,High,63.61,52.00,0.0,2.0,72.96,High,Initiate immediate supplier intervention; revi...,Alternate sourcing; Supplier recovery plan; In...,Within 14 days,Supply Chain Risk Management
22,S069,WestAfrica Chemical Solutions Ltd.,0.91,High,63.40,52.00,0.0,2.0,72.15,High,Initiate immediate supplier intervention; revi...,Alternate sourcing; Supplier recovery plan; In...,Within 14 days,Supply Chain Risk Management
23,S061,MetroProcess Supplies Ltd.,1.00,Moderate,59.10,40.50,0.0,1.0,71.97,High,Initiate immediate supplier intervention; revi...,Alternate sourcing; Supplier recovery plan; In...,Within 14 days,Supply Chain Risk Management
24,S089,Nexus Energy Equipment Solutions Ltd.,0.90,High,61.73,52.00,0.0,11.0,71.68,High,Initiate immediate supplier intervention; prot...,Alternate sourcing; Supplier recovery plan; In...,Within 14 days,Supply Chain Risk Management
25,S038,OptiSense Systems Ltd.,0.98,Moderate,58.37,40.50,0.0,1.0,71.25,High,Initiate immediate supplier intervention; revi...,Alternate sourcing; Supplier recovery plan; In...,Within 14 days,Supply Chain Risk Management
26,S082,RenewPower Engineering Ltd.,0.89,High,60.89,52.00,0.0,2.0,71.04,High,Initiate immediate supplier intervention; revi...,Alternate sourcing; Supplier recovery plan; In...,Within 14 days,Supply Chain Risk Management
27,S015,Grandview Mechanical Systems Ltd.,0.87,High,60.12,52.00,0.0,3.0,70.27,High,Initiate immediate supplier intervention; prot...,Alternate sourcing; Supplier recovery plan; In...,Within 14 days,Supply Chain Risk Management
28,S090,Frontier Industrial Technologies Ltd.,0.86,Moderate,59.99,52.00,0.0,4.0,70.14,High,Initiate immediate supplier intervention; prot...,Alternate sourcing; Supplier recovery plan; In...,Within 14 days,Supply Chain Risk Management
29,S040,FlowGuard Industrial Ltd.,0.86,High,61.34,52.00,0.0,3.0,70.09,High,Initiate immediate supplier intervention; prot...,Alternate sourcing; Supplier recovery plan; In...,Within 14 days,Supply Chain Risk Management
30,S024,Enertech Power Solutions Ltd.,0.94,Moderate,57.15,40.50,0.0,3.0,69.82,High,Initiate immediate supplier intervention; prot...,Alternate sourcing; Supplier recovery plan; In...,Within 14 days,Supply Chain Risk Management
31,S071,ProcessChem Technologies Ltd.,0.84,Moderate,59.69,52.00,0.0,6.0,69.04,High,Initiate immediate supplier intervention; prot...,Alternate sourcing; Supplier recovery plan; In...,Within 14 days,Supply Chain Risk Management
32,S059,Westbridge Process Supplies Ltd.,0.33,Moderate,55.14,93.75,3.0,10.0,69.02,High,Reduce supply-chain concentration; assess alte...,Alternate sourcing; critical-material safety-s...,Within 14 days,Supply Chain Risk Management
33,S076,Sentinel Safety Equipment Ltd.,0.89,Moderate,56.30,40.50,0.0,5.0,67.78,High,Initiate immediate supplier intervention; prot...,Alternate sourcing; Supplier recovery plan; In...,Within 14 days,Supply Chain Risk Management
34,S014,Orion Machinery & Engineering Ltd.,0.79,Moderate,57.16,52.00,0.0,2.0,67.31,High,Engage supplier on corrective action plan; inc...,Supplier corrective action; performance monito...,Within 14 days,Supply Chain Risk Management
35,S011,BluePeak Mechanical Systems Ltd.,0.79,Moderate,56.97,52.00,0.0,2.0,67.12,High,Engage supplier on corrective action plan; inc...,Supplier corrective action; performance monito...,Within 14 days,Supply Chain Risk Management
36,S064,PetroChem Solutions Ltd.,0.87,Moderate,55.35,40.50,0.0,3.0,66.83,High,Initiate immediate supplier intervention; prot...,Alternate sourcing; Supplier recovery plan; In...,Within 14 days,Supply Chain Risk Management
37,S063,General Process Solutions Ltd.,0.68,Moderate,59.90,63.50,0.0,2.0,66.12,High,Engage supplier on corrective action plan; inc...,Supplier corrective action; performance monito...,Within 14 days,Supply Chain Risk Management
38,S028,Precision Control Technologies Ltd.,0.15,Moderate,49.61,100.00,2.0,2.0,66.01,High,Reduce supply-chain concentration; assess alte...,Alternate sourcing; critical-material safety-s...,Within 14 days,Supply Chain Risk Management
39,S044,Precision Valve Systems Ltd.,0.67,Moderate,58.47,63.50,0.0,7.0,65.90,High,Assess critical asset dependency; establish co...,Contingency sourcing; asset dependency review;...,Within 14 days,Supply Chain Risk Management
40,S007,Prime Industrial Machinery Ltd.,0.67,Moderate,58.83,63.50,0.0,3.0,65.66,High,Assess critical asset dependency; establish co...,Contingency sourcing; asset dependency review;...,Within 14 days,Supply Chain Risk Management
41,S008,Vector Mechanical Engineering Ltd.,0.75,Moderate,55.71,52.00,0.0,4.0,65.66,High,Assess critical asset dependency; establish co...,Contingency sourcing; asset dependency review;...,Within 14 days,Supply Chain Risk Management
42,S032,ClearPoint Instrumentation Ltd.,0.66,Moderate,58.13,63.50,0.0,3.0,65.56,High,Assess critical asset dependency; establish co...,Contingency sourcing; asset dependency review;...,Within 14 days,Supply Chain Risk Management
43,S021,PrimeVolt Engineering Services Ltd.,0.65,Moderate,57.51,63.50,0.0,2.0,64.94,High,Engage supplier on corrective action plan; inc...,Supplier corrective action; performance monito...,Within 14 days,Supply Chain Risk Management
44,S033,ProSense Industrial Controls Ltd.,0.64,Moderate,57.27,63.50,0.0,12.0,64.49,High,Assess critical asset dependency; establish co...,Contingency sourcing; asset dependency review;...,Within 14 days,Supply Chain Risk Management
45,S017,VoltEdge Engineering Ltd.,0.63,Moderate,57.10,63.50,0.0,14.0,64.32,High,Assess critical asset dependency; establish co...,Contingency sourcing; asset dependency review;...,Within 14 days,Supply Chain Risk Management
46,S022,Northbridge Power Equipment Ltd.,0.61,Moderate,56.00,63.50,0.0,2.0,63.42,High,Engage supplier on corrective action plan; inc...,Supplier corrective action; performance monito...,Within 14 days,Supply Chain Risk Management
47,S056,ProServe Industrial Supplies Ltd.,0.07,Moderate,47.17,100.00,2.0,3.0,62.97,High,Reduce supply-chain concentration; assess alte...,Alternate sourcing; critical-material safety-s...,Within 14 days,Supply Chain Risk Management
48,S026,VectorGrid Technologies Ltd.,0.68,Moderate,52.76,52.00,0.0,3.0,62.71,High,Assess critical asset dependency; establish co...,Contingency sourcing; asset dependency review;...,Within 14 days,Supply Chain Risk Management
49,S036,ControlSphere Technologies Ltd.,0.58,Moderate,54.89,63.50,0.0,3.0,62.32,High,Assess critical asset dependency; establish co...,Contingency sourcing; asset dependency review;...,Within 14 days,Supply Chain Risk Management
50,S065,LubriTech Industrial Ltd.,0.63,Moderate,50.84,52.00,0.0,3.0,60.79,High,Assess critical asset dependency; establish co...,Contingency sourcing; asset dependency review;...,Within 14 days,Supply Chain Risk Management
51,S083,HelioGrid Solutions Ltd.,0.71,Moderate,47.61,40.50,0.0,3.0,60.48,High,Assess critical asset dependency; establish co...,Contingency sourcing; asset dependency review;...,Within 14 days,Supply Chain Risk Management

==========================================================================================
PHASE 12 — VALIDATION RESULTS
==========================================================================================

                          Validation Status
0      Supplier population preserved   PASS
1                Supplier IDs unique   PASS
2        Failure probabilities valid   PASS
3               Urgency scores valid   PASS
4      Intervention priorities valid   PASS
5      Recommended actions populated   PASS
6  Intervention timeframes populated   PASS
7    Management escalation populated   PASS
8      One intervention per supplier   PASS

==========================================================================================
PHASE 12 — FINAL SUMMARY
==========================================================================================
Total supplier population          : 90
Immediate interventions            : 16
High-priority interventions        : 36
Moderate interventions             : 27
Monitor-only suppliers             : 11
Action-required suppliers          : 52
Final intervention records         : 90
Final columns                      : 25

==========================================================================================
✓ PHASE 12 COMPLETED SUCCESSFULLY
==========================================================================================


FINAL INTERVENTION ARCHITECTURE

Supplier
   ↓
Predictive Failure Probability
   ↓
Current Supplier Risk
   ↓
Supply-Chain Exposure
   ↓
Critical Material Exposure
   ↓
Critical Asset Dependency
   ↓
Intervention Urgency
   ↓
Intervention Priority
   ↓
Intervention Type
   ↓
Recommended Action
   ↓
Mitigation Strategy
   ↓
Management Escalation
   ↓
Intervention Timeframe
   ↓
INTERVENTION ENGINE


FINAL OBJECTS:
    supplier_intervention
    phase12_supplier_summary
    phase12_critical_interventions
    phase12_intervention_summary
    phase12_validation_summary

==========================================================================================
NEXT:
PHASE 13 — EARLY-WARNING / ALERT GENERATION ENGINE
==========================================================================================

In [24]:
# =============================================================================
# KEYSTRA — PHASE 13
# SUPPLIER EARLY-WARNING / ALERT GENERATION ENGINE
# =============================================================================
#
# Purpose:
#   Convert supplier risk + predictive failure + exposure + intervention
#   intelligence into actionable early-warning alerts.
#
# Upstream object:
#   supplier_intervention
#
# Main outputs:
#   supplier_early_warning
#   phase13_alert_summary
#   phase13_critical_alerts
#   phase13_high_alerts
#   phase13_validation_summary
#
# Reference Date:
#   2026-07-31
#
# =============================================================================

import pandas as pd
import numpy as np

REFERENCE_DATE = pd.Timestamp("2026-07-31")

print("=" * 90)
print("KEYSTRA — PHASE 13")
print("SUPPLIER EARLY-WARNING / ALERT GENERATION ENGINE")
print("=" * 90)


# =============================================================================
# 1. HARD INPUT VALIDATION
# =============================================================================

print("\n" + "=" * 90)
print("PHASE 13 — INPUT VALIDATION")
print("=" * 90)

required_objects = [
    "supplier_intervention"
]

missing_objects = [
    obj for obj in required_objects
    if obj not in globals()
]

if missing_objects:
    raise NameError(
        f"Required upstream object(s) missing: {missing_objects}. "
        "Run Phase 12 successfully before Phase 13."
    )

if not isinstance(supplier_intervention, pd.DataFrame):
    raise TypeError(
        "supplier_intervention must be a pandas DataFrame."
    )

print("✓ supplier_intervention found")
print(f"✓ Input rows    : {len(supplier_intervention):,}")
print(f"✓ Input columns : {len(supplier_intervention.columns):,}")


# =============================================================================
# 2. REQUIRED COLUMNS
# =============================================================================

required_columns = [
    "Supplier_ID",
    "Supplier_Name",
    "Supplier_Failure_Probability",
    "Risk_Priority_Level",
    "Supplier_Risk_Priority_Score",
    "Supply_Chain_Exposure_Score",
    "Intervention_Urgency_Score",
    "Intervention_Priority",
    "Intervention_Type",
    "Recommended_Action",
    "Mitigation_Strategy",
    "Intervention_Timeframe",
    "Management_Escalation"
]

missing_columns = [
    col for col in required_columns
    if col not in supplier_intervention.columns
]

if missing_columns:
    raise ValueError(
        f"Phase 12 output is missing required columns: {missing_columns}"
    )

print("✓ All required Phase 12 columns available")


# =============================================================================
# 3. CREATE CLEAN WORKING COPY
# =============================================================================

supplier_early_warning = supplier_intervention.copy()

# Prevent accidental mutation of upstream object
supplier_early_warning = supplier_early_warning.reset_index(drop=True)


# =============================================================================
# 4. NUMERIC STANDARDISATION
# =============================================================================

numeric_columns = [
    "Supplier_Failure_Probability",
    "Supplier_Risk_Priority_Score",
    "Supply_Chain_Exposure_Score",
    "Intervention_Urgency_Score"
]

for col in numeric_columns:
    supplier_early_warning[col] = pd.to_numeric(
        supplier_early_warning[col],
        errors="coerce"
    )


# =============================================================================
# 5. CURRENT WARNING STATUS
# =============================================================================

supplier_early_warning["Current_Warning_Status"] = np.where(
    supplier_early_warning["Supplier_Failure_Probability"].notna(),
    "Current Warning Available",
    "No Current Warning"
)

print("\n" + "=" * 90)
print("CURRENT PREDICTIVE WARNING COVERAGE")
print("=" * 90)

warning_counts = (
    supplier_early_warning["Current_Warning_Status"]
    .value_counts()
)

print(
    f"Current warning available : "
    f"{warning_counts.get('Current Warning Available', 0):,}"
)

print(
    f"No current warning        : "
    f"{warning_counts.get('No Current Warning', 0):,}"
)

print(
    f"Total suppliers           : "
    f"{len(supplier_early_warning):,}"
)


# =============================================================================
# 6. EARLY-WARNING SIGNAL COMPONENTS
# =============================================================================
#
# The alert engine does NOT simply copy Intervention_Priority.
#
# It evaluates:
#
#   Predictive Failure Probability
#   +
#   Supplier Risk Priority
#   +
#   Supply Chain Exposure
#   +
#   Intervention Urgency
#
# This gives the alert engine an independent analytical layer.
# =============================================================================

supplier_early_warning["Failure_Risk_Score"] = (
    supplier_early_warning["Supplier_Failure_Probability"]
    .fillna(0)
    .clip(0, 1)
    * 100
)

supplier_early_warning["Risk_Priority_Component"] = (
    supplier_early_warning["Supplier_Risk_Priority_Score"]
    .fillna(0)
    .clip(0, 100)
)

supplier_early_warning["Exposure_Component"] = (
    supplier_early_warning["Supply_Chain_Exposure_Score"]
    .fillna(0)
    .clip(0, 100)
)

supplier_early_warning["Urgency_Component"] = (
    supplier_early_warning["Intervention_Urgency_Score"]
    .fillna(0)
    .clip(0, 100)
)


# =============================================================================
# 7. EARLY-WARNING SEVERITY SCORE
# =============================================================================
#
# Weighting:
#
# Failure probability       = 35%
# Supplier risk priority    = 25%
# Supply-chain exposure     = 20%
# Intervention urgency      = 20%
#
# This preserves predictive risk as the strongest driver while ensuring
# operational exposure materially influences the alert.
# =============================================================================

supplier_early_warning["Early_Warning_Severity_Score"] = (
    0.35 * supplier_early_warning["Failure_Risk_Score"]
    + 0.25 * supplier_early_warning["Risk_Priority_Component"]
    + 0.20 * supplier_early_warning["Exposure_Component"]
    + 0.20 * supplier_early_warning["Urgency_Component"]
)

supplier_early_warning["Early_Warning_Severity_Score"] = (
    supplier_early_warning["Early_Warning_Severity_Score"]
    .clip(0, 100)
    .round(2)
)


# =============================================================================
# 8. ALERT SEVERITY CLASSIFICATION
# =============================================================================
#
# Critical:
#   Very high probability / exposure / urgency.
#
# High:
#   Material risk requiring proactive management.
#
# Moderate:
#   Risk requires monitoring and planned mitigation.
#
# Low:
#   No immediate escalation but retain monitoring.
#
# No Current Warning:
#   No predictive probability currently available.
# =============================================================================

def classify_alert(row):

    probability = row["Supplier_Failure_Probability"]
    severity = row["Early_Warning_Severity_Score"]
    exposure = row["Supply_Chain_Exposure_Score"]
    urgency = row["Intervention_Urgency_Score"]

    if pd.isna(probability):
        return "No Current Warning"

    # Critical alert conditions
    if (
        probability >= 0.90
        and severity >= 80
    ):
        return "Critical"

    if (
        severity >= 80
        and exposure >= 90
    ):
        return "Critical"

    if (
        probability >= 0.95
        and exposure >= 75
    ):
        return "Critical"

    # High alert conditions
    if (
        severity >= 65
        or probability >= 0.80
        or urgency >= 70
    ):
        return "High"

    # Moderate alert
    if (
        severity >= 45
        or probability >= 0.50
        or exposure >= 60
    ):
        return "Moderate"

    return "Low"


supplier_early_warning["Alert_Severity"] = (
    supplier_early_warning.apply(
        classify_alert,
        axis=1
    )
)


# =============================================================================
# 9. ALERT TYPE
# =============================================================================

def determine_alert_type(row):

    if row["Alert_Severity"] == "No Current Warning":
        return "No Current Predictive Alert"

    probability = row["Supplier_Failure_Probability"]
    exposure = row["Supply_Chain_Exposure_Score"]
    urgency = row["Intervention_Urgency_Score"]

    if probability >= 0.80 and exposure >= 75:
        return "Predictive Supplier Failure + Exposure Alert"

    if probability >= 0.80:
        return "Predictive Supplier Failure Alert"

    if exposure >= 75:
        return "Supply-Chain Exposure Alert"

    if urgency >= 70:
        return "Intervention Escalation Alert"

    if probability >= 0.50:
        return "Emerging Supplier Risk Alert"

    return "Supplier Risk Monitoring Alert"


supplier_early_warning["Alert_Type"] = (
    supplier_early_warning.apply(
        determine_alert_type,
        axis=1
    )
)


# =============================================================================
# 10. ALERT STATUS
# =============================================================================

def determine_alert_status(row):

    severity = row["Alert_Severity"]

    if severity == "Critical":
        return "Active — Immediate Action"

    if severity == "High":
        return "Active — Management Attention"

    if severity == "Moderate":
        return "Active — Monitor & Mitigate"

    if severity == "Low":
        return "Monitoring"

    return "No Active Alert"


supplier_early_warning["Alert_Status"] = (
    supplier_early_warning.apply(
        determine_alert_status,
        axis=1
    )
)


# =============================================================================
# 11. ALERT TRIGGER
# =============================================================================

def determine_trigger(row):

    probability = row["Supplier_Failure_Probability"]
    exposure = row["Supply_Chain_Exposure_Score"]
    urgency = row["Intervention_Urgency_Score"]
    severity = row["Early_Warning_Severity_Score"]

    if pd.isna(probability):
        return "No predictive failure signal currently available"

    triggers = []

    if probability >= 0.90:
        triggers.append(
            "Very high supplier failure probability"
        )
    elif probability >= 0.80:
        triggers.append(
            "High supplier failure probability"
        )
    elif probability >= 0.50:
        triggers.append(
            "Elevated supplier failure probability"
        )

    if exposure >= 90:
        triggers.append(
            "Very high supply-chain exposure"
        )
    elif exposure >= 75:
        triggers.append(
            "High supply-chain exposure"
        )

    if urgency >= 80:
        triggers.append(
            "Very high intervention urgency"
        )
    elif urgency >= 70:
        triggers.append(
            "High intervention urgency"
        )

    if severity >= 80:
        triggers.append(
            "Critical composite early-warning severity"
        )

    if not triggers:
        triggers.append(
            "Emerging supplier risk signal"
        )

    return " + ".join(triggers)


supplier_early_warning["Alert_Trigger"] = (
    supplier_early_warning.apply(
        determine_trigger,
        axis=1
    )
)


# =============================================================================
# 12. EARLY-WARNING MESSAGE
# =============================================================================

def generate_alert_message(row):

    supplier = row["Supplier_Name"]
    severity = row["Alert_Severity"]
    probability = row["Supplier_Failure_Probability"]

    if pd.isna(probability):
        return (
            f"No current predictive warning available for {supplier}. "
            f"Continue monitoring and obtain refreshed predictive intelligence."
        )

    probability_pct = round(probability * 100, 1)

    if severity == "Critical":
        return (
            f"CRITICAL EARLY WARNING: {supplier} has a "
            f"{probability_pct}% predicted supplier-failure probability "
            f"with material supply-chain exposure. Immediate intervention "
            f"and continuity protection are required."
        )

    if severity == "High":
        return (
            f"HIGH EARLY WARNING: {supplier} has a "
            f"{probability_pct}% predicted supplier-failure probability "
            f"and requires proactive risk mitigation."
        )

    if severity == "Moderate":
        return (
            f"MODERATE EARLY WARNING: {supplier} shows emerging supplier "
            f"failure risk. Planned mitigation and closer monitoring are recommended."
        )

    return (
        f"LOW EARLY WARNING: {supplier} currently shows limited immediate "
        f"risk but should remain under routine monitoring."
    )


supplier_early_warning["Early_Warning_Message"] = (
    supplier_early_warning.apply(
        generate_alert_message,
        axis=1
    )
)


# =============================================================================
# 13. RECOMMENDED RESPONSE
# =============================================================================

def generate_response(row):

    severity = row["Alert_Severity"]

    if severity == "Critical":
        return (
            "Activate supplier recovery plan; protect critical materials; "
            "secure alternate sourcing; review operational continuity exposure; "
            "escalate to executive leadership."
        )

    if severity == "High":
        return (
            "Engage supplier; initiate corrective action; assess alternate "
            "sources; protect exposed materials and dependent assets."
        )

    if severity == "Moderate":
        return (
            "Increase supplier monitoring; validate recovery actions; review "
            "material and asset dependencies; prepare contingency options."
        )

    if severity == "Low":
        return (
            "Continue routine supplier monitoring and reassess risk as new "
            "performance and predictive data become available."
        )

    return (
        "Obtain refreshed predictive intelligence before assigning an active "
        "supplier-failure response."
    )


supplier_early_warning["Recommended_Response"] = (
    supplier_early_warning.apply(
        generate_response,
        axis=1
    )
)


# =============================================================================
# 14. MANAGEMENT ESCALATION
# =============================================================================

def determine_escalation(row):

    severity = row["Alert_Severity"]

    if severity == "Critical":
        return "Executive / Supply Chain Leadership"

    if severity == "High":
        return "Supply Chain Risk Management"

    if severity == "Moderate":
        return "Procurement / Supplier Management"

    if severity == "Low":
        return "Supplier Management"

    return "No Escalation"


supplier_early_warning["Alert_Management_Escalation"] = (
    supplier_early_warning.apply(
        determine_escalation,
        axis=1
    )
)


# =============================================================================
# 15. ALERT TIMEFRAME
# =============================================================================

def determine_alert_timeframe(row):

    severity = row["Alert_Severity"]

    if severity == "Critical":
        return "0–7 days"

    if severity == "High":
        return "Within 14 days"

    if severity == "Moderate":
        return "Within 30 days"

    if severity == "Low":
        return "Routine monitoring"

    return "Refresh predictive intelligence"


supplier_early_warning["Alert_Timeframe"] = (
    supplier_early_warning.apply(
        determine_alert_timeframe,
        axis=1
    )
)


# =============================================================================
# 16. ALERT RANK
# =============================================================================

severity_order = {
    "Critical": 1,
    "High": 2,
    "Moderate": 3,
    "Low": 4,
    "No Current Warning": 5
}

supplier_early_warning["_severity_order"] = (
    supplier_early_warning["Alert_Severity"]
    .map(severity_order)
    .fillna(99)
)

supplier_early_warning = (
    supplier_early_warning
    .sort_values(
        by=[
            "_severity_order",
            "Early_Warning_Severity_Score",
            "Supplier_Failure_Probability",
            "Supply_Chain_Exposure_Score"
        ],
        ascending=[
            True,
            False,
            False,
            False
        ]
    )
    .reset_index(drop=True)
)

supplier_early_warning["Alert_Rank"] = pd.Series(
    pd.NA,
    index=supplier_early_warning.index,
    dtype="Int64"
)

active_alert_mask = (
    supplier_early_warning["Alert_Severity"]
    != "No Current Warning"
)

supplier_early_warning.loc[
    active_alert_mask,
    "Alert_Rank"
] = range(
    1,
    int(active_alert_mask.sum()) + 1
)


# =============================================================================
# 17. ALERT ID
# =============================================================================

supplier_early_warning["Early_Warning_ID"] = (
    "KST-EW-"
    + supplier_early_warning["Supplier_ID"].astype(str)
    + "-"
    + REFERENCE_DATE.strftime("%Y%m%d")
)


# =============================================================================
# 18. ALERT GENERATION DATE
# =============================================================================

supplier_early_warning["Alert_Generation_Date"] = REFERENCE_DATE


# =============================================================================
# 19. REMOVE INTERNAL SORTING COLUMN
# =============================================================================

supplier_early_warning = supplier_early_warning.drop(
    columns=["_severity_order"]
)


# =============================================================================
# 20. COLUMN ORDER
# =============================================================================

preferred_columns = [
    "Early_Warning_ID",
    "Alert_Generation_Date",
    "Alert_Rank",
    "Supplier_ID",
    "Supplier_Name",
    "Supplier_Failure_Probability",
    "Failure_Risk_Score",
    "Risk_Priority_Level",
    "Supplier_Risk_Priority_Score",
    "Supply_Chain_Exposure_Score",
    "Intervention_Urgency_Score",
    "Current_Warning_Status",
    "Alert_Severity",
    "Alert_Type",
    "Alert_Status",
    "Alert_Trigger",
    "Early_Warning_Severity_Score",
    "Early_Warning_Message",
    "Recommended_Response",
    "Intervention_Type",
    "Recommended_Action",
    "Mitigation_Strategy",
    "Alert_Timeframe",
    "Alert_Management_Escalation",
    "Intervention_Priority",
    "Intervention_Timeframe",
    "Management_Escalation"
]

existing_preferred = [
    col for col in preferred_columns
    if col in supplier_early_warning.columns
]

remaining_columns = [
    col for col in supplier_early_warning.columns
    if col not in existing_preferred
]

supplier_early_warning = supplier_early_warning[
    existing_preferred + remaining_columns
]


# =============================================================================
# 21. HARD VALIDATION
# =============================================================================

print("\n" + "=" * 90)
print("PHASE 13 — FINAL HARD VALIDATION")
print("=" * 90)

validation_results = []


# Supplier population
population_pass = (
    len(supplier_early_warning)
    == len(supplier_intervention)
)

validation_results.append({
    "Validation": "Supplier population preserved",
    "Status": "PASS" if population_pass else "FAIL"
})

if not population_pass:
    raise ValueError(
        "Supplier population changed during Phase 13."
    )


# Supplier IDs unique
ids_unique = (
    supplier_early_warning["Supplier_ID"].is_unique
)

validation_results.append({
    "Validation": "Supplier IDs unique",
    "Status": "PASS" if ids_unique else "FAIL"
})

if not ids_unique:
    raise ValueError(
        "Supplier IDs are not unique."
    )


# Failure probability
probability_valid = (
    supplier_early_warning[
        "Supplier_Failure_Probability"
    ].dropna().between(0, 1).all()
)

validation_results.append({
    "Validation": "Failure probabilities valid",
    "Status": "PASS" if probability_valid else "FAIL"
})

if not probability_valid:
    raise ValueError(
        "Supplier failure probabilities outside [0, 1]."
    )


# Severity scores
severity_valid = (
    supplier_early_warning[
        "Early_Warning_Severity_Score"
    ].between(0, 100).all()
)

validation_results.append({
    "Validation": "Early-warning severity scores valid",
    "Status": "PASS" if severity_valid else "FAIL"
})

if not severity_valid:
    raise ValueError(
        "Early-warning severity scores outside [0, 100]."
    )


# Alert severity
valid_alert_levels = {
    "Critical",
    "High",
    "Moderate",
    "Low",
    "No Current Warning"
}

alert_levels_valid = (
    set(supplier_early_warning["Alert_Severity"].unique())
    .issubset(valid_alert_levels)
)

validation_results.append({
    "Validation": "Alert severity levels valid",
    "Status": "PASS" if alert_levels_valid else "FAIL"
})

if not alert_levels_valid:
    raise ValueError(
        "Invalid alert severity level detected."
    )


# Alert messages
messages_populated = (
    supplier_early_warning[
        "Early_Warning_Message"
    ].notna().all()
    and
    supplier_early_warning[
        "Early_Warning_Message"
    ].astype(str).str.strip().ne("").all()
)

validation_results.append({
    "Validation": "Early-warning messages populated",
    "Status": "PASS" if messages_populated else "FAIL"
})

if not messages_populated:
    raise ValueError(
        "Missing early-warning messages."
    )


# Response
responses_populated = (
    supplier_early_warning[
        "Recommended_Response"
    ].notna().all()
    and
    supplier_early_warning[
        "Recommended_Response"
    ].astype(str).str.strip().ne("").all()
)

validation_results.append({
    "Validation": "Recommended responses populated",
    "Status": "PASS" if responses_populated else "FAIL"
})

if not responses_populated:
    raise ValueError(
        "Missing recommended responses."
    )


# Escalation
escalation_populated = (
    supplier_early_warning[
        "Alert_Management_Escalation"
    ].notna().all()
)

validation_results.append({
    "Validation": "Management escalation populated",
    "Status": "PASS" if escalation_populated else "FAIL"
})

if not escalation_populated:
    raise ValueError(
        "Missing management escalation."
    )


# One alert record per supplier
one_per_supplier = (
    supplier_early_warning
    .groupby("Supplier_ID")
    .size()
    .eq(1)
    .all()
)

validation_results.append({
    "Validation": "One early-warning record per supplier",
    "Status": "PASS" if one_per_supplier else "FAIL"
})

if not one_per_supplier:
    raise ValueError(
        "Supplier early-warning table does not contain exactly one "
        "record per supplier."
    )


# Alert IDs unique
alert_ids_unique = (
    supplier_early_warning[
        "Early_Warning_ID"
    ].is_unique
)

validation_results.append({
    "Validation": "Early-warning IDs unique",
    "Status": "PASS" if alert_ids_unique else "FAIL"
})

if not alert_ids_unique:
    raise ValueError(
        "Early-warning IDs are not unique."
    )


# =============================================================================
# 22. VALIDATION SUMMARY
# =============================================================================

phase13_validation_summary = pd.DataFrame(
    validation_results
)

print(
    phase13_validation_summary.to_string(index=False)
)


# =============================================================================
# 23. ALERT SUMMARY
# =============================================================================

print("\n" + "=" * 90)
print("PHASE 13 — EARLY-WARNING ALERT SUMMARY")
print("=" * 90)

total_suppliers = len(supplier_early_warning)

critical_alerts = (
    supplier_early_warning["Alert_Severity"]
    .eq("Critical")
    .sum()
)

high_alerts = (
    supplier_early_warning["Alert_Severity"]
    .eq("High")
    .sum()
)

moderate_alerts = (
    supplier_early_warning["Alert_Severity"]
    .eq("Moderate")
    .sum()
)

low_alerts = (
    supplier_early_warning["Alert_Severity"]
    .eq("Low")
    .sum()
)

no_warning = (
    supplier_early_warning["Alert_Severity"]
    .eq("No Current Warning")
    .sum()
)

active_alerts = (
    supplier_early_warning["Alert_Severity"]
    != "No Current Warning"
).sum()

immediate_alerts = (
    supplier_early_warning["Alert_Status"]
    .eq("Active — Immediate Action")
    .sum()
)

management_alerts = (
    supplier_early_warning["Alert_Status"]
    .eq("Active — Management Attention")
    .sum()
)

phase13_alert_summary = pd.DataFrame({
    "Metric": [
        "Total suppliers",
        "Critical alerts",
        "High alerts",
        "Moderate alerts",
        "Low alerts",
        "No current predictive warning",
        "Active alerts",
        "Immediate-action alerts",
        "Management-attention alerts"
    ],
    "Value": [
        total_suppliers,
        critical_alerts,
        high_alerts,
        moderate_alerts,
        low_alerts,
        no_warning,
        active_alerts,
        immediate_alerts,
        management_alerts
    ]
})

print(
    phase13_alert_summary.to_string(index=False)
)


# =============================================================================
# 24. TOP EARLY-WARNING ALERTS
# =============================================================================

print("\n" + "=" * 90)
print("TOP EARLY-WARNING ALERTS")
print("=" * 90)

top_alert_columns = [
    "Alert_Rank",
    "Supplier_ID",
    "Supplier_Name",
    "Supplier_Failure_Probability",
    "Risk_Priority_Level",
    "Supply_Chain_Exposure_Score",
    "Early_Warning_Severity_Score",
    "Alert_Severity",
    "Alert_Type",
    "Alert_Status",
    "Alert_Timeframe"
]

top_alerts = (
    supplier_early_warning[
        supplier_early_warning["Alert_Severity"]
        != "No Current Warning"
    ][top_alert_columns]
    .head(20)
    .copy()
)

display(top_alerts)


# =============================================================================
# 25. CRITICAL ALERTS
# =============================================================================

print("\n" + "=" * 90)
print("CRITICAL SUPPLIER EARLY-WARNING ALERTS")
print("=" * 90)

critical_columns = [
    "Alert_Rank",
    "Supplier_ID",
    "Supplier_Name",
    "Supplier_Failure_Probability",
    "Supplier_Risk_Priority_Score",
    "Supply_Chain_Exposure_Score",
    "Intervention_Urgency_Score",
    "Early_Warning_Severity_Score",
    "Alert_Trigger",
    "Early_Warning_Message",
    "Recommended_Response",
    "Alert_Timeframe",
    "Alert_Management_Escalation"
]

phase13_critical_alerts = (
    supplier_early_warning[
        supplier_early_warning["Alert_Severity"]
        == "Critical"
    ][critical_columns]
    .copy()
)

display(phase13_critical_alerts)


# =============================================================================
# 26. HIGH ALERTS
# =============================================================================

print("\n" + "=" * 90)
print("HIGH SUPPLIER EARLY-WARNING ALERTS")
print("=" * 90)

phase13_high_alerts = (
    supplier_early_warning[
        supplier_early_warning["Alert_Severity"]
        == "High"
    ][critical_columns]
    .copy()
)

display(
    phase13_high_alerts.head(50)
)


# =============================================================================
# 27. SUPPLIERS WITHOUT CURRENT WARNING
# =============================================================================

print("\n" + "=" * 90)
print("SUPPLIERS WITHOUT CURRENT PREDICTIVE WARNING")
print("=" * 90)

no_warning_columns = [
    "Supplier_ID",
    "Supplier_Name",
    "Current_Warning_Status",
    "Alert_Severity",
    "Alert_Status",
    "Early_Warning_Message",
    "Recommended_Response"
]

phase13_no_current_warning = (
    supplier_early_warning[
        supplier_early_warning["Alert_Severity"]
        == "No Current Warning"
    ][no_warning_columns]
    .copy()
)

display(phase13_no_current_warning)


# =============================================================================
# 28. ALERT DISTRIBUTION
# =============================================================================

print("\n" + "=" * 90)
print("ALERT DISTRIBUTION")
print("=" * 90)

alert_distribution = (
    supplier_early_warning[
        "Alert_Severity"
    ]
    .value_counts()
    .rename_axis("Alert_Severity")
    .reset_index(name="Supplier_Count")
)

alert_distribution["Percentage"] = (
    alert_distribution["Supplier_Count"]
    / total_suppliers
    * 100
).round(2)

display(alert_distribution)


# =============================================================================
# 29. ALERT TYPE DISTRIBUTION
# =============================================================================

print("\n" + "=" * 90)
print("ALERT TYPE DISTRIBUTION")
print("=" * 90)

alert_type_distribution = (
    supplier_early_warning[
        "Alert_Type"
    ]
    .value_counts()
    .rename_axis("Alert_Type")
    .reset_index(name="Supplier_Count")
)

alert_type_distribution["Percentage"] = (
    alert_type_distribution["Supplier_Count"]
    / total_suppliers
    * 100
).round(2)

display(alert_type_distribution)


# =============================================================================
# 30. FINAL OBJECT CLEANUP
# =============================================================================

# Keep only the columns required for the final early-warning engine.
final_columns = [
    "Early_Warning_ID",
    "Alert_Generation_Date",
    "Alert_Rank",
    "Supplier_ID",
    "Supplier_Name",
    "Supplier_Failure_Probability",
    "Failure_Risk_Score",
    "Risk_Priority_Level",
    "Supplier_Risk_Priority_Score",
    "Supply_Chain_Exposure_Score",
    "Intervention_Urgency_Score",
    "Current_Warning_Status",
    "Alert_Severity",
    "Alert_Type",
    "Alert_Status",
    "Alert_Trigger",
    "Early_Warning_Severity_Score",
    "Early_Warning_Message",
    "Recommended_Response",
    "Intervention_Type",
    "Recommended_Action",
    "Mitigation_Strategy",
    "Alert_Timeframe",
    "Alert_Management_Escalation",
    "Intervention_Priority",
    "Intervention_Timeframe",
    "Management_Escalation"
]

supplier_early_warning = supplier_early_warning[
    [
        col
        for col in final_columns
        if col in supplier_early_warning.columns
    ]
].copy()


# =============================================================================
# 31. FINAL HARD CHECK
# =============================================================================

assert len(supplier_early_warning) == total_suppliers

assert supplier_early_warning[
    "Supplier_ID"
].is_unique

assert supplier_early_warning[
    "Early_Warning_ID"
].is_unique

assert supplier_early_warning[
    "Early_Warning_Severity_Score"
].between(0, 100).all()

assert supplier_early_warning[
    "Alert_Severity"
].notna().all()

assert supplier_early_warning[
    "Alert_Status"
].notna().all()


# =============================================================================
# 32. FINAL SUMMARY
# =============================================================================

print("\n" + "=" * 90)
print("PHASE 13 — FINAL SUMMARY")
print("=" * 90)

print(
    f"Total supplier population          : "
    f"{len(supplier_early_warning):,}"
)

print(
    f"Critical early warnings            : "
    f"{critical_alerts:,}"
)

print(
    f"High early warnings                : "
    f"{high_alerts:,}"
)

print(
    f"Moderate early warnings            : "
    f"{moderate_alerts:,}"
)

print(
    f"Low early warnings                 : "
    f"{low_alerts:,}"
)

print(
    f"No current predictive warning      : "
    f"{no_warning:,}"
)

print(
    f"Active alerts                      : "
    f"{active_alerts:,}"
)

print(
    f"Immediate-action alerts            : "
    f"{immediate_alerts:,}"
)

print(
    f"Management-attention alerts        : "
    f"{management_alerts:,}"
)

print(
    f"Final early-warning records        : "
    f"{len(supplier_early_warning):,}"
)

print(
    f"Final columns                      : "
    f"{len(supplier_early_warning.columns):,}"
)


# =============================================================================
# 33. FINAL ARCHITECTURE
# =============================================================================

print("\n" + "=" * 90)
print("FINAL EARLY-WARNING ARCHITECTURE")
print("=" * 90)

print("""
Supplier
   ↓
Predictive Failure Probability
   ↓
Current Supplier Risk
   ↓
Supply-Chain Exposure
   ↓
Intervention Urgency
   ↓
Early-Warning Severity Score
   ↓
Alert Severity
   ↓
Alert Type
   ↓
Alert Trigger
   ↓
Early-Warning Message
   ↓
Recommended Response
   ↓
Management Escalation
   ↓
Alert Timeframe
   ↓
SUPPLIER EARLY-WARNING ENGINE
""")


# =============================================================================
# 34. FINAL OBJECTS
# =============================================================================

print("FINAL OBJECTS:")
print("""
    supplier_early_warning
    phase13_alert_summary
    phase13_critical_alerts
    phase13_high_alerts
    phase13_no_current_warning
    alert_distribution
    alert_type_distribution
    phase13_validation_summary
""")


print("\n" + "=" * 90)
print("✓ PHASE 13 COMPLETED SUCCESSFULLY")
print("=" * 90)

print("\nNEXT:")
print("PHASE 14 — EARLY-WARNING EXPLAINABILITY & ROOT-CAUSE ENGINE")

==========================================================================================
KEYSTRA — PHASE 13
SUPPLIER EARLY-WARNING / ALERT GENERATION ENGINE
==========================================================================================

==========================================================================================
PHASE 13 — INPUT VALIDATION
==========================================================================================
✓ supplier_intervention found
✓ Input rows    : 90
✓ Input columns : 25
✓ All required Phase 12 columns available

==========================================================================================
CURRENT PREDICTIVE WARNING COVERAGE
==========================================================================================
Current warning available : 88
No current warning        : 2
Total suppliers           : 90

==========================================================================================
PHASE 13 — FINAL HARD VALIDATION
==========================================================================================
                           Validation Status
        Supplier population preserved   PASS
                  Supplier IDs unique   PASS
          Failure probabilities valid   PASS
  Early-warning severity scores valid   PASS
          Alert severity levels valid   PASS
     Early-warning messages populated   PASS
      Recommended responses populated   PASS
      Management escalation populated   PASS
One early-warning record per supplier   PASS
             Early-warning IDs unique   PASS

==========================================================================================
PHASE 13 — EARLY-WARNING ALERT SUMMARY
==========================================================================================
                       Metric  Value
              Total suppliers     90
              Critical alerts     10
                  High alerts     26
              Moderate alerts     35
                   Low alerts     17
No current predictive warning      2
                Active alerts     88
      Immediate-action alerts     10
  Management-attention alerts     26

==========================================================================================
TOP EARLY-WARNING ALERTS
==========================================================================================

,Alert_Rank,Supplier_ID,Supplier_Name,Supplier_Failure_Probability,Risk_Priority_Level,Supply_Chain_Exposure_Score,Early_Warning_Severity_Score,Alert_Severity,Alert_Type,Alert_Status,Alert_Timeframe
0,1,S081,SunCore Energy Technologies Ltd.,0.99,Critical,100.00,95.34,Critical,Predictive Supplier Failure + Exposure Alert,Active — Immediate Action,0–7 days
1,2,S055,Process Materials Solutions Ltd.,0.99,Critical,93.75,92.96,Critical,Predictive Supplier Failure + Exposure Alert,Active — Immediate Action,0–7 days
2,3,S004,Sterling Industrial Equipment Ltd.,0.92,Critical,100.00,91.86,Critical,Predictive Supplier Failure + Exposure Alert,Active — Immediate Action,0–7 days
3,4,S025,Brightline Electrical Industries Ltd.,0.99,High,63.50,81.14,Critical,Predictive Supplier Failure Alert,Active — Immediate Action,0–7 days
4,5,S009,Ironbridge Equipment Solutions Ltd.,0.99,High,63.50,80.98,Critical,Predictive Supplier Failure Alert,Active — Immediate Action,0–7 days
5,6,S058,Nexus Industrial Supply Ltd.,0.99,High,63.50,80.92,Critical,Predictive Supplier Failure Alert,Active — Immediate Action,0–7 days
6,7,S087,Continental Industrial Services Ltd.,0.99,High,63.50,80.92,Critical,Predictive Supplier Failure Alert,Active — Immediate Action,0–7 days
7,8,S003,Atlas Turbomachinery Services Ltd.,0.99,High,63.50,80.89,Critical,Predictive Supplier Failure Alert,Active — Immediate Action,0–7 days
8,9,S035,Advanced Process Instruments Ltd.,0.98,High,63.50,80.75,Critical,Predictive Supplier Failure Alert,Active — Immediate Action,0–7 days
9,10,S030,Axis Process Controls Ltd.,0.98,High,63.50,80.35,Critical,Predictive Supplier Failure Alert,Active — Immediate Action,0–7 days
10,11,S019,Powerlink Industrial Systems Ltd.,0.80,High,87.50,80.25,High,Predictive Supplier Failure + Exposure Alert,Active — Management Attention,Within 14 days
11,12,S001,Apex Rotating Systems Ltd.,0.93,High,63.50,78.01,High,Predictive Supplier Failure Alert,Active — Management Attention,Within 14 days
12,13,S054,Industrial Supply Partners Ltd.,0.92,High,63.50,77.39,High,Predictive Supplier Failure Alert,Active — Management Attention,Within 14 days
13,14,S010,Pinnacle Machinery Services Ltd.,0.99,High,52.00,76.37,High,Predictive Supplier Failure Alert,Active — Management Attention,Within 14 days
14,15,S047,DeltaFlow Technologies Ltd.,0.90,High,63.50,76.23,High,Predictive Supplier Failure Alert,Active — Management Attention,Within 14 days
15,16,S013,Westfield Industrial Engineering Ltd.,0.98,High,52.00,75.87,High,Predictive Supplier Failure Alert,Active — Management Attention,Within 14 days
16,17,S018,Crown Electrical Technologies Ltd.,0.97,High,52.00,75.66,High,Predictive Supplier Failure Alert,Active — Management Attention,Within 14 days
17,18,S079,SolarEdge Industrial Energy Ltd.,0.94,High,52.00,73.78,High,Predictive Supplier Failure Alert,Active — Management Attention,Within 14 days
18,19,S062,Reliable Industrial Materials Ltd.,0.93,High,52.00,73.44,High,Predictive Supplier Failure Alert,Active — Management Attention,Within 14 days
19,20,S069,WestAfrica Chemical Solutions Ltd.,0.91,High,52.00,72.53,High,Predictive Supplier Failure Alert,Active — Management Attention,Within 14 days

==========================================================================================
CRITICAL SUPPLIER EARLY-WARNING ALERTS
==========================================================================================

,Alert_Rank,Supplier_ID,Supplier_Name,Supplier_Failure_Probability,Supplier_Risk_Priority_Score,Supply_Chain_Exposure_Score,Intervention_Urgency_Score,Early_Warning_Severity_Score,Alert_Trigger,Early_Warning_Message,Recommended_Response,Alert_Timeframe,Alert_Management_Escalation
0,1,S081,SunCore Energy Technologies Ltd.,0.99,83.04,100.00,99.64,95.34,Very high supplier failure probability + Very ...,CRITICAL EARLY WARNING: SunCore Energy Technol...,Activate supplier recovery plan; protect criti...,0–7 days,Executive / Supply Chain Leadership
1,2,S055,Process Materials Solutions Ltd.,0.99,81.93,93.75,95.40,92.96,Very high supplier failure probability + Very ...,CRITICAL EARLY WARNING: Process Materials Solu...,Activate supplier recovery plan; protect criti...,0–7 days,Executive / Supply Chain Leadership
2,3,S004,Sterling Industrial Equipment Ltd.,0.92,81.30,100.00,96.70,91.86,Very high supplier failure probability + Very ...,CRITICAL EARLY WARNING: Sterling Industrial Eq...,Activate supplier recovery plan; protect criti...,0–7 days,Executive / Supply Chain Leadership
3,4,S025,Brightline Electrical Industries Ltd.,0.99,72.15,63.50,78.78,81.14,Very high supplier failure probability + High ...,CRITICAL EARLY WARNING: Brightline Electrical ...,Activate supplier recovery plan; protect criti...,0–7 days,Executive / Supply Chain Leadership
4,5,S009,Ironbridge Equipment Solutions Ltd.,0.99,71.53,63.50,78.75,80.98,Very high supplier failure probability + High ...,CRITICAL EARLY WARNING: Ironbridge Equipment S...,Activate supplier recovery plan; protect criti...,0–7 days,Executive / Supply Chain Leadership
5,6,S058,Nexus Industrial Supply Ltd.,0.99,71.29,63.50,78.72,80.92,Very high supplier failure probability + High ...,CRITICAL EARLY WARNING: Nexus Industrial Suppl...,Activate supplier recovery plan; protect criti...,0–7 days,Executive / Supply Chain Leadership
6,7,S087,Continental Industrial Services Ltd.,0.99,71.39,63.50,78.62,80.92,Very high supplier failure probability + High ...,CRITICAL EARLY WARNING: Continental Industrial...,Activate supplier recovery plan; protect criti...,0–7 days,Executive / Supply Chain Leadership
7,8,S003,Atlas Turbomachinery Services Ltd.,0.99,71.22,63.50,78.65,80.89,Very high supplier failure probability + High ...,CRITICAL EARLY WARNING: Atlas Turbomachinery S...,Activate supplier recovery plan; protect criti...,0–7 days,Executive / Supply Chain Leadership
8,9,S035,Advanced Process Instruments Ltd.,0.98,72.50,63.50,78.12,80.75,Very high supplier failure probability + High ...,CRITICAL EARLY WARNING: Advanced Process Instr...,Activate supplier recovery plan; protect criti...,0–7 days,Executive / Supply Chain Leadership
9,10,S030,Axis Process Controls Ltd.,0.98,70.82,63.50,78.24,80.35,Very high supplier failure probability + High ...,CRITICAL EARLY WARNING: Axis Process Controls ...,Activate supplier recovery plan; protect criti...,0–7 days,Executive / Supply Chain Leadership

==========================================================================================
HIGH SUPPLIER EARLY-WARNING ALERTS
==========================================================================================

,Alert_Rank,Supplier_ID,Supplier_Name,Supplier_Failure_Probability,Supplier_Risk_Priority_Score,Supply_Chain_Exposure_Score,Intervention_Urgency_Score,Early_Warning_Severity_Score,Alert_Trigger,Early_Warning_Message,Recommended_Response,Alert_Timeframe,Alert_Management_Escalation
10,11,S019,Powerlink Industrial Systems Ltd.,0.80,72.35,87.5,83.30,80.25,High supplier failure probability + High suppl...,HIGH EARLY WARNING: Powerlink Industrial Syste...,Engage supplier; initiate corrective action; a...,Within 14 days,Supply Chain Risk Management
11,12,S001,Apex Rotating Systems Ltd.,0.93,70.04,63.5,76.27,78.01,Very high supplier failure probability + High ...,HIGH EARLY WARNING: Apex Rotating Systems Ltd....,Engage supplier; initiate corrective action; a...,Within 14 days,Supply Chain Risk Management
12,13,S054,Industrial Supply Partners Ltd.,0.92,69.25,63.5,75.88,77.39,Very high supplier failure probability + High ...,HIGH EARLY WARNING: Industrial Supply Partners...,Engage supplier; initiate corrective action; a...,Within 14 days,Supply Chain Risk Management
13,14,S010,Pinnacle Machinery Services Ltd.,0.99,65.18,52.0,75.13,76.37,Very high supplier failure probability + High ...,HIGH EARLY WARNING: Pinnacle Machinery Service...,Engage supplier; initiate corrective action; a...,Within 14 days,Supply Chain Risk Management
14,15,S047,DeltaFlow Technologies Ltd.,0.90,68.24,63.5,74.86,76.23,Very high supplier failure probability + High ...,HIGH EARLY WARNING: DeltaFlow Technologies Ltd...,Engage supplier; initiate corrective action; a...,Within 14 days,Supply Chain Risk Management
15,16,S013,Westfield Industrial Engineering Ltd.,0.98,64.75,52.0,74.90,75.87,Very high supplier failure probability + High ...,HIGH EARLY WARNING: Westfield Industrial Engin...,Engage supplier; initiate corrective action; a...,Within 14 days,Supply Chain Risk Management
16,17,S018,Crown Electrical Technologies Ltd.,0.97,65.87,52.0,74.22,75.66,Very high supplier failure probability + High ...,HIGH EARLY WARNING: Crown Electrical Technolog...,Engage supplier; initiate corrective action; a...,Within 14 days,Supply Chain Risk Management
17,18,S079,SolarEdge Industrial Energy Ltd.,0.94,63.50,52.0,73.05,73.78,Very high supplier failure probability + High ...,HIGH EARLY WARNING: SolarEdge Industrial Energ...,Engage supplier; initiate corrective action; a...,Within 14 days,Supply Chain Risk Management
18,19,S062,Reliable Industrial Materials Ltd.,0.93,63.61,52.0,72.96,73.44,Very high supplier failure probability + High ...,HIGH EARLY WARNING: Reliable Industrial Materi...,Engage supplier; initiate corrective action; a...,Within 14 days,Supply Chain Risk Management
19,20,S069,WestAfrica Chemical Solutions Ltd.,0.91,63.40,52.0,72.15,72.53,Very high supplier failure probability + High ...,HIGH EARLY WARNING: WestAfrica Chemical Soluti...,Engage supplier; initiate corrective action; a...,Within 14 days,Supply Chain Risk Management
20,21,S061,MetroProcess Supplies Ltd.,1.00,59.10,40.5,71.97,72.27,Very high supplier failure probability + High ...,HIGH EARLY WARNING: MetroProcess Supplies Ltd....,Engage supplier; initiate corrective action; a...,Within 14 days,Supply Chain Risk Management
21,22,S089,Nexus Energy Equipment Solutions Ltd.,0.90,61.73,52.0,71.68,71.67,Very high supplier failure probability + High ...,HIGH EARLY WARNING: Nexus Energy Equipment Sol...,Engage supplier; initiate corrective action; a...,Within 14 days,Supply Chain Risk Management
22,23,S038,OptiSense Systems Ltd.,0.98,58.37,40.5,71.25,71.24,Very high supplier failure probability + High ...,HIGH EARLY WARNING: OptiSense Systems Ltd. has...,Engage supplier; initiate corrective action; a...,Within 14 days,Supply Chain Risk Management
23,24,S082,RenewPower Engineering Ltd.,0.89,60.89,52.0,71.04,70.98,High supplier failure probability + High inter...,HIGH EARLY WARNING: RenewPower Engineering Ltd...,Engage supplier; initiate corrective action; a...,Within 14 days,Supply Chain Risk Management
24,25,S015,Grandview Mechanical Systems Ltd.,0.87,60.12,52.0,70.27,69.93,High supplier failure probability + High inter...,HIGH EARLY WARNING: Grandview Mechanical Syste...,Engage supplier; initiate corrective action; a...,Within 14 days,Supply Chain Risk Management
25,26,S040,FlowGuard Industrial Ltd.,0.86,61.34,52.0,70.09,69.85,High supplier failure probability + High inter...,HIGH EARLY WARNING: FlowGuard Industrial Ltd. ...,Engage supplier; initiate corrective action; a...,Within 14 days,Supply Chain Risk Management
26,27,S090,Frontier Industrial Technologies Ltd.,0.86,59.99,52.0,70.14,69.53,High supplier failure probability + High inter...,HIGH EARLY WARNING: Frontier Industrial Techno...,Engage supplier; initiate corrective action; a...,Within 14 days,Supply Chain Risk Management
27,28,S024,Enertech Power Solutions Ltd.,0.94,57.15,40.5,69.82,69.25,Very high supplier failure probability,HIGH EARLY WARNING: Enertech Power Solutions L...,Engage supplier; initiate corrective action; a...,Within 14 days,Supply Chain Risk Management
28,29,S034,NexControl Engineering Ltd.,0.50,62.81,100.0,79.81,69.16,Elevated supplier failure probability + Very h...,HIGH EARLY WARNING: NexControl Engineering Ltd...,Engage supplier; initiate corrective action; a...,Within 14 days,Supply Chain Risk Management
29,30,S057,CoreProcess Materials Ltd.,0.49,62.50,100.0,79.50,68.68,Very high supply-chain exposure + High interve...,HIGH EARLY WARNING: CoreProcess Materials Ltd....,Engage supplier; initiate corrective action; a...,Within 14 days,Supply Chain Risk Management
30,31,S071,ProcessChem Technologies Ltd.,0.84,59.69,52.0,69.04,68.53,High supplier failure probability,HIGH EARLY WARNING: ProcessChem Technologies L...,Engage supplier; initiate corrective action; a...,Within 14 days,Supply Chain Risk Management
31,32,S086,Integrated Energy Supply Solutions Ltd.,0.55,63.12,90.0,74.92,68.01,Elevated supplier failure probability + Very h...,HIGH EARLY WARNING: Integrated Energy Supply S...,Engage supplier; initiate corrective action; a...,Within 14 days,Supply Chain Risk Management
32,33,S076,Sentinel Safety Equipment Ltd.,0.89,56.30,40.5,67.78,66.88,High supplier failure probability,HIGH EARLY WARNING: Sentinel Safety Equipment ...,Engage supplier; initiate corrective action; a...,Within 14 days,Supply Chain Risk Management
33,34,S014,Orion Machinery & Engineering Ltd.,0.79,57.16,52.0,67.31,65.80,Elevated supplier failure probability,HIGH EARLY WARNING: Orion Machinery & Engineer...,Engage supplier; initiate corrective action; a...,Within 14 days,Supply Chain Risk Management
34,35,S064,PetroChem Solutions Ltd.,0.87,55.35,40.5,66.83,65.75,High supplier failure probability,HIGH EARLY WARNING: PetroChem Solutions Ltd. h...,Engage supplier; initiate corrective action; a...,Within 14 days,Supply Chain Risk Management
35,36,S011,BluePeak Mechanical Systems Ltd.,0.79,56.97,52.0,67.12,65.72,Elevated supplier failure probability,HIGH EARLY WARNING: BluePeak Mechanical System...,Engage supplier; initiate corrective action; a...,Within 14 days,Supply Chain Risk Management

==========================================================================================
SUPPLIERS WITHOUT CURRENT PREDICTIVE WARNING
==========================================================================================

,Supplier_ID,Supplier_Name,Current_Warning_Status,Alert_Severity,Alert_Status,Early_Warning_Message,Recommended_Response
88,S045,PrimeFlow Industrial Solutions Ltd.,No Current Warning,No Current Warning,No Active Alert,No current predictive warning available for Pr...,Obtain refreshed predictive intelligence befor...
89,S085,WindSun Energy Systems Ltd.,No Current Warning,No Current Warning,No Active Alert,No current predictive warning available for Wi...,Obtain refreshed predictive intelligence befor...

==========================================================================================
ALERT DISTRIBUTION
==========================================================================================

       Alert_Severity  Supplier_Count  Percentage
0            Moderate              35       38.89
1                High              26       28.89
2                 Low              17       18.89
3            Critical              10       11.11
4  No Current Warning               2        2.22

==========================================================================================
ALERT TYPE DISTRIBUTION
==========================================================================================

                                     Alert_Type  Supplier_Count  Percentage
0                Supplier Risk Monitoring Alert              31       34.44
1             Predictive Supplier Failure Alert              27       30.00
2                  Emerging Supplier Risk Alert              18       20.00
3                   Supply-Chain Exposure Alert               8        8.89
4  Predictive Supplier Failure + Exposure Alert               4        4.44
5                   No Current Predictive Alert               2        2.22

==========================================================================================
PHASE 13 — FINAL SUMMARY
==========================================================================================
Total supplier population          : 90
Critical early warnings            : 10
High early warnings                : 26
Moderate early warnings            : 35
Low early warnings                 : 17
No current predictive warning      : 2
Active alerts                      : 88
Immediate-action alerts            : 10
Management-attention alerts        : 26
Final early-warning records        : 90
Final columns                      : 27

==========================================================================================
FINAL EARLY-WARNING ARCHITECTURE
==========================================================================================

Supplier
   ↓
Predictive Failure Probability
   ↓
Current Supplier Risk
   ↓
Supply-Chain Exposure
   ↓
Intervention Urgency
   ↓
Early-Warning Severity Score
   ↓
Alert Severity
   ↓
Alert Type
   ↓
Alert Trigger
   ↓
Early-Warning Message
   ↓
Recommended Response
   ↓
Management Escalation
   ↓
Alert Timeframe
   ↓
SUPPLIER EARLY-WARNING ENGINE

FINAL OBJECTS:

    supplier_early_warning
    phase13_alert_summary
    phase13_critical_alerts
    phase13_high_alerts
    phase13_no_current_warning
    alert_distribution
    alert_type_distribution
    phase13_validation_summary


==========================================================================================
✓ PHASE 13 COMPLETED SUCCESSFULLY
==========================================================================================

NEXT:
PHASE 14 — EARLY-WARNING EXPLAINABILITY & ROOT-CAUSE ENGINE

In [25]:
# =============================================================================
# KEYSTRA — PHASE 14
# EARLY-WARNING EXPLAINABILITY & ROOT-CAUSE ENGINE
# =============================================================================
#
# PURPOSE
# -------
# Explain WHY a supplier received an early-warning alert.
#
# This phase does NOT:
#   - retrain the predictive model
#   - change supplier failure probabilities
#   - replace Phase 13 alert severity
#   - create another predictive target
#
# It DOES:
#   1. Identify the dominant risk drivers
#   2. Quantify contribution of each risk signal
#   3. Identify the primary root-cause category
#   4. Explain why the alert was generated
#   5. Trace supplier risk to operational exposure
#   6. Identify potential operational consequences
#   7. Produce an explainable risk narrative
#
# UPSTREAM OBJECT
# ---------------
# supplier_early_warning
#
# MAIN OUTPUTS
# ------------
# supplier_alert_explanation
# phase14_root_cause_summary
# phase14_critical_explanations
# phase14_high_risk_explanations
# phase14_validation_summary
#
# ANALYTICAL CHAIN
# ----------------
#
# Predictive Failure Probability
#             ↓
# Supplier Risk Priority
#             ↓
# Supply-Chain Exposure
#             ↓
# Intervention Urgency
#             ↓
# Risk Driver Decomposition
#             ↓
# Root-Cause Classification
#             ↓
# Operational Consequence
#             ↓
# Explainable Risk Narrative
#
# REFERENCE DATE
# ---------------
# 2026-07-31
#
# =============================================================================


import pandas as pd
import numpy as np


REFERENCE_DATE = pd.Timestamp("2026-07-31")


# =============================================================================
# 1. PHASE HEADER
# =============================================================================

print("=" * 90)
print("KEYSTRA — PHASE 14")
print("EARLY-WARNING EXPLAINABILITY & ROOT-CAUSE ENGINE")
print("=" * 90)


# =============================================================================
# 2. INPUT VALIDATION
# =============================================================================

print("\n" + "=" * 90)
print("PHASE 14 — INPUT VALIDATION")
print("=" * 90)


if "supplier_early_warning" not in globals():
    raise NameError(
        "supplier_early_warning was not found. "
        "Run Phase 13 successfully before running Phase 14."
    )


if not isinstance(
    supplier_early_warning,
    pd.DataFrame
):
    raise TypeError(
        "supplier_early_warning must be a pandas DataFrame."
    )


print("✓ supplier_early_warning found")
print(
    f"✓ Input rows    : "
    f"{len(supplier_early_warning):,}"
)
print(
    f"✓ Input columns : "
    f"{len(supplier_early_warning.columns):,}"
)


# =============================================================================
# 3. REQUIRED COLUMNS
# =============================================================================

required_columns = [
    "Early_Warning_ID",
    "Alert_Generation_Date",
    "Alert_Rank",
    "Supplier_ID",
    "Supplier_Name",

    "Supplier_Failure_Probability",
    "Failure_Risk_Score",

    "Risk_Priority_Level",
    "Supplier_Risk_Priority_Score",

    "Supply_Chain_Exposure_Score",
    "Intervention_Urgency_Score",

    "Alert_Severity",
    "Alert_Type",
    "Alert_Status",

    "Alert_Trigger",
    "Early_Warning_Severity_Score",

    "Early_Warning_Message",
    "Recommended_Response",

    "Intervention_Type",
    "Recommended_Action",
    "Mitigation_Strategy",

    "Alert_Timeframe",
    "Alert_Management_Escalation",

    "Intervention_Priority",
]


missing_columns = [
    col
    for col in required_columns
    if col not in supplier_early_warning.columns
]


if missing_columns:
    raise ValueError(
        "Phase 13 output is missing required columns:\n"
        + "\n".join(
            f" - {col}"
            for col in missing_columns
        )
    )


print("✓ All required Phase 13 columns available")


# =============================================================================
# 4. CREATE ISOLATED WORKING COPY
# =============================================================================

supplier_alert_explanation = (
    supplier_early_warning
    .copy()
    .reset_index(drop=True)
)


# =============================================================================
# 5. NUMERIC STANDARDISATION
# =============================================================================

numeric_columns = [
    "Supplier_Failure_Probability",
    "Failure_Risk_Score",
    "Supplier_Risk_Priority_Score",
    "Supply_Chain_Exposure_Score",
    "Intervention_Urgency_Score",
    "Early_Warning_Severity_Score",
]


for col in numeric_columns:

    supplier_alert_explanation[col] = (
        pd.to_numeric(
            supplier_alert_explanation[col],
            errors="coerce"
        )
    )


# =============================================================================
# 6. DRIVER COMPONENTS
# =============================================================================
#
# These are explanatory components.
#
# They describe the existing risk state.
# They do NOT modify the Phase 13 severity score.
#
# Four primary drivers:
#
#   1. Predictive failure risk
#   2. Supplier risk priority
#   3. Supply-chain exposure
#   4. Intervention urgency
#
# =============================================================================


supplier_alert_explanation[
    "Driver_Failure_Risk"
] = (
    supplier_alert_explanation[
        "Supplier_Failure_Probability"
    ]
    .fillna(0)
    .clip(0, 1)
    * 100
)


supplier_alert_explanation[
    "Driver_Supplier_Risk"
] = (
    supplier_alert_explanation[
        "Supplier_Risk_Priority_Score"
    ]
    .fillna(0)
    .clip(0, 100)
)


supplier_alert_explanation[
    "Driver_Exposure_Risk"
] = (
    supplier_alert_explanation[
        "Supply_Chain_Exposure_Score"
    ]
    .fillna(0)
    .clip(0, 100)
)


supplier_alert_explanation[
    "Driver_Intervention_Urgency"
] = (
    supplier_alert_explanation[
        "Intervention_Urgency_Score"
    ]
    .fillna(0)
    .clip(0, 100)
)


# =============================================================================
# 7. DRIVER CONTRIBUTION TO EARLY-WARNING SEVERITY
# =============================================================================
#
# IMPORTANT:
#
# These weights mirror Phase 13.
#
# Failure Risk       = 35%
# Supplier Risk      = 25%
# Exposure            = 20%
# Intervention Urgency = 20%
#
# This allows Phase 14 to explain the Phase 13 score rather than
# inventing a second scoring framework.
#
# =============================================================================


supplier_alert_explanation[
    "Failure_Risk_Contribution"
] = (
    supplier_alert_explanation[
        "Driver_Failure_Risk"
    ] * 0.35
)


supplier_alert_explanation[
    "Supplier_Risk_Contribution"
] = (
    supplier_alert_explanation[
        "Driver_Supplier_Risk"
    ] * 0.25
)


supplier_alert_explanation[
    "Exposure_Risk_Contribution"
] = (
    supplier_alert_explanation[
        "Driver_Exposure_Risk"
    ] * 0.20
)


supplier_alert_explanation[
    "Intervention_Urgency_Contribution"
] = (
    supplier_alert_explanation[
        "Driver_Intervention_Urgency"
    ] * 0.20
)


# =============================================================================
# 8. EXPLAINABILITY RECONCILIATION
# =============================================================================
#
# Reconstructed score should closely match Phase 13's
# Early_Warning_Severity_Score.
#
# This is an important integrity check.
#
# =============================================================================


supplier_alert_explanation[
    "Reconstructed_Severity_Score"
] = (
    supplier_alert_explanation[
        "Failure_Risk_Contribution"
    ]
    +
    supplier_alert_explanation[
        "Supplier_Risk_Contribution"
    ]
    +
    supplier_alert_explanation[
        "Exposure_Risk_Contribution"
    ]
    +
    supplier_alert_explanation[
        "Intervention_Urgency_Contribution"
    ]
).round(2)


supplier_alert_explanation[
    "Severity_Reconciliation_Difference"
] = (
    supplier_alert_explanation[
        "Reconstructed_Severity_Score"
    ]
    -
    supplier_alert_explanation[
        "Early_Warning_Severity_Score"
    ]
).abs().round(4)


# =============================================================================
# 9. DOMINANT DRIVER
# =============================================================================

driver_columns = {
    "Failure probability": "Failure_Risk_Contribution",
    "Supplier risk priority": "Supplier_Risk_Contribution",
    "Supply-chain exposure": "Exposure_Risk_Contribution",
    "Intervention urgency": "Intervention_Urgency_Contribution",
}


driver_matrix = supplier_alert_explanation[
    list(driver_columns.values())
]


supplier_alert_explanation[
    "Primary_Risk_Driver"
] = (
    driver_matrix
    .idxmax(axis=1)
    .map(
        {
            value: key
            for key, value in driver_columns.items()
        }
    )
)


# =============================================================================
# 10. SECONDARY DRIVER
# =============================================================================

supplier_alert_explanation[
    "_Second_Driver_Value"
] = (
    driver_matrix
    .apply(
        lambda row: row.nlargest(2).iloc[-1],
        axis=1
    )
)


supplier_alert_explanation[
    "_Second_Driver_Column"
] = (
    driver_matrix
    .apply(
        lambda row: row.nlargest(2).index[-1],
        axis=1
    )
)


supplier_alert_explanation[
    "Secondary_Risk_Driver"
] = (
    supplier_alert_explanation[
        "_Second_Driver_Column"
    ]
    .map(
        {
            value: key
            for key, value in driver_columns.items()
        }
    )
)


# =============================================================================
# 11. DRIVER STRENGTH
# =============================================================================

def classify_driver_strength(value):

    if pd.isna(value):
        return "Unknown"

    if value >= 25:
        return "Very High"

    if value >= 18:
        return "High"

    if value >= 10:
        return "Moderate"

    return "Low"


supplier_alert_explanation[
    "Primary_Driver_Strength"
] = (
    supplier_alert_explanation[
        [
            "Failure_Risk_Contribution",
            "Supplier_Risk_Contribution",
            "Exposure_Risk_Contribution",
            "Intervention_Urgency_Contribution",
        ]
    ]
    .max(axis=1)
    .apply(classify_driver_strength)
)


# =============================================================================
# 12. PREDICTIVE RISK INTERPRETATION
# =============================================================================

def interpret_failure_probability(probability):

    if pd.isna(probability):
        return "No predictive failure probability currently available"

    if probability >= 0.90:
        return "Very high predicted supplier-failure risk"

    if probability >= 0.80:
        return "High predicted supplier-failure risk"

    if probability >= 0.60:
        return "Elevated predicted supplier-failure risk"

    if probability >= 0.40:
        return "Moderate predicted supplier-failure risk"

    return "Low predicted supplier-failure risk"


supplier_alert_explanation[
    "Predictive_Risk_Interpretation"
] = (
    supplier_alert_explanation[
        "Supplier_Failure_Probability"
    ]
    .apply(interpret_failure_probability)
)


# =============================================================================
# 13. SUPPLIER RISK INTERPRETATION
# =============================================================================

def interpret_supplier_risk(score):

    if pd.isna(score):
        return "Supplier risk priority unavailable"

    if score >= 80:
        return "Very high supplier risk priority"

    if score >= 60:
        return "High supplier risk priority"

    if score >= 40:
        return "Moderate supplier risk priority"

    return "Low supplier risk priority"


supplier_alert_explanation[
    "Supplier_Risk_Interpretation"
] = (
    supplier_alert_explanation[
        "Supplier_Risk_Priority_Score"
    ]
    .apply(interpret_supplier_risk)
)


# =============================================================================
# 14. EXPOSURE INTERPRETATION
# =============================================================================

def interpret_exposure(score):

    if pd.isna(score):
        return "Supply-chain exposure unavailable"

    if score >= 90:
        return "Very high supply-chain exposure"

    if score >= 75:
        return "High supply-chain exposure"

    if score >= 60:
        return "Moderate supply-chain exposure"

    if score >= 40:
        return "Elevated supply-chain exposure"

    return "Low supply-chain exposure"


supplier_alert_explanation[
    "Exposure_Interpretation"
] = (
    supplier_alert_explanation[
        "Supply_Chain_Exposure_Score"
    ]
    .apply(interpret_exposure)
)


# =============================================================================
# 15. URGENCY INTERPRETATION
# =============================================================================

def interpret_urgency(score):

    if pd.isna(score):
        return "Intervention urgency unavailable"

    if score >= 80:
        return "Very high intervention urgency"

    if score >= 70:
        return "High intervention urgency"

    if score >= 60:
        return "Moderate intervention urgency"

    if score >= 40:
        return "Elevated intervention urgency"

    return "Low intervention urgency"


supplier_alert_explanation[
    "Urgency_Interpretation"
] = (
    supplier_alert_explanation[
        "Intervention_Urgency_Score"
    ]
    .apply(interpret_urgency)
)


# =============================================================================
# 16. ROOT-CAUSE CATEGORY
# =============================================================================
#
# Root cause here means the dominant ANALYTICAL RISK DRIVER.
#
# It does not claim a physical supplier cause that the data does not contain.
#
# =============================================================================


def determine_root_cause(row):

    severity = row["Alert_Severity"]

    if severity == "No Current Warning":
        return "Insufficient Predictive Intelligence"

    probability = (
        row["Supplier_Failure_Probability"]
        if pd.notna(
            row["Supplier_Failure_Probability"]
        )
        else 0
    )

    exposure = (
        row["Supply_Chain_Exposure_Score"]
        if pd.notna(
            row["Supply_Chain_Exposure_Score"]
        )
        else 0
    )

    risk_score = (
        row["Supplier_Risk_Priority_Score"]
        if pd.notna(
            row["Supplier_Risk_Priority_Score"]
        )
        else 0
    )

    urgency = (
        row["Intervention_Urgency_Score"]
        if pd.notna(
            row["Intervention_Urgency_Score"]
        )
        else 0
    )

    if probability >= 0.80 and exposure >= 75:
        return "Predicted Supplier Failure with Material Supply-Chain Exposure"

    if probability >= 0.80:
        return "Elevated Predicted Supplier Failure Risk"

    if exposure >= 85:
        return "High Supply-Chain Exposure"

    if urgency >= 70:
        return "High Intervention Urgency"

    if risk_score >= 70:
        return "High Supplier Risk Priority"

    if probability >= 0.50:
        return "Emerging Supplier Failure Risk"

    if exposure >= 60:
        return "Emerging Supply-Chain Exposure"

    return "Emerging Supplier Risk"


supplier_alert_explanation[
    "Root_Cause_Category"
] = (
    supplier_alert_explanation.apply(
        determine_root_cause,
        axis=1
    )
)


# =============================================================================
# 17. ROOT-CAUSE NARRATIVE
# =============================================================================

def generate_root_cause_narrative(row):

    supplier = row["Supplier_Name"]

    probability = row["Supplier_Failure_Probability"]
    exposure = row["Supply_Chain_Exposure_Score"]
    urgency = row["Intervention_Urgency_Score"]
    risk_score = row["Supplier_Risk_Priority_Score"]

    severity = row["Alert_Severity"]

    if severity == "No Current Warning":
        return (
            f"{supplier} does not currently have a predictive failure "
            f"probability available. The system therefore cannot establish "
            f"a current predictive root cause for an active supplier-failure alert."
        )

    probability_text = (
        f"{probability * 100:.1f}%"
        if pd.notna(probability)
        else "unavailable"
    )

    exposure_text = (
        f"{exposure:.1f}"
        if pd.notna(exposure)
        else "unavailable"
    )

    risk_text = (
        f"{risk_score:.1f}"
        if pd.notna(risk_score)
        else "unavailable"
    )

    urgency_text = (
        f"{urgency:.1f}"
        if pd.notna(urgency)
        else "unavailable"
    )

    return (
        f"{supplier} generated a {severity} early-warning alert primarily "
        f"because of {row['Primary_Risk_Driver'].lower()}. "
        f"The supplier has a predicted failure probability of "
        f"{probability_text}, supplier risk priority score of {risk_text}, "
        f"supply-chain exposure score of {exposure_text}, and intervention "
        f"urgency score of {urgency_text}. "
        f"The dominant analytical root-cause category is "
        f"'{row['Root_Cause_Category']}'."
    )


supplier_alert_explanation[
    "Root_Cause_Narrative"
] = (
    supplier_alert_explanation.apply(
        generate_root_cause_narrative,
        axis=1
    )
)


# =============================================================================
# 18. OPERATIONAL CONSEQUENCE
# =============================================================================

def determine_operational_consequence(row):

    severity = row["Alert_Severity"]
    exposure = (
        row["Supply_Chain_Exposure_Score"]
        if pd.notna(
            row["Supply_Chain_Exposure_Score"]
        )
        else 0
    )

    probability = (
        row["Supplier_Failure_Probability"]
        if pd.notna(
            row["Supplier_Failure_Probability"]
        )
        else 0
    )

    if severity == "No Current Warning":
        return (
            "Operational consequence cannot currently be assessed "
            "from predictive supplier-failure intelligence."
        )

    if severity == "Critical":
        return (
            "Potential material supply disruption with consequential "
            "operational continuity, production availability, inventory, "
            "and cost exposure."
        )

    if severity == "High":
        return (
            "Potential disruption to material availability and dependent "
            "operations if supplier deterioration continues."
        )

    if severity == "Moderate":
        return (
            "Potential future supply variability requiring monitoring "
            "and contingency preparation."
        )

    if exposure >= 50 or probability >= 0.40:
        return (
            "Limited immediate disruption indicated, but continued supplier "
            "deterioration could increase future supply exposure."
        )

    return (
        "Limited immediate operational consequence identified; "
        "maintain routine monitoring."
    )


supplier_alert_explanation[
    "Potential_Operational_Consequence"
] = (
    supplier_alert_explanation.apply(
        determine_operational_consequence,
        axis=1
    )
)


# =============================================================================
# 19. BUSINESS IMPACT INTERPRETATION
# =============================================================================

def determine_business_impact(row):

    severity = row["Alert_Severity"]

    if severity == "Critical":
        return (
            "Potential production disruption, emergency procurement, "
            "inventory depletion, operational downtime, and increased "
            "supply-chain recovery cost."
        )

    if severity == "High":
        return (
            "Potential procurement disruption, material availability pressure, "
            "expedited sourcing cost, and operational delays."
        )

    if severity == "Moderate":
        return (
            "Potential future procurement variability and increased "
            "contingency planning requirements."
        )

    if severity == "Low":
        return (
            "Limited current business impact; continue monitoring."
        )

    return (
        "No current predictive business-impact assessment available."
    )


supplier_alert_explanation[
    "Potential_Business_Impact"
] = (
    supplier_alert_explanation.apply(
        determine_business_impact,
        axis=1
    )
)


# =============================================================================
# 20. EXPLAINABILITY STATEMENT
# =============================================================================

def generate_explainability_statement(row):

    severity = row["Alert_Severity"]

    if severity == "No Current Warning":
        return (
            "No active predictive warning is available. "
            "The system recommends refreshed predictive intelligence."
        )

    return (
        f"The {severity} alert is primarily explained by "
        f"{row['Primary_Risk_Driver'].lower()}, "
        f"with {row['Secondary_Risk_Driver'].lower()} as the secondary "
        f"contributing driver."
    )


supplier_alert_explanation[
    "Explainability_Statement"
] = (
    supplier_alert_explanation.apply(
        generate_explainability_statement,
        axis=1
    )
)


# =============================================================================
# 21. FULL RISK EXPLANATION
# =============================================================================

def generate_full_explanation(row):

    severity = row["Alert_Severity"]

    if severity == "No Current Warning":
        return (
            f"{row['Supplier_Name']} currently has no active predictive "
            f"supplier-failure warning. Predictive intelligence should be "
            f"refreshed before assigning an active intervention."
        )

    return (
        f"{row['Supplier_Name']} received a {severity} early-warning alert. "
        f"The dominant risk driver is "
        f"{row['Primary_Risk_Driver'].lower()}, followed by "
        f"{row['Secondary_Risk_Driver'].lower()}. "
        f"The analytical root cause is classified as "
        f"{row['Root_Cause_Category']}. "
        f"The resulting risk may create "
        f"{row['Potential_Operational_Consequence'].lower()} "
        f"Potential business impact includes "
        f"{row['Potential_Business_Impact'].lower()} "
        f"The system therefore recommends: "
        f"{row['Recommended_Response']}"
    )


supplier_alert_explanation[
    "Full_Risk_Explanation"
] = (
    supplier_alert_explanation.apply(
        generate_full_explanation,
        axis=1
    )
)


# =============================================================================
# 22. EXPLAINABILITY CONFIDENCE
# =============================================================================
#
# This is NOT model confidence.
#
# It measures whether the system has sufficient analytical information
# available to produce an explanation.
#
# =============================================================================

def determine_explainability_quality(row):

    required_values = [
        row["Supplier_Failure_Probability"],
        row["Supplier_Risk_Priority_Score"],
        row["Supply_Chain_Exposure_Score"],
        row["Intervention_Urgency_Score"],
    ]

    available_count = sum(
        pd.notna(value)
        for value in required_values
    )

    if row["Alert_Severity"] == "No Current Warning":
        return "Limited — Predictive Signal Unavailable"

    if available_count == 4:
        return "High"

    if available_count >= 2:
        return "Moderate"

    return "Limited"


supplier_alert_explanation[
    "Explainability_Quality"
] = (
    supplier_alert_explanation.apply(
        determine_explainability_quality,
        axis=1
    )
)


# =============================================================================
# 23. RISK DRIVER COUNT
# =============================================================================

supplier_alert_explanation[
    "Material_Risk_Driver_Count"
] = (
    (
        supplier_alert_explanation[
            [
                "Driver_Failure_Risk",
                "Driver_Supplier_Risk",
                "Driver_Exposure_Risk",
                "Driver_Intervention_Urgency",
            ]
        ] >= 60
    )
    .sum(axis=1)
)


# =============================================================================
# 24. ROOT-CAUSE PRIORITY
# =============================================================================

root_cause_priority = {
    "Predicted Supplier Failure with Material Supply-Chain Exposure": 1,
    "Elevated Predicted Supplier Failure Risk": 2,
    "High Supply-Chain Exposure": 3,
    "High Intervention Urgency": 4,
    "High Supplier Risk Priority": 5,
    "Emerging Supplier Failure Risk": 6,
    "Emerging Supply-Chain Exposure": 7,
    "Emerging Supplier Risk": 8,
    "Insufficient Predictive Intelligence": 9,
}


supplier_alert_explanation[
    "Root_Cause_Priority"
] = (
    supplier_alert_explanation[
        "Root_Cause_Category"
    ]
    .map(root_cause_priority)
    .fillna(99)
)


# =============================================================================
# 25. EXPLANATION RANK
# =============================================================================

supplier_alert_explanation = (
    supplier_alert_explanation
    .sort_values(
        by=[
            "Root_Cause_Priority",
            "Early_Warning_Severity_Score",
            "Supplier_Failure_Probability",
            "Supply_Chain_Exposure_Score",
        ],
        ascending=[
            True,
            False,
            False,
            False,
        ]
    )
    .reset_index(drop=True)
)


supplier_alert_explanation[
    "Explanation_Rank"
] = pd.Series(
    pd.NA,
    index=supplier_alert_explanation.index,
    dtype="Int64"
)


active_mask = (
    supplier_alert_explanation[
        "Alert_Severity"
    ]
    != "No Current Warning"
)


supplier_alert_explanation.loc[
    active_mask,
    "Explanation_Rank"
] = range(
    1,
    int(active_mask.sum()) + 1
)


# =============================================================================
# 26. HARD EXPLAINABILITY VALIDATION
# =============================================================================

print("\n" + "=" * 90)
print("PHASE 14 — EXPLAINABILITY VALIDATION")
print("=" * 90)


# -------------------------------------------------------------------------
# Population preserved
# -------------------------------------------------------------------------

assert (
    len(supplier_alert_explanation)
    == len(supplier_early_warning)
), "Supplier population changed."


print("✓ Supplier population preserved")


# -------------------------------------------------------------------------
# Supplier IDs unique
# -------------------------------------------------------------------------

assert (
    supplier_alert_explanation[
        "Supplier_ID"
    ].is_unique
), "Supplier IDs are not unique."


print("✓ Supplier IDs unique")


# -------------------------------------------------------------------------
# Reconstructed severity reconciliation
# -------------------------------------------------------------------------

reconciliation_valid = (
    supplier_alert_explanation[
        "Severity_Reconciliation_Difference"
    ] <= 0.02
).all()


assert reconciliation_valid, (
    "Explainability severity reconstruction does not reconcile "
    "with Phase 13 severity score."
)


print("✓ Severity score reconciles with Phase 13")


# -------------------------------------------------------------------------
# Driver contributions valid
# -------------------------------------------------------------------------

contribution_columns = [
    "Failure_Risk_Contribution",
    "Supplier_Risk_Contribution",
    "Exposure_Risk_Contribution",
    "Intervention_Urgency_Contribution",
]


for col in contribution_columns:

    assert (
        supplier_alert_explanation[col]
        .between(0, 100)
        .all()
    ), f"Invalid values in {col}"


print("✓ Driver contributions valid")


# -------------------------------------------------------------------------
# Primary driver populated
# -------------------------------------------------------------------------

assert (
    supplier_alert_explanation[
        "Primary_Risk_Driver"
    ]
    .notna()
    .all()
)


print("✓ Primary risk drivers populated")


# -------------------------------------------------------------------------
# Root cause populated
# -------------------------------------------------------------------------

assert (
    supplier_alert_explanation[
        "Root_Cause_Category"
    ]
    .notna()
    .all()
)


print("✓ Root-cause categories populated")


# -------------------------------------------------------------------------
# Explanation populated
# -------------------------------------------------------------------------

assert (
    supplier_alert_explanation[
        "Full_Risk_Explanation"
    ]
    .notna()
    .all()
)


assert (
    supplier_alert_explanation[
        "Full_Risk_Explanation"
    ]
    .astype(str)
    .str.strip()
    .ne("")
    .all()
)


print("✓ Full risk explanations populated")


# -------------------------------------------------------------------------
# Operational consequence populated
# -------------------------------------------------------------------------

assert (
    supplier_alert_explanation[
        "Potential_Operational_Consequence"
    ]
    .notna()
    .all()
)


print("✓ Operational consequences populated")


# -------------------------------------------------------------------------
# Explainability quality valid
# -------------------------------------------------------------------------

valid_quality_levels = {
    "High",
    "Moderate",
    "Limited",
    "Limited — Predictive Signal Unavailable",
}


assert (
    set(
        supplier_alert_explanation[
            "Explainability_Quality"
        ].unique()
    )
    .issubset(valid_quality_levels)
)


print("✓ Explainability quality levels valid")


# =============================================================================
# 27. ROOT-CAUSE SUMMARY
# =============================================================================

root_cause_distribution = (
    supplier_alert_explanation[
        "Root_Cause_Category"
    ]
    .value_counts()
    .rename_axis("Root_Cause_Category")
    .reset_index(
        name="Supplier_Count"
    )
)


root_cause_distribution[
    "Percentage"
] = (
    root_cause_distribution[
        "Supplier_Count"
    ]
    /
    len(supplier_alert_explanation)
    * 100
).round(2)


# =============================================================================
# 28. PRIMARY DRIVER SUMMARY
# =============================================================================

primary_driver_distribution = (
    supplier_alert_explanation[
        "Primary_Risk_Driver"
    ]
    .value_counts()
    .rename_axis("Primary_Risk_Driver")
    .reset_index(
        name="Supplier_Count"
    )
)


primary_driver_distribution[
    "Percentage"
] = (
    primary_driver_distribution[
        "Supplier_Count"
    ]
    /
    len(supplier_alert_explanation)
    * 100
).round(2)


# =============================================================================
# 29. EXPLAINABILITY QUALITY SUMMARY
# =============================================================================

explainability_quality_distribution = (
    supplier_alert_explanation[
        "Explainability_Quality"
    ]
    .value_counts()
    .rename_axis("Explainability_Quality")
    .reset_index(
        name="Supplier_Count"
    )
)


explainability_quality_distribution[
    "Percentage"
] = (
    explainability_quality_distribution[
        "Supplier_Count"
    ]
    /
    len(supplier_alert_explanation)
    * 100
).round(2)


# =============================================================================
# 30. PHASE 14 ROOT-CAUSE SUMMARY TABLE
# =============================================================================

phase14_root_cause_summary = pd.DataFrame(
    {
        "Metric": [
            "Total suppliers explained",
            "Active alerts explained",
            "Critical alerts explained",
            "High alerts explained",
            "Moderate alerts explained",
            "Low alerts explained",
            "Suppliers without predictive warning",
            "High explainability quality",
            "Moderate explainability quality",
            "Limited explainability quality",
            "Severity reconciliation failures",
        ],
        "Value": [
            len(supplier_alert_explanation),

            (
                supplier_alert_explanation[
                    "Alert_Severity"
                ]
                != "No Current Warning"
            ).sum(),

            (
                supplier_alert_explanation[
                    "Alert_Severity"
                ]
                == "Critical"
            ).sum(),

            (
                supplier_alert_explanation[
                    "Alert_Severity"
                ]
                == "High"
            ).sum(),

            (
                supplier_alert_explanation[
                    "Alert_Severity"
                ]
                == "Moderate"
            ).sum(),

            (
                supplier_alert_explanation[
                    "Alert_Severity"
                ]
                == "Low"
            ).sum(),

            (
                supplier_alert_explanation[
                    "Alert_Severity"
                ]
                == "No Current Warning"
            ).sum(),

            (
                supplier_alert_explanation[
                    "Explainability_Quality"
                ]
                == "High"
            ).sum(),

            (
                supplier_alert_explanation[
                    "Explainability_Quality"
                ]
                == "Moderate"
            ).sum(),

            supplier_alert_explanation[
                "Explainability_Quality"
            ]
            .isin(
                [
                    "Limited",
                    "Limited — Predictive Signal Unavailable",
                ]
            )
            .sum(),

            (
                supplier_alert_explanation[
                    "Severity_Reconciliation_Difference"
                ]
                > 0.02
            ).sum(),
        ],
    }
)


# =============================================================================
# 31. CRITICAL EXPLANATIONS
# =============================================================================

critical_columns = [
    "Explanation_Rank",
    "Early_Warning_ID",
    "Supplier_ID",
    "Supplier_Name",

    "Alert_Severity",
    "Alert_Type",

    "Supplier_Failure_Probability",
    "Supplier_Risk_Priority_Score",
    "Supply_Chain_Exposure_Score",
    "Intervention_Urgency_Score",

    "Early_Warning_Severity_Score",

    "Primary_Risk_Driver",
    "Secondary_Risk_Driver",
    "Primary_Driver_Strength",

    "Root_Cause_Category",
    "Root_Cause_Narrative",

    "Potential_Operational_Consequence",
    "Potential_Business_Impact",

    "Recommended_Response",
    "Alert_Management_Escalation",
    "Alert_Timeframe",

    "Full_Risk_Explanation",
]


phase14_critical_explanations = (
    supplier_alert_explanation[
        supplier_alert_explanation[
            "Alert_Severity"
        ] == "Critical"
    ][critical_columns]
    .copy()
)


# =============================================================================
# 32. HIGH-RISK EXPLANATIONS
# =============================================================================

phase14_high_risk_explanations = (
    supplier_alert_explanation[
        supplier_alert_explanation[
            "Alert_Severity"
        ] == "High"
    ][critical_columns]
    .copy()
)


# =============================================================================
# 33. FINAL EXPLANATION TABLE
# =============================================================================

final_columns = [
    "Early_Warning_ID",
    "Alert_Generation_Date",
    "Explanation_Rank",

    "Supplier_ID",
    "Supplier_Name",

    "Alert_Severity",
    "Alert_Type",
    "Alert_Status",

    "Supplier_Failure_Probability",
    "Failure_Risk_Score",

    "Supplier_Risk_Priority_Score",
    "Supply_Chain_Exposure_Score",
    "Intervention_Urgency_Score",

    "Early_Warning_Severity_Score",

    "Driver_Failure_Risk",
    "Driver_Supplier_Risk",
    "Driver_Exposure_Risk",
    "Driver_Intervention_Urgency",

    "Failure_Risk_Contribution",
    "Supplier_Risk_Contribution",
    "Exposure_Risk_Contribution",
    "Intervention_Urgency_Contribution",

    "Reconstructed_Severity_Score",
    "Severity_Reconciliation_Difference",

    "Primary_Risk_Driver",
    "Secondary_Risk_Driver",
    "Primary_Driver_Strength",

    "Predictive_Risk_Interpretation",
    "Supplier_Risk_Interpretation",
    "Exposure_Interpretation",
    "Urgency_Interpretation",

    "Root_Cause_Category",
    "Root_Cause_Narrative",

    "Material_Risk_Driver_Count",

    "Potential_Operational_Consequence",
    "Potential_Business_Impact",

    "Explainability_Quality",
    "Explainability_Statement",
    "Full_Risk_Explanation",

    "Recommended_Response",
    "Recommended_Action",
    "Mitigation_Strategy",

    "Alert_Timeframe",
    "Alert_Management_Escalation",

    "Intervention_Type",
    "Intervention_Priority",
]


supplier_alert_explanation = (
    supplier_alert_explanation[
        [
            col
            for col in final_columns
            if col in supplier_alert_explanation.columns
        ]
    ]
    .copy()
)


# =============================================================================
# 34. FINAL VALIDATION SUMMARY
# =============================================================================

phase14_validation_summary = pd.DataFrame(
    {
        "Validation": [
            "Supplier population preserved",
            "Supplier IDs unique",
            "Severity score reconciled",
            "Driver contributions valid",
            "Primary risk drivers populated",
            "Root-cause categories populated",
            "Risk narratives populated",
            "Operational consequences populated",
            "Explainability quality populated",
            "One explanation per supplier",
        ],
        "Status": [
            "PASS",
            "PASS",
            "PASS",
            "PASS",
            "PASS",
            "PASS",
            "PASS",
            "PASS",
            "PASS",
            "PASS",
        ],
    }
)


# =============================================================================
# 35. DISPLAY ROOT-CAUSE SUMMARY
# =============================================================================

print("\n" + "=" * 90)
print("PHASE 14 — ROOT-CAUSE SUMMARY")
print("=" * 90)

display(
    phase14_root_cause_summary
)


# =============================================================================
# 36. PRIMARY DRIVER DISTRIBUTION
# =============================================================================

print("\n" + "=" * 90)
print("PRIMARY RISK DRIVER DISTRIBUTION")
print("=" * 90)

display(
    primary_driver_distribution
)


# =============================================================================
# 37. ROOT-CAUSE DISTRIBUTION
# =============================================================================

print("\n" + "=" * 90)
print("ROOT-CAUSE DISTRIBUTION")
print("=" * 90)

display(
    root_cause_distribution
)


# =============================================================================
# 38. EXPLAINABILITY QUALITY
# =============================================================================

print("\n" + "=" * 90)
print("EXPLAINABILITY QUALITY")
print("=" * 90)

display(
    explainability_quality_distribution
)


# =============================================================================
# 39. CRITICAL EXPLANATIONS
# =============================================================================

print("\n" + "=" * 90)
print("CRITICAL SUPPLIER ALERT EXPLANATIONS")
print("=" * 90)

if len(phase14_critical_explanations) > 0:

    display(
        phase14_critical_explanations
    )

else:

    print(
        "No Critical supplier explanations generated."
    )


# =============================================================================
# 40. HIGH-RISK EXPLANATIONS
# =============================================================================

print("\n" + "=" * 90)
print("HIGH-RISK SUPPLIER ALERT EXPLANATIONS")
print("=" * 90)

if len(phase14_high_risk_explanations) > 0:

    display(
        phase14_high_risk_explanations.head(50)
    )

else:

    print(
        "No High-risk supplier explanations generated."
    )


# =============================================================================
# 41. TOP EXPLAINED SUPPLIER RISKS
# =============================================================================

print("\n" + "=" * 90)
print("TOP EXPLAINED SUPPLIER RISKS")
print("=" * 90)


top_explanation_columns = [
    "Explanation_Rank",
    "Supplier_ID",
    "Supplier_Name",
    "Alert_Severity",
    "Early_Warning_Severity_Score",
    "Primary_Risk_Driver",
    "Secondary_Risk_Driver",
    "Root_Cause_Category",
    "Explainability_Quality",
]


display(
    supplier_alert_explanation[
        supplier_alert_explanation[
            "Alert_Severity"
        ]
        != "No Current Warning"
    ][top_explanation_columns]
    .head(20)
)


# =============================================================================
# 42. FINAL HARD CHECK
# =============================================================================

assert (
    len(supplier_alert_explanation)
    == len(supplier_early_warning)
)

assert (
    supplier_alert_explanation[
        "Supplier_ID"
    ].is_unique
)

assert (
    supplier_alert_explanation[
        "Early_Warning_ID"
    ].is_unique
)

assert (
    supplier_alert_explanation[
        "Early_Warning_Severity_Score"
    ]
    .between(0, 100)
    .all()
)

assert (
    supplier_alert_explanation[
        "Severity_Reconciliation_Difference"
    ]
    <= 0.02
).all()

assert (
    supplier_alert_explanation[
        "Root_Cause_Category"
    ]
    .notna()
    .all()
)

assert (
    supplier_alert_explanation[
        "Full_Risk_Explanation"
    ]
    .notna()
    .all()
)


# =============================================================================
# 43. FINAL VALIDATION DISPLAY
# =============================================================================

print("\n" + "=" * 90)
print("PHASE 14 — FINAL VALIDATION")
print("=" * 90)

display(
    phase14_validation_summary
)


# =============================================================================
# 44. FINAL SUMMARY
# =============================================================================

total_explanations = (
    len(supplier_alert_explanation)
)

active_explanations = (
    supplier_alert_explanation[
        "Alert_Severity"
    ]
    != "No Current Warning"
).sum()

critical_explanations_count = (
    supplier_alert_explanation[
        "Alert_Severity"
    ]
    == "Critical"
).sum()

high_explanations_count = (
    supplier_alert_explanation[
        "Alert_Severity"
    ]
    == "High"
).sum()

moderate_explanations_count = (
    supplier_alert_explanation[
        "Alert_Severity"
    ]
    == "Moderate"
).sum()

no_predictive_explanation = (
    supplier_alert_explanation[
        "Alert_Severity"
    ]
    == "No Current Warning"
).sum()

high_quality_explanations = (
    supplier_alert_explanation[
        "Explainability_Quality"
    ]
    == "High"
).sum()

reconciliation_failures = (
    supplier_alert_explanation[
        "Severity_Reconciliation_Difference"
    ]
    > 0.02
).sum()


print("\n" + "=" * 90)
print("PHASE 14 — FINAL SUMMARY")
print("=" * 90)

print(
    f"Total supplier explanations       : "
    f"{total_explanations:,}"
)

print(
    f"Active alert explanations        : "
    f"{active_explanations:,}"
)

print(
    f"Critical explanations             : "
    f"{critical_explanations_count:,}"
)

print(
    f"High-risk explanations            : "
    f"{high_explanations_count:,}"
)

print(
    f"Moderate-risk explanations        : "
    f"{moderate_explanations_count:,}"
)

print(
    f"No predictive warning             : "
    f"{no_predictive_explanation:,}"
)

print(
    f"High-quality explanations         : "
    f"{high_quality_explanations:,}"
)

print(
    f"Severity reconciliation failures  : "
    f"{reconciliation_failures:,}"
)

print(
    f"Final explanation records         : "
    f"{len(supplier_alert_explanation):,}"
)

print(
    f"Final columns                     : "
    f"{len(supplier_alert_explanation.columns):,}"
)


# =============================================================================
# 45. FINAL ARCHITECTURE
# =============================================================================

print("\n" + "=" * 90)
print("PHASE 14 — FINAL EXPLAINABILITY ARCHITECTURE")
print("=" * 90)

print("""
Supplier
   ↓
Predictive Failure Probability
   ↓
Supplier Risk Priority
   ↓
Supply-Chain Exposure
   ↓
Intervention Urgency
   ↓
Early-Warning Severity
   ↓
Risk Driver Decomposition
   ↓
Primary Risk Driver
   ↓
Secondary Risk Driver
   ↓
Root-Cause Category
   ↓
Root-Cause Narrative
   ↓
Potential Operational Consequence
   ↓
Potential Business Impact
   ↓
Explainable Risk Narrative
   ↓
Recommended Response
   ↓
MANAGEMENT ACTION
""")


# =============================================================================
# 46. FINAL OBJECTS
# =============================================================================

print("FINAL OBJECTS:")
print("""
    supplier_alert_explanation
    phase14_root_cause_summary
    phase14_critical_explanations
    phase14_high_risk_explanations
    phase14_validation_summary
    root_cause_distribution
    primary_driver_distribution
    explainability_quality_distribution
""")


print("\n" + "=" * 90)
print("✓ PHASE 14 COMPLETED SUCCESSFULLY")
print("=" * 90)


print("\nNEXT:")
print("PHASE 15 — RISK PROPAGATION & SUPPLY-CHAIN IMPACT ENGINE")
print("=" * 90)

==========================================================================================
KEYSTRA — PHASE 14
EARLY-WARNING EXPLAINABILITY & ROOT-CAUSE ENGINE
==========================================================================================

==========================================================================================
PHASE 14 — INPUT VALIDATION
==========================================================================================
✓ supplier_early_warning found
✓ Input rows    : 90
✓ Input columns : 27
✓ All required Phase 13 columns available

==========================================================================================
PHASE 14 — EXPLAINABILITY VALIDATION
==========================================================================================
✓ Supplier population preserved
✓ Supplier IDs unique
✓ Severity score reconciles with Phase 13
✓ Driver contributions valid
✓ Primary risk drivers populated
✓ Root-cause categories populated
✓ Full risk explanations populated
✓ Operational consequences populated
✓ Explainability quality levels valid

==========================================================================================
PHASE 14 — ROOT-CAUSE SUMMARY
==========================================================================================

                                  Metric  Value
0              Total suppliers explained     90
1                Active alerts explained     88
2              Critical alerts explained     10
3                  High alerts explained     26
4              Moderate alerts explained     35
5                   Low alerts explained     17
6   Suppliers without predictive warning      2
7            High explainability quality     88
8        Moderate explainability quality      0
9         Limited explainability quality      2
10      Severity reconciliation failures      0

==========================================================================================
PRIMARY RISK DRIVER DISTRIBUTION
==========================================================================================

     Primary_Risk_Driver  Supplier_Count  Percentage
0    Failure probability              62       68.89
1  Supply-chain exposure              27       30.00
2   Intervention urgency               1        1.11

==========================================================================================
ROOT-CAUSE DISTRIBUTION
==========================================================================================

,Root_Cause_Category,Supplier_Count,Percentage
0,Elevated Predicted Supplier Failure Risk,27,30.00
1,Emerging Supplier Risk,21,23.33
2,Emerging Supplier Failure Risk,18,20.00
3,Emerging Supply-Chain Exposure,10,11.11
4,High Supply-Chain Exposure,8,8.89
5,Predicted Supplier Failure with Material Suppl...,4,4.44
6,Insufficient Predictive Intelligence,2,2.22

==========================================================================================
EXPLAINABILITY QUALITY
==========================================================================================

                    Explainability_Quality  Supplier_Count  Percentage
0                                     High              88       97.78
1  Limited — Predictive Signal Unavailable               2        2.22

==========================================================================================
CRITICAL SUPPLIER ALERT EXPLANATIONS
==========================================================================================

,Explanation_Rank,Early_Warning_ID,Supplier_ID,Supplier_Name,Alert_Severity,Alert_Type,Supplier_Failure_Probability,Supplier_Risk_Priority_Score,Supply_Chain_Exposure_Score,Intervention_Urgency_Score,...,Secondary_Risk_Driver,Primary_Driver_Strength,Root_Cause_Category,Root_Cause_Narrative,Potential_Operational_Consequence,Potential_Business_Impact,Recommended_Response,Alert_Management_Escalation,Alert_Timeframe,Full_Risk_Explanation
0,1,KST-EW-S081-20260731,S081,SunCore Energy Technologies Ltd.,Critical,Predictive Supplier Failure + Exposure Alert,0.99,83.04,100.00,99.64,...,Supplier risk priority,Very High,Predicted Supplier Failure with Material Suppl...,SunCore Energy Technologies Ltd. generated a C...,Potential material supply disruption with cons...,"Potential production disruption, emergency pro...",Activate supplier recovery plan; protect criti...,Executive / Supply Chain Leadership,0–7 days,SunCore Energy Technologies Ltd. received a Cr...
1,2,KST-EW-S055-20260731,S055,Process Materials Solutions Ltd.,Critical,Predictive Supplier Failure + Exposure Alert,0.99,81.93,93.75,95.40,...,Supplier risk priority,Very High,Predicted Supplier Failure with Material Suppl...,Process Materials Solutions Ltd. generated a C...,Potential material supply disruption with cons...,"Potential production disruption, emergency pro...",Activate supplier recovery plan; protect criti...,Executive / Supply Chain Leadership,0–7 days,Process Materials Solutions Ltd. received a Cr...
2,3,KST-EW-S004-20260731,S004,Sterling Industrial Equipment Ltd.,Critical,Predictive Supplier Failure + Exposure Alert,0.92,81.30,100.00,96.70,...,Supplier risk priority,Very High,Predicted Supplier Failure with Material Suppl...,Sterling Industrial Equipment Ltd. generated a...,Potential material supply disruption with cons...,"Potential production disruption, emergency pro...",Activate supplier recovery plan; protect criti...,Executive / Supply Chain Leadership,0–7 days,Sterling Industrial Equipment Ltd. received a ...
4,5,KST-EW-S025-20260731,S025,Brightline Electrical Industries Ltd.,Critical,Predictive Supplier Failure Alert,0.99,72.15,63.50,78.78,...,Supplier risk priority,Very High,Elevated Predicted Supplier Failure Risk,Brightline Electrical Industries Ltd. generate...,Potential material supply disruption with cons...,"Potential production disruption, emergency pro...",Activate supplier recovery plan; protect criti...,Executive / Supply Chain Leadership,0–7 days,Brightline Electrical Industries Ltd. received...
5,6,KST-EW-S009-20260731,S009,Ironbridge Equipment Solutions Ltd.,Critical,Predictive Supplier Failure Alert,0.99,71.53,63.50,78.75,...,Supplier risk priority,Very High,Elevated Predicted Supplier Failure Risk,Ironbridge Equipment Solutions Ltd. generated ...,Potential material supply disruption with cons...,"Potential production disruption, emergency pro...",Activate supplier recovery plan; protect criti...,Executive / Supply Chain Leadership,0–7 days,Ironbridge Equipment Solutions Ltd. received a...
6,7,KST-EW-S058-20260731,S058,Nexus Industrial Supply Ltd.,Critical,Predictive Supplier Failure Alert,0.99,71.29,63.50,78.72,...,Supplier risk priority,Very High,Elevated Predicted Supplier Failure Risk,Nexus Industrial Supply Ltd. generated a Criti...,Potential material supply disruption with cons...,"Potential production disruption, emergency pro...",Activate supplier recovery plan; protect criti...,Executive / Supply Chain Leadership,0–7 days,Nexus Industrial Supply Ltd. received a Critic...
7,8,KST-EW-S087-20260731,S087,Continental Industrial Services Ltd.,Critical,Predictive Supplier Failure Alert,0.99,71.39,63.50,78.62,...,Supplier risk priority,Very High,Elevated Predicted Supplier Failure Risk,Continental Industrial Services Ltd. generated...,Potential material supply disruption with cons...,"Potential production disruption, emergency pro...",Activate supplier recovery plan; protect criti...,Executive / Supply Chain Leadership,0–7 days,Continental Industrial Services Ltd. received ...
8,9,KST-EW-S003-20260731,S003,Atlas Turbomachinery Services Ltd.,Critical,Predictive Supplier Failure Alert,0.99,71.22,63.50,78.65,...,Supplier risk priority,Very High,Elevated Predicted Supplier Failure Risk,Atlas Turbomachinery Services Ltd. generated a...,Potential material supply disruption with cons...,"Potential production disruption, emergency pro...",Activate supplier recovery plan; protect criti...,Executive / Supply Chain Leadership,0–7 days,Atlas Turbomachinery Services Ltd. received a ...
9,10,KST-EW-S035-20260731,S035,Advanced Process Instruments Ltd.,Critical,Predictive Supplier Failure Alert,0.98,72.50,63.50,78.12,...,Supplier risk priority,Very High,Elevated Predicted Supplier Failure Risk,Advanced Process Instruments Ltd. generated a ...,Potential material supply disruption with cons...,"Potential production disruption, emergency pro...",Activate supplier recovery plan; protect criti...,Executive / Supply Chain Leadership,0–7 days,Advanced Process Instruments Ltd. received a C...
10,11,KST-EW-S030-20260731,S030,Axis Process Controls Ltd.,Critical,Predictive Supplier Failure Alert,0.98,70.82,63.50,78.24,...,Supplier risk priority,Very High,Elevated Predicted Supplier Failure Risk,Axis Process Controls Ltd. generated a Critica...,Potential material supply disruption with cons...,"Potential production disruption, emergency pro...",Activate supplier recovery plan; protect criti...,Executive / Supply Chain Leadership,0–7 days,Axis Process Controls Ltd. received a Critical...

==========================================================================================
HIGH-RISK SUPPLIER ALERT EXPLANATIONS
==========================================================================================

,Explanation_Rank,Early_Warning_ID,Supplier_ID,Supplier_Name,Alert_Severity,Alert_Type,Supplier_Failure_Probability,Supplier_Risk_Priority_Score,Supply_Chain_Exposure_Score,Intervention_Urgency_Score,...,Secondary_Risk_Driver,Primary_Driver_Strength,Root_Cause_Category,Root_Cause_Narrative,Potential_Operational_Consequence,Potential_Business_Impact,Recommended_Response,Alert_Management_Escalation,Alert_Timeframe,Full_Risk_Explanation
3,4,KST-EW-S019-20260731,S019,Powerlink Industrial Systems Ltd.,High,Predictive Supplier Failure + Exposure Alert,0.80,72.35,87.5,83.30,...,Supplier risk priority,Very High,Predicted Supplier Failure with Material Suppl...,Powerlink Industrial Systems Ltd. generated a ...,Potential disruption to material availability ...,"Potential procurement disruption, material ava...",Engage supplier; initiate corrective action; a...,Supply Chain Risk Management,Within 14 days,Powerlink Industrial Systems Ltd. received a H...
11,12,KST-EW-S001-20260731,S001,Apex Rotating Systems Ltd.,High,Predictive Supplier Failure Alert,0.93,70.04,63.5,76.27,...,Supplier risk priority,Very High,Elevated Predicted Supplier Failure Risk,Apex Rotating Systems Ltd. generated a High ea...,Potential disruption to material availability ...,"Potential procurement disruption, material ava...",Engage supplier; initiate corrective action; a...,Supply Chain Risk Management,Within 14 days,Apex Rotating Systems Ltd. received a High ear...
12,13,KST-EW-S054-20260731,S054,Industrial Supply Partners Ltd.,High,Predictive Supplier Failure Alert,0.92,69.25,63.5,75.88,...,Supplier risk priority,Very High,Elevated Predicted Supplier Failure Risk,Industrial Supply Partners Ltd. generated a Hi...,Potential disruption to material availability ...,"Potential procurement disruption, material ava...",Engage supplier; initiate corrective action; a...,Supply Chain Risk Management,Within 14 days,Industrial Supply Partners Ltd. received a Hig...
13,14,KST-EW-S010-20260731,S010,Pinnacle Machinery Services Ltd.,High,Predictive Supplier Failure Alert,0.99,65.18,52.0,75.13,...,Supplier risk priority,Very High,Elevated Predicted Supplier Failure Risk,Pinnacle Machinery Services Ltd. generated a H...,Potential disruption to material availability ...,"Potential procurement disruption, material ava...",Engage supplier; initiate corrective action; a...,Supply Chain Risk Management,Within 14 days,Pinnacle Machinery Services Ltd. received a Hi...
14,15,KST-EW-S047-20260731,S047,DeltaFlow Technologies Ltd.,High,Predictive Supplier Failure Alert,0.90,68.24,63.5,74.86,...,Supplier risk priority,Very High,Elevated Predicted Supplier Failure Risk,DeltaFlow Technologies Ltd. generated a High e...,Potential disruption to material availability ...,"Potential procurement disruption, material ava...",Engage supplier; initiate corrective action; a...,Supply Chain Risk Management,Within 14 days,DeltaFlow Technologies Ltd. received a High ea...
15,16,KST-EW-S013-20260731,S013,Westfield Industrial Engineering Ltd.,High,Predictive Supplier Failure Alert,0.98,64.75,52.0,74.90,...,Supplier risk priority,Very High,Elevated Predicted Supplier Failure Risk,Westfield Industrial Engineering Ltd. generate...,Potential disruption to material availability ...,"Potential procurement disruption, material ava...",Engage supplier; initiate corrective action; a...,Supply Chain Risk Management,Within 14 days,Westfield Industrial Engineering Ltd. received...
16,17,KST-EW-S018-20260731,S018,Crown Electrical Technologies Ltd.,High,Predictive Supplier Failure Alert,0.97,65.87,52.0,74.22,...,Supplier risk priority,Very High,Elevated Predicted Supplier Failure Risk,Crown Electrical Technologies Ltd. generated a...,Potential disruption to material availability ...,"Potential procurement disruption, material ava...",Engage supplier; initiate corrective action; a...,Supply Chain Risk Management,Within 14 days,Crown Electrical Technologies Ltd. received a ...
17,18,KST-EW-S079-20260731,S079,SolarEdge Industrial Energy Ltd.,High,Predictive Supplier Failure Alert,0.94,63.50,52.0,73.05,...,Supplier risk priority,Very High,Elevated Predicted Supplier Failure Risk,SolarEdge Industrial Energy Ltd. generated a H...,Potential disruption to material availability ...,"Potential procurement disruption, material ava...",Engage supplier; initiate corrective action; a...,Supply Chain Risk Management,Within 14 days,SolarEdge Industrial Energy Ltd. received a Hi...
18,19,KST-EW-S062-20260731,S062,Reliable Industrial Materials Ltd.,High,Predictive Supplier Failure Alert,0.93,63.61,52.0,72.96,...,Supplier risk priority,Very High,Elevated Predicted Supplier Failure Risk,Reliable Industrial Materials Ltd. generated a...,Potential disruption to material availability ...,"Potential procurement disruption, material ava...",Engage supplier; initiate corrective action; a...,Supply Chain Risk Management,Within 14 days,Reliable Industrial Materials Ltd. received a ...
19,20,KST-EW-S069-20260731,S069,WestAfrica Chemical Solutions Ltd.,High,Predictive Supplier Failure Alert,0.91,63.40,52.0,72.15,...,Supplier risk priority,Very High,Elevated Predicted Supplier Failure Risk,WestAfrica Chemical Solutions Ltd. generated a...,Potential disruption to material availability ...,"Potential procurement disruption, material ava...",Engage supplier; initiate corrective action; a...,Supply Chain Risk Management,Within 14 days,WestAfrica Chemical Solutions Ltd. received a ...
20,21,KST-EW-S061-20260731,S061,MetroProcess Supplies Ltd.,High,Predictive Supplier Failure Alert,1.00,59.10,40.5,71.97,...,Supplier risk priority,Very High,Elevated Predicted Supplier Failure Risk,MetroProcess Supplies Ltd. generated a High ea...,Potential disruption to material availability ...,"Potential procurement disruption, material ava...",Engage supplier; initiate corrective action; a...,Supply Chain Risk Management,Within 14 days,MetroProcess Supplies Ltd. received a High ear...
21,22,KST-EW-S089-20260731,S089,Nexus Energy Equipment Solutions Ltd.,High,Predictive Supplier Failure Alert,0.90,61.73,52.0,71.68,...,Supplier risk priority,Very High,Elevated Predicted Supplier Failure Risk,Nexus Energy Equipment Solutions Ltd. generate...,Potential disruption to material availability ...,"Potential procurement disruption, material ava...",Engage supplier; initiate corrective action; a...,Supply Chain Risk Management,Within 14 days,Nexus Energy Equipment Solutions Ltd. received...
22,23,KST-EW-S038-20260731,S038,OptiSense Systems Ltd.,High,Predictive Supplier Failure Alert,0.98,58.37,40.5,71.25,...,Supplier risk priority,Very High,Elevated Predicted Supplier Failure Risk,OptiSense Systems Ltd. generated a High early-...,Potential disruption to material availability ...,"Potential procurement disruption, material ava...",Engage supplier; initiate corrective action; a...,Supply Chain Risk Management,Within 14 days,OptiSense Systems Ltd. received a High early-w...
23,24,KST-EW-S082-20260731,S082,RenewPower Engineering Ltd.,High,Predictive Supplier Failure Alert,0.89,60.89,52.0,71.04,...,Supplier risk priority,Very High,Elevated Predicted Supplier Failure Risk,RenewPower Engineering Ltd. generated a High e...,Potential disruption to material availability ...,"Potential procurement disruption, material ava...",Engage supplier; initiate corrective action; a...,Supply Chain Risk Management,Within 14 days,RenewPower Engineering Ltd. received a High ea...
24,25,KST-EW-S015-20260731,S015,Grandview Mechanical Systems Ltd.,High,Predictive Supplier Failure Alert,0.87,60.12,52.0,70.27,...,Supplier risk priority,Very High,Elevated Predicted Supplier Failure Risk,Grandview Mechanical Systems Ltd. generated a ...,Potential disruption to material availability ...,"Potential procurement disruption, material ava...",Engage supplier; initiate corrective action; a...,Supply Chain Risk Management,Within 14 days,Grandview Mechanical Systems Ltd. received a H...
25,26,KST-EW-S040-20260731,S040,FlowGuard Industrial Ltd.,High,Predictive Supplier Failure Alert,0.86,61.34,52.0,70.09,...,Supplier risk priority,Very High,Elevated Predicted Supplier Failure Risk,FlowGuard Industrial Ltd. generated a High ear...,Potential disruption to material availability ...,"Potential procurement disruption, material ava...",Engage supplier; initiate corrective action; a...,Supply Chain Risk Management,Within 14 days,FlowGuard Industrial Ltd. received a High earl...
26,27,KST-EW-S090-20260731,S090,Frontier Industrial Technologies Ltd.,High,Predictive Supplier Failure Alert,0.86,59.99,52.0,70.14,...,Supplier risk priority,Very High,Elevated Predicted Supplier Failure Risk,Frontier Industrial Technologies Ltd. generate...,Potential disruption to material availability ...,"Potential procurement disruption, material ava...",Engage supplier; initiate corrective action; a...,Supply Chain Risk Management,Within 14 days,Frontier Industrial Technologies Ltd. received...
27,28,KST-EW-S024-20260731,S024,Enertech Power Solutions Ltd.,High,Predictive Supplier Failure Alert,0.94,57.15,40.5,69.82,...,Supplier risk priority,Very High,Elevated Predicted Supplier Failure Risk,Enertech Power Solutions Ltd. generated a High...,Potential disruption to material availability ...,"Potential procurement disruption, material ava...",Engage supplier; initiate corrective action; a...,Supply Chain Risk Management,Within 14 days,Enertech Power Solutions Ltd. received a High ...
28,29,KST-EW-S071-20260731,S071,ProcessChem Technologies Ltd.,High,Predictive Supplier Failure Alert,0.84,59.69,52.0,69.04,...,Supplier risk priority,Very High,Elevated Predicted Supplier Failure Risk,ProcessChem Technologies Ltd. generated a High...,Potential disruption to material availability ...,"Potential procurement disruption, material ava...",Engage supplier; initiate corrective action; a...,Supply Chain Risk Management,Within 14 days,ProcessChem Technologies Ltd. received a High ...
29,30,KST-EW-S076-20260731,S076,Sentinel Safety Equipment Ltd.,High,Predictive Supplier Failure Alert,0.89,56.30,40.5,67.78,...,Supplier risk priority,Very High,Elevated Predicted Supplier Failure Risk,Sentinel Safety Equipment Ltd. generated a Hig...,Potential disruption to material availability ...,"Potential procurement disruption, material ava...",Engage supplier; initiate corrective action; a...,Supply Chain Risk Management,Within 14 days,Sentinel Safety Equipment Ltd. received a High...
30,31,KST-EW-S064-20260731,S064,PetroChem Solutions Ltd.,High,Predictive Supplier Failure Alert,0.87,55.35,40.5,66.83,...,Supplier risk priority,Very High,Elevated Predicted Supplier Failure Risk,PetroChem Solutions Ltd. generated a High earl...,Potential disruption to material availability ...,"Potential procurement disruption, material ava...",Engage supplier; initiate corrective action; a...,Supply Chain Risk Management,Within 14 days,PetroChem Solutions Ltd. received a High early...
31,32,KST-EW-S034-20260731,S034,NexControl Engineering Ltd.,High,Supply-Chain Exposure Alert,0.50,62.81,100.0,79.81,...,Failure probability,High,High Supply-Chain Exposure,NexControl Engineering Ltd. generated a High e...,Potential disruption to material availability ...,"Potential procurement disruption, material ava...",Engage supplier; initiate corrective action; a...,Supply Chain Risk Management,Within 14 days,NexControl Engineering Ltd. received a High ea...
32,33,KST-EW-S057-20260731,S057,CoreProcess Materials Ltd.,High,Supply-Chain Exposure Alert,0.49,62.50,100.0,79.50,...,Failure probability,High,High Supply-Chain Exposure,CoreProcess Materials Ltd. generated a High ea...,Potential disruption to material availability ...,"Potential procurement disruption, material ava...",Engage supplier; initiate corrective action; a...,Supply Chain Risk Management,Within 14 days,CoreProcess Materials Ltd. received a High ear...
33,34,KST-EW-S086-20260731,S086,Integrated Energy Supply Solutions Ltd.,High,Supply-Chain Exposure Alert,0.55,63.12,90.0,74.92,...,Supply-chain exposure,High,High Supply-Chain Exposure,Integrated Energy Supply Solutions Ltd. genera...,Potential disruption to material availability ...,"Potential procurement disruption, material ava...",Engage supplier; initiate corrective action; a...,Supply Chain Risk Management,Within 14 days,Integrated Energy Supply Solutions Ltd. receiv...
39,40,KST-EW-S014-20260731,S014,Orion Machinery & Engineering Ltd.,High,Emerging Supplier Risk Alert,0.79,57.16,52.0,67.31,...,Supplier risk priority,Very High,Emerging Supplier Failure Risk,Orion Machinery & Engineering Ltd. generated a...,Potential disruption to material availability ...,"Potential procurement disruption, material ava...",Engage supplier; initiate corrective action; a...,Supply Chain Risk Management,Within 14 days,Orion Machinery & Engineering Ltd. received a ...
40,41,KST-EW-S011-20260731,S011,BluePeak Mechanical Systems Ltd.,High,Emerging Supplier Risk Alert,0.79,56.97,52.0,67.12,...,Supplier risk priority,Very High,Emerging Supplier Failure Risk,BluePeak Mechanical Systems Ltd. generated a H...,Potential disruption to material availability ...,"Potential procurement disruption, material ava...",Engage supplier; initiate corrective action; a...,Supply Chain Risk Management,Within 14 days,BluePeak Mechanical Systems Ltd. received a Hi...

==========================================================================================
TOP EXPLAINED SUPPLIER RISKS
==========================================================================================

,Explanation_Rank,Supplier_ID,Supplier_Name,Alert_Severity,Early_Warning_Severity_Score,Primary_Risk_Driver,Secondary_Risk_Driver,Root_Cause_Category,Explainability_Quality
0,1,S081,SunCore Energy Technologies Ltd.,Critical,95.34,Failure probability,Supplier risk priority,Predicted Supplier Failure with Material Suppl...,High
1,2,S055,Process Materials Solutions Ltd.,Critical,92.96,Failure probability,Supplier risk priority,Predicted Supplier Failure with Material Suppl...,High
2,3,S004,Sterling Industrial Equipment Ltd.,Critical,91.86,Failure probability,Supplier risk priority,Predicted Supplier Failure with Material Suppl...,High
3,4,S019,Powerlink Industrial Systems Ltd.,High,80.25,Failure probability,Supplier risk priority,Predicted Supplier Failure with Material Suppl...,High
4,5,S025,Brightline Electrical Industries Ltd.,Critical,81.14,Failure probability,Supplier risk priority,Elevated Predicted Supplier Failure Risk,High
5,6,S009,Ironbridge Equipment Solutions Ltd.,Critical,80.98,Failure probability,Supplier risk priority,Elevated Predicted Supplier Failure Risk,High
6,7,S058,Nexus Industrial Supply Ltd.,Critical,80.92,Failure probability,Supplier risk priority,Elevated Predicted Supplier Failure Risk,High
7,8,S087,Continental Industrial Services Ltd.,Critical,80.92,Failure probability,Supplier risk priority,Elevated Predicted Supplier Failure Risk,High
8,9,S003,Atlas Turbomachinery Services Ltd.,Critical,80.89,Failure probability,Supplier risk priority,Elevated Predicted Supplier Failure Risk,High
9,10,S035,Advanced Process Instruments Ltd.,Critical,80.75,Failure probability,Supplier risk priority,Elevated Predicted Supplier Failure Risk,High
10,11,S030,Axis Process Controls Ltd.,Critical,80.35,Failure probability,Supplier risk priority,Elevated Predicted Supplier Failure Risk,High
11,12,S001,Apex Rotating Systems Ltd.,High,78.01,Failure probability,Supplier risk priority,Elevated Predicted Supplier Failure Risk,High
12,13,S054,Industrial Supply Partners Ltd.,High,77.39,Failure probability,Supplier risk priority,Elevated Predicted Supplier Failure Risk,High
13,14,S010,Pinnacle Machinery Services Ltd.,High,76.37,Failure probability,Supplier risk priority,Elevated Predicted Supplier Failure Risk,High
14,15,S047,DeltaFlow Technologies Ltd.,High,76.23,Failure probability,Supplier risk priority,Elevated Predicted Supplier Failure Risk,High
15,16,S013,Westfield Industrial Engineering Ltd.,High,75.87,Failure probability,Supplier risk priority,Elevated Predicted Supplier Failure Risk,High
16,17,S018,Crown Electrical Technologies Ltd.,High,75.66,Failure probability,Supplier risk priority,Elevated Predicted Supplier Failure Risk,High
17,18,S079,SolarEdge Industrial Energy Ltd.,High,73.78,Failure probability,Supplier risk priority,Elevated Predicted Supplier Failure Risk,High
18,19,S062,Reliable Industrial Materials Ltd.,High,73.44,Failure probability,Supplier risk priority,Elevated Predicted Supplier Failure Risk,High
19,20,S069,WestAfrica Chemical Solutions Ltd.,High,72.53,Failure probability,Supplier risk priority,Elevated Predicted Supplier Failure Risk,High

==========================================================================================
PHASE 14 — FINAL VALIDATION
==========================================================================================

                           Validation Status
0       Supplier population preserved   PASS
1                 Supplier IDs unique   PASS
2           Severity score reconciled   PASS
3          Driver contributions valid   PASS
4      Primary risk drivers populated   PASS
5     Root-cause categories populated   PASS
6           Risk narratives populated   PASS
7  Operational consequences populated   PASS
8    Explainability quality populated   PASS
9        One explanation per supplier   PASS

==========================================================================================
PHASE 14 — FINAL SUMMARY
==========================================================================================
Total supplier explanations       : 90
Active alert explanations        : 88
Critical explanations             : 10
High-risk explanations            : 26
Moderate-risk explanations        : 35
No predictive warning             : 2
High-quality explanations         : 88
Severity reconciliation failures  : 0
Final explanation records         : 90
Final columns                     : 46

==========================================================================================
PHASE 14 — FINAL EXPLAINABILITY ARCHITECTURE
==========================================================================================

Supplier
   ↓
Predictive Failure Probability
   ↓
Supplier Risk Priority
   ↓
Supply-Chain Exposure
   ↓
Intervention Urgency
   ↓
Early-Warning Severity
   ↓
Risk Driver Decomposition
   ↓
Primary Risk Driver
   ↓
Secondary Risk Driver
   ↓
Root-Cause Category
   ↓
Root-Cause Narrative
   ↓
Potential Operational Consequence
   ↓
Potential Business Impact
   ↓
Explainable Risk Narrative
   ↓
Recommended Response
   ↓
MANAGEMENT ACTION

FINAL OBJECTS:

    supplier_alert_explanation
    phase14_root_cause_summary
    phase14_critical_explanations
    phase14_high_risk_explanations
    phase14_validation_summary
    root_cause_distribution
    primary_driver_distribution
    explainability_quality_distribution


==========================================================================================
✓ PHASE 14 COMPLETED SUCCESSFULLY
==========================================================================================

NEXT:
PHASE 15 — RISK PROPAGATION & SUPPLY-CHAIN IMPACT ENGINE
==========================================================================================

In [26]:
# KEYSTRA — PHASE 15
# SHORT RUNTIME DATAFRAME INVENTORY

import pandas as pd

print("=" * 80)
print("KEYSTRA — AVAILABLE DATAFRAMES")
print("=" * 80)

for name, obj in globals().items():
    if isinstance(obj, pd.DataFrame):
        print(f"{name:<45} {obj.shape}")

================================================================================
KEYSTRA — AVAILABLE DATAFRAMES
================================================================================
dates                                         (150570, 4)
dim_date                                      (1673, 12)
dim_asset                                     (13, 7)
dim_asset_check                               (13, 7)
dim_supplier                                  (90, 10)
daily_demand                                  (31206, 3)
safety_stock                                  (60, 3)
dim_material                                  (60, 11)
dim_supplier_reload                           (90, 10)
dim_material_reload                           (60, 11)
dim_failure_type                              (5, 2)
reloaded_failure_type                         (5, 2)
supplier_master                               (90, 10)
material_master                               (60, 12)
candidates                                    (13, 3)
bridge_supplier_material                      (174, 5)
candidate_materials                           (23, 2)
validation_join                               (174, 7)
material_sourcing_check                       (60, 4)
invalid_sourcing                              (0, 4)
bridge_reload                                 (174, 5)
asset_master                                  (13, 8)
candidate_pairs                               (780, 3)
criticality                                   (60, 2)
bridge_asset_material                         (141, 6)
material_lookup                               (60, 10)
material_dependency_check                     (141, 9)
reloaded_bridge_asset_material                (141, 6)
suppliers                                     (90, 10)
materials                                     (60, 11)
assets                                        (13, 7)
supplier_material                             (174, 5)
asset_material                                (141, 6)
df                                            (60, 3)
supplier_lookup                               (90, 2)
fact_purchase_order_line                      (40000, 19)
date_lookup                                   (1673, 2)
supplier_outcomes                             (90, 5)
po                                            (40000, 20)
dim_supplier_work                             (90, 10)
dim_material_work                             (60, 11)
dim_asset_work                                (13, 7)
dim_failure_type_work                         (5, 2)
bridge_supplier_material_work                 (174, 5)
bridge_asset_material_work                    (141, 6)
eligible_po                                   (35392, 31)
history_source                                (35392, 19)
material_criticality                          (60, 2)
quality_candidates                            (748, 40)
quality_failure_rows                          (1, 2)
fact_quality_event                            (748, 14)
po_lookup                                     (40000, 6)
validation_merge                              (748, 19)
temporal_validation                           (35392, 4)
quality_temporal_check                        (748, 17)
first_observations                            (90, 31)
severity_rejection_summary                    (4, 2)
quality                                       (748, 14)
demand_orders                                 (39688, 20)
material_safety_stock                         (60, 3)
receipts                                      (35392, 24)
quality_rejections                            (748, 3)
daily_receipts                                (28369, 5)
material_date_grid                            (100380, 26)
fact_inventory_snapshot                       (100380, 25)
stockout_rows                                 (11596, 25)
future_receipts                               (0, 24)
future_quality                                (0, 14)
quality_date_check                            (748, 3)
stockout_by_material                          (60, 7)
operational_po                                (39688, 20)
supplier_date_grid                            (150570, 45)
daily_supplier_activity                       (34909, 9)
delivery_activity                             (35392, 25)
daily_delivery                                (31388, 6)
po_events                                     (39688, 5)
daily_ordered                                 (34909, 3)
daily_received                                (31388, 3)
fact_supplier_risk_phase1                     (150570, 32)
future_po                                     (39688, 25)
supplier_future_events                        (34909, 7)
observation_grid                              (150570, 2)
future_events                                 (34909, 7)
obs_group                                     (1673, 2)
supplier_events                               (351, 7)
future_outcome                                (150570, 11)
fact_supplier_risk_label                      (150570, 41)
labelable                                     (138953, 18)
label_counts                                  (2, 3)
component_df                                  (4, 6)
combination_distribution                      (4, 3)
label_component                               (4, 5)
state_analysis                                (4, 5)
supplier_analysis                             (90, 4)
combo                                         (6, 7)
phase2                                        (150570, 32)
future_base                                   (150570, 20)
future_roll                                   (150570, 42)
fact_supplier_failure_outcome                 (150570, 18)
component_summary_df                          (4, 3)
one_dimension_failures                        (0, 18)
combo_summary                                 (10, 7)
group                                         (1673, 71)
fact_supplier_risk_state                      (150570, 72)
failure_df                                    (9407, 72)
supplier_history                              (1673, 72)
prior_history                                 (1663, 72)
severity_summary                              (5, 7)
phase1                                        (150570, 32)
phase3                                        (150570, 18)
phase4                                        (150570, 72)
target_df                                     (150570, 3)
phase1_selected                               (150570, 23)
phase4_selected                               (150570, 21)
model_df                                      (138953, 57)
fact_supplier_model_ready                     (138953, 57)
phase6_train                                  (96995, 59)
phase6_validation                             (20849, 59)
phase6_test                                   (21109, 59)
split_summary                                 (3, 4)
X_train                                       (96995, 54)
X_validation                                  (20849, 54)
X_test                                        (21109, 54)
phase6_model_results                          (3, 14)
test_cm_df                                    (2, 2)
train_drift_df                                (96995, 59)
validation_drift_df                           (20849, 59)
test_drift_df                                 (21109, 59)
train_yearly                                  (4, 4)
train_monthly                                 (38, 4)
validation_yearly                             (1, 4)
validation_monthly                            (9, 4)
test_yearly                                   (2, 4)
test_monthly                                  (9, 4)
validation_threshold_results                  (17, 5)
eligible_thresholds                           (15, 5)
high_recall_candidates                        (14, 5)
model_validation_results                      (3, 3)
best_model_threshold_results                  (17, 5)
eligible_best                                 (17, 5)
high_recall_best                              (13, 5)
comparison                                    (5, 4)
importance_sample                             (10000, 54)
feature_importance                            (54, 3)
phase7_model_results                          (1, 10)
model_ready                                   (138953, 57)
risk_state                                    (150570, 72)
current_model                                 (88, 57)
state_snapshot                                (90, 11)
current_snapshot                              (88, 62)
X_current                                     (88, 54)
state_severity_summary                        (9, 5)
fact_supplier_early_warning                   (88, 62)
ew                                            (88, 62)
current                                       (88, 86)
fi                                            (54, 3)
top_supplier_risk_drivers                     (88, 22)
fact_supplier_explainable_warning             (88, 109)
supplier_risk_explanations                    (88, 28)
warning                                       (88, 109)
supplier_dim                                  (90, 10)
material_dim                                  (60, 11)
asset_dim                                     (13, 7)
current_warning                               (88, 110)
material_attributes                           (60, 2)
criticality_context                           (60, 3)
safety_context                                (60, 3)
supplier_material_context                     (174, 2)
material_asset_context                        (141, 2)
asset_attributes                              (13, 5)
material_asset_enriched                       (141, 6)
supplier_material_asset                       (407, 16)
supplier_exposure                             (90, 11)
phase10                                       (405, 135)
supplier_context_summary                      (88, 11)
phase10_critical_dependencies                 (31, 135)
fact_supplier_supply_chain_context            (405, 135)
phase10_supplier_summary                      (88, 11)
supplier_universe                             (90, 3)
context                                       (405, 136)
supplier_context                              (88, 14)
risk_state_lookup                             (88, 3)
supplier_risk                                 (90, 22)
critical_exposure_display                     (12, 22)
supplier_input                                (90, 22)
intervention                                  (90, 25)
supplier_intervention                         (90, 25)
phase12_supplier_summary                      (90, 14)
phase12_critical_interventions                (52, 25)
phase12_intervention_summary                  (8, 2)
phase12_validation_summary                    (9, 2)
supplier_early_warning                        (90, 27)
phase13_validation_summary                    (10, 2)
phase13_alert_summary                         (9, 2)
top_alerts                                    (20, 11)
phase13_critical_alerts                       (10, 13)
phase13_high_alerts                           (26, 13)
phase13_no_current_warning                    (2, 7)
alert_distribution                            (5, 3)
alert_type_distribution                       (6, 3)
supplier_alert_explanation                    (90, 46)
driver_matrix                                 (90, 4)
root_cause_distribution                       (7, 3)
primary_driver_distribution                   (3, 3)
explainability_quality_distribution           (2, 3)
phase14_root_cause_summary                    (11, 2)
phase14_critical_explanations                 (10, 22)
phase14_high_risk_explanations                (26, 22)
phase14_validation_summary                    (10, 2)

In [27]:
# KEYSTRA — PHASE 15
# TARGET OBJECT SCHEMA CHECK

phase15_targets = [
    "supplier_alert_explanation",
    "supplier_material_asset",
    "fact_purchase_order_line",
    "fact_inventory_snapshot",
    "fact_supplier_supply_chain_context",
    "supplier_exposure"
]

print("=" * 100)
print("KEYSTRA — PHASE 15 TARGET SCHEMAS")
print("=" * 100)

for name in phase15_targets:
    obj = globals().get(name)

    print(f"\n{name}")
    print(f"Shape: {obj.shape}")
    print("Columns:")
    print(list(obj.columns))

====================================================================================================
KEYSTRA — PHASE 15 TARGET SCHEMAS
====================================================================================================

supplier_alert_explanation
Shape: (90, 46)
Columns:
['Early_Warning_ID', 'Alert_Generation_Date', 'Explanation_Rank', 'Supplier_ID', 'Supplier_Name', 'Alert_Severity', 'Alert_Type', 'Alert_Status', 'Supplier_Failure_Probability', 'Failure_Risk_Score', 'Supplier_Risk_Priority_Score', 'Supply_Chain_Exposure_Score', 'Intervention_Urgency_Score', 'Early_Warning_Severity_Score', 'Driver_Failure_Risk', 'Driver_Supplier_Risk', 'Driver_Exposure_Risk', 'Driver_Intervention_Urgency', 'Failure_Risk_Contribution', 'Supplier_Risk_Contribution', 'Exposure_Risk_Contribution', 'Intervention_Urgency_Contribution', 'Reconstructed_Severity_Score', 'Severity_Reconciliation_Difference', 'Primary_Risk_Driver', 'Secondary_Risk_Driver', 'Primary_Driver_Strength', 'Predictive_Risk_Interpretation', 'Supplier_Risk_Interpretation', 'Exposure_Interpretation', 'Urgency_Interpretation', 'Root_Cause_Category', 'Root_Cause_Narrative', 'Material_Risk_Driver_Count', 'Potential_Operational_Consequence', 'Potential_Business_Impact', 'Explainability_Quality', 'Explainability_Statement', 'Full_Risk_Explanation', 'Recommended_Response', 'Recommended_Action', 'Mitigation_Strategy', 'Alert_Timeframe', 'Alert_Management_Escalation', 'Intervention_Type', 'Intervention_Priority']

supplier_material_asset
Shape: (407, 16)
Columns:
['Supplier_ID', 'Material_ID', 'Material_Name', 'Material_Criticality', 'Material_Criticality_Score', 'Safety_Stock', 'Reorder_Point', 'Asset_ID', 'Asset_Name', 'Asset_Type', 'Asset_Criticality', 'Asset_Criticality_Score', 'Operational_Dependency_Score', 'Operational_Dependency', 'Potential_Operational_Consequence', 'Material_Exposure_Status']

fact_purchase_order_line
Shape: (40000, 19)
Columns:
['PO_Line_ID', 'PO_ID', 'Date_ID', 'Order_Date', 'Supplier_ID', 'Material_ID', 'Asset_ID', 'Priority', 'PO_Status', 'Quantity_Ordered', 'Unit_Cost_USD', 'Order_Value_USD', 'Expected_Delivery_Date', 'Actual_Delivery_Date', 'Quantity_Received', 'Days_Late', 'Fulfilment_Rate', 'Outstanding_Quantity', 'Outstanding_Value_USD']

fact_inventory_snapshot
Shape: (100380, 25)
Columns:
['Date_ID', 'Snapshot_Date', 'Material_ID', 'Safety_Stock', 'Demand_Quantity', 'Gross_Receipt_Quantity', 'Rejected_Receipt_Quantity', 'Usable_Receipt_Quantity', 'Inventory_Before_Demand', 'On_Hand_Quantity', 'Net_Inventory_Change', 'Stockout_Quantity', 'Stockout_Flag', 'Low_Stock_Flag', 'Safety_Stock_Breach_Flag', 'Critical_Stock_Flag', 'Inventory_Coverage_Days', 'Receipt_Rejection_Rate', 'Usable_Receipt_Rate', 'Rolling_30D_Avg_Inventory', 'Rolling_30D_Avg_Demand', 'Inventory_Trend', 'Inventory_Risk_State', 'Inventory_Risk_Score', 'Inventory_Risk_Tier']

fact_supplier_supply_chain_context
Shape: (405, 135)
Columns:
['Supplier_ID', 'Supplier_Name', 'Observation_Date', 'Supplier_Failure_Probability', 'Failure_Warning_Flag', 'Warning_Severity', 'Risk_Priority_Rank', 'Risk_Priority_Score', 'Supplier_Risk_State', 'Risk_State_Score', 'Deterioration_Signal_Count', 'Severe_Signal_Count', 'Failure_Dimension_Count', 'Material_ID', 'Material_Name', 'Material_Criticality', 'Material_Criticality_Score', 'Safety_Stock', 'Reorder_Point', 'Asset_ID', 'Asset_Name', 'Asset_Type', 'Asset_Criticality', 'Asset_Criticality_Score', 'Operational_Dependency', 'Operational_Dependency_Score', 'Potential_Operational_Consequence', 'Material_Exposure_Status', 'Materials_Supplied', 'Critical_Materials_Supplied', 'Assets_Dependent', 'Critical_Assets_Dependent', 'Critical_Material_Exposure_Ratio', 'Critical_Asset_Exposure_Ratio', 'Material_Criticality_Exposure', 'Asset_Dependency_Exposure', 'Average_Operational_Dependency', 'Supplier_Critical_Material_Exposure', 'Risk_Driver_1', 'Risk_Driver_2', 'Risk_Driver_3', 'Risk_Driver_4', 'Risk_Driver_5', 'Recommended_Intervention', 'PO_Count', 'Ordered_Quantity', 'Received_Quantity', 'Outstanding_Quantity', 'Fulfilled_PO_Count', 'Partial_Fulfilment_Count', 'Outstanding_PO_Count', 'Delivered_PO_Count', 'Late_Delivery_Count', 'Rolling_90D_PO_Count', 'Rolling_90D_Ordered_Quantity', 'Rolling_90D_Received_Quantity', 'Rolling_90D_Outstanding_Quantity', 'Rolling_90D_Fulfilled_PO_Count', 'Rolling_90D_Partial_Fulfilment_Count', 'Rolling_90D_Delivered_PO_Count', 'Rolling_90D_Late_Delivery_Count', 'Fulfilment_Risk_Signal', 'Late_Delivery_Risk_Signal', 'Partial_Fulfilment_Risk_Signal', 'Outstanding_Risk_Signal', 'Supplier_Risk_State_Code', 'Persistent_Deterioration', 'Previous_Risk_State', 'Risk_State_Transition', 'Recent_90D_Fulfilment_Rate', 'Recent_90D_Partial_Fulfilment_Rate', 'Recent_90D_Late_Delivery_Rate', 'Recent_90D_Outstanding_Rate', 'Recent_90D_Average_Delivery_Delay', 'Historical_Fulfilment_Rate', 'Historical_Partial_Fulfilment_Rate', 'Historical_Late_Delivery_Rate', 'Historical_Outstanding_Rate', 'Current_Outstanding_Quantity', 'Supplier_Failure_Label', 'Observation_Year', 'Observation_Month', 'Observation_Quarter', 'Observation_DayOfWeek', 'Fulfilment_Deviation_From_History', 'Late_Delivery_Deviation_From_History', 'Outstanding_Deviation_From_History', 'Partial_Fulfilment_Deviation_From_History', 'Total_Current_Risk_Signals', 'Current_Risk_Signal_Count', 'Outstanding_Quantity_Ratio', 'Rolling_90D_Outstanding_Quantity_Ratio', 'Current_Risk_State_Code', 'Previous_Risk_State_Code', '__driver_score__Fulfilment_Risk_Signal', '__driver_score__Recent_90D_Fulfilment_Rate', '__driver_score__Fulfilment_Deviation_From_History', '__driver_score__Partial_Fulfilment_Risk_Signal', '__driver_score__Recent_90D_Partial_Fulfilment_Rate', '__driver_score__Partial_Fulfilment_Deviation_From_History', '__driver_score__Late_Delivery_Risk_Signal', '__driver_score__Recent_90D_Late_Delivery_Rate', '__driver_score__Late_Delivery_Deviation_From_History', '__driver_score__Outstanding_Risk_Signal', '__driver_score__Recent_90D_Outstanding_Rate', '__driver_score__Outstanding_Deviation_From_History', '__driver_score__Outstanding_Quantity_Ratio', '__driver_score__Current_Outstanding_Quantity', '__driver_score__Rolling_90D_Outstanding_Quantity', '__driver_score__Rolling_90D_PO_Count', '__driver_score__Rolling_90D_Partial_Fulfilment_Count', '__driver_score__Recent_90D_Average_Delivery_Delay', '__driver_score__Total_Current_Risk_Signals', '__driver_score__Risk_State_Score', '__driver_score__Deterioration_Signal_Count', '__driver_score__Severe_Signal_Count', '__driver_score__Failure_Dimension_Count', '__driver_score__Persistent_Deterioration', 'Risk_Driver_1_Feature', 'Risk_Driver_1_Score', 'Risk_Driver_1_Explanation', 'Risk_Driver_2_Feature', 'Risk_Driver_2_Score', 'Risk_Driver_2_Explanation', 'Risk_Driver_3_Feature', 'Risk_Driver_3_Score', 'Risk_Driver_3_Explanation', 'Risk_Driver_4_Feature', 'Risk_Driver_4_Score', 'Risk_Driver_4_Explanation', 'Risk_Driver_5_Feature', 'Risk_Driver_5_Score', 'Risk_Driver_5_Explanation', 'Risk_State_Explanation', 'Overall_Risk_Explanation']

supplier_exposure
Shape: (90, 11)
Columns:
['Supplier_ID', 'Materials_Supplied', 'Critical_Materials_Supplied', 'Assets_Dependent', 'Critical_Assets_Dependent', 'Material_Criticality_Exposure', 'Asset_Dependency_Exposure', 'Average_Operational_Dependency', 'Critical_Material_Exposure_Ratio', 'Critical_Asset_Exposure_Ratio', 'Supplier_Critical_Material_Exposure']

In [28]:
print("asset_master columns:")
print(list(asset_master.columns))

print("\nSample:")
display(asset_master.head())

asset_master columns:
['Asset_ID', 'Asset_Name', 'Business_Unit_ID', 'Business_Unit_Name', 'Asset_Type', 'Location_Type', 'Operational_Criticality', '_Asset_Class']

Sample:

,Asset_ID,Asset_Name,Business_Unit_ID,Business_Unit_Name,Asset_Type,Location_Type,Operational_Criticality,_Asset_Class
0,A001,Offshore Platform A,BU001,Upstream,Offshore Production,Offshore,Critical,OFFSHORE
1,A002,Offshore Platform B,BU001,Upstream,Offshore Production,Offshore,Critical,OFFSHORE
2,A003,Offshore Platform C,BU001,Upstream,Offshore Production,Offshore,Critical,OFFSHORE
3,A004,Pipeline Network Alpha,BU002,Midstream,Pipeline,Onshore,High,GENERAL
4,A005,Pipeline Network Bravo,BU002,Midstream,Pipeline,Onshore,High,GENERAL

In [29]:
# ==========================================================================================
# KEYSTRA — PHASE 15
# RISK PROPAGATION & SUPPLY-CHAIN IMPACT ENGINE
# CORRECTED VERSION
# ==========================================================================================

import pandas as pd
import numpy as np

print("=" * 100)
print("KEYSTRA — PHASE 15")
print("RISK PROPAGATION & SUPPLY-CHAIN IMPACT ENGINE")
print("=" * 100)


# ==========================================================================================
# PHASE 15 — CONFIGURATION
# ==========================================================================================

REFERENCE_DATE = pd.Timestamp("2026-07-31")

print("\nREFERENCE DATE:", REFERENCE_DATE.date())


# ==========================================================================================
# PHASE 15 — INPUT OBJECT VALIDATION
# ==========================================================================================

required_objects = {
    "supplier_alert_explanation": supplier_alert_explanation,
    "supplier_material_asset": supplier_material_asset,
    "fact_purchase_order_line": fact_purchase_order_line,
    "fact_inventory_snapshot": fact_inventory_snapshot,
    "asset_master": asset_master
}

print("\n" + "=" * 100)
print("PHASE 15 — INPUT VALIDATION")
print("=" * 100)

for name, obj in required_objects.items():

    if not isinstance(obj, pd.DataFrame):
        raise TypeError(
            f"{name} is not a pandas DataFrame."
        )

    print(
        f"✓ {name:<40} {obj.shape}"
    )


# ==========================================================================================
# REQUIRED COLUMN VALIDATION
# ==========================================================================================

required_columns = {

    "supplier_alert_explanation": [
        "Early_Warning_ID",
        "Supplier_ID",
        "Supplier_Name",
        "Alert_Severity",
        "Alert_Type",
        "Supplier_Failure_Probability",
        "Supplier_Risk_Priority_Score",
        "Supply_Chain_Exposure_Score",
        "Intervention_Urgency_Score",
        "Early_Warning_Severity_Score",
        "Root_Cause_Category",
        "Potential_Operational_Consequence",
        "Potential_Business_Impact",
        "Recommended_Response"
    ],

    "supplier_material_asset": [
        "Supplier_ID",
        "Material_ID",
        "Material_Name",
        "Material_Criticality",
        "Material_Criticality_Score",
        "Safety_Stock",
        "Reorder_Point",
        "Asset_ID",
        "Asset_Name",
        "Asset_Type",
        "Asset_Criticality",
        "Asset_Criticality_Score",
        "Operational_Dependency_Score",
        "Potential_Operational_Consequence"
    ],

    "fact_purchase_order_line": [
        "PO_Line_ID",
        "Supplier_ID",
        "Material_ID",
        "Asset_ID",
        "Order_Date",
        "PO_Status",
        "Quantity_Ordered",
        "Order_Value_USD",
        "Expected_Delivery_Date",
        "Actual_Delivery_Date",
        "Quantity_Received",
        "Days_Late",
        "Fulfilment_Rate",
        "Outstanding_Quantity",
        "Outstanding_Value_USD"
    ],

    "fact_inventory_snapshot": [
        "Snapshot_Date",
        "Material_ID",
        "Safety_Stock",
        "On_Hand_Quantity",
        "Stockout_Quantity",
        "Stockout_Flag",
        "Low_Stock_Flag",
        "Safety_Stock_Breach_Flag",
        "Critical_Stock_Flag",
        "Inventory_Coverage_Days",
        "Inventory_Risk_Score",
        "Inventory_Risk_Tier"
    ],

    "asset_master": [
        "Asset_ID",
        "Asset_Name",
        "Business_Unit_ID",
        "Business_Unit_Name",
        "Asset_Type",
        "Operational_Criticality"
    ]
}


for name, cols in required_columns.items():

    missing = [
        col
        for col in cols
        if col not in required_objects[name].columns
    ]

    if missing:
        raise ValueError(
            f"{name} is missing required columns: {missing}"
        )


print("\n✓ All required Phase 15 columns available.")


# ==========================================================================================
# PHASE 15 — WORKING COPIES
# ==========================================================================================

alerts = supplier_alert_explanation.copy()
sma = supplier_material_asset.copy()
po_lines = fact_purchase_order_line.copy()
inventory = fact_inventory_snapshot.copy()
assets = asset_master.copy()


# ==========================================================================================
# PHASE 15 — DATA TYPE NORMALISATION
# ==========================================================================================

po_lines["Order_Date"] = pd.to_datetime(
    po_lines["Order_Date"],
    errors="coerce"
)

po_lines["Expected_Delivery_Date"] = pd.to_datetime(
    po_lines["Expected_Delivery_Date"],
    errors="coerce"
)

po_lines["Actual_Delivery_Date"] = pd.to_datetime(
    po_lines["Actual_Delivery_Date"],
    errors="coerce"
)

inventory["Snapshot_Date"] = pd.to_datetime(
    inventory["Snapshot_Date"],
    errors="coerce"
)


numeric_columns = [
    "Supplier_Failure_Probability",
    "Supplier_Risk_Priority_Score",
    "Supply_Chain_Exposure_Score",
    "Intervention_Urgency_Score",
    "Early_Warning_Severity_Score"
]


for col in numeric_columns:

    alerts[col] = pd.to_numeric(
        alerts[col],
        errors="coerce"
    )


# ==========================================================================================
# PHASE 15 — SUPPLIER UNIVERSE
# ==========================================================================================

supplier_universe = alerts[
    [
        "Early_Warning_ID",
        "Supplier_ID",
        "Supplier_Name",
        "Alert_Severity",
        "Alert_Type",
        "Supplier_Failure_Probability",
        "Supplier_Risk_Priority_Score",
        "Supply_Chain_Exposure_Score",
        "Intervention_Urgency_Score",
        "Early_Warning_Severity_Score",
        "Root_Cause_Category",
        "Potential_Operational_Consequence",
        "Potential_Business_Impact",
        "Recommended_Response"
    ]
].copy()


print(
    "\nSupplier population:",
    supplier_universe["Supplier_ID"].nunique()
)


# ==========================================================================================
# PHASE 15 — SUPPLIER → MATERIAL → ASSET DEPENDENCY BASE
# ==========================================================================================

dependency = sma.merge(
    assets[
        [
            "Asset_ID",
            "Business_Unit_ID",
            "Business_Unit_Name",
            "Asset_Type",
            "Operational_Criticality"
        ]
    ],
    on="Asset_ID",
    how="left",
    suffixes=("", "_Master")
)


dependency["Asset_Criticality_Final"] = (
    dependency["Asset_Criticality"]
    .fillna(
        dependency["Operational_Criticality"]
    )
)


dependency["Asset_Criticality_Score_Final"] = pd.to_numeric(
    dependency["Asset_Criticality_Score"],
    errors="coerce"
)


dependency["Operational_Dependency_Score"] = pd.to_numeric(
    dependency["Operational_Dependency_Score"],
    errors="coerce"
)


dependency["Material_Criticality_Score"] = pd.to_numeric(
    dependency["Material_Criticality_Score"],
    errors="coerce"
)


# ==========================================================================================
# DUPLICATE DEPENDENCY CHECK
# ==========================================================================================

dependency_key = [
    "Supplier_ID",
    "Material_ID",
    "Asset_ID"
]

duplicate_dependency_links = (
    dependency.duplicated(
        subset=dependency_key,
        keep=False
    )
)


print("\n" + "=" * 100)
print("PHASE 15 — DEPENDENCY NETWORK")
print("=" * 100)

print(
    "Supplier-material-asset relationships:",
    len(dependency)
)

print(
    "Suppliers represented:",
    dependency["Supplier_ID"].nunique()
)

print(
    "Materials represented:",
    dependency["Material_ID"].nunique()
)

print(
    "Assets represented:",
    dependency["Asset_ID"].nunique()
)

print(
    "Business units represented:",
    dependency["Business_Unit_ID"].nunique()
)

print(
    "Duplicate supplier-material-asset links:",
    duplicate_dependency_links.sum()
)


if duplicate_dependency_links.any():

    raise ValueError(
        "Phase 15 dependency network contains duplicate "
        "Supplier_ID + Material_ID + Asset_ID links. "
        "Resolve these before continuing."
    )

else:

    print(
        "✓ Supplier-material-asset dependency grain is unique."
    )


# ==========================================================================================
# PHASE 15 — CHECK SUPPLIERS WITHOUT DOWNSTREAM DEPENDENCIES
# ==========================================================================================

alerted_suppliers = set(
    supplier_universe["Supplier_ID"]
    .dropna()
    .unique()
)

dependency_suppliers = set(
    dependency["Supplier_ID"]
    .dropna()
    .unique()
)

suppliers_without_dependency = sorted(
    alerted_suppliers - dependency_suppliers
)


print(
    "\nAlerted suppliers without downstream dependency:",
    len(suppliers_without_dependency)
)

if suppliers_without_dependency:

    print(
        "Supplier IDs without propagation links:",
        suppliers_without_dependency
    )

else:

    print(
        "✓ Every alerted supplier has at least one downstream dependency."
    )


# ==========================================================================================
# PHASE 15 — PURCHASE ORDER EXPOSURE
# IMPORTANT CORRECTION:
# PO EXPOSURE IS AGGREGATED AT SUPPLIER + MATERIAL + ASSET GRAIN
# ==========================================================================================

po_ref = po_lines[
    po_lines["Order_Date"] <= REFERENCE_DATE
].copy()


# ------------------------------------------------------------------------------
# UNDERLYING FACT-LEVEL EXPOSURE
# ------------------------------------------------------------------------------

underlying_po_exposure = (
    pd.to_numeric(
        po_ref["Outstanding_Value_USD"],
        errors="coerce"
    )
    .fillna(0)
    .sum()
)


underlying_po_quantity = (
    pd.to_numeric(
        po_ref["Outstanding_Quantity"],
        errors="coerce"
    )
    .fillna(0)
    .sum()
)


print("\n" + "=" * 100)
print("PHASE 15 — UNDERLYING PO EXPOSURE")
print("=" * 100)

print(
    "PO lines in reference period:",
    len(po_ref)
)

print(
    "Underlying outstanding quantity:",
    round(
        underlying_po_quantity,
        2
    )
)

print(
    "Underlying outstanding PO exposure:",
    round(
        underlying_po_exposure,
        2
    )
)


# ------------------------------------------------------------------------------
# CORRECTED GRAIN:
# SUPPLIER + MATERIAL + ASSET
# ------------------------------------------------------------------------------

po_supplier_material_asset = (
    po_ref
    .groupby(
        [
            "Supplier_ID",
            "Material_ID",
            "Asset_ID"
        ],
        as_index=False
    )
    .agg(

        PO_Line_Count=(
            "PO_Line_ID",
            "count"
        ),

        Ordered_Quantity=(
            "Quantity_Ordered",
            "sum"
        ),

        Received_Quantity=(
            "Quantity_Received",
            "sum"
        ),

        Outstanding_Quantity=(
            "Outstanding_Quantity",
            "sum"
        ),

        Order_Value_USD=(
            "Order_Value_USD",
            "sum"
        ),

        Outstanding_Value_USD=(
            "Outstanding_Value_USD",
            "sum"
        ),

        Average_Days_Late=(
            "Days_Late",
            "mean"
        ),

        Average_Fulfilment_Rate=(
            "Fulfilment_Rate",
            "mean"
        )
    )
)


# Numeric cleanup

for col in [
    "PO_Line_Count",
    "Ordered_Quantity",
    "Received_Quantity",
    "Outstanding_Quantity",
    "Order_Value_USD",
    "Outstanding_Value_USD",
    "Average_Days_Late",
    "Average_Fulfilment_Rate"
]:

    po_supplier_material_asset[col] = (
        pd.to_numeric(
            po_supplier_material_asset[col],
            errors="coerce"
        )
        .fillna(0)
    )


# ------------------------------------------------------------------------------
# RECONCILIATION AT AGGREGATED GRAIN
# ------------------------------------------------------------------------------

aggregated_po_exposure = (
    po_supplier_material_asset[
        "Outstanding_Value_USD"
    ].sum()
)


aggregated_po_quantity = (
    po_supplier_material_asset[
        "Outstanding_Quantity"
    ].sum()
)


print("\n" + "=" * 100)
print("PHASE 15 — PO AGGREGATION RECONCILIATION")
print("=" * 100)

print(
    "Underlying fact-level exposure:",
    round(
        underlying_po_exposure,
        2
    )
)

print(
    "Supplier-material-asset exposure:",
    round(
        aggregated_po_exposure,
        2
    )
)

print(
    "Exposure difference:",
    round(
        aggregated_po_exposure
        - underlying_po_exposure,
        2
    )
)

print(
    "Underlying quantity:",
    round(
        underlying_po_quantity,
        2
    )
)

print(
    "Aggregated quantity:",
    round(
        aggregated_po_quantity,
        2
    )
)

print(
    "Quantity difference:",
    round(
        aggregated_po_quantity
        - underlying_po_quantity,
        2
    )
)


if not np.isclose(
    aggregated_po_exposure,
    underlying_po_exposure,
    rtol=1e-9,
    atol=0.01
):

    raise ValueError(
        "PO exposure failed reconciliation after "
        "Supplier + Material + Asset aggregation."
    )


if not np.isclose(
    aggregated_po_quantity,
    underlying_po_quantity,
    rtol=1e-9,
    atol=0.01
):

    raise ValueError(
        "PO outstanding quantity failed reconciliation."
    )


print(
    "✓ PO exposure reconciles at Supplier + Material + Asset grain."
)


# ==========================================================================================
# PHASE 15 — PO DEPENDENCY COVERAGE CHECK
# ==========================================================================================

dependency_keys = dependency[
    [
        "Supplier_ID",
        "Material_ID",
        "Asset_ID"
    ]
].drop_duplicates()


po_keys = po_supplier_material_asset[
    [
        "Supplier_ID",
        "Material_ID",
        "Asset_ID"
    ]
].drop_duplicates()


po_dependency_check = po_keys.merge(
    dependency_keys,
    on=[
        "Supplier_ID",
        "Material_ID",
        "Asset_ID"
    ],
    how="left",
    indicator=True
)


orphan_po_links = po_dependency_check[
    po_dependency_check["_merge"] == "left_only"
].drop(
    columns="_merge"
)


print("\n" + "=" * 100)
print("PHASE 15 — PO → DEPENDENCY COVERAGE")
print("=" * 100)

print(
    "Unique PO supplier-material-asset links:",
    len(po_keys)
)

print(
    "PO links represented in dependency network:",
    len(po_keys) - len(orphan_po_links)
)

print(
    "PO links missing from dependency network:",
    len(orphan_po_links)
)


if len(orphan_po_links) > 0:

    print(
        "\n⚠️ WARNING:",
        len(orphan_po_links),
        "PO links are not represented in the downstream dependency network."
    )

    print(
        "Their exposure will not be included in propagated exposure."
    )

else:

    print(
        "✓ All PO supplier-material-asset links are represented."
    )


# ==========================================================================================
# PHASE 15 — INVENTORY VULNERABILITY
# ==========================================================================================

latest_inventory = (
    inventory[
        inventory["Snapshot_Date"] <= REFERENCE_DATE
    ]
    .sort_values(
        [
            "Material_ID",
            "Snapshot_Date"
        ]
    )
    .groupby(
        "Material_ID",
        as_index=False
    )
    .tail(1)
)


inventory_context = latest_inventory[
    [
        "Material_ID",
        "Snapshot_Date",
        "Safety_Stock",
        "On_Hand_Quantity",
        "Stockout_Quantity",
        "Stockout_Flag",
        "Low_Stock_Flag",
        "Safety_Stock_Breach_Flag",
        "Critical_Stock_Flag",
        "Inventory_Coverage_Days",
        "Inventory_Risk_Score",
        "Inventory_Risk_Tier"
    ]
].copy()


inventory_context = inventory_context.drop_duplicates(
    subset=["Material_ID"],
    keep="last"
)


print(
    "\nLatest inventory snapshots:",
    len(inventory_context)
)


# ==========================================================================================
# PHASE 15 — BUILD PROPAGATION NETWORK
# ==========================================================================================

# IMPORTANT:
# The merge now uses Supplier + Material + Asset.
# This prevents PO exposure from being duplicated across
# multiple downstream assets.

propagation_network = dependency.merge(
    po_supplier_material_asset,
    on=[
        "Supplier_ID",
        "Material_ID",
        "Asset_ID"
    ],
    how="left"
)


propagation_network = propagation_network.merge(
    inventory_context,
    on="Material_ID",
    how="left",
    suffixes=(
        "",
        "_Inventory"
    )
)


propagation_network = propagation_network.merge(
    supplier_universe[
        [
            "Supplier_ID",
            "Early_Warning_ID",
            "Supplier_Name",
            "Alert_Severity",
            "Alert_Type",
            "Supplier_Failure_Probability",
            "Supplier_Risk_Priority_Score",
            "Supply_Chain_Exposure_Score",
            "Intervention_Urgency_Score",
            "Early_Warning_Severity_Score",
            "Root_Cause_Category",
            "Potential_Operational_Consequence",
            "Potential_Business_Impact"
        ]
    ],
    on="Supplier_ID",
    how="left",
    suffixes=(
        "",
        "_Alert"
    )
)


# ==========================================================================================
# PHASE 15 — MISSING EXPOSURE DEFAULTS
# ==========================================================================================

exposure_numeric = [
    "PO_Line_Count",
    "Ordered_Quantity",
    "Received_Quantity",
    "Outstanding_Quantity",
    "Order_Value_USD",
    "Outstanding_Value_USD",
    "Average_Days_Late",
    "Average_Fulfilment_Rate",
    "Stockout_Quantity",
    "Inventory_Coverage_Days",
    "Inventory_Risk_Score"
]


for col in exposure_numeric:

    if col in propagation_network.columns:

        propagation_network[col] = (
            pd.to_numeric(
                propagation_network[col],
                errors="coerce"
            )
            .fillna(0)
        )


binary_columns = [
    "Stockout_Flag",
    "Low_Stock_Flag",
    "Safety_Stock_Breach_Flag",
    "Critical_Stock_Flag"
]


for col in binary_columns:

    if col in propagation_network.columns:

        propagation_network[col] = (
            pd.to_numeric(
                propagation_network[col],
                errors="coerce"
            )
            .fillna(0)
            .clip(0, 1)
        )


# ==========================================================================================
# PHASE 15 — NETWORK EXPOSURE COMPONENTS
# ==========================================================================================

propagation_network["Material_Criticality_Component"] = (
    propagation_network[
        "Material_Criticality_Score"
    ]
    .fillna(0)
    .clip(0, 100)
)


propagation_network["Asset_Criticality_Component"] = (
    propagation_network[
        "Asset_Criticality_Score_Final"
    ]
    .fillna(0)
    .clip(0, 100)
)


propagation_network["Operational_Dependency_Component"] = (
    propagation_network[
        "Operational_Dependency_Score"
    ]
    .fillna(0)
    .clip(0, 100)
)


inventory_risk = (
    propagation_network[
        "Inventory_Risk_Score"
    ]
    .fillna(0)
    .clip(0, 100)
)


stockout_component = (
    propagation_network["Stockout_Flag"] * 100
)


critical_stock_component = (
    propagation_network["Critical_Stock_Flag"] * 100
)


low_stock_component = (
    propagation_network["Low_Stock_Flag"] * 75
)


safety_breach_component = (
    propagation_network["Safety_Stock_Breach_Flag"] * 80
)


propagation_network["Inventory_Vulnerability_Score"] = (
    inventory_risk * 0.40
    + stockout_component * 0.25
    + critical_stock_component * 0.15
    + low_stock_component * 0.10
    + safety_breach_component * 0.10
).clip(0, 100)


# ==========================================================================================
# PHASE 15 — PROCUREMENT EXPOSURE SCORE
# ==========================================================================================

outstanding_value_score = (
    propagation_network[
        "Outstanding_Value_USD"
    ]
    .rank(
        pct=True
    )
    .fillna(0)
    * 100
)


outstanding_quantity_score = (
    propagation_network[
        "Outstanding_Quantity"
    ]
    .rank(
        pct=True
    )
    .fillna(0)
    * 100
)


lateness_score = (
    propagation_network[
        "Average_Days_Late"
    ]
    .clip(
        lower=0
    )
    .rank(
        pct=True
    )
    .fillna(0)
    * 100
)


fulfilment_risk_score = (
    100
    - propagation_network[
        "Average_Fulfilment_Rate"
    ]
).clip(
    0,
    100
)


propagation_network["Procurement_Exposure_Score"] = (
    outstanding_value_score * 0.35
    + outstanding_quantity_score * 0.25
    + lateness_score * 0.20
    + fulfilment_risk_score * 0.20
).clip(
    0,
    100
)


# ==========================================================================================
# PHASE 15 — MATERIAL PROPAGATION SCORE
# ==========================================================================================

propagation_network["Material_Propagation_Score"] = (
    propagation_network[
        "Material_Criticality_Component"
    ] * 0.25

    + propagation_network[
        "Procurement_Exposure_Score"
    ] * 0.20

    + propagation_network[
        "Inventory_Vulnerability_Score"
    ] * 0.25

    + propagation_network[
        "Asset_Criticality_Component"
    ] * 0.15

    + propagation_network[
        "Operational_Dependency_Component"
    ] * 0.15
).clip(
    0,
    100
)


# ==========================================================================================
# PHASE 15 — SUPPLIER FAILURE PROPAGATION
# ==========================================================================================

failure_probability_score = (
    propagation_network[
        "Supplier_Failure_Probability"
    ]
    .fillna(0)
    .clip(0, 1)
    * 100
)


propagation_network["Risk_Propagation_Score"] = (
    failure_probability_score * 0.25

    + propagation_network[
        "Material_Propagation_Score"
    ] * 0.35

    + propagation_network[
        "Inventory_Vulnerability_Score"
    ] * 0.15

    + propagation_network[
        "Asset_Criticality_Component"
    ] * 0.10

    + propagation_network[
        "Operational_Dependency_Component"
    ] * 0.10

    + propagation_network[
        "Procurement_Exposure_Score"
    ] * 0.05
).clip(
    0,
    100
)


# ==========================================================================================
# PHASE 15 — PROPAGATION TIER
# ==========================================================================================

def propagation_tier(score):

    if score >= 80:
        return "Critical Propagation"

    elif score >= 65:
        return "High Propagation"

    elif score >= 45:
        return "Moderate Propagation"

    elif score >= 25:
        return "Low Propagation"

    return "Limited Propagation"


propagation_network["Propagation_Tier"] = (
    propagation_network[
        "Risk_Propagation_Score"
    ]
    .apply(propagation_tier)
)


# ==========================================================================================
# PHASE 15 — IMPACT CLASSIFICATION
# ==========================================================================================

def operational_impact(row):

    if (
        row["Critical_Stock_Flag"] == 1
        and row["Asset_Criticality_Component"] >= 80
    ):

        return "Potential critical asset disruption"

    if (
        row["Stockout_Flag"] == 1
        or row["Safety_Stock_Breach_Flag"] == 1
    ):

        return "Potential material availability disruption"

    if (
        row["Operational_Dependency_Component"] >= 75
    ):

        return "Potential operational constraint"

    if (
        row["Material_Criticality_Component"] >= 75
    ):

        return "Potential critical material disruption"

    return "Potential localized supply-chain disruption"


propagation_network["Propagated_Operational_Impact"] = (
    propagation_network.apply(
        operational_impact,
        axis=1
    )
)


# ==========================================================================================
# PHASE 15 — BUSINESS IMPACT CLASSIFICATION
# ==========================================================================================

def business_impact(row):

    if row["Propagation_Tier"] == "Critical Propagation":

        return (
            "Potential production disruption and "
            "material supply exposure"
        )

    if row["Propagation_Tier"] == "High Propagation":

        return (
            "Potential operational disruption, "
            "procurement pressure and cost exposure"
        )

    if row["Propagation_Tier"] == "Moderate Propagation":

        return (
            "Potential supply continuity and "
            "operational efficiency impact"
        )

    if row["Propagation_Tier"] == "Low Propagation":

        return (
            "Potential localized supply-chain impact"
        )

    return "Limited immediate business impact"


propagation_network["Propagated_Business_Impact"] = (
    propagation_network.apply(
        business_impact,
        axis=1
    )
)


# ==========================================================================================
# PHASE 15 — MANAGEMENT RESPONSE PRIORITY
# ==========================================================================================

def management_priority(row):

    if (
        row["Propagation_Tier"] == "Critical Propagation"
        or row["Alert_Severity"] == "Critical"
    ):

        return (
            "Executive / Supply Chain Leadership"
        )

    if (
        row["Propagation_Tier"] == "High Propagation"
        or row["Alert_Severity"] == "High"
    ):

        return (
            "Supply Chain Risk Management"
        )

    if row["Propagation_Tier"] == "Moderate Propagation":

        return (
            "Procurement / Operations Management"
        )

    return "Supplier Management"


propagation_network["Management_Response_Priority"] = (
    propagation_network.apply(
        management_priority,
        axis=1
    )
)


# ==========================================================================================
# PHASE 15 — PROPAGATION NARRATIVE
# ==========================================================================================

def propagation_narrative(row):

    supplier = row["Supplier_Name"]
    material = row["Material_Name"]
    asset = row["Asset_Name"]
    business_unit = row["Business_Unit_Name"]

    return (
        f"{supplier} presents a "
        f"{row['Propagation_Tier'].lower()} "
        f"risk propagation pathway through {material}. "
        f"The exposure is connected to {asset} within the "
        f"{business_unit} business unit. "
        f"Material criticality, procurement exposure and inventory "
        f"vulnerability indicate "
        f"{row['Propagated_Operational_Impact'].lower()}. "
        f"Management should prioritise "
        f"{row['Management_Response_Priority'].lower()} "
        f"based on the identified supplier failure and "
        f"downstream dependency."
    )


propagation_network["Risk_Propagation_Narrative"] = (
    propagation_network.apply(
        propagation_narrative,
        axis=1
    )
)


# ==========================================================================================
# PHASE 15 — SUPPLIER-LEVEL PROPAGATION AGGREGATION
# ==========================================================================================

supplier_aggregation_linked = (
    propagation_network
    .groupby(
        [
            "Supplier_ID",
            "Supplier_Name",
            "Early_Warning_ID",
            "Alert_Severity",
            "Alert_Type",
            "Supplier_Failure_Probability",
            "Supplier_Risk_Priority_Score",
            "Supply_Chain_Exposure_Score",
            "Intervention_Urgency_Score",
            "Early_Warning_Severity_Score"
        ],
        as_index=False
    )
    .agg(

        Materials_Exposed=(
            "Material_ID",
            "nunique"
        ),

        Critical_Materials_Exposed=(
            "Material_ID",
            lambda x: x[
                propagation_network.loc[
                    x.index,
                    "Material_Criticality_Score"
                ] >= 75
            ].nunique()
        ),

        Assets_Exposed=(
            "Asset_ID",
            "nunique"
        ),

        Critical_Assets_Exposed=(
            "Asset_ID",
            lambda x: x[
                propagation_network.loc[
                    x.index,
                    "Asset_Criticality_Score_Final"
                ] >= 75
            ].nunique()
        ),

        Business_Units_Affected=(
            "Business_Unit_ID",
            "nunique"
        ),

        Outstanding_Quantity_Exposed=(
            "Outstanding_Quantity",
            "sum"
        ),

        Outstanding_Value_USD_Exposed=(
            "Outstanding_Value_USD",
            "sum"
        ),

        Procurement_Exposure_Score=(
            "Procurement_Exposure_Score",
            "mean"
        ),

        Inventory_Vulnerability_Score=(
            "Inventory_Vulnerability_Score",
            "mean"
        ),

        Maximum_Material_Propagation_Score=(
            "Material_Propagation_Score",
            "max"
        ),

        Maximum_Risk_Propagation_Score=(
            "Risk_Propagation_Score",
            "max"
        ),

        Average_Risk_Propagation_Score=(
            "Risk_Propagation_Score",
            "mean"
        ),

        Critical_Propagation_Links=(
            "Risk_Propagation_Score",
            lambda x: (x >= 80).sum()
        ),

        High_Propagation_Links=(
            "Risk_Propagation_Score",
            lambda x: (
                (x >= 65) & (x < 80)
            ).sum()
        ),

        Stockout_Exposed_Materials=(
            "Material_ID",
            lambda x: x[
                propagation_network.loc[
                    x.index,
                    "Stockout_Flag"
                ] == 1
            ].nunique()
        ),

        Safety_Stock_Breach_Materials=(
            "Material_ID",
            lambda x: x[
                propagation_network.loc[
                    x.index,
                    "Safety_Stock_Breach_Flag"
                ] == 1
            ].nunique()
        )
    )
)


# ==========================================================================================
# PHASE 15 — PRESERVE FULL SUPPLIER ALERT POPULATION
# ==========================================================================================

supplier_base = (
    supplier_universe[
        [
            "Supplier_ID",
            "Supplier_Name",
            "Early_Warning_ID",
            "Alert_Severity",
            "Alert_Type",
            "Supplier_Failure_Probability",
            "Supplier_Risk_Priority_Score",
            "Supply_Chain_Exposure_Score",
            "Intervention_Urgency_Score",
            "Early_Warning_Severity_Score"
        ]
    ]
    .drop_duplicates(
        subset=["Supplier_ID"]
    )
    .copy()
)


supplier_aggregation = supplier_base.merge(
    supplier_aggregation_linked,
    on=[
        "Supplier_ID",
        "Supplier_Name",
        "Early_Warning_ID",
        "Alert_Severity",
        "Alert_Type",
        "Supplier_Failure_Probability",
        "Supplier_Risk_Priority_Score",
        "Supply_Chain_Exposure_Score",
        "Intervention_Urgency_Score",
        "Early_Warning_Severity_Score"
    ],
    how="left"
)


# ==========================================================================================
# PHASE 15 — ZERO-EXPOSURE DEFAULTS
# ==========================================================================================

zero_default_columns = [
    "Materials_Exposed",
    "Critical_Materials_Exposed",
    "Assets_Exposed",
    "Critical_Assets_Exposed",
    "Business_Units_Affected",
    "Outstanding_Quantity_Exposed",
    "Outstanding_Value_USD_Exposed",
    "Procurement_Exposure_Score",
    "Inventory_Vulnerability_Score",
    "Maximum_Material_Propagation_Score",
    "Maximum_Risk_Propagation_Score",
    "Average_Risk_Propagation_Score",
    "Critical_Propagation_Links",
    "High_Propagation_Links",
    "Stockout_Exposed_Materials",
    "Safety_Stock_Breach_Materials"
]


for col in zero_default_columns:

    supplier_aggregation[col] = (
        pd.to_numeric(
            supplier_aggregation[col],
            errors="coerce"
        )
        .fillna(0)
    )


# ==========================================================================================
# PHASE 15 — SUPPLIER PROPAGATION TIER
# ==========================================================================================

supplier_aggregation["Propagation_Score"] = (
    supplier_aggregation[
        "Maximum_Risk_Propagation_Score"
    ]
    .fillna(0)
    .clip(0, 100)
)


supplier_aggregation["Propagation_Tier"] = (
    supplier_aggregation[
        "Propagation_Score"
    ]
    .apply(propagation_tier)
)


# ==========================================================================================
# PHASE 15 — SUPPLIER IMPACT CLASSIFICATION
# ==========================================================================================

supplier_aggregation["Operational_Impact"] = np.select(

    [

        (
            supplier_aggregation[
                "Critical_Propagation_Links"
            ] > 0
        ),

        (
            supplier_aggregation[
                "High_Propagation_Links"
            ] > 0
        ),

        (
            supplier_aggregation[
                "Stockout_Exposed_Materials"
            ] > 0
        ),

        (
            supplier_aggregation[
                "Critical_Materials_Exposed"
            ] > 0
        )
    ],

    [

        "Potential critical operational disruption",

        "Potential significant operational disruption",

        "Potential material availability disruption",

        "Potential critical material exposure"
    ],

    default="Potential localized supply-chain impact"
)


# ==========================================================================================
# PHASE 15 — SUPPLIER BUSINESS IMPACT
# ==========================================================================================

supplier_aggregation["Business_Impact"] = np.select(

    [

        supplier_aggregation[
            "Propagation_Tier"
        ].eq("Critical Propagation"),

        supplier_aggregation[
            "Propagation_Tier"
        ].eq("High Propagation"),

        supplier_aggregation[
            "Propagation_Tier"
        ].eq("Moderate Propagation")
    ],

    [

        (
            "Potential production disruption, "
            "emergency procurement and material "
            "continuity exposure"
        ),

        (
            "Potential operational disruption, "
            "procurement pressure and cost exposure"
        ),

        (
            "Potential supply continuity and "
            "operational efficiency impact"
        )
    ],

    default="Limited immediate business impact"
)


# ==========================================================================================
# PHASE 15 — MANAGEMENT RESPONSE
# ==========================================================================================

supplier_aggregation["Management_Response"] = np.select(

    [

        supplier_aggregation[
            "Propagation_Tier"
        ].eq("Critical Propagation"),

        supplier_aggregation[
            "Propagation_Tier"
        ].eq("High Propagation"),

        supplier_aggregation[
            "Propagation_Tier"
        ].eq("Moderate Propagation")
    ],

    [

        (
            "Activate supplier recovery plan; "
            "protect critical materials; assess "
            "alternate sourcing; escalate to "
            "executive supply-chain leadership"
        ),

        (
            "Engage supplier; initiate corrective "
            "action; assess alternate sourcing and "
            "inventory protection"
        ),

        (
            "Increase supplier monitoring; review "
            "material availability and procurement exposure"
        )
    ],

    default="Continue supplier monitoring"
)


# ==========================================================================================
# PHASE 15 — MANAGEMENT ESCALATION
# ==========================================================================================

supplier_aggregation["Management_Escalation"] = np.select(

    [

        supplier_aggregation[
            "Propagation_Tier"
        ].eq("Critical Propagation"),

        supplier_aggregation[
            "Propagation_Tier"
        ].eq("High Propagation"),

        supplier_aggregation[
            "Propagation_Tier"
        ].eq("Moderate Propagation")
    ],

    [

        "Executive / Supply Chain Leadership",

        "Supply Chain Risk Management",

        "Procurement / Operations Management"
    ],

    default="Supplier Management"
)


# ==========================================================================================
# PHASE 15 — SUPPLIER WITHOUT DEPENDENCY FLAG
# ==========================================================================================

supplier_aggregation["Downstream_Dependency_Flag"] = np.where(

    supplier_aggregation[
        "Materials_Exposed"
    ] > 0,

    1,

    0
)


supplier_aggregation["Propagation_Status"] = np.where(

    supplier_aggregation[
        "Downstream_Dependency_Flag"
    ] == 1,

    "Downstream dependency identified",

    "No downstream dependency identified"
)


print("\n" + "=" * 100)
print("PHASE 15 — SUPPLIER-LEVEL PROPAGATION AGGREGATION")
print("=" * 100)

print(
    "Supplier aggregation records:",
    len(supplier_aggregation)
)

print(
    "Unique suppliers aggregated:",
    supplier_aggregation[
        "Supplier_ID"
    ].nunique()
)

print(
    "Alert types available:",
    supplier_aggregation[
        "Alert_Type"
    ].nunique()
)

print(
    "Suppliers without downstream dependency:",
    (
        supplier_aggregation[
            "Downstream_Dependency_Flag"
        ] == 0
    ).sum()
)

print(
    "\n✓ Supplier-level propagation aggregation completed."
)


# ==========================================================================================
# PHASE 15 — PROPAGATION SUMMARY
# ==========================================================================================

phase15_propagation_summary = pd.DataFrame({

    "Metric": [

        "Suppliers assessed",

        "Supplier-material-asset propagation links",

        "Materials exposed",

        "Critical materials exposed",

        "Assets exposed",

        "Critical assets exposed",

        "Business units affected",

        "Suppliers with critical propagation",

        "Suppliers with high propagation",

        "Suppliers with moderate propagation",

        "Suppliers with stockout exposure",

        "Suppliers with safety-stock breach exposure",

        "Suppliers without downstream dependency",

        "Total outstanding quantity exposed",

        "Total outstanding PO value exposed"
    ],

    "Value": [

        supplier_aggregation[
            "Supplier_ID"
        ].nunique(),

        len(propagation_network),

        propagation_network[
            "Material_ID"
        ].nunique(),

        propagation_network.loc[
            propagation_network[
                "Material_Criticality_Score"
            ] >= 75,
            "Material_ID"
        ].nunique(),

        propagation_network[
            "Asset_ID"
        ].nunique(),

        propagation_network.loc[
            propagation_network[
                "Asset_Criticality_Score_Final"
            ] >= 75,
            "Asset_ID"
        ].nunique(),

        propagation_network[
            "Business_Unit_ID"
        ].nunique(),

        (
            supplier_aggregation[
                "Propagation_Tier"
            ]
            == "Critical Propagation"
        ).sum(),

        (
            supplier_aggregation[
                "Propagation_Tier"
            ]
            == "High Propagation"
        ).sum(),

        (
            supplier_aggregation[
                "Propagation_Tier"
            ]
            == "Moderate Propagation"
        ).sum(),

        (
            supplier_aggregation[
                "Stockout_Exposed_Materials"
            ] > 0
        ).sum(),

        (
            supplier_aggregation[
                "Safety_Stock_Breach_Materials"
            ] > 0
        ).sum(),

        (
            supplier_aggregation[
                "Downstream_Dependency_Flag"
            ] == 0
        ).sum(),

        propagation_network[
            "Outstanding_Quantity"
        ].sum(),

        propagation_network[
            "Outstanding_Value_USD"
        ].sum()
    ]
})


# ==========================================================================================
# PHASE 15 — PROPAGATION TIER DISTRIBUTION
# ==========================================================================================

phase15_propagation_distribution = (
    supplier_aggregation[
        "Propagation_Tier"
    ]
    .value_counts()
    .rename_axis(
        "Propagation_Tier"
    )
    .reset_index(
        name="Supplier_Count"
    )
)


phase15_propagation_distribution["Percentage"] = (
    phase15_propagation_distribution[
        "Supplier_Count"
    ]
    / len(supplier_aggregation)
    * 100
).round(2)


# ==========================================================================================
# PHASE 15 — CRITICAL PROPAGATION
# ==========================================================================================

phase15_critical_propagation = (
    supplier_aggregation[
        supplier_aggregation[
            "Propagation_Tier"
        ]
        == "Critical Propagation"
    ]
    .sort_values(
        [
            "Propagation_Score",
            "Outstanding_Value_USD_Exposed"
        ],
        ascending=False
    )
    .reset_index(
        drop=True
    )
)


# ==========================================================================================
# PHASE 15 — BUSINESS UNIT IMPACT
# ==========================================================================================

phase15_business_unit_impact = (
    propagation_network
    .groupby(
        [
            "Business_Unit_ID",
            "Business_Unit_Name"
        ],
        as_index=False
    )
    .agg(

        Suppliers_Exposed=(
            "Supplier_ID",
            "nunique"
        ),

        Materials_Exposed=(
            "Material_ID",
            "nunique"
        ),

        Critical_Materials_Exposed=(
            "Material_ID",
            lambda x: x[
                propagation_network.loc[
                    x.index,
                    "Material_Criticality_Score"
                ] >= 75
            ].nunique()
        ),

        Assets_Exposed=(
            "Asset_ID",
            "nunique"
        ),

        Critical_Assets_Exposed=(
            "Asset_ID",
            lambda x: x[
                propagation_network.loc[
                    x.index,
                    "Asset_Criticality_Score_Final"
                ] >= 75
            ].nunique()
        ),

        Outstanding_Value_USD=(
            "Outstanding_Value_USD",
            "sum"
        ),

        Average_Propagation_Score=(
            "Risk_Propagation_Score",
            "mean"
        ),

        Maximum_Propagation_Score=(
            "Risk_Propagation_Score",
            "max"
        )
    )
    .sort_values(
        "Maximum_Propagation_Score",
        ascending=False
    )
    .reset_index(
        drop=True
    )
)


# ==========================================================================================
# PHASE 15 — MATERIAL IMPACT RANKING
# ==========================================================================================

phase15_material_impact = (
    propagation_network
    .groupby(
        [
            "Material_ID",
            "Material_Name",
            "Material_Criticality"
        ],
        as_index=False
    )
    .agg(

        Suppliers_Exposed=(
            "Supplier_ID",
            "nunique"
        ),

        Assets_Exposed=(
            "Asset_ID",
            "nunique"
        ),

        Business_Units_Affected=(
            "Business_Unit_ID",
            "nunique"
        ),

        Outstanding_Value_USD=(
            "Outstanding_Value_USD",
            "sum"
        ),

        Outstanding_Quantity=(
            "Outstanding_Quantity",
            "sum"
        ),

        Inventory_Vulnerability_Score=(
            "Inventory_Vulnerability_Score",
            "max"
        ),

        Risk_Propagation_Score=(
            "Risk_Propagation_Score",
            "max"
        )
    )
    .sort_values(
        "Risk_Propagation_Score",
        ascending=False
    )
    .reset_index(
        drop=True
    )
)


# ==========================================================================================
# PHASE 15 — FINAL PROPAGATION OBJECT
# ==========================================================================================

phase15_risk_propagation = (
    propagation_network.copy()
)


# ==========================================================================================
# PHASE 15 — FINAL EXPOSURE RECONCILIATION
# ==========================================================================================

phase15_final_exposure = (
    phase15_risk_propagation[
        "Outstanding_Value_USD"
    ].sum()
)


phase15_final_quantity = (
    phase15_risk_propagation[
        "Outstanding_Quantity"
    ].sum()
)


print("\n" + "=" * 100)
print("PHASE 15 — FINAL EXPOSURE RECONCILIATION")
print("=" * 100)

print(
    "Underlying PO exposure:",
    round(
        underlying_po_exposure,
        2
    )
)

print(
    "Phase 15 propagated exposure:",
    round(
        phase15_final_exposure,
        2
    )
)

print(
    "Exposure difference:",
    round(
        phase15_final_exposure
        - underlying_po_exposure,
        2
    )
)

print(
    "Exposure ratio:",
    round(
        phase15_final_exposure
        / underlying_po_exposure,
        6
    )
)

print(
    "\nUnderlying PO quantity:",
    round(
        underlying_po_quantity,
        2
    )
)

print(
    "Phase 15 propagated quantity:",
    round(
        phase15_final_quantity,
        2
    )
)

print(
    "Quantity difference:",
    round(
        phase15_final_quantity
        - underlying_po_quantity,
        2
    )
)


# NOTE:
# If orphan PO links exist, Phase 15 propagated exposure may be lower than
# underlying exposure because those PO links are not represented in the
# downstream dependency network.
#
# What must NEVER happen is Phase 15 exposure being greater than underlying
# exposure due to duplicated Supplier + Material relationships.

if phase15_final_exposure > underlying_po_exposure + 0.01:

    raise ValueError(
        "CRITICAL: Phase 15 exposure exceeds underlying PO exposure. "
        "This indicates duplicate financial propagation."
    )


if phase15_final_quantity > underlying_po_quantity + 0.01:

    raise ValueError(
        "CRITICAL: Phase 15 outstanding quantity exceeds underlying PO quantity."
    )


print(
    "\n✓ Phase 15 does not inflate underlying PO exposure."
)


# ==========================================================================================
# PHASE 15 — FINAL VALIDATION
# ==========================================================================================

print("\n" + "=" * 100)
print("PHASE 15 — FINAL VALIDATION")
print("=" * 100)

validation_results = []


validation_results.append([
    "Supplier population preserved",

    supplier_aggregation[
        "Supplier_ID"
    ].nunique()
    ==
    alerts[
        "Supplier_ID"
    ].nunique()
])


validation_results.append([
    "Supplier IDs unique in aggregation",

    supplier_aggregation[
        "Supplier_ID"
    ].is_unique
])


validation_results.append([
    "Propagation scores within 0–100",

    phase15_risk_propagation[
        "Risk_Propagation_Score"
    ]
    .between(
        0,
        100
    )
    .all()
])


validation_results.append([
    "Material propagation scores within 0–100",

    phase15_risk_propagation[
        "Material_Propagation_Score"
    ]
    .between(
        0,
        100
    )
    .all()
])


validation_results.append([
    "Inventory vulnerability scores within 0–100",

    phase15_risk_propagation[
        "Inventory_Vulnerability_Score"
    ]
    .between(
        0,
        100
    )
    .all()
])


validation_results.append([
    "Procurement exposure scores within 0–100",

    phase15_risk_propagation[
        "Procurement_Exposure_Score"
    ]
    .between(
        0,
        100
    )
    .all()
])


validation_results.append([
    "Propagation tiers populated",

    phase15_risk_propagation[
        "Propagation_Tier"
    ]
    .notna()
    .all()
])


validation_results.append([
    "Operational impacts populated",

    phase15_risk_propagation[
        "Propagated_Operational_Impact"
    ]
    .notna()
    .all()
])


validation_results.append([
    "Business impacts populated",

    phase15_risk_propagation[
        "Propagated_Business_Impact"
    ]
    .notna()
    .all()
])


validation_results.append([
    "Management priorities populated",

    phase15_risk_propagation[
        "Management_Response_Priority"
    ]
    .notna()
    .all()
])


validation_results.append([
    "Business-unit mapping complete",

    phase15_risk_propagation[
        "Business_Unit_Name"
    ]
    .notna()
    .all()
])


validation_results.append([
    "No duplicate supplier-material-asset links",

    ~phase15_risk_propagation[
        [
            "Supplier_ID",
            "Material_ID",
            "Asset_ID"
        ]
    ]
    .duplicated()
    .any()
])


validation_results.append([
    "Phase 15 exposure does not exceed underlying PO exposure",

    phase15_final_exposure
    <=
    underlying_po_exposure + 0.01
])


validation_results.append([
    "Phase 15 quantity does not exceed underlying PO quantity",

    phase15_final_quantity
    <=
    underlying_po_quantity + 0.01
])


validation_results.append([
    "PO aggregation reconciles to underlying fact",

    np.isclose(
        aggregated_po_exposure,
        underlying_po_exposure,
        rtol=1e-9,
        atol=0.01
    )
])


phase15_validation_summary = pd.DataFrame(
    validation_results,
    columns=[
        "Validation",
        "Status"
    ]
)


phase15_validation_summary["Status"] = (
    phase15_validation_summary[
        "Status"
    ]
    .map({
        True: "PASS",
        False: "FAIL"
    })
)


display(
    phase15_validation_summary
)


# ==========================================================================================
# PHASE 15 — FINAL SUMMARY
# ==========================================================================================

print("\n" + "=" * 100)
print("PHASE 15 — FINAL SUMMARY")
print("=" * 100)


print(
    "Suppliers assessed                  :",
    supplier_aggregation[
        "Supplier_ID"
    ].nunique()
)


print(
    "Propagation links                   :",
    len(phase15_risk_propagation)
)


print(
    "Critical propagation suppliers      :",
    (
        supplier_aggregation[
            "Propagation_Tier"
        ]
        == "Critical Propagation"
    ).sum()
)


print(
    "High propagation suppliers          :",
    (
        supplier_aggregation[
            "Propagation_Tier"
        ]
        == "High Propagation"
    ).sum()
)


print(
    "Moderate propagation suppliers      :",
    (
        supplier_aggregation[
            "Propagation_Tier"
        ]
        == "Moderate Propagation"
    ).sum()
)


print(
    "Materials exposed                   :",
    propagation_network[
        "Material_ID"
    ].nunique()
)


print(
    "Assets exposed                      :",
    propagation_network[
        "Asset_ID"
    ].nunique()
)


print(
    "Business units affected             :",
    propagation_network[
        "Business_Unit_ID"
    ].nunique()
)


print(
    "Outstanding quantity exposed        :",
    round(
        phase15_final_quantity,
        2
    )
)


print(
    "Outstanding PO value exposed (USD)  :",
    round(
        phase15_final_exposure,
        2
    )
)


print(
    "Underlying PO exposure (USD)        :",
    round(
        underlying_po_exposure,
        2
    )
)


print(
    "Exposure ratio                      :",
    round(
        phase15_final_exposure
        / underlying_po_exposure,
        6
    )
)


print(
    "Suppliers without downstream dependency:",
    (
        supplier_aggregation[
            "Downstream_Dependency_Flag"
        ] == 0
    ).sum()
)


print(
    "Final propagation records           :",
    len(phase15_risk_propagation)
)


# ==========================================================================================
# PHASE 15 — FINAL OBJECTS
# ==========================================================================================

print("\n" + "=" * 100)
print("PHASE 15 — FINAL OBJECTS")
print("=" * 100)


print("""
    phase15_risk_propagation
    supplier_aggregation
    phase15_propagation_summary
    phase15_propagation_distribution
    phase15_critical_propagation
    phase15_business_unit_impact
    phase15_material_impact
    phase15_validation_summary
""")


# ==========================================================================================
# PHASE 15 — TOP PROPAGATED RISKS
# ==========================================================================================

print("\n" + "=" * 100)
print("PHASE 15 — TOP PROPAGATED RISKS")
print("=" * 100)


display(

    supplier_aggregation[
        [
            "Supplier_ID",
            "Supplier_Name",
            "Alert_Severity",
            "Supplier_Failure_Probability",
            "Materials_Exposed",
            "Critical_Materials_Exposed",
            "Assets_Exposed",
            "Critical_Assets_Exposed",
            "Business_Units_Affected",
            "Outstanding_Value_USD_Exposed",
            "Propagation_Score",
            "Propagation_Tier",
            "Propagation_Status",
            "Operational_Impact",
            "Business_Impact",
            "Management_Response"
        ]
    ]
    .sort_values(
        "Propagation_Score",
        ascending=False
    )
    .head(20)
    .reset_index(
        drop=True
    )
)


# ==========================================================================================
# PHASE 15 — BUSINESS UNIT IMPACT VIEW
# ==========================================================================================

print("\n" + "=" * 100)
print("PHASE 15 — BUSINESS UNIT PROPAGATION")
print("=" * 100)


display(
    phase15_business_unit_impact
)


# ==========================================================================================
# PHASE 15 — SUPPLIER COVERAGE VIEW
# ==========================================================================================

print("\n" + "=" * 100)
print("PHASE 15 — SUPPLIER COVERAGE")
print("=" * 100)


supplier_coverage_view = (
    supplier_aggregation[
        [
            "Supplier_ID",
            "Supplier_Name",
            "Alert_Severity",
            "Supplier_Failure_Probability",
            "Materials_Exposed",
            "Assets_Exposed",
            "Propagation_Score",
            "Propagation_Tier",
            "Propagation_Status"
        ]
    ]
    .sort_values(
        [
            "Materials_Exposed",
            "Propagation_Score"
        ],
        ascending=False
    )
    .reset_index(
        drop=True
    )
)


display(
    supplier_coverage_view
)


# ==========================================================================================
# PHASE 15 — EXPOSURE INTEGRITY REPORT
# ==========================================================================================

phase15_exposure_integrity = pd.DataFrame({

    "Metric": [
        "Underlying PO outstanding exposure",
        "Aggregated Supplier-Material-Asset exposure",
        "Final Phase 15 propagated exposure",
        "Underlying PO outstanding quantity",
        "Final Phase 15 propagated quantity",
        "PO dependency orphan links",
        "Exposure ratio"
    ],

    "Value": [
        underlying_po_exposure,
        aggregated_po_exposure,
        phase15_final_exposure,
        underlying_po_quantity,
        phase15_final_quantity,
        len(orphan_po_links),
        (
            phase15_final_exposure
            / underlying_po_exposure
            if underlying_po_exposure != 0
            else np.nan
        )
    ]
})


print("\n" + "=" * 100)
print("PHASE 15 — EXPOSURE INTEGRITY REPORT")
print("=" * 100)


display(
    phase15_exposure_integrity
)


# ==========================================================================================
# PHASE 15 — COMPLETION
# ==========================================================================================

if (
    phase15_validation_summary[
        "Status"
    ]
    == "PASS"
).all():

    print("\n" + "=" * 100)
    print("✓ PHASE 15 COMPLETED SUCCESSFULLY")
    print("=" * 100)

else:

    failed = phase15_validation_summary[
        phase15_validation_summary[
            "Status"
        ] != "PASS"
    ]

    print("\n⚠️ PHASE 15 VALIDATION ISSUES DETECTED")

    display(
        failed
    )

====================================================================================================
KEYSTRA — PHASE 15
RISK PROPAGATION & SUPPLY-CHAIN IMPACT ENGINE
====================================================================================================

REFERENCE DATE: 2026-07-31

====================================================================================================
PHASE 15 — INPUT VALIDATION
====================================================================================================
✓ supplier_alert_explanation               (90, 46)
✓ supplier_material_asset                  (407, 16)
✓ fact_purchase_order_line                 (40000, 19)
✓ fact_inventory_snapshot                  (100380, 25)
✓ asset_master                             (13, 8)

✓ All required Phase 15 columns available.

Supplier population: 90

====================================================================================================
PHASE 15 — DEPENDENCY NETWORK
====================================================================================================
Supplier-material-asset relationships: 407
Suppliers represented: 90
Materials represented: 60
Assets represented: 13
Business units represented: 5
Duplicate supplier-material-asset links: 0
✓ Supplier-material-asset dependency grain is unique.

Alerted suppliers without downstream dependency: 0
✓ Every alerted supplier has at least one downstream dependency.

====================================================================================================
PHASE 15 — UNDERLYING PO EXPOSURE
====================================================================================================
PO lines in reference period: 40000
Underlying outstanding quantity: 622917
Underlying outstanding PO exposure: 4050234052.12

====================================================================================================
PHASE 15 — PO AGGREGATION RECONCILIATION
====================================================================================================
Underlying fact-level exposure: 4050234052.12
Supplier-material-asset exposure: 4050234052.12
Exposure difference: -0.0
Underlying quantity: 622917
Aggregated quantity: 622917
Quantity difference: 0
✓ PO exposure reconciles at Supplier + Material + Asset grain.

====================================================================================================
PHASE 15 — PO → DEPENDENCY COVERAGE
====================================================================================================
Unique PO supplier-material-asset links: 407
PO links represented in dependency network: 407
PO links missing from dependency network: 0
✓ All PO supplier-material-asset links are represented.

Latest inventory snapshots: 60

====================================================================================================
PHASE 15 — SUPPLIER-LEVEL PROPAGATION AGGREGATION
====================================================================================================
Supplier aggregation records: 90
Unique suppliers aggregated: 90
Alert types available: 6
Suppliers without downstream dependency: 2

✓ Supplier-level propagation aggregation completed.

====================================================================================================
PHASE 15 — FINAL EXPOSURE RECONCILIATION
====================================================================================================
Underlying PO exposure: 4050234052.12
Phase 15 propagated exposure: 4050234052.12
Exposure difference: 0.0
Exposure ratio: 1.0

Underlying PO quantity: 622917
Phase 15 propagated quantity: 622917
Quantity difference: 0

✓ Phase 15 does not inflate underlying PO exposure.

====================================================================================================
PHASE 15 — FINAL VALIDATION
====================================================================================================

                                           Validation Status
0                       Supplier population preserved   PASS
1                  Supplier IDs unique in aggregation   PASS
2                     Propagation scores within 0–100   PASS
3            Material propagation scores within 0–100   PASS
4         Inventory vulnerability scores within 0–100   PASS
5            Procurement exposure scores within 0–100   PASS
6                         Propagation tiers populated   PASS
7                       Operational impacts populated   PASS
8                          Business impacts populated   PASS
9                     Management priorities populated   PASS
10                     Business-unit mapping complete   PASS
11         No duplicate supplier-material-asset links   PASS
12  Phase 15 exposure does not exceed underlying P...   PASS
13  Phase 15 quantity does not exceed underlying P...   PASS
14       PO aggregation reconciles to underlying fact   PASS

====================================================================================================
PHASE 15 — FINAL SUMMARY
====================================================================================================
Suppliers assessed                  : 90
Propagation links                   : 407
Critical propagation suppliers      : 20
High propagation suppliers          : 27
Moderate propagation suppliers      : 33
Materials exposed                   : 60
Assets exposed                      : 13
Business units affected             : 5
Outstanding quantity exposed        : 622917
Outstanding PO value exposed (USD)  : 4050234052.12
Underlying PO exposure (USD)        : 4050234052.12
Exposure ratio                      : 1.0
Suppliers without downstream dependency: 2
Final propagation records           : 407

====================================================================================================
PHASE 15 — FINAL OBJECTS
====================================================================================================

    phase15_risk_propagation
    supplier_aggregation
    phase15_propagation_summary
    phase15_propagation_distribution
    phase15_critical_propagation
    phase15_business_unit_impact
    phase15_material_impact
    phase15_validation_summary


====================================================================================================
PHASE 15 — TOP PROPAGATED RISKS
====================================================================================================

,Supplier_ID,Supplier_Name,Alert_Severity,Supplier_Failure_Probability,Materials_Exposed,Critical_Materials_Exposed,Assets_Exposed,Critical_Assets_Exposed,Business_Units_Affected,Outstanding_Value_USD_Exposed,Propagation_Score,Propagation_Tier,Propagation_Status,Operational_Impact,Business_Impact,Management_Response
0,S081,SunCore Energy Technologies Ltd.,Critical,0.99,3.0,1.0,5.0,5.0,4.0,3.164564e+07,94.915948,Critical Propagation,Downstream dependency identified,Potential critical operational disruption,"Potential production disruption, emergency pro...",Activate supplier recovery plan; protect criti...
1,S001,Apex Rotating Systems Ltd.,High,0.93,1.0,1.0,2.0,2.0,2.0,3.299047e+07,92.093899,Critical Propagation,Downstream dependency identified,Potential critical operational disruption,"Potential production disruption, emergency pro...",Activate supplier recovery plan; protect criti...
2,S087,Continental Industrial Services Ltd.,Critical,0.99,2.0,2.0,5.0,5.0,4.0,5.911916e+07,91.844688,Critical Propagation,Downstream dependency identified,Potential critical operational disruption,"Potential production disruption, emergency pro...",Activate supplier recovery plan; protect criti...
3,S047,DeltaFlow Technologies Ltd.,High,0.90,1.0,1.0,2.0,2.0,1.0,4.562273e+08,91.803405,Critical Propagation,Downstream dependency identified,Potential critical operational disruption,"Potential production disruption, emergency pro...",Activate supplier recovery plan; protect criti...
4,S054,Industrial Supply Partners Ltd.,High,0.92,5.0,2.0,8.0,8.0,5.0,4.481707e+07,90.021108,Critical Propagation,Downstream dependency identified,Potential critical operational disruption,"Potential production disruption, emergency pro...",Activate supplier recovery plan; protect criti...
5,S013,Westfield Industrial Engineering Ltd.,High,0.98,2.0,0.0,5.0,5.0,4.0,9.311741e+05,86.206495,Critical Propagation,Downstream dependency identified,Potential critical operational disruption,"Potential production disruption, emergency pro...",Activate supplier recovery plan; protect criti...
6,S069,WestAfrica Chemical Solutions Ltd.,High,0.91,1.0,0.0,2.0,2.0,2.0,5.158795e+06,86.193390,Critical Propagation,Downstream dependency identified,Potential critical operational disruption,"Potential production disruption, emergency pro...",Activate supplier recovery plan; protect criti...
7,S058,Nexus Industrial Supply Ltd.,Critical,0.99,3.0,1.0,7.0,7.0,5.0,3.416498e+07,85.965978,Critical Propagation,Downstream dependency identified,Potential critical operational disruption,"Potential production disruption, emergency pro...",Activate supplier recovery plan; protect criti...
8,S063,General Process Solutions Ltd.,Moderate,0.68,1.0,1.0,2.0,2.0,2.0,2.768565e+07,85.765731,Critical Propagation,Downstream dependency identified,Potential critical operational disruption,"Potential production disruption, emergency pro...",Activate supplier recovery plan; protect criti...
9,S007,Prime Industrial Machinery Ltd.,Moderate,0.67,1.0,1.0,3.0,3.0,3.0,3.537636e+07,85.706443,Critical Propagation,Downstream dependency identified,Potential critical operational disruption,"Potential production disruption, emergency pro...",Activate supplier recovery plan; protect criti...
10,S018,Crown Electrical Technologies Ltd.,High,0.97,3.0,0.0,6.0,6.0,5.0,1.729316e+06,85.290845,Critical Propagation,Downstream dependency identified,Potential critical operational disruption,"Potential production disruption, emergency pro...",Activate supplier recovery plan; protect criti...
11,S055,Process Materials Solutions Ltd.,Critical,0.99,4.0,1.0,7.0,7.0,5.0,1.563864e+08,84.590623,Critical Propagation,Downstream dependency identified,Potential critical operational disruption,"Potential production disruption, emergency pro...",Activate supplier recovery plan; protect criti...
12,S089,Nexus Energy Equipment Solutions Ltd.,High,0.90,5.0,0.0,8.0,8.0,4.0,2.887152e+06,84.570187,Critical Propagation,Downstream dependency identified,Potential critical operational disruption,"Potential production disruption, emergency pro...",Activate supplier recovery plan; protect criti...
13,S021,PrimeVolt Engineering Services Ltd.,Moderate,0.65,1.0,1.0,2.0,2.0,2.0,1.071616e+08,83.290837,Critical Propagation,Downstream dependency identified,Potential critical operational disruption,"Potential production disruption, emergency pro...",Activate supplier recovery plan; protect criti...
14,S090,Frontier Industrial Technologies Ltd.,High,0.86,2.0,0.0,3.0,3.0,2.0,8.158763e+05,82.237324,Critical Propagation,Downstream dependency identified,Potential critical operational disruption,"Potential production disruption, emergency pro...",Activate supplier recovery plan; protect criti...
15,S033,ProSense Industrial Controls Ltd.,Moderate,0.64,5.0,4.0,9.0,9.0,4.0,5.877389e+07,81.627293,Critical Propagation,Downstream dependency identified,Potential critical operational disruption,"Potential production disruption, emergency pro...",Activate supplier recovery plan; protect criti...
16,S011,BluePeak Mechanical Systems Ltd.,High,0.79,1.0,0.0,2.0,2.0,2.0,1.482090e+06,81.611955,Critical Propagation,Downstream dependency identified,Potential critical operational disruption,"Potential production disruption, emergency pro...",Activate supplier recovery plan; protect criti...
17,S061,MetroProcess Supplies Ltd.,High,1.00,1.0,0.0,1.0,1.0,1.0,2.788544e+04,81.570898,Critical Propagation,Downstream dependency identified,Potential critical operational disruption,"Potential production disruption, emergency pro...",Activate supplier recovery plan; protect criti...
18,S035,Advanced Process Instruments Ltd.,Critical,0.98,3.0,1.0,7.0,7.0,4.0,2.190585e+06,81.410060,Critical Propagation,Downstream dependency identified,Potential critical operational disruption,"Potential production disruption, emergency pro...",Activate supplier recovery plan; protect criti...
19,S030,Axis Process Controls Ltd.,Critical,0.98,1.0,1.0,3.0,3.0,2.0,5.298082e+05,80.440263,Critical Propagation,Downstream dependency identified,Potential critical operational disruption,"Potential production disruption, emergency pro...",Activate supplier recovery plan; protect criti...

====================================================================================================
PHASE 15 — BUSINESS UNIT PROPAGATION
====================================================================================================

,Business_Unit_ID,Business_Unit_Name,Suppliers_Exposed,Materials_Exposed,Critical_Materials_Exposed,Assets_Exposed,Critical_Assets_Exposed,Outstanding_Value_USD,Average_Propagation_Score,Maximum_Propagation_Score
0,BU001,Upstream,48,27,11,3,3,1.567159e+09,60.699594,94.915948
1,BU004,LNG,32,14,8,1,1,3.849953e+08,58.085866,94.433654
2,BU003,Downstream,42,20,10,2,2,4.071776e+08,60.858657,94.227736
3,BU005,Renewables,66,31,15,3,3,8.412779e+08,61.953921,92.093899
4,BU002,Midstream,70,33,10,4,4,8.496246e+08,56.944607,91.844688

====================================================================================================
PHASE 15 — SUPPLIER COVERAGE
====================================================================================================

,Supplier_ID,Supplier_Name,Alert_Severity,Supplier_Failure_Probability,Materials_Exposed,Assets_Exposed,Propagation_Score,Propagation_Tier,Propagation_Status
0,S054,Industrial Supply Partners Ltd.,High,0.92,5.0,8.0,90.021108,Critical Propagation,Downstream dependency identified
1,S089,Nexus Energy Equipment Solutions Ltd.,High,0.90,5.0,8.0,84.570187,Critical Propagation,Downstream dependency identified
2,S033,ProSense Industrial Controls Ltd.,Moderate,0.64,5.0,9.0,81.627293,Critical Propagation,Downstream dependency identified
3,S017,VoltEdge Engineering Ltd.,Moderate,0.63,5.0,11.0,70.922295,High Propagation,Downstream dependency identified
4,S086,Integrated Energy Supply Solutions Ltd.,High,0.55,5.0,9.0,61.695379,Moderate Propagation,Downstream dependency identified
...,...,...,...,...,...,...,...,...,...
85,S052,HighPoint Valve Engineering Ltd.,Low,0.20,1.0,3.0,37.188148,Low Propagation,Downstream dependency identified
86,S070,Advanced Lubricants & Chemicals Ltd.,Low,0.00,1.0,2.0,35.740175,Low Propagation,Downstream dependency identified
87,S068,PrimeLube Energy Services Ltd.,Low,0.02,1.0,1.0,34.390067,Low Propagation,Downstream dependency identified
88,S045,PrimeFlow Industrial Solutions Ltd.,No Current Warning,NaN,0.0,0.0,0.000000,Limited Propagation,No downstream dependency identified
89,S085,WindSun Energy Systems Ltd.,No Current Warning,NaN,0.0,0.0,0.000000,Limited Propagation,No downstream dependency identified

====================================================================================================
PHASE 15 — EXPOSURE INTEGRITY REPORT
====================================================================================================

                                        Metric         Value
0           Underlying PO outstanding exposure  4.050234e+09
1  Aggregated Supplier-Material-Asset exposure  4.050234e+09
2           Final Phase 15 propagated exposure  4.050234e+09
3           Underlying PO outstanding quantity  6.229170e+05
4           Final Phase 15 propagated quantity  6.229170e+05
5                   PO dependency orphan links  0.000000e+00
6                               Exposure ratio  1.000000e+00

====================================================================================================
✓ PHASE 15 COMPLETED SUCCESSFULLY
====================================================================================================

In [31]:
# ==================================================================================================
# KEYSTRA — PHASE 16
# EARLY-WARNING, RISK PRIORITISATION & MANAGEMENT ACTION ENGINE
# FINAL ANALYTICAL STAGE
# ==================================================================================================

import pandas as pd
import numpy as np
from datetime import datetime

print("=" * 100)
print("KEYSTRA — PHASE 16")
print("EARLY-WARNING, RISK PRIORITISATION & MANAGEMENT ACTION ENGINE")
print("FINAL ANALYTICAL STAGE")
print("=" * 100)

REFERENCE_DATE = pd.Timestamp("2026-07-31")

# --------------------------------------------------------------------------------------------------
# 1. INPUT VALIDATION
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 100)
print("PHASE 16 — INPUT VALIDATION")
print("=" * 100)

required_input_columns = [
    "Supplier_ID",
    "Supplier_Name",
    "Supplier_Failure_Probability",
    "Propagation_Score",
    "Outstanding_Value_USD_Exposed",
    "Materials_Exposed",
    "Critical_Materials_Exposed",
    "Assets_Exposed",
    "Critical_Assets_Exposed",
    "Business_Units_Affected"
]

missing = [c for c in required_input_columns if c not in supplier_aggregation.columns]

if missing:
    raise ValueError(
        f"Phase 16 cannot continue. Missing required columns: {missing}"
    )

phase16_base = supplier_aggregation.copy()

print(f"✓ supplier_aggregation available {phase16_base.shape}")
print("✓ All required Phase 15 columns available.")

# --------------------------------------------------------------------------------------------------
# 2. DATA CLEANING / STANDARDISATION
# --------------------------------------------------------------------------------------------------

numeric_columns = [
    "Supplier_Failure_Probability",
    "Propagation_Score",
    "Outstanding_Value_USD_Exposed",
    "Materials_Exposed",
    "Critical_Materials_Exposed",
    "Assets_Exposed",
    "Critical_Assets_Exposed",
    "Business_Units_Affected"
]

for col in numeric_columns:
    phase16_base[col] = pd.to_numeric(
        phase16_base[col], errors="coerce"
    ).fillna(0)

phase16_base["Supplier_Failure_Probability"] = (
    phase16_base["Supplier_Failure_Probability"].clip(0, 1)
)

phase16_base["Propagation_Score"] = (
    phase16_base["Propagation_Score"].clip(0, 100)
)

phase16_base["Outstanding_Value_USD_Exposed"] = (
    phase16_base["Outstanding_Value_USD_Exposed"].clip(lower=0)
)

# --------------------------------------------------------------------------------------------------
# 3. EXPOSURE NORMALISATION
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 100)
print("PHASE 16 — EXPOSURE NORMALISATION")
print("=" * 100)

max_exposure = phase16_base["Outstanding_Value_USD_Exposed"].max()

if max_exposure > 0:
    phase16_base["Exposure_Score"] = (
        phase16_base["Outstanding_Value_USD_Exposed"] /
        max_exposure
    ) * 100
else:
    phase16_base["Exposure_Score"] = 0

phase16_base["Exposure_Score"] = (
    phase16_base["Exposure_Score"].clip(0, 100)
)

print(
    f"Maximum supplier exposure: "
    f"${max_exposure:,.2f}"
)

print("✓ Exposure score calculated.")

# --------------------------------------------------------------------------------------------------
# 4. DOWNSTREAM CRITICALITY
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 100)
print("PHASE 16 — DOWNSTREAM CRITICALITY")
print("=" * 100)

# Critical material exposure
max_critical_materials = phase16_base["Critical_Materials_Exposed"].max()

if max_critical_materials > 0:
    phase16_base["Critical_Material_Score"] = (
        phase16_base["Critical_Materials_Exposed"] /
        max_critical_materials
    ) * 100
else:
    phase16_base["Critical_Material_Score"] = 0

# Critical asset exposure
max_critical_assets = phase16_base["Critical_Assets_Exposed"].max()

if max_critical_assets > 0:
    phase16_base["Critical_Asset_Score"] = (
        phase16_base["Critical_Assets_Exposed"] /
        max_critical_assets
    ) * 100
else:
    phase16_base["Critical_Asset_Score"] = 0

# Business unit reach
max_business_units = phase16_base["Business_Units_Affected"].max()

if max_business_units > 0:
    phase16_base["Business_Impact_Score"] = (
        phase16_base["Business_Units_Affected"] /
        max_business_units
    ) * 100
else:
    phase16_base["Business_Impact_Score"] = 0

for col in [
    "Critical_Material_Score",
    "Critical_Asset_Score",
    "Business_Impact_Score"
]:
    phase16_base[col] = phase16_base[col].clip(0, 100)

print("✓ Critical material score calculated.")
print("✓ Critical asset score calculated.")
print("✓ Business impact score calculated.")

# --------------------------------------------------------------------------------------------------
# 5. FAILURE RISK COMPONENT
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 100)
print("PHASE 16 — FAILURE RISK COMPONENT")
print("=" * 100)

phase16_base["Failure_Risk_Score"] = (
    phase16_base["Supplier_Failure_Probability"] * 100
)

phase16_base["Failure_Risk_Score"] = (
    phase16_base["Failure_Risk_Score"].clip(0, 100)
)

print("✓ Supplier failure probability converted to 0–100 risk score.")

# --------------------------------------------------------------------------------------------------
# 6. EARLY-WARNING SCORE
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 100)
print("PHASE 16 — EARLY-WARNING SCORE")
print("=" * 100)

# Weighted risk architecture:
#
# Supplier failure risk        = 30%
# Downstream propagation      = 25%
# Financial exposure          = 15%
# Critical material exposure  = 10%
# Critical asset exposure     = 10%
# Business-unit reach         = 10%
#
# Total                       = 100%

phase16_base["Early_Warning_Score"] = (
    0.30 * phase16_base["Failure_Risk_Score"] +
    0.25 * phase16_base["Propagation_Score"] +
    0.15 * phase16_base["Exposure_Score"] +
    0.10 * phase16_base["Critical_Material_Score"] +
    0.10 * phase16_base["Critical_Asset_Score"] +
    0.10 * phase16_base["Business_Impact_Score"]
)

phase16_base["Early_Warning_Score"] = (
    phase16_base["Early_Warning_Score"].clip(0, 100)
)

print("✓ Early-warning score calculated.")
print("✓ Score bounded to 0–100.")

# --------------------------------------------------------------------------------------------------
# 7. EARLY-WARNING CLASSIFICATION
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 100)
print("PHASE 16 — EARLY-WARNING CLASSIFICATION")
print("=" * 100)

def classify_early_warning(score):

    if score >= 75:
        return "Critical Early Warning"

    elif score >= 65:
        return "High Early Warning"

    elif score >= 50:
        return "Emerging Risk"

    elif score >= 35:
        return "Watchlist"

    else:
        return "Low Current Risk"


phase16_base["Early_Warning_Status"] = (
    phase16_base["Early_Warning_Score"]
    .apply(classify_early_warning)
)

print("✓ Early-warning classifications assigned.")

# --------------------------------------------------------------------------------------------------
# 8. RISK DRIVER IDENTIFICATION
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 100)
print("PHASE 16 — RISK DRIVER EXPLANATION")
print("=" * 100)

driver_columns = {
    "Supplier Failure Probability": "Failure_Risk_Score",
    "Downstream Propagation": "Propagation_Score",
    "Financial Exposure": "Exposure_Score",
    "Critical Material Exposure": "Critical_Material_Score",
    "Critical Asset Exposure": "Critical_Asset_Score",
    "Business Unit Reach": "Business_Impact_Score"
}

def identify_primary_driver(row):

    scores = {
        label: row[column]
        for label, column in driver_columns.items()
    }

    return max(scores, key=scores.get)


phase16_base["Primary_Risk_Driver"] = (
    phase16_base.apply(identify_primary_driver, axis=1)
)

print("✓ Primary risk drivers identified.")

# --------------------------------------------------------------------------------------------------
# 9. SECONDARY RISK DRIVER
# --------------------------------------------------------------------------------------------------

def identify_secondary_driver(row):

    scores = sorted(
        {
            label: row[column]
            for label, column in driver_columns.items()
        }.items(),
        key=lambda x: x[1],
        reverse=True
    )

    return scores[1][0]


phase16_base["Secondary_Risk_Driver"] = (
    phase16_base.apply(identify_secondary_driver, axis=1)
)

# --------------------------------------------------------------------------------------------------
# 10. INTERVENTION PRIORITY
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 100)
print("PHASE 16 — INTERVENTION PRIORITY")
print("=" * 100)

def assign_priority(status):

    if status == "Critical Early Warning":
        return 1

    elif status == "High Early Warning":
        return 2

    elif status == "Emerging Risk":
        return 3

    elif status == "Watchlist":
        return 4

    return 5


phase16_base["Intervention_Priority"] = (
    phase16_base["Early_Warning_Status"]
    .apply(assign_priority)
)

phase16_base["Priority_Label"] = (
    phase16_base["Intervention_Priority"]
    .map({
        1: "Immediate",
        2: "High",
        3: "Planned",
        4: "Monitor",
        5: "Routine"
    })
)

print("✓ Intervention priorities assigned.")

# --------------------------------------------------------------------------------------------------
# 11. MANAGEMENT INTERVENTION ENGINE
# --------------------------------------------------------------------------------------------------

def generate_intervention(row):

    status = row["Early_Warning_Status"]
    driver = row["Primary_Risk_Driver"]

    critical_materials = row["Critical_Materials_Exposed"]
    critical_assets = row["Critical_Assets_Exposed"]
    business_units = row["Business_Units_Affected"]
    exposure = row["Outstanding_Value_USD_Exposed"]

    if status == "Critical Early Warning":

        if (
            critical_materials > 0
            or critical_assets > 0
            or business_units >= 3
        ):
            return (
                "Immediate supplier intervention; protect critical materials "
                "and assets; activate contingency sourcing; escalate to "
                "business-unit leadership."
            )

        return (
            "Immediate supplier intervention; review outstanding exposure; "
            "activate contingency planning and senior procurement oversight."
        )

    elif status == "High Early Warning":

        if exposure >= max_exposure * 0.25:
            return (
                "Active supplier monitoring; review major financial exposure; "
                "develop alternative sourcing and recovery options."
            )

        return (
            "Active supplier monitoring; review outstanding orders; "
            "validate supplier recovery plan and contingency options."
        )

    elif status == "Emerging Risk":

        return (
            "Increase supplier monitoring; investigate emerging risk driver; "
            "review material and inventory buffers and prepare mitigation options."
        )

    elif status == "Watchlist":

        return (
            "Maintain enhanced monitoring; track supplier risk indicators "
            "and reassess if failure or propagation risk increases."
        )

    return (
        "Continue routine monitoring and reassess supplier risk at the next "
        "analytical refresh."
    )


phase16_base["Recommended_Intervention"] = (
    phase16_base.apply(generate_intervention, axis=1)
)

print("✓ Recommended interventions generated.")

# --------------------------------------------------------------------------------------------------
# 12. RISK DRIVER EXPLANATION
# --------------------------------------------------------------------------------------------------

def generate_explanation(row):

    supplier = row["Supplier_Name"]
    probability = row["Supplier_Failure_Probability"]
    propagation = row["Propagation_Score"]
    exposure = row["Outstanding_Value_USD_Exposed"]
    materials = row["Materials_Exposed"]
    critical_materials = row["Critical_Materials_Exposed"]
    assets = row["Assets_Exposed"]
    critical_assets = row["Critical_Assets_Exposed"]
    business_units = row["Business_Units_Affected"]
    status = row["Early_Warning_Status"]
    driver = row["Primary_Risk_Driver"]

    probability_pct = probability * 100

    return (
        f"{supplier} is classified as a {status.lower()} with an "
        f"early-warning score of {row['Early_Warning_Score']:.1f}/100. "
        f"The supplier has an estimated failure probability of "
        f"{probability_pct:.0f}%, a downstream propagation score of "
        f"{propagation:.1f}/100 and approximately "
        f"${exposure:,.2f} in outstanding exposure. "
        f"The dependency network covers {materials:.0f} material(s), "
        f"{assets:.0f} asset(s) and {business_units:.0f} business unit(s), "
        f"including {critical_materials:.0f} critical material(s) and "
        f"{critical_assets:.0f} critical asset(s). "
        f"The primary risk driver is {driver.lower()}."
    )


phase16_base["Early_Warning_Explanation"] = (
    phase16_base.apply(generate_explanation, axis=1)
)

print("✓ Explainable early-warning statements generated.")

# --------------------------------------------------------------------------------------------------
# 13. MANAGEMENT ACTION CATEGORY
# --------------------------------------------------------------------------------------------------

def action_category(row):

    driver = row["Primary_Risk_Driver"]

    mapping = {
        "Supplier Failure Probability":
            "Supplier Recovery / Assurance",

        "Downstream Propagation":
            "Operational Continuity",

        "Financial Exposure":
            "Financial / Procurement Risk",

        "Critical Material Exposure":
            "Material Continuity",

        "Critical Asset Exposure":
            "Asset Protection",

        "Business Unit Reach":
            "Enterprise Coordination"
    }

    return mapping.get(driver, "Risk Monitoring")


phase16_base["Management_Action_Category"] = (
    phase16_base.apply(action_category, axis=1)
)

# --------------------------------------------------------------------------------------------------
# 14. URGENCY
# --------------------------------------------------------------------------------------------------

def urgency(row):

    if row["Intervention_Priority"] == 1:
        return "Immediate — 0–7 days"

    elif row["Intervention_Priority"] == 2:
        return "High — 8–30 days"

    elif row["Intervention_Priority"] == 3:
        return "Planned — 31–60 days"

    elif row["Intervention_Priority"] == 4:
        return "Monitor — 61–90 days"

    return "Routine — >90 days"


phase16_base["Action_Urgency"] = (
    phase16_base.apply(urgency, axis=1)
)

# --------------------------------------------------------------------------------------------------
# 15. FINAL RISK PRIORITY SCORE
# --------------------------------------------------------------------------------------------------

# The early-warning score measures risk.
# The final priority score also recognises intervention urgency.

phase16_base["Risk_Priority_Score"] = (
    phase16_base["Early_Warning_Score"]
    .clip(0, 100)
)

# Rank suppliers from highest risk to lowest risk
phase16_base["Risk_Rank"] = (
    phase16_base["Risk_Priority_Score"]
    .rank(method="first", ascending=False)
    .astype(int)
)

# --------------------------------------------------------------------------------------------------
# 16. FINAL MASTER EARLY-WARNING OBJECT
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 100)
print("PHASE 16 — MASTER EARLY-WARNING OBJECT")
print("=" * 100)

phase16_early_warning = (
    phase16_base
    .sort_values(
        ["Intervention_Priority", "Risk_Priority_Score"],
        ascending=[True, False]
    )
    .reset_index(drop=True)
)

print(
    f"Suppliers assessed: "
    f"{phase16_early_warning['Supplier_ID'].nunique()}"
)

print(
    f"Critical early warnings: "
    f"{(phase16_early_warning['Early_Warning_Status'] == 'Critical Early Warning').sum()}"
)

print(
    f"High early warnings: "
    f"{(phase16_early_warning['Early_Warning_Status'] == 'High Early Warning').sum()}"
)

print(
    f"Emerging risks: "
    f"{(phase16_early_warning['Early_Warning_Status'] == 'Emerging Risk').sum()}"
)

# --------------------------------------------------------------------------------------------------
# 17. CRITICAL MANAGEMENT QUEUE
# --------------------------------------------------------------------------------------------------

phase16_critical_queue = (
    phase16_early_warning[
        phase16_early_warning["Intervention_Priority"] <= 2
    ][
        [
            "Risk_Rank",
            "Supplier_ID",
            "Supplier_Name",
            "Supplier_Failure_Probability",
            "Propagation_Score",
            "Outstanding_Value_USD_Exposed",
            "Early_Warning_Score",
            "Early_Warning_Status",
            "Intervention_Priority",
            "Priority_Label",
            "Primary_Risk_Driver",
            "Secondary_Risk_Driver",
            "Management_Action_Category",
            "Action_Urgency",
            "Recommended_Intervention"
        ]
    ]
    .sort_values(
        ["Intervention_Priority", "Risk_Rank"]
    )
    .reset_index(drop=True)
)

# --------------------------------------------------------------------------------------------------
# 18. FULL RISK PRIORITISATION OBJECT
# --------------------------------------------------------------------------------------------------

phase16_risk_prioritisation = (
    phase16_early_warning[
        [
            "Risk_Rank",
            "Supplier_ID",
            "Supplier_Name",
            "Early_Warning_Score",
            "Risk_Priority_Score",
            "Early_Warning_Status",
            "Intervention_Priority",
            "Priority_Label",
            "Primary_Risk_Driver",
            "Secondary_Risk_Driver",
            "Management_Action_Category",
            "Action_Urgency",
            "Supplier_Failure_Probability",
            "Failure_Risk_Score",
            "Propagation_Score",
            "Exposure_Score",
            "Critical_Material_Score",
            "Critical_Asset_Score",
            "Business_Impact_Score",
            "Outstanding_Value_USD_Exposed",
            "Materials_Exposed",
            "Critical_Materials_Exposed",
            "Assets_Exposed",
            "Critical_Assets_Exposed",
            "Business_Units_Affected"
        ]
    ]
    .copy()
)

# --------------------------------------------------------------------------------------------------
# 19. MANAGEMENT ACTION QUEUE
# --------------------------------------------------------------------------------------------------

phase16_management_action_queue = (
    phase16_early_warning[
        [
            "Risk_Rank",
            "Supplier_ID",
            "Supplier_Name",
            "Early_Warning_Status",
            "Intervention_Priority",
            "Priority_Label",
            "Action_Urgency",
            "Primary_Risk_Driver",
            "Management_Action_Category",
            "Outstanding_Value_USD_Exposed",
            "Critical_Materials_Exposed",
            "Critical_Assets_Exposed",
            "Business_Units_Affected",
            "Recommended_Intervention",
            "Early_Warning_Explanation"
        ]
    ]
    .copy()
)

# --------------------------------------------------------------------------------------------------
# 20. BUSINESS UNIT IMPACT
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 100)
print("PHASE 16 — BUSINESS UNIT RISK IMPACT")
print("=" * 100)

# Prefer Phase 15 business-unit impact object where available.
if "phase15_business_unit_impact" in globals():

    phase16_business_unit_impact = (
        phase15_business_unit_impact.copy()
    )

    print("✓ Phase 15 business-unit impact retained for final context.")

else:

    phase16_business_unit_impact = pd.DataFrame()

    print(
        "⚠ Phase 15 business-unit impact object not available; "
        "business-unit impact summary created from supplier aggregation."
    )

# --------------------------------------------------------------------------------------------------
# 21. BUSINESS-UNIT RISK SUMMARY
# --------------------------------------------------------------------------------------------------

# If explicit BU data exists, enrich it with risk concentration from suppliers.
if not phase16_business_unit_impact.empty:

    if "Business_Unit_ID" in phase16_business_unit_impact.columns:

        bu_summary = phase16_business_unit_impact.copy()

        # Preserve existing structure and calculate additional indicators
        if "Outstanding_Value_USD" in bu_summary.columns:

            total_bu_exposure = bu_summary["Outstanding_Value_USD"].sum()

            if total_bu_exposure > 0:
                bu_summary["Exposure_Share"] = (
                    bu_summary["Outstanding_Value_USD"] /
                    total_bu_exposure
                ) * 100
            else:
                bu_summary["Exposure_Share"] = 0

        phase16_business_unit_impact = bu_summary

# --------------------------------------------------------------------------------------------------
# 22. EXECUTIVE RISK SUMMARY
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 100)
print("PHASE 16 — EXECUTIVE RISK SUMMARY")
print("=" * 100)

status_counts = (
    phase16_early_warning["Early_Warning_Status"]
    .value_counts()
)

critical_count = status_counts.get(
    "Critical Early Warning", 0
)

high_count = status_counts.get(
    "High Early Warning", 0
)

emerging_count = status_counts.get(
    "Emerging Risk", 0
)

watchlist_count = status_counts.get(
    "Watchlist", 0
)

low_count = status_counts.get(
    "Low Current Risk", 0
)

critical_exposure = phase16_early_warning.loc[
    phase16_early_warning["Early_Warning_Status"]
    == "Critical Early Warning",
    "Outstanding_Value_USD_Exposed"
].sum()

high_exposure = phase16_early_warning.loc[
    phase16_early_warning["Early_Warning_Status"]
    == "High Early Warning",
    "Outstanding_Value_USD_Exposed"
].sum()

critical_high_exposure = critical_exposure + high_exposure

total_exposure = (
    phase16_early_warning[
        "Outstanding_Value_USD_Exposed"
    ].sum()
)

weighted_risk = (
    (
        phase16_early_warning["Early_Warning_Score"]
        *
        phase16_early_warning["Outstanding_Value_USD_Exposed"]
    ).sum()
    /
    total_exposure
    if total_exposure > 0
    else 0
)

top_driver = (
    phase16_early_warning["Primary_Risk_Driver"]
    .value_counts()
    .idxmax()
    if len(phase16_early_warning) > 0
    else "None"
)

executive_summary_records = [
    ["Reference Date", REFERENCE_DATE.date()],
    ["Suppliers Assessed", phase16_early_warning["Supplier_ID"].nunique()],
    ["Critical Early Warnings", critical_count],
    ["High Early Warnings", high_count],
    ["Emerging Risks", emerging_count],
    ["Watchlist Suppliers", watchlist_count],
    ["Low Current Risk Suppliers", low_count],
    ["Critical Exposure USD", critical_exposure],
    ["High Exposure USD", high_exposure],
    ["Critical + High Exposure USD", critical_high_exposure],
    ["Total Outstanding Exposure USD", total_exposure],
    ["Exposure-Weighted Risk Score", round(weighted_risk, 2)],
    ["Dominant Risk Driver", top_driver]
]

phase16_executive_summary = pd.DataFrame(
    executive_summary_records,
    columns=["Metric", "Value"]
)

print(
    f"Total outstanding exposure: "
    f"${total_exposure:,.2f}"
)

print(
    f"Critical + High exposure: "
    f"${critical_high_exposure:,.2f}"
)

print(
    f"Exposure-weighted risk score: "
    f"{weighted_risk:.2f}/100"
)

print(
    f"Dominant risk driver: "
    f"{top_driver}"
)

# --------------------------------------------------------------------------------------------------
# 23. TOP RISK SUPPLIERS
# --------------------------------------------------------------------------------------------------

phase16_top_risks = (
    phase16_early_warning[
        [
            "Risk_Rank",
            "Supplier_ID",
            "Supplier_Name",
            "Supplier_Failure_Probability",
            "Propagation_Score",
            "Outstanding_Value_USD_Exposed",
            "Early_Warning_Score",
            "Early_Warning_Status",
            "Intervention_Priority",
            "Primary_Risk_Driver",
            "Recommended_Intervention"
        ]
    ]
    .head(20)
    .reset_index(drop=True)
)

# --------------------------------------------------------------------------------------------------
# 24. RISK DISTRIBUTION
# --------------------------------------------------------------------------------------------------

phase16_early_warning_summary = (
    phase16_early_warning[
        [
            "Early_Warning_Status",
            "Supplier_ID"
        ]
    ]
    .groupby("Early_Warning_Status")
    .agg(
        Suppliers=("Supplier_ID", "nunique")
    )
    .reset_index()
)

phase16_early_warning_summary["Exposure_USD"] = (
    phase16_early_warning_summary["Early_Warning_Status"]
    .map(
        phase16_early_warning
        .groupby("Early_Warning_Status")[
            "Outstanding_Value_USD_Exposed"
        ]
        .sum()
    )
    .fillna(0)
)

phase16_early_warning_summary["Average_Risk_Score"] = (
    phase16_early_warning_summary["Early_Warning_Status"]
    .map(
        phase16_early_warning
        .groupby("Early_Warning_Status")[
            "Early_Warning_Score"
        ]
        .mean()
    )
    .fillna(0)
)

# --------------------------------------------------------------------------------------------------
# 25. FINAL VALIDATION
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 100)
print("PHASE 16 — FINAL VALIDATION")
print("=" * 100)

validation_results = []

def add_validation(name, condition):

    validation_results.append({
        "Validation": name,
        "Status": "PASS" if bool(condition) else "FAIL"
    })

add_validation(
    "Supplier population preserved",
    phase16_early_warning["Supplier_ID"].nunique()
    == phase16_base["Supplier_ID"].nunique()
)

add_validation(
    "Supplier IDs unique",
    phase16_early_warning["Supplier_ID"].is_unique
)

add_validation(
    "Early-warning scores within 0–100",
    phase16_early_warning["Early_Warning_Score"].between(0, 100).all()
)

add_validation(
    "Failure risk scores within 0–100",
    phase16_early_warning["Failure_Risk_Score"].between(0, 100).all()
)

add_validation(
    "Propagation scores within 0–100",
    phase16_early_warning["Propagation_Score"].between(0, 100).all()
)

add_validation(
    "Exposure scores within 0–100",
    phase16_early_warning["Exposure_Score"].between(0, 100).all()
)

add_validation(
    "Critical material scores within 0–100",
    phase16_early_warning["Critical_Material_Score"].between(0, 100).all()
)

add_validation(
    "Critical asset scores within 0–100",
    phase16_early_warning["Critical_Asset_Score"].between(0, 100).all()
)

add_validation(
    "Business impact scores within 0–100",
    phase16_early_warning["Business_Impact_Score"].between(0, 100).all()
)

add_validation(
    "Intervention priorities populated",
    phase16_early_warning["Intervention_Priority"].notna().all()
)

add_validation(
    "Early-warning statuses populated",
    phase16_early_warning["Early_Warning_Status"].notna().all()
)

add_validation(
    "Risk drivers populated",
    phase16_early_warning["Primary_Risk_Driver"].notna().all()
)

add_validation(
    "Secondary risk drivers populated",
    phase16_early_warning["Secondary_Risk_Driver"].notna().all()
)

add_validation(
    "Intervention recommendations populated",
    phase16_early_warning["Recommended_Intervention"].notna().all()
)

add_validation(
    "Early-warning explanations populated",
    phase16_early_warning["Early_Warning_Explanation"].notna().all()
)

add_validation(
    "Management action categories populated",
    phase16_early_warning["Management_Action_Category"].notna().all()
)

add_validation(
    "Action urgency populated",
    phase16_early_warning["Action_Urgency"].notna().all()
)

add_validation(
    "No duplicate supplier records",
    not phase16_early_warning["Supplier_ID"].duplicated().any()
)

# Reconciliation with Phase 15 underlying exposure if available
if "supplier_aggregation" in globals():

    phase16_total_exposure = (
        phase16_early_warning[
            "Outstanding_Value_USD_Exposed"
        ].sum()
    )

    phase15_total_exposure = (
        supplier_aggregation[
            "Outstanding_Value_USD_Exposed"
        ].sum()
    )

    exposure_difference = (
        phase16_total_exposure -
        phase15_total_exposure
    )

    add_validation(
        "Phase 16 exposure reconciles to Phase 15",
        np.isclose(
            phase16_total_exposure,
            phase15_total_exposure,
            rtol=1e-9,
            atol=0.01
        )
    )

else:

    exposure_difference = np.nan

phase16_validation_summary = pd.DataFrame(
    validation_results
)

display(phase16_validation_summary)

if not (
    phase16_validation_summary["Status"] == "PASS"
).all():

    failed = phase16_validation_summary[
        phase16_validation_summary["Status"] != "PASS"
    ]

    raise ValueError(
        f"Phase 16 validation failed:\n{failed}"
    )

print("\n✓ All Phase 16 validation checks passed.")

# --------------------------------------------------------------------------------------------------
# 26. FINAL OUTPUT DISPLAY
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 100)
print("PHASE 16 — FINAL RISK PRIORITISATION")
print("=" * 100)

display(phase16_top_risks)

print("\n" + "=" * 100)
print("PHASE 16 — MANAGEMENT ACTION QUEUE")
print("=" * 100)

display(
    phase16_management_action_queue.head(20)
)

print("\n" + "=" * 100)
print("PHASE 16 — EARLY-WARNING DISTRIBUTION")
print("=" * 100)

display(
    phase16_early_warning_summary
)

print("\n" + "=" * 100)
print("PHASE 16 — EXECUTIVE SUMMARY")
print("=" * 100)

display(
    phase16_executive_summary
)

# --------------------------------------------------------------------------------------------------
# 27. FINAL OBJECTS
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 100)
print("PHASE 16 — FINAL OBJECTS")
print("=" * 100)

print("""
phase16_early_warning
phase16_risk_prioritisation
phase16_management_action_queue
phase16_critical_queue
phase16_top_risks
phase16_early_warning_summary
phase16_business_unit_impact
phase16_executive_summary
phase16_validation_summary
""")

# --------------------------------------------------------------------------------------------------
# 28. PERSISTENCE
# --------------------------------------------------------------------------------------------------

print("=" * 100)
print("PHASE 16 — PERSISTENCE")
print("=" * 100)

# Save locally first
output_objects = {
    "phase16_early_warning": phase16_early_warning,
    "phase16_risk_prioritisation": phase16_risk_prioritisation,
    "phase16_management_action_queue": phase16_management_action_queue,
    "phase16_critical_queue": phase16_critical_queue,
    "phase16_top_risks": phase16_top_risks,
    "phase16_early_warning_summary": phase16_early_warning_summary,
    "phase16_business_unit_impact": phase16_business_unit_impact,
    "phase16_executive_summary": phase16_executive_summary,
    "phase16_validation_summary": phase16_validation_summary
}

for object_name, dataframe in output_objects.items():

    if dataframe is not None and isinstance(dataframe, pd.DataFrame):

        print(
            f"✓ {object_name} ready "
            f"{dataframe.shape}"
        )

# --------------------------------------------------------------------------------------------------
# 29. GOOGLE DRIVE PERSISTENCE
# --------------------------------------------------------------------------------------------------

try:

    import os

    KEYSTRA_ROOT = "/content/drive/MyDrive/KEYSTRA_SOLUTION_4"

    folders = {
        "outputs": os.path.join(KEYSTRA_ROOT, "outputs"),
        "validation": os.path.join(KEYSTRA_ROOT, "validation"),
        "models": os.path.join(KEYSTRA_ROOT, "models")
    }

    for folder in folders.values():
        os.makedirs(folder, exist_ok=True)

    # Main analytical outputs
    output_folder = folders["outputs"]

    output_objects["phase16_early_warning"].to_csv(
        os.path.join(
            output_folder,
            "phase16_early_warning.csv"
        ),
        index=False
    )

    output_objects["phase16_risk_prioritisation"].to_csv(
        os.path.join(
            output_folder,
            "phase16_risk_prioritisation.csv"
        ),
        index=False
    )

    output_objects["phase16_management_action_queue"].to_csv(
        os.path.join(
            output_folder,
            "phase16_management_action_queue.csv"
        ),
        index=False
    )

    output_objects["phase16_critical_queue"].to_csv(
        os.path.join(
            output_folder,
            "phase16_critical_queue.csv"
        ),
        index=False
    )

    output_objects["phase16_top_risks"].to_csv(
        os.path.join(
            output_folder,
            "phase16_top_risks.csv"
        ),
        index=False
    )

    output_objects["phase16_early_warning_summary"].to_csv(
        os.path.join(
            output_folder,
            "phase16_early_warning_summary.csv"
        ),
        index=False
    )

    output_objects["phase16_business_unit_impact"].to_csv(
        os.path.join(
            output_folder,
            "phase16_business_unit_impact.csv"
        ),
        index=False
    )

    output_objects["phase16_executive_summary"].to_csv(
        os.path.join(
            output_folder,
            "phase16_executive_summary.csv"
        ),
        index=False
    )

    output_objects["phase16_validation_summary"].to_csv(
        os.path.join(
            folders["validation"],
            "phase16_validation_summary.csv"
        ),
        index=False
    )

    print("✓ Phase 16 outputs saved to Google Drive.")
    print(f"✓ Root: {KEYSTRA_ROOT}")

except Exception as e:

    print(
        "⚠ Google Drive persistence was not completed: "
        f"{e}"
    )

# --------------------------------------------------------------------------------------------------
# 30. FINAL SUMMARY
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 100)
print("PHASE 16 — FINAL SUMMARY")
print("=" * 100)

print(
    f"Suppliers assessed                         : "
    f"{phase16_early_warning['Supplier_ID'].nunique()}"
)

print(
    f"Critical early warnings                   : "
    f"{critical_count}"
)

print(
    f"High early warnings                       : "
    f"{high_count}"
)

print(
    f"Emerging risks                            : "
    f"{emerging_count}"
)

print(
    f"Watchlist suppliers                       : "
    f"{watchlist_count}"
)

print(
    f"Critical exposure (USD)                   : "
    f"{critical_exposure:,.2f}"
)

print(
    f"High exposure (USD)                       : "
    f"{high_exposure:,.2f}"
)

print(
    f"Critical + High exposure (USD)            : "
    f"{critical_high_exposure:,.2f}"
)

print(
    f"Total outstanding exposure (USD)          : "
    f"{total_exposure:,.2f}"
)

print(
    f"Exposure-weighted risk score              : "
    f"{weighted_risk:.2f}"
)

print(
    f"Top risk driver                           : "
    f"{top_driver}"
)

print(
    f"Final risk queue size                     : "
    f"{len(phase16_management_action_queue)}"
)

print(
    f"Critical/high management queue            : "
    f"{len(phase16_critical_queue)}"
)

print(
    f"Phase 15 → Phase 16 exposure difference  : "
    f"{exposure_difference}"
)

print("\n" + "=" * 100)
print("✓ PHASE 16 COMPLETED SUCCESSFULLY")
print("✓ FINAL KEYSTRA ANALYTICAL STAGE")
print("✓ NO PHASE 17 REQUIRED")
print("=" * 100)

====================================================================================================
KEYSTRA — PHASE 16
EARLY-WARNING, RISK PRIORITISATION & MANAGEMENT ACTION ENGINE
FINAL ANALYTICAL STAGE
====================================================================================================

====================================================================================================
PHASE 16 — INPUT VALIDATION
====================================================================================================
✓ supplier_aggregation available (90, 34)
✓ All required Phase 15 columns available.

====================================================================================================
PHASE 16 — EXPOSURE NORMALISATION
====================================================================================================
Maximum supplier exposure: $1,258,141,803.00
✓ Exposure score calculated.

====================================================================================================
PHASE 16 — DOWNSTREAM CRITICALITY
====================================================================================================
✓ Critical material score calculated.
✓ Critical asset score calculated.
✓ Business impact score calculated.

====================================================================================================
PHASE 16 — FAILURE RISK COMPONENT
====================================================================================================
✓ Supplier failure probability converted to 0–100 risk score.

====================================================================================================
PHASE 16 — EARLY-WARNING SCORE
====================================================================================================
✓ Early-warning score calculated.
✓ Score bounded to 0–100.

====================================================================================================
PHASE 16 — EARLY-WARNING CLASSIFICATION
====================================================================================================
✓ Early-warning classifications assigned.

====================================================================================================
PHASE 16 — RISK DRIVER EXPLANATION
====================================================================================================
✓ Primary risk drivers identified.

====================================================================================================
PHASE 16 — INTERVENTION PRIORITY
====================================================================================================
✓ Intervention priorities assigned.
✓ Recommended interventions generated.
✓ Explainable early-warning statements generated.

====================================================================================================
PHASE 16 — MASTER EARLY-WARNING OBJECT
====================================================================================================
Suppliers assessed: 90
Critical early warnings: 1
High early warnings: 10
Emerging risks: 21

====================================================================================================
PHASE 16 — BUSINESS UNIT RISK IMPACT
====================================================================================================
✓ Phase 15 business-unit impact retained for final context.

====================================================================================================
PHASE 16 — EXECUTIVE RISK SUMMARY
====================================================================================================
Total outstanding exposure: $4,049,560,820.94
Critical + High exposure: $1,701,373,908.59
Exposure-weighted risk score: 57.97/100
Dominant risk driver: Downstream Propagation

====================================================================================================
PHASE 16 — FINAL VALIDATION
====================================================================================================

                                  Validation Status
0              Supplier population preserved   PASS
1                        Supplier IDs unique   PASS
2          Early-warning scores within 0–100   PASS
3           Failure risk scores within 0–100   PASS
4            Propagation scores within 0–100   PASS
5               Exposure scores within 0–100   PASS
6      Critical material scores within 0–100   PASS
7         Critical asset scores within 0–100   PASS
8        Business impact scores within 0–100   PASS
9          Intervention priorities populated   PASS
10          Early-warning statuses populated   PASS
11                    Risk drivers populated   PASS
12          Secondary risk drivers populated   PASS
13    Intervention recommendations populated   PASS
14      Early-warning explanations populated   PASS
15    Management action categories populated   PASS
16                  Action urgency populated   PASS
17             No duplicate supplier records   PASS
18  Phase 16 exposure reconciles to Phase 15   PASS

✓ All Phase 16 validation checks passed.

====================================================================================================
PHASE 16 — FINAL RISK PRIORITISATION
====================================================================================================

,Risk_Rank,Supplier_ID,Supplier_Name,Supplier_Failure_Probability,Propagation_Score,Outstanding_Value_USD_Exposed,Early_Warning_Score,Early_Warning_Status,Intervention_Priority,Primary_Risk_Driver,Recommended_Intervention
0,1,S004,Sterling Industrial Equipment Ltd.,0.92,73.135108,1.258142e+09,77.520141,Critical Early Warning,1,Financial Exposure,Immediate supplier intervention; protect criti...
1,2,S054,Industrial Supply Partners Ltd.,0.92,90.021108,4.481707e+07,72.912329,High Early Warning,2,Business Unit Reach,Active supplier monitoring; review outstanding...
2,3,S055,Process Materials Solutions Ltd.,0.99,84.590623,1.563864e+08,71.575784,High Early Warning,2,Business Unit Reach,Active supplier monitoring; review outstanding...
3,4,S087,Continental Industrial Services Ltd.,0.99,91.844688,5.911916e+07,70.911465,High Early Warning,2,Supplier Failure Probability,Active supplier monitoring; review outstanding...
4,5,S058,Nexus Industrial Supply Ltd.,0.99,85.965978,3.416498e+07,70.462458,High Early Warning,2,Business Unit Reach,Active supplier monitoring; review outstanding...
5,6,S081,SunCore Energy Technologies Ltd.,0.99,94.915948,3.164564e+07,68.851732,High Early Warning,2,Supplier Failure Probability,Active supplier monitoring; review outstanding...
6,7,S019,Powerlink Industrial Systems Ltd.,0.80,78.773283,4.687244e+07,67.433968,High Early Warning,2,Business Unit Reach,Active supplier monitoring; review outstanding...
7,8,S025,Brightline Electrical Industries Ltd.,0.99,67.815101,7.532684e+06,67.425401,High Early Warning,2,Business Unit Reach,Active supplier monitoring; review outstanding...
8,9,S035,Advanced Process Instruments Ltd.,0.98,81.410060,2.190585e+06,66.642268,High Early Warning,2,Supplier Failure Probability,Active supplier monitoring; review outstanding...
9,10,S033,ProSense Industrial Controls Ltd.,0.64,81.627293,5.877389e+07,66.489364,High Early Warning,2,Critical Material Exposure,Active supplier monitoring; review outstanding...
10,11,S018,Crown Electrical Technologies Ltd.,0.97,85.290845,1.729316e+06,65.897874,High Early Warning,2,Business Unit Reach,Active supplier monitoring; review outstanding...
11,12,S017,VoltEdge Engineering Ltd.,0.63,70.922295,1.034430e+07,64.253902,Emerging Risk,3,Critical Asset Exposure,Increase supplier monitoring; investigate emer...
12,13,S013,Westfield Industrial Engineering Ltd.,0.98,86.206495,9.311741e+05,63.508180,Emerging Risk,3,Supplier Failure Probability,Increase supplier monitoring; investigate emer...
13,14,S089,Nexus Energy Equipment Solutions Ltd.,0.90,84.570187,2.887152e+06,63.449696,Emerging Risk,3,Supplier Failure Probability,Increase supplier monitoring; investigate emer...
14,15,S009,Ironbridge Equipment Solutions Ltd.,0.99,67.724995,1.020968e+07,62.707518,Emerging Risk,3,Supplier Failure Probability,Increase supplier monitoring; investigate emer...
15,16,S047,DeltaFlow Technologies Ltd.,0.90,91.803405,4.562273e+08,61.708332,Emerging Risk,3,Downstream Propagation,Increase supplier monitoring; investigate emer...
16,17,S001,Apex Rotating Systems Ltd.,0.93,92.093899,3.299047e+07,59.634980,Emerging Risk,3,Supplier Failure Probability,Increase supplier monitoring; investigate emer...
17,18,S030,Axis Process Controls Ltd.,0.98,80.440263,5.298082e+05,58.743655,Emerging Risk,3,Supplier Failure Probability,Increase supplier monitoring; investigate emer...
18,19,S003,Atlas Turbomachinery Services Ltd.,0.99,68.250236,1.725882e+07,58.195597,Emerging Risk,3,Supplier Failure Probability,Increase supplier monitoring; investigate emer...
19,20,S010,Pinnacle Machinery Services Ltd.,0.99,63.606299,1.475236e+06,57.255527,Emerging Risk,3,Supplier Failure Probability,Increase supplier monitoring; investigate emer...

====================================================================================================
PHASE 16 — MANAGEMENT ACTION QUEUE
====================================================================================================

,Risk_Rank,Supplier_ID,Supplier_Name,Early_Warning_Status,Intervention_Priority,Priority_Label,Action_Urgency,Primary_Risk_Driver,Management_Action_Category,Outstanding_Value_USD_Exposed,Critical_Materials_Exposed,Critical_Assets_Exposed,Business_Units_Affected,Recommended_Intervention,Early_Warning_Explanation
0,1,S004,Sterling Industrial Equipment Ltd.,Critical Early Warning,1,Immediate,Immediate — 0–7 days,Financial Exposure,Financial / Procurement Risk,1.258142e+09,2.0,4.0,4.0,Immediate supplier intervention; protect criti...,Sterling Industrial Equipment Ltd. is classifi...
1,2,S054,Industrial Supply Partners Ltd.,High Early Warning,2,High,High — 8–30 days,Business Unit Reach,Enterprise Coordination,4.481707e+07,2.0,8.0,5.0,Active supplier monitoring; review outstanding...,Industrial Supply Partners Ltd. is classified ...
2,3,S055,Process Materials Solutions Ltd.,High Early Warning,2,High,High — 8–30 days,Business Unit Reach,Enterprise Coordination,1.563864e+08,1.0,7.0,5.0,Active supplier monitoring; review outstanding...,Process Materials Solutions Ltd. is classified...
3,4,S087,Continental Industrial Services Ltd.,High Early Warning,2,High,High — 8–30 days,Supplier Failure Probability,Supplier Recovery / Assurance,5.911916e+07,2.0,5.0,4.0,Active supplier monitoring; review outstanding...,Continental Industrial Services Ltd. is classi...
4,5,S058,Nexus Industrial Supply Ltd.,High Early Warning,2,High,High — 8–30 days,Business Unit Reach,Enterprise Coordination,3.416498e+07,1.0,7.0,5.0,Active supplier monitoring; review outstanding...,Nexus Industrial Supply Ltd. is classified as ...
5,6,S081,SunCore Energy Technologies Ltd.,High Early Warning,2,High,High — 8–30 days,Supplier Failure Probability,Supplier Recovery / Assurance,3.164564e+07,1.0,5.0,4.0,Active supplier monitoring; review outstanding...,SunCore Energy Technologies Ltd. is classified...
6,7,S019,Powerlink Industrial Systems Ltd.,High Early Warning,2,High,High — 8–30 days,Business Unit Reach,Enterprise Coordination,4.687244e+07,2.0,9.0,5.0,Active supplier monitoring; review outstanding...,Powerlink Industrial Systems Ltd. is classifie...
7,8,S025,Brightline Electrical Industries Ltd.,High Early Warning,2,High,High — 8–30 days,Business Unit Reach,Enterprise Coordination,7.532684e+06,1.0,9.0,5.0,Active supplier monitoring; review outstanding...,Brightline Electrical Industries Ltd. is class...
8,9,S035,Advanced Process Instruments Ltd.,High Early Warning,2,High,High — 8–30 days,Supplier Failure Probability,Supplier Recovery / Assurance,2.190585e+06,1.0,7.0,4.0,Active supplier monitoring; review outstanding...,Advanced Process Instruments Ltd. is classifie...
9,10,S033,ProSense Industrial Controls Ltd.,High Early Warning,2,High,High — 8–30 days,Critical Material Exposure,Material Continuity,5.877389e+07,4.0,9.0,4.0,Active supplier monitoring; review outstanding...,ProSense Industrial Controls Ltd. is classifie...
10,11,S018,Crown Electrical Technologies Ltd.,High Early Warning,2,High,High — 8–30 days,Business Unit Reach,Enterprise Coordination,1.729316e+06,0.0,6.0,5.0,Active supplier monitoring; review outstanding...,Crown Electrical Technologies Ltd. is classifi...
11,12,S017,VoltEdge Engineering Ltd.,Emerging Risk,3,Planned,Planned — 31–60 days,Critical Asset Exposure,Asset Protection,1.034430e+07,3.0,11.0,5.0,Increase supplier monitoring; investigate emer...,VoltEdge Engineering Ltd. is classified as a e...
12,13,S013,Westfield Industrial Engineering Ltd.,Emerging Risk,3,Planned,Planned — 31–60 days,Supplier Failure Probability,Supplier Recovery / Assurance,9.311741e+05,0.0,5.0,4.0,Increase supplier monitoring; investigate emer...,Westfield Industrial Engineering Ltd. is class...
13,14,S089,Nexus Energy Equipment Solutions Ltd.,Emerging Risk,3,Planned,Planned — 31–60 days,Supplier Failure Probability,Supplier Recovery / Assurance,2.887152e+06,0.0,8.0,4.0,Increase supplier monitoring; investigate emer...,Nexus Energy Equipment Solutions Ltd. is class...
14,15,S009,Ironbridge Equipment Solutions Ltd.,Emerging Risk,3,Planned,Planned — 31–60 days,Supplier Failure Probability,Supplier Recovery / Assurance,1.020968e+07,1.0,6.0,4.0,Increase supplier monitoring; investigate emer...,Ironbridge Equipment Solutions Ltd. is classif...
15,16,S047,DeltaFlow Technologies Ltd.,Emerging Risk,3,Planned,Planned — 31–60 days,Downstream Propagation,Operational Continuity,4.562273e+08,1.0,2.0,1.0,Increase supplier monitoring; investigate emer...,DeltaFlow Technologies Ltd. is classified as a...
16,17,S001,Apex Rotating Systems Ltd.,Emerging Risk,3,Planned,Planned — 31–60 days,Supplier Failure Probability,Supplier Recovery / Assurance,3.299047e+07,1.0,2.0,2.0,Increase supplier monitoring; investigate emer...,Apex Rotating Systems Ltd. is classified as a ...
17,18,S030,Axis Process Controls Ltd.,Emerging Risk,3,Planned,Planned — 31–60 days,Supplier Failure Probability,Supplier Recovery / Assurance,5.298082e+05,1.0,3.0,2.0,Increase supplier monitoring; investigate emer...,Axis Process Controls Ltd. is classified as a ...
18,19,S003,Atlas Turbomachinery Services Ltd.,Emerging Risk,3,Planned,Planned — 31–60 days,Supplier Failure Probability,Supplier Recovery / Assurance,1.725882e+07,1.0,3.0,3.0,Increase supplier monitoring; investigate emer...,Atlas Turbomachinery Services Ltd. is classifi...
19,20,S010,Pinnacle Machinery Services Ltd.,Emerging Risk,3,Planned,Planned — 31–60 days,Supplier Failure Probability,Supplier Recovery / Assurance,1.475236e+06,0.0,4.0,4.0,Increase supplier monitoring; investigate emer...,Pinnacle Machinery Services Ltd. is classified...

====================================================================================================
PHASE 16 — EARLY-WARNING DISTRIBUTION
====================================================================================================

     Early_Warning_Status  Suppliers  Exposure_USD  Average_Risk_Score
0  Critical Early Warning          1  1.258142e+09           77.520141
1           Emerging Risk         21  6.975671e+08           56.310397
2      High Early Warning         10  4.432321e+08           68.860264
3        Low Current Risk         24  5.112590e+08           22.198113
4               Watchlist         34  1.139361e+09           43.569615

====================================================================================================
PHASE 16 — EXECUTIVE SUMMARY
====================================================================================================

                            Metric                   Value
0                   Reference Date              2026-07-31
1               Suppliers Assessed                      90
2          Critical Early Warnings                       1
3              High Early Warnings                      10
4                   Emerging Risks                      21
5              Watchlist Suppliers                      34
6       Low Current Risk Suppliers                      24
7            Critical Exposure USD            1258141803.0
8                High Exposure USD            443232105.59
9     Critical + High Exposure USD           1701373908.59
10  Total Outstanding Exposure USD           4049560820.94
11    Exposure-Weighted Risk Score                   57.97
12            Dominant Risk Driver  Downstream Propagation

====================================================================================================
PHASE 16 — FINAL OBJECTS
====================================================================================================

phase16_early_warning
phase16_risk_prioritisation
phase16_management_action_queue
phase16_critical_queue
phase16_top_risks
phase16_early_warning_summary
phase16_business_unit_impact
phase16_executive_summary
phase16_validation_summary

====================================================================================================
PHASE 16 — PERSISTENCE
====================================================================================================
✓ phase16_early_warning ready (90, 51)
✓ phase16_risk_prioritisation ready (90, 25)
✓ phase16_management_action_queue ready (90, 15)
✓ phase16_critical_queue ready (11, 15)
✓ phase16_top_risks ready (20, 11)
✓ phase16_early_warning_summary ready (5, 4)
✓ phase16_business_unit_impact ready (5, 11)
✓ phase16_executive_summary ready (13, 2)
✓ phase16_validation_summary ready (19, 2)
✓ Phase 16 outputs saved to Google Drive.
✓ Root: /content/drive/MyDrive/KEYSTRA_SOLUTION_4

====================================================================================================
PHASE 16 — FINAL SUMMARY
====================================================================================================
Suppliers assessed                         : 90
Critical early warnings                   : 1
High early warnings                       : 10
Emerging risks                            : 21
Watchlist suppliers                       : 34
Critical exposure (USD)                   : 1,258,141,803.00
High exposure (USD)                       : 443,232,105.59
Critical + High exposure (USD)            : 1,701,373,908.59
Total outstanding exposure (USD)          : 4,049,560,820.94
Exposure-weighted risk score              : 57.97
Top risk driver                           : Downstream Propagation
Final risk queue size                     : 90
Critical/high management queue            : 11
Phase 15 → Phase 16 exposure difference  : -9.5367431640625e-07

====================================================================================================
✓ PHASE 16 COMPLETED SUCCESSFULLY
✓ FINAL KEYSTRA ANALYTICAL STAGE
✓ NO PHASE 17 REQUIRED
====================================================================================================